### ISSUE TITLE
[Feature request] Getting the extra part of composer.json from a installed package

### ISSUE THREAD

**Issue by shyim** [composer/composer#10004]
Hey,

since Composer 2.1 we can use `getInstalledPackagesByType` to get all installed packages from specific type. That's nice, but we can get only information like package name, package version, installed path. 
To have an automatic lookup and registration of extensions of a system the systems would need also the `extra` part of the composer.json. This information is currently not accessible using the InstalledVersions.

## Example bolt extensions

Bolt extensions save into extra the bolt-class which class should be constructed (https://github.com/bolt/boltforms/blob/4.2/composer.json#L53). 
Currently, the only way is to read the `composer.lock` of the project or read the single composer.json by own using the new installed path method.  I guess it would be a great addition to InstalledVersions when such information could be also provided.

**Comment by Seldaek** [comment]
- Reading composer.lock is a bad idea, as it may not match what is installed
- Reading composer.json in install path is okish but still not great idea as it also may not strictly match what the package metadata contained (although this is more of an edge case situation)
- The best way to get the info is to read vendor/composer/installed.json, loop over packages array and find the one you are interested in by name, then you can get extra info.

IMO the last point is key here, and your best bet to implement this feature if you need extra information. I don't really think InstalledVersions should give access to the entire package data, as it is already there in installed.json, and that file has a stable format that you can rely on to be BC.

Alternatively you could say if package install path contains a `bolt-extension.php` file you will include this to bootstrap it for example, so that could contain a `<?php return new ExtensionClass(...)`. That way you rely less on extra data, and don't need installed.json, and can simply include files which can be then stored in opcache etc.

**Comment by stof** [comment]
>     * Reading composer.json in install path is okish but still not great idea as it also may not strictly match what the package metadata contained (although this is more of an edge case situation)

also, there is nothing enforcing that this composer.json actually exist. Composer does not require you to keep it in the archive.
