### ISSUE TITLE
Shallow git clone to target location (and utilize cache as full repo source)

### ISSUE THREAD

**Issue by mvorisek** [composer/composer#10074]
This is a feature request to improve git performace and save disk space with git repos.

Currently, all git cloning is done thru cache. This is perfect and it seems, as discussed in https://github.com/composer/composer/issues/3449 (and some other related issues), one full git clone is always needed. However the cached repo is 1:1 mirrored to the target install location, which requires twice the space and is time consuming with repos with long history or big removed files.

Example of such repos are:
- [git@github.com:PrestaShop/PrestaShop.git](git@github.com:PrestaShop/PrestaShop.git)
- [git@github.com:phpstan/phpstan.git](git@github.com:phpstan/phpstan.git)

This is a feature request to always determine the exact sha to clone againt the single local cached copy and then mirror/fetch the exactly sha to the install target location only.

Updating the target shallowly (eg. git fetch) is possible since git 2.5 (2015), ref https://stackoverflow.com/questions/14872486/retrieve-specific-commit-from-a-remote-git-repository/30701724#30701724

**Comment by Seldaek** [comment]
Since 2.1 we don't ever clone by default anymore, even for dev versions, so I don't think this is super urgent or beneficial as the amount of clones happening is pretty low, and I'd even argue if you do request a clone you most likely will want the full history of the repo to work with it, so it might even be counter productive to optimize this away.

**Comment by AngryUbuntuNerd** [comment]
just ran into this problem, using composer 2.1.14

for example, installing `phpunit/php-file-iterator` version 1.4.5 takes 18M disk space, of which 16K (!) are the source code files, the rest 99,X% is `.git`

causing issues for our CI (and wastes space locally)

**Comment by Seldaek** [comment]
Closing as I don't see the point as per my comment above.

**Comment by computator** [comment]
I think this should be added to be enabled with an optional parameter. Many packages use dists yes, but for ones that only have a repository as a source it still uses the full git history in both the cache and the target. If using it with a dev environment where you want to edit the packages that's great, but for CI, building containers, or other things like that it's counterproductive to have the entire repository in the target directory.

If `composer update` or another command somehow removes the `.git` directories from the target (as mentioned above) that would work for some situations, however I have been unable to duplicate this.

**Comment by mvorisek** [comment]
@Seldaek would it be ok with you to reopen this issue? Fo CI purposes, we need shallow clone - we have large dependencies and can access them thru git only. Currently, whole repo needs to be cloned, which is several orders of magnitude slower than shallow clone.

**Comment by Seldaek** [comment]
Sorry but I am not so inclined to bear the cost of maintenance for this edge case, and add even more complexity to GitDownloader (which is already a horrible mess of mostly untested edge cases).

I would recommend using [Private Packagist](https://packagist.com/) or similar to host the private packages in a way that they can be installed as regular packages. It tends to make everything faster and smoother anyway, and should help more than just your CI.

**Comment by NickSdot** [comment]
@Seldaek as others mentioned, this is not only about performance.

I'd like to add another example. [`cebe/php-openapi` is using `apis-guru/openapi-directory`](https://github.com/cebe/php-openapi/blob/020d72b8e3a9a60bc229953e93eda25c49f46f45/composer.json#L79C1-L79C1) to get testing data. The actual data is ~105 MB, and `.git` is **~740 MB.** This version version was cloned in August. 

![image](https://github.com/composer/composer/assets/32384907/353ea6ea-c719-42d0-9f57-a302eed9f201)

To send this comment here I did a new clone to check how much it grew since then. Now, only about two months later, the `.git` folder of the project now is 16 MB more, **~760 MB**.

![image](https://github.com/composer/composer/assets/32384907/41ee28e7-8a7b-4c15-b38b-666264cea77d)

This is one single repo. Size adds up, when you work on and with a lot of stuff. 
I also would appreciate if you would consider to re-open this issue. ❤️

**Comment by Seldaek** [comment]
@NickSdot and the reason there is a clone is that the packages are defined inline as having only a git source to install. If a dist was defined with the zipball URL from github then this dependency would be downloaded as a zip and all would be well. Again, I don't see the need to bear the cost of maintaining this because others have unreasonable expectations.

**Comment by mvorisek** [comment]
@Seldaek I am the author of this issue and in some scenarios/repos, the size/time different can be even 100 times (realistically, theoretically nearly unlimited). In our usecase, it will reduce about 4 GB download to 40 MB. The improvement will be huge and it will save us also our SSD cells - we currently, sadly need to download/store the whole 4GB in CI daily many times.

I would be happy if this issue can be at least kept open, as it should be possible when the dep constraints are like `dev-xxx` (branch) or `dev-xxx#hash as 1.0` (specific commit).

**Comment by mvorisek** [comment]
@Seldaek can you please keep this issue open. I actually think this is solveable by using git sparse checkout to allow still clone all `composer.json` versions for all tags. This will massively lower the data needed to be downloaded for dependency solved. Once an installable version/commit is resolved, only this commit needs to be fully downloaded.

**Comment by kdambekalns** [comment]
Found this while looking into an unexpected use of disk space… My use-case is this:

Have a root manifest with (shortened):

```yaml
{
  "config": {
    "preferred-install": {
      "acme/stuff-compiled": "dist",
      "acme/*": "source"
    },
  },
  "require": {
    "acme/foo": "1.2.x-dev",
    "acme/stuff-compiled": "1.0.x-dev"
  }
}
```

I want this specific package `acme/stuff-compiled` without the history. But even though I override `preferred-install` a full clone is done (about 1 GB) instead of the needed 23 MB. That is a massive difference (and it takes ages to "clone the cache", annoying even if it only happens the first time)!

I would expect a `preferred-install` of `dist` whould work even for `1.0.x-dev`, as GitHub provides archive downloads for "anything". Or am I wrong here? At least I can successfully download `https://github.com/username/repository/archive/COMMIT_HASH.zip` for my case…

So, is this possible? That would be so awesome!

**Comment by Seldaek** [comment]
@kdambekalns please  report a new issue with a complete json unaltered if possible.. Pretty sure that dist install should work for you

**Comment by kdambekalns** [comment]
Will do… leaving this here for completeness, though:

My test ended like this:

```
Package operations: 1 install, 0 updates, 0 removals
  - Syncing acme/stuff-compiled (1.0.x-dev e5bcc0e) into cache
    Failed to download acme/stuff-compiled from source: The process "'git' 'clone' '--mirror' '--' 'https://github.com/acme/stuff-compiled.git' '/Users/karsten/Library/Caches/composer/vcs/https---github.com-acme-stuff-compiled.git/'" exceeded the timeout of 300 seconds.
    Now trying to download from dist
  - Downloading acme/stuff-compiled (8.3.x-dev e5bcc0e)
  - Installing acme/stuff-compiled (8.3.x-dev e5bcc0e): Extracting archive
```

So it **can** download from archive, it just doesn't seem to try it first. 🙄

**Comment by kdambekalns** [comment]
New issue: https://github.com/composer/composer/issues/12310
