### ISSUE TITLE
Debug output add where authentication was loaded from

### ISSUE THREAD

**Issue by glaubinix** [composer/composer#10085]
Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: You are not running the latest stable version, run `composer self-update` to update (2.1.5 => 2.1.6)
Composer version: 2.1.5
PHP version: 7.4.19
PHP binary path: /usr/local/Cellar/php@7.4/7.4.19_1/bin/php
OpenSSL version: OpenSSL 1.1.1k  25 Mar 2021
cURL version: 7.77.0 libz 1.2.11 ssl (SecureTransport) OpenSSL/1.1.1k
zip: extension present, unzip present, 7-Zip not available
```

When I run this command: 

```
any command with -vvv that does HTTP requests e.g. composer oudated -vvv
```

I get the following output: 

```
Reading ./composer.json (/Users/glaubinix/Projects/example/composer.json)
Loading config file /Users/glaubinix/.composer/config.json
Loading config file /Users/glaubinix/.composer/auth.json
Loading config file ./composer.json (/Users/glaubinix/Projects/example/composer.json)
Loading config file /Users/glaubinix/Projects/example/auth.json
Reading /Users/glaubinix/Projects/example/auth.json
Checked CA file /usr/local/etc/openssl@1.1/cert.pem: valid
Executing command (/Users/glaubinix/Projects/example): git branch -a --no-color --no-abbrev -v
Reading /Users/glaubinix/.composer/composer.json
Loading config file /Users/glaubinix/.composer/config.json
Loading config file /Users/glaubinix/.composer/auth.json
Loading config file /Users/glaubinix/.composer/composer.json (/Users/glaubinix/.composer/composer.json)
Loading config file /Users/glaubinix/.composer/auth.json
Reading /Users/glaubinix/.composer/auth.json
Reading /Users/glaubinix/Projects/example/vendor/composer/installed.json
Running 2.1.5 (2021-07-23 10:35:47) with PHP 7.4.19 on Darwin / 20.6.0
Using HTTP basic authentication with username "glaubinix"
```

And I expected this to happen:

Composer lists several files that are loaded which can contain authentication. For the first request for every host It later displays the username that is used for authentication. However based on the output it is not obvious from which file or ENV the authentication was loaded. Having an idea where the authentication was loaded from can help:
* find where it is store and delete unwanted/outdated authentication
* debug as the order in which authentication is loaded/applied is not 100% clear from the output

Was thinking similar to:

`Using HTTP basic authentication with username "glaubinix" from COMPOSER_AUTH`

or 

`Using HTTP basic authentication with username "glaubinix" from /Users/glaubinix/.composer/auth.json`

**Comment by Seldaek** [comment]
This is really quite tricky to do IMO, or well it'd have to impact lots of places to keep track of this completely, and I then wonder if it'd be really worth it. The COMPOSER_AUTH stuff gets merged into the Config instance, which is also getting the various config files merged in, and then it's finally all loaded at once in the BaseIO.

So one option I see to perhaps improve things is taking this warning here https://github.com/composer/composer/blob/5b16d61762579fcd86507292789f1c92432d9e8b/src/Composer/IO/BaseIO.php#L99-L104

And duplicating it into [Config::merge](https://github.com/composer/composer/blob/5b16d61762579fcd86507292789f1c92432d9e8b/src/Composer/Config.php#L135) so that it warns (in debug output only) if merging overwrites some auth value. Except merge() doesn't have access to the $io object.. so it's also not super doable, except perhaps buffering those warnings and then retrieving/outputting them once BaseIO::loadConfiguration is called? And merge() would need to accept a $source parameter too that'd allow to know where something came from.

Overall not sure it's worth it :)

**Comment by glaubinix** [comment]
As discussed, simpler alternative would be to have `composer config foo.bar --source` which then outputs where that particular config was loaded from. Config class would have to keep track of the source of every config value it has.
