### ISSUE TITLE
Composer2 package priority conflict

### ISSUE THREAD

**Issue by typoworx-de** [composer/composer#10096]
After migrating from composer1 I have some problems migrating my existing workflow. I'm using public repository, private repository (using gitlab.com) and additionally a vendor.local path-repository to develop/test changes that are not yet available in private repository due to development.

My composer.json's repository sections looks as follows:
```
  "repositories": [
    {
      "type": "composer",
      "url": "https://composer.typo3.org/"
    },
    {
      "type": "composer",
      "only": ["myvendor/*"],
      "url": "https://___token___:{my-private-token}@gitlab.com/api/v4/group/{my-group-id}/-/packages/composer/packages.json"
    },
    {
      "type": "path",
      "url": "./vendor.local/*",
      "only": ["myvendor/*"],
      "options": {
        "symlink": true
      }
    }
  ]
```
installing for example the following package:
> myvendor/foobar

**Expected behaviour**
I would expect it will be installed from private gitlab-repository (2nd one) instead of the fact the private repository also has a version.

**Current result**
The package is always being installed from private online repository instead than from vendor.local path repository.

Even trying to flag the package as follows always installs the 'online' version from repository. The local version has some changes to be tested bevor being applied to the online-repository.
myvendor/foobar:dev-master||^1.0.0

**Comment by typoworx-de** [comment]
I already know the canonical-flag, but in no combination I was able to resolve my problem with that. I would suggest some kind of numeric priority-flag (f.e. ```priority: 10```) to resolve such behaviour.

I already tried to change the ordering of repositores, but those don't seem to make any change to the final result at all.

**Comment by Seldaek** [comment]
I don't understand what your "expected behavior" sentence means, so I may be confused here.. But if you want the path repo to take precedence it needs to be above the gitlab repo, at least if the version required exists in both repos.

If you explicitly require a version that only exists in the path repo, then with canonical:false on the gitlab repo it will allow it to go down to the lower prio path repo to find a version that matches.

I suspect you would be better off using something like https://github.com/franzliedke/studio though than a path repo in this case, as it seems you want it only sometimes.

**Comment by typoworx-de** [comment]
Thanks for reploy @Seldaek. Sorry if there was some confusion about "expected behaviour". But I think you understood it correctly. I expected my local-vendor path to be the prefered one. I'll give it a try with suggested setup -- nevertheless I'm shure I already tried nearly every possible combination with 3 repo's and canonical:false already.

I also will have a look into the suggested tool and leave feedback if one of these will help to resolve the given problem.
