### ISSUE TITLE
Alias must be supported with OR dependency operator

### ISSUE THREAD

**Issue by mvorisek** [composer/composer#10134]
Example composer file:

```
{
    "require-dev": {
        "behat/mink": "^1.8.2 || dev-master as 1.8.99"
    }
}
```

It is an alias for an exact version. It must be supported the same way as if the rule will be without the `^1.8.2 || ` part.

Currently, the following exception is thrown by composer:
```
Invalid alias definition in "behat/mink": "^1.8.2 || dev-master as 1.8.99".
Aliases should be in the form "exact-version as other-exact-version".  
```

Required to support configurations like - both versions are not released yet, and it is the only way to fix PHP 8.1 lowest install:
```
{
    "require-dev": {
        "behat/behat": "^3.8.2 || dev-master",
        "behat/gherkin": "^4.8.1 || dev-master as 4.8.99"
    }
}
```

which prints currently (without the alias):
```
  Problem 1
    - behat/behat dev-master requires behat/gherkin ^4.8.0 -> found behat/gherkin[v4.8.0] but it conflicts with your root composer.json require (^4.8.1 || dev-master).
    - behat/behat 3.8.x-dev is an alias of behat/behat dev-master and thus requires it to be installed too.
    - Root composer.json requires behat/behat ^3.8.2 || dev-master -> satisfiable by behat/behat[dev-master, 3.8.x-dev (alias of dev-master)].
```

**Comment by stof** [comment]
Version aliases are not something that happens inside a constraint. It is something that configures the solver. So your case is not really saying `^1.8.2` OR `dev-master as 1.8.99`. What is being aliased is `^1.8.2 || dev-master`.
Think about it as a precedence issue between `||` and `as` (except it is more complex than that, because aliases cannot be nested in parenthesis to change the precedence, as the are not actually part of the constraint itself)

**Comment by mvorisek** [comment]
If the rule consists of multiple subrules separated by OR, it should be possible to alias each (exact-version) subrule. No change in the solved should be required.

Example test case `^1.4 || dev-2.x as 2.99 || dev-3.x as 3.99`.

**Comment by stof** [comment]
no it is not, at least not without rewriting composer.

What the alias does is installing that version, but making the solver consider that the aliased version is used. But that implies that we cannot let the solver choose a different version (otherwise, it is not actually installed).

Note that your use case looks weird to me. `behat/behat` already aliases the dev-master branch version to `3.8.x-dev`, which means that it will satisfy the `^3.8.2` constraint if your minimum-stability allows to use a dev version (either through the general stability config, or through the `@dev` suffix on the constraint in the root package).

**Comment by mvorisek** [comment]
> What the alias does is installing that version, but making the solver consider that the aliased version is used. But that implies that we cannot let the solver choose a different version (otherwise, it is not actually installed).

is there any reason to not alias the exact version before it is passed to the solver? **The solver must support it as branch aliasing on the package side already supports it.**

> Note that your use case looks weird to me. `behat/behat` already aliases the dev-master branch version to `3.8.x-dev`, which means that it will satisfy the `^3.8.2` constraint if your minimum-stability allows to use a dev version (either through the general stability config, or through the `@dev` suffix on the constraint in the root package).

```
        "behat/behat": "^3.8.2 || dev-master",
        "behat/gherkin": "^4.8.1 || dev-master"
```

I retested this and I confirm the install exception. I think it is because https://github.com/Behat/Gherkin/blob/v4.8.0/composer.json#L45 . With this feature request, the 3rd party package issue can be solved easily.

**Comment by Seldaek** [comment]
Providing that upstream gives you correct branch-aliases, you can simplify these constraints to:

```
        "behat/behat": "^3.8.2@dev",
        "behat/gherkin": "^4.8.1@dev"
```

Which is much better as it does not specify dev-master, so once dev-master changes to be targetting 5.x-dev in the future, you won't run into problems.

All in all I don't think this feature is worth adding, and I am not sure it is feasible at all as stof mentioned.
