### ISSUE TITLE
[Feature] Use a .lock directory instead of a .lock file with a main.json and individual files for the list entries

### ISSUE THREAD

**Issue by LionsAd** [composer/composer#10266]
### Motivation

On composer based projects the main source of conflicts is in composer.lock. Especially if working with patches and many upstream libraries it can be a real pain and a source of frustration.

### Proposed resolution

Use a .lock directory with the following structure:

```
.lock/main.json
.lock/drupal/drupal.json
.lock/drupal/ctools.json
.lock/symfony/http-foundation.json
```

I tried this out in practice (without composer but using information from the .lock file) and we had zero conflicts in all the time we've used this. While a directory-scan can take a little bit longer than a direct lookup, the time has been neglectable in my experience.

This also makes it much easier to see what has been updated just by glancing at the list of changed files in e.g. github :).

### Implementation idea

- Change the current LockFile class to allow usage of a LockDirectory class instead
- Support both formats and do a simple is_file() vs. is_directory() check to use the right class
- Allow to convert from one to the other

Again this can be considered as a RFC.

### Trivia

I wanted to start https://github.com//lock-directory/ and become famous ;) by bringing this idea to all projects out there, but figured I'd better start with composer first ;).

**Comment by naderman** [comment]
I think the main problem with this is a misunderstanding of how a lock file can be "merged". While splitting it into lots of separate files makes git merge the contents of the directory without problems, it will lead to broken lock files in many situations. At https://naderman.de/slippy/slides/2018-01-26-composer-lock-demystified.pdf you can find the slides of a talk I've given on this subject which explains why text based merging of the lock file is a bad idea and how to correctly regenerate a lock file for merges.

The underlying problem is that the lock file describes a set of compatible dependencies as a whole. If you replace some entries on one branch and some other ones on another a text based merge may cleanly use all modified entries, but these modified entries may not be compatible with each other at all. So you must regenerate the lock file as part of a merge unless it is unchanged. For this reason I think it's actually better that the lock file conflicts if you don't do this.

Now what may be beneficial is building some commands that simplify regenerating the lock file in the way described in my talk, without having to fully understand the context. Or maybe one can even build a git hook to correctly update the lock file.

But what you are proposing here will do more harm than good in my eyes.

---

A concrete example based on the linked slides:

We start with 2 packages in the composer.lock file on the main branch.

```json
{ "name": "dep/zebra", "version": "1.0"}
{ "name": "dep/giraffe", "version": "1.0"}
```

On the main branch we update dep/zebra which introduces a dependency on dep/duck 1.*.

```json
{ "name": "dep/zebra", "version": "1.1", "require": {"dep/duck": "1.*"}}
{ "name": "dep/giraffe", "version": "1.0"}
{ "name": "dep/duck", "version": "1.0"}
```

A while later on our dna-upgrade branch based on the original lock file commit we update dep/giraffe which introduces a dependency on dep/duck 2.*.

```json
{ "name": "dep/zebra", "version": "1.0"}
{ "name": "dep/giraffe", "version": "1.2", "require": {"dep/duck": "2.*"}}
{ "name": "dep/duck", "version": "2.0"}
```

Now we merge dna-upgrade into main. If we imagine your system this would lead to the following lock file:

```json
{ "name": "dep/zebra", "version": "1.1", "require": {"dep/duck": "1.*"}}
{ "name": "dep/giraffe", "version": "1.2", "require": {"dep/duck": "2.*"}}
{ "name": "dep/duck", "version": "2.0"}
```

While this merge would work in git without conflicts it leads to an invalid lock file state. The requirement for dep/duck 1.* is not actually met by the updated dep/duck: 2.0. Runtime errors in your application would probably appear if you tried to install this.

To resolve this merge issue one should reset the lock file to the main branch state before merge and rerun the composer update that lead to dep/giraffe being updated. Composer would then notice an upgrade of dep/zebra is also required to allow dep/duck.

```
git checkout main -- composer.lock
composer update dep/giraffe --with-all-dependencies
```

```json
{ "name": "dep/zebra", "version": "1.2", "require": {"dep/duck": "2.*"}}
{ "name": "dep/giraffe", "version": "1.2", "require": {"dep/duck": "2.*"}}
{ "name": "dep/duck", "version": "2.0"}
```
