### ISSUE TITLE
[Feature] Allow to use composer.yml instead of composer.json and auto-convert on the fly

### ISSUE THREAD

**Issue by LionsAd** [composer/composer#10265]
### Motivation

- It's so much nicer to write in YAML than in JSON
- It's language-wise equivalent

### Problems

It might not yet be a good idea to support this for packages itself, but only for root composer.jsons (90% case for users not distributors anyway).

### Implementation idea

- Check if `${COMPOSER/.json/.yml}` exists, if yes use it
- If additionally a .json exists, throw an error (can only use one)
- Load data via YML => convert to JSON

### Feedback

I would be happy to do the implementation, but would want feedback on the feasibility and concerns of the idea first.

So consider this a kind of RFC. If there is a proper RFC process, I missed it and will gladly post there.

Thanks for the great work on composer v2.

**Comment by stof** [comment]
The issue with that is that it will force all repositories to support detecting the yaml file too, which will double the number of API calls.
Otherwise, it will be quite confusing: when you work on a package that will be installed as a dependency, its composer.json is the root package too (being a root package is contextual).

**Comment by Yogarine** [comment]
@Seldaek
> Yeah IMO this is just added complexity for very little value given all the commands we now have to modify the json file easily.

Sorry for necro-bumping, but I'd like to vouch for adding `composer.yaml` support primarily because it supports **comments**.

JSON was never intended to be used as a human-readable format.

You can argue that there are commands that facilitate manipulating the composer.json, but in the end many (if not most) of us prefer to just open the composer.json and update/check dependencies/config there. And in the real world I often have to make certain decisions regarding dependencies, and not even having the ability to accompany these cases with comments is a big hindrance and significantly increases the bus-factor in a project.
Perhaps most of you have simply adjusted to not commenting their composer.json to the point where you don't even realise the implications, but I know that practically every non-json config file I use in my projects (personal or at work) contains many comments to clarify and explain important things. And if I could comment my composer.json, oh boy I would, believe me.
And then there are many other nice features in YAML, like pointers and references, multi-line options, etc.

I mean, there is a reason most notable projects in the past ten years have chosen for YAML over JSON.

@stof's argument that it would double the number of API calls also doesn't hold up as well; if you check for `composer.json` first, then there is no need to check for `composer.yaml`. You could also maintain a bootstrap `composer.json` that will allow you to declare that you use a `composer.yaml`, and then you only need to look up the '`.yaml` when needed.
At some point in the future `.yaml` usage might overtake `.json` usage, and that point you can invert the check: look up `composer.yaml` first. You can also hasten this process by eventually deprecating `composer.json` in Composer v3.0.

Additionally, the composer.lock can remain json, because that's auto-generated and not really intended to be human-readable anyway.

So I'd like to ask you to please reconsider your stance. In my opinion, composer.json is an artifact from a time before better alternatives, and the longer you wait with removing it, the more it's gonna hurt.

**Comment by Yogarine** [comment]
> We will **never** be able to deprecate json, otherwise it would make all existing releases unsupported and unavailable.

With deprecating I don't mean a feature should no longer be supported, but rather that it's discouraged because a better alternative is favoured.

I guess I should've been more specific in my wording, sorry!

**Comment by Radiergummi** [comment]
I'd like to second what @Yogarine said. YAML is more than just comments, but multi-line strings without quoting madness, anchors, repeatable sections, and so on. Still, scripts without any comment or context are a real issue for lots of projects I've seen.

I don't really know the composer code base itself, but scanning for composer\.(json|ya?ml) and passing the contents through the matching FS backend doesn't seem to double API calls.

It would be great if this was revisited some time.

**Comment by stof** [comment]
@Radiergummi this is not only about filesystem. When loading repositories, composer reads the composer.json contents from each branch of the repository using the GitHub/Gitlab/Bitbucket API. That's where API calls would be doubled if composer needs to support yaml (and even tripled if it needs to support `.yaml` and `.yml`). Those API endpoints don't support globs.

**Comment by Yogarine** [comment]
@stof 
> @Radiergummi That's where API calls would be doubled if composer needs to support yaml (and even tripled if it needs to support `.yaml` and `.yml`).

However, if you maintain a bootstrap composer.json that would greatly reduce the number of additional API calls needed.

But maybe we're just going about this the wrong way. Different idea: let's _keep_ the `composer.json` file as is, but make it **purely** a generated file (which it already could be if you only use the composer cli to add/remove packages).
Instead, add the possibility to add a `composer.yaml` file that, if it exists, will be read by the composer cli used locally, which then always updates the `composer.json` to represent its state, then initiates the composer operation as per usual.

This would maintain backwards compatibility with existing projects, but provide a nice upgrade for those who prefer YAML. Changes to `composer.yaml`, `composer.json` and `composer.lock` should all be committed to CVS as per usual. If you ensure that the composer cli will _always_ update `composer.json` whenever you run it, to ensure it's up to date, you should have minimal divergency issues. (Not more than currently tends to happen between `composer.json` and `composer.lock` at any rate...)

**Comment by LionsAd** [comment]
I like that idea a lot and we talk indeed mostly about the project root composer.json/.yaml, not the ones used for reading from projects.

Maybe it might be best to open a new feature request for it, because this issue is closed, and the composer.json could have a new entry, which is the hash for the .yaml file.

@Yogarine I just realized another idea is possible right now:

You could probably PoC this with the `composer init` hook/event, which I added to 2.0 at some point, which allows plugins to react to the most initial state and still merge in like some other configuration (I build it originally to split composer into several files, then use the wikimedia merge plugin to merge a specific file into the main file, but then have plugins react to this merged config).

In that case for at least the root configuration, you could have a barebones composer.json file, which only includes the init plugin and then merge the .yaml into it at run-time.

Does not yet solve the writing of composer.json by composer, but it's a start to test the viability of the approach.

**Comment by Yogarine** [comment]
@LionsAd I actually already had started playing with a proof of concept plugin for Composer:

https://github.com/Yogarine/composer-yaml/blob/main/src/YamlPlugin.php

I ended up just using the `activate()` and `deactivate()` methods because the `init` event isn't triggered early enough in the Plugin lifecycle.

The way it currently works is:
during composer startup (`activate()`) the composer.yaml is read and then a composer.json is generated based on it.

During `deactivate()` a check is performed to see if any changes have been made to composer.json since. These are then converted back to composer.yaml to ensure changes made to the json by composer cli commands are effectuated to the yaml as well. There's still some cleanup to do and tests to write, but it already seems to work just fine like this.

**Comment by Veraxus** [comment]
Per comments I added here: https://github.com/composer/composer/issues/5364#issuecomment-2392044857

I know this is old and closed, but I absolutely agree that Composer should support YAML in addition to JSON. JSON was _never_ intended for configuration and that's why it doesn't support basic human-centric features like comments. As others have pointed out, making changes to the JSON spec is inappropriate, but workarounds like duplicate entries or "_comment" keys are equally inappropriate, IMO.

Since composer.json is a configuration file that is intended to be human-usable, YAML (or even TOML) is what makes the most sense as a long-term, human-centric alternative. This is a fundamental best practices issue, IMO.

I am not suggesting dropping support for JSON, just supporting YAML as well... and possibly making YAML the default for commands like composer init going forward. I vote to reopen this issue and make Composer more future-proof in v3 and beyond.

**Comment by stof** [comment]
@Veraxus all the arguments given by @Seldaek and me previously still hold true.

Supporting Yaml or Toml for the config of a root project while not supporting it when registering the package in a repository would lead to a weird state for the ecosystem, given that all packages being shared in a repository **are** the root package when working on those packages.
And supporting several formats in repositories will have a huge cost (forever, as we can never remove a format once it is supported as that would break all package releases that were done using that format) by requiring to load the content of multiple files per version of the package).
For reference, reading the metadata of `symfony/symfony` requires 777 API calls to the GitHub API just to read the composer.json files of the 777 versions available as of today (I'm not counting the extra calls needed to discover the list of available branches and tags, for simplicity). and that number is increasing each month when new releases are done. If we multiply that number by 3 (for `composer.json`, `composer.yml` and `composer.yaml`), this is not negligeable at all. GitHub applies a rate limit of 5000 API calls per hour per user (meaning that this `symfony/symfony` package needs to share this rate limit with other `symfony/*` package registered on packagist.org by the same maintainer, or with any other usage *you* make if you register that package as a VCS repository in your project)
