### ISSUE TITLE
[Feature] --frozen-lockfile option to abort install when lock file is not up to date

### ISSUE THREAD

**Issue by caugner** [composer/composer#10284]
From time to time, our `composer.lock` gets out of sync.

We haven't yet investigated what caused this (possibly multiple simultaneous Dependabot updates), but we would be able to avoid this if the `composer install` command could be configured to fail as part of our CI pipeline if the lock file is not up to date.

Yarn has a [`--frozen-lockfile`](https://classic.yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-frozen-lockfile) option for this.

**Comment by stof** [comment]
you can run `composer validate` to detect cases where the content-hash in you lock file does not match the composer.json

When you have an existing lock file,  `composer install` will *never* modify it. It will either succeed at installing locked dependencies or fail. As such, `composer install` always runs in frozen lockfile mode (assuming you have a lock file, so that it does not switch to running `composer update`).

So to me, there is nothing to change in composer here.

**Comment by caugner** [comment]
Thank you, I wasn't aware that `composer validate` could do the job for me! 👍 

I will extend our CI job that installs the Composer dependencies to run `composer validate --strict` before. 🎉
