### ISSUE TITLE
exec fails to pass arguments to command in some cases

### ISSUE THREAD

**Issue by lazka** [composer/composer#10376]
```
> composer --version
Composer version 2.1.14 2021-11-30 10:51:43
```

Steps:

* `composer exec -- foobar --help`

Actual output:  The help of exec

```
> composer exec -- foobar --help 
Usage:
  exec [options] [--] [<binary>] [<args>]...
...
```

Expected output: The help of foobar, or an error that foobar doesn't exist

**Comment by stof** [comment]
support for `--` was added only in symfony/console 3.0 (on older versions, it was skipped with no effect).

So this will be fixed in composer 2.3 when upgrading the version of symfony/console used in the phar (thanks to removing support for old PHP versions).

**Comment by lazka** [comment]
I see, thanks. For context, I assumed that `--` worked since it was advertised in `exec --help`

```
Description:
  Executes a vendored binary/script.

Usage:
  exec [options] [--] [<binary> [<args>...]]

Arguments:
  binary                         The binary to run, e.g. phpunit
  args                           Arguments to pass to the binary. Use -- to separate from composer arguments
```

**Comment by stof** [comment]
OK, looking more in details, I was wrong saying that it was a no-op before Symfony 3.0.

The parsing of command options supports `--` properly since symfony/console 2.1, so the help text of Composer's ExecCommand is not totally wrong.
However, before Symfony 3, the special API allowing to inspect options before parsing and validating the command input was not supporting `--`. And as `--help` is a global option of the Application that is processed before validating the input of a command, it is still detecting even after the `--` on Symfony 2.x.

**Comment by lazka** [comment]
Looking forward to 2.3 then. Thanks! :)
