### ISSUE TITLE
Composer 2.2 prompt even on non relevant commands

### ISSUE THREAD

**Issue by dereuromark** [composer/composer#10396]
```
composer
```
or --help

should not trigger

```
cakephp/plugin-installer contains a Composer plugin which is currently not in your allow-plugins config. See https://getcomposer.org/allow-plugins
Do you trust "cakephp/plugin-installer" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?] 
```

As this requires to even just list the main command overview or any --help using -n etc.
Which does not sound like it should be needed.

**Comment by Seldaek** [comment]
It is needed though because to list all commands we need to enable plug-ins as they can provide new commands.

**Comment by dereuromark** [comment]
I see :/

**Comment by dereuromark** [comment]
Could those be Listed grayed out if not yet approved or something?

**Comment by driesvints** [comment]
Can we maybe set a global setting to auto accept these all the time? I don't think it's feasible to ask this every time and for every package separately that's affected.

**Comment by driesvints** [comment]
I see we have https://getcomposer.org/doc/06-config.md#allow-plugins but is that a global composer setting or per-repository composer.json? If it's the latter can we also get this in as a global setting?

**Comment by Seldaek** [comment]
You can set it globally with `composer config -g allow-plugins.foo/bar true` for example to allow foo/bar always on that machine.

You can also set allow-plugins true entirely but that completely defeats the purpose of the feature and is IMO a terrible idea on a non-sandboxed environment.

And no we can't easily show commands greyed out as loading the plug-ins to even know if there's a command lets them execute code. At that point it's too late.

**Comment by Seldaek** [comment]
> Can we maybe set a global setting to auto accept these all the time? I don't think it's feasible to ask this every time and for every package separately that's affected.

Also note that it won't ask you every time, it prompts once per package and adds the package to the composer.json, then it's not prompting anymore on subsequent run. The idea is that in the long term every composer.json will simply declare allowed plug-ins and then those prompts become very rare.

**Comment by dereuromark** [comment]
Fair enough then. Thank you.

**Comment by stof** [comment]
if it is already allowed (or forbidden) globally, it does not need to be configured at the project level as there is already a config for that plugin.
if it is not configured globally (and not yet configured locally), composer update *is* asking (when running in interactive mode)

**Comment by stof** [comment]
@eusonlito then configure it at the project level rather than globally. This way, the config is part of the project.
And when you install a new package in your project, `composer update` (or `composer require`) will prompt you and add it in the project-level configuration.
A plugin will get allowed globally only if *you* do it explicitly. Composer prompts about allowing plugins will never modify the global config.

**Comment by eusonlito** [comment]
@stof, thanks a lot for your comments, but I know that I can configure at project level, but then, why there are a global config option if this option is not shared to projects?

If I configure a global option that always trust certain packages, why is that not reflected in the project?

As a Laravel developer, I have to trust always same packages on every project that I manage, and it's very annoying. But I can not to set this option as global, because my new projects will not deploy if I don't set manually the `allow-plugins` inside the composer.json.

:)
