### ISSUE TITLE
Requirements problem when doing `composer require` mentions update command

### ISSUE THREAD

**Issue by joachim-n** [composer/composer#10453]
The `composer require` command produces requirement errors which look like this:

>     - drush/drush[10.0.0-alpha1, ..., 10.0.0-rc1] require consolidation/site-process ^2.0.3 -> found consolidation/site-process[2.0.3, 2.0.4, 2.1.0, 2.x-dev] but the package is fixed to 2.0.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Saying 'Make sure you list it as an argument for the update command.' is confusing, because I've run a require command, not an update command.

**Comment by Seldaek** [comment]
Looking at this some more, it'd be really a mess to fix. It is a fact that the require command updates the composer.json and then runs an update internally, unless you do --no-update.

In theory it should also list this below the problem description as a hint:

> Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

I think I'll have to close as won't fix, because anyway establishing whether we are inside a  require or update command at the point where we generate solver problem output is practically impossible.

**Comment by joachim-n** [comment]
> I think I'll have to close as won't fix, because anyway establishing whether we are inside a require or update command at the point where we generate solver problem output is practically impossible.

Does the statement actually make sense for the 'require' command as well?

If so, could the string created in the solver part of the code use a token like '%command' which gets replaced by the output?

**Comment by Seldaek** [comment]
I don't think that holds no, if you just add package names to require you're adding them to your composer.json even tho they might not be directly required by your project. I suppose one thing we could do in require is detect this and add some extra text explaining the use of no update to split the command in two.

**Comment by Seldaek** [comment]
Sorry closing again as I just don't see a clear way to fix this.
