### ISSUE TITLE
Shebang generated in bin files causes php fatal error

### ISSUE THREAD

**Issue by lcdss** [composer/composer#10533]
My `composer.json`:

```json
{
    "require": {
        "google/cloud-functions-framework": "^1.1"
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: OK
Composer version: 2.2.6
PHP version: 7.4.27
PHP binary path: /usr/local/bin/php
OpenSSL version: OpenSSL 1.1.1k  25 Mar 2021
cURL version: 7.74.0 libz 1.2.11 ssl OpenSSL/1.1.1k
zip: extension present, unzip present, 7-Zip not available
```

Hi! After installing `cloud-functions-framework`, a file inside vendor/bin directory is generated with the following content:

```php
#!/usr/bin/env php
<?php

/**
 * Proxy PHP file generated by Composer
 *
 * This file includes the referenced bin path (../google/cloud-functions-framework/router.php)
 *
 * @generated
 */

namespace Composer;

$GLOBALS['_composer_bin_dir'] = __DIR__;
$GLOBALS['_composer_autoload_path'] = __DIR__ . '/..'.'/autoload.php';


include __DIR__ . '/..'.'/google/cloud-functions-framework/router.php';
``` 

then you run the server to execute the function when a request is made

```bash
php -S 0.0.0.0:8000 /function/vendor/bin/router.php
```

and you get the error bellow when a request is made

```
<br />
<b>Fatal error</b>: Namespace declaration statement has to be the very first statement or after any declare call in the
script in <b>/function/vendor/bin/router.php</b> on line <b>12</b><br />
```

If the shebang (`#!/usr/bin/env php`) line added by composer is removed from the` vendor/bin/router.php` file, there's no error anymore.

I thought this would be happening only on Windows, but I could replicate this error on Arch Linux as well. On both OSs, I was using docker containers to run the function.

Anyone knows why this happen? Why does composer creates those proxy files? Is there any way to disable this behavior?

**Comment by Seldaek** [comment]
We create proxy files everywhere as of 2.2.0 for consistency and to fix issues with symlinked packages. There is no way to turn this off and it's not going away.

The problem is this file is not a binary and it should not be using the binary feature to be linked in bin dir IMO. Use `php -S 0.0.0.0:8000 /function/vendor/google/cloud-functions-framework/router.php` to include the file directly in the package.

That said, I find it strange that PHP would error on this, seems to be an issue of the embedded webserver that it doesn't strip the shebang. I'll report that to PHP, see if that can be fixed at least.

**Comment by Seldaek** [comment]
Ah sorry I misread this. The problem seems to be that you are not using PHP 8, which fixed this behavior already.

The other issue seems to be your vendor/bin/router.php is missing a chunk of code for handling PHP<7.4, I am not sure why, but try to remove it and run composer install again, there should be a huge code block before the last include looking like:
```
if (PHP_VERSION_ID < 80000) {
    if (!class_exists('Composer\BinProxyWrapper')) {
[...]
}
```

**Comment by lcdss** [comment]
@Seldaek  Thank you for clarifying the reason behind that error. I haven't realized myself PHP <= 7.4.x wasn't compatible with shebangs. As `cloud-functions-framework` is only compatible with PHP 7.4 I'm stuck for the time being with PHP < 8, but calling the underlying `router.php` directly works for me.
