### ISSUE TITLE
Version guessing takes long when no package version is defined

### ISSUE THREAD

**Issue by shyim** [composer/composer#10568]
We switched from custom  shell scripts to use Composer scripts. I just recognized that the startup time of Composer is sooo slow, when no package version is defined. 

In my local setup `Composer\Package\Version\VersionGuesser::guessFeatureVersion` takes 1,3s. If you have to execute multiple scripts is it pretty annoying to wait so long.

See blackfire trace: https://blackfire.io/profiles/e2f58687-3356-4fea-b454-2a98a9e2b577/graph?settings%5Bdimension%5D=timeline

My `composer.json`:

```json
{
    "scripts": {
        "foo": "echo bla"
    }
}
```

Command:

```bash
composer run foo
```

**Comment by Seldaek** [comment]
It's definitely a problem and something I've been trying to improve, but we still have room for improvement in some areas.

This only happens if you're on a feature branch tho I guess? Could you show the output of `git branch -a`?

In case your main/default branch isn't a standard name, you can also use `"non-feature-branches": ["foo"]}` with the name of that branch. That will bypass the branch guessing logic which should speed things up a lot.

Another thought is we can probably run these processes in parallel now that we have the infrastructure to do so. That'd hopefully speed things up quite a bit. I'll try and do that when I find a minute.
