### ISSUE TITLE
Symlinks inside /vendor/bin/ get replaced with regular files

### ISSUE THREAD

**Issue by pcapp2114** [composer/composer#10602]
Sorry if I did not follow the message template. I am using Composer to manage a Drupal 9 website. I had to downgraded back to Composer version 2.1.5.  in order to continue working. A problem started when I upgraded to version 2.2.7. If you run certain Composer commands like installing a Drupal module like this.
`composer require 'drupal/rabbit_hole:^1.0@beta'`
The symlinks inside /vendor/bin/ will be replaced with regular files which then breaks the Drush symlink. Then Drush will not work on the server. People say to delete the /vendor folder, than run composer install. But this just recreates normal files again and not symlinks inside vendor/bin. If I downgrade back to v 2.1.5 and run composer install, symlinks are then created inside vendor/bin.

**Comment by Seldaek** [comment]
Yes this is how it is as of Composer 2.2.0 and it'll stay that way as we need it to fix enable some other functionality.

Either call vendor/foo/bar/bin-path directly or.. let me know more details about what happens/how it breaks then maybe we can find a way to fix things in drush.

Note that I am only vaguely familiar with Drupal so please explain like I'm an idiot otherwise it probably won't help.

**Comment by JonMcL** [comment]
We also just ran into this as an unexpected surprise during deployment.

Is there a change record or commit that I can reference for our internal teams?

Our issue is that the vendor/bin files (i.e. vendor/bin/drush) do not have the execution bit set. I'm currently investigating why they do not and our vendor/drush/drush/drush file does have the execution bit set.

So, without the symlink, we get a permission denied error. This is for a deployment that has to (unfortunately) keep the contents of the vendor directory in the git repo. So the X bit doesn't seem to be making in or out of the repo. Likely a problem on our end.

**Comment by Seldaek** [comment]
@JonMcL the initial change was in https://github.com/composer/composer/pull/10137 - but there were many subsequent fixes and so looking at the latest code in https://github.com/composer/composer/blob/main/src/Composer/Installer/BinaryInstaller.php is probably more relevant.

The execute bit should be set on the `vendor/bin/...` file by https://github.com/composer/composer/blob/bbf2e94579cb91f8eacb9bd050f4b13aef67a853/src/Composer/Installer/BinaryInstaller.php#L116 

I am not sure why this would not work for you.

**Comment by JonMcL** [comment]
@Seldaek The bit is being set fine when I run `composer install` (after removing the `./vendor` directory) in my local dev environment (it happens to be ddev on Mac OS).

However, we have to commit our `./vendor` directory to the git repo and it looks like the execute bit is not making it through to the repo or when cloned to the app server.

It turns out our deployment pipeline has been always setting the execute bit on the original file (`./vendor/drush/drush/drush`) and the symlink of course inherited that. I'm not particularly informed about how well or poorly our git repo will carry the X bit through to the server, so we might just have to add an additional chmod +x for `./vendor/bin/drush` in our deployment pipline. (and maybe other files in `./vendor/bin/`)

Of course, the proper solution would be for us to not commit the `./vendor` directory and instead run `composer install` on the server itself (or somewhere in deployment pipeline). I just have to convince a few folks here of that requirement.

So this is probably more of an "us" problem rather than a composer problem, but maybe my experience is helpful for @pcapp2114  or others.

**Comment by Seldaek** [comment]
Sure, maybe check https://git-scm.com/docs/git-config#Documentation/git-config.txt-corefileMode on your machine and the build server? 

Otherwise adding a chmod sounds like it'll work around it fine, even tho it's not a root cause fix.

**Comment by JonMcL** [comment]
Yes, just confirmed. `git config core.filemode true` does make the X bit reach our server (at least a dev staging server). Of course various other shell scrips, and some JS files, installed by Drupal core and contrib modules also get +x on the server.

I'll probably have to force ddev to use an older version of composer for a short time to allow team members to get up to speed.

Thank you for the help! (and sorry to hijack this issue thread)

**Comment by Seldaek** [comment]
You can also leave core.filemode to false otherwise and make sure you set the flag correctly in the git repo with `git update-index --chmod=+x vendor/bin/lala` then commit that, it should then persist IMO.

**Comment by pcapp2114** [comment]
@JonMcl @Seldaek Thanks for providing this information. We also have to commit our /vendor folder to all 3 development environments. I forgot to mention, setting the execution bit with this.
`chmod +x vendor/bin/*`
also fixes it for us and changes the files back to symlinks.
Also this is not a problem on my local environment Virtaulbox/Centos. Drush will continue to work on my local even after the execution bit is removed. But the development Redhat server doesn't like it and Drush breaks.

I can't use `fileMode = true`. This changes the file mode for all files in the Drupal project. I always set this to false.

We do not have composer installed on the dev servers. And we are not using a cli tool/jenkins or a pipline tool. We push our local git branches up to the dev server, then manually pull them into the master branch.

@JonMcl, When we run git status the files inside /vendor/bin/ are listed as typechange, like this.
```
typechange: vendor/bin/drush
typechange: vendor/bin/release
typechange: vendor/bin/robo
```
Running this removes typechange files from git status
`git update-index --assume-unchanged vendor/bin/*`

Can a git hook run this shell script before a git push?
`chmod +x vendor/bin/*`
Or can this be run before a git add --all?
`git update-index --assume-unchanged vendor/bin/*`

Maybe /vendor/bin/* can be added to gitignore, but if new packages are installed, they will be ignored.

Is it correct to run this before you run git add --all?
`git update-index --assume-unchanged vendor/bin/*`

Once I ran update-index, typechange files do not show up again, even after install new packages. Is this setting saved permanently in your current project? can this be added to gitconfig?

To manually undo this, I can run this.
`git update-index --no-assume-unchanged vendor/bin/*`

To get a list of dir's/files that are assume-unchanged run this.
`git ls-files -v|grep '^h'`

**Comment by pcapp2114** [comment]
Running this seems to be working very good. And it is persistent.
`git update-index --assume-unchanged vendor/bin/*`
I will need to run this in all my Drupal projects.
Sometimes when I run this, I get error.
`fatal: Unable to mark file vendor/bin/dcg`
I have a few files indside /vendor/bin/
