### ISSUE TITLE
composer install/update checks requirements even from "require-dev" stuff

### ISSUE THREAD

**Issue by 6562680** [composer/composer#10891]
We have `laravel/horizon` in composer.json at "require-dev" section

This web-admin for redis requires php-pcntl thats available only on linux

I dont want to install these package on my windows machine, and in case cant run `composer install` cus of package requires it.

It wont be installed but require some.

ps. i know that "Timmy" in laravel team creates something... something. Actually i dont want to remove "this" from our composer, but wanna skip. I couldnt.

**Comment by stof** [comment]
you can use the `platform` config to force composer to consider that `ext-pcntl` is available (but then, make sure that the package does not actually require that extension for real but instead handles properly the case where the extension is not there, in which case you might as well send them a PR to move it from `require` to `suggests`)

**Comment by stof** [comment]
And checking the dev requirements of the root package is expected, because the dependency resolution always takes them into account

We don't want to generate a different lock file with different versions of packages depending on whether you run `composer update` or `composer update --no-dev` (`--no-dev` impacts only the installation step, not the dependency resolution step). Early version of composers were doing that, and it created tons of weird cases.

**Comment by 6562680** [comment]
thanks.
understand that dev dependencies wont be installed if our package is a dependency for other.
if we install using composer.json - it installs both and requires flag to skip.

**Comment by stof** [comment]
When you package is the root package, the behavior is indeed different that when using it as a dependency. That's totally expected (that's the difference between `require-dev` and `require`)
