### ISSUE TITLE
#stand with ukraine political statement

### ISSUE THREAD

**Issue by gaining** [composer/composer#10983]
When running composer, I see the #standwithukraine political statement. Can we remove any political statement from composer? Some of us just want to do work without having anything to do with politics. That world is extremely toxic, can we just code in peace without being reminded of that toxicity? Also it'd be nice if no politics ever had influence on this project. I'm not russian or ukrainian but I have had friends from both countries and there are good people in both, pls stop the divide.

**Comment by Seldaek** [comment]
Sorry no, see other previous issues if you are interested in a longer answer.

**Comment by dougwhite** [comment]
You've put politics in a development tool.... 

Regardless of the moral correctness or incorrectness, putting your political opinions out like this is so supremely unprofessional. To make things worse, the way you've been calling anybody who raises an issue with this a "russian bot" is so very childish. 

If somebody were to fork this project I wouldn't hesitate in recommending customers jump ship, as you've proven that you can't separate your politics from your work. You know... as adults are able to.

This is why the professional software development world has zero respect for open source projects, and we have to fight a constant battle to prove that OSS can be of professional quality... childish shit like this.

I sincerely hope that you can understand how much good faith you've shattered in your community, especially from people who may share your politics, but not your childish desire to force them into every aspect of life. 

So very disappointing to see this from one of my favorite open source projects

**Comment by Erutan409** [comment]
@Seldaek I'd be willing to bet that a good portion of people relegate the conflict with the threat of ***nuclear war***. So, I'll be the one to bring up that point as to why I'm sure a lot of people would rather not see this message stamped in their console while doing a simple package inclusion.

**Comment by kodima05** [comment]
You can remove it by removing this specific package:
`composer remove ukeloop/stand-with-ukraine`

**Comment by Andreas-Schoenefeldt** [comment]
we also have this amazing discussion about the topic: https://github.com/composer/composer/discussions/10808

**Comment by oni321** [comment]
@Seldaek The finality of your "no" answer reminds me of closed-source software vendors who say "No, you can't change the code." It goes against the spirit of open-source. Not only that, it's ineffective. Annoy others (as you have) and they'll go from neutral to hating your message. Have a nice day.

**Comment by lazarevicivica** [comment]
I don't stand with Ukraine and what the Composer has to do with it?

**Comment by Geddo** [comment]
I can understand that they want to use the reach here to draw attention to the war, but it is not our war, it is driven by political interests that we do not understand and that we cannot influence. And srsly: "Let's fight back against the Russian regime"? We are not your private army, nor is it useful to turn the aggression around. Information must be freely available and the only way out of the conflict is de-escalation on all sides - just my 50 Cent

**Comment by pMatviienko** [comment]
> I can understand that they want to use the reach here to draw attention to the war, but it is not our war, it is driven by political interests that we do not understand and that we cannot influence. And srsly: "Let's fight back against the Russian regime"? We are not your private army, nor is it useful to turn the aggression around. Information must be freely available and the only way out of the conflict is de-escalation on all sides - just my 50 Cent

"but it is not our war" - well that's was Ukrainians thoughts during war in Georgia. or in Chechnya. 

"it is driven by political interests" - oO, so politicians was raping and murdering people in Bucha, Izyum, Kupiansk, Kherson? As i know it was regular russians nad not Putin himself.

"conflict is de-escalation on all sides" - I guess you want to give russians your home to "de-escalate". Because a lot of ukrainians do not understand why they should give their homes to rssians.

Sure it is not your war, just wait until it become yours

**Comment by jteedub** [comment]
@pMatviienko Ukraine committed genocide of civilians in Donbas since 2014... Victoria Nuland and the CIA conducted a coup in Ukraine to put your lord and savior Zelensky in office and then began ratcheting up attacks civilians in Donbas and throughout  Eastern Ukraine... Both sides of this conflict need to deescalate, neither is heroic, neither should be celebrated.

"One of the most cowardly things ordinary people do is to shut their eyes to facts." - C.S. Lewis

**Comment by d9media** [comment]
I was actually a bit shocked when I first saw this. I strongly condemn any political statements in Opensource. Don't use your software as an audience for any political propaganda.

**Comment by Andreas-Schoenefeldt** [comment]
Some solutions can be found here: https://stackoverflow.com/questions/76130997/composer-how-to-remove-standwithukraine-cli-message

**Comment by pMatviienko** [comment]
@jteedub any proofs for your words? or you just love to talk? By the way officially russian actions was confirmed a genocide, by the way. Actualy looking on reactions and moderation of thread pretty glad that i stopped using github a long time ago

**Comment by Erutan409** [comment]
@pMatviienko Are you just looking to get into an argument? One that was never a threat of being started, if it weren't for this political co-opting of a package manager? Seriously, what is the end-game, here? It's pretty apparent the support for keeping composer politically neutral is stronger than your insistence that it remain for your personal reasons.

**Comment by newart1st** [comment]
Please add the output of the following statement to be fair:
#standwithLibya
#standwithSyria 
#standwithIran
#standwithCAR
#standwithAfghanistan
#standwithIraq
#standwithYugoslavia
#standwithBosnia
#standwithVenezuela

**Comment by theodorosploumis** [comment]
There is also `#standwithCyprus`. See https://en.wikipedia.org/wiki/Turkish_invasion_of_Cyprus.

**Comment by Winfle** [comment]
Every normal person support Ukraine, so just calm down, chill

**Comment by dougwhite** [comment]
> Every normal person support Ukraine, so just calm down, chill

I support Ukraine, I don't support politics in open source. I support ending war, I don't support shallow internet politics.

When I worked as a self employed software consultant, I would use composer for customer installations. I would never consider bringing politics into my customers business. No matter how "right" i am, and no matter how much my customer would agree with my politics; it would still 1000% not be acceptable because it would be highly unprofessional.

Considering I don't contribute to the source code, don't help maintain, don't pay for the package... Well I feel the decision isn't mine to make. However it's still disappointing to see, and frustrating (to me at least, can't speak for everyone) because it feels like those defending this decision seem to think that if the message had been #StandWithRussia we would all totally be totally on board.

If this was really a massive issue to me I should look at forking or moving to an alternative. (Also correct me if I'm wrong but didn't I read that it's trivial to remove and originates from packagist anyways?). So really I just wanted to add my 2 cents as somebody who doesn't really have a problem with your politics but still disagrees with how and where you think it's appropriate to express them. 

As I said I'm not an active contributor, and believe that it's the right of those who build and support the code to have the final say. Still, I hope at the very least I've convinced you that there is more nuance to the opposing side of your argument than simple black and white internet politics.

**Comment by theodorosploumis** [comment]
I have submitted a https://github.com/theodorosploumis/stand-with-cyprus fyi.

**Comment by Andreas-Schoenefeldt** [comment]
It's not the same, if not everybody get's it unasked in there command line ;)

**Comment by theodorosploumis** [comment]
> It's not the same, if not everybody get's it unasked in there command line ;)

I know, I do not agree with the forced promoted message by composer either.

**Comment by markbaka** [comment]
为什么这么多傻逼乌贼，支持你妈逼，给泽兰斯基爆菊花去吧

**Comment by kerranswell** [comment]
So, it seems shameful #StandWithNazi has finally been removed.
