### ISSUE TITLE
Disable installed.php file generation

### ISSUE THREAD

**Issue by garygreen** [composer/composer#11018]
Is there a way to disable this file from being generated? We currently don't have any use for it, nor do we want or need packages in our app to know what's installed and their versions. The `installed.php` file is absolutely huge on our app, adding unnecessary memory usage and resources to each request.

I checked the docs at: https://getcomposer.org/doc/07-runtime.md#installed-versions - however it seems this feature is non opt-in.

Would it be possible to add something to composer.json to disable it, something like:

```php
"installed-file": false
```

And maybe a command line option?

```bash
composer install --no-installed-file
```

**Comment by Seldaek** [comment]
Why is it adding memory usage to reach request? It isn't loaded unless you use it AFAIK.

**Comment by garygreen** [comment]
> It isn't loaded unless you use it AFAIK.

There are so many things that load that file, even within Composer itself - so it's hard to track down exactly where and why it's loading, but it is for every single one of our requests. That file is several megabytes and it's just not adding any value to our application but increasing memory usage.

> Aside from that no we are unlikely to add a switch for this as it would add complexity and ways for people to shoot themselves in the foot.

That's a shame to hear. We could have some custom script that clears that file making it blank. That installed file is purely a progressive enhancement and shouldn't be essential (some sites are still running on older version of composer) so it's not clear how this could shoot people in the foot?

**Comment by stof** [comment]
@garygreen packages can depend on `composer-runtime-api` version 2 or higher, in which case they will expect to be able to use the `Composer\InstalledVersions` API. Just removing the file would mean that this API reports wrong info (telling you that the package is not installed while it actually is), which can then break things depending on what uses that API.

@Seldaek would it be possible to make sure that the initialization of `Composer\InstalledVersions` does not copy the array, to keep it in the OPCache shared memory ? We have such an optimization for the ClassLoader initialization.

**Comment by Seldaek** [comment]
It should already be the case that the array is not copied and that it remains only once in shared memory.

It may appear as if all processes use more ram because they'll all have a higher shared memory amount but it should only be once in ram if you're using opcache (which you should if you remotely care about perf..).

**Comment by danog** [comment]
Note: to cache the array returned by installed.php in shared memory when using opcache preloading, make sure your preload file invokes `\Composer\InstalledVersions::getInstalledPackages();`, otherwise the installed.php file will just be re-parsed on each request.

A nicer way of fixing this would be to directly initialize the `InstalledVersions::$installed` property when generating the autoloader (similar to how it is done in `ComposerStaticInit` when using the optimized autoloader) + invoke `class_exists(\Composer\InstalledVersions::class)` in `ComposerAutoloaderInit::getLoader`, this way even just preloading the autoloader will immediately cache the installed versions array.

**Comment by Seldaek** [comment]
Letting you disable this is not something we want to do, but please see #12147 - it should ensure it's preloaded. /cc @jarstelfox as you seemed to hit this as well in https://github.com/Jean85/pretty-package-versions/issues/47

**Comment by Seldaek** [comment]
Per the discussion on #12147 I don't think this should be a composer concern for the time being. There's also no way to identify when php is running in preload mode which is unfortunate.. So rather leave this up to each app to figure out. If someone has preloading experience and wants to share some composer-related tips here or ideally as a docs PR that'd be great though.
