### ISSUE TITLE
Package single-file composer.phar for Guix

### ISSUE THREAD

**Issue by trev-dev** [composer/composer#11051]
Maybe related to #9830

I was able to package composer in a cheesy way by using guix's `copy-build-system`. All this does is patch the shebangs and move it into the profile's /bin directory where it can be found on path.

Turns out one cannot "just simply patch a shebang" because it causes the resulting composer executible to fail some Sha512 checksum. Fair enough!

Any suggestions for how to properly update the hash? Let me know if I'm off base here.

```bash
Fatal error: Uncaught PharException: phar "/gnu/store/pymc4ippfvhlhk1sf5vbg7sdih6h70jg-php-composer-2.4.1/bin/composer" SHA512 signature could not be verified: broken signature in /gnu/store/pymc4ippfvhlhk1sf5vbg7sdih6h70jg-php-composer-2.4.1/bin/composer:28
Stack trace:
#0 /gnu/store/pymc4ippfvhlhk1sf5vbg7sdih6h70jg-php-composer-2.4.1/bin/composer(28): Phar::mapPhar('composer.phar')
#1 {main}
  thrown in /gnu/store/pymc4ippfvhlhk1sf5vbg7sdih6h70jg-php-composer-2.4.1/bin/composer on line 28
```

**Comment by Seldaek** [comment]
Why would you need to patch the shebang exactly? Sorry I am not very familiar with guix. Is it because you need to directly reference a php which is not in the PATH?

Anyway you could update the signature, we do it as well when compiling the phar, see https://github.com/Seldaek/phar-utils/blob/main/src/Timestamps.php#L103-L130 

Or you could create a proxy file like:

```
#!/path/to/php
<?php

include __DIR__.'/composer.phar';
```

On php 8+ this works fine without outputting the phar file's shebang.

**Comment by vladgorenkin** [comment]
@trev-dev i would guess it's also possible to remove 'patch-shebang phase and add php as propagated-inputs if you are not packaging composer properly anyway

**Comment by trev-dev** [comment]
For anyone who cares about this, I tried deleting the shebang patches and surrendered when I realized that the `copy-build-system` did too much for my tastes. I switched to the trivial build system and kept it "simple". Guix Simple, that is.

https://git.sr.ht/~trevdev/guix-channel/tree/main/item/trevdev/packages/php.scm
