### ISSUE TITLE
--ignore-platform-req=php+ reversed when using --prefer-lowest

### ISSUE THREAD

**Issue by nicolas-grekas** [composer/composer#11068]
When `--ignore-platform-req=php+ --prefer-lowest` is used, composer ignores the lower boundary of php. This is not the desired behavior imho, `--prefer-lowest` should not affect to the platform requirements.

**Comment by nicolas-grekas** [comment]
I reported this when I realized that a transitive dep was installed at v1.0 instead of v1.1 on PHP 8 while v1.0 was ^7 and v1.1 was >=7.
Now that I think twice about this, it looks expected. Still surprising at first.
I keep this open if someone else would like to have a second look. Feel free to close.

**Comment by nicolas-grekas** [comment]
There might still be something to improve on this topic. I tried using `--ignore-platform-req=php+` on the CI of Symfony and I realized there is no way to make it green on deps=low jobs.
The reason is that a dep (doctrine/dbal in this case) has its v2.6 support php `^7.1` while v2.12 has `^7.3|^8.0` and is the first to run on PHP.
This means I cannot bump this dep to v2.12 because that would bump the min version of php we support to v7.3.
If I use `--ignore-platform-req=php+`, composer installs v2.6 even thought we run on PHP8, and the job fails with a fatal error.

**Comment by stof** [comment]
@nicolas-grekas to me, Symfony should not use `--ignore-platform-req=php+` on the deps=low job. Lowest version of the deps is less likely to work with a newest PHP version.

**Comment by Seldaek** [comment]
Yeah I am not sure what we can do about this. prefer-lowest is hard because all lowest dependencies of all your dependencies need to be absolutely correct and often things just work by chance as prefer-highest is the default..

IMO doing prefer-lowest on latest PHP is bound to cause pain. I always run prefer-lowest on the oldest supported PHP to ensure that all the old stuff works together, but if someone runs latest PHP version I do expect them to also reasonably update software to working versions.
