### ISSUE TITLE
Feature: install highest dev dependencies (with lowest prod dependencies)

### ISSUE THREAD

**Issue by Bilge** [composer/composer#11099]
We can install only production dependencies but we can never install only dev dependencies. Why this arbitrary limitation? Presumably because it is imagined the use-case does not exist. But it does: it is good practice for libraries to configure CI to test not only highest but also lowest dependencies (with `--prefer-lowest`), but it does not help to install the lowest dev dependencies because they do not reach consumers of our library and installing lowest dev dependencies often breaks tests unnecessarily by introducing fixed bugs in those libraries. Ergo, we want to install lowest prod dependencies but highest dev dependencies; Composer provides no mechanism to do this because we cannot install dev dependencies with separate configuration from prod.

**Comment by Seldaek** [comment]
Just an example problem: What if something is required by both dev and non dev tho, how would prefer-lowest work in that case? 

Anyway IMO the way here is to bump your dev dependencies so they are at a level where bugs are fixed.. Or install test tools separately to run the tests against your project's prefer-lowest installation.

I am going to close this because I don't really see a way to do this sanely.
