### ISSUE TITLE
feature suggestion: pnpm mode

### ISSUE THREAD

**Issue by DanielRuf** [composer/composer#11132]
I'm currently searching for a solution to reduce the actual disk space used by composer and reduce the work involved in copying files from the composer cache.

For this we have https://pnpm.io/ in the JS ecosystem which uses a content-addressable storage with hardlinks (https://en.wikipedia.org/wiki/Content-addressable_storage). Other package managers like yarn and npm also implemented this.

See also https://pnpm.io/motivation

Is this already possible or planned natively using composer? My motivation is to reduce disk usage, power / electricity consumption and have a smaller carbon footprint.

This would probably also dramatically speed up install steps and reduce the amount of duplicated files.

The current structure looks like this:in pnpm looks like this:

pnpm store (`pnpm store path`):

![image](https://user-images.githubusercontent.com/827205/196410068-55bc598c-6521-4760-83c8-f109227a6cfb.png)

A install step does this:

![image](https://user-images.githubusercontent.com/827205/196410283-b00f227e-7dff-4730-915a-d835053dacd8.png)

The node_modules folder looks like this:

![image](https://user-images.githubusercontent.com/827205/196410452-86e19423-52b2-4fe2-bfb7-9eb635ae9413.png)

See also https://d33wubrfki0l68.cloudfront.net/64b2f62af3b1c3dc4314df0ec517d9661d03b934/aca71/assets/images/node-modules-structure-8ab301ddaed3b7530858b233f5b3be57.jpg for the technical concept.

**Comment by Seldaek** [comment]
This is IMO way less beneficial in Composer than in npm because we have typically less dependencies and they are also not recursively installed so you don't get many times the same thing installed unless you have many projects with the exact same dep versions installed on the same filesystem.

So we have not considered doing this because it doesn't seem worth the effort nor the added complexity/maintenance burden.

**Comment by DanielRuf** [comment]
@Seldaek I'm not so sure, I have a Magento project with 1.5 GiB of `vendor` and we at bitExpert are working on more Magento / Symfony projects. Also for one client we have the exact same composer.json file so there are definitely duplicated files and folders in many places.

Besides this, the content addressable approach hashes each single file so it definitely saves disk space across packages.

**Comment by Seldaek** [comment]
Yeah I can see it might have some benefit for some projects, magento is definitely on the larger side of project sizes.. I'm seeing a 50-300MiB range here on projects I have on my machine.

I still think it requires more worth than is worth, but I'm willing to keep it around as a feature request. If someone is willing to put the time and effort and it seems reasonable in terms of maintenance cost I guess I'd be intrigued to see the benefits.

**Comment by stof** [comment]
@DanielRuf if you have 1.5GB for a single project, I don't see how a pnpm approach would solve things. Unlike in the node.js ecosystem, you cannot have the same package installed multiple times in a composer vendor directory. So you would need to investigate what is inside this huge vendor directory to identify the offending packages

**Comment by DanielRuf** [comment]
@stof if you have more than one Magento 2 project, than it drastically saves disk space.

It is not about having packages multiple times in a deeply nested dependency graph. It is mainly about deduplicating files on disk by using hardlinks. Even other Magento projects use almost the same packages and many files.

This is just an example scenario. The same applies if you have 20x the same Symfony project like we have (or some packages in multiple projects = multiple disk usage).

**Comment by matzeeable** [comment]
Hey!

I'd like to chime in here as well, as I think the idea of Content Addressable Storage is great. Especially in the time of **monorepos**, it makes perfect sense that "deduplication" takes place. I would like to illustrate this with my use case: We have all our coding inside a monorepos, this includes composer packages including dependencies:

![image](https://user-images.githubusercontent.com/1008534/211188870-98bcb461-03ad-400e-b325-c18cbe80bbcd.png)

As you can see, some dependencies are installed in **each of our packages** (e.g. PHPUnit):

![image](https://user-images.githubusercontent.com/1008534/211189041-30e6918c-2b01-4c26-9331-ff18a99642ac.png)

**That's all no problem really, but now, let's get to the problem:** We use a hot cache for our CI images and production builds (i.e. we install all dependencies inside a container before running the CI pipeline and commit the layer for use accordingly). The whole thing runs highly performant since Composer v2 improved the installer (~20 seconds), but the problem is that now each image has ~1 GB:

![image](https://user-images.githubusercontent.com/1008534/211189262-c9a573fe-84d9-4277-bf76-20f621c7c8ac.png)

When I create a container from this hot cache image, it's clear to see that `vendor` folders take up appropriate space per plugin and package (this is not a production install, but dev install - same for PNPM):

![image](https://user-images.githubusercontent.com/1008534/211189426-95d1f227-851a-4ef8-811f-ae1d084d1e6f.png)

**Comment by Seldaek** [comment]
@matzeeable you could also not cache vendor and instead cache `~/.cache/composer` so you have the archives in there ready to unpack which should make the install very fast and deduplicate vendor dirs.

**Comment by matzeeable** [comment]
@Seldaek I may have expressed myself a little wrongly here when I wrote "hot cache". We always prepare our Docker images so that they are already usable without any further install step. This means: Simply pull the Docker image, create the container and the `vendor` folder is immediately there and can be used. This saves us quite a few seconds in the CI, as dependencies do not have to be "checked" again. You have to imagine that within our monorepo we have also created the CI in a very granular way. This means that for example, PHP CS is executed as a separate CI job for each project.

**Just some numbers:** Our CI currently carries out around 200 jobs and growing. Each job takes about 5-15 seconds, thanks to the optimization provided by Docker Image Layers and the fact that we don't need to run `composer install` for each job. If we need to do `composer install` for each job again, this would cost as plus 1-5 seconds again.

For 200 jobs and growing, this could be a plus of 200 * ~3 seconds = **600 seconds**. (when all jobs are executed, they also are granulary controlled on the state "has the package changed?"). Calculations leave out the fact of parallelism in the CI pipeline._

**Comment by anomiex** [comment]
This would be something that would be useful for our monorepo too. In our case most of the projects in our monorepo have various symfony and phpunit packages in each project's vendor dir.

Also, I note that there are really two parts to the proposed structure.

1. You have one directory somewhere, call it `.composer`. For every project in the monorepo, `vendor/some/package` would be a symlink to something like `../../.composer/some/package@1.2.3.0` that holds a copy of version 1.2.3 of some/package. This is very much like how path repositories create symlinks already, just with automatic population of the "path repository".
   * This gives most benefit when you have a lot of projects using the same versions of the same dependencies, as instead of having one copy of the package per project they're all symlinked to a single copy.
2. Within `.composer/some/package@1.2.3.0/`, every file is a hard link to the corresponding file within the content-addressable store.
   * This gives most benefit for cases where there are multiple versions of a package in use where many of the files within that package are unchanged across versions, as each unchanged file is only saved on disk once.

In our case we'd derive most of the benefit from the first part, as we mostly don't have dependencies on different versions of the same packages. If the second part didn't happen, we likely wouldn't notice much difference.

If you want to take "pnpm mode" even further, add in some additional features:

* In the root of the repository, have a definition of which subdirectories hold projects.
  * pnpm itself does this with a ["pnpm-workspace.yaml" file](https://pnpm.io/pnpm-workspace_yaml), while yarn and npm put it in [their equivalent of composer.json in the repo root](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#workspaces).
* Have one `composer.lock` file at the root of the repository covering all the projects, instead of one for each project.
  * pnpm's structure has one section listing projects and which versions of which packages they depend on, and a second section listing each depended-on package+version and the metadata needed to validate cache and reconstruct the `.pnpm` directory (and not e.g. dev dependencies or description fields or the like).
* Running `composer install` in this mode would populate the vendor directories for all projects. The end result would be the same as you'd currently get by running `composer install` individually in each project's directory, but accomplished without paying startup costs and cache re-validation costs and such multiple times.
* Various other commands are also aware of projects, if only to recognize an option to run for all projects instead of just one.

**Comment by DanielRuf** [comment]
@naderman what do you think about this feature proposal?

**Comment by stof** [comment]
being a symlink to `../../.composer/some/package@1.2.3.0` would break things because the package would see installed in `.composer`, not in `vendor`, which would break cases where a package looks for the generated autoloader (as it would not be at `../../autoload.php` anymore) or code treating the `vendor` folder in a special way

**Comment by DanielRuf** [comment]
`autoload.php` wouldn't have to be a symlink, then it would not be a problem. See how pnpm does it with a content addressable approach.

**Comment by stof** [comment]
@DanielRuf In PHP, if a file is at `../../.composer/some/package@1.2.3.0/foo.php` and does `__DIR__.'/../../autoload.php'`, it will resolve `__DIR__` to `../../.composer/some/package@1.2.3.0` even if you were doing `require 'vendor/some/package/foo.php`. The issue is not `autoload.php` being a symlink, but the package source not being inside the `vendor` folder anymore (and yes, `path` repositories do cause issues for such cases, but a project has to explicitly choose to use a path repository)

**Comment by stof** [comment]
the usage of symlinks in pnpm works because node packages never use relative paths escaping their folder to locate other things (the ask the node runtime to resolve some dependencies)

**Comment by DanielRuf** [comment]
I'm not sure I understand correctly.

A symlink is basically like a normal file but links to a different path. pnpm uses hardlinks (yarn also does it like this if accordingly configured) and junctions (in Windows).

For the filesystem this seems like the files still reside in their original location.

> The issue is not autoload.php being a symlink, but the package source not being inside the vendor folder anymore

The issue is about solving this and related issues stemming from such a feature. Otherwise, I can't follow anymore (and what the exact issue is now).

@zkochan do you want to chime in and maybe shed some light on the challenges that you faced and how these were conceptually solved?

**Comment by stof** [comment]
@DanielRuf pnpm deals with the way the node runtime works. Composer deals with the way the PHP runtime works, which is not the same. Asking the pnpm team to help here is useless, as the problem they solved is a **different** one.

**Comment by DanielRuf** [comment]
> @DanielRuf pnpm deals with the way the node runtime works. Composer deals with the way the PHP runtime works, which is not the same. Asking the pnpm team to help here is useless, as the problem they solved is a different one.

I'm fully aware of the differences, but I'm not sure I understand the exact problem now.

If some logic is developed for compoer to support this feature, then it should work, yes?

**Comment by DanielRuf** [comment]
> @DanielRuf pnpm deals with the way the node runtime works. Composer deals with the way the PHP runtime works, which is not the same. Asking the pnpm team to help here is useless, as the problem they solved is a different one.

I'm fully aware of the differences, but I'm not sure I understand the exact problem now.

If some logic is developed for compoer to support this feature, then it should work, correct?

**Comment by stof** [comment]
@DanielRuf the issue is that in the Composer ecosystem, it is very common (and even recommended) to use `__DIR__ . '/../..'` as the way to locate the vendor folder from a file at the root of your package installed as a dependency (for code inside a `bin/` or `src` folder, we would add an extra `../` to account for it). And this is a common need for any package that provide a binary for instance, as their binary (being an entrypoint for the PHP execution) will need to load the generated autoload file.
If the actual location of the package code is `../../.composer/some/package@1.2.3.0` as you suggest, `__DIR__` will **not** be a path inside `vendor/` anymore, breaking this pattern.
And by not being a path in `vendor` anymore, it will also break all cases treating the `vendor` folder in a special way when looking where a class is defined (for instance when filtering code coverage, inspecting stack traces, configuring resource tracking for the automatic cache refreshing of Symfony, etc...).

Composer cannot change the behavior of **PHP** to make it report paths in `vendor` for files that are not actually there.

**Comment by Seldaek** [comment]
Yeah that's actually a good point that makes me even less likely to look into implementing this.. so I guess rather just close it.

**Comment by DanielRuf** [comment]
> we would add an extra ../

That is not true.

I think there is a fundamental misunderstanding of junctions and symlinks. and how a content addressable solution works

**Comment by DanielRuf** [comment]
> If the actual location of the package code is ../../.composer/some/package@1.2.3.0 as you suggest

Not sure where I personally suggested that. That's not how I would do that. For users, PHP and composer it would still look like a "normal" vendor folder.

**Comment by stof** [comment]
hmm, sorry, you were not the one doing the proposal in https://github.com/composer/composer/issues/11132#issuecomment-1611966232

> You have one directory somewhere, call it `.composer`. For every project in the monorepo, `vendor/some/package` would be a **symlink** to something like `../../.composer/some/package@1.2.3.0` that holds a copy of version 1.2.3 of some/package.

**Comment by anomiex** [comment]
>  If the actual location of the package code is `../../.composer/some/package@1.2.3.0` as you suggest, `__DIR__` will **not** be a path inside `vendor/` anymore, breaking this pattern.

All the different levels of `../` seem to have gotten confusing. I may have used the wrong number in my comment earlier. :sweat_smile:

To be more explicit, the directory structure could look something like this to keep things under `vendor/`:
```
monorepo-root/
├ vendor/
│ └ .composer
│   └ some
│     ├ package@1.2.3.0
│     └ package@2.0.0.0
└ packages
  ├ one
  │ └ vendor
  │   └ some
  │     └ package → ../../../../vendor/.composer/some/package@1.2.3.0
  ├ two
  │ └ vendor
  │   └ some
  │     └ package → ../../../../vendor/.composer/some/package@1.2.3.0
  └ three
    └ vendor
      └ some
        └ package → ../../../../vendor/.composer/some/package@2.0.0.0
```
That's similar to what pnpm does with its `.pnpm` directory that's inside the root-level `node_modules/` directory.

> the issue is that in the Composer ecosystem, it is very common (and even recommended) to use `__DIR__ . '/../..'` as the way to locate the vendor folder from a file at the root of your package installed as a dependency (for code inside a `bin/` or `src` folder, we would add an extra `../` to account for it). And this is a common need for any package that provide a binary for instance, as their binary (being an entrypoint for the PHP execution) will need to load the generated autoload file.

Encouraging people to switch to [the `$_composer_autoload_path` global](https://getcomposer.org/doc/articles/vendor-binaries.md#finding-the-composer-autoloader-from-a-binary) (added in Composer 2.2.0) would probably be the best option for binaries to find the right `autoload.php` file.

**Comment by DanielRuf** [comment]
@anomiex thanks for the clarification.

Correct, this would be the better approach and combined with the global it should be possible.

**Comment by Adelagric** [comment]
Measured data point for this thread, since the question left open was whether
the benefit is worth the complexity.

I profiled `composer install` (2.10.3, PHP 8.5, macOS/APFS, hyperfine
medians) on three real projects — Laravel skeleton (109 packages), Symfony
demo (153), Sylius standard (276, 40k files in vendor/):

| scenario | Laravel | Symfony demo | Sylius |
|---|---|---|---|
| no-op (vendor present, lock unchanged) | 1 049 ms | 577 ms | 592 ms |
| warm (dist cache hot, vendor deleted) | 2 695 ms | 2 405 ms | 6 007 ms |
| same, `--no-autoloader` | 2 348 ms | 2 235 ms | 5 739 ms |

Two findings:

- The warm install is not bound by PHP. A throwaway extractor written in a
  compiled language, doing exactly what Composer does (unzip each dist from
  the cache into vendor/, in parallel), took 5 804 ms on Sylius against
  5 856 ms for Composer. The cost is creating ~40k small files, and no
  language fixes that.
- What does fix it is not extracting per project. Extracting each package once
  into a content-addressed store and cloning it into vendor/ brings the file
  placement on Sylius from 5.8 s to 0.73 s (271 `clonefile(2)` calls, one per
  package, on APFS; hardlinks on ext4 give a similar order, reflinks on
  btrfs/xfs the same as APFS). That is the pnpm/uv mechanism, and its gain
  here comes from a single project, not from deduplication across projects —
  so the "we have fewer duplicates than npm" argument doesn't apply to it.

For the record, the full install with that model (store + clone + autoloader)
measures 196 / 182 / 609 ms on the same three projects, i.e. 10-14× on warm
installs, and on a GitHub ubuntu runner 5-9× (Composer is faster on ext4 than
on APFS). The numbers, the scripts and the methodology are in
https://github.com/Adelagric/vivace/tree/main/bench (`bench/M0-profil.md` for
the profile, `bench/ci-bench.sh` for the runner figures).

I realise the maintenance-cost side of the trade-off is yours to weigh; I only
wanted the benefit side to be a measurement rather than a guess. The store can
stay opt-in (`config.store` or similar), and Composer's dist cache already
gives you the immutable input it needs. Happy to answer questions on the
measurements.

**Comment by Seldaek** [comment]
Thanks for the measurements. I have no doubt it is beneficial but what I meant by less duplication is that typically on a dev machine you won't see the same packages used tens of time IMO, and in general waiting a few seconds isn't so dramatic anyway.

The main gain would be on CI workers as they reinstall the same stuff many times, but if you suddenly have all the files extracted in the cache dir, I suspect producing/restoring a cache dir artifact would also take a lot longer than it does now just zipping up a few zip files. So a big question there is whether that offsets the gains or not.

**Comment by Adelagric** [comment]
Fair points on both counts — on a dev machine the dedup is mostly across installs of the *same* project (branch switches, lock updates), and a few seconds is rarely dramatic there.

On the CI cache question I measured it rather than guess, on an ubuntu-latest runner (ext4, 4 vCPU), Sylius (276 packages), `tar | zstd -3` like `actions/cache` does — script and run in [bench/M7-ci-cache.md](https://github.com/Adelagric/vivacity/blob/main/bench/M7-ci-cache.md):

| | zip cache (what Composer caches today) | extracted store |
|---|---|---|
| on disk | 100 MB, 276 files | 403 MB, 40 552 files |
| produce artifact | 0.20 s | 1.0 s |
| restore artifact | 0.16 s | 1.7 s |
| artifact size | 86 MB | 66 MB |

| install, vendor removed | median |
|---|---|
| composer, warm zips | 5.4 s |
| vivacity, warm zips, cold store | 2.1 s |
| vivacity, warm store | 1.0 s |

So your suspicion holds: caching the extracted store costs ~2.4 s more per job to save ~1.1 s at install time — it doesn't pay (the compressed artifact is smaller, but that's the only thing in its favour). Which is why vivacity doesn't do it: the CI artifact stays Composer's zip cache (it reads the same `COMPOSER_CACHE_DIR`), and the store is derived from those zips on the fly, never meant to be cached. What a single-install CI job gets is the warm-zips / cold-store row — 5.4 s → 2.1 s here without changing anything about its cache. The 1.0 s figure only shows up on the second install on the same worker, which is the dev-machine case rather than the CI one.

For what it's worth, the same measurement on macOS/APFS is far worse for the store (15 s produce, 16 s restore): a 40 000-file artifact is exactly the wrong shape for that filesystem.

**Comment by stof** [comment]
> Fair points on both counts — on a dev machine the dedup is mostly across installs of the _same_ project (branch switches, lock updates), and a few seconds is rarely dramatic there.

Not that if only switch branches in the same working directory, there is no need to dedup: composer will not delete existing installed packages if they don't change version (assuming your "branch switch" does not involve deleting the vendor folder of course)

**Comment by Adelagric** [comment]
Right, a branch switch that keeps the versions is a no-op for Composer, and for vivacity too. I picked a bad example — the store pays when a package *comes back*: switching to a branch whose lock has other versions and back again, `rm -rf vendor`, or several checkouts of the same app on one machine. Same-version packages are never touched by either.

**Comment by Seldaek** [comment]
@Adelagric if you're trying to convince us of anything, please use your brain and not an LLM. They're fine to do grunt work but critical thinking is still needed. Anyway leaving this closed..

**Comment by Adelagric** [comment]
Not a native English speaker, hence the polished wording — the numbers are mine. Nothing to convince anyone of; #13075 has a red test on main and speaks for itself.

**Comment by Seldaek** [comment]
That's ok, but I'd rather read broken english than feel like I'm talking to chatgpt.
