### ISSUE TITLE
HOME or COMPOSER_HOME

### ISSUE THREAD

**Issue by Justman10000** [composer/composer#11175]
Hi, after installing Shopware, Symfony is grumbling the following:

> The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly

And yes, the variable is set!

**Comment by Seldaek** [comment]
Maybe it's not set in whichever environment/process you're running composer in?

**Comment by Justman10000** [comment]
> Maybe it's not set in whichever environment/process you're running composer in?

That's the joke! Both are configured!

**Comment by Seldaek** [comment]
Well if it reports this error it is because the Composer process cannot see these env vars, so somehow they are not available. I can't tell you more than this tho.

**Comment by shyim** [comment]
I guess this can be closed.
On some Homebrew installations, the `HOME` variable is not there (maybe clear_env set to true in FPM) so that error occurs. In our application (Shopware) we set since some versions to all installations a `COMPOSER_HOME` with https://github.com/shopware/platform/commit/2813ffcbb7201c456110b03b7396196049b6be29 .
