### ISSUE TITLE
Failed to autoload classes by upgrading composer to `2.5.1`

### ISSUE THREAD

**Issue by seoker** [composer/composer#11245]
My `composer.json`:

```json
{
    "require": {
        "php": "^7.0.0",
        "aws/aws-sdk-php": "3.224.*",
        "facebook/graph-sdk": "5.6.*",
        "google/protobuf": "v3.7.1",
        "grpc/grpc": "1.19.0",
        "justinrainbow/json-schema": "^5.2",
        "mongodb/mongodb": "1.4.*",
        "phpunit/phpunit": "6.5.*"
    },
    "config": {
        "platform": {
            "php": "7.0"
        }
    },
    "autoload": {
        "psr-0": {
            ... // proprietary packages
        },
        "psr-4": {
            "GPBMetadata\\": "./Protobuf/GPBMetadata/",
            "Protobuf\\": "./Protobuf/Protobuf/",
            ... // proprietary packages
        }
    },
    "minimum-stability": "stable"
}

```

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK git version 2.30.1
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.5.1
PHP version: 8.2.0
PHP binary path: /opt/homebrew/Cellar/php/8.2.0/bin/php
OpenSSL version: OpenSSL 1.1.1s  1 Nov 2022
cURL version: 7.87.0 libz 1.2.11 ssl (SecureTransport) OpenSSL/1.1.1s
zip: extension present, unzip present, 7-Zip not available
```

When I launched my program, an error thrown with:

```
PHP Fatal error:  Uncaught TypeError: Return value of Composer\Autoload\ClassLoader::initializeIncludeClosure() must be an instance of Composer\Autoload\void, none returned in /var/app/current/_libs/vendor/composer/ClassLoader.php:580
Stack trace:
#0 /var/app/current/_libs/vendor/composer/ClassLoader.php(112): Composer\Autoload\ClassLoader::initializeIncludeClosure()
#1 /var/app/current/_libs/vendor/composer/autoload_real.php(28): Composer\Autoload\ClassLoader->__construct('/var/app/curren...')
#2 /var/app/current/_libs/vendor/autoload.php(25): ComposerAutoloaderInit8cbab0e9160881f88c44458183518071::getLoader()
#3 /var/app/current/ajax.php(24): require_once('/var/app/curren...')
#4 {main}
  thrown in /var/app/current/_libs/vendor/composer/ClassLoader.php on line 580
```

Though I am using PHP 8 on my dev machine, we're actually running codes with PHP 7.0, and the `ClassLoader.php` in newer version seems to have 7.0 incompatible syntax like:

```php
private static function initializeIncludeClosure(): void // void return types are not allowed in PHP 7.0
{
    if (self::$includeFile !== null) {
        return;
    }

    /**
     * Scope isolated include.
     *
     * Prevents access to $this/self from included files.
     *
     * @param  string $file
     * @return void
     */
    self::$includeFile = static function($file) {
        include $file;
    };
}
```

Reference to RFC: https://wiki.php.net/rfc/void_return_type

**Comment by mbabker** [comment]
See https://github.com/composer/composer/issues/10340

Composer 2.3 and later require PHP 7.2.5 or newer.  If you're deploying to a PHP 7.0 environment, you should be sticking with Composer 2.2.

**Comment by nicolus** [comment]
> Composer 2.3 and later require PHP 7.2.5 or newer. If you're deploying to a PHP 7.0 environment, you should be sticking with Composer 2.2.

Is this the official stance ? It was my understanding that it was possible to building for PHP 7.0 on PHP 8.1 with composer 2.3 by specifying 

```json
    "config": {
        "platform": {
            "php": "7.0"
        }
    }
```

This has worked flawlessly for us for over a year, but it suddenly broke all our workflow when 2.5.1 was released.

**Comment by mbabker** [comment]
That works for forcing the resolver to use PHP 7.0 as the version it checks against, but there aren't version conditional changes in how it dumps files (like the autoloader).  So if it's dumping code that requires PHP 7.2 in a version that doesn't support older PHP versions, your best bet is to use a Composer version supported by your PHP version.

**Comment by nicolus** [comment]
Yeah, that seems to be exactly what's happening. Now the question is : is it intentional or not ?

If it is intentional, it make the platform.php config is a lot less useful than it sounds, and the documentation is misleading because it says : 

>[The platform option] Lets you fake platform packages (PHP and extensions) **so that you can emulate a production env or define your target platform in the config**. Example: {"php": "7.0.3", "ext-something": "4.0.3"}.
>This will make sure that no package requiring more than PHP 7.0.3 can be installed regardless of the actual PHP version you run locally. However it also means the dependencies are not checked correctly anymore, if you run PHP 5.6 it will install fine as it assumes 7.0.3, but then it will fail at runtime. This also means if {"php":"7.4"} is specified; no packages will be used that define 7.4.1 as minimum.
> 
> Therefore **if you use this it is recommended, and safer, to also run the [check-platform-reqs](https://getcomposer.org/doc/03-cli.md#check-platform-reqs) command as part of your deployment strategy**.

This make it sound like it is made precisely for this usecase, and that everything will be fine as long as you check the dependencies on the production environment. I think we should : 
* Add a warning in the documentation that states that this only work as intented if both versions of PHP (the one running locally and the target) are supported by composer)
* Maybe fail when you try to run composer install with a platform.php version that's not supported by composer, just like when the local version is not supported by composer.

On the other hand, if it's not intentional, It should be pretty easy to fix (I think we just need to remove the "void" return type from the `initializeIncludeClosure` method in the Classloader).

I'm fine with both, and I will revert back to 2.2 for the time being, but I think something should be done, since @seoker and me are probably not the only ones who encountered this issue.

**Comment by stof** [comment]
This is intentional, because the Composer runtime API needs to support the target PHP runtime, and Composer 2.3+ requires PHP 7.2+ features so its runtime API does too.

I suggest updating the documentation of the `platform` config to use a newer PHP version than 7.0.3 (one that is supported by Composer 2.3+). And also adding a note about the fact that you still need to use a Composer version compatible with your target runtime due to the composer runtime API.

> On the other hand, if it's not intentional, It should be pretty easy to fix (I think we just need to remove the "void" return type from the `initializeIncludeClosure` method in the Classloader).

Removing that `void` return type might be enough to support PHP 7.0, but more changes will need to be reverted to support older PHP versions (in Composer 2.2 and older, the runtime API is compatible with PHP 5.3+)

**Comment by aschleifer** [comment]
I'm a bit confused. From the first paragraph under https://getcomposer.org/doc/06-config.md#platform I read that it emulates the production environment. Doesn't the autoloader that is later used in that production environment also falls into that definition? In my opinion it doesn't make much sense to control only the loaded dependencies with the `config.platform.php` setting, but not the automatically generated autolaoder. 

If this is really the intended behavior than this needs to be clearly stated and that would mean, at least for us as a company, massive rework in 10+ projects across our business.

**Comment by stof** [comment]
The autoloader is *copied* from the composer source code. So we cannot generate different ones depending on the target platform.

**Comment by aschleifer** [comment]
> The autoloader is _copied_ from the composer source code. So we cannot generate different ones depending on the target platform.

I wasn't aware of that. This needs to be clearly stated in the linked documentation to make anyone aware that the flag does not mean the resulting vendor files will be fully compatible with your target version.

**Comment by Seldaek** [comment]
This is definitely a regression, the autoloader should work on PHP 5.6+ - I'll need to make sure we have some proper tests enforcing this sorry for the mistake. In the meantime yes please use the last 2.4 or 2.2 LTS release.

**Comment by tm-pepe-bawagan** [comment]
For those who don't want to fiddle with their composer version just yet, I was able to temporarily fix my problem by just removing `: void` from the end of `ClassLoader.php:580`

**Comment by Seldaek** [comment]
Composer 2.5.2 fixes this
