### ISSUE TITLE
Checking missing packages in 2.5.0 breaks our workflow

### ISSUE THREAD

**Issue by nickygerritsen** [composer/composer#11241]
My `composer.json`:

(modified to not have proprietary information)

```json
{
    "name": "letstalk/some-web-app",
    "description": "....",
    "type": "project",
    "license": "proprietary",
    "repositories": [
        {
            "type": "composer",
            "url": "https://letstalk.repo.repman.ops.letstalk.nl"
        },
        {
            "type": "vcs",
            "url": "https://github.com/Lets-Talk-NL/composer-extra-assets"
        }
    ],
    "require": {
        "php": ">=7.4",
        "ext-json": "*",
        "ext-intl": "*",
        "cakephp/cakephp": "^3.9.0",
        "cakephp/debug_kit": "^3.17.0",
        "cakephp/migrations": "^2.0.0",
        "cakephp/plugin-installer": "^1.0",
[...]
        "letstalk/cake-json-api": "0.7",
        "letstalk/otsc-tonny": "dev/master",
        "letstalk/restricted-access-debug-kit": "~1.3",
        "letstalk/wrqr-cakephp": "~1.6",
    },
    "require-dev": {
        "cakephp/bake": "^1.9.0",
        "dereuromark/cakephp-ide-helper": "^0.14",
        "friendsofphp/php-cs-fixer": "^2.16",
        "phpstan/phpstan": "^0.12.58",
        "psy/psysh": "@stable"
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/",
[...]
        }
    },
    "scripts": {
[...]
    },
    "extra": {
        "dev-on": "/^(develop|feature.*|post-master-merge.*)$/",
        "dev-able": {
            "letstalk/cake-json-api": "dev-develop",
            "letstalk/wrqr-cakephp": "dev-develop",
            "letstalk/otsc-tonny": "dev/develop"
        }
    },
    "prefer-stable": true,
    "minimum-stability": "dev",
    "config": {
        "sort-packages": true,
        "allow-plugins": {
[...]
            "letstalk/composer-dev-dependency-changer": true
        }
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK git version 2.37.1
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.5.1
PHP version: 7.4.33
PHP binary path: /opt/homebrew/Cellar/php@7.4/7.4.33/bin/php
OpenSSL version: OpenSSL 1.1.1s  1 Nov 2022
cURL version: 7.87.0 libz 1.2.11 ssl (SecureTransport) OpenSSL/1.1.1s
zip: extension present, unzip present, 7-Zip not available
```

When I run this command:

```
composer install --no-interaction --no-scripts --ignore-platform-reqs
```

I get the following output:

```
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
- Required package "letstalk/otsc-tonny" is in the lock file as "dev/develop" but that does not satisfy your constraint "dev/master".
- Required package "letstalk/wrqr-cakephp" is in the lock file as "dev-develop" but that does not satisfy your constraint "~1.6".
This usually happens when composer files are incorrectly merged or the composer.json file is manually edited.
Read more about correctly resolving merge conflicts https://getcomposer.org/doc/articles/resolving-merge-conflicts.md
and prefer using the "require" command over editing the composer.json file directly https://getcomposer.org/doc/03-cli.md#require
```

And I expected this to happen:

So, we have this package `letstalk/composer-dev-dependency-changer` that does the following on PRE_INSTALL_CMD and PRE_UPDATE_CMD:
If the current git branch matches the regex in `extra.dev-on` in composer.json, for each package in `extra.dev-able` change the requirement to what what is said in the `extra.dev-on`.
This allows us to have a tagged version for master / tagged releases but use the develop branch when we are developing.
We have some CI that takes care of updating the .lock on master / develop depending on this.

Now up until 2.4.x this worked; `composer install` didn't verify the lock<->json so it installed what was in the lock. However, now with 2.5.0+ it will not and stop. We need to use `--no-scripts` during this install since this is done at our CI: we run composer install to get all packages installed, which we then ZIP up and deploy to a server. We do not have access to an actual deploy at this time, so we can't run any other post-install-cmd scripts, like clearing caches.

I am not sure if what we do is even supported behaviour, but if so I see two ways of supporting it:
* Allow to specify to only run **some** scripts instead of all/nothing; or
* Add a flag to ignore the lock check

**Comment by hexus** [comment]
This is breaking our pipelines at Claromentis too. There are cases where we simply don't need this lock verification, so it would be great to have a flag to skip this check and retain the previous behaviour of just installing what's in the lock file.

**Comment by stof** [comment]
What you do is clearly not something that was expected to be supported, as you are intentionally generating a corrupted lock file.

**Comment by nickygerritsen** [comment]
I kinda expected this answer 😄 . I wonder if there is a better way of doing what we want to do without being 'illegal'

**Comment by hexus** [comment]
> I kinda expected this answer 😄

Likewise, to be fair 😁 

We simply have some branches of our project that are used for QA only, where we want our QA team to edit `composer.json` and later user `composer update`. Our pipeline runs `composer install` just to make sure the locked dependencies are working and that `composer.json` requirements are at least _valid_, but it's now failing when they make changes to `composer.json` exclusively, without committing an updated lock file (they don't use Composer locally).

I understand from reading comments in other issues that this is considered an edge case, however, and I suppose it's reasonable to expect that `composer.json` is invalid if it's out of sync with `composer.lock`. Personally, I think it would be awesome if it was possible to `composer install` exclusively from a `composer.lock`, without the presence of `composer.json`. 🤓 

However, I think I have an example case that I would have expected to be valid, due to the aliases we use:

```
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
- Required package "claromentis/some-project" is in the lock file as "v9.0.x-dev" but that does not satisfy your constraint "dev-improvement/some-dev-branch as 9.0.x-dev".
```

Here, the locked version is `v9.0.x-dev`, and the `composer.json` version is some dev branch aliased to `9.0.x-dev`. Is the alias intended to be ignored? I've tried with and without the `v` prefix, so that doesn't appear to be the issue; I know Composer handles such prefixes well anyway. For clarity, the actual branches in this case would be named `v9.0` and `improvement/some-dev-branch`.

**Comment by stof** [comment]
the composer.lock does not copy all the metadata from the composer.json (the root package does not appear in it).

> Here, the locked version is v9.0.x-dev, and the composer.json version is some dev branch aliased to 9.0.x-dev. Is the alias intended to be ignored?

`dev-improvement/some-dev-branch as 9.0.x-dev` means you actually want to have `dev-improvement/some-dev-branch` installed (but it should be considered to satisfy constraints that 9.0.x-dev can satisfy). That does not mean that installing 9.0.x (as locked) is valid to satisfy this requirement.

**Comment by hexus** [comment]
Fair enough. It makes sense, just a bit of a PITA for our workflow.

We had been working on the belief that `composer install` only really cares about the locked dependencies, and that `composer update` is used to update `composer.lock` to suit `composer.json` requirements. This stems purely from the description of `composer install`:

```
$ composer install --help
Description:
  Installs the project dependencies from the composer.lock file if present, or falls back on the composer.json
```

This has fundamentally changed with this new check, but I suppose it's for the best for the majority of users.

**Comment by stof** [comment]
The composer.json has always been used as part of the install.

Note that the help of `composer install` should be improved to better describe the fallback when there is no lock file (which is really running a `composer update` instead)

**Comment by hexus** [comment]
> The composer.json has always been used as part of the install.

Indeed it has, despite the help text describing the contrary.

It had never before been used to _enforce_ consistency with the lock file, however. This new check is now unavoidable, but the previous behaviour was actually helpful during development when project dependencies may change multiple times per day.

**Comment by stof** [comment]
Well, the old behavior was also the root cause of bugs where composer would never tell you that your lock file does not actually install the dependencies you have in your composer.json (a case that would impact you after a wrong resolution during a git merge for instance)

**Comment by Seldaek** [comment]
Yeah I don't think we want to revert this as it is quite an important integrity-check behavior and it was really just an omission that it wasn't checked previously.

So now one question for you.. If you do update the lock file already, why are you not also updating the composer.lock so the requires match what versions you are changing the lock to?

It still smells of a bad workflow to me, but if you're anyway gonna be hacking into the lock file I guess editing the json as well on top of it isn't so bad.

**Comment by hexus** [comment]
Our development team update the lock file when we actually want to lock dependencies for a release, but our QA team doesn't use Composer with version control. We never change the lock file manually though, only `composer.json` to change requirements. 

Indeed, I agree that it's just a workflow that needs improving, and the more I've thought about it the more I realise the importance of the check. It makes `composer install` more reliable; more "correct". My workaround for our CI/CD pipeline was to simply use `composer update` on our QA branches instead of `composer install`. This mirrors our deployment process for QA systems anyway. Problem solved. 🙃 

Thanks for the feedback and explanations for the new behaviour. We've never had a bad merge of a lock file ourselves, because our workflow for merging is quite sound, but I'm sure the check will save us (and many others) from a mistake in the future!
