### ISSUE TITLE
Cannot make branch alias for dev-master (renaming master to main)

### ISSUE THREAD

**Issue by danepowell** [composer/composer#11301]
As you've probably noticed, many projects are renaming `master` to `main`. This has caused a lot of problem for consumers of those libraries using the `dev-master` version.

Specifically, my project uses `dealerdirect/phpcodesniffer-composer-installer:dev-master`. That package renamed `master` to `main`, causing my builds to fail. I thought "no problem, I'll just submit a PR for phpcodesniffer-composer-installer to add a branch alias for `dev-master` to fix everyone's builds".... but it turns out that's not possible, because the branch-alias can only be a numbered version ending in `-dev`.

So I'm wondering how projects can rename branches without causing massive disruption to consumers.

My `composer.json`:

```json
{
  "name": "dealerdirect/phpcodesniffer-composer-installer",
  "description": "PHP_CodeSniffer Standards Composer Installer Plugin",
  "type": "composer-plugin",
  "keywords": [
    "composer", "installer", "plugin",
    "phpcs", "phpcbf", "codesniffer", "phpcodesniffer", "php_codesniffer",
    "standard", "standards", "style guide", "stylecheck",
    "qa", "quality", "code quality", "tests"
  ],
  "homepage": "http://www.dealerdirect.com",
  "license": "MIT",
  "authors": [
    {
      "name": "Franck Nijhof",
      "email": "franck.nijhof@dealerdirect.com",
      "homepage": "http://www.frenck.nl",
      "role": "Developer / IT Manager"
    },
    {
      "name" : "Contributors",
      "homepage" : "https://github.com/PHPCSStandards/composer-installer/graphs/contributors"
    }
  ],
  "support": {
    "issues": "https://github.com/PHPCSStandards/composer-installer/issues",
    "source": "https://github.com/PHPCSStandards/composer-installer"
  },
  "require": {
    "php": ">=5.4",
    "composer-plugin-api": "^1.0 || ^2.0",
    "squizlabs/php_codesniffer": "^2.0 || ^3.1.0 || ^4.0"
  },
  "require-dev": {
    "ext-json": "*",
    "ext-zip": "*",
    "composer/composer": "*",
    "phpcompatibility/php-compatibility": "^9.0",
    "php-parallel-lint/php-parallel-lint": "^1.3.1",
    "yoast/phpunit-polyfills": "^1.0"
  },
  "minimum-stability": "dev",
  "prefer-stable": true,
  "autoload": {
    "psr-4": {
      "PHPCSStandards\\Composer\\Plugin\\Installers\\PHPCodeSniffer\\": "src/"
    }
  },
  "autoload-dev": {
    "psr-4": {
      "PHPCSStandards\\Composer\\Plugin\\Installers\\PHPCodeSniffer\\Tests\\": "tests/"
    }
  },
  "extra": {
    "class": "PHPCSStandards\\Composer\\Plugin\\Installers\\PHPCodeSniffer\\Plugin",
    "branch-alias": {
      "dev-main": "dev-master"
    }
  },
  "scripts": {
    "install-codestandards": [
      "PHPCSStandards\\Composer\\Plugin\\Installers\\PHPCodeSniffer\\Plugin::run"
    ],
    "lint": [
      "@php ./vendor/php-parallel-lint/php-parallel-lint/parallel-lint . -e php --exclude vendor --exclude .git"
    ],
    "test": [
      "@php ./vendor/phpunit/phpunit/phpunit --no-coverage"
    ],
    "coverage": [
      "@php ./vendor/phpunit/phpunit/phpunit"
    ]
  }
}

```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
extra.branch-alias.dev-main : the target branch (dev-master) must end in -dev
Checking platform settings: OK
Checking git settings: OK git version 2.39.1
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: You are not running the latest stable version, run `composer self-update` to update (2.4.1 => 2.5.2)
Composer version: 2.4.1
PHP version: 8.1.14
PHP binary path: /usr/local/Cellar/php@8.1/8.1.14_1/bin/php
OpenSSL version: OpenSSL 1.1.1s  1 Nov 2022
cURL version: 7.87.0 libz 1.2.11 ssl (SecureTransport) OpenSSL/1.1.1s
zip: extension present, unzip present, 7-Zip not available
```

When I run this command: 

```
composer validate
```

I get the following output: 

```
- extra.branch-alias.dev-main : the target branch (dev-master) must end in -dev
```

And I expected this to happen:

dev-master to be a supported alias

**Comment by Seldaek** [comment]
Well relying on named branches is fairly dangerous, as you can have major changes happening at any time. That's why we introduced the concept of branch aliases, so dev-main can be aliased to 1.x-dev in the dealerdirect/phpcodesniffer-composer-installer case for example, then you can require it as `1.x-dev` or even better `^1.1@dev` for example right now if you need unreleased new features (1.0.0 being latest stable), so that tells composer I need the 1.1 release of that package, but also I'll take a dev version if needed. `1.x-dev` (seen as `1.9999999.9999999` internally)  matches `^1.1` so it'll install dev-main right now, but once 1.1.0 is tagged it would go back to stable tags if you have `prefer-stable:true`, or if a package using yours as dependency does not allow dev packages for example.

Requiring dev-main directly breaks all of this, so it is not a good idea.

If consumers require packages correctly, and the publisher had an alias for dev-master previously, then renaming should be pain-free as dev-main would get the same numeric alias as dev-master had, and everything keeps working.

I realize this may not help you solve anything right now because once it's done it's too late, but hopefully this clarifies things and you and others can learn from this.

**Comment by Seldaek** [comment]
The point of aliasing is to become compatible with numeric constraints. You don't really need an alias for named constraints because named constraints only ever match one exact name.

I can definitely see how it would lead to confusion though if you take it as a plain aliasing feature to alias anything. But I'd rather not add this at this stage. Improving docs definitely would be good I agree.
