### ISSUE TITLE
Caching improvement - prevent calls of metadata-url API unless the root packages.json is modified.

### ISSUE THREAD

**Issue by vtsykun** [composer/composer#11323]
I've noticed that composer makes unnecessary metadata API calls if the root `packages.json` is not modified [304].
Can we say if the `packages.json` return 304, then all the packages in the composer repository will also not be changed?
Just this would be a very nice caching improvement.

**Actual Behavior**
Composer checks all packages via API v2 even if the root `packages.json` hasn't been changed.

```
No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.
Loading composer repositories with package information
Reading /home/vm123456/.cache/composer/repo/http---j33erf55nuwjvgsrs6eoxxxxxxxxxai3lzc477azj5xeb5a6cm4rq.b32.i2p/packages.json from cache
Warning: Accessing j33erf55nuwjvgsrs6eoxxxxxxxxxai3lzc477azj5xeb5a6cm4rq.b32.i2p over http which is an insecure protocol.
Using HTTP basic authentication with username "admin"
Downloading http://j33erf55nuwjvgsrs6eoxxxxxxxxxai3lzc477azj5xeb5a6cm4rq.b32.i2p/packages.json using proxy (127.0.0.1:4444) if modified
[304] http://j33erf55nuwjvgsrs6eoxxxxxxxxxai3lzc477azj5xeb5a6cm4rq.b32.i2p/packages.json
Reading /home/vm123456/.cache/composer/repo/http---j33erf55nuwjvgsrs6eoxxxxxxxxxai3lzc477azj5xeb5a6cm4rq.b32.i2p/provider-lib123~flotr2.json from cache
Downloading http://j33erf55nuwjvgsrs6eoxxxxxxxxxai3lzc477azj5xeb5a6cm4rq.b32.i2p/p2/lib123/flotr2.json using proxy (127.0.0.1:4444) if modified
[304] http://j33erf55nuwjvgsrs6eoxxxxxxxxxai3lzc477azj5xeb5a6cm4rq.b32.i2p/p2/lib123/flotr2.json
Built pool.
Running pool optimizer.
Updating dependencies
Generating rules
Resolving dependencies through SAT
Looking at all rules.

Dependency resolution completed in 0.000 seconds
Analyzed 101 packages to resolve dependencies
Analyzed 101 rules to resolve dependencies
Lock file operations: 1 install, 0 updates, 0 removals
Installs: lib123/flotr2:1.0.0
  - Locking lib123/flotr2 (1.0.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Reading ./composer.lock (/var/www/project1/composer.lock)
Package operations: 1 install, 0 updates, 0 removals
Installs: lib123/flotr2:1.0.0
Reading /home/vm123456/.cache/composer/files/lib123/flotr2/276a5997813878d95318a72d5789e6d29737aa6f.zip from cache
  - Loading lib123/flotr2 (1.0.0) from cache
  - Installing lib123/flotr2 (1.0.0): Extracting archive
Executing async command (CWD): '/usr/bin/unzip' -qq '/var/www/project1/vendor/composer/tmp-60d9532eba11010072c9546e57a15396.zip' -d '/var/www/project1/vendor/composer/4996a9ea'
Downloading http://j33erf55nuwjvgsrs6eoxxxxxxxxxai3lzc477azj5xeb5a6cm4rq.b32.i2p/downloads/ using proxy (127.0.0.1:4444)
[201] http://j33erf55nuwjvgsrs6eoxxxxxxxxxai3lzc477azj5xeb5a6cm4rq.b32.i2p/downloads/
```

**Comment by stof** [comment]
the root packages.json does not require being updated each time one of the package metadata is updated in the v2 format (which is one of the reasons why packagist.org can now dump the metadata of new packages almost immediately when a package is updated instead of having to batch the updates in a cronjob to avoid concurrent updates of the files).

For packagist.org, the root file is updated only when dumping the updated v1 metadata, which happens much less frequently (or when forcing a dump due to deploying a new version of the other root metadata)

So no, we cannot assume that a 304 on the root file will imply a 304 on all packages (not even counting the fact that your composer cache might have older content for some package endpoints if they were queried at an older time than the root file)

**Comment by stof** [comment]
Note that if the root file was touched each time another file is dumped, this would actually *hurt* caching, as it would be invalidated each time a commit is done in any package registered on Packagist (and using a webhook to update the metadata immediately on Packagist, which is the recommended setup)

**Comment by vtsykun** [comment]
Yes, I see. I had a problem with using composer for my private repository via i2p tunnel for security. Composer cannot reuse current connection without http v2, so packages installations works slowly due to network specification. It would be great to have some package metadata-batch API to request only changed packages. I think this feature would be very useful for private `packagist.com` or the other repository implementors

**Comment by stof** [comment]
A batch endpoint would have to be dynamic (as returning the whole metadata of packagist is a single response would be insane as that would be several GB). And that would require a lot more server resources than the current infrastructure serving static files.
So this seems unlikely to happen.

And doing an endpoint where you could give a list of packages with the local cache modification time to know which ones are outdated would not help much here. Composer would still have to call it many times, because the list of packages it needs is built incrementally (when receiving responses for some packages, it discovers which dependencies they might need)
