### ISSUE TITLE
GitDriver requires a usable cache directory, and it looks like you set it to be disabled

### ISSUE THREAD

**Issue by Arr-n-D** [composer/composer#11345]
Inside of a php:8.1-apache Docker image, I fetch composer via CURL like so
``
curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
``
I then attempt to install my packages after copying my composer.json and my composer.lock via the command
``
RUN composer install --ignore-platform-reqs --no-cache \
&& composer dump-autoload
``

While building the image, after the downloading of packages, and after receiving the `Use the composer fund command to find out more!` message, the installation fails with the error 

``
#15 61.08 In GitDriver.php line 52:
#15 61.08
#15 61.08   GitDriver requires a usable cache directory, and it looks like you set it to be disabled
``

I've also attempted to set a COMPOSER_CACHE_DIR environment variable to no success.

**Comment by stof** [comment]
Well, the `--no-cache` CLI flag wins by disabling the cache

**Comment by Arr-n-D** [comment]
Correct me if I'm wrong but isn't --no-cache supposed to allow me to always fetch the repositories from the repositories instead of fetching from cache?

**Comment by stof** [comment]
But GitDriver is not able to read the metadata of a git repository without cloning it in the cache to be able to run a bunch of git commands.

If you want to be able to run without cache, the repositories registered in your project should only be ones that don't require a usable cache. This includes the `composer` type (used for packagist.org and any other metadata repository exposing metadata directly in the composer format), the `package` type (where all metadata are inline in your composer.json file) and the `vcs` type when the metadata can be loaded from an API (GitHub, Gitlab or Bitbucket) instead of using the GitDriver fallback.
