### ISSUE TITLE
Request for comment - Towards better reproducibility outputs

### ISSUE THREAD

**Issue by drupol** [composer/composer#11422]
Hello,

As a developer working with Nix and PHP daily, I've noticed an opportunity to improve the reproducibility rate of the `composer install` command.
I believe that enhancing reproducibility is important because it ensures consistency across different installations, promotes trust among developers, and facilitates collaboration, debugging, and learning.  By enhancing it, we can foster a more reliable and collaborative development environment, ensuring that our software remains consistent, dependable and predictable.

I've observed that the output of the sha256sum calculation varies between two runs of the `composer install` command. This can be demonstrated with the following steps:

```shell
$ git clone git@github.com:nyholm/psr7.git
$ cd psr7
$ composer install
$ dir=. find "$dir" -type f -exec sha256sum {} \; | LC_ALL=C sort -d | sha256sum
7329b99157848d8ea4c33376ebfa484bb1619adefb04233aaa8989182118c8da
$
```

Then, remove `vendor` and `composer.lock` and retry the same set of commands:

```shell
$ git clone git@github.com:nyholm/psr7.git
$ cd psr7
$ composer install
$ dir=. find "$dir" -type f -exec sha256sum {} \; | LC_ALL=C sort -d | sha256sum
486cbf6ab5ce3b4ef472de0e099df0a830c14f1effcd06e9ff6eacaabea0bd09
$
```

A possible solution to address this issue is to add the following configuration:

```json
,
    "config": {
        "autoloader-suffix": "NyholmPsr7"
    }
```

By implementing this change, the sha256sum calculation demonstrates consistency across multiple executions of the `composer install` command.

I'm initiating this issue to solicit feedback and engage in a discussion regarding potential solutions to enhance reproducibility. From my standpoint, there are several viable strategies:

1. Derive the `autoloader-suffix` from specific, yet-to-be-determined attributes within the `composer.json` file.
2. Employ a prefix derived from a checksum of all dependency files.

I acknowledge that there may be alternative solutions to address this issue that I have not considered. I encourage you to share your insights and contribute to the conversation.

Thank you.

**Comment by drupol** [comment]
I just notice that there was already an issue about that at https://github.com/composer/composer/issues/9768

Let me know if things have changed since then and if there are room for improvements.

**Comment by stof** [comment]
The goal of having a random suffix by default is because that reduces the risk of issues in case multiple generated autoloaders are loaded in the same process (as that only works fine if they have different suffixes), which is a case that happens regularly when you have a tool installed globally or from a phar that also loads the project-level autoloader.
Using a checksum of all dependency files would be quite costly to compute and would not solve that (it is totally possible to have 2 projects using the same dependencies will still being different).

Projects wanting a reproducible install can configure a `autoloader-suffix` explicitly (side note: if you care about reproducibility, you should not remove the lock file as an install without lock file is actually an update, and updates are definitely not meant to be reproducible).

**Comment by drupol** [comment]
Fair enough, thanks.

**Comment by drupol** [comment]
Just to summarize:

[![php composer reproducibility matrix](https://planttext.com/api/plantuml/png/hP7D2i8m48JlUOg0ju3w0gKKl7YIujNsa3IhHjDisAHetzxK7ugWFVMukxFVC4mHegJO6gTRwHaBL-CuOG3612-tPUKssFeqK-K8FA7k6gECDR5F2i7ta8uc8lMLorH-C_7Cc_V7oc9ppTOgJq8nRYy1tIYMNKIBKWCjFS7Ht3yFuh0u4O2h1u-dhrGM9b3OnKaQWQxv3YEdRzwl30DhjXZ_ZESDmWf87RvwV000)](https://planttext.com/?text=hP7D2i8m48JlUOg0ju3w0gKKl7YIujNsa3IhHjDisAHetzxK7ugWFVMukxFVC4mHegJO6gTRwHaBL-CuOG3612-tPUKssFeqK-K8FA7k6gECDR5F2i7ta8uc8lMLorH-C_7Cc_V7oc9ppTOgJq8nRYy1tIYMNKIBKWCjFS7Ht3yFuh0u4O2h1u-dhrGM9b3OnKaQWQxv3YEdRzwl30DhjXZ_ZESDmWf87RvwV000)
