### ISSUE TITLE
php-64bit should throw an error on install if sub-packages require it

### ISSUE THREAD

**Issue by pabloelcolombiano** [composer/composer#11468]
First of all thanks for your great work!

I have an issue with php-64bit. Here is an example:

On [cakephp/migrations](https://github.com/cakephp/migrations/blob/3.x/composer.json), we have `composer.json`:

```json
...
"require": {
      "php": ">=7.4.0",
      "robmorgan/phinx": "^0.13.2"
    ...
  },
...
```

and on [cakephp/phinx](https://github.com/cakephp/phinx/blob/0.x/composer.json): 
```json
"require": {
    "php-64bit": ">=7.3",
    ...
},
...
```

Output of `composer diagnose`:

```
Checking composer version: OK
Composer version: 2.5.5
PHP version: 7.4.33
```

When I run the `composer update`  on cakephp/phinx, I see as expected an error.
But when running the same command on cakephp/migrations, there is no error nor warning.

I would expect that being in 32 bit, `composer update` on a package requiring a package, itself requiring php-64bit would fail.

So technically, I can install a package on a 32 bit system, without knowing that it will eventually fail.

Is there a way to prevent that?

**Comment by glaubinix** [comment]
The only version of robmorgan/phinx that requires php-64bit is [0.x-dev ](https://packagist.org/packages/robmorgan/phinx#0.x-dev). Your Composer update command in the project using cake/migrations, unless otherwise specified, will try to install a stable version of robmorgan/phinx and not a dev version. The exact version will be shown to you during the Composer command.
