### ISSUE TITLE
Regression: phpstan/rules.neon missing in distributed release.

### ISSUE THREAD

**Issue by cmlara** [composer/composer#11507]
In #10813 the phpstan/rules.neon file was included in the distribution to allow re-use in composer plugins, this was regressed while merging #11484 which did not keep the exclusion.

**Comment by mglaman** [comment]
The file _does_ say: https://github.com/composer/composer/blob/main/phpstan/rules.neon#L1-L4

```
# Composer-specific PHPStan extensions
#
# These can be reused by third party packages by including 'vendor/composer/composer/phpstan/rules.neon'
# in your phpstan config
```

**Comment by fredden** [comment]
@mglaman if the file is not included in the ZIP export by GitHub, then they won't exist in `vendor/` to be referenced.

**Comment by mglaman** [comment]
I know. The `gitattributes` needs to allow this file. Sorry I should have been more clear:

+1 to this issue, the file even documents that it should be included.

**Comment by drupol** [comment]
> +1 to this issue, the file even documents that it should be included.

True, but since this file is not required at Composer runtime, I removed it.

In the meantime, you could use `composer require composer/composer --prefer-source` and the file will be available again.

**Comment by mglaman** [comment]
I think it's perfectly fine to allow this file instead of requiring the package by source. The others are Composer dev config but this file is public

**Comment by drupol** [comment]
> I think it's perfectly fine to allow this file instead of requiring the package by source. The others are Composer dev config but this file is public

Yes it is fine, there's nothing wrong including any file actually.

The idea behind what I did is to remove all the files not required for Composer runtime to reduce the package size. Given the amount of times Composer is installed, those small changes can make a difference.

Now, to come back to your issue, it seems that just requiring `composer/composer` in `require-dev` will download a zip archive from Github. Since that zip is created from Git, the PHPStan files are filtered out.

I guess you agree that usually we need PHPStan during development phase, not while in production. Therefore, doing `composer install --prefer-source` could be an option.

Maybe @Seldaek has a point of view on this as well?

**Comment by cmlara** [comment]
I will also add, that the composer.json publishes the rules file as registered for phpstan/extension-installer to detect and execute.

https://github.com/composer/composer/blob/main/composer.json#L70-L74
```
        "phpstan": {
            "includes": [
                "phpstan/rules.neon"
            ]
        }

```

Regarding preferring source vs packaged: I would argue that is actually not a proper PHPStan run at that point. If some files are in source but not in the packaged release we run the risk of false-negatives that PHPStan should detect. 

An example being if some how a class is intended for debug only and is not in the packaged composer/composer release, but is accidentally used PHPSstan would not detect the missing class if you used source distribution which could lead to a failure when pushed to production without ` --prefer-source`

**Comment by stof** [comment]
I would be in favor of keeping the file (which is quite small anyway) to have things well-behaving.

An install of the `composer/composer` package should mostly happen for composer plugin developers, for which the file is useful. If we force them all to install from source, we _increase_ the size of the download/install instead of decreasing it.
Most _users_ of composer will not install the `composer/composer` package. They will download the phar.

**Comment by Seldaek** [comment]
Yeah I'd definitely rather keep the file, I missed that when reviewing. Glad it got caught before ending in an actual release 👍🏻

**Comment by danepowell** [comment]
I think this continued to be broken after #11508. See #11586 for a second fix.
