### ISSUE TITLE
is there a way to get notified whenever composer hash changes

### ISSUE THREAD

**Issue by imdmahajankanika** [composer/composer#11528]
Is there a way to get notified whenever composer hash changes

**Comment by fredden** [comment]
@imdmahajankanika can you describe how you would like to receive these notifications? Should the notification come from the composer binary running on a developer's computer, or from the version control system, or some other monitoring system? Should the notification come through the existing event system that Composer provides, so that plug-ins can choose to listen/consume the same?

**Comment by imdmahajankanika** [comment]
> @imdmahajankanika can you describe how you would like to receive these notifications? Should the notification come from the composer binary running on a developer's computer, or from the version control system, or some other monitoring system? Should the notification come through the existing event system that Composer provides, so that plug-ins can choose to listen/consume the same?

Hello @fredden actually, we are using composer hash in our builds préprod and prod and whenever composer hash changes, the build fails. So we are wondering if there is any way to get notified or receive warning regarding the hash update so that in advance we can update it in our builds without breaking anything.

**Comment by fredden** [comment]
At what step in the development process would you like to get notified? It sounds like there is a problem with your build process if it fails when the content-hash changes.

**Comment by imdmahajankanika** [comment]
> At what step in the development process would you like to get notified? It sounds like there is a problem with your build process if it fails when the content-hash changes.

Actually, the build process is in fact the execution of dockerfile and in the dockerfile, we have a step to download the composer to execute the command "composer install", but if the hash changes, the composer download fails and so the build.

**Comment by fredden** [comment]
I think I've misunderstood. I thought you were talking about the `content-hash` line in `composer.lock`, but it seems that perhaps you're talking about the verification of a downloaded file. Are you asking about the hash listed on https://getcomposer.org/download/ ?

In my `Dockerfile`s, I use this to get Composer: `COPY --from=composer /usr/bin/composer /usr/bin/composer`. Perhaps you could use this approach instead.

Alternatively, the file content (and therefore its hash) should only change when the version changes. Perhaps you want to download a specific version and check its hash, rather than getting the "latest" which will by design link to a different file from time to time.

**Comment by fredden** [comment]
GitHub can send a notification when a new release is published. On this page https://github.com/composer/composer, choose 'watch' (or 'unwatch'), then 'custom', then select 'releases', then 'apply'.
![Screenshot_2023-06-28_14-04-45](https://github.com/composer/composer/assets/334786/d6914fcd-ddaf-43cb-810e-78bf13c881af)

**Comment by Seldaek** [comment]
To avoid installer hash issues please see https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md

And if you're just copying from our archives, please use https://hub.docker.com/r/composer/composer/tags which has `-bin` suffixed archives containing only the composer file, see https://blog.codito.dev/2022/11/composer-binary-only-docker-images/ for more details but e.g. you can do `COPY --from=composer/composer:2-bin /composer /usr/bin/composer` which is much faster as the image is smaller.

**Comment by imdmahajankanika** [comment]
> To avoid installer hash issues please see https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md
> 
> And if you're just copying from our archives, please use https://hub.docker.com/r/composer/composer/tags which has `-bin` suffixed archives containing only the composer file, see https://blog.codito.dev/2022/11/composer-binary-only-docker-images/ for more details but e.g. you can do `COPY --from=composer/composer:2-bin /composer /usr/bin/composer` which is much faster as the image is smaller.

@Seldaek Thank You! I will test it.
