### ISSUE TITLE
Longer backtrace when installed using 2.6.0

### ISSUE THREAD

**Issue by mvorisek** [composer/composer#11615]
with composer 2.6.0/2.6.1:

CI output with composer 2.6.1: https://github.com/atk4/core/actions/runs/6053504555/job/16429145566#step:8:154

repro: https://github.com/atk4/core/commit/3a60dd943aaeb955d9bd5c86bfdb583cc93bbe98 - one phpunit test is failing

---

with composer 2.5.8:

CI output with composer 2.5.8: https://github.com/atk4/core/actions/runs/6053551255/job/16429280994#step:8:139

repro: https://github.com/atk4/core/commit/d54a022841067014d48015660459139e7c53a8ef - phpunit tests are passing

---

the 1st repro is different from the 2nd only in the composer version

maybe this change is wanted/needed, but please confirm, I find lower backtrace depth better

**Comment by stof** [comment]
the links you gave are comparing a stack trace with a display of the content of a file, not with another stack trace

**Comment by mvorisek** [comment]
yes, but solely with different composer version the results are different, same php version (docker image) and same deps

**Comment by stof** [comment]
Among your 2 links, one shows a stacktrace for a PHPUnit failure (running `vendor/bin/phpunit --exclude-group none --no-coverage -v`) while the other shows the output of `cat /__w/core/core/vendor/bin/phpunit`. there is no point comparing those.

**Comment by mvorisek** [comment]
> Among your 2 links, one shows a stacktrace for a PHPUnit failure (running `vendor/bin/phpunit --exclude-group none --no-coverage -v`) while the other shows the output of `cat /__w/core/core/vendor/bin/phpunit`. there is no point comparing those.

I tried to debug the issue with that, see regular CI jobs: https://github.com/atk4/core/actions, the last 4 unit tests failures are since the docker image was updated with composer 2.6.1. Unchanged https://github.com/atk4/core repo should be enough to reproduce.

**Comment by mvorisek** [comment]
I diffed whole vendor after install with composer 2.5.8/2.6.1 and the whole difference is https://github.com/composer/composer/pull/11562.

**Comment by Seldaek** [comment]
I referenced this in https://github.com/sebastianbergmann/phpunit/issues/5447 - which is the reason we did this fix. I am not sure however what is causing your problem. What is rendering the backtrace you are checking against? Is this in PHPUnit or are you rendering the backtrace some other way? I think the issue is normally the `$_SERVER['SCRIPT_NAME']` gets cleaned out of the backtrace perhaps and now it doesn't work anymore? Or something like that.. I'm not sure. It'd be good if you can figure out the root cause so we can see what can be done.
