### ISSUE TITLE
Version 2.6.0 broke executable of editorconfigchecker

### ISSUE THREAD

**Issue by janedbal** [composer/composer#11612]
See CI pipelines executed on the **same commit** before and after upgrade:

- before (2.5.8): [pipeline](https://github.com/shipmonk-rnd/name-collision-detector/actions/runs/6046806405/attempts/1) ([job](https://github.com/shipmonk-rnd/name-collision-detector/actions/runs/6046806405/job/16409044845))
- after (2.6.0): [pipeline](https://github.com/shipmonk-rnd/name-collision-detector/actions/runs/6046806405/attempts/2) ([job](https://github.com/shipmonk-rnd/name-collision-detector/actions/runs/6046806405/job/16413469154)) 

The `ec` there refers to [this library](https://github.com/editorconfig-checker/editorconfig-checker.php).

**Comment by stof** [comment]
My guess is that this is caused by https://github.com/composer/composer/pull/11557

By forcing to use `sh`, it does not rely on the shebang anymore, and so would not use `bash` anymore (btw, if your script is written in an entirely different language for instance with a shebang saying `#!/usr/bin/env python`, things would be even worse as some bash scripts could be compatible with the more restricted `sh` and work by luck)

**Comment by stof** [comment]
/cc @Seldaek 

Either the PR should be reverted or it should be reworked to respect the shebang that would get bypassed.

**Comment by Seldaek** [comment]
Right, reverted in 5fae76ce6

**Comment by Seldaek** [comment]
2.6.1 released with the revert

**Comment by janedbal** [comment]
Thank you for such a fast fix!
