### ISSUE TITLE
Why does `composer bump` not work for minor wildcards

### ISSUE THREAD

**Issue by bendavies** [composer/composer#11640]
Hi,

Just wondering what was the motivation behind `bump` not working on [minor wildcards](https://github.com/composer/composer/blob/3bc72f75cbfc43b25ba4fb6013449b69cf29fc66/tests/Composer/Test/Package/Version/VersionBumperTest.php#L63).

We use [malukenho/mcbumpface](https://github.com/malukenho/mcbumpface) and I thought `bump` could replace it, but it seems not.

When requiring symfony packages with flex, they will come in like
`symfony/lock => 6.3.*` and then `bump` will not modify the constraint the constraint.

Thanks,
Ben

**Comment by stof** [comment]
Well, `bump` about bumping the lowest bound of the constraint but it tries to preserve the kind of constraint used as input so that it can still output a pretty constraint (normalized constraints are ugly as Composer deals with 4 parts in versions internally). The current implementation does that by using the same kind of constraint as output than given as input.
For a wildcard constraint, there is no way to bump it will keeping it a wildcard.

**Comment by Seldaek** [comment]
Yeah that seems more like something to report to flex really, I don't know why they use such constraints instead of ^6.3.

**Comment by Seldaek** [comment]
But I see your point, we upgrade 2.* to ^2.4, so maybe we should also upgrade minor wildcards.. 

However, switching to ^6.3 would change the meaning as it allows 6.4+ which 6.3.* did not. Switching to ~6.3.3 would be better but so many people are confused by `~` that I rather not do this.
