### ISSUE TITLE
Don't include PHP 5.6 compat in autoload when require php > 5.6

### ISSUE THREAD

**Issue by kkmuffme** [composer/composer#11660]
My `composer.json`:

```json
{
    "name": "foo/bar",
    "require": {
        "x/y": "^2.0.",
        "php": "^7.0"
    },
    "config": {
        "optimize-autoloader": true,
        "classmap-authoritative": true
    }
}
```

When php >=5.6 is required, then it's unnecessary to add this to autoload, as this cannot happen normally (since any composer install,... would have failed previously, and if you didn't install but have this in a package, then this will be the least of your problems)

```
if (PHP_VERSION_ID < 50600) {
    if (!headers_sent()) {
        header('HTTP/1.1 500 Internal Server Error');
    }
    $err = 'Composer 2.3.0 dropped support for autoloading on PHP <5.6 and you are running '.PHP_VERSION.', please upgrade PHP or use Composer 2.2 LTS via "composer self-update --2.2". Aborting.'.PHP_EOL;
    if (!ini_get('display_errors')) {
        if (PHP_SAPI === 'cli' || PHP_SAPI === 'phpdbg') {
            fwrite(STDERR, $err);
        } elseif (!headers_sent()) {
            echo $err;
        }
    }
    trigger_error(
        $err,
        E_USER_ERROR
    );
}
```

**Comment by stof** [comment]
This is in the same kind of things that the [runtime check of platform requirements](https://getcomposer.org/doc/06-config.md#platform-check) IMO: you might run `composer install` with a different runtime.
However, checking that early rather than in platform_check.php allows to have a proper failure there instead of a fatal error because the code loaded for the composer runtime _before_ platform_check.php is executed is incompatible.

Note that when you use OPCache, this code has no impact at all as the condition `if (PHP_VERSION_ID < 50600) {` is resolved by OPCache and the whole block becomes dead code that is eliminated.

**Comment by rudiservo** [comment]
@stof sorry to revive this, tested in php8.3 with opcache, the impact is very minimal but not zero, I know people always complain not to do micro optimizations, but the global use of composer and autoload does have a larger impact that even a the smallest optimization has a great impact.

**Comment by stof** [comment]
@rudiservo please open a dedicated issue providing actual numbers then, instead of commenting on a closed issue that maintainers won't follow
