### ISSUE TITLE
composer 2.6.5 hangs for any command on macOS Sonoma 14.0

### ISSUE THREAD

**Issue by polatolu** [composer/composer#11686]
at least empty `composer` command could print out list of commands but nothing happens, just hangs and waits forever. `composer install`, `composer diagnose`, etc any command hangs.

I believe this issue may be related to latest version of macOS Sonoma or my PHP 8.2.11 version but all of my efforts didn't solve the problem. I uninstalled, installed, re-installed composer and php via `brew` but this also didn't help. 

`php` commands works fine, composer never responds.

My `composer.json`:

```json
not relevant as composer is not responding at all
```

Output of `composer diagnose`:

```
hangs and waits forever without any response, just empty.
```

When I run any command, event with `-vvv` parameter didn't print any output.

And I expected this to happen:
works as expected, at least prints out the error message about what is going wrong.

**Comment by fredden** [comment]
Here are some further questions to help try to work out what/where the problem is:
- Do you get the same behaviour with other versions of Composer? (Is this bug specific to version 2.6.5, or are other versions also affected?)
- How did you install Composer? (Download a phar file (from where?), or run the installation script from https://getcomposer.org/download/ or https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md, or another method?)
- Do other phar files work as expected? (Is the problem unique to Composer, or more widespread on your machine?)
- Is the Xdebug module enabled within your PHP configuration? (`php -i | grep -i xdebug`)

**Comment by polatolu** [comment]
Sure, thanks for those, here are the answers.

- I got the same behaviour for older versions, I tried 2.5.5 for example and it was having the same behaviour.
- I installed composer via homebrew and direct download via composer.phar file from getcomposer.org), originally I was using homebrew installation and after having the issues, I tried composer.phar on getcomposer.org.
- No, none of them work as expected. 
- Yes, XDebug v3.2.1 is enabled on my global PHP installation. Is this a problem causing composer fail to start?

**Comment by fredden** [comment]
Is xdebug configured to connect to your editor? In some of the projects I work with, xdebug is configured this way, and Composer appears to hang and do nothing, but there's a prompt in phpstorm saying it's paused execution because the composer.phar file is outside of the project paths, and the path mapping isn't set up for it yet. I wonder if that's what's happening for you too?

**Comment by polatolu** [comment]
Yes actually. This makes sense actually. After making a research around XDebug and Composer, I've seen some issues and it's suggested that XDebug must be disabled before using composer. I'll dig more about that in the evening and see how it goes.

**Comment by polatolu** [comment]
Thanks a lot @fredden 🎯

I set an environment variable by calling `export XDEBUG_MODE=off` and composer started working immediately. Now, when I'll need composer I'll change that variable to off and user `composer`, then I'll remove that variable by `unset XDEBUG_MODE` so enable the PHP debugger.
