### ISSUE TITLE
unnecessary error message when ignoring the upper bound of platform requirements

### ISSUE THREAD

**Issue by dg** [composer/composer#11722]
When option `--ignore-platform-req=php+` is used, it still prints the error message like `Cannot use texy/texy's latest version v3.2.0 as it requires php 8.1 - 8.3 which is not satisfied by your platform.`, although it does install the library.

`composer.json`:

```json
{
    "config": {
        "platform": {
            "php": "8.4"
        }
    }
}
```

Run: 

```shell
composer --ignore-platform-req=php+ require texy/texy
```

**Comment by fredden** [comment]
I've tested this locally with Composer version 2.6.5 and PHP 8.2.

|Command|Warning shown?|Version installed|
|-|-|-|
|`composer require texy/texy`|Yes|3.1.7|
|`composer --ignore-platform-req=php require texy/texy`|No|3.2.0|
|`composer --ignore-platform-req=php+ require texy/texy`|Yes|3.2.0|

According to the [documentation for `--ignore-platform-req`](https://getcomposer.org/doc/03-cli.md#install-i), using `php+` changes the restraint from `=8.4` to `>=8.4`. Version `3.2.0` of the `texy/texy` package requires PHP versions 8.1-8.3, which is not satisfiable with a constraint of `>=8.4`. Printing the warning here seems sensible to me.

I think the bug here is not about the warning message, but instead that when specifying `php+` we get an "incorrect" version of the package installed. I would expect version 3.1.7 to be installed (which has a PHP constraint of `>=7.1`), not version 3.2.0 (which has a PHP constraint of `8.1-8.3`).

**Comment by dg** [comment]
@fredden `--ignore-platform-req` does not affect the value in `config > platform`, but the value in `require > php` in the installed package. So it doesn't affect `8.4`, but the value of `8.1 - 8.3` here https://github.com/dg/texy/blob/master/composer.json#L14

**Comment by Seldaek** [comment]
Yeah I see what you mean, the first line of output there is not needed, and actually incorrect as it ends up using it anyway. I'll see if we can get rid of that.

```
$ composer --ignore-platform-req=php+ require texy/texy
Cannot use texy/texy's latest version v3.2.0 as it requires php 8.1 - 8.3 which is not satisfied by your platform.
./composer.json has been updated
Running composer update texy/texy
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking texy/texy (v3.2.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Downloading texy/texy (v3.2.0)
  - Installing texy/texy (v3.2.0): Extracting archive
Generating autoload files
No security vulnerability advisories found.
Using version ^3.2 for texy/texy
```
