### ISSUE TITLE
Change  Composer php version

### ISSUE THREAD

**Issue by TechNov** [composer/composer#11727]
Hello to the great Composer team and Community.

It w'll be very nice if we have somme tool like NVM that will help us to change PHP version in composer when needed. 
why this suggestion? 
I have php 8.0 ( for my App 1) and 8.1  ( For my App 2) on the same server. Composer use php 8.1 only... 
When i want to manage my App 1 with Composer, impossible because composer php version is PHP 8.1.

How to change php version in composer when needed?
Thank's

**Comment by fredden** [comment]
You should be able to specify the PHP executable to use for any PHP file on the command line. For example, instead of running `composer update` and letting your system find a file called `composer` in your `PATH` and then reading its shebang to determine what to execute, you could run `php8.0 /usr/local/bin/composer update` (or whatever the path to `composer` is, and however you find the "right" version of PHP on your system).

**Comment by matthiaz** [comment]
I usually  use [ddev](https://ddev.com/) to accomplish the same.

Since ddev spins up whatever php version you want for a specific project, you can run a different php and different composer, depending on each project.

And to run composer? simply prepend it with `ddev`
`ddev composer update`

**Comment by TechNov** [comment]
@matthiaz , thanks for your reply.
i w'll check ddev soon.
