### ISSUE TITLE
docs on packages doesn't explain 'reference' property

### ISSUE THREAD

**Issue by joachim-n** [composer/composer#11735]
The docs at https://getcomposer.org/doc/05-repositories.md#package-2 give an example which contains this:

```
                "source": {
                    "url": "http://smarty-php.googlecode.com/svn/",
                    "type": "svn",
                    "reference": "tags/Smarty_3_1_7/distribution/"
                },
```

but I can't see anywhere an explanation of what the `reference` property does. I can't see it mentioned on https://getcomposer.org/doc/04-schema.md either.

**Comment by stof** [comment]
The reference field is the reference to the version that must be installed. For git, this will be a commit id (it could also be a branch name or a tag name as supported by `git checkout` but passing a branch name is not recommended as that's a mutable reference and so won't lock things).
For svn this is the reference that gets appended to the URL when running `svn co`, due to the way SVN references versions.

**Comment by Seldaek** [comment]
Right, if someone can PR some additions feel free, otherwise I'll try and get to it some time.

**Comment by Seldaek** [comment]
Fixed by https://github.com/composer/composer/pull/11840
