### ISSUE TITLE
Unable to Create "web" Directory for Drupal Projects in Docker with Composer 2.7.0 #11853

### ISSUE THREAD

**Issue by daniela-zc** [composer/composer#11854]
Issue Report:
When attempting to install Drupal into a Docker container using Composer version 2.7.0, the expected "web" directory is missing, causing issues with project setup. This behavior is unexpected and disrupts the standard Drupal installation process within Docker environments.

Temporal solution:
Downgrade to Composer 2.6.6: As a temporary workaround, reverting to Composer version 2.6.6 has been observed to resolve the issue. This allows for the creation of the "web" directory as expected, enabling the Drupal project setup within Docker containers.

**Comment by xabbuh** [comment]
Could it be that the directory was created by a plugin and that this plugin is not executed with 2.7.0 as you run Composer as the root user (see #11839)?

**Comment by daniela-zc** [comment]
It's likely related, but I've already attempted using "export COMPOSER_ALLOW_SUPERUSER=1" without success. I'm working with Drupal, and this is what I have noticed:

    - Running "composer create-project drupal/recommended-project ." functions correctly.
    - However, "composer install" fails to produce the desired outcome.

The issue appears confined to Docker environments; outside of Docker, the process works flawlessly.

**Comment by Seldaek** [comment]
Have you tried prefixing the composer command with `COMPOSER_ALLOW_SUPERUSER=1` like `COMPOSER_ALLOW_SUPERUSER=1 composer install`?  That's a simple way to set env vars for just this one process. Because if you do export it may not work depending on the exact way you do it with docker. https://stackoverflow.com/questions/33379393/docker-env-vs-run-export

**Comment by Arr-n-D** [comment]
I spent the entire morning trying to figure out why this was happening, and finally came across this thread. I assume therefore that we would need to add the plugins we wish to execute ( without using COMPOSER_ALLOW_SUPERUSER=1 ) to the config.allow-plugins list?

**Comment by Arr-n-D** [comment]
I'm commenting the same thing on this as I've commented on #11839 

I spent the entire morning debugging why at first, the web folder was not created by Drupal project scaffolding from my Docker image.
I then used the COMPOSER_ALLOW_SUPERUSER=1 setting and that fixed that issue.
I then spent the entire afternoon and evening trying to figure out why commands such as ./vendor/bin/drush from my container would fail with this error

Fatal error: Uncaught Error: Class "Drupal" not found in /var/www/html/vendor/drush/drush/src/Boot/DrupalBoot8.php:93

After reverting COMPOSER_ALLOW_SUPERUSER=1 and applying the composer self-update 2.6.6 solution, things restarted working as intended. This indicates to me that there's more to the solution than just setting COMPOSER_ALLOW_SUPERUSER

**Comment by Seldaek** [comment]
@Arr-n-D I'm not sure what the issue is there, but I know for sure that rolling back to 2.6.6 is not a long term solution. It's just hiding the problem and gets you stuck on an unmaintained Composer release. I'm fairly sure that either running as non-root or setting the COMPOSER_ALLOW_SUPERUSER=1 env var should get 2.7.0 running more or less like 2.6.6 did. So if there is another issue still maybe it's a small regression somewhere else. That's worth investigating IMO but I have no drupal knowledge and no working docker setup so I'd be happy if someone affected can help figure some of this out.

**Comment by Arr-n-D** [comment]
I can confirm that COMPOSER_ALLOW_SUPERUSER=1 only mitigated the problem where the Web folder wasn't created, but additional issues rose further down the line. 

Running as non-root is in the works for our workflow, but it's not something I can do in the short-term without adding a bunch of things to my workload. 

I think it'd be worth investigating indeed, but I myself don't have much knowledge with Drupal in terms of project configuration, I am but the DevOps 😄 I could potentially try to generate a starter project with Drupal that fails due to this exact issue and send it over to you

**Comment by daniela-zc** [comment]
@Arr-n-D This was the correct solution for me : https://github.com/Probesys/bileto/commit/777ee4c7e744c12e0ce9e4bc0001809fb2d46a9d
Check it out , it ay work for you too

**Comment by Arr-n-D** [comment]
> @Arr-n-D This was the correct solution for me : https://github.com/Probesys/bileto/commit/777ee4c7e744c12e0ce9e4bc0001809fb2d46a9d
> Check it out , it may work for you too

This seems to require running things with a non-root user.

As mentioned, it is not currently viable for me to change that

**Comment by daniela-zc** [comment]
@Arr-n-D You are right, I was able to install "web" folder successfully but now I am having problems with drush not existing.

**Comment by Seldaek** [comment]
Could it be that drush or whatever plugin is running when drupal installs runs composer again in a subprocess that does not have the COMPOSER_ALLOW_SUPERUSER env var set, thus causing some failures?

Do you have instructions for me so I can try to repro this? Just composer commands to run and a git repo to clone if needed.
