### ISSUE TITLE
Execute post-install/post-update scripts of dependencies

### ISSUE THREAD

**Issue by ezzatron** [composer/composer#1193]
Is there a valid reason why scripts are not executed for dependencies? I'm sure this has been discussed before, but I couldn't find an issue here.

I have a use case. I have written a [component](https://github.com/eloquent/composer-npm-bridge) that allows NPM packages to be installed/updated at the same time as Composer's dependencies by using the [scripts](http://getcomposer.org/doc/articles/scripts.md) system.

The component works great for end projects, but obviously cannot be used for dependencies currently, which is where it would actually be useful.

Even if it's not something that will be implemented, it would be nice to know why it's not possible or desirable.

**Comment by mcd-php** [comment]
+1 for this.

I need to patch other packages from dependency packages - since I have too weak bargaining power to impose my patches upon upstream framework vendor.

`my/FooERP` depends on `yiisoft/yii2` and `my/ApacheCassandraForYii2`, I need to patch `yiisoft/yii2` from `my/ApacheCassandraForYii2` at the moment it's being installed as dependency for `my/FooERP`.

**Comment by Seldaek** [comment]
@mcd-php you shouldn't need bargaining power IMO if you are doing sensible things you should be able to get it in, unless upstream is crazy but then maybe it's time to work with another project. 

And anyway hot-patching code on install really sounds like a bad idea. You could tell users of your lib that they should require your fork of yii2 if they want to work with your package, but IMO that's a poor proposal as well.. imagine if everyone relied on their own forks the whole ecosystem falls apart.

**Comment by younishd** [comment]
![](http://i.memeful.com/media/post/VMVNNZM_700wa_0.gif)

**Comment by sminnee** [comment]
Just a quick note about the reference I just posted: one use-case for this feature is conditional requirements.

**Comment by spekary** [comment]
@Seldaek 

So, here is our use case. We would like to use composer to be able to install our framework, and individual packages that are plugins to the framework. As part of the installation process, we want to copy specific stub files that we just installed out of the vendor directory and into a user editable space so that the user can edit them and not worry about composer stomping on those edits on the next update. We are trying to use scripts to do the copy of those files.

With the current architecture, I need to tell these users to make certain 'scripts' entries to the composer.json file. HOWEVER, if there is already a 'scripts' entry there because of other dependencies, we need to tell them to MERGE the entries into what is already there. If they remove our framework, they will have to un-merge by hand. 

Now, our users are not all experts. I would like to avoid the requirement of needing to know how to hand-edit a .json file before being able to use our framework. Explaining how to do this hand-editing, and to be careful of every little comma and bracket can lead to quite a bit of frustration that will be a barrier to entry for our beginning developers. With the current architecture, I can't tell them to just execute 'composer require'. 

I guess I don't understand your point about losing user control. If I require a package in my top level composer.json file, I want that package to install. If that package fires off some scripts during installation, as a user of that package, I WANT that. I could easily inspect that package's composer.json file to see what it is trying to do if something goes wrong. The package creator can communicate in its documentation that it is firing off scripts at install and update time. Composer could notify the user during the composer execution process by outputing "Executing xyz script from package ABC" as part of the messages it sends out. Composer could have some options to not execute package scripts, or even have an interactive option to ask for confirmation on each script it finds. All of these would give the user sufficient control in the very unlikely event that the user would want that.

If you still don't agree, then perhaps at a minimum have the ```composer require``` and ```composer remove``` operations look for scripts entries in the required packages and merge and underage those entries to avoid a bunch of user error in the manipulation of the composer.json file.

>You could have a custom installer allowing hooks in packages it installs, or maybe even with a plugin if we add the given hook. I feel it'd be best than to add this in composer itself.

Don't both of these options require a bunch of work by the developer, and the user has to create special entries in the top-level composer.json file? And these packages are then allowed to fire custom scripts on their own. I don't see how doing more work is better, when the end result is basically the same thing, that a package that was installed is firing a script at install time. I don't see how calling it a 'composer-plugin' means that the user has more control than the scenario that any required package could fire off scripts.

**Comment by younishd** [comment]
@spekary Thank you!

I totally agree.
There should at least be some kind of option like `--run-dep-scripts` to explicitly allow a dependency to fire off some custom installation scripts.

If at the end of the day I still need to edit some JSON files by hand to get my dependencies to work then why bother with composer in the first place?

**Comment by stof** [comment]
The point is that use cases described here are kind of abusing what composer is for. It is not a boostrapping tool for framework-based projects.
thus, your script would have to run for the initial project creation, but not for any installation of the package (installing a project on another machine later because you have several devs, or updating the packages), because it would then overwrite these files again, loosing the benefit you describe here. A tool bootstrapping a project based on your framework makes much more sense IMO.

**Comment by spekary** [comment]
>because it would then overwrite these files again
The script simply checks to see if the file is there, and if it is already there, it will not over-write it. Its not that difficult.

So, perhaps this should become an open issue debate on what IS composer. The dev team sometimes calls it a dependency manager, and sometimes an installer. Whether the dev team knows it or not, Composer has become the defacto way to install PHP libraries and even whole frameworks for people who want to use those things to develop websites. The PHP developer community expects all PHP libraries and frameworks to be Composer installable. As such, there is a certain amount of responsibility the dev team has to make it easy to use for novice PHP developers. Admittedly, Composer has a little bit become a victim of its own success.

I am not asking for Composer to be a complete solution for all bootstrapping. However, I AM asking that package developers be given the ability to configure their own composer.json files in such a way that ```composer require package``` is all that the user needs to do to install a framework, or a framework plugin, or a library, or whatever.

Composer is 99% there. Script launching is the missing piece. The issue has come up over and over, I would think the message is pretty clear.

@Seldaek gave some principles for why dependencies should not launch scripts. Mainly, he said users would lose control of the installation process. I assume he means that since a script isn't explicitly called out in the top-level composer.json file, it is therefore hidden and therefore there is some loss of user control. I think there are lots of ways of mitigating this and I gave some. However, I think he is trying to protect users from something they don't want protection from.

I think the primary problem is a misunderstanding of your audience. There seems to be an assumption that all users of composer are accomplished programmers and .json editors. I would say most composer users are at the level of struggling to just get composer installed, and they follow a set of commands or instructions to use composer to get some PHP thing installed. They do NOT want to know the inner workings and they would like to avoid editing a .json file as much as possible. The ```composer require``` command is a great tool for them.

The principle I would recommend going by is "Give the people with the problem the ability to solve their own problem." The dev team tried to do that with plugins and custom installers, but unless I am mistaken (and I easily could be, I don't totally understand how a user configures a composer.json file to use a package's custom installer), there is no way for package developers that need some extra installation steps to tell users to just ```composer require``` in order to install.

**Comment by Seldaek** [comment]
@spekary I definitely get your point (although I think you could summarize a bit more in the future:) but even if I agreed it's not as easy as enabling all scripts of all dependencies at this point, backwards compatibility also has to be taken into account. If we were to simply enable them for dependencies as you say it might have unexpected effects as packages don't really expect this to happen.

Plugins are **a bit** more work for you yes as a framework author, but it also gives more guarantees (i.e. there is a plugin API that you require and will guarantee in the future that  the right version of the plugin is installed for the right version of composer the user has..). Plugins are also installed before other packages to ensure they are ready to do their task when other stuff gets installed.

As I understand it, you need one thing to check whenever your framework or one of its plugins is installed and copy some config files in the right location. If you make your framework require the plugin package users wouldn't have to do anything, they just require the framework and the plugin will be installed first and it can then copy things after the framework is installed.

**Comment by nejtr0n** [comment]
Hi. Here is my example. I have basic .gitignore file for one popular CMS, which i have to create in each new project. (It differs in some cases, but base is common). I want to make composer package, which will take current version to vendor dir, and copy it to document root on installation. (It is under own git control ). Dependency script would be natural thing for this job. But i could not use it. I think some flag like "--run-dep-scripts" will be greate advantage. It wont change basic behaviour of composer, but give it more flexebility!

**Comment by vercotux** [comment]
+1 for this

Another use case is [EasyEngine](https://rtcamp.com/easyengine/) which needs to be added as a dependency, but installed with a command. It also provides update and uninstall commands, perfect for this setup, if only composer supported dependency scripts.

**Comment by SplicePHP** [comment]
Couldn't see any solutions on this thread.
Here is a workaround I now use to invoke post install events manually on selected packages.
```
composer run-script post-install-cmd -d ./vendor/[name]/[package]
```
You could also write a simple bash loop to trigger them all with this method if needed.

**Comment by saitho** [comment]
Also +1. About security concerns and backwards compatibility: wouldn't it be enough if the feature has to be explicitly enabled in the root composer.json file?

**Comment by verbruggenalex** [comment]
I'm ashamed to be looking for the same thing. Please forget I was here ;)

**Comment by derhecht** [comment]
Also have this need :(

**Comment by verbruggenalex** [comment]
Best option is to have people use "composer create-project" Then you get git clone and composer install which can do the installation process for them.  That was the best alternative in my case.

**Comment by mindplay-dk** [comment]
What about a package such as [this one](https://github.com/kodus/jpeg) that needs to set permissions of bundled binaries after installation?

I tried [this](https://github.com/kodus/jpeg/tree/fix/permission) and it doesn't work.

The `create-project` work-around doesn't make sense for this.

I could set the `type` as `composer-plugin` and make it execute the install-script that way, but that seems really hacky.

I don't understand the security concerns around this? I mean, I can just set my package type as `composer-plugin` and execute arbitrary code anyway, how is it any more of a concern to provide a simple means of executing a script post-install of a package?

**Comment by mindplay-dk** [comment]
Another hacky work-around would be to use [composer-locator](https://github.com/mindplay-dk/composer-locator) and the `bin` option to make Composer automatically set the permissions at installation time - to do that, I would need to rename the binaries and put them in a single folder, which doesn't exactly make sense either.

Bottom line is there are plenty of hacky ways to do this, so why not provide an official way to do it?

If security is the only reason, we have a slew of features already that are dangeous anyway... don't we?

**Comment by Seldaek** [comment]
I just don't see the problem at all for this package.. Git supports setting permissions in the file metadata, which will propagate fine on unix systems and is kinda ignored on windows but there it's irrelevant anyway. Why not just set the binaries to be executable in git and be done with it?

**Comment by mindplay-dk** [comment]
> Why not just set the binaries to be executable in git and be done with it?

I had no idea that was possible. I'll try.

**Comment by Seldaek** [comment]
`git update-index --chmod=+x filename` if you're on windows, on other OSs you can just do a chmod then git add.

**Comment by Seldaek** [comment]
I don't mind if someone learned something ;)

**Comment by johnrobertporter** [comment]
As this has been a requested feature for 5 years now, with people still requesting it (myself now included) can this not be implemented as a `composer.json` config option at least?

My use case is migrating a database. We have packages that are grouped together in a meta composer repo. We then install this single repository onto the API infrastructure. I was hoping to have composer auto-run the package post install scripts, which would run the relevant database migrations for each required package.

If I can't do this, has anyone any suggestions how to do it? I really haven't the time to learn the composer plugin architecture to achieve something I thought possible already (and therefore haven't accounted sprint time for).

A simple `composer.json` feature switch (defaulting to `false`) like `"run-dep-install-scripts": true` would be a godsend. An additional security measure would be to add package vendors to trust?

```
"dep-install-scripts": {
    "run": true,
    "trust": ["phpunit", "illuminate"]
}
```

Thoughts?

**Comment by verbruggenalex** [comment]
Contact me @johnrobertporter. As Composer has good reasons not to do this. It's probably not that hard to provide a plugin for this with the config you describe. Merge plugin already does similar stuff. Althouh it might require a re-run on initial install of the plugin. Unless you put it globally.

**Comment by tonglil** [comment]
Don't execute dependency code automatically, as then you'll run into this:
https://github.com/eslint/eslint-scope/issues/39
https://eslint.org/blog/2018/07/postmortem-for-malicious-package-publishes

**Comment by kurtfoster** [comment]
The suggestion from @johnrobertporter is exactly what I need. We have packages that we're writing ourselves that are used across multiple projects, it would be great to be able to whitelist them in this way, including their scripts.

**Comment by uphlewis** [comment]
> Don't execute dependency code automatically, as then you'll run into this:
> [eslint/eslint-scope#39](https://github.com/eslint/eslint-scope/issues/39)
> https://eslint.org/blog/2018/07/postmortem-for-malicious-package-publishes

Blocking dependency update event scripts wouldn't help prevent that. A compromised package could just as easily run malicious code at runtime.

**Comment by stof** [comment]
@uphlewis but you can have a chance to review the install code before the runtime. For code running at installation time, it runs before you could look at it.

**Comment by nolanpro** [comment]
@kurtfoster @stof Don't know about you guys but I never look at source code after I composer require but before running the application if the code is from a reputable source. If anything, I would review it in github before running composer require.

I feel like running dependency scripts would be extremely helpful without introducing much more risk then what's already there when installing a 3rd party dependency.

**Comment by b-hayes** [comment]
Why not a bin export? "bin" : ["bin/mypackage-setup"]
Your users do not need to edit any json files to add scripts just run a simple command after they require.

if you have a freamworky system with a lot of other component packages then you can just have one bin from your framework detect and setup other components.

Would be so easy to also make your setup command edit the users composer.json for them and add a scripts entry so it happens for every install/update command they do in future.

For npm dependencies can use npm-bridge but you can just as easily commit your node_modules folder instead. Since bridge will duplicate all the npm dependencies in each vendore/package/node_modules folder anyway then why not make it easy on yourself and also prevent users form breaking your package with npm updates.

**Comment by NicoHaase** [comment]
@b-hayes bin export won't help to **automatically** run such a script after the installation, regardless of any framework or anything else, and that's what this feature request is about: define a way to run a script defined by a dependency without any further interaction

**Comment by b-hayes** [comment]
@NicoHaase yeah I know I. But there is no way to automatically run scripts and its probably not coming anytime soon, or ever. So just offering a simple work around. It's only one command line after they run composer require. Not very hard  for a user to do.

**Comment by mathias-meyer** [comment]
I was looking for the same feature and made a composer library which is implementing the proposed solution from the 14 Feb 2018.

In order to avoid security breaches, only PackageEvents raised by a package will be forwarded to scripts matching the event in its package.

Pushed code here : https://github.com/mathias-meyer/composer-package-updater

I'm about to have it handled by packagist as well.

Mathias

**Comment by mathias-meyer** [comment]
> I'm about to have it handled by packagist as well.

Now available in packagist under `mathias-meyer/composer-package-updater`

**Comment by totten** [comment]
Well, I did something very similar to allow dependencies to perform post-install compilation tasks. The permission model was initially pretty flat (eg on/off switch - with an interactive prompt to get permission on first run), but it looked like the "whitelist" approach had a lot of buy-in here, so I switched to a whitelist. Currently, it's tagged as v0.3.

In a library package (upstream POV), the `composer.json` declares an `extra.compile` blurb. It may include shell commands or PHP callbacks. Here's an example library from the test-suite which compiles SCSS:

```json
{
  "name": "test/gnocchi",
  "require": {
    "civicrm/composer-compile-plugin": "@dev",
    "scssphp/scssphp": "1.2.0",
    "padaliyajay/php-autoprefixer": "~1.2"
  },
  "autoload": {"psr-4": {"ScssExample\\": "src"}},
  "extra": {
    "compile": [{"php-method": "\\ScssExample\\ScssExample::make"}]
  }
}
```

During installation on the root-package (downstream POV), `composer` will finish its normal work (downloading, dump-autoload, etc) and then run the compilation tasks. It prompts for permission first:

![Screenshot](https://raw.githubusercontent.com/civicrm/composer-compile-plugin/master/doc/img/composer-require.png)

More details at https://github.com/civicrm/composer-compile-plugin
