### ISSUE TITLE
PSR-0 namespaced classname resolving bug

### ISSUE THREAD

**Issue by ideus-biz** [composer/composer#12002]
Hi!
As to composer docs and the code&comments inside \Composer\Autoload\ClassLoader we can see that composer does support PSR-0 class naming with namespaces, but in fact such classes are not resolved.

Let's assume a vendor's library has a class:
`\MyHouse\Room\Shelf\Fruit_Apple`
located in vendor's folder `./src/Shelf/Fruit/Apple.php`

Vendor's `composer.json` contains:

```json
  "autoload": {
    "psr-0": {
      "MyHouse\\Room\\": "src/"
    },
  },
```
In such way composer searches the file in
`./vendor/...../src/MyHouse/Room/Shelf/Fruit/Apple.php`
but has to look up in
`./vendor/...../src/Shelf/Fruit/Apple.php`
due to composer.json psr-0 autoload directive.

The next code of \Composer\Autoload\ClassLoader::findFileWithExtension method is not sufficient and in fact does not assume autoload configuration:

```
if (isset($this->prefixesPsr0[$first])) {
            foreach ($this->prefixesPsr0[$first] as $prefix => $dirs) {
                if (0 === strpos($class, $prefix)) {
                    foreach ($dirs as $dir) {
                        if (file_exists($file = $dir . DIRECTORY_SEPARATOR . $logicalPathPsr0)) {
                            return $file;
                        }
                    }
                }
            }
        }
```

And it must be replaced with a similar code as above this one which seaches psr-4 class file taking in an account 'namespace' => 'directory' mapping, for example:

```
		if (isset($this->prefixesPsr0[$first])) {
			$subPath = $class;
			while (false !== $lastPos = strrpos($subPath, '\\')) {
				$subPath = substr($subPath, 0, $lastPos);
				$search = $subPath . '\\';
				if (isset($this->prefixesPsr0[$first][$search])) {
					$pathEnd = DIRECTORY_SEPARATOR . substr($logicalPathPsr0, $lastPos + 1);
					foreach ($this->prefixesPsr0[$first][$search] as $dir) {
						if (file_exists($file = $dir . $pathEnd)) {
							return $file;
						}
					}
				}
			}
		}
```
Which resolves file location correctly.

Please look up the issue and correct the code to respect PSR-0 namespaced classes, because composer states it support such class naming.
As well as our software needs such support.

Thank you.

**Comment by Seldaek** [comment]
> In such way composer searches the file in
> `./vendor/...../src/MyHouse/Room/Shelf/Fruit/Apple.php`
> but has to look up in
> `./vendor/...../src/Shelf/Fruit/Apple.php`
> due to composer.json psr-0 autoload directive.

I think what you describe is is a psr-4 directive.. kind of. 

`"MyHouse\\Room\\": "src/"` with a config like this, psr-0 will look inside src/MyHouse/Room/..., psr-4 will look inside src/... and both will first remove `MyHouse\Room\` from the class name.

The problem is only psr-0 does underscore replacement in the class names. psr-4 does not.

So you have psr-0 classes that you want to load with a psr-4 path structure.. 

Either you move the file to `./src/Shelf/Fruit_Apple.php` and change the config to psr-4, or you keep psr-0 but then it needs to be located in `./src/MyHouse/Room/Shelf/Fruit/Apple.php`

I don't think there is a bug here, at least as far as your made up example goes.

**Comment by ideus-biz** [comment]
PSR-0 uses underscore symbol as a separator for path name to a class, as it well-known, but it does not explecitly deny using namespaces, and there is no reason to not using them in a classes architecture.
If PSR-0 class has namespace as it needs by developing process, then composer, as a respectable service, has to support such kind of class naming.
And the code analisys shows that there is a lack of support for classes in namespaced psr-0 format.

Yes, maybe this is a rare case, not a trend, but it is a good practive to support the way wich does not forbidden!
Such feature, as a minor change in the code, absolutely is not too hard to be implemented, but opens more ways for composer society.

**Comment by Seldaek** [comment]
I'd need an example that makes sense to me because as i explained your example above seems to me like it is not psr0 compliant so as such I don't think we should support it.

**Comment by ideus-biz** [comment]
OK, let me describe the issue in other words.

PSR-0 allows namespaced class names, which may contain a vendor's namespace:

```\<VendorNamespace>\(<SubNamespace>\)<Class_Name>```

Just like for PSR-4 ```\<VendorNamespace>\(<SubNamespace>\)<ClassName>```
Composer offers to `move` vendor's namespace **out of the path** to the classes
**by declaring a directive** in composer.json:
```
    "autoload": {
        "psr-4": {
            "VendorNamespace\\": "src/"
        }
    },
```
And so the path to class just like that: .../vendors/my-vendor/src/**SubNamespace/ClassName** that is **without directory**  \VendorNamespace\

And that's great!

The same feature is great to be for psr-0 as well, but in fact it does not work as awaiting.

In the example above fo the class ```\MyHouse\Room\Shelf\Fruit_Apple``` we have vendor's namespace:
```\MyHouse\Room\```
and there is **no way to move it out of the path**, even if appropriate autoload directive is declared, which is official composer's directive, isn't it? :
```
    "autoload": {
        "psr-0": {
            "MyHouse\\Room\\": "src/"
        }
    },
```

If composer allows to move vendor's namespace out of the path by autoload directive, why it does not work and why should not work, as you insist:

> psr-0 will look inside src/MyHouse/Room/...

Why, what the reason :) ?
This is an issue in the a small block of not trending code, and it should be fixed / improved to let to organise PSR-0 structure in a package of classes which have their own vendor's namespace but without a need to make a sub-directories in the package for vendor's namepace.

Thank you!

**Comment by Seldaek** [comment]
> Why, what the reason :) ?

Because that is how the PSR-0 spec works https://www.php-fig.org/psr/psr-0/ - in all examples you will see that the ENTIRE fully qualified class name is reflected in the path.

PSR-4 was done to fix this amongst other things, as you can see here https://www.php-fig.org/psr/psr-4/meta/ 

Sorry but I am not going to make the autoloader non-compliant because you feel it'd be more convenient.

**Comment by ideus-biz** [comment]
https://www.php-fig.org/psr/psr-0/
This specification is not about how Composer processes psr-0.
And our complaint is not about a convenience.

But about Composer's json ```autoload.psr-0``` **directive** which **has no meaning for PSR-0** if package class contains vendor's namespace.
And evidently there shouldn't be any difference what PSR is used, because if composer's autoloading configuration **offers the directive** to `hide` vendor's namespace, it must work the same.

Anyway, as we understand you right, it is more simple to describe the issue as ```an artifact``` and write a whole explanation documentation than just fix the 'artifact' with a couple lines of code ) .
So we keep using external autoloading logic to avoid Composer's obvious problem.

Thanks!

**Comment by xabbuh** [comment]
> But about Composer's json autoload.psr-0 directive which has no meaning for PSR-0 if package class contains vendor's namespace.
And evidently there shouldn't be any difference what PSR is used [...]

Being able to "hide" directories is precisely the reason for the introduction of PSR-4: https://www.php-fig.org/psr/psr-4/meta/ (specifically the section at https://www.php-fig.org/psr/psr-4/meta/#along-comes-composer).

You can also take a look at the example at https://www.php-fig.org/psr/psr-0/#examples

**Comment by Seldaek** [comment]
> Anyway, as we understand you right, it is more simple to describe the issue as an artifact and write a whole explanation documentation than just fix the 'artifact' with a couple lines of code ) .
So we keep using external autoloading logic to avoid Composer's obvious problem.

That's your perspective. Mine is that we have standard compliant code - which btw is probably one of the most executed few lines of php code out there - and someone too lazy to rename some classes to follow either of two 10year old standards wants me to make changes to that code. That change carries lots of risk and I don't want to spend time thinking about whether it even would work fine because I don't see the point of it. There is no use case as psr4 solves this already.

So sure, use your own autoloader if that works better for you than renaming classes (or you could use classmap autoloading too).
