### ISSUE TITLE
`PluginInterface::PLUGIN_API_VERSION` is incorrect

### ISSUE THREAD

**Issue by Seb33300** [composer/composer#12036]
From the `UPDRADE.md` file, I can read:
> you can detect which version of Composer you run via `PluginInterface::PLUGIN_API_VERSION`

https://github.com/composer/composer/blob/e61d4ad9866570bff39ce0f95a7fc2c950c63cc5/UPGRADE-2.0.md?plain=1#L18

But this constant seems to never been updated when a new composer version is released.
The version returned by composer `2.7.7` is `2.6.0`

https://github.com/composer/composer/blob/e61d4ad9866570bff39ce0f95a7fc2c950c63cc5/src/Composer/Plugin/PluginInterface.php#L35

**Comment by stof** [comment]
The *plugin api* version is not updated each time composer is released. It is updated only when composer does a change in its plugin API.

**Comment by Seldaek** [comment]
Yes, see https://getcomposer.org/doc/articles/composer-platform-dependencies.md#composer-package-composer - if you need an exact composer version you can also use `Composer\Composer::getVersion()` when you are running a plugin as that runs in the Composer process, but IMO it is better to add a require so that you enforce it at the dependency management level.

**Comment by Seb33300** [comment]
Thanks
