### ISSUE TITLE
Composer audit not showing CVEs found by symfony check:security and listed on packagist API with `packagist: false` on repositories list

### ISSUE THREAD

**Issue by mleczakm** [composer/composer#12210]
When I run this command:

```
composer require symfony/security-http:5.4.45
```
having composer.json with
```
  "repositories": [
    {
      ...
    },
    {
      "packagist": false
    }
  ],
  ```

I get the following output: 
```
...
No security vulnerability advisories found.
```
Same with `composer audit` when that package is installed, and I expected message with current CVE for that package, which is listed by command `symfony check:security`:
```
symfony security:check
Symfony Security Check Report
=============================

3 packages have known vulnerabilities.

symfony/security-http (v5.4.45)
-------------------------------

* [CVE-2024-51996][]: Authentication Bypass via persisted RememberMe cookie
...
```
CVE is listed on https://packagist.org/api/security-advisories/?packages%5B%5D=symfony/security-http

**Comment by stof** [comment]
As discussed on the Symfony Slack, this is totally expected behavior. When you disable usage of packagist.org to use only your own repository, Composer will not use packagist.org anymore, and that includes the loading of metadata about security advisories. Advisories have to be provided by one of your registered repositories (or multiple of them)
