### ISSUE TITLE
Load "extra" from config.json and merge with composer.json

### ISSUE THREAD

**Issue by naderman** [composer/composer#1358]
Since we allow the "extra" section of composer.json to contain pretty much any data for customization, it'd be useful to allow setting it globally as well. Should work in the same way "config" is currently handled I think.

**Comment by gggeek** [comment]
+1 for env vars being made available to script handlers.

My current gripe is that I have some script handlers which are not in my control (3rd party), and those only accept values set in the 'extra' section or composer.json, or ask the user for input.
It goes without saying that this makes it hard for me to automate calls to 'composer install' for those apps.

While I agree that I could ask to the maintainers of those app to change their script handler classes to look for env vars as well, I think it would be better if Composer itself made the env vars available via an API, so that developers (of script handler scripts) would be encouraged to use them.

Thanks
Gaetano

**Comment by gggeek** [comment]
ps: sorry for posting OT on closed issues. Shall I open a new issue ?

**Comment by Seldaek** [comment]
@gggeek pleas open a new issue with more details because I  don't quite get what you mean. As for this issue I think it's old enough that we can close it at this point. Doesn't seem all too important.
