### ISSUE TITLE
"vendor" folder structure

### ISSUE THREAD

**Issue by e-oz** [composer/composer#1428]
Hello.
In [PSR-0](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-0.md) standard, classes should be placed in a "<Vendor Name>(<Namespace>)" folder.  
Example from docs:
`\Symfony\Core\Request => /path/to/project/lib/vendor/Symfony/Core/Request.php` 
So, by this rule, [Twig_Compiler.php](https://github.com/fabpot/Twig/blob/master/lib/Twig/Compiler.php) should be in `vendor/Twig/Compiler.php`, so any PSR-0 autoloader will be able to find this class.
But after `composer install` I see structure `vendor/twig/twig/lib/Twig/Compiler.php` and I can use only mapping of namespaces in autoloaders, so PSR-0 actually is not used for autoloading.

Excuse me, if it is described already in documentation. Please, let me know, if it is configurable somehow in composer.json.

**Comment by jslegers** [comment]
What I loved about `PSR-0`, is that you could do this :

### 1. Folder structure :

````
Project 
  |__ Index.php
  |__ App
       |__ Controllers
       |__ Models
       |__ Views
  |__ Vendor
       |__ PowerTools
       |__ Symfony
       |__ Zend
````

### 2. Use a SINGLE autoloader

You could use [**a single autoloader**](https://github.com/PHPPowertools/Loader) that supports both files in the `App` folder and files in the `Vendor` folder with **ZERO CONFIGURATION**. As long as a package is `PSR-0` compatible, you just put all the files in either the `App` or `Vendor` folder and everything magically works out-of-the-box, just like that.

Well, maybe "zero config" is a bit exagerated. You may want to configure the directories you want to autoload from... once... regardless of the number of projects used.

This is why I never used `Composer` for any of my projects thusfar.

--------------------------

### 3. Why I'm considering Composer support to my projects

I don't like using `Composer`, because (AFAIK I know) using the same namespace for multiple packages that are part of the same framework comes with [**a significant performance drawback**](http://stackoverflow.com/questions/25121155/different-composer-packages-with-same-nam space).. Right? If I'm wrong here, please [**tell me what's the right way to do this with Composer**] (https://github.com/composer/composer/issues/4605)!

Another reason I've always avoided using `Composer` so far, is because I find it a lot more complicated than just dragging-and-dropping some files in a folder and I like to keep my number of dependencies as low as possible.

Unfortunately, somehow, few people seem to be aware that zero-config auto-loading is even possible, using `Composer` because it's the simplest alternative they are familiar with. So if I want people to actually try my projects, I supposed I need to add `Composer` support.

Additionally, deprecating `PSR-0` and adding all sorts of custom behavior to the `PSR-4` standard makes it increasingly difficult for me to just us a single zero config autoloader for any project. It adds additional complexity to my projects, making it but a matter of time before I actually need `Composer`. 

I guess this is supposed to be progress? It isn't in my opinion, but hey... I guess I have to move on if I want to stay relevant as a PHP developer.

**Comment by e-oz** [comment]
@jslegers 

> few people seem to be aware that zero-config auto-loading is even possible, using Composer because it's the simplest alternative they are familiar with

> if I want to stay relevant as a PHP developer.

It's more looks like regression to the level of the crowd :)
Currently composer not only doesn't promote updating to PSR-0 for old projects, but even allows new project to spread chaos in their structures. Example: new AWS PHP SDK has "functions.php" file. We should require it by the special line. They can do it, they can return to dark middle age of "functions.php" because Composer hides this ugliness and nobody cares.

**Comment by jslegers** [comment]
@e-oz

> Currently composer not only doesn't promote updating to PSR-0 for old projects, but even allows new project to spread chaos in their structures. Example: new AWS PHP SDK has "functions.php" file. We should require it by the special line. They can do it, they can return to dark middle age of "functions.php" because Composer hides this ugliness and nobody cares.

The blame is mostly on @philsturgeon... as well as other members of @php-fig.
It's they who're setting the standards for the the rest of us, telling us what we should and shouldn't do!

**Comment by e-oz** [comment]
@jslegers members of @php-fig created very good standard proposal (psr-0), the only issue is Composer don't follow it.

**Comment by jslegers** [comment]
@e-oz :

I love PSR-0!

However, then they came up with PSR-4, which gets rid of the rigid `convention over configuration` principle that made PSR-0 so great. Not only that, but PSR-4 also breaks compatibility with PSR-0. More specificly, you can no longer use an underscore in your class name to represent going a level down in your folder structure for classes within the same namespace.

Not only does PSR-4 break compatibility with PSR-0, but they even decided to deprecate PSR-0... which is just plain ridiculous!

**Comment by e-oz** [comment]
@jslegers agreed.

**Comment by Seldaek** [comment]
There is so much misinformation in the last few comments I don't even know where to start, but yes Composer follows PSR-0, and PSR-4, both optionally, and it lets you do a simple fallback config like mapping a psr-0 namespace of `""` to `["Project/App", "Project/Vendor"]` which would make it look for every class in both of these directories, so universal autoloading of sorts, but I don't think this makes much sense to be honest. As for poor @philsturgeon he is really not to blame for all the evils of this world, especially imaginary ones. And the FIG isn't telling you what to do, the FIG is setting standards for the FIG members that want to collaborate on things and do things in a similar way amongst project, if you don't want to listen to them you are welcome to ignore them.

Anyway it's being dicsussed in further details at #4605 and I'd advise to move the discussion there because this is an old issue that's completely dead at this point.

**Comment by philsturgeon** [comment]
What on earth are you people talking about? 

Firstly, you're bumping a years old thread. Don't do that. 

Secondly, you're conflating the actions of composer, PSR-0, PSR-4 and the FIG in a way unlike nobody else. Please read this. 

https://philsturgeon.uk/php/2013/05/07/composer-and-psr0-friends-not-relatives/

If you want this folder structure, then you can do that:

```
Project 
  |__ Index.php
  |__ App
       |__ Controllers
       |__ Models
       |__ Views
```

You just use the `autoload` option in your application `composer.json` and you're done. What happens in the `vendor/` folder (you can rename that to `Vendor/` if you really have to) is completely irrelevant. 

You can also do exactly this with PSR-4. 

> Currently composer not only doesn't promote updating to PSR-0 for old projects, but even allows new project to spread chaos in their structures. Example: new AWS PHP SDK has "functions.php" file. We should require it by the special line. They can do it, they can return to dark middle age of "functions.php" because Composer hides this ugliness and nobody cares.

@e-oz The AWS PHP SDK does have a functions.php, for namespaced functions. That's great. Not everything in PHP needs to be a class, and having functions is completely ok. You **do not** have to include this yourself, you only need to have the composer autoloader included.

Please don't spread FUD.

> @jslegers members of @php-fig created very good standard proposal (psr-0), the only issue is Composer don't follow it.

Composer 100% absolutely follows PSR-0. Please consult the earlier blog post.

> However, then they came up with PSR-4, which gets rid of the rigid convention over configuration principle that made PSR-0 so great. 

Not true. Set the namespace prefix to the root of the source folder and you're identical to PSR-0. 

> Not only that, but PSR-4 also breaks compatibility with PSR-0. More specificly, you can no longer use an underscore in your class name to represent going a level down in your folder structure for classes within the same namespace.

This was an explicit goal of PSR-4. Underscores (a.k.a "Poor Mans Namespaces") were used in a < PHP 5.2 world, and are useless in a PHP 5.3 world. They also carry [a bug](https://github.com/philsturgeon/psr0-naming-oddity) which PSR-4 got rid of.

> Not only does PSR-4 break compatibility with PSR-0, but they even decided to deprecate PSR-0... which is just plain ridiculous!

[Deprecation is entirely logical](https://philsturgeon.uk/php/2014/07/19/send-psr0-to-the-standards-farm-in-the-sky/), has zero downsides and helps point developers in the right direction, while leaving Composer and any other project able to use PSR-0 for as long as they like.

You folks seem confused about how these things fit together and it's not the first time I've seen it, which is why I've written about these things so much.

That's also why you're **blaming** me for the actions of the FIG, despite me joining _after_ PSR-2. Lol.

Nobody is forcing you to use any PSRs, feel free to use your own autoloaders. Composer lets you do that, which is why it's pretty cool.

Let me know if you have any questions. 

Keep is classy.

**Comment by philsturgeon** [comment]
@Seldaek haha, thanks chap! Didn't see your reply come in while I was writing mine.

**Comment by jslegers** [comment]
@Seldaek :

> There is so much misinformation in the last few comments

Misinformation?

> it lets you do a simple fallback config like mapping a psr-0 namespace of `""` to `["Project/App", "Project/Vendor"]` which would make it look for every class in both of these directories, so universal autoloading of sorts, but I don't think this makes much sense to be honest.

Why don't you think it makes sense? I first stumbled on this strategy when playing around with [**Kohana**](https://kohanaframework.org/) years ago, and I still haven't seen any PHP code as clean and elegant as that project.

I've been using this autoloading strategy for years (using it to load Symfony, Zend and many other libraries without any per-package configuration). I never had any problems with that strategy whatsoever until PSR-4 came around, which makes zero-config universal autoloading impossible.

> As for poor @philsturgeon he is really not to blame for all the evils of this world, especially imaginary ones.

Imaginary ones?

> And the FIG isn't telling you what to do, the FIG is setting standards for the FIG members that want to collaborate on things and do things in a similar way amongst project, if you don't want to listen to them you are welcome to ignore them.

You can't just ignore FIG standards if FIG standards are the standards used by the PHP community at large... or if your project uses dependencies created by FIG members.

Unless your project has no third party dependencies whatsoever (which isn't a realistic requirement for any real world customer project), whichever standards are set by FIG are relevant to you if you're a PHP developer. Heck, even Drupal is using Symfony2 these days, and they're like the masters of [**NIH**](https://en.wikipedia.org/wiki/Not_invented_here)... sortof.

Much the same way, I can't ignore Composer support for my open source projects even if I wanted to. Because most professional PHP developers are using Composer these days, excluding Composer support is simply not an option if you want people to even consider playing around with your open source projects.

> Anyway it's being dicsussed in further details at https://github.com/composer/composer/issues/4605 and I'd advise to move the discussion there because this is an old issue that's completely dead at this point.

Isn't **https://github.com/composer/composer/issues/4605** pretty much a completely seperate discussion?

--------------

@philsturgeon :

> Firstly, you're bumping a years old thread. Don't do that.

I don't know why that's supposed to be wrong if you think you have something to add that's relevant to the topic... but OK.

> Secondly, you're conflating the actions of composer, PSR-0, PSR-4 and the FIG in a way unlike nobody else. 

I've been using PSR-0 for years without ever having to use Composer. So there's no need telling me that they're not the same.

> If you want this folder structure, then you can do that:
> 
> ````
> Project 
>   |__ Index.php
>   |__ App
>        |__ Controllers
>        |__ Models
>        |__ Views
> ````

Only if I name my default controler something like `\App\Controller\Default`, whereas I prefer `\App\Controller_Default`.

PSR-4 no longer supports that and forces every folder to have its own namespace. I find that utterly ridiculous!

> The AWS PHP SDK does have a functions.php, for namespaced functions. That's great. Not everything in PHP needs to be a class, and having functions is completely ok.

I have to agree with @e-oz here. Allowing this kind of bad practices is a step backward and NOT a step forward!

> Not true. Set the namespace prefix to the root of the source folder and you're identical to PSR-0.

Again, PSR-4 doesn't allow me to both (1) use a file structure like [**`vendor/PowerTools/DOM/Document.php`**](https://github.com/PHPPowertools/DOM-Query/blob/master/vendor/PowerTools/DOM/Document.php) and [**`vendor/PowerTools/Event/Listener.php`**](https://github.com/PHPPowertools/Event/blob/master/vendor/PowerTools/Event/Listener.php) and (2) name my classes `\PowerTools\DOM_Document` and `\PowerTools\Event_Listener`.

Again, PSR-4 doesn't allow me to use a single namespace `\PowerTools` for ANY class in my framework, which is how I prefer to use namespaces.

> This was an explicit goal of PSR-4. Underscores (a.k.a "Poor Mans Namespaces") were used in a < PHP 5.2 world, and are useless in a PHP 5.3 world.

I don't see why "Poor Mans Namespaces" are useless in a PHP 5.3+ world. I don't see why every folder is supposed to refer to a seperate namespace. IMO, it makes no sense whatsoever for different classes of the same library (or even the same framework) to use different namespaces. There is little to no advantage to that if your projects are well-managed.

I don't want statements like `use PowerTools\Event\Listener As EventListener` to pollute my projects... nor do I don't want to use the fully qualified name `\PowerTools\Event\Listener` either. IMO, it makes far more sense to use references like `Event_Listener` without namespaces and without `use` statements whenever I'm refering to a class within the same framework.

> They also carry a bug which PSR-4 got rid of.

If you use the naming conventions I'm using, it's a bug you never encounter at all. It's hardly a reason to deprecate a popular convention that still has its use cases. In fact, it's precisely this convention that allows [**Kohana framework**](https://github.com/kohana/kohana) (I really love their HMVC architecture) to have such elegant, readable code!

> Deprecation is entirely logical, has zero downsides and helps point developers in the right direction

Zero downsides?

Breaking compatibility between PSR-0 and PSR-4 is a major downside imo, which significantly complicates writing your own universal autoloader and inevitably has a negative impact on performance.

> That's also why you're **blaming me** for the actions of the FIG, despite me joining *after* PSR-2. Lol.

I have no problem with PSR-1, PSR-2 or PSR-3, because neither break compatibility with PSR-0. You could use a single universal autoloader for any package written in any of these standards, because PSR-1 to PSR-3 are all essentially just refinements of the same PSR-0 standard.

PSR-4 is the first PSR-X standard to break compatibility with PSR-0 (in several ways), which has multiple downsides (that have all been mentioned earlier).

> Nobody is forcing you to use any PSRs, feel free to use your own autoloaders. Composer lets you do that, which is why it's pretty cool.

What I want, is ONE universal autoloader that allows me to just drop ANY package into my `vendor` folder and have it work out of the box with zero per-package configuration. PSR-0 to PSR-3 allowed that, whereas PSR-4 doesn't... for several reasons!

How anyone can think PSR-4 is a step forward (compared with PSR-3) is beyond me... but then again, considering [**how full of design flaws PHP is as a language**](http://eev.ee/blog/2012/04/09/php-a-fractal-of-bad-design/), I guess I shouldn't be surprised. I gues I shouldn't expect better from a community where Zend framework (** yuck **) and Drupal (**shiver down my spine**) have been the industry standard for God-knows-how-long and the beautiful Kohana is barely known at all.

**Comment by jslegers** [comment]
@philsturgeon :

> Firstly, you're bumping a years old thread. Don't do that.

I don't know why that's supposed to be wrong if you think you have something to add that's relevant to the topic... but OK.

> Secondly, you're conflating the actions of composer, PSR-0, PSR-4 and the FIG in a way unlike nobody else. 

I've been using PSR-0 for years without ever having to use Composer. So there's no need telling me that they're not the same.

> If you want this folder structure, then you can do that:
> 
> ````
> Project 
>   |__ Index.php
>   |__ App
>        |__ Controllers
>        |__ Models
>        |__ Views
> ````

Only if I name my default controler something like `\App\Controller\Default`, whereas I prefer `\App\Controller_Default`.

PSR-4 no longer supports that and forces every folder to have its own namespace. I find that utterly ridiculous!

> The AWS PHP SDK does have a functions.php, for namespaced functions. That's great. Not everything in PHP needs to be a class, and having functions is completely ok.

I have to agree with @e-oz here. Allowing this kind of bad practices is a step backward and NOT a step forward!

> Not true. Set the namespace prefix to the root of the source folder and you're identical to PSR-0.

Again, PSR-4 doesn't allow me to both (1) use a file structure like [**`vendor/PowerTools/DOM/Document.php`**](https://github.com/PHPPowertools/DOM-Query/blob/master/vendor/PowerTools/DOM/Document.php) and [**`vendor/PowerTools/Event/Listener.php`**](https://github.com/PHPPowertools/Event/blob/master/vendor/PowerTools/Event/Listener.php) and (2) name my classes `\PowerTools\DOM_Document` and `\PowerTools\Event_Listener`.

Again, PSR-4 doesn't allow me to use a single namespace `\PowerTools` for ANY class in my framework, which is how I prefer to use namespaces.

> This was an explicit goal of PSR-4. Underscores (a.k.a "Poor Mans Namespaces") were used in a < PHP 5.2 world, and are useless in a PHP 5.3 world.

I don't see why "Poor Mans Namespaces" are useless in a PHP 5.3+ world. I don't see why every folder is supposed to refer to a seperate namespace. IMO, it makes no sense whatsoever for different classes of the same library (or even the same framework) to use different namespaces. There is little to no advantage to that if your projects are well-managed.

Also, I don't want statements like `use PowerTools\Event\Listener As EventListener` to pollute my projects... nor do I don't want to use fully qualified names like `\PowerTools\Event\Listener` either. IMO, it makes far more sense to use references like `Event_Listener` without namespaces and without `use` statements whenever I'm refering to a class within the same framework.

> They also carry a bug which PSR-4 got rid of.

If you use the naming conventions I'm using, it's a bug you never encounter at all. It's hardly a reason to deprecate a popular convention that still has its use cases. In fact, it's precisely this convention that allows [**Kohana framework**](https://github.com/kohana/kohana) (I really love their HMVC architecture) to have such elegant, readable code!

> Deprecation is entirely logical, has zero downsides and helps point developers in the right direction

Zero downsides?

Breaking compatibility between PSR-0 and PSR-4 is a major downside imo, which significantly complicates writing your own universal autoloader and inevitably has a negative impact on performance.

> That's also why you're **blaming me** for the actions of the FIG, despite me joining *after* PSR-2. Lol.

I have no problem with PSR-1, PSR-2 or PSR-3, because neither break compatibility with PSR-0. You could use a single universal autoloader for any package written in any of these standards, because PSR-1 to PSR-3 are all essentially just refinements of the same PSR-0 standard.

PSR-4 is the first PSR-X standard to break compatibility with PSR-0 (in several ways), which has multiple downsides (that have all been mentioned earlier).

> Nobody is forcing you to use any PSRs, feel free to use your own autoloaders. Composer lets you do that, which is why it's pretty cool.

What I want, is ONE universal autoloader that allows me to just drop ANY package into my `vendor` folder and have it work out of the box with zero per-package configuration. PSR-0 to PSR-3 allowed that, whereas PSR-4 doesn't... for several reasons!

How anyone can think PSR-4 is a step forward (compared with PSR-3) is beyond me... but then again, considering [**how full of design flaws PHP is as a language**](http://eev.ee/blog/2012/04/09/php-a-fractal-of-bad-design/), I guess I shouldn't be surprised. I gues I shouldn't expect better from a community where Zend framework ( ** yuck ** ) and Drupal ( ** shivers down my spine ** ) were the industry standard for God-knows-how-long and the beautiful Kohana is barely known at all. Maybe it's time to move on to Nodejs and ditch PHP once and for all? It sure is itching!

**Comment by e-oz** [comment]
A lot of spam, will unsubscribe (and it's a dead thread anyway), just reply to mention.

@philsturgeon 
> Not everything in PHP needs to be a class, and having functions is completely ok. 

While their autoloading is handled by vendor, not by client.

> You do not have to include this yourself, you only need to have the composer autoloader included.

That's what I'm talking about - without Composer you have to include it yourself, that's how Composer hides this crap under the hood.
____

Nothing personal, people. Sorry if some claims were looking like personal - all I said was only about code, not persons. I'm sure you all are great people.
I have no interest in PHP and in Composer anymore, Rust is my new favorite language :) Bye.

**Comment by Seldaek** [comment]
@jslegers I'm not gonna address everything bit by bit, but just a few points to consider from Composer's point of view (as this issue is on the composer repo after all):

- PSR-4 allows you to say that namespace `PowerTools\` can be loaded from dirs A, B or C. That works fine. The only thing it doesn't allow is underscores, but PSR-0 is allowed, and we won't remove support for that anytime soon if ever, so use that if you need it, I don't care. And if you are not happy about PSR-4 please take it to the FIG, it's not our problem here.
- Composer offers a `classmap` autoloader that lets you autoload *any class* following *any convention*. We do that to be compatible with everyone, to make sure that autoloading becomes as transparent as possible, no matter what piece of code you use. There goes your universal autoloader. If you refuse to use it for whatever reason that's fine, but then you forfeit your right to complain about it here.
- (personal opinion note, even though I really shouldn't) Using underscores in classnames is fine if you don't want to play by the rules, but if you want to follow PSR-4 then you follow it and you follow it quietly. If you're gonna rant all along the way then you might as well not use it, because nobody forces you. The only good side to everyone using it IMO is that things look the same everywhere, if joe X uses underscores and anna Y doesn't, my code looks like I glued random things together, it's not uniform. So if you use it, follow it and follow conventions (even if they're not written in the spec, most everyone does things the same way, do the same and everyone's happy).

**Comment by jslegers** [comment]
> The only good side to everyone using it IMO is that things look the same everywhere, if joe X uses underscores and anna Y doesn't, my code looks like I glued random things together, it's not uniform. So if you use it, follow it and follow conventions (even if they're not written in the spec, most everyone does things the same way, do the same and everyone's happy).

I loved PSR-0 because the rules were simple ánd uniform (which allows for universal class loaders).

I hate PSR-4 because it breaks backwards compatibility with PSR-0 and because it isn't nearly as uniform, due to all the customizing it allows (which doesn't allow for universal class loaders).

If you consider uniformity to be a good thing, I don't see how you can possibly think the move towards PSR-4 is a step forward!

**Comment by philsturgeon** [comment]
NEW THINGS ARE NEW I HATE CHANGE WHY CANT WE ALL DO EVERYTHING LIKE ITS 2006 CAN WE ALL JUST USE KOHANA

Enjoy Rust or whatever. I'm going to go back to Ruby and Golang. 

Don't @ me.

--
Phil Sturgeon
