### ISSUE TITLE
Add git-binary config setting (was: Composer doesn't find git)

### ISSUE THREAD

**Issue by Anahkiasen** [composer/composer#1441]
When I run `composer update` it hits me with the following error message :

    Failed to clone http://github.com/symfony/Translation, git was not found, check that it is installed and in your PATH env.

But when I do `git --version` I do get `git version 1.8.0.msysgit.0`. Where could this come from ? I've read this might stem from git not being accessible for PHP ?

```
Windows 8 — x64
msysgit 1.8.0
PHP 5.4.3
Latest Composer
```

Running the commands from Git Bash.

**Comment by sealeg** [comment]
I would be interested in tackling this if it is still considered relevant.

**Comment by curry684** [comment]
In my opinion not really - back in 2012 when the issue was opened git support on Windows was sketchy and depended on third party installers. Nowadays there are fine [official installers](https://git-scm.com/downloads) for all platforms that integrate perfectly and do all the necessary PATH modifications.

My advice to @Seldaek would be to close this issue as anachronistic, and your well appreciated efforts will be more useful elsewhere  :smile:

**Comment by sealeg** [comment]
Yeah, it was @th3fallen's comment that made me think it might still have merit. Thanks for the feedback.

**Comment by Seldaek** [comment]
Agreed, probably not necessary.

**Comment by Lancelight** [comment]
Actually this is a good request even in 2022.  I have a situation where 2 versions of git are necessary.  Being able to tell composer which git binary to use would be MASSIVE for this specific type of setup.  Most other applications allow binary locations to be passed in via config,  composer seems to be the only exception to that rule for all the wrong reasons (people thinking it's not necessary is not a valid reason heh).

**Comment by Seldaek** [comment]
> for all the wrong reasons (people thinking it's not necessary is not a valid reason heh).

It's not just that, it's that this also adds complexity to classes which are already quite complex and quite poorly tested due to the variety of edge cases covered and that testing for these is kind of a huge pain.

So yeah it's a trade-off for sure, it will get in the way of some fringe usages, but we also do support quite a broad range of git versions so having one of those in the PATH sounds like a reasonable ask IMO.
