### ISSUE TITLE
Documentation: Composer Requirements

### ISSUE THREAD

**Issue by frenetic** [composer/composer#1472]
In the Composer documentation there is no _REQUIREMENTS_ explanation.
Since it's PHP based, it's easy to assume the need of PHP.
But there is no explanation about minimum version nor required extensions.
Also, you have to guess that Composer needs GIT.

That would be nice to have this requirements explained
- Explicit is better than implicit *

**Comment by polarathene** [comment]
Is zip support implied? Looking at [this docker alpine image for composer](https://github.com/composer/docker/blob/0dbcef7c67fcf1ce30c66ff42759f6af58b4960c/1.9/Dockerfile), there appears to be a fair amount of other implicit dependencies?

Just after clarification if any of those aren't required. Does it actually require `make`,`openssh-client`,`bash`? The `zip` php extension?

Meanwhile, the official [alpine package for composer](https://pkgs.alpinelinux.org/package/v3.10/community/x86_64/composer), lists `iconv`,`json`,`mbstring`,`openssl`,`phar` php extensions as dependencies. 

I am not a PHP developer, but it seems that requirements may be more than [the docs presently state](https://getcomposer.org/doc/00-intro.md#system-requirements)?

**Comment by Seldaek** [comment]
make, openssh-client and bash are definitely not needed. Either zip php extension or system unzip is needed to extract package archives.

**Comment by stof** [comment]
git, subversion, mercurial (and other supported VCS) are needed in case you want to use a package using them (either as a custom repository, or for a source install of packages provided by a composer repository). That's why they are included in the docker image.

In practice, git is very useful (most of packages on packagist are using git as their VCS), while mercurial much less (unless your own packages are using it).

For zip, this is also an optional dependency (on either php-zip or unzip), but almost all packages hosted on Packagist are using zip as their dist archive so supporting zip is almost a must-have (having to perform source installs for all packages due to being unable to unzip their archives will be much slower).

Note that composer 2 will also depend on php-curl
