### ISSUE TITLE
Separate directory for dev dependencies

### ISSUE THREAD

**Issue by enumag** [composer/composer#1484]
When I use require-dev section I have a problem with deployment. I'd like to only deploy the non-dev dependencies but there is no easy way to determine what in the vendor directory is a non-dev dependency and what isn't. I just end up uploading everything.
The solution I'd like to see is a (possibly optional) separate directory for dev-only dependencies.
Probably related to issue #1185.
EDIT: This would probably also require a separate lock file.

**Comment by clphillips** [comment]
Hate to bring up this old thread, but it would be nice if composer could deal with this. Here's why:

If your org follows a "commit everything" mantra, and you don't want dev dependencies in your build, you have to manually remove them. This can be dangerous, however. Assume the following:

**my composer.json**
```js
{
    "require-dev": {
        "vendor/package": "~1.0",
        "othervendor/otherpackage": "~2.0"
    }
}
```

**vendor/package's composer.json**
```js
{
    "require": {
        "othervendor/otherpackage": "~2.0"
    }
}
```

Since my composer.json doesn't require **othervendor/otherpackage**, my build process removes it *after* my tests run and now my build has bugs.

If composer could be configured to use separate directories for dev dependencies, then I could safely ignore the dev-vendor directory since it would contain *only* packages that are dev dependencies (which in this simple case would be nothing).

**Comment by stof** [comment]
@clphillips use the lock file to decide what should be removed instead of the composer.json in your build process. Using the composer.json is flawed because it only contains a very small subset of the installed package anyway. The lock file has all of them, and it separates the dev packages from the non-dev ones.

**Comment by Seldaek** [comment]
@clphillips an easy way to remove dev dependencies is to run `composer install --no-dev`, if you have a lock file it should work quite quick.

**Comment by clphillips** [comment]
Thanks @Seldaek. That works as expected!

**Comment by scrobbleme** [comment]
I'm looking for the same. It should just be possible and no problem. There is no reason, why this shouldn't be possible at all. But it would make live easier for some people...

My use case: I would like to be able to use WordPress as a development requirement, so I can make use of autocompletion.... Of course I don't want to include WordPress while development, as I can't deploy WordPress into WordPress....
As of now, I have to explicitly add WordPress as separate dependency within my IDE and so partially broken the composer workflow.

**Comment by alewolf** [comment]
You can use `composer install --no-dev` to remove the dev packages before roll out and then `composer install` before continuing to develop.
