### ISSUE TITLE
Error when install PHPUnit via composer on shared linux hosting

### ISSUE THREAD

**Issue by yuanzhou** [composer/composer#1513]
I've installed composer successfully on my Macbook, but when I tried to install composer on my shared linux hosting with "php composer.phar install", I got the following error.

```
# php composer.phar install
Content-type: text/html


Fatal error: Uncaught exception 'ErrorException' with message 'Undefined index: argv' in phar:///my_web_apps/system/composer.phar/vendor/symfony/console/Symfony/Component/Console/Input/ArgvInput.php:57
Stack trace:
#0 phar:///my_web_apps/system/composer.phar/vendor/symfony/console/Symfony/Component/Console/Input/ArgvInput.php(57): Composer\Util\ErrorHandler::handle(8, 'Undefined index...', 'phar:///home2/i...', 57, Array)
#1 phar:///my_web_apps/system/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(98): Symfony\Component\Console\Input\ArgvInput->__construct()
#2 phar:///my_web_apps/system/composer.phar/src/Composer/Console/Application.php(82): Symfony\Component\Console\Application->run(NULL, Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///my_web_apps/system/composer.phar/bin/composer(39): Composer\Console\Application->run()
#4 /my_web_apps/system/composer.phar(15): require('phar:///ho in phar:///my_web_apps/system/composer.phar/vendor/symfony/console/Symfony/Component/Console/Input/ArgvInput.php on line 57
```

Here is my composer.json

```
{
    "name": "phpunit",
    "description": "PHPUnit",
    "require": {
        "phpunit/phpunit": "3.7.*"
    }
}
```

Does anyone have any ideas on this? Thx.

**Comment by php-daddy** [comment]
Thanks @zanderbaldwin :+1:

**Comment by hdushku** [comment]
php-cli composer.phar <command>

**Comment by merhawifissehaye** [comment]
@zanderbaldwin what security issues can be there by allowing php-cli

**Comment by stof** [comment]
@merhawifissehaye no more issues that if you give people a CLI access to your server but give them the CGI sapi. the security implication is not the fact that the php cli is available, but the fact that the user has access to your server

**Comment by zanderbaldwin** [comment]
@merhawifissehaye, none really. Hosting companies can be idiots.

**Comment by SaifurRahmanMohsin** [comment]
@zanderbaldwin A thumbs up indeed to my current shared hosting provider “hostinger”. They provided ssh access with exec turned off and also a cgi-fcgi SAPI version of the PHP command so I am unable to install composer. The sad thing is that they [seem to support Composer](https://github.com/hostinger/example-app) but do not really allow composer to be installed nor have it pre-installed. I even tried your command `php -d register_argc_argv=1 "./composer.phar” install` sadly that doesn’t work since it’s a cgi-fcgi SAPI version. Know any other possible workaround?

**Comment by curry684** [comment]
You can just download the phar directly and use it from your home directory.

**Comment by paolooo** [comment]
@zanderbaldwin Try to locate the `php-cli`. You'll notice that it is a php-cli, when you run `php -v` it will show **(cli)**. See example below. On hostmonster, it is located in 

For php 5.4

```
$ /usr/php/54/usr/bin/php-cli -v

PHP 5.4.43 (cli) ...
```

For php 5.6

```
$ /usr/php/56/bin/php -v
PHP 5.6.17 (cli) ...
```

If you were able to locate the file. Then, run your command. As for this example, I'll run php 5.6

```
$ /usr/php/56/bin/php -d register_argc_argv=1 "./composer.phar" install
```

**Comment by curry684** [comment]
Other ways to discover whether you have different PHP executables:
```sh
which -a php
```
Shows all `php` commands on the current PATH instead of just the highest priority one.

Or use locate:
```sh
locate -br ^php$
```
Shows all files called *exactly* `php` on the entire system. You may need to `updatedb` first. Leave out the `$` to search for files *beginning* with `php` instead.

Finally the slowest option:
```sh
find / -type f -perm /a+x -name "php*"
```
Will find all executable files on your system whose name starts with `php`, so also `php56`, `php-cli` or whatever it may be called.

**Comment by SaifurRahmanMohsin** [comment]
@curry684 Thanks for this info. I was able to find one cli version of php at `/opt/php-7.0/bin/php`.
I could not move `composer.phar` to `/usr/local/bin/composer` due to restrictions so I ended up making a .bash_profile with the code:
```
alias composer='/opt/php-7.0/bin/php ~/composer.phar'
```

Now it works fine. Thanks again for the info.

**Comment by curry684** [comment]
Happy to help  :smile:

**Comment by morgzz** [comment]
@SaifurRahmanMohsin your advice helped me.
cPanel environment running multiple PHP versions.

`alias composer='/opt/cpanel/ea-php70/root/usr/bin/php -c ~/php.ini ~/bin/composer'`

into .bashrc

**Comment by hoahovan** [comment]
@zanbaldwin 
Thank you, it is working on my server.
