### ISSUE TITLE
Packages changelog

### ISSUE THREAD

**Issue by ArabCoders** [composer/composer#1524]
Can we add new feature to composer where you can get the package changelog?

for example packageX got updated, you can write in console "composer (log/changelog) packageX"

and it will list the changelog of that package version?

**Comment by mhitza** [comment]
I would actually like this feature as well, however I would have a different proposal instead of getting into the hairy details of standardizing a format.

I would like a `--summary` flag for composer update which would generate/overwrite a update.summary file and would contain the following (only for the top level dependencies, and would not recur on their dependencies)

```
dependency-name (ex symfony/symfony)
  hash first line of the commit message
    The full body of the commit message
```

The indentation would help (I guess in almost all editors) that have the option to fold code based on indentation level (instead of using specific markers). You've got both an auto-generated "changelog" (of sorts) and an easy way to navigate it.

**Comment by kanariezwart** [comment]
:+1: 
I was just thinking the same, adding a summary of updated dependencies. Something like a diff if you will. Perhaps something a feature that looks at the existing composer.lock (or composer.json) and the new one, and computes the updated version differences :
```
Updated packages:
- dependency-name:
   - from: 1.x.x (#hash)
   - to: 2.x.x (#hash)
- another-dependency:
   - from: 1.x.x (#hash)
   - to: 2.x.x (#hash)
```
Something you might want to add to a commit message of composer.lock update

**Comment by Seldaek** [comment]
Could be done as a plugin if someone really cares, going to close this here as I don't think we want to do it and maintain it..
