### ISSUE TITLE
composer update results in: RuntimeException: Failed to clone http://github.com/composer/installers.git 

### ISSUE THREAD

**Issue by prembo** [composer/composer#1707]
I haven't had any issues with composer updates on this project until I did a composer `self-update` yesterday.  

Now I seem to getting these exceptions for most modules including `composer/installers`.  Anyone else experiencing this?

``` bash
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Updating composer/installers dev-master (f5dea66 => v1.0.3)
    Checking out v1.0.3

  [RuntimeException]                                                                                      
  Failed to clone http://github.com/composer/installers.git via git, https and http protocols, aborting.  

  - git://github.com/composer/installers.git                                                              
    fatal: Not a git repository (or any of the parent directories): .git                                  

  - https://github.com/composer/installers.git                                                            
    fatal: Not a git repository (or any of the parent directories): .git                                  

  - http://github.com/composer/installers.git                                                             
    fatal: Not a git repository (or any of the parent directories): .git                                  

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [-v|--verbose] [-o|--optimize-autoloader] [packages1] ... [packagesN]
```

**Comment by salarmehr** [comment]
@Seldaek  That is a workaround.
I had the issue several times. If deleting a folder is safe composer need to do it by itself.

**Comment by Seldaek** [comment]
Yeah composer could catch this particular exception and in case it happens wipe the dir and try again, but this only happens if you mess up with the vendor directory yourself though. By default everything works fine. And if you mess with the .git dirs of vendors you might have other issues than this one, like it'll try to git checkout your main project's git repo instead of the vendor's repo as git automatically looks up directories to find a git dir. All in all by messing with the vendor dir you void the warranty..
