### ISSUE TITLE
The "https://packagist.org/packages.json" file could not be downloaded: failed to open stream: Cannot allocate memory

### ISSUE THREAD

**Issue by mynona** [composer/composer#1775]
osx 10.8, php latest version, composer latest version

What am I doing wrong? Any ideas?

**Comment by Josue198s** [comment]
Compose.json is killing me, I cant put my head around it..

**Comment by Josue198s** [comment]
See https://getcomposer.org/doc/04-schema.md for details on the schema
name : The property name is required
description : The property description is required
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
root@lab-VirtualBox:/var/www/html/alogin#

**Comment by alsemany** [comment]
I had the same issue and just resolved it
 this usually because of multiple php versions 
first of all try to login ssh as root 
and try 
`# composer selfupdate `
you should see the same issue here ,
check which php version running for the root 
`# php -v`
now go to the exact version which running with the root and edit php.ini 
allow_url_fopen = on 
if you had any issue with memory allocate try to increase the memory allocation 
memory_limit = 128M
now again after updating the php.ini file for the root version and with the root permission use this 
`# composer selfupdate `
then 
`# su myusername `
and you can use composer

**Comment by lequy1010** [comment]
Please disable IPv6.
https://blogcakephp.wordpress.com/2017/04/21/the-httpspackagist-orgpackages-json-file-could-not-be-downloaded-failed-to-open-stream-operation-timed-out-retrying-with-degraded-mode-check-httpsgetcomposer-orgdocarticlestroubleshoo/
