### ISSUE TITLE
Case insensitive classmap

### ISSUE THREAD

**Issue by fprochazka** [composer/composer#1803]
Hi,
it would be great, if the generated classmap autoloader would be case insensitive (at least for the classes found by robot loader), it would have saved us a really nasty WTF moment.

**Comment by black-snow** [comment]
I've just wasted 2+ hours to figure out why my app runs fine on my windows dev machine but not on my *nix staging system. Turns out it's due to Composer not loading my files since they're located in app/controller but the namespace is App/Controller which is just fine w/ ci file systems.

**Comment by hco** [comment]
@Seldaek I reconsidered what I think about this issue.

I think that the user experience could be improved for some users, if the classmap would be case sensitive.
I understand that for some users, the call to strtolower would be a performance problem.

So that's a point where you have to balance user experience vs performance.
My suggestion would be two implementations of generating the classmap - a case insenstive approach, and the current, more performant, case sensitive approach.
I would suggest making the case insensitive implementation the default & announce this change loudly, so that those, for whom the performance of the classmap actually matters that much, can adjust their configuration accordingly.

That could result in everyone being happy - new users don't struggle with the case sensitivity, and power users that profile their application and see all those strtolower-calls as a performance issue will be able to google that problem and find the configuration switch.

We worked around this issue, so I'm really not caring about my personal work, but rather about the user experience of users new to composer (and thus the adoption rate of composer) :)

I'd be happy to support you on the implementation, if that would be a feasible way for you to go.

**Comment by black-snow** [comment]
@hco That's a great approach. +1

**Comment by stof** [comment]
@hco this would mean that the behavior of your app would be different depending on whether your autoloader has the optimized classmap or no though, as the PSR-0/4 lookup would still be case sensitive

**Comment by hco** [comment]
@stof Agreed. But I assume that most would use PSR 0/4 Autoloader in development and use the optimized one in production (if they mix them at all), which would reduce problems in production, but increase them in development, right?

**Comment by Seldaek** [comment]
Please see #4209 and let's move the discussion there if you have more points to add.

**Comment by phuib** [comment]
Another DIY option is to rewrite composer's classmap on **post-autoload-dump** and change all the keys to lowercase.

e.g.
composer.json
```javascript
    "scripts": {
        "post-autoload-dump": [ "MyClassLoader::postAutoloadDump"]
    }
```

MyClassLoader.php
```php
class MyClassLoader {
    static public function postAutoloadDump() {
        $classmapFile = __DIR__ . '/vendor/composer/autoload_classmap.php';
        if(file_exists($classmapFile)) {
            file_put_contents($classmapFile, sprintf("<?php\n return %s;",
                var_export(array_change_key_case(require $classmapFile), true)
            ));
        }
    }
}
```

**Comment by AndryG** [comment]
composer has so many different options and can't add "class-map-case-insinsitive"?
Where is the logic?

Don't want to inject ONE function into your code ?! Well, let's make it a really slow plugin or something. To persist in not fixing a common inconvenience ... is stupid.

**Comment by stof** [comment]
@AndryG that's not only about adding an option. that also means adding a runtime logic in the ClassLoader to support this option, which impacts all Composer projects (whether they use the option or no)

**Comment by AndryG** [comment]
Are we really arguing about one “if” in the code right now? It's real? 
When a classmap loads hundreds and thousands of class names into memory, are we arguing about one "if"? 
We are now arguing with common sense. :)

```    /**
     * Loads the given class or interface.
     *
     * @param  string    $class The name of the class
     * @return bool|null True if loaded, null otherwise
     */
    public function loadClass($class)
    {
        if ($file = $this->findFile($class)) {
            includeFile($file);

            return true;
        }
    }
```

"findFile()" used **once**, but specified in a separate method. Isn't the struggle for resources important here?
```
    public function findFile($class)
    {
        if($this->classMapCaseInsensitive){
          $class = strtolower($class);
        }
        // class map lookup
        if (isset($this->classMap[$class])) {
            return $this->classMap[$class];
        }
```
or

```
   public function findFile($class)
    {
        // class map lookup
        if (isset($this->classMap[$class])) {
            return $this->classMap[$class];
        }elseif($this->classMapCaseInsensitive && isset($this->classMap[$tmp = strtolower($class)])){
          return $this->classMap[$tmp];
        }
```
or
```
    public function findFile($class)
    {
        // class map lookup
        if (isset($this->classMap[$class])) {
            return $this->classMap[$class];
        }elseif($this->classMapCaseSensitive && ($res = $this->classMap[strtolower($class)] ?? false)){
          return $res;
        }
```

__question price - one branch on a simple boolean field__ 

sorry for my google-english :)

**Comment by AndryG** [comment]
> runtime logic in the ClassLoader to support this option, which impacts all Composer projects (whether they use the option or no)

```
        if ($this->classMapAuthoritative || isset($this->missingClasses[$class])) {
            return false;
        }
```

Two options. Everyone is alive and happy ...

**Comment by stof** [comment]
> When a classmap loads hundreds and thousands of class names into memory

The code generated by Composer is specifically meant to *avoid* loading the classmap in memory, by making sure that OPCache does not need to copy it from shared memory to process memory due to triggering copy-on-write (that's why for cases needing to use a dynamic config of a ClassLoader, it is much better to register a separate instance for the dynamic cases rather that dynamically changing the config of the instance managed by `vendor/autoload.php`, as this would undo that optimization).

> Two options. Everyone is alive and happy ...

these are conditions running only for classes which are not found in the classmap, which is not something you will find in the hot path typically (your code is a lot more likely to use classes that exists than classes that don't exist), and they are here to prevent running a more costly logic (checking the filesystem for PSR-4 rules).

And turning your proposal will also have a perf impact: your proposal involves adding a `strtolower` call for *each* autoloaded class, even when the code using the class was using the same case than the code defining the class (your first solution), or doubling the size of the classmap by including both the original case and the lower case (your second and third solutions).
And in the first solution, you still check the boolean option for each call even when disabled (the other solutions are only checking it when not found). Even though reading a boolean property is not considered a slow operation in PHP, doing something in the hot path is still something that needs to be measured compared to doing nothing (the composer ClassLoader is in the hot path of *all* projects using Composer for autoloading, unless they turned on preloading in PHP 7.4)

**Comment by AndryG** [comment]
The first variant is an simple and bad option. I agree too.

The second and third options imply the create one "lower-ClassMap". 

I understand that in this case the first condition ` if (isset($this->classMap[$class]))` will be triggered less often than usual, but this is an acceptable price for simply maintaining the legacy code

You just haven't seen the old autoloaders :)

**Comment by AndryG** [comment]
Gentlemen, let's add one small "IF", which will greatly simplify the implementation of the product on old projects!

**Comment by AndryG** [comment]
If you don't want to meet old projects, please tell me, can this be done with a plugin?

**Comment by Seldaek** [comment]
Anyone can build their own autoloader and reuse the composer stuff that is dumped in vendor/composer/... You don't even need a plugin. Requiring the vendor/autoload.php is completely optional and you can replace that in your project with an alternative autoloader.

**Comment by AndryG** [comment]
How to generate classMapCaseInsensitive for an alternate autoloader?
