### ISSUE TITLE
Scripts not obeying process-timeout setting

### ISSUE THREAD

**Issue by cmenning** [composer/composer#1894]
We have some long-running post-update scripts (Assetic compiling Compass assets) on a low-powered webserver, and Composer is not obeying the process-timeout setting either in the composer.json or in the environment variable.

This is my composer.json:

``` json
{
    ...
    "config": {
        "bin-dir": "bin",
        "process-timeout": 1000
    }
    ...
}
```

I also tried:

``` bash
$ export COMPOSER_PROCESS_TIMEOUT=1000
$ php composer.phar install -o
```

and

``` bash
$ COMPOSER_PROCESS_TIMEOUT=1000 php composer.phar install -o
```

In both cases, the script terminates after Assetic has been executing for 300 seconds.  It does not seem to be applying the config value to the timeout.

Server is a small Amazon EC2 instance running Ubuntu 12.04.

**Comment by devprojectsapps** [comment]
Hi.
I have something similar.
We are using for Laravel Deployment the Envoyer platform.
We have the problem that the Deployment Hook "Install Composer Dependencies" stops at 600 Seconds on one server.
So the Deployment does not go through since days.
I found the possibility to set a config param "process-timeout" in the composer.json but nothing happens. That is not considered.
I have no idea where I should still look to change this value or increase.
Can someone help me?

**Comment by bricehartmann** [comment]
@devprojectsapps did you ever find a solution to your envoyer hook timeout?
