### ISSUE TITLE
Allow to disable the cache via an argument

### ISSUE THREAD

**Issue by dorongutman** [composer/composer#1896]
something like 
```
php composer.phar update --no-cache
```

**Comment by ethanclevenger91** [comment]
Use case:
I'm writing a custom package into my `composer.json` to grab a paid WordPress plugin zip. I have to define a version here. I can use the same URL to the zip every time even when the plugin is updated. I reuse this `composer.json` file often, and unless I update the version I have assigned it in the package, I get the plugin from my cache, which is outdated. I'd rather tell it to ignore the cache for this package and refetch it every time.

```
{
        "type": "package",
        "package": {
            "name": "acf/acf-pro",
            "type": "wordpress-plugin",
            "version": "1.0.0",
            "require": {
                "composer/installers": "~1.0"
            },
            "dist": {
                "url": "http://connect.advancedcustomfields.com/index.php?a=download&p=pro&k=[my-key-here]",
                "type": "zip"
            }
        }
    }
```

Even though version 5.2.4 may be what would be downloaded, composer doesn't go get it because the version I've assigned hasn't changed, so it get 5.2.2 from my cache.

**Comment by stof** [comment]
@ethanclevenger91 if the plugin changes, you need to bump the version. Otherwise it will create lots of weird issues (one of the dev has an old version of the plugin installed, but running ``composer update`` won't get the new version given that composer considers that 1.0.0 is already installed).

this is one of the reasons why the ``package`` repository is a pain to manage.

**Comment by ethanclevenger91** [comment]
That's what the no-cache flag would be for. It says "if you do composer 
install or update, fetch it from the src no matter what". In this 
particular use case the plugin should always be updated anyway - a dev 
with an old version should be updating anyway. Perhaps that's an oddly 
specific use case?

**Comment by stof** [comment]
@ethanclevenger91 even if the composer cache is ignored, this won't change the fact that this package is already **installed** in the project (I never talked about the cache in my previous comment).

**Comment by ethanclevenger91** [comment]
Got it. So I guess my need, rather, is that if I call `composer update`, overwrite no matter what (on specific packages).

**Comment by slbmeh** [comment]
@ethanclevenger91 you need to either update the version each time so installed repository knows that it's outdated, or you need to delete the installed dependency before each update.

**Comment by Seldaek** [comment]
Closing this as it just does not make sense, if there are real issues with the cache please report a new issue with details so we can fix things.
