### ISSUE TITLE
Composer update runs out of memory

### ISSUE THREAD

**Issue by jrooi** [composer/composer#1898]
Running the "composer update" command results in a fatal error:

Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 79 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleWatchGraph.php on line 100

Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 71 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Solver.php on line 700

Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 72 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleWatchGraph.php on line 104

I already tried removing the vendors in my Symfony2 project. After removing the vendors and running a "composer install" command I get no errors. Running a "composer update" directly after the install results in the same memory error. The current memory limit is set to 512MB, that should be enough, right?

What can be the cause of the sudden memory issue? Can I take other steps in solving this issue? As far as I can tell, the dependencies haven't changed and I don't include many vendors. 

Any help is much appreciated!

Kind regards,
Jeroen van Rooij

Ps. I'm using the latest composer version and al the requires in the json are set to a fixed version

**Comment by seanlindo** [comment]
@CaptainN This worked perfectly.

**Comment by mrofi** [comment]
I have same issue when I would install laravel 4.2 on my openshift gear. 
Even I use a small gear that only has 512 MB RAM, this solved the issue 
php -dmemory_limit=2G /var/lib/openshift/.cartridge_repository/redhat-php/0.0.23/usr/bin/composer.phar install

**Comment by velikanov** [comment]
@Seldaek :+1: :+1: :+1: for running **composer install** on production!

**Comment by mailightkun** [comment]
This solved my problem base on their Suggestion:
https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors

**Comment by phirschybar** [comment]
this worked for me as well: https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors

**Comment by kumarramalingam** [comment]
Solve this problem.

Update PHP Version.
Ubuntu Terminal window:

1.sudo apt-get update

2.sudo apt-get install lamp-server^

That's all.

**Comment by cbrunnkvist** [comment]
_"You're on the wrong server" / "You don't have enough swap" / "Problems like this are not always meant to be fixed"_?? Whaaaat, seriously? Is everybody (with the brilliant exception of @stof and @judgej) turning into total apologists? :worried: 

The issue still remains: something is wrong, because it is _insane_ that such an important and central tool such as the dependency manager, should gobble up gigglypiles of memory just in order to complete it's most basic tasks.

**Comment by cbrunnkvist** [comment]
For reference: mem usage stays stable on my Yosemite Mac (PHP 5.5.20) but totally blows up on my Ubuntu Trusty deployment (PHP 5.5.9-1ubuntu4.9). None of the workarounds above has any effecty ~ it must be some triggering some leak in that older ("stable") version of PHP.

**Comment by slbmeh** [comment]
> The issue still remains: something is wrong, because it is insane that such an important and central tool such as the dependency manager, should gobble up gigglypiles of memory just in order to complete it's most basic tasks.

Dependency resolution is not it's most basic task, on the contrary it is the most complex task. Being such a critical piece of the application, it is rather difficult to make improvements to. Servers generally have less memory than a development machine and it is recommended to do the update in your development environment and simply do an install from the lock on a server.

The solver is computing a solution for a graph theory equation. It basically does a tsort with an unbounded set discovering additional dependencies to consider for resolution throughout the process. The larger the graph the more memory required to compute the result. When you introduce potential nodes to the graph via discovery through a service like packagist that provides a large number of alternatives it increases the complexity and required memory/compute time.  A traditional tsort algorithm has a complexity of O(log^2 n).

**Comment by cbrunnkvist** [comment]
I would stress that my use of "basic" is not in the sense of "simplistic and of low complexity" - but in the meaning that this task is quintessential, and critical, to the goals of the program.

If we can conclude that there is nothing obviously wrong with the algo. implementation itself, then one way to start dealing with the problem could be to build up a dataset of known PHP version where bloat occurs and at the very least display a warning at execution time. Ideas?

**Comment by slbmeh** [comment]
It isn't a specific PHP version that causes bloat, it is a factor.  Packages can have dependencies on different PHP versions.  The largest factor is the dependencies themselves.  For instance `"symfony/symfony": "^2.7"` is a much simpler constraint because it performs a replaces for all of it's subpackages with `self.version`... this eliminates a huge subset of possibilities because each sub package does not need to be evaluated. 

The bloat generally occurs whenever you have a dependency somewhere down the line that has a large number of potential candidates. For instance, if you only require a subset of symfony packages they will need to be calculated individually to satisfy each constraint and dependency. If you drop that constraint down to `^2.3` you introduce a significant number of possibilities to evaluate.

The ideal goal of maintaining backwards compatibility with other open source packages, a good motivation IMO, is the main killer of the memory utilization of composer.  When a new version is released that meets your constraint it needs to be evaluated.

**Comment by cbrunnkvist** [comment]
> "Packages can have dependencies on different PHP versions"

:bulb: Aaah darn, good point...

**Comment by mpemberton5** [comment]
I turned off xdebug and still had problem.  Turned off OpCode for cli and worked like a dream (and fast too).

**Comment by orhan-proven** [comment]
I turned off xdebug and it works now.

**Comment by fabianhenzler** [comment]
Haflinger ist with HHVM too

**Comment by ronnyandre** [comment]
Thanks @kureikain
Your solution solved my problem! :+1:

**Comment by chrisg123** [comment]
I was having this issue. Updating composer and it seems to have solved it for me...

**Comment by Aldibe** [comment]
i got this error when running `composer.phar update`. and i think it is similar to this issue, but i don't know how to fix it.. 

`PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 144115188075867549 bytes) in phar:///bin/composer.phar/src/Composer/Util/RemoteFilesystem.php on line 179`

this is my composer.json

`{
        "description" : "The CodeIgniter framework",
        "name" : "codeigniter/framework",
        "license": "MIT",
        "require": {
                "php": ">=5.2.4",
                "videlalvaro/php-amqplib": "2.5.*"
        },
        "require-dev": {
                "mikey179/vfsStream": "1.1.*",
                "videlalvaro/php-amqplib": "2.5.*"
        }
}`

is it possible/normal for composer to allocate that much memory??

**Comment by stof** [comment]
during an update, it can indeed use lots of memory

**Comment by konstantin-komelin** [comment]
I might have missed some of the comments above but since this issue is still open I'll add my two coins.
My system:  
VPS: 1Gb RAM, Ubuntu, ssd, no swap (I don't need it)
My situation:  
I successfully updated composer to the latest using self-update command. Then I tried to [update Drush to the latest](http://docs.drush.org/en/master/install/#composer-one-drush-for-all-projects) but received the memory error discussed in this issue.  
I used the following command: ```composer global require drush/drush```

I did this way because it's required by official Drush documentation which is used by thousands so the suggestion to use composer on my local machine and then move to Git is not for me obviously.

Of course, I can temporary increase memory to 1G but folks... really... it's too much for one utility tool and it's probably not a PHP problem but a problem of the composer architecture.

So, maintainers please think about this when you're planning roadmap for future versions because I believe that no one utility tool deserves 1G of memory even if it's local machine memory. Thanks.

**Comment by stefandoorn** [comment]
@barryvdh Ain't your suggestion more like this, just a suggestion:

* Composer update
* Composer copies composer.json to composer.json.tmp
* Get all dependencies from root projects and add to require part in composer.json.tmp
* Internally run composer update again but then using the temporary file, which seems faster and less memory in your examples
* After update, remove composer.json.tmp file and write composer.lock file

**Comment by TengfeiQi** [comment]
这个问题好蛋疼
```
Fatal error: Uncaught exception 'ErrorException' with message 'proc_open(): fork failed - Cannot allocate memory' in phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:940
```

**Comment by SiliconMind** [comment]
I'd consider this more than serious. I just tried to install Symfony CMF. I needed to increase memory limit to 2G in order to avoid constant out of memory issues. Come one guys! There is something seriously wrong with the composer. I'm managing dozens of dev machines and it was the first time for past few years that I had to increase it's memory over 1G and for what? A composer install?

With recent boom for small cloud dev machines this will become a serious issue.

**Comment by judgej** [comment]
@SiliconMind Be more specific about the version you want to install. That is the key. Don't give composer the option to have to investigate every possible combination of every single package that is needed to install your framework; if you do, then it will be trying out mkany thousands of possible combinations to find the perfect latest compatible set of packages, and it is that what eats memory.

**Comment by staabm** [comment]
Did you check the tipps mentioned at https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors ?

**Comment by staabm** [comment]
Also it would be very helpfull when you could create a blackfire profile of your run (after you increased php-memory-limit to a value high enough that it doesnt crash)

**Comment by SiliconMind** [comment]
@judgej You know, I can handle myself a lot but I don't think that's the point. Consider someone less experienced that visits [Symfony's CMF install instructions](http://symfony.com/doc/master/cmf/quick_tour/the_big_picture.html) and sees this: `composer create-project symfony-cmf/standard-edition cmf '~1.2'`.

You can't expect that average John Developer will know composer inside out. And frankly, the versions for Symfony CMF are pretty precise. Maybe related packages are not specific enough, but you can't expect that all end users will now start to edit related composer.json files in hope of finding the source of the issue.

**Comment by SiliconMind** [comment]
@staabm xdebu was disabled. It was vanilla debian install without any additional stuff. As for the profile - I'm sorry, I can't do this now.

**Comment by garethmcc** [comment]
I have been plagued by this issue for over two years now and the official response is still "add swap"? This should not be a problem and its ridiculous that it isn't resolved yet. If a memory issue such as this made it into anything I released I would lose my job.
