### ISSUE TITLE
Error output printed to STDOUT instead of STDERR

### ISSUE THREAD

**Issue by scribu** [composer/composer#1905]
I'm writing an installer that runs several Composer commands. I want to suppress informational messages, such as "composer.json has been updated", but not error messages.

Currently, Composer prints everything to STDOUT, so the following will suppress everything:

```
composer update > /dev/null
```

Same problem with the `--quiet` flag.

**Comment by r1pp3rj4ck** [comment]
I agree with implementing the `writeError`. Any progress on this? It would be awesome for deployment with Capistrano for example.

**Comment by Seldaek** [comment]
Adding writeError to IOInterface/ConsoleIO is pretty easy, but reviewing all the ->write calls is the main part of the work, if you feel like doing that though feel free :)

**Comment by BreiteSeite** [comment]
@dzuelke 

> Any status report, progress info, help output on wrong usage (but not when doing composer help etc) should end up on STDERR.

I'll agree with "help output on wrong usage", but not with "status report" and "progress info"

> Right now, it's not possible to programmatically use Composer's output for some things. For instance, $(mkdir $(composer config bin-dir)) will fail if Composer is older than 30 days, as the output of composer config bin-dir will be

> ```
Warning: This development build of composer is over 30 days old. It is recommended to update it by running "composer.phar self-update" to get the latest version.
vendor/bin
```
> However, the first line should be written to STDERR and the second line to STDOUT.

IMHO there are two problems. First one is, the Warning which is displayed have actually nothing to do with the command. Yes, it probably should be on STDERR, but it shouldn't be there in the first place if you use --quiet (which is a very common practice when chaining commands together).

I would be careful to output everything on stderr because of this use-case. status-report/progress-info should be on stdout, but hidden when using --quiet in my opinion, because output on stderr is - like the name suggests - often used to indicated an error happend.

PR #4091 is about this change, because progress information/status updates are verbose information, not error-related information.

**Comment by nevvermind** [comment]
> because output on stderr is - like the name suggests - often used to indicated an error happend.

Quoting from http://lists.gnu.org/archive/html/bug-wget/2011-02/msg00034.html
```
> In what cases do we use stderr for something different than an error
> message?

Literally everywhere, other than outputting downloaded content (and as
you point out, --help). Progress bars. Informational messages.
Connection status. You name it. Everything goes to stderr.

Note that stderr is not "just for errors". The C standard describes
stdout as being "for conventional output", and stderr "for diagnostic
output". It is very frequently used in Unix for informational "out of
band" messages (i.e., any output that shouldn't be included in output
that might be redirected to another program as input).
```
I tend to agree with the guy.

**Comment by BreiteSeite** [comment]
Well... i assumed stderr means "error-only". However thought about the statements mentioned/quoted/linked in here in the last couple of days and i changed my mind.

It seems better to output on stdout only the intended-working-output and anything else on stderr and use the return code for checking if errors occured.

Thanks for the information (especially @nevvermind for the quote).

Keep up the good work.
