### ISSUE TITLE
run Composer from php script

### ISSUE THREAD

**Issue by ghost** [composer/composer#1906]
Hi!

I have tried different ways to run Composer from php script. My script creates a composer.json by filled form and then I want to run composer install from the php script.

I have tried:
- <?php ... system('/usr/local/bin/composer install -d /home/...', $return); ... ?> not work
- <?php ... system('/home/.../composer_run.sh', $return); ... ?> It script (/home/.../composer_run.sh) work, when I run it from console, but not work from php system

How can I run composer install from php script?

**Comment by Nayjest** [comment]
Even if I specify --no-interaction, composer command waits for input after finishing work.
Simplest solution that works for me:
```php
<?php
// executing composer from php script:
`echo '1' | php composer install --no-interaction`
```

**Comment by XedinUnknown** [comment]
Composer's "API" is worthless for *using* composer via PHP. It seems that the API is there for plugins. But using the PHP classes themselves from outside, while possible, doesn't allow calling Composer commands from PHP in any way that is helpful.

**Comment by endel** [comment]
Hi @XedinUnknown, don't know exactly what you need to achieve, but I got this working successfully here: https://github.com/doubleleft/hook/blob/master/src/Package/Manager.php

**Comment by XedinUnknown** [comment]
Hi @endel, I can see the usage of Symfony components to invoke the Composer CLI interface, not usage of Composer's PHP classes to run Composer tasks. Am I missing something?

**Comment by bhartvigsen** [comment]
Ideally you'd be able to programmatically run composer tasks, but it 
seems to be that trigering the cli commands from PHP is a decent means 
to an end, no?

**Comment by endel** [comment]
@XedinUnknown Yes, you're right. Composer API doesn't expose friendly methods for running tasks AFAIK. :/

**Comment by XedinUnknown** [comment]
@bhartvigsen, if you are using Symfony, you have the advantage of having the Symfony CLI application classes to ease your job, and have the disadvantage of having to learn how to do that first. However, without Symfony to back you up, you have to write a whole PHP wrapper for Composer, which is already in PHP. Additionally, you have no access to aspects that are not exposed via the CLI. For example, I wanted to see a particular project the way Composer sees it, with the parsed config "DOM", and the result of any plugins' actions. But I was told that this is not the purpose of Composer. Therefore, I see no use for the Composer PHP classes, apart from as a dev requirement for composer plugins themselves. This is very disappointing.

**Comment by Seldaek** [comment]
@XedinUnknown Composer is built around the symfony console component, so the component is included with composer, and the code at https://github.com/composer/composer/issues/1906#issuecomment-51632453 actually instruments that directly within a php process, no external processes needed.

An alternative is to just load up a `Composer\Composer` instance via `Composer\Factory::create()` - from that you can access most things programmatically, check all the getters on `Composer\Composer`. All you need is to pass an IOInterface instance to the factory method, and for that you can use one of the few implementations we provide or roll your own, see `Composer\IO\*`.

**Comment by XedinUnknown** [comment]
Thanks, @Seldaek, very helpful. Yes, I know that the console component is built in. However, it wasn't very clear the [last time](https://github.com/composer/composer/issues/4323) how exactly Composer's PHP API can be used programmatically to actually run Composer and interface with it in the process. I'll give your suggestion a go.

**Comment by ducktype** [comment]
This issue is closed but i don't see a clear answer, below is the code i'm trying right now, but unfortunately throws errors i'm not able to fix, someone can help?

`
error_reporting(E_ALL & ~E_NOTICE & ~E_USER_NOTICE & ~E_DEPRECATED & ~E_USER_DEPRECATED 
                & ~E_WARNING & ~E_CORE_WARNING & ~E_USER_WARNING & ~E_STRICT);

$composer_data = array(
  'url' => 'https://getcomposer.org/composer.phar',
  'dir' => __DIR__.'/.code',
  'bin' => __DIR__.'/.code/composer.phar',
  'json' => __DIR__.'/.code/composer.json',
  'conf' => array(
    "autoload" => array(
      "psr-4" => array(
        "" => "local/"
      )
    ),
    "require"=> array(
      "rmccue/requests" => "@stable"
    )
  )
);

mkdir($composer_data['dir'],0777,true);
mkdir("{$composer_data['dir']}/local",0777,true);
copy($composer_data['url'],$composer_data['bin']);

//$conf_json = json_encode($composer_data['conf'],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);
//file_put_contents($composer_data['json'],$conf_json);
//chdir($composer_data['dir']);
require_once "phar://{$composer_data['bin']}/src/bootstrap.php";

$factory = new \Composer\Factory();
$output = $factory->createOutput();
$input = new \Symfony\Component\Console\Input\ArgvInput(array());
$helpset = new \Symfony\Component\Console\Helper\HelperSet();
$io = new \Composer\IO\ConsoleIO($input,$output,$helpset);
$composer = $factory->createComposer($io,$composer_data['conf'],false,$composer_data['dir'],true);

echo "<pre>";

$cmd = new \Composer\Command\SelfUpdateCommand();
$cmd->setComposer($composer);
$cmd->run($input,$output);
/*
Fatal error: Uncaught exception 'RuntimeException' with message 'The phar signature did not match the file you downloaded, this means your public keys are outdated or that the phar file is corrupt/has been modified' in phar:///home/XXX/public_html/hsapi/.code/composer.phar/src/Composer/Command/SelfUpdateCommand.php:208
Stack trace:
#0 phar:///home/XXX/public_html/hsapi/.code/composer.phar/vendor/symfony/console/Command/Command.php(259): Composer\Command\SelfUpdateCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /home/XXX/public_html/hsapi/index.php(43): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 {main}
  thrown in phar:///home/XXX/public_html/hsapi/.code/composer.phar/src/Composer/Command/SelfUpdateCommand.php on line 208
*/

$cmd = new \Composer\Command\UpdateCommand();
$cmd->setComposer($composer);
$cmd->run($input,$output);
/*
Fatal error: Uncaught exception 'Symfony\Component\Console\Exception\InvalidArgumentException' with message 'The "no-plugins" option does not exist.' in phar:///home/XXX/public_html/hsapi/.code/composer.phar/vendor/symfony/console/Input/Input.php:157
Stack trace:
#0 phar:///home/XXX/public_html/hsapi/.code/composer.phar/src/Composer/Command/UpdateCommand.php(97): Symfony\Component\Console\Input\Input->getOption('no-plugins')
#1 phar:///home/XXX/public_html/hsapi/.code/composer.phar/vendor/symfony/console/Command/Command.php(259): Composer\Command\UpdateCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /home/XXX/public_html/hsapi/index.php(47): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 {main}
  thrown in phar:///home/XXX/public_html/hsapi/.code/composer.phar/vendor/symfony/console/Input/Input.php on line 157
*/
`

**Comment by stof** [comment]
Don't use the phar to get access to the code. It is not meant to work, as the phar is meant to be a CLI tool. You should install the composer source code instead (as a composer dependency for instance, which is the support way)

**Comment by ducktype** [comment]
If i read correctly this means there is no supported way to run composer programmatically without first relying on composer-cli?

**Comment by stof** [comment]
There is no way to download composer with all its dependencies from github (as we don't store the dependencies in the repository). There is no supported way to install composer from source without relying on the composer CLI to manage dependencies.

If you want to run Composer programmatically, there is 2 ways:

- using a subprocess to run the composer CLI tool from your own code
- installing composer itself as a dependency of your project (assuming your project is using composer to manage its dependencies) and then calling the code directly. But be careful that backward compatibility for such usage may not be guaranteed (the CLI tool will stay BC outside of major versions).

And previous comments have examples of both of this.

**Comment by ducktype** [comment]
If someone is interested in a UNSUPPORTED way to run composer without relying on CLI:

``'php
error_reporting(E_ALL & ~E_NOTICE & ~E_USER_NOTICE & ~E_DEPRECATED & ~E_USER_DEPRECATED 
                & ~E_WARNING & ~E_CORE_WARNING & ~E_USER_WARNING & ~E_STRICT);

$composer_data = array(
  'url' => 'https://getcomposer.org/composer.phar',
  'dir' => __DIR__.'/.code',
  'bin' => __DIR__.'/.code/composer.phar',
  'json' => __DIR__.'/.code/composer.json',
  'conf' => array(
    "autoload" => array(
      "psr-4" => array(
        "" => "local/"
      )
    ),
    "require"=> array(
      "rmccue/requests" => "@stable"
    )
  )
);

mkdir($composer_data['dir'],0777,true);
mkdir("{$composer_data['dir']}/local",0777,true);
copy($composer_data['url'],$composer_data['bin']);
require_once "phar://{$composer_data['bin']}/src/bootstrap.php";

$conf_json = json_encode($composer_data['conf'],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);
file_put_contents($composer_data['json'],$conf_json);
chdir($composer_data['dir']);
putenv("COMPOSER_HOME={$composer_data['dir']}");
putenv("OSTYPE=OS400"); //force to use php://output instead of php://stdout
$app = new \Composer\Console\Application();

$factory = new \Composer\Factory();
$output = $factory->createOutput();

$input = new \Symfony\Component\Console\Input\ArrayInput(array(
  'command' => 'update',
));
$input->setInteractive(false);
echo "<pre>";
$cmdret = $app->doRun($input,$output); //unfortunately ->run() call exit() so we use doRun()
echo "end!";

**Comment by strausmann** [comment]
Hello ducktype,

Thank you for the super code. It works with me so far really good.

Only I have one more question, how could I process the output from the Composer? I am primarily concerned here, e.g. The feedback was updated and if there were errors. Especially in the case of errors, I would be interested in the reason, e.g. Due to missing dependencies.

Does anyone have an idea?

**Comment by XedinUnknown** [comment]
@strausmann, I haven't tried the code example yet, as the project I was working on had to be put on hold due to the complexity of this topic. However, in the above example, `$output` is an instance of [`ConsoleOutputInterface`](https://github.com/symfony/console/blob/master/Output/ConsoleOutputInterface.php). Because ducktype is "forcing" output to go to `php://output`, I'm fairly confident that capturing output with [`ob_start()`](http://php.net/manual/en/function.ob-start.php) should work.

**Comment by gplcart** [comment]
system() works, but I had to specify COMPOSER_HOME variable.

```
        $composer_dir = '/absolute/path/to/composer.phar/directory';
        putenv("COMPOSER_HOME=$composer_dir");
        $command = "php $composer_dir/composer.phar create-project some/repository test --stability dev --no-interaction 2>&1";

        ob_start();
        system($command);
        $output = ob_get_clean();
```

**Comment by laurentdinclaux** [comment]
Using system, exec etc. I only get `sh: 1: : Permission denied error` ( [see here](https://stackoverflow.com/questions/45815117/why-cant-i-run-the-composer-script-from-php-using-exec-shell-exec-system?noredirect=1#comment78591227_45815117) )

@ducktype answer is pretty neat, but no need to use `doRun`, can use `run` with `$app->setAutoExit(false)`

Also isn't there a better way to get the output ? I tried

```
$stream = fopen('php://temp', 'w+');
$output = new \Symfony\Component\Console\Output\StreamOutput($stream);
```

then 

```
rewind($stream);
$content = stream_get_contents($stream);
```
but output misses some parsing, see the output of calling `--version`:
```
Composer version @package_branch_alias_version@ (@package_version@) @release_date@ 
```

**Comment by laurentdinclaux** [comment]
> I have one issue: it looks like output misses some parsing, see the output of calling --version:
> 
> Composer version @package_branch_alias_version@ (@package_version@) @release_date@ 

Well it was because vendor directory installed composer was used. Have to use a compiled composer "binary" to get it working properly.

**Comment by filips123** [comment]
Is there now a better way to run Composer from the script?

I want support for "plugin" (package) installation from my web admin UI, but I don't want to rely on installed Composer binary.

For now, I will use [this](https://stackoverflow.com/a/25208897/6523409) and related answers but I want to know if there is a better and simpler way.

**Comment by vith27** [comment]
Hi !

Five years later... I reopen this issues to ask if someone can help me. 
I'm using the following code to try to execute composer within a php script : 

```
    require 'autoload.php';
    // needs COMPOSER_HOME environment variable set.
    $path = __DIR__ . '/../../../../vendor/bin/composer';
    putenv('COMPOSER_HOME=' . $path);
    // Force to use php://output instead of php://stdout.
    putenv("OSTYPE=OS400");

    // Call `composer update` command programmatically.
    $application = new Application();
    $factory = new Factory();
    $output = $factory->createOutput();
    $input = new ArrayInput([
      'command' => 'update',
    ]);

    $input->setInteractive(FALSE);
    echo "<pre>";
    $cmdret = $application->doRun($input, $output);
    echo "</pre>";

```

And I'm facing the following error : 

Composer could not find a composer.json file in path/to/root/web

the composer.json is in path/to/root and the php file is executed from path/to/root/web.
I tried multiple codes to add the --working-dir path but no one seems to works...

$input->setArgument(...)
$input->setOption(...)

I tried to add definition and other things but no way...

The code is executed from a Drupal controller based on path/to/root/web/modules/custom/site_updater/src/Controller and when it's done, a new path/to/root/web/modules/vendor/bin/composer/cache is created. I think I must specify some options to make all working correctly but I can't find the way to.

If anyone could help me it would be great.

Thanks in advance.

**Comment by Seldaek** [comment]
@vith27 maybe try `chdir('path/to/root')` before running composer, that makes it a lot easier IMO.
