### ISSUE TITLE
Custom install path for user-defined packages

### ISSUE THREAD

**Issue by ghost** [composer/composer#1948]
I want to combine two things:
http://getcomposer.org/doc/05-repositories.md#package-2
and this
http://getcomposer.org/doc/faqs/how-do-i-install-a-package-to-a-custom-path-for-my-framework.md

Even if i require composer/installers for defined package, looks like composer is ignoring extra.installer-paths option

**Comment by christhomas** [comment]
I absolutely adore the way the composer programmers proclaim to know what bad practices are, are we just to throw out what we knew and adopt whatever you self proclaimed masters of programming practices even though we might need to actually support custom code written in the past that doesn't break bad practices, but flags one of the rules you've set down from above?

maybe you should get some stone tablets, I mean, if you're going to be so arrogant as to go all "moses" on us, you might as well do it properly

there are valid reasons for wanting to do things that don't comply with composers way of doing things and just because they do, doesn't make them bad practices, you're arrogance makes me sick....

**Comment by francisberesford** [comment]
haha I know right! bunch of dickheads!

**Comment by stof** [comment]
@christhomas the Composer maintainers recognized this need. This is precisely the reason why Composer supports custom installers, which can choose the place where they want to install things.

But for custom install paths to be take into account, the package must define its type using one of the types handled by the composer/installers plugin: https://github.com/composer/installers#a-multi-framework-composer-library-installer
In the case described in the issue above, the ``type`` setting of the package is not configured at all, which means it is the default value ``library``. and the ``library`` type is not handled by the composer/installers plugin. It is handled by the standard composer installer. So it is not using the composer feature properly.

**Comment by christhomas** [comment]
if they TRUELY recognised this need, they would provide a way to just override the install location on a package basis, but they didn't because there is no generic type and really it's because they don't really want to, cause they just prefer to proclaim arrogantly that this breaks good practices....GO OPEN SOURCE! YAY!.....

**Comment by shama** [comment]
@christhomas I'm sorry that my opinions on code I wrote and give for free has upset you so. The good news is it is open source licensed, so you don't have to put up with my arrogant opinions. You're free to fork and/or write your own installer.

FWIW, the Composer maintainers have provided a way to override the install location on a package basis. I'll copy and paste the solution @stof gave in really big letters as I think it was missed:

> # This is precisely the reason why Composer supports custom installers, which can choose the place where they want to install things.

**Comment by christhomas** [comment]
Good, thank you for your apology, although why somebody has to tell what appears to be a senior programmer about such a glaring mistake in their reasoning is beyond me.

So instead of just building this is as a default feature because, well, I dunno, maybe people (read: A LOT OF PEOPLE) would find it oh-so-useful to install code where WE want and not where you've demanded we all do it, you've decided to make a installer that you can install custom installers in!

The mind boggles at how you believe this is a decent solution and BTW, just because it's open source doesn't release you from the criticism people can lay at your feet for botching your design process, it just means we can read the code and realise you botched it instead of being able to hide it in a binary code nobody else can read.

It seems so obvious to anybody that an installer might want to decide where to install things and let the user, or programmer decide.  Since this obvious fact seems to have evaded you, I'm sure you'll have plenty of people, and after a short reading around, it would seem that you do have plenty of people pointing that out and yet for some reason, it's still not fixed.

So obviously this obvious point does NOT elude you, you just don't want to do it because of your own stupid opinions.  Again, just because you wrote it in your free time doesn't mean you escape the criticism.

Welcome to the internet! :D

**Comment by Seldaek** [comment]
@christhomas TL;DR: you are a silly internet bully and this conversation is over. 

If "A LOT OF PEOPLE" wanted this, I believe one of them would have done it by now, since it is entirely possible, just not using the composer/installers package as we do not want to promote what we view as bad practices. You are free to disagree, but not in such an insulting way thank you.
