### ISSUE TITLE
Clean command

### ISSUE THREAD

**Issue by igorw** [composer/composer#197]
Would be nice to have a clean command that does `rm -rf vendor`. And maybe even rm composer.lock for now.

**Comment by lickybuay** [comment]
Check what i found, Composer Cleanup Plugin -> https://github.com/barryvdh/composer-cleanup-plugin , Remove tests & documentation from the vendor dir. Based on laravel-vendor-cleanup but implemented as a Composer Plugin instead of a Laravel command.

Note: This package is still experimental, usage in production is not recommended. In normal circumstances, you shouldn't care about disk space! Try deploying with SSH/Git instead.

Please, comment if it works.
