### ISSUE TITLE
update causes different hash on windows

### ISSUE THREAD

**Issue by nicktacular** [composer/composer#2115]
I'm not sure whether I should be expecting this or not, but it's a bit of a nuisance. Here's  my order of operations:
1. Run `composer update` on OS X.
2. Push my new lock file to `git`.
3. Pull on my windows machine.
4. Run `composer update`.
5. Everything updates.
6. Hash in `composer.lock` changes, just in 1 line...

If I follow these same steps but change # 3 to OS X or Linux, this doesn't happen, so I'm guessing this is a windows-related issue.

Should I be expecting this?

```
$composer --version
Composer version 3ffad59719bd94987813ea1872001619200c24a0
```

```
$ git diff
diff --git a/composer.lock b/composer.lock
index 02a3986..826a5e2 100755
--- a/composer.lock
+++ b/composer.lock
@@ -3,7 +3,7 @@
         "This file locks the dependencies of your project to a known state",
         "Read more about it at http://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file"
     ],
-    "hash": "64e7a9da90b718f4dbeaf94ee2d2ffd3",
+    "hash": "8e81387da33c819c6adb1b51c1c6162f",
     "packages": [
         {
             "name": "doctrine/annotations",
warning: LF will be replaced by CRLF in composer.lock.
The file will have its original line endings in your working directory.
```

Any ideas?

**Comment by ppetermann** [comment]
but even with input turned on, that means that the line breaks will only be changed on git commit, composer update is usually run before that, so it would still end up with a different hash on windows and linux systems (as long as windows team members are using windows settings). Wouldn't it be better to strip windows breaks before creating the hash?

**Comment by ekonoval** [comment]
Not 
git config --global core.autocrlf input 
nor 
git config --global core.autocrlf false 
didn't help. After doing composer update on windows,  1 line of hash in composer.lock changes

**Comment by NiallSmyth** [comment]
@ekonoval The git configuration changes will only make a difference if you checkout the file fresh from git. If you're working on a composer.json file that's already got CRLF line endings, the git setting alone won't change it now. What you need to do is make sure the composer.json file is saved with LF line endings before running `composer update` - that will ensure the hash saved in the .lock file is for the .json file without CRs, and will match when generated on a linux system.

I do agree with @ppetermann that it'd be more convenient for the hash not to be dependent on the type of linebreak, but it looks like @Seldaek disagrees. I definitely don't think turning the git windows auto line handling off is a good idea, since that feature was specifically created to avoid issues with line endings for cross-platform development teams.

**Comment by slbmeh** [comment]
@NiallSmyth after you update your line endings configuration it is recommended to do a `git rm --cached .` followed by a `git reset --hard`.

https://github.com/composer/composer/issues/2115#issuecomment-121974235

There is a ticket somewhere, maybe a PR, that discusses updates to the lock file to hash the data rather than the file.
