### ISSUE TITLE
Symfony Signal 5 Fatal Error

### ISSUE THREAD

**Issue by robertdown** [composer/composer#2146]
Composer version 1f2d331fd341897c9d54414a76b909beba9e3a59

I'm receiving this error when I try to run `composer install`, `composer update`, `composer diagnose`

```
Exception trace:
 () at phar:///usr/local/bin/composer/vendor/symfony/process/Symfony/Component/Process/Process.php:430
 Symfony\Component\Process\Process->wait() at phar:///usr/local/bin/composer/vendor/symfony/process/Symfony/Component/Process/Process.php:207
 Symfony\Component\Process\Process->run() at phar:///usr/local/bin/composer/src/Composer/Util/ProcessExecutor.php:61
 Composer\Util\ProcessExecutor->execute() at phar:///usr/local/bin/composer/src/Composer/Package/Loader/RootPackageLoader.php:192
 Composer\Package\Loader\RootPackageLoader->guessGitVersion() at phar:///usr/local/bin/composer/src/Composer/Package/Loader/RootPackageLoader.php:177
 Composer\Package\Loader\RootPackageLoader->guessVersion() at phar:///usr/local/bin/composer/src/Composer/Package/Loader/RootPackageLoader.php:57
 Composer\Package\Loader\RootPackageLoader->load() at phar:///usr/local/bin/composer/src/Composer/Factory.php:235
 Composer\Factory->createComposer() at phar:///usr/local/bin/composer/src/Composer/Factory.php:393
 Composer\Factory::create() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:175
 Composer\Console\Application->getComposer() at phar:///usr/local/bin/composer/src/Composer/Command/Command.php:50
 Composer\Command\Command->getComposer() at phar:///usr/local/bin/composer/src/Composer/Command/InstallCommand.php:59
 Composer\Command\InstallCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:244
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:882
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:212
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:117
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:119
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:83
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:43
 require() at /usr/local/bin/composer:15
```

**Comment by thinsoldier** [comment]
More info for anyone else still encountering bugs like this one.

Before running into this problem with composer and Symfony\Component\Process I encountered it while working on something else involving basic exec() usage.

exec("git log",$output); print_r($output);

This was returning nothing while other commands like

exec("ls",$output); print_r($output);

were working fine.

I added 2>&1 to the end of my commands which apparently allows php to receive both the stderror content when unsuccessful as well as stdout when successful.

exec('git log  2>&1', $output); print_r($output);

Now I could see the actual error message from git:

 dyld: lazy symbol binding failed: Symbol not found: _iconv_open
   Referenced from: /Library/Developer/CommandLineTools/usr/bin/git
   Expected in: /Applications/XAMPP/xamppfiles/lib/libiconv.2.dylib
 
 dyld: Symbol not found: _iconv_open
   Referenced from: /Library/Developer/CommandLineTools/usr/bin/git
   Expected in: /Applications/XAMPP/xamppfiles/lib/libiconv.2.dylib
 
At this point I realized the culprit was something related to some "configuration thing" within XAMPP.

So a command like git log works from terminal but not from php exec().

I exported the environments to text files for closer inspection.

printenv > ./env_php.txt - ran via php exec
printenv > ./env_terminal - ran from command line

Comparing those 2 files I saw that this environment variable:
DYLD_LIBRARY_PATH=/Applications/XAMPP/xamppfiles/lib:/Applications/XAMPP/xamppfiles/lib
was present in the environment php runs in.

It comes from:
/Applications/XAMPP/xamppfiles/bin/envvars
/Applications/XAMPP/xamppfiles/bin/envvars-std


I'd imagine some people using wamp, xampp or other *amp packages might have similar issues.

So now whether I'm using basic exec() or some library that eventually uses Symfony\Component\Process (like gitter) all I have to do is add 	unset DYLD_LIBRARY_PATH 
to the begging of my command/bash script  
or use <? putenv('DYLD_LIBRARY_PATH'); ?> anywhere early in my php code to avoid the problem.

**Comment by anojan28** [comment]
i'm having this issue on centos 6 with symfony 2.6.0   
symfony 2.5.12 works fine

any help

**Comment by acady** [comment]
I have this issue on OS X 10.10 with AMPPS, Apple-Git55. Any help is welcome!  
                                                         
  [Symfony\Component\Process\Exception\RuntimeException]  
  The process has been signaled with signal "5".          
                                                          
Exception trace:
 () at phar:///usr/local/bin/composer/vendor/symfony/process/Symfony/Component/Process/Process.php:367
 Symfony\Component\Process\Process->wait() at phar:///usr/local/bin/composer/vendor/symfony/process/Symfony/Component/Process/Process.php:210
 Symfony\Component\Process\Process->run() at phar:///usr/local/bin/composer/src/Composer/Util/ProcessExecutor.php:62
 Composer\Util\ProcessExecutor->execute() at phar:///usr/local/bin/composer/src/Composer/Package/Loader/RootPackageLoader.php:325
 Composer\Package\Loader\RootPackageLoader->guessSvnVersion() at phar:///usr/local/bin/composer/src/Composer/Package/Loader/RootPackageLoader.php:193
 Composer\Package\Loader\RootPackageLoader->guessVersion() at phar:///usr/local/bin/composer/src/Composer/Package/Loader/RootPackageLoader.php:59
 Composer\Package\Loader\RootPackageLoader->load() at phar:///usr/local/bin/composer/src/Composer/Factory.php:268
 Composer\Factory->createComposer() at phar:///usr/local/bin/composer/src/Composer/Factory.php:486
 Composer\Factory::create() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:222
 Composer\Console\Application->getComposer() at phar:///usr/local/bin/composer/src/Composer/Command/Command.php:53
 Composer\Command\Command->getComposer() at phar:///usr/local/bin/composer/src/Composer/Command/InstallCommand.php:82
 Composer\Command\InstallCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:146
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:82
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:43
 require() at /usr/local/bin/composer:25

**Comment by acady** [comment]
Sorry, I missed one small note:
"I had the same issue it was being caused by svn, version 1.7.10 (r1485443). I renamed svn in /usr/bin to /usr/bin/svn.orig and it resolved my issues." 
solved it.

**Comment by anojan28** [comment]
finally the issue is found. Thanks to Rackspace support staff Cristian Banciu and Mike Bostic

Cause:
Latest newrelic php agent 4.23.1.107 causes seg fault when used with symfony 2.6.0 or above with process component. newrelic.browser_monitoring.auto_instrument = 0 didn't help

Solution:
finally i downgraded newrelic php agent to 4.21.0.97-1 and all work fine

**Comment by trkoch** [comment]
Make sure your installation of Git is compatible with your system. To verify execute `git describe --exact-match --tags`.

**Comment by bgarrison25** [comment]
Hey guys, I have gone through this issue top to bottom and implemented all suggested fixes and am still getting this issue on Mac OSX 10.10 when installing a laravel app our company has made. I am the only developer using Max OSX and all others have no issue. Here is the output of composer install --vvv

` post-install-cmd: php artisan clear-compiled


  [Symfony\Component\Process\Exception\RuntimeException]
  The process has been signaled with signal "5".


Exception trace:
 () at phar:///usr/local/bin/composer/vendor/symfony/process/Process.php:375
 Symfony\Component\Process\Process->wait() at phar:///usr/local/bin/composer/vendor/symfony/process/Process.php:203
 Symfony\Component\Process\Process->run() at phar:///usr/local/bin/composer/src/Composer/Util/ProcessExecutor.php:62
 Composer\Util\ProcessExecutor->execute() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:204
 Composer\EventDispatcher\EventDispatcher->doDispatch() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:94
 Composer\EventDispatcher\EventDispatcher->dispatchScript() at phar:///usr/local/bin/composer/src/Composer/Installer.php:337
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/InstallCommand.php:134
 Composer\Command\InstallCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:844
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:189
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:99
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:43
 require() at /usr/local/bin/composer:24

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...

Trace/BPT trap: 5`

**Comment by masoudsourni** [comment]
hi , i have error when install composer with osx el capitano v10.11 , i have mamp v 4.1.1 in osx and php v7 .
[Symfony\Component\Process\Exception\RuntimeException]
  The process has been signaled with signal "5".
I attach the photo error
https://www.photobox.co.uk/my/photo/full?photo_id=9780357510

**Comment by emri99** [comment]
Got same error on OSX capitano too.

```
$ composer -vvv
Reading ./composer.json
Loading config file ./composer.json
Checked CA file /private/var/folders/89/7r_blf851pnb9w8rg22v6yt00000gn/T/composer-cacert-e62a07e61e5870effa81b430e1900778943c228bd7da1259dd6a955ee2262b47.pem: valid
Executing command (.../src/_tests/php-cs-fixer-config): git branch --no-color --no-abbrev -v
Executing command (.../src/_tests/php-cs-fixer-config): git describe --exact-match --tags
Executing command (.../src/_tests/php-cs-fixer-config): git log --pretty="%H" -n1 HEAD
Executing command (.../src/_tests/php-cs-fixer-config): hg branch
Executing command (.../src/_tests/php-cs-fixer-config): fossil branch list
Executing command (.../src/_tests/php-cs-fixer-config): fossil tag list
Executing command (.../src/_tests/php-cs-fixer-config): svn info --xml

                                                          
  [Symfony\Component\Process\Exception\RuntimeException]  
  The process has been signaled with signal "5".          
```                                                    

```
$ svn
dyld: Library not loaded: /usr/lib/libcrypto.35.dylib
  Referenced from: /Library/Developer/CommandLineTools/usr/lib/libserf-1.0.dylib
  Reason: image not found
[1]    5221 trace trap  svn
```
So it's `svn` the problem.
But as  I don't need svn,  moving binary executable resolve this case.
```
mv /usr/bin/svn /usr/bin/svn-bak
```

**Comment by FreeFromItAll** [comment]
@emri99 i confirm this is exactly what the problem was for me too. svn was not installed properly. Getting rid of the binary does allow composer to continue installation of dependency.

**Comment by deondazy** [comment]
This worked for me:
$brew install svn
$brew link --overwrite subversion

**Comment by softnayr** [comment]
works on me.

@deondazy thanks man

**Comment by PhilippeDunbar** [comment]
I had this problem too, spent about 3 hours trying to track it down. @deondazy solution fixed it for me as well. Thanks @emri99 for pointing out the SVN error. 

Three potential solutions for this. 
1. Add SVN to dependencies for homebrew installs. (easy, and would probably solve for most people)
2. A more verbose error for SVN errors.
3. git fallback (or use SVN as the fallback since git is more popular) 

I'm not familiar with composer's codebase, but I'm willing to take a look.

**Comment by RingRan** [comment]
thanks to @PhilippeDunbar
I fix the problem in mac.
brew install svn.

**Comment by lukasfischer** [comment]
brew reinstall subversion

**Comment by azizultex** [comment]
```
$brew upgrade subversion
$brew link --overwrite subversion
```

Fixed my problem
