### ISSUE TITLE
Document behaviour of forked (renamed) packages

### ISSUE THREAD

**Issue by igorw** [composer/composer#2249]
The VCS repo reads the package name only from the master branch. This allows effectively actively forking a package and renaming it while keeping the old tags and branches intact. Applies to packagist too.

This behaviour should be documented.

**Comment by kdambekalns** [comment]
Yes, please. It took me over an hour to realize my branch was not picked up because the package I required was renamed. And in my fork, the master branch was outdated, not having the new name. Only the new branch had the new name, but that was not seen.

Repo:
- `master` - `neos/content-repository-search`

Fork:
- `master` - `neos/content-repository-search`
- `bugfix/target-workspace-handling` - `typo3/typo3cr-search`

Required:

    "neos/content-repository-search": "dev-bugfix/target-workspace-handling as 3.0.9"

Result:

    composer update -vv
    …
    Reading composer.json of typo3/typo3cr-search (bugfix/target-workspace-handling)
    Importing branch bugfix/target-workspace-handling (dev-bugfix/target-workspace-handling)
    …
    Updating dependencies (including require-dev)
    Dependency resolution completed in 4.625 seconds
    Your requirements could not be resolved to an installable set of packages.
    
      Problem 1
        - The requested package neos/content-repository-search dev-bugfix/target-workspace-handling as 3.0.9 exists as neos/content-repository-search[1.0, 1.0.1, 1.0.x-dev, 1.1.0, 1.1.x-dev, 1.2.0, 1.2.1, 1.2.x-dev, 2.0.0, 2.0.x-dev, 2.1.0, 2.1.1, 2.1.2, 3.0.0, 3.0.x-dev, dev-dimaip-fix-discard, dev-master] but these are rejected by your constraint.

So, this showed me the branch was there, so why was it not listed in the "exists as"? Only when I rubber-ducked the issue to a colleague it dawned upon me. Could it be I needed the old name? Yes, indeed. But why? Again, just a thought… the master branch?

I think I only understood, because I know of the behaviour regarding dependencies beind read from a branch tip, even if requiring a specific commit hash.

So, yes, please document. **I'll happily do it, but please advise on where to put it.** :)

**Comment by oleg-andreyev** [comment]
@kdambekalns in case of fork you need to specify custom repository https://getcomposer.org/doc/05-repositories.md#using-private-repositories, composer does not know anything about your fork

**Comment by kdambekalns** [comment]
@oleg-andreyev I know. That was not the issue.

**Comment by Seldaek** [comment]
The issue is we have to pick the name from the default branch, otherwise if we read the name from every branch/tag we can not support renaming packages without renaming in composer.json in every branch/tag which would be a hassle. If you find a good place to explain this in the docs feel free to PR :)
