### ISSUE TITLE
Allow to add "Soft Links" in local repositories

### ISSUE THREAD

**Issue by mmoreram** [composer/composer#2290]
given:

    {
        "type":"vcs",
        "url":"/var/www/projects/MyBundle"
    },

could be nice add an option, like this

    {
        "type": "vcs",
        "url": "/var/www/projects/MyBundle",
        "softlink": true
    },

and just creates a soft link between local repository and vendors copy. Just for development environment.

**Comment by cosmincatalin** [comment]
+1

**Comment by slbmeh** [comment]
There is one limitation with doing this as a plugin.  Repositories cannot be added in `config.json` because they're added to the repository manager before plugins are activated.  It would also have to be a global plugin to make sure that it's loaded before the root package.  There will be some weird errors when running commands with `--no-plugins` and if there are any commands that interact with the repositories in the root package without initializing plugins.

**Comment by Seldaek** [comment]
This is covered by https://getcomposer.org/doc/05-repositories.md#path I believe.
