### ISSUE TITLE
Composer hangs on Updating Dependencies

### ISSUE THREAD

**Issue by sandersjj** [composer/composer#2392]
Hello Everyone,

Since today my composer seems to hang on:

Updating Dependencies (including-require-devv)

This is my Json file

"require":{
        "php": ">=5.3.3",
        "zendframework/zendframework": "2.2.5",
        "zendframework/Zend-developer-tools": "0.0.2",
        "zendframework/zftool": "dev-master",
        "zendframework/ZendPdf": "2.0.2",
        "doctrine/doctrine-module": "0.7.2",
        "doctrine/doctrine-orm-module": "0.7.0",
        "doctrine/data-fixtures": "1.0.0",
        "zf-commons/zfc-user": "0.1.2" ,
        "zf-commons/zfc-user-doctrine-orm": "0.1.1",
        "zf-commons/zfc-admin" : "0.1.1",
        "phpunit/phpunit": "3.7.*"
    }

I updated Composer this morning. How could I narrow down to the problem?

**Comment by MahdiZareie** [comment]
Same as me !
I have tried runing compsoer update with -vvv and this was the end result before hanging :-1: 
Importing tag v0.10.5 (0.10.5.0)
Reading /home/mahdi/.composer/cache/repo/https---packagist.org/provider-fzaninotto$faker.json from cache
Reading /home/mahdi/.composer/cache/repo/https---packagist.org/provider-yiisoft$yii2-faker.json from cache
 - Installing mahdiz/easy-two-factor (dev-master 548bfa7)
   Cloning 548bfa7c0dfcddac7ece59fa95e36c479b19d03c
Executing command (CWD): 
git clone —no-checkout 'https://bitbucket.org/MahdiZ/easytwofactor.git' '/projects/cerberus/CerberusI/vendor/mahdiz/easy-two-factor' 
&& 
cd '/projects/cerberus/CerberusI/vendor/mahdiz/easy-two-factor' 
&& 
git remote add composer 'https://bitbucket.org/MahdiZ/easytwofactor.git' 
&& 
git fetch composer
Executing command (CWD): 
git clone —no-checkout 'https://MahdiZ:****@bitbucket.org/MahdiZ/easytwofactor.git' '/projects/cerberus/CerberusI/vendor/mahdiz/easy-two-factor' 
&&
cd '/projects/cerberus/CerberusI/vendor/mahdiz/easy-two-factor' 
&& 
git remote add composer 'https://MahdiZ:****@bitbucket.org/MahdiZ/easytwofactor.git' 
&& 
git fetch composer

**Comment by iv-enovation** [comment]
Not sure why this is closed as composer still hangs on updating dependencies, the issue is not resolved
-vvv does not give much info either as it hangs after reporting writing to a cache, and it's not clear if this step fails or it tries to start a next download and fails

here are my last lines of -vvv output:
...
Reading /home/vagrant/.composer/cache/repo/https---packagist.org/provider-symfony$security-bundle.json from cache
Reading /home/vagrant/.composer/cache/repo/https---packagist.org/provider-symfony$serializer.json from cache
Reading /home/vagrant/.composer/cache/repo/https---packagist.org/provider-symfony$twig-bridge.json from cache
Reading /home/vagrant/.composer/cache/repo/https---packagist.org/provider-symfony$twig-bundle.json from cache
Reading /home/vagrant/.composer/cache/repo/https---packagist.org/provider-symfony$validator.json from cache
Reading /home/vagrant/.composer/cache/repo/https---packagist.org/provider-symfony$web-profiler-bundle.json from cache
Downloading http://packagist.org/p/symfony/debug-bundle%241452d21efd87ba393be49c3ff73e5bfed441cd3631555b6bf7a47d852d0f8a41.json
Writing /home/vagrant/.composer/cache/repo/https---packagist.org/provider-symfony$debug-bundle.json into cache
Downloading http://packagist.org/p/symfony/var-dumper%240b6364666d982d6f2af7569219da8827f618ec12fda2bb720a94bb7d36ed6e0f.json
Writing /home/vagrant/.composer/cache/repo/https---packagist.org/provider-symfony$var-dumper.json into cache
Downloading http://packagist.org/p/phpdocumentor/reflection%2423d940c5c3192a7f1ad16837e07896315b030370aac47627596224af8d19f8e9.json
Writing /home/vagrant/.composer/cache/repo/https---packagist.org/provider-phpdocumentor$reflection.json into cache
Downloading http://packagist.org/p/symfony/ldap%24df45842cb1d6f06ad6c1e2f03178763adc8224e14bc656ea2f7452f84e61f384.json
Writing /home/vagrant/.composer/cache/repo/https---packagist.org/provider-symfony$ldap.json into cache
Downloading http://packagist.org/p/symfony/property-info%245e74e4fd96f024a69d1e7202c39cffde2a09391d8506f459fec18c815d180b99.json
Writing /home/vagrant/.composer/cache/repo/https---packagist.org/provider-symfony$property-info.json into cache
Downloading http://packagist.org/p/symfony/security-guard%244cb1d35603e5ab4d53197c6612dcaf40cc708f8d5d942e7114049d0d22ef2250.json
Writing /home/vagrant/.composer/cache/repo/https---packagist.org/provider-symfony$security-guard.json into cache
Downloading http://packagist.org/p/phpdocumentor/reflection-docblock%24ca7598c7ad9fe3ea894215a28c4df6b2e6e8360e8c09c262f72711dad929535c.json
Writing /home/vagrant/.composer/cache/repo/https---packagist.org/provider-phpdocumentor$reflection-docblock.json into cache
Downloading http://packagist.org/p/phpdocumentor/type-resolver%24a68c82909dfa7cef4f3216951b1ba071e3cc9ae0794a4fb979c55681e9ff0c60.json
Writing /home/vagrant/.composer/cache/repo/https---packagist.org/provider-phpdocumentor$type-resolver.json into cache

Loads on a host peak and an OS becomes slow with latencies of responses, php occupies the highest line of `top` with 82% of memory usage, i believe it deadloops with polling some external resources

**Comment by ofembe** [comment]
It did not hang. Wait for a few minutes longer.

**Comment by vibrantBits** [comment]
True. My is experience is that Composer sometimes gets VERY slow in local Windows enviroment. In Mac and Linux behaves good most of time.
