### ISSUE TITLE
Dependency Hell in Composer

### ISSUE THREAD

**Issue by CMCDragonkai** [composer/composer#2609]
Is there any work to automatically resolve dependency hell in Composer/PHP?

Currently there's a problem in which if package A and package B strictly depend on different versions of package C, this results in a dependency conflict. The solutions I've read on stack overflow indicate it requires the user of both package A and package B to modify their composer.json in order to overwrite package C with the latest version, assuming that both packages are compatible with the latest package C.

However this I think is a bit of messy way to do it, and it relies on that assumption of compatibility which isn't always true.

NPM solves this http://blog.timoxley.com/post/20772365842/node-js-npm-reducing-dependency-overheads by having each module install their own dependent modules.

In Composer that would be a hierarchical vendor folder.

However the problem with PHP is namespaces... http://everzet.com/post/29622748103/behat-extensions-and-dependencies-conflicts

So any ideas for how we make PHP work without dependency hell? There must a solution.

**Comment by ElijahLynn** [comment]
http://www.joelonsoftware.com/articles/LeakyAbstractions.html

**Comment by XedinUnknown** [comment]
Of course, this cannot really be resolved by conventional means because this is a PHP limitation and has nothing to do with Composer. Even if composer provides a way to have different versions of dependencies installed, only one version of anything would be loaded (using class autoloading), or would cause a conflict when reading the same FQCN from a different version.

I was wondering, however, if something like [`humbug/php-scoper`][], [`bamarni/composer-bin-plugin`][], or a similar tool could solve the problem. This would work by isolating the FQNs used in a module to that module only.

Of course it has several implications:

1. If you do this by running a module in a separate process, you cannot use the same resources, like classes etc.
2. If you do this by somehow managing which versions are used from a particular directory (or something like that), you would really slow down your system, because the resources would no longer be shared. This would require a separate, possibly opcache, caching layer to exist on top.

My problem is that I have a module system, which can load any module class implementing `ModuleInterface`. I also have a package that provides an abstract module implementation, so that modules can be created quickly. If two modules use two incompatible versions of the abstract module package, this would cause a conflict, **even though they can both be consumed in the same way**.

I think that this is a serious problem, and needs to be addressed by the PHP community at large. Although right now it seems almost impossible, many technologies have emerged in the last decade that made the impossible possible. @rlerdorf, pretty pretty pwease!

[`humbug/php-scoper`]: https://github.com/humbug/php-scoper
[`bamarni/composer-bin-plugin`]: https://github.com/bamarni/composer-bin-plugin

**Comment by XedinUnknown** [comment]
> but that does not work as soon as a module uses another module and you scoped it, as you know need to rewrite the consuming code now

Didn't understand. If I, for example, have `$result = $a->run(...)`, and then do `$b->run($result), why would having them scoped cause a problem, and why would that need a re-write of anything?

> If you need to be able to consume multiple modules in the same process and you still need to be both instances of the ModuleInterface to pass typehint checks, you have no choice than being able to use the same ModuleInterface for both modules.

It's no problem, as the interface is very stable. But the implementation is very prone to change. It's the implementation of the abstract module functionality that I'm talking about.

> This is why the Symfony community decided to make it possible to support both the latest minor version of X and the X+1 version easily (all features present in X+1 are also in the last minor version of X, so any package support X+1 can also support X.4 in the constraint)

I understand if e.g. framework `2.0` supports stuff of framework `1.7`. This is BC, and how much BC to maintain is a decision made by everyone differently. Of course, this is a decision that _can_ be made. What I'm talking about is forward-compatibility, and resolution of dependency constraints by Composer. So, if `A` depends on `Z:^0.1` and `B` depends on `Z:^0.2`, and `C` depends on `Z:^0.3` (because with 2 deps you can use inline aliasing), how do you make your application `X` install all `A`, `B`, and `C` (FQN collision aside)? `A`, `B`, and `C` can all be consumed by `X`, as they all implement the same version of the same interface.

**Comment by stof** [comment]
@XedinUnknown look at how the rewritten code could look like:

```php
class A {
    function run(): \RewrittenForA\C {}
}

class B {
    function run(\RewrittenForB\C $c): \RewrittenForB\D {}
}

$result = $a->run(...);

$b->run($result);
// TypeError. Argument of type \RewrittenForB\C expected but \RewrittenForA\C given
```

**Comment by stof** [comment]
and if you rewrite the code of the C package being installed (to be able to install another version of C for another package), you **must** rewrite the code of the consumer package (A in this case). Otherwise, it would not consume your rewritten package.
