### ISSUE TITLE
failed to open stream: HTTP request failed!

### ISSUE THREAD

**Issue by rahulpramodpande** [composer/composer#2624]
When execute composer update or composer install it says
"$ composer update
Loading composer repositories with package information

  [Composer\Downloader\TransportException]
  The "http://packagist.org/p/smalot/pdfparser$63e0f41161a730860c6cabd5a872b397f21d67e391d7e1d3fc3e227f5cb809d7.json" file could not be downloaded: failed to open stream: HTTP request failed!

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o
|--optimize-autoloader] [packages1] ... [packagesN] "

For FYI 

$ composer diag
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity: OK
Checking composer.json: OK
Checking disk free space: OK
Checking composer version: OK.

Getting irritate. Please help me out.

**Comment by ernestob** [comment]
:boom:  Downloading the file manually as @nonlux previous comment worked here

**Comment by shreyas135** [comment]
I am creating "Custom Auth Class & Interface" in Laravel 4.2 with the help of "http://goo.gl/8QNaHB" link. But I am having an error like 

"Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_ERROR)
Class 'App\Providers\CustomAuthProvider' not found "

After that I have update my composer too because it was showing fail error like:
"Checking platform settings: OK
Checking git settings: OK
Checking http connectivity: OK
Checking disk free space: OK
Checking composer version: FAIL
You are not running the latest version"

Then I have fire command like:
"composer self-update"
And got the result like:

F:\F***5_F***d>composer selfupdate --profile
[2.8MB/2.00s] You are already using composer version 8c81ec0d0e9f864f0ec77831fc7
12ee7bcdd119b.
[2.8MB/2.00s] Memory usage: 2.79MB (peak: 2.84MB), time: 2s

Still facing the same error "class not found"

Can anybody help me how can I fix it?

**Comment by marcsoler** [comment]
I have the same problem on composer install
composer diagnose shows all OK

Running under Windows 10

**Comment by marcsoler** [comment]
So I came up with two solutions;
One would be changing the repo config:
```json
"repositories": [
	{
		"type": "composer",
		"url": "https://packagist.org"
	},
	{
		"packagist": false
	}
]
```
And the other (since I was running xampp) is generating a new ca certificate with \xampp\apache\makecert.bat

**Comment by Seldaek** [comment]
Closing as this has way too many comments about many different issues. If anything is still relevant please open a new one.
