### ISSUE TITLE
Nested dependencies not pulled from custom repository

### ISSUE THREAD

**Issue by DennisBirkholz** [composer/composer#2632]
I have three projects A, B and C where A depends on B and B on C.
All packages are available as git-repos provided via a satis-managed repository.
If I checkout B and let composer update, C is pulled from that repo.
If I checkout A and let composer update, B is pulled from the repo but composer then fails because it can not resolve B's dependency to C but both are in the same repository!
If I make C a dependency of A also, everything works.
If B has a dependency that is available on packagist (e.g. doctrine), it is pulled when updating A, only dependencies from custom repositories seem to be the problem.

**Comment by matrixbegins** [comment]
I Understand This issue is closed, the only reason I am bugging here is I have same use case But my root project has the definition of my private repo and root project has `"minimum-stability": "alpha"`.
The Package A&B are on same repo and B is dependent on A. 
Full Question I have asked here:
http://stackoverflow.com/questions/39297507/composer-not-resolving-dependency-for-private-repositories
It'll be very helpful if someone can take a look and guide me where I am going wrong.
