### ISSUE TITLE
FR Generate a lock file without downloading the packages

### ISSUE THREAD

**Issue by judgej** [composer/composer#2656]
Using `--dry-run` on an update is great to see some of the details of what would be installed. To make that more formal, so the dry-run results can be used or analysed in an automated way, generating a composer.lock file (maybe composer.dry-run.lock or something to prevent overwriting the live version) would be great.

I would like to be able to generate `composer.lock` files on a decently big server that has the memory to cope with it, then use the lock file on smaller dev servers with less memory to do a `composer install`.

Doing a dry-run would do everything except downloading the packages. Downloading when not needed just adds to network traffic, server load and creates download stats on packagist that are just not realistic. I am finding personally that I am needing to run `composer update` often on another server, just to subsequently delete the downloaded files anyway.

This is all related to the memory issue, where the amount of memory needed to work out the dependencies is increasing exponentially over time, and the abilities for servers to run `composer update` is becoming an issue as they drop like flies with memory errors. (Edit: and by "server", I mean "the machine I am developing on").

**Comment by browner12** [comment]
not sure if this is still being discussed since it is such an old issue, but I would like to add another use case. i have many clients that I build websites for.  if a bug fix comes out in a package I use across all of those sites it becomes a huge pain to deploy that bug fix to all of the sites.  currently it means i need to clone all of the repos down to my machine, and then run a `composer update` on all of them. having the ability to simply generate the new lock file from the `composer.json` file would be a tremendous help into automating this process.

**Comment by drAlberT** [comment]
:+1:

**Comment by curry684** [comment]
If implemented the logic could likely be merged with/from #4517 as both imply a dry run with only the solver and no installs.

**Comment by curry684** [comment]
As https://github.com/composer/composer/pull/4946 was denied this FR is automatically void I suppose.

**Comment by browner12** [comment]
i'll admit, i didn't fully understand his use case, but i feel like the one i put forth is quite different.  not sure if that changes the outcome, but i still feel like this should be discussed.

**Comment by Seldaek** [comment]
@browner12 tbh I think it could possibly be achieved as a plugin that just nullifies all installs/updates/.. Since it's kinda special use I'd rather keep it out of core.
