### ISSUE TITLE
Add flag to force .bat file creation in bin

### ISSUE THREAD

**Issue by ciarand** [composer/composer#2771]
When working with a shared folder in a VM I'd like to be able to run Composer on the host machine (Mac, Linux) while still building the .bat files for the VM (Windows).

**Comment by kocsismate** [comment]
Hi there,

I also ran into this pretty disturbing issue recently when I "composer install"-ed directly from my Vagrant box which sits on a Virtualbox Windows host, and I wanted to run a binary, but the guest couldn't find the aformentioned symlink because of bugs in Virtualbox synced folders...

So having read the conversation, I like @Seldaek's proposal very much, but my question is: it it really good to make ``bin-compat`` a configuration option in the composer.json file? Isn't it better to only make it configurable by an environment variable? I think the types of binaries used only depend on the running environment and it shouldn't be part of the project-wide configuration. What do you think? Or am I missing the point?

And also here is my very initial take: https://github.com/kocsismate/composer/commit/6a776c5edf747ce833246f321beb6ba6873e8d96

**Comment by dersonsena** [comment]
Awesome @Seldaek ! Thanks for it. Just a TL;DR:

Just add that one in your `composer.json` file in `config` section:

```json
"config": {
        "bin-compat": "full"
}
```
