### ISSUE TITLE
Treat warnings as errors (give an exit code)

### ISSUE THREAD

**Issue by VasekPurchart** [composer/composer#2783]
Hey, i found out that it is really inconvenient when you want to incorporate composer into a build script, that there is no way (AFAIK) to return an **non-zero exit code** when a warning occurs.

The most obvious example would be running `composer install` in a project using versioned lock file. If the warning: `Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.` occurs, it always means that the build process should stop, because other (weirder) errors may occur down the road.

Since the program is running even after an error occurs (and some other use-cases don't care about warnings) **I think the best solution of this issue could be adding an CLI parameter to treat all warnings as errors (or convert them to errors).**

Or am I missing something and there is already a solution to this problem?

**Comment by Seldaek** [comment]
`composer validate` now returns non-zero (fail) if the lock file is not up to date, so you can use that in your deployment to check if all is good.

**Comment by VasekPurchart** [comment]
@Seldaek thanks for the heads up, this is indeed very useful. But I still think this issue is not resolved, because the example with outdated composer.lock was only the most obvious and painful one (as I stated in the opening post). That does not mean that the other warnings are non-issues. In the code there [plenty of other warnings](https://github.com/composer/composer/search?p=1&q=%3Cwarning%3E&type=Code&utf8=%E2%9C%93). 

From the top of my head the next most common warning I tend to see is about old Composer.phar (oddly enough it does not pop up in the search I mentioned - only the test for it). This (and probably most if not all) other warnings can cause nasty issues.

So I still think a system solution to this is needed. I wanted to look into this myself, but since it was put in the `Later` "Non-essential things or stuff that may not make sense at all." milestone I didn't work on this. If there is will I can try to do some research and come up with a proposed way to solve this and if it's ok with you, then a PR. Can you please reopen the issue (since it wasn't about one particular warning)?

**Comment by Seldaek** [comment]
@VasekPurchart well I don't really agree that we should return non-zero on any warning being output, most warnings are purely informational and do not really constitute an error. Potential problem sure, but failing all automated builds that watch exit codes for warnings seems a bit too drastic to me. 

I'll reopen for now, but I'd like to hear of a potential good solution before anyone spends time implementing it otherwise it'll be a waste of time.

**Comment by VasekPurchart** [comment]
> well I don't really agree that we should return non-zero on any warning being output

That's why I mentioned that adding a CLI parameter would be an option - if you want to use it, use it, but it does not bug you if you don't (also it would not cause a BC break).

> I'll reopen for now, but I'd like to hear of a potential good solution before anyone spends time implementing it otherwise it'll be a waste of time.

Thanks, that's exactly what I mean, I'll do some research on possible implementation approaches.

**Comment by Seldaek** [comment]
Closing as I don't think it's likely to happen..

**Comment by c33s** [comment]
@Seldaek would really be nice to have more control about the exit code.

instead of stopping with an exit code 1 my testing suite continued to run after a 
```
OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054
Failed to download recipe: curl error 0 while downloading 
```
which was tiggered by flex. because of the yellow color i assume that the ssl error was handled as warning. i would really appreciate to be able to call composer with `--strict` or `--handle-warning-as-error` or something like that. is there a specific reason for not giving more control about the exit codes?

**Comment by Seldaek** [comment]
@c33s please open a new issue instead of digging up 7yo one.. and provide all details as per issue template.

And explain your use case

And maybe report this on the flex repo instead because if it's flex not failing hard when it should we can't do anything about it.
