### ISSUE TITLE
Install fails because of getcomposer.org certificate verify failed

### ISSUE THREAD

**Issue by ChristianRiesen** [composer/composer#2798]
@Seldaek @naderman we just saw this in a capifony deploy:

Download failed: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
file_get_contents(): Failed to enable crypto
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: operation failed

**Comment by daragilroy** [comment]
FOR ANYONE LOOKING FOR THE FINAL SOLUTION TO THIS PROBLEM:
@ChristianRiesen noted on March 26 2014 that this works ( run it from the terminal ):
echo "<?php echo file_get_contents('https://getcomposer.org/composer.phar') ?>" | php > composer.phar

I too was having the SSL Certification error when running PHP 5.3 but Christian's solution worked for me ( after having spent a long time reading through this thread, I thought a final solution should be highlighted near the bottom ! :-) )

Another issue I had is that Composer will only support versions of PHP from 5.3 onwards. Therefore on my Mac ( OSX Snow Leopard ) I had to install MAMP running PHP 5.3 and specify which version of PHP I wanted to run in the terminal command above..Therefore my command was:

echo "<?php echo file_get_contents('https://getcomposer.org/composer.phar') ?>" | /Applications/MAMP/bin/php5.3/bin/php > composer.phar

**Comment by daragilroy** [comment]
FOR ANYONE LOOKING FOR THE FINAL SOLUTION TO THIS PROBLEM:
@ChristianRiesen noted on March 26 2014 that this works ( run it from the terminal ):
echo "<?php echo file_get_contents('https://getcomposer.org/composer.phar') ?>" | php > composer.phar

I too was having the SSL Certification error when running PHP 5.3 but Christian's solution worked for me ( after having spent a long time reading through this thread, I thought a final solution should be highlighted near the bottom ! :-) )

Another issue I had is that Composer will only support versions of PHP from 5.3 onwards. Therefore on my Mac ( OSX Snow Leopard ) I had to install MAMP running PHP 5.3 and specify which version of PHP I wanted to run in the terminal command above..Therefore my command was:

echo "<?php echo file_get_contents('https://getcomposer.org/composer.phar') ?>" | /Applications/MAMP/bin/php5.3/bin/php > composer.phar

**Comment by daragilroy** [comment]
FOR ANYONE LOOKING FOR THE FINAL SOLUTION TO THIS PROBLEM:
@ChristianRiesen noted on March 26 2014 that this works ( run it from the terminal ):
echo "<?php echo file_get_contents('https://getcomposer.org/composer.phar') ?>" | php > composer.phar

I too was having the SSL Certification error when running PHP 5.3 but Christian's solution worked for me ( after having spent a long time reading through this thread, I thought a final solution should be highlighted near the bottom ! :-) )

Another issue I had is that Composer will only support versions of PHP from 5.3 onwards. Therefore on my Mac ( OSX Snow Leopard ) I had to install MAMP running PHP 5.3 and specify which version of PHP I wanted to run in the terminal command above..Therefore my command was:

echo "<?php echo file_get_contents('https://getcomposer.org/composer.phar') ?>" | /Applications/MAMP/bin/php5.3/bin/php > composer.phar

**Comment by ranvirp** [comment]
I think it can be fixed by the configuration 
<code>
openssl.cafile=<location of cacert.pem>
</code>
http://stackoverflow.com/a/27254240

**Comment by padraic** [comment]
@daragilroy That is not a solution. Not in any way, shape or form. Just not. The point of SSL is to ensure you can download code from a verified server without any risk of someone delivering you bad code through a Man-In-The-Middle attack. Your solution is to simply undo that protection. Ergo, it is effectively one hideous gigantic security vulnerability. It is this attitude that needs to be pitilessly hinted down in PHP and stamped on...hard.

**Comment by daragilroy** [comment]
Hi Padraic,
I received your reply and saw your post on the thread.
Firstly let me say that I am a relatively inexperienced developer and wasn't aware of the consequences of using the solution I did..i.e that it creates a vulnerability. Basically I was having serious problems getting Composer installed and this one suggestion from Christian Riesen worked for me ( to get past this obstacle ) and my intention in making this post was to help others encountering the same problem.
I found your post in response to be un-necessarily aggressive..talk of 'stamping on this attitude..hard', 'not a solution. Not in any way, shape or form. Just not.' etc
From looking at the thread now, it seems that you are involved with the Composer development team and I understand that you want best practice to be followed..
Can I suggest 2 options:
1) If you think it'd be better if my solution wasnt there at all..i.e that it could potentially do more harm than good, I can remove my post and I'd ask that you please remove your response also
2) If you think that my post might still benefit newbies in some way..i.e people who don't know how to configure their server for safe HTTPS connections ( as I frankly don't ), then I can edit the post to mention that this is a security risk and you could perhaps subsequently edit your post to underscore this but in a more gentle way..
Finally since you are part of the development team and since many people seem to be encountering this SSL Certificate issue, might it be possible to devise a way for those with less technical knowledge to download Composer ? I want Composer as I want to install Laravel..I am a PHP developer but my knowledge is more on coding PHP itself and building / designing webpages than on other areas of expertise such as configuring servers etc..
Regards,
Dara

**Comment by daragilroy** [comment]
@padraic
I received your reply and saw your post on the thread.
Firstly let me say that I am a relatively inexperienced developer and wasn't aware of the consequences of using the solution I did..i.e that it creates a vulnerability. Basically I was having serious problems getting Composer installed and this one suggestion from @ChristianRiesen worked for me ( to get past this obstacle ) and my intention in making this post was to help others encountering the same problem.
I found your post in response to be un-necessarily aggressive..talk of 'stamping on this attitude..hard', 'not a solution. Not in any way, shape or form. Just not.' etc
From looking at the thread now, it seems that you are involved with the Composer development team and I understand that you want best practice to be followed..
Can I suggest 2 options:
1) If you think it'd be better if my solution wasnt there at all..i.e that it could potentially do more harm than good, I can remove my post and I'd ask that you please remove your response also
2) If you think that my post might still benefit newbies in some way..i.e people who don't know how to configure their server for safe HTTPS connections ( as I frankly don't ), then I can edit the post to mention that this is a security risk and you could perhaps subsequently edit your post to underscore this but in a more gentle way..
Finally since you are part of the development team and since many people seem to be encountering this SSL Certificate issue, might it be possible to devise a way for those with less technical knowledge to download Composer ? I want Composer as I want to install Laravel..I am a PHP developer but my knowledge is more on coding PHP itself and building / designing webpages than on other areas of expertise such as configuring servers etc..

**Comment by padraic** [comment]
@daragilroy What I posted is simple truth. This is not a solution. It is considered a security issue if used. The attitude of justifying ignoring security, or ignoring one's ignorance of security, does indeed need to be stamped out across PHP. I do not edit comments to remove obvious, if briefly written, truths. Brevity unfortunately robs any message of any context - which is why I overuse smilies everywhere normally :P. They are two characters long and let people know when my sarcastic wit (as I like to think of it) is definitely not intended to harm.

You need to realise that in the search for solutions, you have elevated the convenience of a quick workaround over the necessity of practicing good security, and then published it online for others to do the same. In this you have erred and, from this, you can learn. I've had to learn too!

My suggestion, even given your professed inexperience, is simply to invest some time in understanding why Composer enforces SSL, why SSL is so critical to secure downloads, and why Composer cannot ever make this easier. SSL is dictated by internet standards so there is literally no way for Composer to change it. Even the configuration of SSL (though it's actually now TLS only) is dictated by best practices.

The problem you were having was due solely to a misconfigured server which is not within Composer's control to fix. Once you know how to fix that yourself once, you can do it over and over for the next umpteen years and never have a failed Composer download in all that time. You'll also never have downloads at risk of Man-In-The-Middle attacks which is a nice bonus ;).

As to attitude stamping, consider it from the perspective of a security advocate. You found the solution from someone, reused it, and shared it here for others to find. We really do need to reach a point where sharing insecure information is discouraged. It misleads others, as it misled you.

Programmers cannot all be security experts - it's a huge field. They can however become proficient dabblers in the dark arts. It's well worth the time!

**Comment by ayonliu** [comment]
Edit php.ini

curl.cainfo=/full/path/to/ssl/certs/ca-bundle.crt
openssl.cafile=/full/path/to/ssl/certs/ca-bundle.crt

@brandonlamb  , Your answer works for me ,thanks.

**Comment by thecodingwizard** [comment]
@ayonliu After 3 hours of searching - and all I needed to do was add two lines of code. Thanks!

For any curious Windows users: 

I downloaded [ca-bundle.crt](https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt) and placed it somewhere on my hard drive. 

I double clicked it and installed it (though I really don't think I needed to do that.) 

I added the two lines @ayonliu posted to my php.ini (the two lines weren't there before). 

After that, it works!

**Comment by Petrox** [comment]
Hi. I'll just leave a note, as Google might drive other people here if they search for the error messages, that the pear.php.net problems are unrelated to this: They have some hardware issues and the pear.php.net is relocated, with some known ssl problems it seems.

https://bugs.php.net/bug.php?id=71048

**Comment by sergey-dev** [comment]
Came to this thread by searching the solution on the same issue, and apparently http://stackoverflow.com/a/34192495/4354249 helped in my specific situation with Mac OSX.
The issue was not in composer itself, but because of obsolete certificates in OpenSSL

**Comment by ccab** [comment]
I got a problem when I try to install composer, I'm using:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:  trusty
```
I'm using XAMPP for Linux with:
```
PHP 5.6.15 (cli) (built: Dec  4 2015 22:27:28) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies


openssl
SSL Version => OpenSSL/1.0.1q
Vendor Name => OpenLDAP
OpenSSL support => enabled
OpenSSL Library Version => OpenSSL 1.0.1q 3 Dec 2015
OpenSSL Header Version => OpenSSL 1.0.1q 3 Dec 2015
Openssl default config => /opt/lampp/share/openssl/openssl.cnf
OpenSSL support => enabled

```
I already set my `http_proxy` and `https_proxy` env vars 'cause I'm behind my company proxy and also downlad `ca-bundle.crt` from `http://curl.haxx.se` and added to `/opt/lampp/share/curl/curl-ca-bundle.crt` , so whe I run `curl -sS https://getcomposer.org/installer | php` I got:
```
All settings correct for using Composer

Notice: Undefined variable: caBundle in - on line 906

Call Stack:
    1.9639     220100   1. {main}() -:0
    1.9640     220292   2. process() -:13
    1.9654     221396   3. installComposer() -:111
    1.9659     222184   4. HttpClient::getSystemCaRootBundlePath() -:414

Downloading...
Download failed: file_get_contents(https://getcomposer.org/composer.phar.sig): failed to open stream: Cannot connect to HTTPS server through proxy
Download failed: file_get_contents(https://getcomposer.org/composer.phar.sig): failed to open stream: Cannot connect to HTTPS server through proxy
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: Cannot connect to HTTPS server through proxy
Downloading...
Download failed: file_get_contents(https://getcomposer.org/composer.phar.sig): failed to open stream: Cannot connect to HTTPS server through proxy
Download failed: file_get_contents(https://getcomposer.org/composer.phar.sig): failed to open stream: Cannot connect to HTTPS server through proxy
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: Cannot connect to HTTPS server through proxy
Downloading...
Download failed: file_get_contents(https://getcomposer.org/composer.phar.sig): failed to open stream: Cannot connect to HTTPS server through proxy
Download failed: file_get_contents(https://getcomposer.org/composer.phar.sig): failed to open stream: Cannot connect to HTTPS server through proxy
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: Cannot connect to HTTPS server through proxy
The download failed repeatedly, aborting.
```

Using any other tool like `wget` or `curl` to get any of this links works fine. Thanks in advance

**Comment by staabm** [comment]
Please try updating your composer. This should already be fixed.

**Comment by Seldaek** [comment]
@ccab I fixed that issue in the installer, please try again.

**Comment by ccab** [comment]
I know it, actually I was using it a while but in Debian, I'm able to install Symfony via the installer and I fetch this URLs with `curl`, so it could be a problem with the certificates check or it's location in the OS. Please any help from the Ubuntu friends

**Comment by cs278** [comment]
Try it without the proxy, perhaps you don't need it for HTTPS.

**Comment by b01** [comment]
OK I think this issues needs to be reopened, I'm getting this error again. Really need a fix.

So I can run:
```
php -r "echo file_get_contents('https://getcomposer.org/version');"

output:
cd21505c8d58499a9b4d38573881cfec49c51ffd
```

but when I run:
```
composer.phar self-update

output:
[Composer\Downloader\TransportException]                                                                                  
  The "https://getcomposer.org/version" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error mess  
  ages:                                                                                                                     
  error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed                                         
  Failed to enable crypto                                                                                                   
  failed to open stream: operation failed   
```

I've reinstalled openssl, curl, php using Homebrew on Mac OSX Yosemite. This usually happens when I update the OS, but this time I only updated Xcode. Please note that HTTPS calls with file_get_contents work just fine.

**Comment by Seldaek** [comment]
@b01 can you please open a new issue for this and report your full php version info as well as the complete output of `composer show -p -vvv | grep ssl`? I'll lock this issue because it's way too long and spamming 30 people every time someone finds it on google is kinda pointless.
