### ISSUE TITLE
Tag a Stable Release

### ISSUE THREAD

**Issue by jonmchan** [composer/composer#2803]
I am interested in having a copy of composer.phar in the package so I can call composer.phar commands from my bundle. I tried requiring composer/composer in my bundle, but the package would not install it because it is @dev, not a stable release. 

Is there any reason why there are only alpha builds available and there isn't a stable version released? I assume this is a fairly mature project and it would be useful for bundles that want to access composer.phar functionality from within the bundle without having to make the package require the  @dev or @alpha version.

**Comment by jonmchan** [comment]
@Seldaek any update on this? It's almost a year now - is there  some roadmap that you are trying to follow that keeps composer from going to release? It doesn't make sense that so many production projects are using alpha software for package management. Composer clearly isn't alpha (or at least used as an alpha software).

**Comment by Faryshta** [comment]
for the php community it almost doesn't matter if its alpha, beta or stable, we are already using it.

but for companies it matters more than anything else.

Google api's and sdk's that use php (like the google drive) don't have plans to use composer at all until its tagged as stable.

MercadoLibre api is on the same issue, they still use 'require' because there is no other 'official' way to do it.

And its very important to do it. Open source community know that free software means no warranty but the MercadoLibre api can suffer backslash if they start using an alpha software to handle the installation of their api.

Every few months its reopened again and again because its very important for developers that work in big companies, specially now with the advancement and popularity of ecommerce

**Comment by nishigori** [comment]
> for the php community it almost doesn't matter if its alpha, beta or stable, we are already using it.

I think too.

I really want to get the plan of continuous updatiing.
Composer was updating 1.0.0-alpha9, hope to release next version in a few months.
or I'll be have to update Composer so gingerly...
(of cource, we are always updating carefully.)

**Comment by rindeal** [comment]
IMHO the number of installs via packagist.org will hit 1 billion mark by the end of year. I hope composer will move at least to beta to celebrate it...

**Comment by schmunk42** [comment]
\+:100: 

Composer hit the 1.5 billion mark recently and I haven't seen BC breaking changes for a long time.

@Seldaek @naderman What is keeping you from releasing a stable version?

Related:
- https://github.com/composer/composer/issues/4724

**Comment by hkdobrev** [comment]
As this hasn't been posted here - https://github.com/composer/composer/milestones/Backwards%20Compatible

I think this is the list which the maintainers consider needed before 1.0 so they can ensure there won't be any immediate need for BC changes after the 1.0. Look at the amount of people using Composer now, imagine for how long people would be stuck with 1.0 if there's a BC change that needs updating to 2.0. For a good plugin ecosystem, the API should be stable and maintained in a backwards-compatible way.

**Comment by schmunk42** [comment]
Shouldn't that list be called "Backward incompatible" then? :smile:

**Comment by hkdobrev** [comment]
👏 https://github.com/composer/composer/releases/tag/1.0.0

**Comment by Seldaek** [comment]
Yup, closed.

**Comment by jonmchan** [comment]
2 years! 'bout time! ;-)
