### ISSUE TITLE
More explicit reporting for meta-packages which "provide" something.

### ISSUE THREAD

**Issue by dbu** [composer/composer#2811]
We use the require-provide mechanism to decouple interfaces from implementation with phpcr and php-odm. so the phpcr bundle requires "any phpcr implementation" https://github.com/doctrine/DoctrinePHPCRBundle/blob/master/composer.json#L23 and the implementation says https://github.com/jackalope/jackalope/blob/master/composer.json#L26

Since composer switched to no longer randomly download any of the providing packages (which makes a lot of sense to me, as you need to configure each of them), people get confused by composer complaining that it found no phpcr-implementation. Could we make this more explicit by telling the user that he needs to specify one of the providers? Possibly even listing all providers we can find on packagist?

i checked if this is already reported, but found only #1559 about the provide field

**Comment by shadiakiki1986** [comment]
Hello, about composer's `provide`, I tried requiring "any phpcr implementation" like @dbu mentioned above, but I get `Your requirements could not be resolved to an installable set of packages`. I'm using composer version 1.3.0, and I posted my simplified example on [SO](http://stackoverflow.com/questions/41484850/composer-provide-require-not-finding-implementation) in case this turned out to be wrong usage from my end instead of a bug with `provide`

**Comment by Seldaek** [comment]
Fixed by https://github.com/composer/composer/pull/8558
