### ISSUE TITLE
ErrorException ZipArchive::extractTo on composer install

### ISSUE THREAD

**Issue by newtonianb** [composer/composer#2824]
I keep trying `composer install` and keep getting the same error

```
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing mustache/mustache (v2.4.1)
    Downloading: 100%



  [ErrorException]
  ZipArchive::extractTo(vendor/composer/1cf5eec3/bobthecow-mustache.php-14bc3b4\test\Mustache\Test\FiveThree\Functional/HigherOrderSectionsTest.php): failed to open stream: No such file or director
  y



install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [packag
es1] ... [packagesN]
```

I tried:
- deleting my vendor directory
- deleting composer.lock
- deleting composer cache

https://github.com/bobthecow/mustache.php/issues/195

**Comment by andela-fokosun** [comment]
So how did you resolve it i didn't get that part?

Thanks

**Comment by jjoselon** [comment]
I had this path in my machine:

`C:/xampp5.0/htdocs/project-recordando-symfony/project-recordando-symfony`
Then I run `composer install` or/and `composer update` and it returned this error:

`ErrorException ZipArchive::extractTo...`
That error is because your path is too much long, I changed to:

`C:/xampp5.0/htdocs/p-symfony/*`
and worked!

**Comment by darius-v** [comment]
isn't there better way to solve it?

**Comment by j2000d20** [comment]
CvbjsjjskakalLlKzbslaoaiznAlks
