### ISSUE TITLE
Feature - Vendor Directory Constant

### ISSUE THREAD

**Issue by Rican7** [composer/composer#2904]
Currently, writing console applications that use composer is difficult due to the nature of the vendor directory location/name.

If you create a well structured console application then you'll most likely require a bootstrap file of some sort that boots up the application's requirements and instantiate/run's the application's class. However, when doing this, you can run into two problems:
##### 1. What's the name of the vendor directory?

Composer is configurable, which is both wonderful and a problem. Since the "vendor" directory can be [specified to actually be a different directory](https://getcomposer.org/doc/03-cli.md#composer-vendor-dir), the application can't be 100% certain that the vendor directory will actually be called `vendor`.
##### 2. Where is the vendor directory?

Since the vendor directory can technically be in more than one location depending on whether the package is being developed or being used as a dependency, it can make developing a project a pain. When requiring the autoloader, you'll have to technically look for the vendor directory in multiple locations... or worse, you'd have to recurse up a directory tree to locate/find a directory called "vendor" (which may not be its actual name) and hope that it contains a readable file called autoload.php. And believe me, there are [plenty](https://github.com/robmorgan/phinx/blob/948d06712d8e3df23b56a76f890f95e963bb7319/bin/phinx#L31-L34) [of](https://github.com/bobthecow/psysh/blob/636ea9b98ae228fadc3b500cb858eef0c6b63194/bin/psysh#L14-L18) [examples](https://github.com/composer/composer/blob/68e910d92a87dde9c905c9d397fe2e5983ea32ab/src/bootstrap.php#L18) of this practice (yes, even Composer itself).

I propose that a simple constant definition be added to the auto-generated autoloader, so that when using composer's autoloader you have a defined location of where the vendor directory actually exists, regardless of what its name is.

It might also be a good idea to define constants for other locations too, like the `bin` directory since that [can also be redefined](https://getcomposer.org/doc/03-cli.md#composer-bin-dir). Maybe a constant for the autoloader location itself? That might be overkill.

Maybe a better solution to this could exist? This would be just a simple, one-line addition. I'm always open to comments/ideas, though.

Either way, this would help solve a few notable issues here.

**Comment by ggedde** [comment]
I would like to re-open this request.
I am working on a project that would really benefit from a constant or some sort of way to get the "vendor-dir" of the current project.

I fully understand that typically you don't need this feature, but I am working on something that is different and could use it.

the scenario is that from a current class method i want to call a background process to another class.  
Ex.
`class ClassA
{
    public static function process_run()
    {
        $pid = shell_exec('php -r "include \'../../vendor/autoload.php\'; ClassB::run();" > /dev/null 2>&1 & echo $!');
        return $pid;
    }
}`


Right now I have to hard code the path to the vendor/autoload.php, but since ClassA was loaded by composer it should have access to autoloader.php, but is doesn't.

I would prefer:
`class ClassA
{
    public static function process_run()
    {
        $pid = shell_exec('php -r "include COMPOSER_VENDOR_AUTOLOADER_FILE; ClassB::run();" > /dev/null 2>&1 & echo $!');
        return $pid;
    }
}`

If a constant isn't your thing then maybe something else like a static class method.
`
use Composer/Composer;
Composer::getAutoloader();
Composer::getVendorDir();
`

The closest thing I found is to run a shell command:
`$vendor_dir = str_replace("\n", "", shell_exec('composer config --absolute vendor-dir'));`
however, that only works if running from the same directory where your 'composer.json' file is.
Which then means you need to setup some hacky method to find that file.

It is all fine if your managing your own project, but I am trying to create a public package that others can use and therefore I wont know that data and would prefer that they don't have to setup their own constants, etc.

For now I see the benefits of this feature and don't see any downsides and therefore am hoping that this can be added.

I can see a few helper constants:
COMPOSER_VENDOR_AUTOLOADER_FILE
COMPOSER_VENDOR_DIR

Thanks

**Comment by Chi-teck** [comment]
> if PsySH was installed via composer — either globally or in a project — the autoloader is in ../../../autoload.php. Always. No matter what the environment variables are.

Actually not always. Many projects depends on `composer/installers` package which allows to specify location for packages outside of vendor directory. Namely Drupal relies on it.
Does Composer offers a generic way to obtain the autoloader object from any location?

**Comment by stof** [comment]
Well, a given package will know whether it depends on a custom installer or no, as it needs to depend on the installer for things to work fine (and to have a special type). If you don't use a custom installer, the vendor folder will be `../../` from the root of your package.

Defining a constant would not work for cases where a tool installed globally with composer also loads the project-level code, as we would have 2 composer vendor dirs involved, but we cannot have 2 values for the constant.

**Comment by Chi-teck** [comment]
> Well, a given package will know whether it depends on a custom installer or no, as it needs to depend on the installer for things to work fine (and to have a special type). 

Consider Drupal modules. Their location depends on site owner preferences and some other factors. Drupal core does recursive search for _info.yml_ files to discover and register new extensions. So that the module author cannot rely on predefined directory structure.

**Comment by Chi-teck** [comment]
> but we cannot have 2 values for the constant

I suppose the primary goal of finding vendor directory is to locate some specific package. Which is obviously has one and only one location. This could be done using `$autoloder->findFile()` but so far there is no easy way to locate the autoloader object itself. The class inside `autoloader_real.php` has a static method `getLoader()` which could be very useful here. However there it is not clear how to reach that method since its class name is encrypted (i.e. ComposerAutoloaderInit5c100f5f36462f5c09fd9e108d3f47a3).

**Comment by stof** [comment]
The fact that the class name is randomized is precisely done to allow loading the global autoloader and the project-level one at the same time.
Any known class name generated by composer would break that. This is why the supported way to get the autoloader is to require the autoload.php file, which returns the instance.

I think that cases like Drupal modules where the author don't know where the module will be installed would have to be solved with a Drupal-specific solution to find the autoloader of the Drupal project.

**Comment by Chi-teck** [comment]
> Will be installed would have to be solved with a Drupal-specific solution to find the autoloader of the Drupal project.

Right, here it is.
https://github.com/webflo/drupal-finder
