### ISSUE TITLE
Composer fails to find composer.json in private package on git repository

### ISSUE THREAD

**Issue by wvdweij** [composer/composer#2935]
Hi,

After updating composer to the latest version on windows, it's unable to find my composer.json from my private package on springloops. It was working perfect but some how it can't find my package anymore. When I manually create a package in my Project's composer.json respository it works.

I'm running php 5.4.27 on windows 8.1 x64. Composer is updated to latest version. Package is a git repository on Springloops.

Here's a stack trace:

``` php
  [Composer\Repository\InvalidRepositoryException]
  No valid composer.json was found in any branch or tag of ssh://sls@slsapp.c
  om:1234/point4media/p4m-framework.git, could not load a package from it.
```

My project composer:

``` json
{
    "repositories": [
        {
            "url": "ssh://sls@slsapp.com:1234/point4media/p4m-framework.git",
            "type" : "git"
        }
    ],
    "require": {
        "p4m/framework": "dev-master",
        "guzzle/guzzle": "dev-master",
        "facebook/php-sdk": "dev-master",
        "mandrill/mandrill": "dev-master",
        "bluetools/moneybird-php-api": "dev-master",
        "bitgandtter/google-api": "dev-master",
        "paypal/sdk-core-php": "dev-master",
        "synchro/uasparser": "dev-master",
        "enormail/enormail-php-api": "dev-master"
    },
    "autoload": {
        "files": [
            "vendor/lionite/paypal/Paypal.php"
        ]
    },
    "config": {
        "preferred-install": "dist"
    },
    "minimum-stability": "dev"
}
```

And package composer.json hosted on private repository:

``` json
{
    "name": "p4m/framework",
    "type": "framework",
    "description": "P4M Framework",
    "keywords": ["framework", "P4M"],
    "homepage": "http://point4media.nl",
    "license": "proprietary",
    "authors": [
        {
            "name": "Wijnand van der Weij",
            "email": "we.vd.weij@point4media.nl"
        }
    ],
    "require": {
        "php": ">=5.3.0",
        "symfony/console": "2.5.*",
        "symfony/http-foundation": "2.4.*",
        "symfony/finder": "2.5.*",
        "symfony/http-kernel": "2.5.*",
        "stack/builder": "1.0.*@dev",
        "monolog/monolog": "*",
        "filp/whoops": "*",
        "phpmailer/phpmailer": "*",
        "pimple/pimple": "dev-master",
        "htmlawed/htmlawed": "dev-master",
        "doctrine/dbal": "2.4.*@dev",
        "vrana/notorm": "dev-master",
        "hybridauth/hybridauth": "*",
        "phpfastcache/phpfastcache": "dev-Stable-Version-1.x",
        "mobiledetect/mobiledetectlib" : "*",
        "ircmaxell/password-compat": "dev-master",
        "nesbot/carbon": "dev-master",
        "patchwork/utf8": "dev-master",
        "natxet/CssMin": "dev-master",
        "imagine/imagine": "dev-master",
        "oyejorge/less.php": "~1.5"
    },
    "autoload": {
        "psr-0": { "P4m": "src/" }
    },
    "config": {
        "preferred-install": "dist"
    },
    "minimum-stability": "dev"
}
```

**Comment by tasmaniski** [comment]
This save my day, tnx!
``` 
sudo rm -R ~/.composer/cache/vcs/*
```

**Comment by strarsis** [comment]
Composer built-in clean command:
````
composer clear-cache
````

**Comment by DramaMask** [comment]
Sorry to revive an old bug, but I feel that this is a bug. This issue occurs if you change any of the required packages from "dev-master" to "dev-develop", and then delete the master branch. Or any other combination of branches, where you end up deleting the old branch that was being pointed to. 

The error message states "No valid composer.json was found in any branch or tag ...". That implies that composer looked for the composer.json file in several (or even in all) branches and tags. When in fact it only looked in the branch or tag that was cached. The error message should read something like "No valid composer.json was found in the cached branch or tag". Or, ideally, there should be no error message at all. Composer should be smart enough to see that the cached branch does not exist anymore, and subsequently pull down the correct branch (i.e. the one that is listed in the composer.json file).

So, to me, it feels like this ticket should be reopened because we are dealing with a bug here.
