### ISSUE TITLE
Depend on "PHP and Xdebug" or "HHVM"

### ISSUE THREAD

**Issue by sebastianbergmann** [composer/composer#2940]
Is it possible, and if so, how, to express that a package depends on "PHP and Xdebug" or "HHVM"?

The use case for this is php-code-coverage which requires the Xdebug extension on standard PHP but no additional extension on HHVM.

**Comment by nicolas-grekas** [comment]
:+1: on this. Sooner than later, we'll need to express: this lib work on `php>=5.y.z or hhvm 3.a.b`

**Comment by mickaelandrieu** [comment]
@Seldaek is that a "big" feature that need a lot of work ? Would you consider a pull request that address this issue ?

**Comment by Seldaek** [comment]
I think to do it right and think of all the edge cases yes it's probably a lot of work. If you come up with something that works and doesn't introduce an insane amount of code I guess it might be merged, but I am not too warm to this feature I have to say because it sounds like opening pandora's box. Runtime checks can do pretty powerful things and replicating all that in composer.json sounds like it'll go into feature creep pretty quickly.

**Comment by Seldaek** [comment]
Actually after some more thought, I don't really think this is gonna happen, as said above sure if someone comes up with a working and not insane solution we might reconsider but as such I would rather avoid it so closing.
