### ISSUE TITLE
Memory limit issue persists

### ISSUE THREAD

**Issue by nezaboravi** [composer/composer#3067]
Greetings
About to quit trying, tried as many things i could find on web regarding memory limit issue with composer.
Server: Ubuntu 14.04
PHP: PHP 5.5.9-1ubuntu4 (cli) (built: Apr  9 2014 17:11:57) 
These are messages i am getting.
php -r "echo ini_get('memory_limit').PHP_EOL;"
2024MB

curl -sS https://getcomposer.org/installer | php -- --check
PHP Fatal error:  Allowed memory size of 262144 bytes exhausted (tried to allocate 65536 bytes) in Unknown on line 0
curl: (23) Failed writing body (162 != 16313)

root@playground:# composer self-update
PHP Fatal error:  Allowed memory size of 262144 bytes exhausted (tried to allocate 8192 bytes) in /usr/local/bin/composer on line 13

Really dont know what to do.
Thanks

**Comment by videni** [comment]
I have the same issue, is there a solution for this now?

**Comment by curry684** [comment]
This issue is not useful in its current form. The original poster reported:
```
PHP Fatal error: Allowed memory size of 262144 bytes exhausted (tried to allocate 65536 bytes) in Unknown on line 0
```
Which is perfectly logical as he had defined `2024MB` as `memory_limit`, while PHP [only supports the `K`, `M` and `G` suffixes](http://php.net/manual/en/faq.using.php#faq.using.shorthandbytes), thus it defaulted. This makes this issue unrelated to Composer and not really useful to keep around. If you still have *similar* issues with a *well-defined* and realistic memory limit (at least 512MB, preferably -1) consider opening a new issue.
