### ISSUE TITLE
Number for "dev" Stability

### ISSUE THREAD

**Issue by buskamuza** [composer/composer#3121]
Hi,

could you, please, clarify why "alpha", "beta" and "rc" can be appended by a number and "dev" can't?
According to SemVer it's allowed, so we wanted to have versions like "0.1.0-dev.1" and so on while we're in development stage.
We still want to have explicit versions for "dev". "alpha" doesn't suite for it (according to [wikipedia](http://en.wikipedia.org/wiki/Software_release_life_cycle#Alpha)), as we're not in "alpha" stage yet.

**Comment by Seldaek** [comment]
A bit late but anyway for documentation purposes, we don't really support or encourage dev tags. Composer sees `dev` stuff as branches, that can get new changes at any time. Tags can be stable/rc/beta/alpha though, and they should never change.

That's why we append -dev or prefix dev- to branch names, to make it clear they are not really versions but things in development/in flow.

**Comment by buskamuza** [comment]
ok. Thanks.
