### ISSUE TITLE
create-project from private repo without satis

### ISSUE THREAD

**Issue by mi3ll** [composer/composer#3189]
Hello,

I want to set use composer create-project from a private bitbucket repo without having to install a satis server... Is it possible?

I only have the one repo, so don't really want to manage a satis server for it...

Thanks

**Comment by RdeWilde** [comment]
@stof Can you give me an example how that would look like?

**Comment by nevvermind** [comment]
@RdeWilde - I think @stof meant `composer create-project --repository-url="https://user@bitbucket.org/user/repo.git" vendor/project target_dir`, where the Bitbucket repository contains a `composer.json` in its root.

See `composer help create-project` for more info on that command.

**Comment by mikemix** [comment]
However the composer.json file is not accessible with private repository.

**Comment by Seldaek** [comment]
If it's a private repo just do a `git clone` of it.. You don't gain a lot if at all from using create-project in this context. It's useful for public project because it lets you clone something without knowing the git URL just if you know the package name, but for a private one where you need to pass the repo URL anyway what's the point?
