### ISSUE TITLE
Allow plugins to react to Composer\Package\Version\VersionParser::normalize()

### ISSUE THREAD

**Issue by davidbarratt** [composer/composer#3197]
It would be nice if Composer allowed plugins to react to `Composer\Package\Version\VersionParser::normalize()`. This would allow plugin authors to use non-standard version tags. (i.e. if your versions are "one", "two" and "three"). I believe this is the only place that it causing that to not work, but there might be another place in the code as well (the Git Downloader?).

Thanks!

**Comment by Seldaek** [comment]
We have improved quite a bit on the semver side since this issue was opened, but I don't think an extension point there is gonna happen to be honest. It's too edge-case and for inter-change with other repos/language (which IMO is not really a great idea but anyway..) I think building up composer repositories as a front is more sensible and efficient than having composer plugins that do the translation on the fly.
