### ISSUE TITLE
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

### ISSUE THREAD

**Issue by haxwell** [composer/composer#3346]
I installed composer using the instruction at: https://getcomposer.org/doc/00-intro.md.

1) I executed command "curl -sS https://getcomposer.org/installer | php"
2) copied the .phar to /usr/local/bin/composer
3) created my composer.json file in the project directory
4) executed 'composer install' from the directory containing composer.json

I get the following error:

```
  [Composer\Downloader\TransportException]                                                                                           
  The "https://packagist.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:  
  error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed                                                  
  Failed to enable crypto                                                                                                            
  failed to open stream: operation failed  
```

This is very similar to issue #2798 but that issue seemed to have to do with missing certificates, and I don't know OpenSSL well enough to know which certificates to put where (or even if that is the problem). 

I can, however, get "https://packagist.org/packages.json" using cURL, so I'm at a loss.

I'm willing to research and RTFA, if someone could tell me TFA to R. Thanks...

**Comment by vzool** [comment]
## Finally I found the answer :)

**First:** Check certificate file location which will be in default_cert_file key, you will found it in openssl_get_cert_locations() its php openssl function:

```
$ php -r "print_r(openssl_get_cert_locations());"
Array
(
    [default_cert_file] => /opt/lampp/share/openssl/cert.pem
    [default_cert_file_env] => SSL_CERT_FILE
    [default_cert_dir] => /opt/lampp/share/openssl/certs
    [default_cert_dir_env] => SSL_CERT_DIR
    [default_private_dir] => /opt/lampp/share/openssl/private
    [default_default_cert_area] => /opt/lampp/share/openssl
    [ini_cafile] => 
    [ini_capath] => 
)
```
**Second:** Download http://curl.haxx.se/ca/cacert.pem:
```
$ wget http://curl.haxx.se/ca/cacert.pem
```

**Third:** Copy certificate PEM file into default_cert_file location:
```
$ sudo mv cacert.pem /opt/lampp/share/openssl/cert.pem
```
My php-cli is under XAMPP and default_cert_file maybe point to some place that is different than this.
I hope anything after that should goes fine with you brothers.

**Comment by GeneralRamy** [comment]
@vzool your solution work , Thanks

**Comment by Zemke** [comment]
@vzool, works for me, too. Thanks a lot!

**Comment by ericx** [comment]
In FreeBSD 10.x, the trend is to now sym-link the nss cafile to `/usr/local/etc/ssl/cert.pem`. Previously, it was `/etc/ssl/cert.pem`. I found that on older machines the `/etc/ssl` link was still in place; but newer installs only had `/usr/local/etc/ssl`. Adding the symlink in the old location fixes the problem; but probably a better solution is to add:

    openssl.cafile = /usr/local/etc/ssl/cert.pem

to your favorite /usr/local/etc/php/*.ini config until the php56 port catches up.

**Comment by vipmaa** [comment]
@vzool this solution work with me in Ubuntu - Xampp . Thanks

**Comment by nrsutton** [comment]
I'm still having this problem and I'm pulling what's left of my hair out.  I've copied cert.pm to the location specified by default_cert_file and I still get the error message.  Does anyone else have any kind of update for this.  It seems upgrading to PHP 5.6 is a big no no if you use composer.

**Comment by gravypower** [comment]
Have been having this issue for a few weeks and could not pinpoint what was going on, installing new certificates and making sure NTLM usernames and passwords were all ok, it did not seem to stop the issue as **composer diag** reported everything were still not working. It turned out that I had to remove the protocol from my https_proxy. 

Here is what solved my issue on Ubuntu with PHP 5.6.4 behind a corporate proxy.

My first issue was I needed to pass user credentials to the proxy, I solved this issue with [cntlm](http://cntlm.sourceforge.net/). Basically you set your proxy to a local address and then cntlm passes the request onto the corporate proxy with credentials. I had a hard time getting this to work so if anyone needs help with this drop me a line.

So now I had internet access with our supplying my username and password each time I made a request :D 

I was still having issues with SSL event after working through the suggestions listed in this thread,  finlay I read somewhere that removing the protocol from your https proxy worked.  Using this command:
```bash
export set https_proxy="127.0.0.1:3128"
```
This command made  **composer diag** work for the terminal session but every time I opened a new session this command needed to be run again. That was all good, I can live with that. 

All my problems seemed to be solved, I was so happy, well until I tried to install aegir.  This used apt-get ran with the sudo command, and I was seeing the SSL error again.  NOOOOOO /CRY

What was happening (I think) was that the default environmental variables were being used as sudo was opening a new session. It was time to fix this once and for all (well so far) I made a change to the default environment variables.

```bash
sudo nano /etc/environment 
```

I changed the https_proxy to https_proxy="127.0.0.1:3128"

I hope this helps someone.

Aaron

**Comment by KissDaniGH** [comment]
hi
open https://packagist.org in your browser.
Export all the certs.
copy them /usr/local/ca-certificares.
run update-ca-certifcates
check if new crt is added
if yes ur OK

**Comment by ilhnctn** [comment]
Your solution gave result. Thanks @vzool

**Comment by Seldaek** [comment]
Closing as we now handle SSL quite a lot better.

**Comment by Graham-92** [comment]
@vzool， It work for me too. Thanks very much

**Comment by Vijaysinh** [comment]
I am using windows 7 - 32 bit.

I also updated php.ini file to this after downloading cacert.pem file and restart apache but still I am having issue. Can anyone please help me?

extension=php_openssl.dll
openssl.cafile = "C:\xampp\php\extras\openssl\cacert.pem"

**Comment by psalami** [comment]
In my case, making sure that the correct cert.pem file exists was not sufficient. You need to also set your time zone in your php.ini to your actual time zone using the `date.timezone` key (in my case, I set it to America/Los Angeles). Otherwise, PHP will default to using UTC and your system clock will appear to be off. This solved the issue for me on Mac OS X El Capitan (10.11.2).

**Comment by Vijaysinh** [comment]
@psalami I have updated date.timezone in php.ini but still getting same issue...

**Comment by binarious** [comment]
Same here. Updating the cert and putting it in `default_cert_file` didn't help. The `date.timezone` is set, too.

PHP 5.6.22
OS X 10.11.5

**Comment by mrg123** [comment]
so i have one resolution.
if you use php5.6.x
maybe can help you. 
http://stackoverflow.com/questions/26148701/file-get-contents-ssl-operation-failed-with-code-1-and-more

http://php.net/manual/en/migration56.openssl.php

**Comment by parsibox** [comment]
only install this
yum install ca-certificates.noarch

**Comment by vampirebitter** [comment]
however,it didn't work in version **PHP 7.0.8-0ubuntu0.16.04.2**, I really wonder if you have tried this with a php version of 7.0.* or whether you have an another solution , looking forward to reply , I really appreciate it. @vzool

**Comment by parsibox** [comment]
yes is use php7 but in CENTOS 6 64bit

**Comment by GwenWing** [comment]
On Debian 8.6, using php 5.6, there is a missing file /usr/lib/ssl/cert.pem

In order to fix it download CA certs :
` wget http://curl.haxx.se/ca/cacert.pem`

Then copy to /usr/lib/ssl/cert.pem, and you can use fsockopen with SSL.

Maybe an issue with openssl packaging or a missing dependency, but I couldn't find /usr/lib/ss/cert.pem in Deb packages

**Comment by LPugens** [comment]
Using Ubuntu 16.04 and php7, I could fix it by installing
`apt-get install ca-certificates`
And running 
`update-ca-certificates`

**Comment by ademirdiniz** [comment]
Hi, all.

I've fixed this issue doing the follow:

**1º: Download the certificate:**

`wget http://curl.haxx.se/ca/cacert.pem --no-check-certificate`

`2º: Export it to COMPOSER:`

`export COMPOSER_CAFILE='/home/user/cacert.pem'`

> The path need to be the same where you've downloaded the certificate in firts step.

It works for me! :D

**Comment by AleksSv** [comment]
I don't think I saw this mentioned, but a possible trigger of this error could be incorrect permissions for ssl directories.

For me it turned out I had the default certs directory as 700 instead of 755 (remember this is certs not private).

Doing
sudo chmod 755 certs
Fixed the problem for me

**Comment by mab287** [comment]
Hope this can help :
I had, from one day to another, the same issue on a WS 2k12 server
php -r "print_r(openssl_get_cert_locations());" indicated that cert destination was 

[default_cert_file] => c:/usr/local/ssl/cert.pem
[default_cert_file_env] => SSL_CERT_FILE
[default_cert_dir] => c:/usr/local/ssl/certs
[default_cert_dir_env] => SSL_CERT_DIR
[default_private_dir] => c:/usr/local/ssl/private
[default_default_cert_area] => c:/usr/local/ssl
[ini_cafile] =>
[ini_capath] =>

So, I searched computer for cert.pem files
found in "C:\Program Files\Git\usr"
copied the ssl directory to a created directory : c:/usr/local 

and it works.

Seems crazy ...

**Comment by gavstah** [comment]
Exporting the COMPOSER_CAFILE variable worked like a charm for me.  Until then, I'd been having a frustrating time having tried everything else in this thread.

**Comment by scrummerlp** [comment]
@AleksSv Sweet fix, worked fine for me. Thx :)

**Comment by acccounttest** [comment]
It worked exactly like that, replacing cert file BUT
I CANT HAVE THIS WORKING BECAUSE I USE IT IN POPEN :((
because its in a chat and i dont want i mail server, just this working without delay.

**Comment by mdolnik-eelzee** [comment]
I had the same issue and tried everything, including messing around with the certificate files.

Turned out to be Kapersky Antivirus...

Thanks to [@marcovtwout](https://github.com/composer/composer/issues/6870#issuecomment-394355040)

**Comment by creazy412** [comment]
If you've tried many ways and haven't solved them, try the following:
`;cert.pem 可以从curl.haxx.se/ca/cacert.pem 下载

openssl.cafile=/usr/lib/ssl/cert.pem
`

**Comment by rahulsharma20** [comment]
> only install this yum install ca-certificates.noarch

You are a life saver

**Comment by ckeyhd** [comment]
Wow! @vzool , really, really thanks! Your solution was great for me 😎

**Comment by natzar** [comment]
> ## Finally I found the answer :)
> **First:** Check certificate file location which will be in **default_cert_file** key, you will found it in _openssl_get_cert_locations()_ its php openssl function:
> 
> ```
> $ php -r "print_r(openssl_get_cert_locations());"
> Array
> (
>     [default_cert_file] => /opt/lampp/share/openssl/cert.pem
>     [default_cert_file_env] => SSL_CERT_FILE
>     [default_cert_dir] => /opt/lampp/share/openssl/certs
>     [default_cert_dir_env] => SSL_CERT_DIR
>     [default_private_dir] => /opt/lampp/share/openssl/private
>     [default_default_cert_area] => /opt/lampp/share/openssl
>     [ini_cafile] => 
>     [ini_capath] => 
> )
> ```
> 
> **Second:** Download http://curl.haxx.se/ca/cacert.pem:
> 
> ```
> $ wget http://curl.haxx.se/ca/cacert.pem
> ```
> 
> **Third:** Copy certificate PEM file into default_cert_file location:
> 
> ```
> $ sudo mv cacert.pem /opt/lampp/share/openssl/cert.pem
> ```
> 
> My php-cli is under XAMPP and **default_cert_file** maybe point to some place that is different than this. I hope anything after that should goes fine with you brothers.

Worked on XAMPP for Mac too.

**Comment by anghelpw** [comment]
I had the same issue for Ubuntu 16.10 with PHP 7.0 and here is what worked for me:

1. Download the certificate:
`wget http://curl.haxx.se/ca/cacert.pem --no-check-certificate`

2. Configure composer to use that file:
`composer config --global cafile '<location of cafile>'`
