### ISSUE TITLE
Allow update to specific version. something like composer update vendor/package:v1.0.5

### ISSUE THREAD

**Issue by gena01** [composer/composer#3387]
So i've been running into this weird edge-case where composer will install the "wrong" version of the package for one reason or another. I would love to try and update to a specific package version.

One use case  I ran into today was that doing "composer show vendor/package" showed v1.0.5 but doing "composer update vendor/package" only installed v1.0.4. It took me some time to figure out why it didn't pick the latest  version. I wish I could force a specific version and if the dependencies can not be resolved then I want to see why. I could change composer.json to pin it to that version or hack composer.lock to pin it that way, but via command-line could be easier/cleaner.

P.S. "pear" actually had an option similar to this. Also I think "composer require" has vendor/package:version syntax.

**Comment by Seldaek** [comment]
see `composer require foo/bar:1.0.5` for the update to a specific version.

**Comment by albertski** [comment]
Here is a good scenario of when an update to a specific version would be useful:

I have `"drupal/lightning": "8.1.0",` in my composer file. If I run `composer require drupal/lightning:8.1.01` I get the following errors:

```
  Problem 1
    - Can only install one of: drupal/entity_browser[8.1.0-alpha5, 8.1.0-alpha3].
    - Can only install one of: drupal/entity_browser[8.1.0-alpha5, 8.1.0-alpha3].
    - Can only install one of: drupal/entity_browser[8.1.0-alpha5, 8.1.0-alpha3].
    - drupal/lightning 8.1.01 requires drupal/entity_browser 8.1.0-alpha5 -> satisfiable by drupal/entity_browser[8.1.0-alpha5].
    - Installation request for drupal/lightning 8.1.01 -> satisfiable by drupal/lightning[8.1.01].
    - Installation request for drupal/entity_browser (locked at 8.1.0-alpha3) -> satisfiable by drupal/entity_browser[8.1.0-alpha3].
```

Reason is that 8.1.0 requires entity_browser `8.1.0-alpha3` but 8.1.01 requires `8.1.0-alpha5`.


So the only way for me to update to 8.1.01 is to update my composer file and run `composer update`.

It would be nice to run a command like `composer update drupal/lightning:8.1.01`.

**Comment by ItsReddi** [comment]
@Seldaek like @albertski said. Same here.
Even changing composer.json manually and update doesnt work. Only way is to remove package and install again with new version.
`  Problem 1
Installation request for braintree/braintree_php (locked at 3.8.0) -> satisfiable by braintree/braintree_php[3.8.0].
sp/yii2-braintree 1.3.0 requires braintree/braintree_php 3.16.0 -> satisfiable by braintree/braintree_php[3.16.0].
sp/yii2-braintree 1.3.1 requires braintree/braintree_php 3.16.0 -> satisfiable by braintree/braintree_php[3.16.0].
Conclusion: don't install braintree/braintree_php 3.16.0
Installation request for sp/yii2-braintree 1.3.* -> satisfiable by sp/yii2-braintree[1.3.0, 1.3.1].`

**Comment by stof** [comment]
Well, if you have ``braintree/braintree_php`` locked at 3.8 and you do a partial update not whitelisting it, it won't be allowed to be updated (and so resolution might fail). There is a ``--with-dependencies`` to whitelist automatically the dependencies of the whitelisted packages

**Comment by iBasit** [comment]
what was the solution for this problem?

**Comment by becw** [comment]
You can use the `--update-with-dependencies` flag for [composer require](https://getcomposer.org/doc/03-cli.md#require).

For the [example from the comment above](https://github.com/composer/composer/issues/3387#issuecomment-232555801), say you have `"drupal/lightning": "8.1.0"` required in your composer file. To update to a specific different version (say 8.1.01) you can run `composer require drupal/lightning:8.1.01 --update-with-dependencies`. This will update the `drupal/entity_browser` dependency from 8.1.0-alpha3 to 8.1.0-alpha5, since this dependency has changed between the two versions of `drupal/lightning`.

**Comment by felixfbecker** [comment]
`composer require vendor/package:version` works if you directly depend on the package, but if you indirectly depend on it through another package then there is currently no way to update the composer.lock to update only that package to a specific version. This makes it impossible for services like dependencies.io to update indirect dependencies that are locked in composer.lock.

**Comment by caugner** [comment]
I'm a bit surprised that `composer require vendor/package:version` is advised as a replacement for the requirement explained in this issue.

The `require` command has the side-effect of changing the `composer.json`, which may not be desired, because IMO it reduces the space for conflict resolutions.

**Comment by Seldaek** [comment]
Just for reference, this will be possible in 2.0 thanks to https://github.com/composer/composer/pull/8860 - only for root requirements though as allowing this for non-root requirements is kinda pandora's box as it would potentially lead to adding requirements/packages which did should be there otherwise.
