### ISSUE TITLE
Can I use "pre-dependencies-solving" event to add dynamic dependencies?

### ISSUE THREAD

**Issue by donquixote** [composer/composer#3430]
Hi..
would it be possible to register a "pre-dependencies-solving" event listener in the root composer.json, that will add new dependencies dynamically, or otherwise alter the data from composer.json?
https://getcomposer.org/doc/articles/scripts.md

The scenario I am thinking of:
Having a number of "local" packages with their own composer.json, which are not managed or seen by Composer, living outside of the vendor dir.
My custom event handler could scan these folders and merge the composer.json files found there into the main composer.json data, as if they had been downloaded by Composer.
The idea is to do this by manipulating the data, not by editing a file. (although that would be acceptable too)

Don't ask why - It's a wonky Drupal discussion, again :) I simply want to know if this is possible, but this does not mean we will do it.

**Comment by bojanz** [comment]
I opened a duplicate. Quoting myself:

>Drupal extensions can be downloaded and placed into a Drupal directory to be automatically discovered.  They can contain a composer.json file each. 
Goal: When composer update is run from Drupal's core directory, the extensions are discovered, and their requirements are merged in. Ideally, we'd also resolve minimum-stability and repositories.
The discovery & merging code is already done, what remains is making Composer aware of the regenerated root package.
So, I'm trying to regenerate the root package once composer update is already running (in a pre_update_cmd event), which fails because Composer has already been initialized with the old one.
I tried to do $event->getComposer->setPackage($newPackage) and $event->getComposer->setConfig($newConfig) but that had no effect, probably because the installer already copied the old ones.
Is there are a way to accomplish this without wrapping composer in another command (which regenerates the composer.json and then runs composer itself)?

**Comment by ameenross** [comment]
@bojanz it might just be a matter of using the `pre-dependencies-solving` event instead. Haven't tested though

**Comment by tburry** [comment]
This is a bit of an old issue, but I wanted to share a solution I came up with for anyone else that finds themselves falling through the same google rabbit hole that I did.

My requirements were to have a separate composer.local.json file in the same directory as my root composer.json file that could contain additional dependancies. Here is what I did:

1. I ended finding that the best events to subscribe to were `pre-install-cmd` and `pre-update-cmd` because they happen suitably early. The `pre-dependencies-solving` event happens after requirements are installed which would make installing additional dependencies more difficult.
2. Created a method that looks for the my `composer.local.json` file. If it exists I load it and then merge the `repositories`, `requires`, and `requires-dev` items from my composer, although this is done on the composer object model rather than the file structure.

The code I have is in [this commit](https://github.com/vanilla/vanilla/commit/c2adc45e4c1020d9a865fff080f0b2e1e46eff6e) and is quite short so it should be fairly easy to adapt to other projects.
