### ISSUE TITLE
Partial update is broken

### ISSUE THREAD

**Issue by lu4e3ar** [composer/composer#3468]
I have a composer.json and a composer.lock with a couple of packages and empty vendor directory.

When I run 
composer update sonata-project/notification-bundle sonata-project/media-bundle jms/serializer-bundle knplabs/knp-paginator-bundle oldsound/rabbitmq-bundle

I have all my bundles updated, not only the listed ones.

Behaviour is similar to https://github.com/composer/composer/issues/782

**Comment by esalter** [comment]
Is there any movement on this issue? I'm not sure if it's 100% the same thing, but we are having a problem simply issuing:

composer update ourvendor/ourpackage

This triggers a full update of all packages.  According to the docs it should only update that one package and any dependencies it has.

I'm fairly certain we did a composer install first beforehand as well.

**Comment by nevvermind** [comment]
Yeah, not sure about this, too. I have the opposite. I can't get it to update.

I've installed Monolog 1.10.0, and trying to get that to a later version.
```
$ composer show -i
behat/gherkin   v3.1.3 Gherkin DSL parser for PHP 5.3
monolog/monolog 1.10.0 Sends your logs to files, sockets, inboxes, databases and various web services
psr/log         1.0.0  Common interface for logging libraries
```
Now I'm trying to get Monolog to the latest version. Not sure if _this_ is how you do it, but this seem what someone _might_ do. Here, I'm expeting Monolog to be bumped to the latest version:
```
$ composer update monolog/monolog
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```
OK, that didn't work. I'll try declaring a valid version:
```
$ composer update monolog/monolog:1.13.0
Package "monolog/monolog:1.13.0" listed for update is not installed. Ignoring.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```
But this works, though:
```
$ composer require monolog/monolog:1.13.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing monolog/monolog (1.10.0)
  - Installing monolog/monolog (1.13.0)
    Loading from cache

Writing lock file
Generating autoload files
```

**Comment by alcohol** [comment]
Can everyone please share their `composer.json` related to their scenario. We really cannot reproduce any of these issues without them.

**Comment by alcohol** [comment]
If you are not following the following scenario by the way, then I am not sure what we can do, as anything else is outside the norm:

1. `git clone ...`
2. `composer install` (either from a `composer.json`, or `composer.lock`)
3. `composer update vendor/package`

I have no idea how composer should behave in the following scenario (because it doesn't make any sense):

1. `git clone ...`
2. `composer update vendor/package`

but I suspect it will not behave as you want it to.

If any of the mentioned issues do not fit either of these two descriptions, then please, provide a step by step scenario similar to the two above regarding your issue

**Comment by samuelvogel** [comment]
It's the second case you mentioned @alcohol. It might not make that much sense at first sight, but it happens regularly if you just want to push a dependency to a new version and deploy it, while not developing on your machine with that exact clone.

In my opinion the `composer update vendor/package` without an explicit `composer install` before should behave like you actually did run it before (only `vendor/package` gets updated, everything else is just installed in the version from `composer.lock`) instead of implicitly updating everything (and thereby ignoring the "restriction" to `vendor/package`).

So running:
1. `git clone ...`
2. `composer update vendor/package`

Should be interpreted like (**not** currently the case):
1. `git clone ...`
2. `composer install`
3. `composer update vendor/package`

Instead of (currently the case):
1. `git clone ...`
3. `composer update`

The current behavior is pretty confusing in our opinion.

**Comment by slbmeh** [comment]
Right now an update with a whitelist will add an installation request for the exact version of each package within the installed repository if it does not match the whitelist.  Perhaps that installed repository should be a composite with a locked repository as well.

**Comment by samuelvogel** [comment]
> Right now an update with a whitelist will add an installation request for the exact version of each package within the installed repository if it does not match the whitelist.

But it ignores the fixed versions in `composer.lock` if `composer install` wasn't run before and updates everything ignoring the whitelist (I just tested it again).

> Perhaps that installed repository should be a composite with a locked repository as well.

Sorry, I don't get what you are trying to say.

**Comment by slbmeh** [comment]
The locked repository is what comes from `composer.lock`.  The installed repo is the only thing currently considered.

If we wrap the installed repository that is currently checked with a composite repository and add the locked repository from `composer.lock` it should work as you expect.
