### ISSUE TITLE
Alternative to PSR autoloaders: lowercase all paths?

### ISSUE THREAD

**Issue by Ocramius** [composer/composer#3581]
As per [current discussion on php-internals](http://news.php.net/php.internals/79858), I was wondering if PSR-0 (or PSR-4, depending on preference) autoloaders that use all-lowercase paths would be viable.

The current approach is to convert `Foo\Bar\Baz` to `basepath/Foo/Bar/Baz.php`.

This obviously tends to break a lot of production systems when people develop on case-insensitive filesystems, and then deploy code with Case-SenSITIvIty issues. 

The suggested approach is to just compute every path/substring comparison after having used `strtolower()` on the FQCN/prefix.

New approach would be to convert `Foo\Bar\Baz` to `basepath/foo/bar/baz.php`.
### Autoloader name

As per @TazeTSchnitzel suggestion, `psr-0-lower` or `psr-4-lower` would be decent names for this new kind of autoloader.
### Advantages
- no more ugly failures because of case sensitivity issues: these are still to be reported by static introspection though
- simpler directory structure
### Disadvantages
- no ability to use different autoloaded classes depending on casing (but I'd like to know where you live, what car you drive and where your kids go to school if you are doing that)
- can't easily migrate to new file structure because git/svn/etc freak out with case-sensitivity issues.

**Comment by memtoko** [comment]
hmm, just make an helper in composer to detect the platform is case insentive or not. It's that hard to achieve from current implementation? May be check that php uname match again this string ```'win', 'cygwin', 'darwin'```

**Comment by poncha** [comment]
@Seldaek what about modifying loadClass to perform findFile twice (first time unmodified, second time on `strtolower($class)`) ?

This way composer can support both camel-case and all-lowercase scenarios and there are additional performance implications only if developer choses to use all-lowercase files explicitly, or when there is a typo in class name really (in which case it should fail eventually not unlike right now).
And it would support that regardless of the schema used.

This can also be enabled/disabled by configuration in case there are performance considerations and this is not desired (although since this code would not be reached normally, i'm not sure it is needed).

    public function loadClass($class)
    {
        if ($file = $this->findFile($class)) {
            includeFile($file);

            return true;
        }
        if ($file = $this->findFile(strtolower($class))) {
            includeFile($file);

            return true;
        }
    }

**Comment by Seldaek** [comment]
@poncha it's easy to do in your app by wrapping the composer autoloader so I don't see a need to have exotic stuff added directly in our loader.
