### ISSUE TITLE
Allow/suggest cleanup on failure

### ISSUE THREAD

**Issue by Sequoia** [composer/composer#3648]
```
Writing lock file
Generating autoload files
Mcrypt PHP extension required.
Script php artisan clear-compiled handling the post-install-cmd event returned with an error
                      
  [RuntimeException]  
  Error Output:       
                     

create-project [-s|--stability="..."] [--prefer-source] [--prefer-dist] [--repository-url="..."] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [package] [directory] [version]

➜  learning  pos create-project laravel/laravel learning-laravel
Installing laravel/laravel (v4.2.11)
                                                     
  [InvalidArgumentException]                         
  Project directory learning-laravel/ is not empty.  
                                                     
```

Is the state of learning-laravel corrupt after the install? If so, install failure should either delete it or offer it as a Y/n option.  Why keep a corrupt/failed install? It can lead to user confusion.

**Comment by Seldaek** [comment]
It's quite hard to know what to do after a script fails unfortunately, because some of them do relatively simple things which can fail but not in a dramatic way, just rerun them by running composer install again and all is well, and I guess some might fail in more critical ways.

I assume the `Mcrypt PHP extension required.` line is the reason the script handler failed, you probably want to try again after adding that.
