### ISSUE TITLE
Add support for alternative vendor dir, where one can develop dependencies without the risk of them being overwritten by composer

### ISSUE THREAD

**Issue by Brainshack** [composer/composer#3689]
Hello,

I think we need some place where we can put our dependencies that are currently under development, to ease up the workflow for this kind of development a bit. Some packages, can only be developed, when they are installed in conjunction with other packages. For example: To develop an oxid module, you need to have an oxid installation, which uses you module(package) as a dependency. To do this, right now what you would have to do is:

- Create a repository for your package
- Add a composer.json to this package and push it to your repo
- Make your root package aware of the new package (either by adding it to packagist, satis or via local repo config)
- Install it

However, if I make changes to my package now, I need to push it to my repo, everytime I commit changes. Otherwise I run into the risk, that composer overwrites it, with the current version that resides inside the git repository, everytime i run a composer update.

I don't think that is an optimal workflow.

A suggestion would be, to just add an alternative vendor directory, that wont be updated automatically, but still we be included for autloading and checked for changes in the packages, to be able to install 3rd party packages, that packages that reside in this directory need to work.

**Comment by alcohol** [comment]
Composer detects changes and will ask you what to do. Did you even try this before you wrote this issue?

**Comment by Brainshack** [comment]
It does not if you commited changes but didnt push them to the remote.

Also, if I were to create a new package, I am always forced to push the composer.json to the repository in order to be able for composer to update depdencies from this package.

**Comment by alcohol** [comment]
I'm sorry, but your workflow is suboptimal because it **is** suboptimal. Composer is not at fault here. If you constantly need to run composer update (why?), and that means risking losing committed (but not pushed) changes, then you are simply doing something wrong. 
Either limit your composer update to the package(s) that you want to update (e.g. `composer update symfony/console symfony/http-kernel ...`), or learn to push your changes as soon as you commit them.

**Comment by Brainshack** [comment]
Sorry, but when working in big development teams with a lot of packages
being developed constantly, you really suggest me to update each of these
packages manually? ( We are talking about 60+ packages here) If I wanted to
update my dependencies manually, why even bother using a tool like
composer? Yes, of course I could push every commit I make. But sometimes
you will just forget it and might end up losing work. The change I am
suggesting is more of a quality of life change, that would just ease up the
development process for new packages, that only work in conjunction with
application frameworks.

2015-01-30 11:38 GMT+01:00 Rob <notifications@github.com>:

**Comment by alcohol** [comment]
Would it be useful if the composer update command instead allowed you to use a negative match? I'm just thinking out of the box here, trying to see if there are easier solutions to be found.

So something like, `composer update !vendor/not-this-package`.

**Comment by Brainshack** [comment]
Well I guess this command would be usefull, even for other situations.

I wonder if it would be somehow possible to check whether a package has
unpublished changes.

2015-01-30 11:54 GMT+01:00 Rob <notifications@github.com>:

**Comment by Nek-** [comment]
I'm not sure this issue is relevant.

For development of libraries a good solution is using git submodules. Composer authorize you to add new paths if you want to separate lib that you are working on.

On the other hand, if you change the vendor directory, then frameworks and people can change the dir folder to add what they want. (just imagine if symfony do a `SfVendors` while yii use a `lib` directory) It would be so weird for everybody.

IMO standardization of the PHP dependencies folder is important.

**Comment by Brainshack** [comment]
I am not suggesting to change the vendor dir or have a slew of multiple
vendor directories. All I want to b able to do is, define a directory, in
which i can put my packages that are being developed and that is checked by
comnposer if the packages in this directory need some dependencies.

Let's say I define this directory to be "modules". I will add a package
there that has a composer.json. The package needs guzzle. Now when I do
composer update, composer checks the packages in the modules dir, if they
have any unresolved dependencies, and installs those dependencies in
vendor, if required. Also, composer would consider this directory for
autloading.

This could be done, without having to publish my WIP modules to packagist,
or adding the as local repositories.

It's somewhat similar to the way symfony does things, where you can either
install bundles via composer to the vendor directory, or have them sitting
inside src, while you develop them.

2015-01-30 12:09 GMT+01:00 Maxime Veber <notifications@github.com>:

**Comment by alcohol** [comment]
I agree @Nek- , that is why I am trying to think of simpler solutions. Blacklisting is the most obvious one that comes to mind. Expanding the way composer checks for local vendor changes is another. I suspect the latter can be found [here](https://github.com/composer/composer/blob/master/src/Composer/Downloader/GitDownloader.php#L100), but I need to further investigate the particulars of how it functions and when it is called.

**Comment by alcohol** [comment]
@Brainshack you're making it sound now like you **don't** need composer to manage your modules/packages. Which is it now? Yes or no?

**Comment by Brainshack** [comment]
Wouldnt it suffice to just run "git log origin/composer..HEAD" to see if
there are any commits in the current HEAD or locally used branch, that are
not in the origin? Would have to make sure that the remotes have been
fetched before of course.

2015-01-30 12:21 GMT+01:00 Rob <notifications@github.com>:

**Comment by Seldaek** [comment]
@alcohol that is indeed how the changes are checked. And it only checks for *uncommitted* changes because that's easy to check for and would be rather dramatic if deleted. With committed changes it's pretty hard to lose work when doing an update because composer might update you to another commit but using `git reflog` you can usually get your commit back.

@Brainshack Anyway yes I realize this isn't optimal right now. I am feeling that pain myself in some projects, but I am not entirely sure what the best approach is to fix it. Your approach is interesting but I am not sure if the added complexity is worth it nor if it'll be really easy to work with.

Another option which sounds better to me because there is a precedent is to copy https://docs.npmjs.com/cli/link - it's not necessarily easy to achieve well on windows though.

**Comment by Seldaek** [comment]
@Brainshack regarding git log, yes it could be an option but that exact command won't work. Maybe we have enough info in vendor/composer/installed.json to make up a proper command though, i.e. check if the last installed git reference is still HEAD or not, and then maybe check if it was pushed or not somehow but that's harder because you typically push to origin/something and we don't always know where that is I think, we can possibly guess though. Needs to be explored further.

**Comment by Brainshack** [comment]
@Rob: How so?

We use composer to manage our dependencies and I find it more then just
usefull. It allows us to automate a lot of stuff and I wouldn't want to
miss it.

All I am saying is, that developing and maintaining packages in an
environment where a lot of changes happen in a lot of packages, you could
end up shooting yourself in the foot. I just thing that these suggested
changes would ease up the process of developing with composer and make it
less prone to human error.

2015-01-30 12:26 GMT+01:00 Christian Loock <brainshack@gmail.com>:

**Comment by alcohol** [comment]
@Brainshack no I meant, that if you put your modules/packages in say... `src/`, and just use autoloading to include them, then basically you are suggesting that you would not use composer to manage those. Which in turn makes this whole issue moot because composer update would never touch them. So I think your comparison to Symfony bundles was probably not what you have in mind.

**Comment by Brainshack** [comment]
@Jordi Boggiano:

If I understand the npm-link correctly, it would just replace the package
with a smylink to a package, that resides in a globally available
directory, right? But what if there are mutliple ppl working on the same
machine, like development servers?



2015-01-30 12:32 GMT+01:00 Jordi Boggiano <notifications@github.com>:

**Comment by Brainshack** [comment]
@Rob: Not really. I still want to be able to manage my dependencies inside
my packages inside composer and use composers autoloader. I know that
symfony bundles currently dont work that way. But they could, which would
make it even easier to develop them.

2015-01-30 12:37 GMT+01:00 Christian Loock <brainshack@gmail.com>:

**Comment by Seldaek** [comment]
Development servers haven't really been a great idea since we started 
using VCS and stopped using FTP for deployments. I am ok discussing 
people's use cases but that is really not a valid one IMO because it's 
promoting bad practices.

It would symlink locally and in that case composer update would not 
touch this package at all IMO it would just have to read the 
composer.json data from the directory and we'd have to figure out a way 
to generate info for the lock file. It creates a lot of new problems to 
tackle if we want to do a good job of it, but it would be in a way what 
you suggested with your alternative vendor dir, except it'd be 
"instutionalized" as a command instead of you having to set things up 
manually.

**Comment by alcohol** [comment]
Yeah I know @Brainshack , I was just checking because your reference did not really make sense to me in the given context. Anyway, I think blacklisting is the easiest approach. But as @Seldaek pointed out to me, that is indeed just as prone to being forgotten as `git push` is.

**Comment by Brainshack** [comment]
Maybe an alternative would be to just add a method of marking a package as being "under development". This way, composer would know, that it shouldn't overwrite anything inside the package and just check for local changes inside the composer.json to update dependencies as desired.

**Comment by Seldaek** [comment]
Yes but that is pretty much the same as the link command, and comes with 
the same problematic of lock file management etc.

I think the only quick win we can have here is try to detect unpushed 
commits and if we conclusively detect something warn the user. The rest 
will need a lot more work.

**Comment by Pierstoval** [comment]
If you are using Composer's autoloader, then you'd better have your "under development" repo inside a directory which is checked by your autoloader (like `src` for most Symfony apps, for example) and then add its dependencies to your composer.json file.
Or you can put it inside another single directory and add a `psr-0` or `psr-4` directive in your composer.json in order to autoload it.

IMO , if a package is under development, it has no place in a `vendor` dir.

**Comment by alcohol** [comment]
@Pierstoval While I do agree to some extend, I can see the downside to that.

You could indeed get a local checkout of each "module" package (which are part of your "big" framework package) and have a dev-require on the full framework package to pull in all other modules for inter-module dependency needs.

*But* that would mean that you would end up with a **lot** of checkouts next to a checkout of the "big" framework package as well. I can understand why some people would prefer to work directly on the modules inside the `vendor/` directory of the "big" framework package.

**Comment by slbmeh** [comment]
I didn't read the whole issue thread here, but if you committed your changes then they aren't lost. As long as you're using git anyhow. Don't know about the other vcs drivers. Your commit is still in the object storage and you can find the previous hash by looking at the reflog.

**Comment by grzesiek** [comment]
Hello.

I just run across this issue, sorry for digging it from the ground.

I'm currently working on project that combines features of Composer and Git submodules. It is in it's late alpha phase (almost beta at this moment), so you can check it out. One of core features of this project is to create yet-another-dependency-manager that will allow you to use dependencies and develop them at the same time. 

This is combination of submodule-based approach, plus Composer-like dependency management via manifests and lockfiles.

If you are interested in it, take a look at http://github.com/grzesiek/git_compound

Kind regards,
 Grzegorz

**Comment by Seldaek** [comment]
Don't think we are going to make further changes here, there are a few tools facilitating it, and the path repository in composer lets you also edit things in vendor without much risk of overwrites.
