### ISSUE TITLE
ability to use stable release(s)

### ISSUE THREAD

**Issue by cybernet** [composer/composer#3707]
ability to use ```composer self-update --stable``` :)

**Comment by stloyd** [comment]
There is "stable" release of Composer yet ;)

**Comment by cybernet** [comment]
i know but using just ```composer self-update``` doesn't always get a stable version

**Comment by alcohol** [comment]
Uh... so what defines stable then?

**Comment by aderuwe** [comment]
Stable is the one you roll back to. ;)

**Comment by hkdobrev** [comment]
I suppose a flag could be introduced which only installs tagged versions of Composer. E.g. the alpha tags and not any commit in between. I don't think `--stable` is the right name for it though.

Also for this to be useful versions (even not stable) should be tagged more often.

**Comment by stof** [comment]
@hkdobrev you can rollback to any version of Composer you have installed previously (as long as you don't clear your composer cache).

**Comment by cybernet** [comment]
what about travis ?

**Comment by stof** [comment]
@cybernet I don't understand your question

**Comment by alsar** [comment]
What about `composer self-update --stability=alpha`?

**Comment by alcohol** [comment]
Why do you **need** this?

**Comment by edhgoose** [comment]
I've been wondering about this feature myself - I'm new to Composer and recently set up continuous integration with capifony (a capistrano toolset for Symfony) and found that it _can_ be luck of the draw if you get a stable version.

This is probably partly due to our setup (Jenkins clones our Git repo, updates it's local Composer version to latest and then goes to each box we're deploying to and installs the latest composer), but finding the middle ground between stable (with latest features/bugfixes) but also not bleeding edge (may have issues) would be nice.

I suppose I'm quite happy to run bleeding edge when time is on my side, but when it's late at night and I just want to get the code deployed, I don't want to have to try and figure out whether I broke something in my code or if Composer broke (e.g. earlier this evening: #3777).

It's not a question of need I don't think, it's a case of making life easier and lazier :)  Maybe the solution could be a bleeding edge version (i.e. master), a not-quite-bleeding-edge (e.g. master, but from last week or 30 days ago) and an alpha/stable channel which is for well defined releases.

Just a thought.

(P.s. Having said all that - given selfupdate uses master, I'm pleasantly surprised with how robust it has been!)

**Comment by schmunk42** [comment]
I have a similar problem in our CI and Docker setup.

I am using this at the moment

    curl -sS https://getcomposer.org/installer | php -- --version=1.0.0-alpha10

The install script could obtain the latest version from here: https://api.github.com/repos/composer/composer/releases

**Comment by samdark** [comment]
Would be great to update to tagged commit only be default because of https://github.com/composer/composer/issues/4160 and alike breakages. A special flag to update to master would be great as well.

**Comment by schmunk42** [comment]
I think here would be the place to do it: https://github.com/composer/getcomposer.org/blob/master/web/installer
Please correct me if I am wrong.

How about adding a param

    --stability=stable

Then ... if `"stable" == $stability` .... get the latest tag from GitHub API and create the `$version` from it.

**Comment by samdark** [comment]
Stable should be default. `--dev` should get master. Of course, there will be less live testing but more stability for end users.

**Comment by schmunk42** [comment]
Just a minor thing, but I'd go with `--stability` instead of `--dev` since the latter get dev-packages on install and update and there are no dev-packages for the composer binary AFAIK.

**Comment by stof** [comment]
@schmkr the composer phar is re-built automatically on each push to the master branch. So there is a dev version of the Phar (it is the one you get whne doing a ``self-update`` currently)

**Comment by schmkr** [comment]
@stof I think you meant to mention @schmunk42 :)

**Comment by stof** [comment]
indeed

**Comment by schmunk42** [comment]
@stof Thanks, good to know.

**Comment by schmunk42** [comment]
I figured out a bash solution using the GitHub API I wanted to share with you...

Install latest version

    curl -sS https://getcomposer.org/installer | php -- --version=$(curl -s https://api.github.com/repos/composer/composer/releases/latest | grep -oP '"tag_name": "\K[^"]+')

Update to latest version

    composer self-update $(curl -s https://api.github.com/repos/composer/composer/releases/latest | grep -oP '"tag_name": "\K[^"]+')

**Comment by alcohol** [comment]
@schmunk42 well that is somewhat misleading, since that will not get you the latest version, but merely the latest release on Github (tag). Since those are currently all alpha's, you can't really consider those stable either.

**Comment by alcohol** [comment]
Mind you, all of those can also be found at the bottom of: https://getcomposer.org/download/

**Comment by schmunk42** [comment]
@alcohol It's primarily about automated or non-interactive installs, such as building Docker images.

> since that will not get you the latest version, but merely the latest release on Github (tag)

I've updated the comment to reflect this detail ;)

There are sometimes bugs in composer, which require you to update **and** there are sometimes bugs, when you update. It's just about the strategy you want to choose.

Maybe in my case the issue would read "ability to use release(s)" - in general; actually exactly the same behavior as available for composer packages, like so:

    curl -sS https://getcomposer.org/installer | php -- --version=@alpha

Which gives you currently

    All settings correct for using Composer
    The defined install version (@alpha) does not match release pattern.

**Comment by alcohol** [comment]
It should be `--version=alpha11`, if you wanted alpha11, for example.

**Comment by schmunk42** [comment]
I don't want `alpha11`, I want **latest** `alpha`, `beta`, `rc` or `stable`.

**Comment by alcohol** [comment]
Ok, fair enough. But this conversation is drifting off-topic, so lets leave it at that.

**Comment by dereuromark** [comment]
+1 for a stable 1.0.0 soon.
