### ISSUE TITLE
Composer run does not work in Windows

### ISSUE THREAD

**Issue by vladkens** [composer/composer#3709]
composer run command does not work in Windows.

    C:\Users\user\app>php composer.phar run
    'Started web server on http://localhost:8888'
    Directory web/ does not exist.
    Script php -S localhost:8888 -t web/ web/index_dev.php handling the run event returned with an error

    [RuntimeException]
    Error Output: Directory web/ does not exist.

    run [--dev] [--no-dev] [args1] ... [argsN]
    
    C:\Users\user\app>php composer.phar --version
    Composer version 1.0-dev (07c644ac229a21df80180598d8bb9aaba232eecb) 2015-02-03 12:51:10
    
    C:\Users\user\app>ls
    LICENSE  README.rst  bin  composer.json  composer.lock  composer.phar  config  phpunit.xml.dist  src  templates  var  vendor  web
    
This bug of php -S command. That run without problems need to write `php -S localhost:8888 -t web`.

**Comment by jakoch** [comment]
Hello Vlad,

i can't reproduce the issue you posted.

You are using `php composer.phar run`. This will execute Composers `run-script` cmd.
But not with the output you posted (starting web server, etc).
Running Composer has nothing to do with how you serve your pages (php -S, nginx, etc.).
You should get "[RuntimeException] Not enough arguments.", because the `run-script` cmd expects a script name to execute, like `php composer.phar run post-update-cmd`.

Regards, Jens

**Comment by slbmeh** [comment]
@jakoch i'm assuming the project he's using has `php -S localhost:8888 -t web/ web/index_dev.php` defined as `run` in the scripts section of `composer.json`, if you run composer then the name of a defined script it will run those scripts for instance:
```json
"scripts": {
  "test": "./vendor/bin/phpunit"
}
```
running `composer test` will execute `./vendor/bin/phpunit`

**Comment by jakoch** [comment]
I have no clue, how you found out that this issue is related to Silex, but... 
Good catch, Steve!

**Steps to reproduce:**
```
1 . Download - https://github.com/silexphp/Silex-Skeleton/archive/master.zip
2. composer update
3. composer run (= composer run-script run)
```

**Bugfix:**
There is just a simple slash fix needed in `composer.json` to get this up and running.
Change 
`"php -S localhost:8888 -t web/ web/index_dev.php"`
to
`"php -S localhost:8888 -t web web/index_dev.php"`
Then you'll get `'Started web server on http://localhost:8888'`.

It's a Silex issue (referencing https://github.com/silexphp/Silex-Skeleton/commit/66aeafd933ec6455b555374867709d0091eb4b0b) - not a Composer issue.

**Comment by slbmeh** [comment]
@jakoch i use aliases for different phpunit configurations so I knew they can act as commands, i changed one to run to see what would happen and my tests ran, so i did a search for `run "Started web server on http://localhost:8888" "php -S localhost:8888 -t web/ web/index_dev.php"` and came up with a `composer.json` as a result verifying my suspicion.

**Comment by vladkens** [comment]
Thanks for the explanation.

**Comment by MostafaEzzelden** [comment]
I think this is working
`"scripts": {
        "phpcs": [
            "vendor\\bin\\php-cs-fixer fix --config=.php_cs --verbose --diff --dry-run"
        ]
    }`
