### ISSUE TITLE
Command to set packagist repository to false

### ISSUE THREAD

**Issue by frvge** [composer/composer#3713]
Hi, I am able to add new repositories from the CLI without a problem, but the syntax to disable Packagist doesn't seem to be supported.

Can a command like:
```
composer config repositories.packagist false
```
be added?

**Comment by alcohol** [comment]
https://getcomposer.org/doc/05-repositories.md#disabling-packagist

**Comment by frvge** [comment]
Thank you, but I'm looking for a command-line command, like the one you can use to easily add a new repository:
```
php composer.phar config repositories.foo vcs http://github.com/foo/bar
```

**Comment by alcohol** [comment]
There isn't one, since disabling packagist isn't normal behaviour. `composer config` can be used to set or unset most configuration values, but it doesn't support false as a repositories value. Disabling packagist should only be done if you understand the consequences and your specific use case really requires it. As such, having to manually edit your composer.json to disable it is more of a precautionary step if anything.

**Comment by GromNaN** [comment]
@alcohol I disagree. On large systems you, relying on packagist or not is a strategic decision. Making all options configurable using composer command is a good design.

**Comment by Seldaek** [comment]
`composer config repo.packagist false` now works.
