### ISSUE TITLE
Plugin triggered after it is being removed

### ISSUE THREAD

**Issue by jbutkus** [composer/composer#3729]
Steps to reproduce:
* add some plugin which hooks to post-update action and uses PSR-4 autoloadable classes to `require` section;
* ensure it's working (`composer update`);
* remove it;
* run `composer update` - the plugin attempts to require some file and a fatal error (file not found) is displayed.

Maybe plugin hooks could be unbound if removal of it is detected?

**Comment by slbmeh** [comment]
What do you do to remove the plugin?

**Comment by jbutkus** [comment]
Edit `composer.json`?

**Comment by slbmeh** [comment]
Ah, so you remove it from the `composer.json` and update.  I can see that being a problem.  The local repository gets built from `composer/installed.json` and the `PluginManager` activates the plugins in the local repository and the plugin manager doesn't have a way to know exactly what the plugin did when it was activated in order to deactivate it.

If you are removing a plugin I suggest calling update with `--no-plugins` as the [plugin documentation](https://getcomposer.org/doc/articles/plugins.md) notes for updating or uninstalling a plugin.

**Comment by jbutkus** [comment]
OK, as it's a known issue (*feature*) - I think it's reasonable to close this one.
Also - composer "heals" itself if you execute `composer update` two times in a row (where first one fails).
