### ISSUE TITLE
Custom composer command times out after 300 seconds

### ISSUE THREAD

**Issue by funkytaco** [composer/composer#3737]
I thought I was doing something that others have probably done (running a custom command to fire up a php server locally) with their composer.json, namely this:

    "scripts": {
        "serve" : "php -S localhost:8000 public/index.php",
    }

I then execute `composer serve` to start a PHP web server for development purposes.

But it times out after 300 seconds with:
 `[Symfony\Component\Process\Exception\ProcessTimedOutException]                             
  The process "php -S localhost:8000 public/index.php" exceeded the timeout of 300 seconds.`

If figuired this would work after reading about [custom commands](https://getcomposer.org/doc/articles/scripts.md#writing-custom-commands) in the documentation. 

I know I can increase the timeout, but is there a way to do it for just this one script? Also, I don't see a way to make it never timeout with `COMPOSER_PROCESS_TIMEOUT`, just a way to increase the number of seconds.

Am I trying to be too clever? Is there a better way? This is basically how I do it with gulp for Angular apps.

**Comment by slbmeh** [comment]
That is passed to `symfony/process`, the value gets cast to float and set to null if it is equal to `0.0` so `COMPOSER_PROCESS_TIMEOUT=0` should disable it entirely.  You can't do it for a script alias command like that, but you might be able to do it with a php script handler on an actual event depending on the args that get passed to the constructor of the event being dispatched.

I was just thinking about this recently because I saw a similar setup in #3709 and I was wondering how they do it in Silex. Or if it just times out frequently.

**Comment by funkytaco** [comment]
You are right about offloading this to a php script handler, as that is what I decided to try. It's actually a better way to do it as I don't have to modify/set `COMPOSER_PROCESS_TIMEOUT`. 

In composer.json:

        "serve" : "Tasks\\DevTasks::startDevelopmentWebServer",

In DevTasks.php
```
        public static function startDevelopmentWebServer($event) {
            $port = 8000;
            echo self::ansiFormat('INFO','Starting webserver on port '. $port);
            echo exec('php -S localhost:'. $port .' public/index.php');
        }
```
You could redirect stdout as well, but I didn't bother. You'll still see the web access log/hits in the console.
