### ISSUE TITLE
Schema proposal, moving php from requirements (and some additional stuff)

### ISSUE THREAD

**Issue by mormy** [composer/composer#3762]
Hi, 

I have had a discussion with some colleagues and basically the point is this... System libraries and PHP version shouldn't be specified under "requirements" ... It's very confusing for beginners to differentiate between system libs and project components this way. 

Therefore I propose a new element to be added to the schema. Example below... This is only a proposal and I'd appreciate any input.

```json
{
  "name": "ACMEProject",
  "description" : "Some ACME corp project",
  "minimum-stability": "dev",
  "php-version": ">=5.4.0", 
  "platform": { 
    "php-ext": { 
      "ext-gd": "*",
      "ext-pgsql": "*"
    },
    "libs": {
      "external-deps-for-php-ext" : "*"
    },
    "services": {
      "postgresql": "*",
      "nginx": "*",
      "php-fpm": "*" 
    },    
  },
  "require": {
      "php": ">=5.4.0",
      "silex/silex": "1.0.*",
      "doctrine/dbal": "2.2.*",
      "monolog/monolog": ">=1.0.0"
  },
  "autoload": {
      "psr-0": {
        "ACME": "src/"
      }
   }
}
```
This way the project and it's requirements, could be made much more clear. It's probably not a perfect proposal, or the best thought out scheme (maybe it's better suited for the config object), but IMO, describing the whole sw/libs requirements for running the composer package is great. 

P.S. php version is mentioned in two places... Backward compatibiltiy, easily removed/renamed :)

**Comment by RQuadling** [comment]
For this behaviour, I think it would be important to not upgrade anything if the platform requirements cannot be met as I doubt composer will ever be capable of upgrading PHP and the various extensions and their lib files on all platforms.

**Comment by mormy** [comment]
@RQuadling that too ofc... 

The changes proposed would be useful during automation via Puppet (or other, similar tools) ... when you download the project/library with this type of schema, it can check if the valid versions of libraries/php are installed, and if not, install them prior to running composer install/update... 

I don't know if it'd be widely used, but I'm willing to write a puppet module and put up an example dev-env setup with this kind of schema...

**Comment by RQuadling** [comment]
Some thinking out louds ...

Isn't this really a Puppet (or equiv) issue? ... but because composer is going to also be used to install the package dependencies, having the platform requirements in the same place would seem quite useful, even if all it did was block composer if things failed to match.

What about versioning of the extensions? Not all extension (AFAICR) have versioning (thinking of windows hosts that will be using pre-built binaries and not building from source). ... there again the extension would fail to load if incorrect for the version of PHP (ABI number) ... so that works.

Now if only I could get vagrant to run on Windows as easily as I can on my Mac ...!

**Comment by mormy** [comment]
Well, it is a orchestration issue and it's not an orchestration issue... Depending on your point of view ofc :P 

I think this is a composer issue because you have to have some specification on what to have on the system to run the particular composer package you have installed. It's only logical to put it in the composer.json file and tell puppet (or Chef, or Ansible or a batch script), pull the package from where-ever, check out it's dependecies, install them, then run composer install on the package. 

An alternative would be to put a requirements.json besides composer.json, but I really don't see the point when 1 file would do.

**Comment by slbmeh** [comment]
@mormy I do something similar with a chef recipe for php application deployments. I look for patterns described in the [libraries](https://getcomposer.org/doc/02-libraries.md) section of the docs describing platform packages to get dependencies to install. It would be convenient to have them in a separate section to be easier to obtain, but they would really only be useful on the root package as not having a platform package isn't always a deal breaker because of potential alternatives.

AFAIK the solver can really only tell you everything you are missing if it can solve your dependency constraints, and that would only occur if you aren't missing anything.

You could easily put all of your extension, package, and library dependencies in a section somewhere within extra on your root package and have your tool parse that to install packages composer can't handle.  I do it in a custom installer for bower packages already.

Thinking aloud after reading this, you could possibly write an installer for an external package manager like apt, homebrew, linuxbrew, php-build, etc to install your dependencies.  The caveat being that if you install a PHP version as a dependency you may need to fork the process to the newly installed version of php for certain packages to work properly such as composer plugins and scripts.

**Comment by mormy** [comment]
@slbmeh I don't propose that Composer does any kind of installing... That would be up to tools like Puppet/Chef/Ansible/Juju/whatever ... 

I just want to have a dedicated section for requirements (and possibly suggestions, extra pkgs/libs that could be of use but are not necessary) ... This php ver, this mysql ver, these php extensions.

**Comment by slbmeh** [comment]
@mormy right, I apologize, I went off topic a bit. I have somewhat of an addiction to writing installers/plugins for composer. I would definitely welcome a separation of platform requirements from package requirements. And the addition of supported services is an interesting concept.

My main point was that the schema already supports adding arbitrary metadata in the `extra` section. I do something very similar to what you describe with the existing schema. I get the libraries and extensions from the `require` section and add other information I might need in the context of chef in my case to the `extra` section.

**Comment by mormy** [comment]
Yeah, I know about the `extra` section, but I really don't think `requirements` should be in that section. `extra` imho is just for adding anything that could be useful but not needed for full requirements. 

I'll try to fork it over the weekend and hack something together... As an example

**Comment by pierrejoye** [comment]
I like this idea. It will also drop some of the pain points with pickle integration while allowing multiple PHP/projects installs with some extra work.

**Comment by pierrejoye** [comment]
@rquadling extensions version are solved with pickle.

**Comment by Seldaek** [comment]
I don't really see what problem this is fixing. @pierrejoye can you be more specific how it would help?

If php and exts are requirements they belong in the require IMO. Having the mysql version and whatever is going a bit further than composer's dependency management goal.. And splitting it out of require would just break things (just as an example, heroku and others build the environment according to what's in require) for not much benefit (you mentioned confused people but it's the first time I hear of that and I don't really see how `php` or `ext-pdo` are confusing, they would still be confusing if somewhere else in the file IMO).
