### ISSUE TITLE
Totally sysadmin and guest OS unfriendly: no info on fail

### ISSUE THREAD

**Issue by mariotti** [composer/composer#3770]
It is a couple of days I am trying to install a package with composer.

And honestly it is the least sysadmin "user friendly" I ever had.

From messages like:
GD not "present/installed" (please forgive my memory right now). If you are able to know what is GD good for you.

To:
  Problem 1
    - doctrine/mongodb 1.1.7 requires ext-mongo >=1.2.12,<1.7-dev -> the requested PHP extension mongo is missing from your system.

Like if I would know what is ext-mongo; here as sysadmin on an actual *nix OS. I know mongo, I know php but honestly ext-mongo is not in any package in my OS.

Given the fact that one solution was, run: php ../composer.phar diagnose
And of course the response was:
Checking composer version: FAIL
You are not running the latest version
$

With no information about updating it ... 

The actual issue is that it looks like it gives no information about the actual system, but seems to be leaving in its own glass cage without external communication.

Again it is 2 days I am trying to install a php code on centos which was supposed to be for ubuntu. I got all library dependencies, except the composer part which is still complaining. I would put it as main issue. Right now I am a sysadmin (old php coder), but I would just disqualify apps using composer, as, I will not be able to install them!

This would be very sad as I am a fan of php.

**Comment by mariotti** [comment]
If in case, a specific case is required.
I try to install: http://www.akeneo.com/
On CentoOS 6

Before "composer" there are other problems to solve, so in case you want to do the same, just drop a line ;)

**Comment by GromNaN** [comment]
Both GD and ext-mongo are PHP extensions. You can install them with a PECL.

**Comment by slbmeh** [comment]
All of the dependencies will be PHP related either a package somewhere or an extension is needed. The lib style packages are generally dev packages for the extensions or php itself to be compiled with.

Composer diagnose is for detecting common configuration problems.

The glass cage you speak of is the platform repository. You can see what is present in there with `composer show --platform`.

There is a lot of information in the documentation, but there being a lot makes some things easy to miss.  The libraries section covers the `lib-*` and `ext-*` style packages.  If it says `GD` that's probably not great.

All that being said, I could see those being commonly overlooked areas... I assume developers are more likely to scan `schema` and `repositories` and sysadmins would scan `Download` and maybe `Getting Started`...

I myself don't read or write documentation, if I'm curious about what something means or how something works I ack the code for a section of an output message.  So I can't be of much input on your remarks about it being user friendly.

**Comment by mariotti** [comment]
ok. my point of view that the OS has usually already a package manager. CentOS has for example RPM. In this case I prefer to install rpm packages as much as possible then eventually move on specific needs. Some requirement can be a match, for example php-soap.x86_64 I assume will give ext-soap in composer. But in case of no matching it makes things a bit a complicated ...

In this sense might be useful to have a minimum of OS integration, I mean minimum can simply be to list packages which might be in the OS or even simply: try install using "pecl install <package>" if pecl is available, eventually with some dependency information.

I understand that of course reading the docs might always help, but often when you install a lot of different software, packages, it is a bit difficult to read the docs for everything ;)

**Comment by alcohol** [comment]
I'm sorry, but any sysadmin would tell you to `RTFM`. So.. :>

**Comment by mariotti** [comment]
I'm sorry, today: rtfd.org points to: https://readthedocs.org/ A more polite way.
@alcohol I do read the docs.

Now, I act as sysadmin for development systems.  So I need to give freedom, but trying to keep it under control. Which also means telling to developers (by limiting it) on which platform they can run. Otherwise each developer has its "home" configuration.

Given that we have pecl and rpm, I do understand now that the problem is not composer but the application. As probably they have a way to package the application using composer, indeed, which might not necessarily relay on the details of the OS (ok some still, I guess).

So I would revert the issue into "educating" the application packagers to create OS friendly apps.
Or to mark the projects as "alpha" (or the like) development as the portability of composer tools themselves is simply compromised. I.e. a not installable package.

As indeed, as sysadmin, I might not need to rtfd if the developer gives me the right requirements.

Cheers.

**Comment by mariotti** [comment]
I forgot a note. It would be perfect if composer could work fully in the user space. But I guess for this you might need also pecl to work in the user space...
But in the era of cloud, containers and the like, it might be a nice way to go.

**Comment by slbmeh** [comment]
Composer is intended to manage the source code dependencies. Although, it is possible to install the platform dependencies, I don't believe that will ever be a part of composer. As you mentioned many platforms have their own installer and some individuals may prefer to have the platform package installed rather than the pecl version, however a distro generally won't have a system package for every pecl package.

Working in userspace is something I've been playing around with as far as composer plugins go, but there's a lot of work and consideration that needs to be done down that road.

I believe the issue is more in the documentation of the package you are being told to install. I would never hand off a tarball of source to my sysadmin and expect him to just "make it work". Sysadmin do have some sort of voodoo magic at their disposal, but there is no way for them to know what kind of platform I intended the application to run on unless I express that information. Their test suite is likely built around some sort of system, that is likely a good start for them to compare versions from.

Being a developer in a sysadmin role is a unique position and is a great opportunity to educate developers. Holding that position in the past I've asked developers in charge of the application releases to document the dependencies with justification. E.g. "This application needs GD because of the captcha library we are using". Then system packages that were installed simply to satisfy a dependency can be removed when that dependency is non-existent. Developers often have a mindset of "pick any library that solves our problem" because they've never experienced dependency management hell.

Most often in my experience the application team is responsible for administration of their development environments in some form such as vagrant or docker to have some version controlled script that can express the exact environment configuration. This easily get an overall view of what is needed to run the application.

**Comment by mariotti** [comment]
Cant agree more. Thanks for putting in a better form some of my doubt and adding some missing bits too ;)

I think my main issue was, citing:
"I believe the issue is more in the documentation of the package you are being told to install. "
and this says most of the problem.

I would not mind to discuss, but I am not sure if this is the right place.

From your post indeed I would get a couple of lines for this post:
"Composer is intended to manage the source code dependencies."
"Working in userspace is something .... "

Cheers
F

**Comment by mariotti** [comment]
Okey dokey.. some random notes.

Maven downloads a full set of jars in my home (and also any place where you run it) at ~/.m2 with all the versions. It is somewhat platform independent, being java, but I have all possible versions on the filesystem. It is platform independent if you get the right jar.

But it has a bit: I can make a kinda package, if I am skilled enough, like a war file or the like.

ant: I am not really an expert on it. But should not be that far from maven.

Python, I know it in details for computing, not web, except Django. Yet I know I can install user space
modules, as I had to install it on a public server. Just define the modules directory.

These are the "modern" things.

Make: this is my preferred tool. It simply "make" what you ask it to do (with dependencies).

configure and the auto tools: just perfect.
The funny thing is this:
If you run composer and it asks for: ext-mongo
Then you run pecl: pecl install mongo.X.Y.Z.gz
Which in turn runs: configure!
in your /tmp directory..

Ok, at least for what concern *nix systems.

Can we learn from these?

**Comment by slbmeh** [comment]
I would like to discuss as well, I'm not sure this is the right place for the conversation.  It isn't a common use case for the mainstream composer audience.  I created a new repository and an issue to continue discussion there if you would like. slbmeh/composer-platform-installer#2

**Comment by jakoch** [comment]
Sidenote:
The installation of PHP extensions via Composer will be adressed by Pickle.
https://github.com/FriendsOfPHP/pickle its already usable to install or compile missing extensions.
Integration with Composer is work in progress.

**Comment by Seldaek** [comment]
I made the messages you mentioned hopefully a bit more clear, not sure what else I can do in the short term. Longer term hopefully pickle will provide a way for us to install extensions without confusing the user too much.
