### ISSUE TITLE
using a fork in a sub-project

### ISSUE THREAD

**Issue by justechn** [composer/composer#3780]
I have a project we will call project1 which has a composer file that looks like

```
{
    "name": "is/project1",
    "description": "project1",
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/simpleweb/php-resque-scheduler"
        }
    ],
    "require": {
        "chrisboulton/php-resque-scheduler": "dev-master"
    }
}
```

I have another project called project 2 which has a composer file that looks like

```
{
    "name": "is/project2",
    "description": "project2",
    "require": {
        "is/project1": "dev-master"
    }
}
```

in project1 it correctly pulls in the simpleweb fork of php-resque-scheduler, but in project 2 it pulls in the base project.

Can someone tell me what I am doing wrong?

**Comment by slbmeh** [comment]
Repositories are only applied to the root package. You would need to add the repository in the `composer.json` of each package you want to use it in. If you want to add that repository globally you can add it to your composer configuration.

**Comment by ryanmc2033** [comment]
Thank you for the reply. While I understand that this is currently the way it works it doesn't seem to follow the normal pattern of inheritance used by composer. Everything else in composer trickles up the chain unless overridden further up, for example tags, so why doesn't this? 

This also makes it really hard for anyone else in my company to use this package because they will have to add the same repository to all their packages. It would be great if we could get this changed.

Thanks

**Comment by slbmeh** [comment]
There are a number of things that are root package only for security concerns. Most of the config options are this way.

Consider this: you have a project that depends on one of my packages. I depend on a package that is critical to your application. I happen to make a fork to introduce a new feature and accidentally tag a release with the repository in my composer.json. You happen to update your package and get my fork that is potentially broken and definitely not what you were expecting when you defined your package dependency.

See also https://getcomposer.org/doc/faqs/why-can't-composer-load-repositories-recursively.md

Another reason is the performance of the solver would be drastically degraded if among all of the packages on packagist were scattered about dependencies declared in ad-hoc vcs repositories because each vcs repository would need to be checked out to scan all potential version.

**Comment by slbmeh** [comment]
If you add it to your global configuration you only need it in one location. If it is going to be a long term fork you should consider setting up a private repository like satis, toran, or packagist. It isn't too difficult to create a packages.json by hand either to put in some hosting space so you can reference it in your configuration as a composer repository.

**Comment by TCB13** [comment]
So... I'm running on the exact same issue here. I agree with @ryanmc2033 , this should be changed. It's just a pain when you've custom forks (that will eventually end as master, but will take time) and you need to use them on a package used by another package...

**Comment by slbmeh** [comment]
@TCB13 that's what inline aliasing solves

**Comment by Seldaek** [comment]
We already have things in place to deal with this (as per the docs linked above) so I am closing. There is really nothing we can do to improve this further.
