### ISSUE TITLE
Add no cache option to install, update, and require

### ISSUE THREAD

**Issue by slbmeh** [composer/composer#3781]
Often times in my workflow I update a dependency and want to update immediately. This isn't always possible because of the cache. Clearing the cache may be cumbersome if there are many repositories configured. If one knows the internals of the repository classes and the cache mechanism they can delete the individual file. This may be troublesome if there is a long list of packages to ignore the cache for.

I want to be able to require, install, or update and ignore the cache for that particular run. A `--no-cache` option would be nice to have. This would allow things like `composer update --no-cache vendor/package1 vendor/package2` disabling the cache for that particular run. It may be more desirable to rather than disable the cache for that run, treat the cache as stale allowing the cache to be forcefully updated as well.

**Comment by stof** [comment]
AFAIK, the cache is not preventing to see updates. The cache is mostly about caching downloads.

Your issue is most probably related to a delay on the Packagist side between the time you push a commit to the repo and the time it appears in the Packagist data. A ``--no-cache`` option would not be able to change this.

**Comment by slbmeh** [comment]
You're right. I wrongly assumed that `fetchFile` consulted the cache first, it just uses the cache key to write the cache.  So this option would only be useful for third party repositories.
