### ISSUE TITLE
Cannot parse version properly - 5.5.16-1+deb.sury.org~precise+1

### ISSUE THREAD

**Issue by mszterlingfsite** [composer/composer#3801]
Magento2 is using Composer/Package/Version/VersionParser.php to parse php version and it fails on 
5.5.16-1+deb.sury.org~precise+1

I believe they use version alpha-8

https://github.com/magento/magento2/issues/1066

**Comment by Seldaek** [comment]
The latest version has support for the +metadata part but the `-1` is nonsensical and I think we still don't support that. You can find here what we do to extract the PHP version reliably since so many linux distros use funky versioning schemes.. https://github.com/composer/composer/blob/master/src/Composer/Repository/PlatformRepository.php#L38-44

**Comment by buskamuza** [comment]
Hi @Seldaek , shouldn't this part be included directly in `\Composer\Package\Version\VersionParser::normalize()`? Is there a reason to not do it?
With current implementation, all we can do is to copy the lines you pointed to. And as soon as you modify them (e.g., fix some another bug), we'll have to do the same.

Thanks.

**Comment by Seldaek** [comment]
@buskamuza I understand but the issue is it's only applicable to PHP version IMO, I wouldn't want to allow all other package versions to be full of useless garbage. We have to support it for PHP versions because the distros are doing it already so we have to play well with the existing ecosystem.

**Comment by buskamuza** [comment]
@Seldaek , makes sense. Thanks for the reply.
