### ISSUE TITLE
Composer is not re-using existing github oauth keys

### ISSUE THREAD

**Issue by Vhab** [composer/composer#3855]
`Composer version 1.0-dev (829199c0530ea131262c804924f921447c71d4e8) 2015-03-16 13:11:02`

At each run of `composer update` I get asked for credentials for our private repository.
As result my GitHub account is filling up with tokens like:

Composer on development [20150319163903]
Composer on development [20150319163759]
Composer on development [20150319163657]
Composer on development [20150319163516]

It should be noted, we also have an oauth token set our composer.json for CI. Which is a token for a different account.

Might there be some clash between the token set in composer.json, the globally set the token?

**Comment by stof** [comment]
there may be a clash indeed. You should try storing the CI oauth token in the global config on your CI server instead of putting it in the composer.json of the project.
Thus, storing an oauth token in the project git repository is a very bad idea. It means you are leaking your github credentials in thr git history. So I strongly suggest you to revoke this oauth token and use a different one when switching to a config stored on the CI server.

**Comment by Vhab** [comment]
The way it's setup is due to how the hosted solution we use works.

It isn't ideal, but we have no control to use a different method.

On Sun, Jun 7, 2015 at 9:58 AM, Christophe Coevoet <notifications@github.com

**Comment by stof** [comment]
Couldn't you run a command ``composer config -g github-oauth.github.com <oauthtoken>`` in your CI setup instead, before the composer run ?
