### ISSUE TITLE
Composer update with alpha9

### ISSUE THREAD

**Issue by snapshotpl** [composer/composer#3877]
Hi there!
We use last "stable" version of composer (currently alpha9). Yesterday Zend Framework team released RC3 with Caret Operator in composer.json. We created issue https://github.com/zendframework/zf2/pull/7369 and @weierophinney immediately create new RC. However it didn't help. File `$HOME/.composer/cache/repo/https---packagist.org/provider-zendframework$zendframework.json` still contains dash and `composer update` doesn't work. We recommended to ZF to remove affected RC, but we afraid that any other project can start using caret operator. We think that help for that is release new alpha.

**Comment by weierophinney** [comment]
@snapshotpl Perform a `rm -rf $HOME/.composer/cache` to fix the immediate problem. I agree, however, that it would be nice to get the caret iterator in a stable composer release.

**Comment by snapshotpl** [comment]
@weierophinney I tried this. It doesn't help. `provider-zendframework$zendframework.json` sill contains caret and composer try to parse it.

**Comment by hairmare** [comment]
The lacking support for the caret operator has been cropping up all over the place in the last couple of weeks.

See for instance #3779 where this was first reported or cloudfoundry/php-buildpack#47 where updating to the latest composer release during deploy has been added as a hacky workaround.

The only reason this is not affecting a larger portion of composers users is due to the fact that https://getcomposer.org makes users install an untagged version of composer from master. AFAIK this is also the reason why people are using unreleased features without noticing.

As stated in #3779 it would really help if composer devs would commit doing at least somewhat regular alpha releases until we reach a stable 1.x release.

**Comment by Seldaek** [comment]
new version is out
