### ISSUE TITLE
Require command unable to detect latest stable

### ISSUE THREAD

**Issue by stevelacey** [composer/composer#3900]
Composer seems to be unable to detect the latest stable release when running:

```sh
composer require beberlei/DoctrineExtensions
```

But the following does work:

```sh
composer require beberlei/DoctrineExtensions "~1.0"
```

Packagist and other services seems seem happy that `1.0.1` is the latest stable, but the require command isn't happy? Wondering if it's to do with the `v` tag prefix?

https://github.com/beberlei/DoctrineExtensions/issues/145

**Comment by jakoch** [comment]
Hey Steve! 

I would suggest fixing the branch alias in the composer.json of that package.
```
{
    "extra": {
        "branch-alias": {
            "dev-master": "1.0.x-dev"
        }
    }
}
```
The `.x` part is needed to resolve the 1.0.1 branch.

**Comment by alcohol** [comment]
Found out why; [this line](https://github.com/composer/composer/blob/master/src/Composer/Repository/ComposerRepository.php#L274) returns false, because the array index of `providerListing` is lowercased while `$name` is not.

@Seldaek can you confirm that the `providerListing` array **always** has lowercase indexes, and if so, if a simple `strtolower` on `$name` would be a sufficient enough approach to tackle this issue?

**Comment by stof** [comment]
composer package names are always lowercased. ``ComposerRepository->whatProvides()`` is fine if it expects receiving a lowercase name already (doing a lowercase each time would impact the performance of the solver, which calls this method many times with names being lowercase already). the require command should be fixed to lowercase the argument

**Comment by alcohol** [comment]
I'll get right on that.
