### ISSUE TITLE
Faster loading with include_once?

### ISSUE THREAD

**Issue by VeeeneX** [composer/composer#3941]
I've been browsing code and I found that there is a function for including file, concurrent function uses `include`. As we all know `include` can include file many times. E.g you're using the same trait in multiple classes and can lead into deceleration of performance. Instead of using `include` we can use `include_once`.

```php
// ClassLoader.php
/**
 * Scope isolated include.
 *
 * Prevents access to $this/self from included files.
 */
function includeFile($file)
{
    include_once $file;
}
```

**Comment by GromNaN** [comment]
Even if we use `include`, he same file is never executed 2 times:
- In PHP you cannot register the same class / trait / interface / function more that 1 time
- The autoload mechanism is called for each class that is not already declared. Then when you re-use a class, PHP already know it and don't run the autoloader for this class.

**Comment by slbmeh** [comment]
The `*_once` variations are more expensive operations because of the overhead of negotiating a lookup table. It's actually more efficient to define a constant for a file and check to see if the constant is defined. Either way, as GromNaN said, it can't be called more than once. It technically can if you have a typo in what you are trying to autoload, but you will get an error from defining something more than once. Preventing that error doesn't serve much to gain, you would still get an error, just that the item you tried to call doesn't exist.
