### ISSUE TITLE
Composer installer causes PHP error "CLI has stopped working"

### ISSUE THREAD

**Issue by pete01** [composer/composer#3971]
I have an issue instlaling Comnposer.

Running php 5.6.8 (latest) on Windows 7 with opcache and xdebug 2.3.2 (latest) enabled. When I try to install composer I get a "CLI has stopped working" error.

The composer installer command I'm using is straight from the composer getting started docs.

    php -r "readfile('https://getcomposer.org/installer');" | php

Here are the details of the "CLI has stopped working" error from Windows:

> Problem signature:
>    Problem Event Name: APPCRASH
>    Application Name: php.exe
>    Application Version: 5.6.8.0
>    Application Timestamp: 552ee168
>    Fault Module Name: php_opcache.dll
>    Fault Module Version: 5.6.8.0
>    Fault Module Timestamp: 552ee392
>    Exception Code: c0000005
>    Exception Offset: 00006cec
>    OS Version: 6.1.7601.2.1.0.256.48
>    Locale ID: 2057
>    Additional Information 1: 0a9e
>    Additional Information 2: 0a9e372d3b4ad19135b953a78882e789
>    Additional Information 3: 0a9e
>    Additional Information 4: 0a9e372d3b4ad19135b953a78882e789

This indicates the opcache is causing the problem, but it seems like a problem with having both opcache and xdebug enabled, as if I turn either of these extensions off the composer installer command works fine.

I've also found that Composer will still install when both opcache and xdebug are enabled, but only when not using the pipe command, e.g.

    php -r "readfile('https://getcomposer.org/installer');" > composerinstaller.php
    php composerinstaller.php

Maybe someone knows what is happening and can explain?

**Comment by pborreli** [comment]
could you try : ```php -r "readfile('http://getcomposer.org/installer');" | php```
with http

**Comment by pete01** [comment]
same error appears, PHP CLI has stopped working

**Comment by pete01** [comment]
If I try even this `php -r "" | php` php crashes with "CLI has stopped working"

I will close this as its obviously not a problem with the Composer installer

**Comment by pete01** [comment]
OK, I think I've traced this to actually having opcache enabled on the CLI (this `opcache.enable_cli=1`).  When I turn this off (which is default), then the Composer installer command works.

**Comment by amelkikh** [comment]
:+1: opcache.enable_cli=1

**Comment by remotedman** [comment]
Yeah, symphony screwed up my zip file program written in php which I run using a .bat file on windows.   I run a backup everyday and I kept getting the cli message. Then I was getting error messages from my archive.  and I was able to trace any new programs I installed from where I started getting errors and it was when I installed symphony which I later removed.  I did a little research and its definitely a dll of some type was changed. Visual studio debugger was telling me that pdb symbol file was missing and suggested that I should use Microsoft symbols.  didnt help,  I did not want to upgrade my php version because its tied to apache server and I did not want to shut down and reconfigure.  just not worth it at this time,   Especially since the error seems to cover only one program.  So I changed Zip Archive to PharData tar.gz files and no more errors.  My hypothesis is that Zip Archive module shares dll file(s) that symphony overwrites.  I am satisfied with the solution at this point.  but there could be other modules that could be effected.
