### ISSUE TITLE
composer install --no-dev : still install dev package from lock file

### ISSUE THREAD

**Issue by Rebolon** [composer/composer#3981]
We are trying to deploy in production our symfony2 application.
We have one package in the require-dev section.
In dev we usually do "composer install" which install all packages (normal use case).
In prod we are doing this : 
 composer install --no-dev -o -n

But in fact it also install dev package from lock file. It's like the --no-dev parameter was ignored. The only solution we found was to set an environment var :+1: 
 export symfony_env=prod

And that way composer only install standard package.
So why i have to do that ? --no-dev should do the job

**Comment by Seldaek** [comment]
The issue seems to be that the sensio/generator-bundle is always added in your kernel in dev environment, and the post-install-cmd hooks from symfony load the kernel in dev env by default and it crashes.

I guess setting the symfony_env is the only way to bypass that.. but that sounds like a bit of a mess. Ping @fabpot
