### ISSUE TITLE
Incompatibility with Symfony 2.3

### ISSUE THREAD

**Issue by rgrebenchuk** [composer/composer#4028]
You upgraded the dependency symfony/console to ~2.5. Therefore, users of the 2.3 cannot use this bundle. Tagged Alpha9 is incompatibility with ^ operator.  Is there chance to tag new version (patch) compatible with 2.3 and ^ ?

**Comment by slbmeh** [comment]
There is an alpha10

**Comment by rgrebenchuk** [comment]
alpha10 requires "symfony/console : ~2.5"

**Comment by slbmeh** [comment]
Yes. What is the issue?

The version of the symfony components required by composer shouldn't have anything to do with versions of symfony components of your application.

**Comment by padraic** [comment]
It can have an impact where Composer is a dependency, however. It's sometimes used that way though I don't agree with the practice. At the end of the day, Symfony does have versions beyond 2.3, so one needs to live with the fact that the whole ecosystem is not going to remain frozen at 2.3 simply because it's a LTS version.

**Comment by DimaSoroka** [comment]
let me as a few questions related to this issue:
- do you have any release/support policy in place so other applications could rely on this component in some stable way (for example, what will be a right way to contribute the fix to Alpha9)?
- do you have any plans to release stable version of composer component with any time soon?

**Comment by alcohol** [comment]
1. Not to my knowledge. Since they are alpha's, and there is not even a release branch for 1.x yet, there is no clean way to provide any patches on top of those candidates.
2. Soon(tm). Honestly though, I really don't know when a stable release branch can be setup.

/cc @Seldaek maybe a roadmap or something ought to be discussed, to see what needs to be done before a stable release branch can be setup. I imagine at least most if not all (urgent) bugs should be resolved. Feature wise no idea though.

**Comment by Seldaek** [comment]
See #4960 for some notes on stability stuff.. short story is yes it's coming. As for our dependencies though we try to remain as low as possible but sometimes we need new features. I think we'll get stuck for a while now though as symfony 3 is out and we can't upgrade to it without dropping 5.3.
