### ISSUE TITLE
Pass entire $package object to InstallerInterface.php::supports()

### ISSUE THREAD

**Issue by davidbarratt** [composer/composer#4058]
Sometimes (like in davidbarratt/custom-installer#6) it's necessary to use something more than `type` when determining where to install a package.

This should be a simple fix by changing `InstallationManager::getInstallPath()` to accept/pass the entire `$package` object and then any installer can get the type by using `$package->getType()`.

**Comment by davidbarratt** [comment]
This issue is resolved by #4059

**Comment by nevvermind** [comment]
a) Wouldn't this make `$package` exposed to change from various installers? Like `$package->setId()`? Maybe you should use a read-only representation of `$package`.

b) If I get this right, your code is not BC. Maybe it should. You're breaking every installer out there. Maybe this grants another interface, installers explicitly declaring that they provide a `supports(Package $package)` method, otherwise, the old way of passing the type is applied.

What do you think?
