### ISSUE TITLE
Adding vendor\bin to path

### ISSUE THREAD

**Issue by salarmehr** [composer/composer#4072]
Windows install does not add `vendor\bin` path to system path variables automatically.

**Comment by alcohol** [comment]
Neither does Linux..?

Can you elaborate a bit further on the specifics of the scenario? Where **does** this happen (I assume something has given you the idea that composer does this)?

The only scenario I can think of is when running scripts (script definitions can refer to binaries that are located in vendor/bin without having to specify the full path to them).

**Comment by salarmehr** [comment]
Yes, I mean when a global script is executable (phpunit, robo, rocketeer, etc.). Similar to bower -g packages (less, bower, etc.).

**Comment by alcohol** [comment]
I'm sorry, do you mean you installed some packages using `composer global install` ?

**Comment by salarmehr** [comment]
Yes. For example by running: `composer global require codegyre/robo` I expect `robo` command be accessible globally. But have to add that path to system path manually. It is not hard. However, it is better that this be done by composer installer itself. (as npg do for node.js)

**Comment by alcohol** [comment]
Composer doesn't do this though. Neither on Linux. I disagree that composer should do this automatically by the way. Automatically altering environment variables such as `PATH` is not acceptable behaviour for a binary application.

You will manually have to add `~/.composer/vendor/bin` to your `PATH` (though I have no idea what the path and variable are on Windows).

**Comment by alcohol** [comment]
The way node achieves this by the way is by automatically installing binaries in {prefix}/bin, which is usually something like /usr/local/bin, which is in `PATH` by default on most *nix systems. It requires sudo privileges for this though. You can achieve the same with composer on Linux by having a composer.json as such:

```
{
  "require": { ... your requires here ... },
  "config": {
    "bin-dir": "/usr/local/bin"
  }
}
```

Put this in `/opt/composer-global/composer.json` for example and then run `sudo composer install` in that directory.

**Comment by salarmehr** [comment]
@alcohol I did not convinced. If that works for `gem`, `npm` and `pip`, it is can be OK for composer as well.

**Comment by alcohol** [comment]
@salarmehr I think you misunderstand what I am saying. I am saying that __global__ in composer does something different from what you expect it to do. We are not going to change what __global__ does just because you feel that it should be the same as npm, pip, etc.

**Comment by killua99** [comment]
What if I did the installation in this way?.

curl -sS https://getcomposer.org/installer | php
mv composer.phar /usr/local/bin/

Then when I ran sudo composer global squizlabs/php_codesniffer the output is.

```
Changed current directory to /root/.composer
Using version ^2.5 for squizlabs/php_codesniffer
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing squizlabs/php_codesniffer (2.5.1)
    Downloading: 100%         

Writing lock file
Generating autoload files

```
So I need to write inside the root where the bin folder will be? I vote for this should be handle in a better way for composer.

"Composer is a tool for dependency management in PHP." Well it should cover this kind of features.

**Comment by alcohol** [comment]
@killua99 Composer is not meant to manage your `$PATH`. So no, it "should" not cover this feature.

**Comment by killua99** [comment]
I could not disagree more with you because I know how hard is keep any OpenSource tool.

If Composer is a tool to manage dependencies and it has an option for global installation the common thought is it should manage my PATH for "global installations" or maybe I've something from with the mean Global Installation. I don't wanna sound like a rude people I'm saying this with no harm at all and keep a normal tone.

Just think about it, if composer came with that option for global installation it should handle the PATH to provide global installation, otherwise it should be removed the "global installation".

In other any kind of dependency management tool when they gave you that option they care to optimize you PATH when you execute a global installation.

Isn't hard to add a command "composer setup-init" to write on your .bashrc (in *nix system) to add ~/.composer/vendor/bin to your `echo "export PATH=$PATH:$HOME/.composer/vendor/bin" >> ~/.bashrc`

And then you cover the functionality "global" for that user.
