### ISSUE TITLE
There isn't a (well documented) way to only select some extensions or modules in a run

### ISSUE THREAD

**Issue by hexmode** [composer/composer#4109]
MediaWiki doesn't use Composer for extensions because a common use case is a WikiFarm.  On a WikiFarm, some wikis will want particular extensions installed with a particular configuration, but other wikis should not have the extension enabled at all.

When a web request is made, the wiki is determined and then extensions are enabled and configured.

Would it be possible to use Composer to install extensions without automatically enabling them for all uses of the the code base?

**Comment by hexmode** [comment]
Assuming that this doesn't exist and isn't on the roadmap for Composer, would it be reasonable to use parts of composer to enable this behaviour or should we consider Composer a monolithic, purpose-built system?

**Comment by alcohol** [comment]
Your story doesn't really explain much about what the difference is between an installed extension or an enabled extension. I remember having a chat about wiki farms a while ago with someone on irc. It all comes down to this being a particular scenario that composer simply was not made to cover. It's a matter of deployment, not dependency management.

**Comment by hexmode** [comment]
"installed" -- files (and any dependencies) are in the file system.

"enabled" -- MediaWiki is set up to load files (and any dependencies) for a particular wiki..

Separating these two is essential for a WikiFarm.

Suppose a wiki farm (say, Zoopedia) runs all their wikis off the same code base, but don't want to have the HitCounters extension enabled on every wiki.

The first thing Zoopedia wants to do is install HitCounters.  There aren't currently any dependencies, but let's imagine that there is one (the Counts extension).  We could do this today with Composer and since Composer knows about dependencies, it would install Counts, as well.

At this point, HitCounters and Counts are available to all wikis running on their wiki farm.  Suppose, though, that HitCounters adds a 1s delay to every page request where it is enabled and that a wiki (CamelWiki) wants to use Google Analytics in order to avoid that delay, and doesn't want to use HitCounters at all.

To accomplish this today, we would have to install HitCounters manually (without Composer) and then check, at run time, to see if the wiki in the request is CamelWiki, and, if it isn't, enable HitCounters.

We'd like a way to de-couple installation (putting files on the disk) from enabling (making functionality available only if it is desired).  Composer looks like it could really help wit this if we can figure out how to do it.

**Comment by cicalese** [comment]
> Your story doesn't really explain much about what the difference is between an installed extension or an enabled extension

Here is a scenario that illustrates the end goal.

Wikis A and B exist in a wiki farm: they both share the same extension directory, so all of the extensions required by both wikis (and all of the extensions that those extensions depend upon, and so on) must be *installed* in that extension directory. 

Let's consider an extension X that depends upon extension Y. When extension X is installed by composer, dependency information for extension X is consulted, and, therefore, extension Y is automatically installed as well.

Wiki A needs to load extension X (and thus extension Y). Wiki B, however, does not want to load extension X (perhaps extension X slows down page loading, so you only want to load it if it is necessary).

What follows is one way to achieve the desired behavior: there is a global configuration file for the wiki farm that *enables* all of the extensions that are required by all wikis on the wiki farm. In addition, there is a per-wiki configuration file that selectively *enables* additional extensions. When an extension is enabled, all extensions that the extension depends upon are automatically enabled as well. That dependency information is known the same way it was known at installation time.

In the per-wiki configuration file for Wiki A, extension X is enabled, therefore automatically enabling extension Y.

When a page is requested from wiki A, the global configuration file and the per-wiki configuration file for wiki A will be loaded, autoloading extension X and, because extension X depends upon it, extension Y.

However, when a page is requested from wiki B, extensions X and Y are not autoloaded, because they are not enabled - even though they are installed.

**Comment by alcohol** [comment]
I really don't see what composer has to do with this.

**Comment by hexmode** [comment]
composer-installed extensions are added to a composer-managed autoloader file that is used in MediaWiki.  Ideally, there should be a way to use composer's autoloader and still not have all extensions added to the autoloader (i.e. Enabled).

Since composer manages the autoloader (in my understanding), this *is* a composer issue.

If this is not a composer issue, how can we use the dependency discovery code without using the generated autoloader?

**Comment by cicalese** [comment]
The autoloading code is generated by composer. Currently the autoloading code autoloads all extensions that have been installed by composer. Instead, it would be helpful if there were function in the autoloader capable of taking the a list of names of packages to enable. The function would consult the composer.lock file only autoload those packages in the list and any packages that they depend upon.

**Comment by alcohol** [comment]
I don't see how the autoloader has anything to do with this, unless you're implying there is absolutely no configuration behind enabling or disabling a plugin?

**Comment by cicalese** [comment]
Typically, there is no additional configuration that cannot be accomplished by setting the value of variables accessible through the global scope at the same time that the extension is added to the array of extensions to enable.

**Comment by nevvermind** [comment]
@alcohol I think @cicalese describes some sort of selective process when autoloading, so that _some_ vendors wouldn't be handled. Keep it clear, peeps. It's getting confusing here (globals?).

**Comment by alcohol** [comment]
Autoloaders are a convenience for being able to load classes without having to constantly worry about having your auto include path setup for everything. I don't see what this has to do wiki plugins being loaded automatically and enabled in a wiki.

**Comment by alcohol** [comment]
As I also said in the irc conversation back then, simply install the desired plugins per wiki, problem solved. But I also remember (and you're not really explaining it properly here) that you're trying to share one code base with multiple installations. That however, is a problem you should solve, not composer.

**Comment by hexmode** [comment]
> Autoloaders are a convenience for being able to load classes

I'll have to look at the bits that were added (by @JeroenDeDauw, I think?) to make Composer's autoloading work with MediaWiki, but my understanding is that there is some code executed on each web request from each extension using the autoloader.  Maybe all that is required is modification of the MW shim and this is not a Composer issue.

> Keep it clear, peeps. It's getting confusing here (globals?).

If the mention of Globals makes this confusing, ignore it.  MediaWiki relies too much on globals for configuration, but were improving that slowly, thanks to @legoktm and others.

**Comment by legoktm** [comment]
I'm not sure if everyone in this discussion is aware of how MediaWiki extension setup works, so let me give a quick overview:

Each MW extension has a PHP "entry point" file which sets various global variables to register different metadata with MW. sysadmins add a line like `require_once "$IP/extensions/FooBar/FooBar.php"` to LocalSettings.php, a file MW loads during setup.

The current implementation of making extensions installable via composer makes the PHP entry point an autoload files entry in composer.json, so when MW loads vendor/autoload.php, the extension is enabled.

This is problematic when you run a wiki farm that has different configuration for different wikis by doing something like `switch $_SERVER['SERVER_NAME']`. But vendor/autoload.php is static and will always enable the extension, on every wiki.

---
My opinion is that composer is a dependency manager, not an arbitrary plugin manager, and trying to use it as one really doesn't work. As I've stated elsewhere, I think we (MW devs/interested people) should be working on things like #3545 so MW can re-use the useful parts of composer and not re-invent the wheel without needing to use *all* of composer.

**Comment by alcohol** [comment]
To be honest, to me it sounds like you should be working on a more sane configuration and deployment setup. I understand that your current idea/approach seems very convenient, but convenience often comes with a trade-off. Just my 2 cents though.

**Comment by JeroenDeDauw** [comment]
@hexmode I introduced Composer to the MediaWiki extensions world yes, and I'm quite familiar with the WikiFarm discussion by now. However my thoughts on this remain much as they have been outlined in the past: "disabling" things installed by Composer via Composer undermines the security of the dependency resolving. I've yet to hear clear augments for why one can not have one set of software for each usecase rather than trying to have a single set with a pile of switches serving multiple. To me it just seems like a bad idea, and I personally do not think Composer should support "disabling installed code".

**Comment by hexmode** [comment]
@JeroenDeDauw fair enough.  Back over on the phabricator task about this, I already conceded.  I suppose it is time to close this.  At least now I know where to point if people ask "why didn't you use Composer?"

**Comment by brightbyte** [comment]
If I understand correctly, the idea was to (ab)use the "fieles" entry in the "autoloader" section to execute the extension's setup code on every request. The setup code registers callbacks with MediaWiki, thereby "enabling" the extension. The original request aims at running this code that hooks the extension into the wiki only selectively, presumably based on some global variables. The simples solution would probably be to just have Foo's setup code, Foo.php, start with something like this:

  if ( defined( 'MW_DISABLE_FOO' ) ) return;

But that would have to be explicitly added to each extension.

**Comment by cicalese** [comment]
@JeroenDeDauw I agree that selectively disabling extensions could be dangerous, since you could disable an extension that another enabled extension depends upon. My suggestion, instead, was to selectively *enable* extensions using the same dependency information that was used/generated at install time. Enabling an extension would automatically enable (autoload) all packages (extensions, etc.) that the extension depends upon. Rather than autoloading all extensions, only those extensions that are explicitly enabled and their dependencies would be autoloaded. I believe that this will prevent the dangerous situation that you are concerned about. The wiki farm problem is a real one that I am confronted with, and maintaining multiple wiki farm configurations for multiple combinations of enabled extensions is an unworkable solution.

@brightbyte The simple solution of having an extension disable itself would leave an unstable environment if an extension that another extension depends upon were to disable itself. A dependency aware solution is needed.

**Comment by brightbyte** [comment]
@cicalese Potentially. In reality, extensions depending on other extensions should be rare (once we have decent support for sharing library dependencies, we'll see less of that). The use case would mainly be extensions extending extensions - e.g. extensions that add functionality to other extensions, like SMW or Wikibase. In any case, the new situation would be no worse than what we have now: extension dependencies would be unmanaged,  but we'd have a way to automatically manage libary dependencies.

All that being said, I'm not in favor of managing extensions themselves using composer. Library dependencies should be managed via composer, but extensions/plugins follow a completely different logic: the optional bits depend on the application as a framework. Following that logic, an extension would pull MediaWiki in as a library. That is not how a web application should be installed, and it doesn't make much sense to model dependencies that way. So, extension/plugins should use a different approach, which should be complementary to and compatible with composer.

**Comment by alcohol** [comment]
Installing extensions should not be the same as enabling extensions. Simply because files are included at runtime shouldn't be the determining factor for 'enabling' them. This should be configurable. I would advise that the files that are loaded at runtime merely register as available, and then a configuration panel toggles them as enabled or disabled and stores this value somewhere.

**Comment by cicalese** [comment]
Thank you for the helpful discussion. I'm certainly in favor of an alternate solution if it allows for individual wikis in a wiki farm to have different sets of enabled extensions. The problematic part at present is the autoloading of extensions that are installed with composer. As an extension developer, I have not converted any of my extensions to be installed with composer due to this limitation. But, as a wiki farm manager for wiki farms using Semantic MediaWiki and a host of extensions (some of which I have authored) that depend upon its presence, I am hoping for a solution to this issue soon.

**Comment by brightbyte** [comment]
@cicalese that autoloading by itself should not be problematic at. "autoloading" doesn't load anything - it just tells PHP where to find each class. Actually executing the extensions setup code through the autoloader is problematic. I don't think extensions should be doing that.

**Comment by ingomueller-net** [comment]
So if I understand things correctly, if MediaWiki wanted to use composer, then the correct way would be along the following lines: composer would determine the best version of an extension and *install* it (i.e., to copy the files from somewhere). The file loaded by the autoloader of composer would register the extension in the extension registry of MediaWiki, but not enable it. Enabling would be done with a different mechanism, for example by calling a function in `LocalSettings.php`.

@alcohol, does that sound about right?
@hexmode, would that solve the wiki farm use case?

**Comment by hexmode** [comment]
Ingo Müller writes:

> @hexmode, would that solve the wiki farm use case?

Yes.
