### ISSUE TITLE
"composer diff" to see changes in project and all packages

### ISSUE THREAD

**Issue by sminnee** [composer/composer#4129]
It would be great to have a "composer diff" option that included the changes from any included packages.

     # Composer the current checkout to the older release <sha>
     composer diff <sha> HEAD / composer diff <sha>

     # Compare two previous releases
     composer diff <sha1> <sha2>

It would work by...

 * Running diff on the current project
 * Comparing composer.lock on each version, and getting the to/from SHAs of each included package
 * Running a diff on each included package

I'm wondering whether it would be better to implement this as a standalone script, or as a PR for composer...

 * Would this be a pull-request that you would accept?
 * What kind of gotchas could you foresee?
 * Any implementation advice?

Or would it be better to start with a standalone script and submit it as a PR once it's matured a bit?

**Comment by nevvermind** [comment]
Why would this be great? What's the value provided by such a feature?

**Comment by sminnee** [comment]
It's useful when reviewing a project to understand what has change in a given timespan. For example, when deploying a people are often interested in what has changed since the last time they deployed.

In simple cases, this question can be answered with a "git diff" command. However, for a composite project managed with composer, this only gives half the story. To know what has actually changed in the codebase you are about to deploy, you need to see which dependencies have been updated and then look at the diffs of each of those. If you have a large number of dependencies, this can be time-consuming.

So, a tool to do this is in a single step would be helpful. My particular use-case is that I want to add a "show changes since last deploy" feature to our deployment tool and this script would power that.

Initially I considered building this as a separate script (and may still do) but it occurred to me that building it as a "composer diff" verb might be more logical, if it were of use to other composer users.

**Comment by alcohol** [comment]
http://git-scm.com/docs/git-diff

You're welcome.

**Comment by slbmeh** [comment]
I think I know what you have in mind, a composer driven dependency aware diff tool.  I don't see how it can be done in a practical manner being that composer can be used without VCS at all.

I think you're better off with a tool that depends on composer as a library.  You'll need to dig deep into the VCS internals because you need two versions of the same file simultaneously.  I only know how to do that with git. You'll need to traverse the object tree with `git cat-file` or parse the objects and packs under `${GIT_DIR:-.git}/objects` yourself.

Then you need to make two repositories from the corresponding lock files.  It will only be reliable with a locked repository, because an unlocked repository could give you anything depending on the time and system.

@sminnee ping me if you want help with such a project. I think it would be fun to build.

**Comment by alcohol** [comment]
The most straightforward solution would be to simply `diff` your current and previous release package. However, this will only give you the changes themselves, not the reasons behind them. For that, you would need to work based on tickets, user stories, or something similar. Then you would need to keep track of which went into what release. What you're looking for has been attempted in many ways by many people already, none of which have lead to a standardised solution. It's simply a very a complicated question that cannot easily be answered.

**Comment by sminnee** [comment]
Thanks, everyone. I'll keep it as a separate tool for now.

For those interested, I've started here:
https://github.com/sminnee/composer-diff

**Comment by HongPong** [comment]
Since this issue is still a top hit, I add:
`composer status --verbose`
give the list of changed files (differences with the composer.lock file versions). More: https://getcomposer.org/doc/03-cli.md#status
