### ISSUE TITLE
Maintain "modified files" on install/update, instead of aborting when not discarded

### ISSUE THREAD

**Issue by Pictor13** [composer/composer#4137]
> https://github.com/composer/composer/blob/master/src/Composer/Downloader/GitDownloader.php#L167

Actually is not possible to install/update a package having some changed file in it.
When having a package installed with the `--prefer-source` option could be that there are changes pending in the cloned repository; changes to apply just after a 're-install' of the package itself.

Now, as shown in the code above, if a user has some changed file and does **NOT** want to *discard* these \*he can't rely on *composer*, and needs to proceed with the additional steps of:

* enter the repository cloned under *vendor/*
* stash the changes
* proceed with a `composer install`
* enter the repository again
* apply the stashed files

Would be nice instead to have more suitable options to maintain the changed files or, at least, to have the stashing/restoring steps automated.

Is there some specific limit in realizing this?

Or is it planned to integrate such feature in *composer*?

**Comment by alcohol** [comment]
Due to the nature of there being many possibly reasons as to why the files are modified, it is better to leave most of the conflict resolution up to the user. Trying to automate all the possible scenarios would result in far too much code to maintain and a lot of added complexity. There also isn't a huge demand for this feature, and I personally strongly oppose creating tailored solutions for edge case scenarios.

**Comment by stof** [comment]
@Pictor13 the current feature allows to stash changes rather than discarding them. Just use this choice when composer asks you what you want to do.

**Comment by Pictor13** [comment]
@stof oh that's really cool! It should really be enough (because it what I would do) for the case!

I was not working with the most recent version, I didn't notice it.
I'll try it soon!

Thank you,
issue closable on my side
