### ISSUE TITLE
Composer not falling back on source when failing on dist

### ISSUE THREAD

**Issue by Soullivaneuh** [composer/composer#4147]
See on this build: https://travis-ci.org/sonata-project/SonataAdminBundle/jobs/66780501#L172

As you can see, composer fail to download the release but is not trying to get it from source.

Is that a regression on your code?

Thanks.

**Comment by Nek-** [comment]
Composer get dist by default. But it looks like your problem is something else: it's a limitation of github...

You can specify you want to get dependencies by source with `--prefer-source`.

**Comment by Soullivaneuh** [comment]
@Nek- Thanks but that is not the issue. We configured Travis to call Github with OAuth key.

Failling or not, composer had used to fallback on source mod if dist not working.

**Comment by slbmeh** [comment]
It should still fallback. The exception is caught and then thrown again if it's the last source type in [Composer\Downloader\DownloadManager](https://github.com/composer/composer/blob/69210d5bc130f8cc9f96f99582a041254d7b9833/src/Composer/Downloader/DownloadManager.php#L205-207)

If you have authentication configured for github and it fails for dist, it's probably going to fail for source as well since they both use the API for github packages IIRC.

**Comment by Soullivaneuh** [comment]
@slbmeh In this case of this build, as it's a PR, the secure OAuth key is not available on Travis, the env var is empty. So it's like composer have no authentication configured.

**Comment by andrerom** [comment]
Same issue here, been like this since beginning of the weekend when new packagist site went online, unsure where the connection is.

**Comment by greg0ire** [comment]
@Soullivaneuh then maybe we should not call the command if the variable is empty ? Maybe Composer behaves diffently when the setting is defined, even though it is empty…

**Comment by Soullivaneuh** [comment]
@greg0ire I think I already tried this without success but you can test.

**Comment by greg0ire** [comment]
oh ok :(

**Comment by hkdobrev** [comment]
Try setting the `--no-interaction` flag. In the past it asked whether to try using source and if it was in a non-interactive mode it just used the source as a fallback.

**Comment by hkdobrev** [comment]
Sorry, I didn't see you already use the `--no-interaction` flag. You could try setting an OAuth token in the Composer global config through a secure env variable in Travis. However this is still something which Composer should fix IMHO.

**Comment by greg0ire** [comment]
> You could try setting an OAuth token in the Composer global config through a secure env variable in Travis

If I understand correctly, this is what we already did, but it does not work for P.R.s because the env variable could be easily echo'ed by an attacker/contributor.

**Comment by hkdobrev** [comment]
> it does not work for P.R.s because the env variable could be easily echo'ed by an attacker/contributor.

This is correct. For public repos you could use a non-secure env variable with a OAuth GitHub token which is just for reading.


For private repos you could actually use secure env variables even in PRs.

**Comment by greg0ire** [comment]
> a OAuth GitHub token which is just for reading.

Aha! This sounds interesting

**Comment by greg0ire** [comment]
@Soullivaneuh any way we could do this ?

**Comment by Soullivaneuh** [comment]
@greg0ire It's still a private token. If we made it public, anybody can used it on explode our api calls limit.

I'm right? In any way, you must see that with @rande. ;-)

**Comment by hkdobrev** [comment]
@Soullivaneuh You could use a secure env-variable on master builds and on PRs from a branch in the same repo. You would just run builds without a token on PRs from forks.

**Comment by Soullivaneuh** [comment]
@hkdobrev And then we go back to the original issue. ;-)

**Comment by greg0ire** [comment]
@Soullivaneuh : it sounds right indeed. Let's wait for Stack Overflow, I'll open a big bounty as soon as I can.

**Comment by stof** [comment]
@Soullivaneuh the issue is that you are not only persisting the composer cache between builds, but also the vendor folder itself. In case of updating an existing installed package, composer will indeed not fallback to a different installation method (which would require switching to a remove/install process rather than an update process btw). It tries only the existing method.
I suggest that you only persist the cache between builds, not the vendor folder (the API rate limit is only impacted for cache misses anyway).

And if you don't have a token for PR coming from forks, it is not a big issues IMO: they will hit the cache most of the time once it is populated by branch builds

**Comment by greg0ire** [comment]
Thanks @stof for taking the time to look into this issue! I'm going to make a P.R. for that, hopefully the token will not be used even though I am part of the organization that ows the repo…

**Comment by Soullivaneuh** [comment]
@stof Wow, thanks for the trick! But I'm curious. What is the relation between vendor caching and no fallback on api call?

**Comment by stof** [comment]
@Soullivaneuh when the package is already installed and Composer needs to update it to a different commit, it will always use the installation method used to install this package in the first place. So if the package was installed as dist, it will not try to delete it entirely and resinstall it from source.

**Comment by Soullivaneuh** [comment]
Thank you for the explanation @stof. :+1:
