### ISSUE TITLE
How i can update all symfony bundles from controller?

### ISSUE THREAD

**Issue by averichev** [composer/composer#4154]
Hello.

How i can update **all bundles** from controller? (*php composer.phar update* command analog)

How i can update 1 package from controller? (*php composer.phar update vendor/package* command analog)

Сan be an example?

**Comment by stof** [comment]
Updating code from within your application looks very dangerous to me. It means that your running code will need to alter the codebase. This has a very high chance of failures, especially if classes used to end the request handling are not yet loaded before updating the codebase as you will start using some new classes together with older classes.

thus, it is likely to fail because a request is generally limited to 30s and a composer update is taking much more than that.

and anyway, changing the codebase directly on the server is a very bad idea: it means you are running totally untested code directly.

What is your reason to do it from a controller rather than updating things on the command-line ?

**Comment by averichev** [comment]
I want to allow the user to upgrade the packages of the latest version

**Comment by stof** [comment]
Which user ? In which context ? This is what I'm looking for. I'm trying to understand the use case for doing things this way, because I can only think about drawbacks and risky cases for such setup.

**Comment by averichev** [comment]
I do bundle for users. I wish that he could upgrade my bundle push of a button
