### ISSUE TITLE
Install package via API

### ISSUE THREAD

**Issue by ZAYEC77** [composer/composer#4198]
Can I install package via Composer API?
I tried to install, but it didn't work.
```php
    protected function getComposer()
    {
        $dir = dirname(dirname(dirname(dirname(dirname(__DIR__)))));
        $path = $dir . '/composer.json';
        $factory = new Factory();
        return $factory->createComposer(new NullIO, $path, false, $dir);
    }

    public function actionInstall()
    {
        $composer = $this->getComposer();
        $input = new ArrayInput(['packages' => ['rmrevin/yii2-fontawesome']]);
        $output = new BufferedOutput();
        $cmd = new InstallCommand();

        $cmd->setComposer($composer);
        print_r($cmd->run($input, $output));
        print_r($output->fetch());
    }
```
So, I got result "1"
Can you help me?

**Comment by stof** [comment]
The install command does not accept an array of packages as arguments

**Comment by ZAYEC77** [comment]
@stof, can you give some example of code?

**Comment by stof** [comment]
Well, ``composer install`` does not take such argument. If you pass one, it will fail saying that the call is invalid. So if you call the same command in code, you will face the same issue, which is totally expected.
To give you code example, I miss more info about what you are trying to do rather than how you are trying to do it.

I suggest you to avoid using a NullIO but an IO sending the output to your BufferedOutput instead. Otherwise you would miss most output of Composer telling you what is wrong.

**Comment by ZAYEC77** [comment]
@stof thanks
So, have I to use require command?

**Comment by ZAYEC77** [comment]
I try another variant:
```php

        $composer = $this->getComposer();
        $cmd = new RequireCommand();

        $input = new ArrayInput(['packages' => ['rmrevin/yii2-fontawesome']]);

        $output = new BufferedOutput();
        $cmd->setComposer($composer);
```

But get error:
```
Call to a member function resetComposer() on null
```

**Comment by stof** [comment]
I think this is because your command does not have the Application set on it when you run it. running the command outside an Application is not supported by composer commands, as it is not supposed to happen.

**Comment by ZAYEC77** [comment]
@stof, excuse me, but I use Yii2 application and I don't know how to use composer command correctly.
