### ISSUE TITLE
Consider adding case checks on autoloaded paths

### ISSUE THREAD

**Issue by Seldaek** [composer/composer#4209]
psr-0 paths could be checked on the filesystem when we dump the autoloader to ensure that they match the case used in the namespace prefix. psr-4 does not apply here.

Additionally psr-4/psr-0/classmap paths could be checked to ensure the case on filesystem is the same as the case defined in autoload config.

In case any discrepancy is found we can issue a warning to make sure people on case insensitive filesystems realize the issue early.

This does not cover the full path of course as if a filename is incorrect it'll stop working using psr-4/psr-0 on a case-sensitive filesystem, but it should ensure that classmaps can be generated even on those filesystems so in an optimized autoloader case it should always work out.

Refs #1803

**Comment by stof** [comment]
note that the logic to check case during the autoload (to give you a warning when running your code on case insensitive filesystems to tell you it will break when changing systems) exists in the Debug component of Symfony.
This is not something we should add in the Composer ClassLoader itself IMO, as it adds overhead, but I wanted to mention it here for people not knowing it. It is a nice complement to checks which could be added in Composer itself during the autoload dumping.

**Comment by dynasource** [comment]
+1

**Comment by zmorris** [comment]
I just hit this bug and https://github.com/composer/composer/issues/1803 and https://github.com/composer/composer/issues/2767 when I used php-cs-fixer with Atom to auto-format all of my .php files to PSR-2.  My directory structure looks like app/Http/Controllers/MyController.php so php-cs-fixer writes "namespace app\Http\Controllers;" at the top of my files.  When I run "composer dump-autoload", it fails to find my app\Http\Controllers namespace, even though that is the exact path on disk.  Previously my namespaces had looked like "namespace App\Http\Controllers;" and everything worked.

Note that php namespaces are case-insensitive.

The gist of this is that either:

1) php-cs-fixer (and other formatters) should be updated to follow the "namespace App\Http\Controllers;" convention, regardless of capitalization on disk

or

2) composer should be updated to respect php's case-insensitive namespaces

Keep in mind that repositories MUST run when they are checked out, we can't force users to change their php-cs-fixer (or other) formatter rules every time they check out a repo.

Sorry to be the bearer of bad news, but I don't think composer is respecting standards as it stands now.  I understand that there may be added internally complexity with key mapping, but these should not impact performance as much as is being implied by other posts.

Now I am in a tough spot.  I either have to "git mv app App" or alter composer in some way.  git mv causes the lost of history if diff tools don't use --follow, because git uses a heuristic to track filename changes (it maintains no metadata between commits to track changes) and this heuristic is disabled by default.  Altering composer makes me extremely uncomfortable and should not be necessary.

I spent the weekend thinking about this and believe that the only solution that satisfied both PSR-2 and php's case-insensitive namespaces is to update composer to also be case-insensitive.

If anyone has a drop-in fix for composer, I'd really appreciate it.  Otherwise I am forced to "git mv app App" and lose history in our repo, because these types of minutia do little to explain to my client why source formatting can't "just work", as indeed it should.

Other than this unfortunate turn of events, thanks for the great work on composer, you have saved me countless hours of avoiding dependency hell over the years.

P.S. I am on Mac OS X 10.11.5 (15F34) and my coworker is on a case-sensitive Linux.  I have tried "git config core.ignorecase true" among other workarounds but they don't solve the core issue.  Admittedly this comes down to one of the primary bugs/features in git as much as a case-insensitivity issue, but nobody will understand why this is such a big deal if I try to explain it to them.

**Comment by jvasseur** [comment]
@zmorris The problem is that php-cs-fixer psr0 fixer (which is included in the psr2 level) is broken with psr-4 paths. PSR-4 explicitly states that classes should be loaded in a case-sensitive fashion, so composer is respecting the standard here.

**Comment by Seldaek** [comment]
Yeah I don't think we are going to do this.. It's not really worth it IMO. The case should match between disk and classnames, but in this particular instance if you use psr-4 mapping in composer you can do this AFAIK that would work without requiring a `git mv`:

```json
"autoload": { "psr-4": { "App\\": "app/" } }
```

**Comment by zmorris** [comment]
Ok so it looks like PSR-0, PSR-2 and PSR-4 conflict with php namespaces being case insensitive.  I realize this isn't really composer's fault.

I did stumble onto a workaround for using PSR-2 with PSR-0 disabled for Laravel 5.1's lowercase `app` directory in a [Laracast](https://laracasts.com/series/whats-new-in-laravel-5-1/episodes/1#comment-2454549761).  That led me to a [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) configuration option that can be saved in `.php_cs` in the root of the project directory:

```
<?php

$finder = Symfony\CS\Finder\DefaultFinder::create()
    ->in(__DIR__)
;

return Symfony\CS\Config\Config::create()
    ->level(Symfony\CS\FixerInterface::PSR2_LEVEL)
    ->fixers(['-psr0'])
    ->finder($finder)
;

```

To make this run for every save, I installed php-cs-fixer on my Mac with:

```
brew install homebrew/php/php-cs-fixer
```

Then I installed the [php-cs-fixer Atom package](https://atom.io/packages/php-cs-fixer) and used `which php-cs-fixer` and `which php` to find the executable paths.  `My config.cson` file in [Atom](https://atom.io/) contains:

```
"php-cs-fixer":
    executablePath: "/usr/local/bin/php-cs-fixer"
    executeOnSave: true
    phpExecutablePath: "/usr/bin/php"
```

So now every time I save, it formats to PSR-2 sans PSR-0 and all my namespaces look like `namespace App\...;` so everything "just works" finally.  Hope this helps someone.

**Comment by zanderwar** [comment]
PHP is a case-insensitive language in 99.9% of scenarios; adding a case-sensitive autoloader goes against that grain. However, I also agree that class references should match case perfectly.

#torn

If you wish to support case-insensitive loading and want to do the `strtolower` yourself:

```
/** @var \Composer\Autoload\ClassLoader $autoloader */
$autoloader = require_once "../vendor/autoload.php";
$autoloader->unregister();

include_once "autoloader.php";
spl_autoload_register([new MyAutoLoader($autoloader), 'loadClass']);
```

```
<?php

class PowerhouseAutoLoader
{
	/** @var \Composer\Autoload\ClassLoader */
	private $loader;

	public function __construct($loader)
	{
		$this->loader = $loader;
	}

	/**
	 * Responsible for loading (including) classes
	 *
	 * @param $name
	 * @return null|bool
	 */
	public function loadClass($name)
	{
		$result = $this->loader->loadClass($name);

		if (!$result) {
			return $this->handle($name);
		}

		return $result;
	}

	/**
	 * Handles the delegation of the required inclusion methods
	 *
	 * @param $name
	 * @return null|bool
	 */
	private function handle($name)
	{
		$name = strtolower($name);

               if (file_exists......................) {
                    include_once ..........
                    return true;
                }

		return false;
	}
}
