### ISSUE TITLE
How to provide a localy patched package for one specific version?

### ISSUE THREAD

**Issue by nicolas-grekas** [composer/composer#4226]
This is an issue we have on symfony/symfony and I can't find a solution for now:

While on branch 2.8, I want to test one single component A.
Lets say A depends on B, but I don't know if it's B(2.8) or B(3.0).
In case it's B(2.8), I want to provide an alternative (patched) source package.
In case it's B(3.0), the upstream version is fine (as published by packagist).

What we do now in symfony is putting B source in B.tar, build a local packages.json file referencing B.tar as version 2.8.x-dev, then reference this packages.json in A's composer.json, in the repository section.

This works almost fine, but composer always prefers the local B.tar even when the upstream B(3.0) would be fine.
Is there a way around this behavior? What do I need to change?

**Comment by nicolas-grekas** [comment]
Here is a quick reproducer:
```sh
git clone git@github.com:symfony/symfony.git
cd symfony
git checkout 2.8
export TRAVIS_BRANCH=2.8
export COMPOSER_ROOT_VERSION="$TRAVIS_BRANCH".x-dev
export components="src/Symfony/Component/Asset src/Symfony/Bundle/SecurityBundle"
sh .travis.sh $TRAVIS_BRANCH $components
cd src/Symfony/Bundle/SecurityBundle
composer up --dry-run
```

You'll see that symfony/asset (2.8.x-dev) would be installed, where symfony/asset (dev-master) would be perfectly fine (and is selected if I remove the reference to the generated packages.json)

**Comment by slbmeh** [comment]
I'm not sure I fully understand the issue here.

If you're creating a composer repository and that repository resolves your dependency it will not look for the package in a different repository. E.g. packagist... You would need to include dev-master in your generated packages.json if you would like that to be an installation candidate.

**Comment by nicolas-grekas** [comment]
You've got it: I want to create a repos that overloads only one specific version: if packagist provides a higher version of the same package that my custom repos has, I want to use the version on packagist.
How should I do that? Is referencing all existing versions of my package in my local repos the only way?
Does packagist provide some JSON that could help build this?

**Comment by stof** [comment]
@nicolas-grekas there is https://packagist.org/p/symfony/console.json (replace the package in the URL to get what you want)

**Comment by Seldaek** [comment]
@nicolas-grekas if a package is available in a higher-prio repository than packagist then it will always pick that as otherwise it'd be possible to attack people and make them install packagist code by just publishing new packages with high version numbers. I don't think you can do this except using the hack mentioned in the two comments above.

**Comment by nicolas-grekas** [comment]
Thanks, that's clear. For reference, there is an alternative approach to providing patched version using [composer-patches-plugin](https://github.com/netresearch/composer-patches-plugin)
