### ISSUE TITLE
composer require --dev included in classmap

### ISSUE THREAD

**Issue by oligriffiths** [composer/composer#4252]
Hey

So, run this command:

composer require --dev phpunit/phpunit

Then examine the `vendor/composer/autoload_classmap.php` file. Notice how it's full of php unit classes. Given that these are dev dependencies, these should not be in the autoload file, as this file is used in production, where dev dependencies have no business.

I notice in the phpunit composer.json it has:

```
"autoload": {
        "classmap": [
            "src/"
        ]
    }
```

Which I assume is being read by composer during install and blindly being copied to the classmap, even though it's being installed as a dev dependency.

Can anyone advise on if this is correct behavior, it seems wrong.

**Comment by slbmeh** [comment]
The dev dependencies are added to the autoloader when they are installed.

**Comment by oligriffiths** [comment]
Why?

They don't exist in production, they have no need to be in the production classmap?

**Comment by slbmeh** [comment]
If you install on production, generally with `--no-dev` they will not be in the classmap.  If you happen to install the dependencies they should be in the classmap.  What use case do you have where you want to download the files of a dependency and not use it?

**Comment by oligriffiths** [comment]
We commit out vendor folder so that packages are always available regardless of GitHub uptime, or packages being removed or whatever. 

Thus, we don't run install on deploy. So those things are in the classmap.

**Comment by slbmeh** [comment]
You can still generate the autoloader on deploy. Most do to dump an optimized classmap.

`composer dump-autoload --no-dev`

**Comment by alcohol** [comment]
Git is not a deployment tool. It is good practice to have a build process for your release packages. They should generally be stripped of all `.git` directories, related configuration files (`.gitignore` etc.) and include things like an optimized dump-autoload with `--no-dev`.

**Comment by oligriffiths** [comment]
Yeah we do, I'll look into it. We have a deployment process and could strip that stuff from the classmap on deploy. 

I don't see why committing vendor is a bad idea, what if the package becomes unavailable or github is down?

**Comment by alcohol** [comment]
Maybe I phrased my answer wrong, but I do not believe that I was saying that it is a bad idea?

**Comment by oligriffiths** [comment]
Oh, ok, cool.

**Comment by oligriffiths** [comment]
@alcohol So, I've looked into this and could do with some help explaining the following.

Fresh project:
`composer require --dev filp/whoops 1.*`

Install the dev dependency and the classmap contains the files referenced in the `flip/whoops` classmap property in the project composer.json, all as expected.

`composer dump-autoload --no-dev`

I would now expect the classmap to be empty as I'm specifically telling it NOT to include dev dependencies in the autoloader. However, the classmap is not updated and still contains the dev dependencies classmap...

Am I missing something about how this works?

**Comment by alcohol** [comment]
Because there is literally nothing to do for Composer at that point (you have no normal packages to generate autoload code for), it simply does not touch the files. It does not check your existing autoload files, which is what you are assuming I guess. It merely overwrites them based on the current situation.

**Comment by oligriffiths** [comment]
Shouldn't the classmap be empty though? if im telling it not to include dev dependencies, why is it parsing the dev dependency composer.json and including its classmap?

**Comment by alcohol** [comment]
Not sure at this point. Reading through the code. Give me a moment.

**Comment by alcohol** [comment]
So, it seems that because it is still installed, it will parse the autoload definition of `filp/whoops`.

Not sure why the behaviour is like this. It makes sense from a certain perspective, but it does make the use of `--no-dev` here less practical.

**Comment by alcohol** [comment]
OK, maybe this clarifies it: `--no-dev` means it will exclude the `autoload-dev` definition of your root package.

**Comment by oligriffiths** [comment]
Oh, wait so dev dependencies will always have their classmap definition included in the main classmap, that's weird.

**Comment by oligriffiths** [comment]
So is there no way to tell composer not to include dev-dependencies in the classmap? I notice if you do `--optimize` that that psr0/4 autoload definitions also get included in the classmap for dev dependencies

**Comment by alcohol** [comment]
If they are installed, yes. It makes sense though. Not really weird at all. To control your dependencies, you can simply run `install` with or without `--no-dev`. But you cannot control your own `autoload-dev` rules with that. So that is what `--no-dev` does for `dump-autoload`.

**Comment by oligriffiths** [comment]
I see, so the point is, it generates an autoloader for all `installed` packages, that makes sense.

**Comment by alcohol** [comment]
Exactly :-)

**Comment by alcohol** [comment]
And with `--no-dev`, you can ignore your own `autoload-dev` rules (see [documentation](https://getcomposer.org/doc/04-schema.md#autoload-dev))

**Comment by slbmeh** [comment]
That's interesting. I did not expect `dump-autoload` to use the installed repository when it accepts the `--no-dev` flag.

**Comment by oligriffiths** [comment]
So, should extensions that are dev-dependency extensions be defining an `autoload-dev` in their composer.json and not  `autoload`

**Comment by alcohol** [comment]
@oligriffiths `autoload-dev` is to define autoload configuration that you only want to use during development. It is a **root-only** property. This means that Composer does not read it from the composer.json of your dependencies.

Now, for example, PHPUnit might be a require-dev dependency for you. But it is still just a library. So their autoload configuration belongs in `autoload`. They might have a `autoload-dev`, but that would only apply when you are working directly on PHPUnit (e.g. when that project is the root project). If they moved all of their autoload configuration into `autoload-dev`, you would never be able to use it.

So no, extensions should definitely not do that.

@slbmeh as pointed out earlier, `--no-dev` for `dump-autoload` refers to the `autoload-dev` property of your **root** composer.json. I can see why it is confusing since the flag is identical to the one used for `install` and `update`.

**Comment by oligriffiths** [comment]
I see. Thanks for clarifying. 

It would be very helpful to be able to have 2 class maps, one for dev and one for not. But for now I'll work with what we have. 

Thanks

**Comment by stof** [comment]
@oligriffiths having 2 classmaps would not be helpful, because the code loading the classmap would now have to be aware of whether they should load both of them or only one, which means you would probably have to generate 2 different ``autoload.php`` files too. and this starts making things very complex because any code wanting to access the composer autoloader would then need to choose the right one

**Comment by Seldaek** [comment]
I wonder if dump-autoload --no-dev should ignore dev requirements as well to be honest.. It is a change in what it does, but it would make sense, I think it was just an omission when we added the flag. 

Any thoughts on that anyone?

**Comment by alcohol** [comment]
I have no objections either way. As long as it is properly documented. I think it should be safe to assume that when a user specifies `--no-dev`, they know what they are asking for. In other words, they should not expect installed dev-requirements to still work in that situation.

**Comment by oligriffiths** [comment]
Correct. The current --no-dev is confusing (down to documentation), but having the option to exclude dev dependencies would be helpful.

**Comment by Seldaek** [comment]
Alright closing and replacing with #4343 to have a clean slate.
