### ISSUE TITLE
Composer not elaborate enough when lock file is different than json

### ISSUE THREAD

**Issue by tsvetann** [composer/composer#4256]
Sometimes I get the following message from composer:

Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.

Is it possible to get some more info on what exactly composer think is not up to date. I don't want to run composer update because it will update all packages!

Thanks!

**Comment by alcohol** [comment]
It could be something as small as a newline or character that shifted a column. It's because the lock file contains a hash of the contents of the json file (there is an open PR somewhere to make it look only at relevant attributes instead of the whole file).

Also, if you just changed 1 requirement, you can run `composer update vendor/package`. It will only update that requirement and nothing else. If you changed something like keywords or description, then simply run `composer update --lock`. This will go through the update process, but doesn't actually update dependencies. It does refresh the lock file (brings it back in sync).

**Comment by slbmeh** [comment]
Linking PR #4140

**Comment by Seldaek** [comment]
Fixed by #4140
