### ISSUE TITLE
Implement ability to cache tags and revisions from private git repo

### ISSUE THREAD

**Issue by ihor-sviziev** [composer/composer#4263]
For now when you using composer with private repositories (as example on bitbucket) - you will every time download one package version for every project. For public repositories package with specific version will be downloaded as zip and cached, so next time it will be got from cache. 

Would be great add ability to cache specific module versions. It can be done with [git archive](http://stackoverflow.com/questions/160608/do-a-git-export-like-svn-export/353830#353830). In future we may add same ability for branches with checking latest hash.

I know, that we can use Satis for archive those, but composer also can cache those packages.

**Comment by staabm** [comment]
will Toran proxy work for you?

**Comment by ihor-sviziev** [comment]
@staabm yes, but would be great to cache those packages locally without any services.

**Comment by stof** [comment]
@ihor-sviziev if your private repositories provides downloadable archives for the package, they will be used (and cached) by Composer. This works for private github repos for instance (assuming you have configured an oauth token to perform authenticated API calls otherwise you cannot access the private repo through the API and so you cannot download the archive).
However, I think that the bitbucket driver currently does not support private repos, and so using a private repo there fallbacks to the git driver to find metadata, which does not support archives (because a git server does not provide archives).

**Comment by ihor-sviziev** [comment]
@stof git provides ability to create archive without any API. Example: http://stackoverflow.com/a/12073669
It should works with ANY git repo, it may be your own private repo.

**Comment by Seldaek** [comment]
@ihor-sviziev but that would mean while indexing the git repo for packages we should generate zip archives for all versions and cache these? IMO it's much better to have a server in the middle do that, it's more efficient as it centralizes the work instead of every client having to do it (and wait..)

**Comment by ihor-sviziev** [comment]
@Seldaek I think it doesn't generate zip archives for all versions. 

We may add some parameter to composer.json which allows to cache git tags. If this option enabled - we will execute ```git archive``` command, which will create zip, add to cache and then install it as zip archive instead of using [git clone](https://github.com/composer/composer/blob/master/src/Composer/Downloader/GitDownloader.php#L46)

**Comment by Seldaek** [comment]
Ok I see, I guess we could generate them automatically but the problem is then we need to rework the way we pick an installer because the package metadata won't have the knowledge about that cached zip so we need to check and if it's there install from zip even though there is no zip and then go in the cache to fetch it.. overall quite a lot of nasty workarounds in the code I think to achieve this so I am not sure if it's really worth the trouble :/

**Comment by stof** [comment]
Especially given you then cannot  put this zip archive in the lock file as other devs won't have it.

If you always have to clone the repo locally anyway, why avoiding to clone it in the vendor folder ?

**Comment by ihor-sviziev** [comment]
@stof I'm don't tell you that we need avoiding to clone it in vendor folder. I just want to have cached version that will not be downloaded every time if you installing one package version from one git repo in 5-10 projects.

**Comment by stof** [comment]
@ihor-sviziev then you could contribute support for private repositories in the bitbucket driver, which means it will be usable for them and so will provide archives.
Given that the github driver already works for private repos (assuming you have a github token in composer to be authenticated), archives can already be used for private github repos, and then they are cached.
given that most Packagist packages are hosted on github, the github driver always got more attention than the bitbucket one.

**Comment by gomax** [comment]
Thats strange. Bitbucket private repo provides downloading zip archives for tags, branches, etc. But composer still cloning every time. Why composer doesn't pull? It clones every time I run on the same repo, with the same composer.lock file (I'm removing vendor dir for test)

**Comment by Seldaek** [comment]
Bitbucket support is out now.
