### ISSUE TITLE
path to the vendor directory in script doesn't work on Windows

### ISSUE THREAD

**Issue by Emetrop** [composer/composer#4271]
I've code like this:

    {
      "require-dev": {
        "squizlabs/php_codesniffer": "~2.3.3",
        "wp-coding-standards/wpcs": "~0.6.0"
      },
      "scripts": {
        "post-install-cmd": [
          "vendor/bin/phpcs --config-set installed_paths vendor/wp-coding-standards/wpcs/"
        ]
      }
    }

It works on Linux but not on Windows. What's wrong with this code on Windows?

**Comment by alcohol** [comment]
I honestly don't know if this applies to Windows too, but the vendor/bin directory is automatically added to PATH when running scripts. Can you see if just running `phpcs` (so remove the `vendor/bin/` prefix) works for you?

**Comment by jakoch** [comment]
Yes, Composer's bin-dir and the vendor/bin dir are pushed on top of the PATH so that binaries of dependencies are easily accessible as CLI commands when writing scripts. On Windows the batch files are executed. 

I've tested the given `composer.json` on Windows: the problem is the `vendor/bin` prefix, just run `phpcs`.
