### ISSUE TITLE
Oddness in version resolution

### ISSUE THREAD

**Issue by enygma** [composer/composer#4278]
So I'm trying to get two pages to play nicely together: Laravel and [Gatekeeper](https://github.com/psecio/gatekeeper). Here's what I'm doing:

`composer create-project laravel\laravel --prefer-dist`
then
`cd laravel; composer require psecio\gatekeeper`

It thinks about it for a second and then spits back:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for vlucas/phpdotenv == 1.1.1.0 -> satisfiable by vlucas/phpdotenv[v1.1.1].
    - psecio/gatekeeper 2.6 requires vlucas/phpdotenv 1.1.0 -> satisfiable by vlucas/phpdotenv[v1.1.0].
    - psecio/gatekeeper 2.6.1 requires vlucas/phpdotenv 1.1.0 -> satisfiable by vlucas/phpdotenv[v1.1.0].
    - Conclusion: don't install vlucas/phpdotenv v1.1.0
    - Installation request for psecio/gatekeeper ^2.6 -> satisfiable by psecio/gatekeeper[2.6, 2.6.1].


Installation failed, reverting ./composer.json to its original content.
```

The tricky part is that the Laravel version installed calls for: `"vlucas/phpdotenv": "~1.0"`
and Gatekeeper asks for: `"vlucas/phpdotenv": "1.*"`

which one would think would be able to be resolved correctly but there seems to be something odd at play here and an error is thrown.

Halp? :)

**Comment by stof** [comment]
Stable versions of Gatekeeper are not asking for ``1.*``. It is asking for ``1.1.0``exactly (forbidding ``1.1.1``). And given that the minimum stability does not allow dev versions, the ``dev-master`` version of GateKeeper will not be considered by Composer.

So the fix would be to ask the GateKeeper maintainer to tag a release with their fixed requirement instead of having the fix only in the master branch

**Comment by enygma** [comment]
*facepalm* my fault...I could have sworn I pushed the latest tag on Gatekeeper. It's updated to the `1.*` now and works fine. Sorry for the trouble!
