### ISSUE TITLE
High memory consumption when overwritting a bunch of packages

### ISSUE THREAD

**Issue by nicolas-grekas** [composer/composer#4279]
Trying to create a local repository of all symfony components (see https://github.com/symfony/symfony/pull/15322) I noticed that composer creates a LOT of conflict rules (~1 million in this case), which is both slow and consumes a LOT of memory.

Reading the code, I understand that the conflicting rules are generated to disable any package coming from packagist when a local repos takes over some packages.

I'm sure that a better shadowing strategy could allow the same behavior without this huge memory impact.

**Comment by stof** [comment]
conflicting rules are used to ensure that 2 different versions of Symfony cannot be installed together (as far as the solver is concerned, a package is ``symfony/symfony 2.7.1``, not ``symfony/symfony``).
There has been an attempt in the past to optimize the number of requirements being registered in the solver, but this has been reverted because it was breaking things (because of another optimization implemented before to avoid loading the whole Packagist metadata in the solver)

**Comment by Seldaek** [comment]
The thing is originally we allowed a package to be installed from any repo, but this was later changed to only allow packages from the highest defined repo, to prevent attacks against private packages via packagist. So given that fact I think we could entirely ignore packages present in lower priority repositories if a higher priority one provides them. 

It wouldn't really help in common cases though as this isn't really a typical thing to do unless you load a fork of something, but still would be a nice improvement and might allow a small speedup as a packagist lookup could be skipped for private packages as soon as they are found in the private repo.

**Comment by nicolas-grekas** [comment]
Closing in favor of https://github.com/composer/packagist/issues/938
