### ISSUE TITLE
Github token not used on global update

### ISSUE THREAD

**Issue by Soullivaneuh** [composer/composer#4282]
I setup a GitHub token on travis for composer.

This token is used for `composer update` but not for `composer gobal update`.

Token setup: https://travis-ci.org/sonata-project/SonataAdminBundle/jobs/72092313#L113

Global update: https://travis-ci.org/sonata-project/SonataAdminBundle/jobs/72092313#L120

Local update: https://travis-ci.org/sonata-project/SonataAdminBundle/jobs/72092313#L292

Is this a bug or a misconfiguration?

Thanks.

**Comment by stof** [comment]
this is because you configured the token for the project only, and ``composer global`` actually uses another project (located in ``~/.composer``).

If you want to have the token being used for all projects, you should use ``composer config -g`` to edit the global config (i.e. ``~/.composer/config.json``)

**Comment by Soullivaneuh** [comment]
Works like a charm, thank you @stof!
