### ISSUE TITLE
disabling svn externals 

### ISSUE THREAD

**Issue by glensc** [composer/composer#4283]
hi

please add support (via commandline, via global option) to disable svn:externals when checking out versions from svn. or make it default to be disabled?

the thing is that my project uses relative paths to svn:externals which became invalid when checking out tags:

  * project1/trunk/libs -> ../../../project2/libs -> OK
  * project1/tags/1.1/libs -> ../../../project2/libs -> ERROR

as if you know, svn tags are created by copying "trunk" to "tags/1.1"

btw, status is already ran with ignore externals, maybe should checkout also include ignore-externals flag *unconditionally*?

https://github.com/composer/composer/blob/69210d5bc130f8cc9f96f99582a041254d7b9833/src/Composer/Downloader/SvnDownloader.php#L68

typical outout from error ends with successful svn update, but as svn client exited with 1, process is aborted:

```
    Checking out /tags/2.23-2/@90074

  [RuntimeException]                                   
  Package could not be downloaded, At revision 90074.  
                                                       
```

**Comment by glensc** [comment]
why closing without any explanation?

**Comment by Seldaek** [comment]
Sorry, I've been going through all issues, and explaining on each one I close gets tiring :) 

I closed because svn is less and less relevant and this issue isn't quite clear what's best to do, plus nobody seems willing to do it in the last 9months, so I closed. If someone wants to do it it can still be done, but we need a clean issue tracker to see what's relevant.

**Comment by glensc** [comment]
for consistency composer should ignore `svn:externals` everywhere. in my opinion. i'm willing to make PR but did not get any response from the project which way to go.

**Comment by Seldaek** [comment]
Well we ignore them in status true but status is just informing you if you modified something.. I am not sure if it makes sense or not, but I don't know if we can truly talk of consistency between status and checkout. I see that for you it makes sense but I don't know if it'll break things for others if we do the change. I don't really like taking that risk.

And I don't really like adding more options than necessary just because one person has a weird use case with relative svn:externals. You are creating broken tags essentially so I don't see why we should have to pay the price and get more options and cruft to maintain?

**Comment by glensc** [comment]
Yes, my tags can be considered broken, but should really checkout of some project handle loading also externals? how git submodules are handled, are they also loaded when checking out project which has git submodules?

**Comment by Seldaek** [comment]
svn includes externals by default (IIRC), we don't do anything special with them. git on the other hand needs special treatment of submodules, and they are very rarely used anyway so I don't think it's comparable.

**Comment by glensc** [comment]
didn't git changed (or planned to change) submodules behaviour to do checkout submodules by default?

https://git-scm.com/docs/git-submodule currently says:

> When cloning or pulling a repository containing submodules however, these will not be checked out by default; the init and update subcommands will maintain submodules checked out and at appropriate revision in your working tree. 

and i think it's comparable, both are used to include extra resources to checkout. i'd say `svn:externals` is also rarely used for svn repos.
