### ISSUE TITLE
Composer install/update/diagnose = timeout

### ISSUE THREAD

**Issue by hugosoltys** [composer/composer#4292]
Hi ! 

I need some help, whenever i try to do 

    php composer.phar diagnose

i get this output 

Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: FAIL
[Composer\Downloader\TransportException] The "https://api.github.com/rate_limit" file could not be downloaded: failed to open stream: Connection timed out
Checking disk free space: OK
Checking composer version: OK

And my composer is up to date. Someone can help me ?

**Comment by alcohol** [comment]
And this problem is consistent?

**Comment by hugosoltys** [comment]
Yes. I have to do a composer install on my server but i cant connect to GitHub via composer...

Ping api.github.com works, ssh -T git@github.com too. 

I'm a bit lost.

**Comment by alcohol** [comment]
Have you configured a oauth key for GitHub?

Does the output of `composer config --list` (in your project) or `composer config --global --list` contain `[github-oauth.github.com] HASHHERE` in the output?

**Comment by hugosoltys** [comment]
No it doesn't. 
It should ?

**Comment by alcohol** [comment]
No not for the test. It should return a different error in that case.

**Comment by hugosoltys** [comment]
Ok
is it a known issue ?
I really don't know what to do ...

**Comment by alcohol** [comment]
No. And unfortunately I cannot tell you what is wrong, because it works for me. It looks like a network connectivity issue. But this is hard to debug since I do not share your connection.

**Comment by ctubio** [comment]
did you try..
```sh
echo "192.30.252.127 api.github.com" >> /etc/hosts
```

i had same problem, and fixed it by dont letting the connection of the composer process (other process like ssh may expose a different behavior depending if using ipv4 or ipv6) resolve the api.github.com domain to nothing else but to the address specified in the hosts file, that is the ipv4.

the real fix was done by my isp/hosting, after i report the issue with the ipv6 connection timeouts (not only with github but also with many other external services since some month ago.

**Comment by aerth** [comment]
Related: #4292 #4247 #4142
