### ISSUE TITLE
Support for nested sub-depedencies in case of sub-dependency version conflict?

### ISSUE THREAD

**Issue by EvaLok** [composer/composer#4313]
To my current understanding, since nested dependencies aren't currently supported, it's not possible to use two libraries which require different major versions of the same sub-dependency. For example, if one library supports php5.4 and thus uses Guzzle 5 as a dependency, then it could be incompatible with another library that uses Guzzle 6 as a dependency, since the Guzzle namespace would already be occupied. Of course, one might be able to use an earlier version of a library which might use the same sub-dependency, but this is rather inconvenient and may not even be possible, for example in the case of a new library which may not have ever supported an earlier version of a sub-dependency.

npm, of course, supports nested sub-dependencies, but this is more complicated in PHP due to the way that namespacing and autoloading work. However, it is possible to parse a dependency along with its sub-dependencies and replace `use` and `namespace` statements to reflecting nesting (eg: `Library1`'s `use` statements of `Library2\SomeClass` might be replaced with `Library1\Library2\SomeClass` and `Library2`'s `namespace` statements might similarly be replaced to reflect this change).

This could be a major change, but it could also be rather minimal, possibly so that rather than a dependency conflict causing a failure, composer might instead fall back to parsing conflicting dependencies in a way similar to what I described in the aforementioned paragraph. 

Is this a feature that the composer team is currently considering or interested in implementing? If so, I'd be happy to help out..

**Comment by alcohol** [comment]
I do not see this as being very feasible to implement. Composer tries to simplify dependency management. What you are proposing (and you are the not the first) is more in the line of advanced autoloading configuration. While it might seem tempting to try to implement this from within Composer, I do not think it would be a wise choice. It will increase the complexity of Composer significantly, just for an edge-case scenario (in my opinion).

**Comment by EvaLok** [comment]
I also discussed this with some friends and they were of similar sentiment in regard to this being an edge-case. However, I think that as new PHP versions are released and library histories become deeper, it will become increasingly common and probably increasingly worthy of consideration. If I play around and come up with a proof of concept that has a relatively minimal code footprint, would you be interested in seriously considering this functionality as a new feature?

**Comment by alcohol** [comment]
Pull requests are always open for consideration. Even if your proof of concept gets rejected, it might lead to new discussions (that could lead to a solution eventually).

**Comment by EvaLok** [comment]
OK - sounds good - I'm glad that this functionality isn't completely out of the question :)

**Comment by stof** [comment]
The issue is that PHP requires class names to be unique in the process. This means there is strictly no way to install 2 different versions of the library and using a different one depending on which part of the code base is calling it.
and replacing class names in the code base has already been rejected. It is very common for libraries to have their dependency exposed, be it because they use it in a return value or in an argument (for instance in constructor arguments, for any library using dependency injection). This means that code renaming will also impact the codebase using your library, not only the codebase used by your library (and it is even possible that a given library is called with an object coming from any of the 2 places using different versions of the library).
And having renamed classes is also very bad for users because their codebase will not match the documentation they follow anymore (and I can tell you that I would refuse to provide support for anyone using one of my package in an altered way as I would then have to guess what alterations have been made and how they could impact the code, which would make providing support insane)

**Comment by Seldaek** [comment]
Aye I agree that code patching is a pretty horrible workaround. It sounds like a good way out and I have thought about it as well but if you think of all the possibilities this can go wrong, it's just not worth it IMO. To add to what stof said, what about class names that are in strings (dynamically invoked classes)? And what about application type hints that might need to mean Guzzle5 in one case and Guzzle6 in the other? 

It's just not possible to do it entirely right I think.. Now it doesn't mean you can't try, but I think the chances are very slim that it'll make it into composer just because I don't believe it's feasible given the constraints of the PHP language.

In the meantime I'll close this because it's not really something we can fix unless someone comes up with a magical patch :)
