### ISSUE TITLE
Composer does not see dependences of dependences from third-party repositories

### ISSUE THREAD

**Issue by MAXuk** [composer/composer#4350]
composer.json from my project:
```
    "require": {
        "silex/silex": "~1.3",
        "php-console/silex-service-provider": "1.*",
        "company/silex-pdo": "dev-master"
    },
    "repositories": [
        { "type": "composer", "url": "http://satis.webdev" }
    ]
```

composer.json from <b>"company/silex-pdo"</b>:
```
    "name": "company/silex-pdo",
    "description": "Silex PDOServiceProvider",
    "require": {
        "company/pdo": "dev-master"
    },
    "repositories": [
        { "type": "composer", "url": "http://satis.webdev" }
    ]
```

composer.json from <b>"company/pdo"</b>:
```
    "name": "company/pdo",
    "description": "Extended PDO class",
    "require": {
        "php": ">=5.3.3",
        "ext-pdo": "*"
    }
```
Host http://satis.webdev is it https://github.com/composer/satis

When i`m try <b>composer update -vvv</b> in my project, return error:
```
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for company/silex-pdo dev-master -> satisfiable by company/silex-pdo[dev-master].
    - company/silex-pdo dev-master requires company/pdo dev-master -> no matching package found.
```

Thanks!

**Comment by stof** [comment]
It sees dependencies (which is precisely why it fails). What it does not see is repositories defined in other packages, because only the root package is allowed to define repositories: https://getcomposer.org/doc/04-schema.md#repositories

The doc even explains why this is the case: https://getcomposer.org/doc/faqs/why-can%27t-composer-load-repositories-recursively.md

**Comment by MAXuk** [comment]
It turns out I always need to specify all dependencies in composer.json of my project?:
```
    "require": {
        "silex/silex": "~1.3",
        "php-console/silex-service-provider": "1.*",
        "company/pdo": "dev-master",
        "company/silex-pdo": "dev-master"
    },
    "repositories": [
        { "type": "composer", "url": "http://satis.webdev" }
    ]
```
<b>composer update -vvv</b>  worked fine

**Comment by stof** [comment]
@MAXuk ah, there is another issue in your case too: only the root package can define stability flags. As the minimum-stability is set to ``stable`` in your project (which is the default behavior in composer), ``dev-master`` cannot be found for ``company/pdo`` because there is no stable version matching this constraint.
When specifying it at the root, it works because a ``dev-master`` requirement automatically means ``dev-master@dev``, i.e. it adds a stability flag

**Comment by MAXuk** [comment]
Thanks @stof!
I understood that, close my issue.
