### ISSUE TITLE
Use case question: Different require clauses by repo user.

### ISSUE THREAD

**Issue by Canta** [composer/composer#4369]
Hi there. 

I have this use case in my project, and don't know what's the best way to face it. I'm looking for advise, please tell me if this isn't the place for questions like this.

I'm working in a project that consists of a core software, and multiple add-ons (plugins).
This is a Laravel app, and i decided from the start to handle package management using Composer.

I want to be able to update the app instances by using composer. The company i'm working for uses Subversion, and we have added our private repos to the project's composer.json file. So far, everything's fine: when the user clicks "update" on the UI, the new code for the core is updated using subversion, and composer handles requirement updates. 

But there's a catch: we sell different functionalities at different prices. That is, our customers buy the core at a price, and they can also buy different plugins at an extra price. So, we don't just give all the app's plugins, but manage access to them (to the code itself of the plugins) by customer. 
For that access, we're using subversion credentials: user A has access to plugins 1,2,and 3, while user B has access to plugin 1 and 6, and so on. This way, if somewhere in the future a user decides to buy a plugin, we can give them access to it by simply changing permissions in the repos, and he/she just have to press "update" in the UI. Composer handles this by using REQUIRE clauses that point to the plugins, which have their own separate repos.

Problem is: if i put a generic composer.json file for the core, how do i tell composer to check for this or that other REQUIRE dependency based on the customer's access?

To the day, what we've done is to alter every installation's "composer.json" file in order to match the customer's current plugin setup. That is: hardcoding the requires in the composer.json file (either programatically using the command line "--require" argument or just by editing the json file at setup time). But that will get us to SVN conflicts with that non trivial file the day we wanted to add/remove/change some core dependency, breaking the update proccess. And this app is installed around the whole country: we can't just go and change every installation, the changes has to be carefully planned and compatible with a programable update process.

I was looking for a way of using a second JSON file just for the plugins, so i can have that one outside the project repo and recreated by looking at the repo access, while the "composer.json" file is used for the core and is repo managed. But AFAIK that mechanism doesn't exists. There's of course the option of different repos for different customers, which i simply refuse to mantain. And there are other slightly different options, all which end in an edited "composer.json" file.

We're thinking alternatives, but all of them point to just get composer out of the way and handle app requirements on our own, as the way composer has of living with composer.json doesn't seems to play nice with Subversion. I don't want that, i'm betting on our ignorance: there has to be some way of using composer we (my team) just don't know yet. 

My best bet so far is to just take out of the project the main "composer.json" file and programatically recreate it as part as the update process, doing all the checks i had to do before that. But if i do that, i just feel there's no use in Composer anymore, as i'm doing checks at least twice. My second best bet is to just modify Composer code to fit our needs, which may be a lot of work and we don't have the luxury of time.

So, what do you people think is the best way of doing this with composer? Is it even possible?

Thanks.

**Comment by alcohol** [comment]
You should read into how to use features toggles. This has nothing to do with Composer.

**Comment by Canta** [comment]
Oh, i disagree. I would say Composer has a lot to do with this. 

We've built this software's toggleable features as application packages, and given that we're working in PHP and Composer seems to be the de-facto standard PHP package manager, we've built this features as composer packages in order to avoid technologically isolate ourselves from the rest of the PHP community and/or reinventing any wheel; we even wanted to share part of our code if successful and fit for generic use cases, again leading to Composer. 
I've also seen the example of the "auth.json" file for Github repo authentication, and i thought of asking about similar approachs in order to achieve per-user private authentications and require clauses (that's the why of my mention about a possible second JSON file). Is basicaly something already there (the use of a second JSON), but for another use case.

So... it may not be supported, but i don't see it as something alien to Composer.
However, i understand now that Composer may not be the tool for this job. That's ok. Please feel free to close the issue if there's nothing to do about this. 

Thank you.

**Comment by stof** [comment]
@Canta the part which is outside the scope of composer is automatically changing the requirements based on the authenticated user.

However, I'm thinking about a way this could be solved:

- create a custom composer repository (i.e. a site exposing package metadata in JSON in the same format that Satis or Packagist) which exposes metadata for all the packages your customer bought (based on the authentication needed to access this repository).
- create a special package (I'll name it ``canta-software/bought-plugins`` in my example) for which the requirements are generated based on what the customer bought, and take care of marking it as an updated version each time there is a change (either bumping the package version, or bumping the ``time`` timestamp in case you use a dev version number all the time). this package can have the type ``metapackage`` as there is no code to install for it
- tell your customers to add this custom repository in the composer.json (to be able to access your packages) and to require ``canta-software/bought-plugins``

Be careful about the implementation of your repository though:
- you must return valid data otherwise it will create weird errors for your customers when running composer update
- depending on the number of customers you have, you may have to be careful about the performance of the package list generation.

**Comment by Canta** [comment]
@stof Thank you very much. This is indeed a way it could be handled. I'll check my options on how to do that in the repos. I guess we can let this issue as solved.
