### ISSUE TITLE
Wildcard expansion in the autoload definition?

### ISSUE THREAD

**Issue by lautiamkok** [composer/composer#4383]
I think Composer should have wildcard expansions in the autoload definition as it doesn't make sense while you can do that in `"require"`, such as `"slim/views": "0.1.*"` but not in `"autoload"`.

It would be so good if I can do like this,

```
{
    "require": {
        "slim/slim": "~2.0",
        "slim/views": "0.1.*"
    },
    "autoload": {
        "psr-4": {
            "Foo\\": [
                "module/*/source/"
            ]
        }
    }
}
```

Instead of writing a long list of paths,

```
"module/Artcle/source/"
"module/Book/source/"
"module/Contact/source/"
"module/Admin/Article/source/"
"module/Admin/Book/source/"
"module/Admin/Contact/source/"
```

for if I have this structure in my app,

```
myapp/
  config/ (config and setup)
  module/ (tons of modules!)
     Article/ (one of the modules)
        source/ (<----- note that all php psr4 classes are stored in this folder)
           Article
              Model/
                 ArticleModel.php
                 ArticlesModel.php
              Controller/
              View/
     Book/ (one of the modules)
       ....(the structure is the same as Article's)
  public/  (web site doc root)
  vendor/
    composer/
    ...(other packages)
```

It would be great if this can be considered into the future versions of Composer.

**Comment by alcohol** [comment]
Uhm, your files and classnames are not psr4 compatible so that is why psr4 is not working properly. Please learn about proper naming conventions for psr4. See here for more info: http://www.php-fig.org/psr/psr-4/

**Comment by lauthiamkok** [comment]
I think you don't understand the issue I raised.

**Comment by alcohol** [comment]
Wildcard expansion is not necessary if your directory structure has a logical setup. Code shouldn't be all over the place. Nor should it be constrained by directory structures. I would suggest you stop using this "module" approach and either use namespacing as an alternative or turn those "modules" into separate composer libraries (which will then install them into `vendor/`).

Composer does not support wildcard expansion nor has there been a strong demand for it, since proper autoloading removes the need for weird arbitrary directory structures. It's unlikely to be implemented. But you can always make a PR yourself and submit it. If the impact is minimal and the solution is elegant (and covers all autoload directives), chances are it will be accepted.

**Comment by lauthiamkok** [comment]
`Code shouldn't be all over the place. Nor should it be constrained by directory structures.` I think this is a personal opinion and preference. It can be misleading for newbies. The structure above is actually the structure from Zend Framework 2.

**Comment by alcohol** [comment]
So it seems.. http://framework.zend.com/manual/2.0/en/ref/project.structure.html

Well, if it works for them, so be it. The second paragraph of my answer still applies :-)

**Comment by lauthiamkok** [comment]
Thanks. The link you attached is ZF 2.0. The current stable one is 2.4.

**Comment by alcohol** [comment]
Yes, a full overview page is not available anymore in the documentation of the higher versions. But it is still fairly in line with them.

Otherwise you will have to look at:
https://github.com/zendframework/ZendSkeletonApplication
http://framework.zend.com/manual/current/en/user-guide/skeleton-application.html
http://framework.zend.com/manual/current/en/user-guide/modules.html

**Comment by alcohol** [comment]
If you use the zend approach for autoloading, you will not have to modify composer.json at all. You merely have to setup the Module.php file properly for each module.

**Comment by lauthiamkok** [comment]
Thanks. for the links. `If you use the zend approach for autoloading...` does ZF has it own autoloading then? It does not seem comply with what you suggested.

**Comment by alcohol** [comment]
Yes they have some classes that register their own autoloading mechanics. Read these two sections on how to use it:

http://framework.zend.com/manual/current/en/user-guide/modules.html#setting-up-the-album-module
http://framework.zend.com/manual/current/en/user-guide/modules.html#autoloading-files

**Comment by lauthiamkok** [comment]
Have gone through them. Thanks., That makes sense then that we have to do it **manually** if we go for Composer, just as it says in the doc, 

```
"autoload": {
     "psr-0": { "Album": "module/Album/src/" }
 },
```

**Comment by Seldaek** [comment]
Closing as I don't think this is likely to be worked on sorry.

**Comment by jbnv** [comment]
Boo. 👎
