### ISSUE TITLE
‘quiet’ hides warnings

### ISSUE THREAD

**Issue by kamazee** [composer/composer#4393]
Currently ‘quiet’ option hides warnings. Is that correct? My understanding is that it should hide info-level messages (e.g. details of installation process with package names and versions and download progress), but should not hide potential issues, such as `composer.json` and `composer.lock` being out of sync.

**Comment by alcohol** [comment]
Quiet says "Do not output any message". So I think warnings also qualify as "any".

**Comment by Seldaek** [comment]
I'm working on this in https://github.com/symfony/symfony/pull/15772 which if merged will let us output some important things in quiet mode.

**Comment by dzuelke** [comment]
IMO, `--quiet` should never output anything. It's mostly for automated use by other programs; the exit status of a program is then used to indicate an error or not.

Also see #5031; not sure if that's related.

**Comment by hkdobrev** [comment]
I've seen both `--quiet` and `--no-output` or similar options to other CLI utilities. When both are available usually `--quiet` means no output unless error or warning and `--no-output` means absolutely no output, but you also have `> /dev/null` for that.

I think this is like that, because most CLI programs output something even without a `--verbose` option passed. When you want even more verbosity, you'd use the `--verbose` option (optionally with a level), but if you don't want anything on `STDOUT`, what other option do you have?

**Comment by dzuelke** [comment]
Well, `--quiet` should never ever, even with this change, result in stdout output, because warnings/errors belong on stderr.

So for "complete silence", `composer show doesnotexist --quiet 2>/dev/null`, is enough (`> / dev/null` won't help, you have to redirect stderr, not stdout).

**Comment by Seldaek** [comment]
Linking to https://github.com/composer/composer/issues/5031#issuecomment-194570198 just for future reference.
