### ISSUE TITLE
Using YAML for configuration?

### ISSUE THREAD

**Issue by olegstepura** [composer/composer#440]
Why didn't composer founders choose YAML? Json even does not support comments inside a file.
Yaml is proved to be the best choise for configuration and Symfony proved that.

But it's not too late to also allow yaml usage aswell. 4 example search for composer.json, if not found - for composer.yml

**Comment by hason** [comment]
An another implementation as composer plugin https://github.com/webuni/composer-yaml-plugin

**Comment by sandfoxme** [comment]
A slightly different approach: https://github.com/sandfoxme/composer-yaml
A wrapper command that allows composer to use yaml config directly instead of explicit conversion

**Comment by c33s** [comment]
[another one][1]. a fork of [gorw/composer-yaml][2] with [example scripts][3] for composer, yarn and box. i am using yaml over json many times. 

[1]: https://gitlab.com/c33s-group/yaml-convert/blob/master/README.md
[2]: https://github.com/igorw/composer-yaml 
[3]: https://gitlab.com/c33s-group/yaml-convert/tree/master/bin

**Comment by Chi-teck** [comment]
Something that should have mentioned here is that Composer is not just reading _composer.json_ file but also writing in it, for instance in `composer require` command. The `symfony/yaml` component does not support comments yet (https://github.com/symfony/symfony/issues/22516).

**Comment by mikeschinkel** [comment]
I was one of the ones calling for this. Since then we have decided to give up and just embrace JSON.  So no remaining interest in YAML from me.

**Comment by Chi-teck** [comment]
So far there is no Composer plugin that allows seamlessly replace _composer.json_ with _composer.yml_. All above mentioned solutions offer a way to convert the file manually which is kind of tedious. If Composer team strongly against Yaml format it would be nice to have an abstraction over the process of reading and writing data. So that third party plugins could provide an implementation for other configuration formats (yml, xml, neon, etc).

Nowadays PHP projects tend to have a complex _composer.json_  file with lots of dependencies and configuration options so the need of annotations has became increasingly critical.

**Comment by mfn** [comment]
I didn't see it mentioned but `_comment` has been [supported for many years](url) as an "[official workaround](https://github.com/composer/composer/issues/5364#issuecomment-221220653)".

I'm using this and TBH, in practice I found this sufficient and all one needs.

Sure, "true inline" comments sound nice on paper.

But I honor and actually to prefer the stance of the project: do one thing, do it good. As in: use one format, use it well.

The arguments about pluggable engines for these file formats are laudable but IMHO it's also a narrow view: whilst using composers PHP API to access the data I imagine the actual format wouldn't matter, however there are enough tools in eco system directly building on the file format.

This would fragment these cases and, the way I see it, tools directly building one the file format slowly or not at all.

I'm glad the project leader have a vision with a strong focus and I support this. The project has better areas where developer muscle is needed and I'm glad they're not getting distracted.

**Comment by Chi-teck** [comment]
> I didn't see it mentioned but _comment has been supported for many years as an "official workaround".

`_comment` is only supported on the top level of JSON structure. Composer will fail if you try to put a note inside `require` section.

> The project has better areas where developer muscle is needed and I'm glad they're not getting distracted.

That's just a personal preference. Isn't it? For many people this issue is the most critical one ever.

**Comment by xabbuh** [comment]
Every person's time is limited. So maintainers need to decide which features are worth to maintain and which are not. The Composer developers decided that being able to use different formats to configure your dependencies is not one of their priorities. IMO it's time to accept that and if that's really a critical missing feature for you, find other solutions around it.

**Comment by chr-hertel** [comment]
> For many people this issue is the most critical one ever.

That's just a personal preference. Isn't it?

**Comment by Chi-teck** [comment]
@chr-hertel, of course it is. People may use Composer in different ways and that's why "better areas" vary for them. While for someone this feature is critical for others it makes no sense. The issue was closed almost 8 years ago and a lot has changed since than. People are free to put more arguments in favor of this and project maintainers are free to decline this once again as well. That's I think the right way to keep good communication in any open source project.

**Comment by colans** [comment]
I don't see any linked pull requests on this issue.  If this is really important for folks, create one.  If the code is there (say adding support for YAML as well as JSON), the maintainers would be much more likely to merge it.  If you're not interested in doing the work, or paying someone else to do it, please stop complaining.

**Comment by Seldaek** [comment]
Please don't send a pull request, and please everyone stop wasting everyone
else's time here.

**Comment by seanr** [comment]
> Please don't send a pull request, and please everyone stop wasting everyone else's time here.
> […](#)
Maybe stop wasting developers' time by forcing us to do obnoxious workarounds for comments? After umpteen years, one would think you all would get that this is something we actually _need_? The current JSON format is not sufficient or we wouldn't keep bringing this up. Period. Just because you never comment your code or have to temporarily comment out a line but keep it for future use, etc...

**Comment by igorsantos07** [comment]
Two years later the latest complaint and 10 from the initial request, and here I am, managing and updating a mono-repo of sorts, with 78 dependencies. Those vary from major requirements, third-party packages, optional peer-dependencies, and stuff used in a dark corner or two. Comments are VERY needed for any organized codebase, and a dependency file is not different. On the big task of bringing most forgotten dependencies to their current versions, I'm having to do a **lot** of digging, because there's not a single hint on which one is used for what.
YAML would do _wonders_ here, as would any sort of official support for comments - e.g. allowing `_comment` keys in any place of the JSON file.

That said, as a summary of the hundred replies above, **there's no way Composer would support a second format** (be it officially or via pluggable converters), simply because lots of tools out there _expect_ a single JSON file and that _must_ be readable according to normal JSON and according to expected dependency repositories - that's why a `_comment` key breaks in the `require` section.
It's impossible to have another file, another file format, or a different syntax without breaking the rest of the environment. Allowing you to get rid of a JSON file in place of an auto-converted YAML would break the Composer ecosystem.

This is a decision that should've been taken 10 years ago, when this issue was first raised - and possibly even earlier than that, on the Composer inception. It wasn't, and it definitely won't happen now - no matter what's the community need for organizing their dependencies.
Be glad that Composer isn't like NPM which also rewrites your file, removing all blank likes you left. It could be worse.

I wonder if there's some very dirty solution for, say, Composer 3 (lol) which could allow this without breaking BC. I can't see any, and I guess Seldaek can't either, given his insistence on refusing this idea for so long. Notice he never _locked_ the issue and neither ignored it.

The only idea I can see is a replacement tool that "wraps up" Composer and yet, lives side by side. But that's _definitely_ too much trouble just to have a somewhat cleaner syntax and comments. No wonder why the best solutions so far are manual converters - it's not worth the hassle, different from what Yarn was with NPM for some time.

**Comment by forrest79** [comment]
Hi, for many years, we're using composer config file in NEON (https://doc.nette.org/en/neon/format - similar to YAML) format. During these years, we didn't get in any trouble with this. So I decided to add also YAML support and make it a public plugin. If someone is still interested to use `composer.yaml` (or `composer.neon`) you can give it a try - https://github.com/forrest79/composer-yaml-neon-plugin
