### ISSUE TITLE
Help needed to make our PHP modules written in C a composer ready.

### ISSUE THREAD

**Issue by vnkbabu** [composer/composer#4409]
Hi,
  I am from IBM. I maintain the PHP modules/drivers for IBM databases(DB2, informix). ex: ibm_db2, pdo_db2, pdo_informix. Curently we maintain these modules in PECL site.
These modules are written in C and in-turn depend on the installation of the IBM ODBC Driver. 

Now we are thinking of making these PHP extensions composer ready. All the existing composer ready packages and documentation talks about modules written entirely in PHP.

Can you help us with the steps or documentation or examples to make our modules written in C composer ready.

**Comment by alcohol** [comment]
Composer currently does not support installing extensions. There is a pull request in progress that aims to integrate/use [Pickle](FriendsOfPhp/pickle) within Composer to support something along those lines. But this is still a long way from being done.

**Comment by aderuwe** [comment]
It would be an amazing feature to have though!

**Comment by mistercorea** [comment]
Wouldn't that be little difficult? just a thought because you have to have all the extension object file(so or dll for all if not most popular enviornment) and injected to php.ini to load. is that even possible with composer? 

is composer smart enough to tell what environment you are in?
if so you would have to use project independent php.ini? 
I think those can be done then I don't see why not have different object files in different folder to load by autoloader.

just thinking out loud.

**Comment by agwidarsito** [comment]
Hmm... altering the php.ini file sounds dangerous to me. Unless Composer decides to whole-heartedly embrace that idea and maintain the whole php.ini file?

**Comment by mistercorea** [comment]
Just a thought because without including some so file i do not see how php can have C extension. 
It does not have to be global php.ini It can be local/project php.ini

**Comment by mistercorea** [comment]
Actually with little more thought I think there is way to include the folder and include all the C extension/object files.
