### ISSUE TITLE
Issue with recent build and mopa bootstrap command.

### ISSUE THREAD

**Issue by EduGuide** [composer/composer#4420]
Our deploy recipe is failing with the following:

```
php app/console mopa:bootstrap:symlink:less --env=prod --no-debug
Initializing composer ... PHP Fatal error:  Class 'JsonSchema\Validator' not found in phar:///usr/local/bin/composer/src/Composer/Json/JsonFile.php on line 160
```

This is using the most recent version of composer:

```
composer --version
Composer version 1.0-dev (7267b2ed9063ef64e7dda86421a928a802558fdb) 2015-09-14 14:48:45
```

When using a previous build:

```
composer --version
Composer version 1.0-dev (9f6fdfd703f433bd0777fd89fb4684908a6c4f06) 2015-09-07 16:55:30
```

the command runs without issue:

```
php app/console mopa:bootstrap:symlink:less --env=prod --no-debug
Initializing composer ... done.
Checking symlink ... OK
```

Nothing in composer.json has changed recently, and there are no new commits in the mopa bundle that fit in this timeframe.

Here's the version of mopa in use.

```
"mopa/bootstrap-bundle": "v3.0.0-beta4",
```

I can always copy back the older version of composer to get things back on track, but it seems like something has changed that is causing this to break.

Thanks!

**Comment by cs278** [comment]
It's probably caused by the recent deps update to Composer: https://github.com/composer/composer/commit/1215e194eda21bd225e0ab149930e03c332149cf#diff-1da2c7edc898c70e5a79a9997c98ceccR71 which pulled in a change from JSON schema: https://github.com/justinrainbow/json-schema/commit/344315fe13a015715976425402c3be86e45e6e6e

Due to this https://github.com/phiamo/MopaComposerBridge/blob/6f64e2f626bcdf2a6cab5d5c1be1d46a53905c13/src/Mopa/Bridge/Composer/Adapter/ComposerAdapter.php#L82-L90 code setting up the autoloader by hand and not doing it properly.

Seems somebody else has found the problem: https://github.com/phiamo/MopaComposerBridge/issues/15

**Comment by jkm9000** [comment]
Makes sense, thanks for the info.

**Comment by alcohol** [comment]
Sorry, not a composer issue :-)
