### ISSUE TITLE
`read -s` in post-create-project-cmd sub-shell does not allow input

### ISSUE THREAD

**Issue by sourcerer-mike** [composer/composer#4430]
When creating a project, the sub-shell (on OSX) via `read -s dbPassword` does not allow input.
It seems like the read command get's some empty data and the script continues with great failure.

What further information do you need?

**Comment by sourcerer-mike** [comment]
Some error output:

```
> ./bin/scaffold.sh
DB-Password:
Empty password! Please run ./bin/scaffold.sh again.
Script ./bin/scaffold.sh handling the post-create-project-cmd event returned with an error


                      
  [RuntimeException]  
  Error Output:  
```

**Comment by Seldaek** [comment]
I think the problem is simply that we do not (and as far as I know, we can not, but maybe that's not true) forward the tty/terminal to the child processes, so the child process essentially has no STDIN and can not prompt for input. We only forward STDOUT.

AFAIK if we forward STDIN it blocks forever waiting for input, at least on Windows, which makes it difficult to fix.

That said, if you build a post-create-project-cmd handler that is written in PHP and not a as an external process to be executed, then you should be able to prompt for user input via `$event->getIO()->ask('Here:');` for example.
