### ISSUE TITLE
Maven SNAPSHOT like "don't cache this version" support

### ISSUE THREAD

**Issue by alankent** [composer/composer#4437]
In Maven (Java world), if you put "-SNAPSHOT" at the end of the version number, Maven will not add to your local cache. This forces a download every time. (Either that, or when it sees -SNAPSHOT at the end of the version number it never checks the cache - same effect.)

What this allows is you can create say nightly stable builds. (If CICD tests pass, then push a new version of the code to your package repo.)  Obviously this could be hourly, on demand, etc.  If someone depends on version "3.2.1-SNAPSHOT" they are saying "I am willing to take a risk". It downloads every time (or a very short time to live?), meaning you can test against the latest code drop, knowing it is "somewhat stable", and knowing you got the latest nightly code drop.

Eventually when the version is finished, you release "3.2.1" (you remove the -SNAPSHOT suffix) and move on to "3.2.2-SNAPSHOT" for your nightly builds.

By putting in the version number, you still do all the version management per normal, but you have control over what to cache and what to not cache. I can depend on "a/a" 1.0 and it will cache; I can depend on "b/b" 2.0-SNAPSHOT and it won't cache.

I think the only effort is to either not cache versions with a "-SNAPSHOT" suffix (or force download each time regardless of if its in cache already or not), plus make sure version number comparison sequencing still works.  To make sequencing work, it does not have to be a "-SNAPSHOT" suffix like Maven - whatever works for Composer sequencing rules the best. But "3.2.1-SNAPSHOT" should sequence before "3.2.1".

Background reading (just google "maven snapshot" for more):
 * http://stackoverflow.com/questions/5901378/what-exactly-is-a-maven-snapshot-and-why-do-we-need-it
 * https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN8855

**Comment by alcohol** [comment]
I most other worlds (e.g. not Maven), we just add a build timestamp at the end.

**Comment by alankent** [comment]
Yes. Or a build number.

There are negatives of that however, such as you end up with large cache directories (unless Composer flushes old entries automatically). Every build generates another set of files. Using SNAPSHOT means you avoid this problem as it does not keep all the transient versions.

**Comment by Seldaek** [comment]
The way we avoid this largely, is that we offer via branch-aliases (https://getcomposer.org/doc/articles/aliases.md#branch-alias) a way to install from a branch directly, so you don't have to tag at all. Whenever you install you get the latest from the branch, there's no daily, it's just latest. And by default we install those as git clones so they don't end up in the cache and when you do an update you just fetch the few new commits instead of re-downloading the whole code.

**Comment by stof** [comment]
Note that Composer still installs a specific commit for the branch, which is the commit referenced by Packagist. This allows dependency locking to work in such case too (an install from lock will install the commit referenced in the lock file, i.e. the commit of the branch at the time dependencies were locked).
So this works best when you trigger a Packagist webhook each time your branch is updated (this is dead easy if your repo is hosted on Github or Bitbucket, not that harder for Gitlab, and possible for any repo by using a ``post-receive`` hook in your git server). In such case, Packagist will update its metadata immediately and publish the updated metadata to composer users in the following minute.

**Comment by alankent** [comment]
Ah! Thank you. So "git clone" does not cache. That had not registered before.

It is a problem for Magento 2 today, because of the way Magento works (not because of Composer). We want each "module" to have a separate version series, but we currently have lots of modules in one GIT repo. (We have >100 modules.)  So we either have to split into >100 GIT repos and check them out separately, or we really want to point at a subdirectory of the one repo.  E.g. we have a "magento/module-customer" composer.json file currently in a app/code/Magento/Customer sub-directory. 

Hence we were looking at the CICD pipeline generating say daily builds with ZIP files in a local repo, then use that as the source. I don't think we can use branch aliases today, unless we can somehow tell Composer "this one Git repo has multiple packages in it, and this is how you map your package name to the right subdirectory".  Alternatively we need to split the current big repo into lots of little ones, which seems the "Composer Friendly" way to do things.

**Comment by stof** [comment]
@alankent you could publish your daily builds as dev versions in your composer repository, if you take care of updating the metadata properly:
- use a dev version number (for instance ``3.2.x-dev``)
- set the ``time`` property when you update the code for your dev version (it should the the UTC time of the commit to get things right, so it will automatically update if you follow this)
- set the ``reference`` property for the specification of the ``dist`` of your package (it should be the commit sha)

If you only specify a dist url and no source url (because you have no git repo for individual packages), Composer will still be able to download a dist even for dev versions (and people can also force it with ``--prefer-dist`` even when there is a source url). In such case, Composer will still cache the download (useful if you reinstall the dependencies from a lock file for instance). But this won't cause issues when the dev version is updated, because the composer cache key is based on the reference, and so will change when you rebuild the nightly version the following day.

**Comment by stof** [comment]
this means you have 3 solutions here:

- keep a single monolith repository and build an infrastructure exposing individual packages as dists for composer. This is what I described above. Zend Framework was doing it in the past, and they faced many issues, because making mistakes when generating the composer metadata can lead to cryptic errors client-side when reading the corrupted data
- develop in the monolith repository, and split it automatically into other git repositories for each packages (which can then be processed by Packagist and Composer through the normal github integration). this is what Symfony does. It imposes to have a reliable system to split the repo. The hard part is that an updated split must preserve the current history of the package repository and create only new commits instead of rewriting the repo history from scratch. this can also cause some scaling issues. @fabpot has a closed-source system to do it for Symfony, and Zend Framework failed at building such a system in the past and fallbacked to making ``Import component from main repo at <date>`` commits rather than preserving the history in subtree splits. this also works best if you have the same version number for all packages, as this means you can then have a master composer package for the monolith, which is marked as replacing the same version of subpackages (and helps building the split system if it creates tags with the same names). ``symfony/symfony`` is a good example for that.
- split the repository into one repository per package, and develop packages separately starting from this point (abandonning the monolith repository). This is a huge change in the development process, but it is probably the best solution if you have different versions per package (how would you handle tagging of releases in the monolith repo if you only release a part of it ?). For reference, this is what Zend Framework is doing now. And I think they open-sourced the scripts they used to automate the split.

**Comment by alankent** [comment]
You are free to close this, but I do want to say this functionality has proved useful regardless in the Maven community. It changes your development workflow and opens up options as you are not required to change your source code repository structure to support Composer versioning.

But if you don't think you will ever implement this, they may as well close it! ;-)

**Comment by Seldaek** [comment]
Let's just say that if it's only about the caching, I don't think it's such a big win.. Because firstly we do garbage collect the cache dir every now and then, and second I don't like attaching special meaning like this to some versions. Then there is the fact that -SNAPSHOT is not supported at all right now as a version, and that semantic versioning (which we follow) would rather advocate for the use of build metadata for this IMO, like `1.4.0+nightlyYYMMDD`.

Just a bunch of reasons that overall make it a not so great sell to me.
