### ISSUE TITLE
include autoload.php in project before composer install

### ISSUE THREAD

**Issue by julien2512** [composer/composer#4452]
Proj4php project is working on composer compatibility.
We are trying to reduce impact on older applications.

A solution is to include vendor files on proj4php, so that it works before and after "composer install".
Is that the good way to make the project work with and without composer ?

There's not many vendor files for proj4php, the most important is autoload.

**Comment by alcohol** [comment]
I'm sorry but I am not sure what your question really is.

**Comment by jakoch** [comment]
Yes, one way of reducing impact on an older application is to provide an autoloader yourself, so that your project works standalone (decoupled from Composer and its Autoloader). This would work as a compatibility layer. But you have to communicate to old applications, how to include the "new" autoloader.

For instance, one library using a built-in autoloader is Swiftmailer. When you fetch it as Composer dependency, then the files of Swiftmailer are autoloaded via the Composer Autoloader. When you fetch the archive and use it as a static dependency, then you rely on the built-in autoloader by requiring the swift_required.php file. Ref. http://swiftmailer.org/docs/including-the-files.html

I suggest to simply communicate that your project is now available as a Composer package and let the "impact on the old application" happen. They just need to composerify themself.

**Comment by julien2512** [comment]
@alcohol : lol, don't you know I am french ? So bad english school teachers !

@jakoch : yes, you are right. It was only in case of a better solution or well-know approach. Let the community decide for us !

Thank you both for your help.

**Comment by judgej** [comment]
Thanks @jakoch There are certain sectors - academia for example - that have not caught up with *the composer way* yet, and this is who Proj4php still needs to support. We'll get there in the end by example though :-) From what I've seen, a PSR-4 autoloader built into a package does not need to be more than a couple of lines long - it only has one namespace to handle, and no configuration to read.

**Comment by jakoch** [comment]
You are welcome. And yes, a PSR4 loader is not a huge beast, so you get away with a couple of lines. You may find example implementations over at php-fig.org. http://www.php-fig.org/psr/psr-4/examples/
For instance, if you go with the closure based one, then you would only need to adjust the namespace to handle (and set a target folder for it, but you already have /src).
