### ISSUE TITLE
Stability of "composer/composer" package

### ISSUE THREAD

**Issue by vrann** [composer/composer#4463]
Hello,
are there plans to release stable "composer/composer" package any time soon? It is widely used in variety of environments, including production, but stability is still "alpha".

Thanks,
Eugene

**Comment by alcohol** [comment]
It's on the to-do list.

**Comment by vrann** [comment]
Thanks, do you have an idea how soon it would be done? 
No pressure, just want to understand what to-do list means.

Eugene

**Comment by alcohol** [comment]
It means it's in the back of our heads. There are some issues that we want to spend some more time/attention on first though, because we feel that a stable release would either really benefit from them, or simply really needs them. There is no roadmap set in stone though, so I cannot give you an estimate of "when" this might happen.

**Comment by vrann** [comment]
I see, makes sense.

Thanks for fast response!
