### ISSUE TITLE
composer won't install on Windows 8

### ISSUE THREAD

**Issue by rob-lindman** [composer/composer#4472]
I've downloaded the Composer installer for Windows from the website. Each time I try to install it, it reaches a point where it says it can't continue because applications are using files that need to be updated. This dialog insists that Windows Explorer needs to be closed. Windows Explorer cannot be closed because that's what runs the desktop. I've closed all the file browsers and the other applications, but this is sort of ridiculous.

**Comment by alcohol** [comment]
I'm sorry, but you're the first to report this. Also, it's not easy to support Windows. It's not exactly a developer friendly environment. Honestly, I have no idea why it would ask you close Windows Explorer. There is a small chance @johnstevenson might be able to help you.

**Comment by rob-lindman** [comment]
![fail](https://cloud.githubusercontent.com/assets/2185150/10232699/db4e46aa-684f-11e5-8064-f9298c93fb8c.jpg) I've attached a screenshot. 'easy' is in the eye of the taskmaster, I suppose. I've developed for Windows, Linux, Mac, Android, and a few other odd environments. YMMV. Anyway, that's all the detail I have on this.

**Comment by alcohol** [comment]
Well, if it was easy, you would just run one of the copy-paste one-liners to download the Composer binary and drop it in a directory in your path and you're good to go. Alas, it's not that easy on Windows I guess ;-)

**Comment by johnstevenson** [comment]
You are getting this message because you are trying to install the Shell Menu feature and the installer needs to register the shell extension DLL with Windows Explorer. To ensure that this can happen we use the Windows RestartManager API: https://msdn.microsoft.com/en-us/library/windows/desktop/cc948910(v=vs.85).aspx

However it can be a bit flakey sometimes, especially if the Programs and Features Control Panel window is open. If not, restart you machine. If this doesn't work then you have possibly got Windows Explorer configured in a way that the RestartManager doesn't understand, so you will not be able to register the shell menu.

Sorry I cannot help any more than this, but if a standard Windows API doesn't work it is very hard to diagnose.

**Comment by agwidarsito** [comment]
Anything in your Windows Event logs @alcohol ?

**Comment by alcohol** [comment]
I don't use Windows...

**Comment by f22hd** [comment]
I solved this issue with simple way .
when the popup appears for closing window explorer , close all windows then go to taskbar  , click right and start task manager , after that open proecesses and find explorer.exe , and kill it or end  the process , and click retry on that popup :+1:  . After finishing from installation , start task manager again and click on file choose new task write into it explorer.exe , for run the explorer again . 
sorry about my English .
thanks
