### ISSUE TITLE
Multiple "vendor" folders

### ISSUE THREAD

**Issue by Ziggizag** [composer/composer#4493]
Hi,

I use Composer to manage my Yii2 applications. To spare server space and resources, I would love to keep core framework files as well as its "default" set of extensions shared between individual applications located in many virtual hosts. But on the other hand I would like to let each and every individual application to keep it's own set of "private" extensions.

Thus is my question - is there any way to let an application use two independent "vendor" folders - one shared between many apps and one dedicated to a single app? That would require and application to use two different ComposerAutoloader instances.

Any idea?

**Comment by rquadling** [comment]
Calling the 2 autoloaders should be OK as long as the same version of composer is used (just in case of bug fixes in composer results in a different interaction with the classmaps/etc.). Make sure you call the local project's autoloader first and then the defaults autoloader. This will deal with any projects using a different version of a default package as it will load first.

I would recommend using the optimize option for the dump-autoload so full classmaps are generated.

Other than that, I think all should be OK.

**Comment by Ziggizag** [comment]
Thank you very much for your prompt feedback!

**Comment by curry684** [comment]
You could download the core framework files and the default extensions into a separate folder on the server, and load them from there with Path repositories. This would cause all your consumer packages to symlink/junction to the shared implementation.

**Comment by MatteoOreficeIT** [comment]
> Calling the 2 autoloaders should be OK as long as the same version of composer is used (just in case of bug fixes in composer results in a different interaction with the classmaps/etc.). Make sure you call the local project's autoloader first and then the defaults autoloader. This will deal with any projects using a different version of a default package as it will load first.
> 
> I would recommend using the optimize option for the dump-autoload so full classmaps are generated.
> 
> Other than that, I think all should be OK.

Hello @rquadling , I know this issue is closed, but I have only a question about possible clashes of this approach, I know some classes or functions in various files in `vendor/composer` folder have random names, in the scenario we are building and requiring two or more `autoload.php` at runtime , should we rest assured  that no conflicts can occur at runtime between class or function names ? ( I think each composer dump autoload runs don't know anything about the other )

I think would be nice to have in the documentation a note about the fact the design allows including more the `autoload.php` and possible caveats if there are 

Thanks
