### ISSUE TITLE
Composer inside a framework

### ISSUE THREAD

**Issue by gregfr** [composer/composer#4527]
I'm developping a PHP framework, I'd like to include Composer to manage packages inside.
Is there documentation for that?
Thanks in advance

**Comment by alcohol** [comment]
No. Just use Composer like everyone else, don't try to make things prettier than they need to be.

**Comment by gregfr** [comment]
Not very open mind :(

**Comment by alcohol** [comment]
It is just not a good idea.

**Comment by Seldaek** [comment]
I don't really see why this wouldn't be a good idea. In some cases like WordPress plugins for example there is no way you could require people run some CLI tool to install them. Developers are not the only people using computers.

It's not very easy though, and not documented at all right now, you'd have to dig in to figure things out. Alternatively you could just use a composer.phar inside your app and run it as an external process instead of binding it as a library. It's probably a lot more reliable over time as we don't really provide many guarantees about the stability of internal APIs.

**Comment by alcohol** [comment]
The latter you suggested would always be my recommended approach. And exactly for the same reasons. It's better documented, the "interface" rarely changes, and it's a lot easier to understand. This is also what I meant by "just use Composer as you would usually do" but perhaps I should have elaborated on that.
