### ISSUE TITLE
Is it possible to get zip files for a tagged release on BitBucket.

### ISSUE THREAD

**Issue by rquadling** [composer/composer#4577]
Hi.

I develop a package for our developers and it is held on bitbucket.

Currently, they all use 'dev-master' as the version. Each time they download an update, composer is doing a git checkout from the head of the master branch. All as expected.

What I would like to do is use zip files like GitHub/Packagist.

Is this possible? Ideally in an automated way.

I can't seem to configure my main app to do anything different. I've said use the version ``~1.0`` and that has correctly got the tagged version (though it has a commit hash that doesn't exist in the repo! Not sure what's going on there!). But it has done a checkout, not a download.

**Comment by stof** [comment]
there is a ``--prefer-dist`` option in Composer, to force it to download the archive even for dev versions (and also a configuration setting, as explained in the doc). By default, composer does not download archives for dev versions.

Having a commit hash which does not exist in the repo looks weird (and it may be the reason that the download was not used).

Note that archive support currently does not work for private bitbucket repositories (because the bitbucket driver does not support authentication currently and so cannot access them). See https://github.com/composer/composer/issues/4398

**Comment by kanevbg** [comment]
> Note that archive support currently does not work for private bitbucket repositories (because the bitbucket driver does not support authentication currently and so cannot access them). See #4398

Can that be implemented now or bitbucket is still missing the needed API?
