### ISSUE TITLE
Old packages loaded from cache when using dist option for private packages

### ISSUE THREAD

**Issue by bacinsky** [composer/composer#4581]
The issue I run into is that my private packages have dist url option in theirs composer.json which never changes e.g. like https://something.com/develop.zip, but composer stores it to its cache like dev-develop-zip so even the package gets updated the composer doesn't notice and loads the old dev-develop-.zip. I think it should be stored under hash name no matter of the dist url.

The true is that I have to use prefer dist option because the default cloning strategy is trully useless when you have hundreds of packages with dependencies on big repos like ZF2, it's horribly slow and wasting of a disk space.

**Comment by alcohol** [comment]
I'm sorry, but without any further information, I can only conclude, that you are doing it wrong.

**Comment by stof** [comment]
specify the ``reference`` for the dist version, to  specify the reference for which the archive was built. This way, changing the reference will change the cache key.
Composer uses the commit hash as reference when the source comes from a git repo.

In your case, the reference is always empty, which is why the cache key does not change (and also why the filename ends with ``-.zip``, as the reference comes between the dash and the dot)

**Comment by bacinsky** [comment]
Thank you for reply, but I don't understand.
I have private satis package repository and the dist option in my packages json configs like:

```json
"dist": {
    "url":  "https://example.com/foo/bar/get/develop.zip",
    "type": "zip"
},
```

I'm calling `composer update --prefer-dist` and composer says:

```bash
Updating dependencies (including require-dev)
- Removing foo/bar (dev-develop 1b96a1f)
- Installing foo/bar (dev-develop 7010127)
Loading from cache
```
But it's lying, it should download new archive from the dist url option but it loads that weird dev-develop-zip file. I don't understand why composer is not storing that archive under commit hash.

I don't know what do you mean by specifiing the `reference` exactly. I don't want to update composer.json dist option for every commit and I don't know what am I doing wrong.

**Comment by bacinsky** [comment]
I'm digging into this a little bit, seems like something is wrong with the Satis. I see that the reference option for dist in the packages.json is null, but how to fix that?

**Comment by stof** [comment]
@bacinsky specify it like that:

```
"dist": {
    "url":  "https://example.com/foo/bar/get/develop.zip",
    "type": "zip",
    "reference": "something related to the version, for instance commit hash"
},
```

And it does download it from the specified URL. ``dev-develop-something.zip`` is the name of the file Composer used to store it in the cache.

**Comment by stof** [comment]
well, if you want to provide dists for your packages, you should not specify the URL in the composer.json of your repo (this would indeed not be practical). The proper setup would be to rely on Satis or Toran Proxy to generate the archive, and registering the Satis/Toran Proxy repository instead of registering the VCS repository of the private package in your project (this repo would be registered in Satis/Toran Proxy)

**Comment by stof** [comment]
btw, if you want to have locking working properly for your package, you should not keep the same URL for each update btw, as it would prevent downloading the proper locked code

**Comment by bacinsky** [comment]
I though that Satis is handling the references for dist somehow automatically. I'm just regenerating the Satis on a package repo push, never mind I have to check the docs again and reconfigure my setup. But it would be nice to have a warning for this behavior of the composer cause it silently looks like everything is alright.
