### ISSUE TITLE
Add a `--force-dist` option to avoid cloning

### ISSUE THREAD

**Issue by mikaelrandy** [composer/composer#4591]
As cloning from source is a bad practice for production deployment (time spent, dependencies on VCS, ...), i propose to add a "--force-dist" option to "install" / "update" commands who act as "--prefer-dist", but who will not fallback on "source" install, and raise an exception instead.

Today, the only way to detect source download is a weird trick who look for "Cloning from" in the command output :/

**Comment by alcohol** [comment]
That's because using Composer in production is a bad practice. Thus the logical conclusion is, there is no need for this command.

**Comment by mikaelrandy** [comment]
I use an overhead of Capistrano, who build an entire archive for my project before deploying it.
I don't use Composer directly in production.

But the result is the same : when i want to deploy, my deployer as to build the archive, who mean install vendors.

At some point, i want to avoid download from source, and an option for this seems a good idea

**Comment by jubianchi** [comment]
> That's because using Composer in production

Yes, this is true but we still need to use it at some point to build production artifacts. 

I totally understand the need and the proposed solution seem good to me. 

The build machine would then only have to depend on a composer repository (be it satis or any other) and won't require any VCS client nor deploy keys or whatever. If the dependency artifact is available on the repository then the production artifact can be built. If not, the build fails.

I'm :+1: here.

**Comment by alcohol** [comment]
:-1:.

**Comment by alcohol** [comment]
I still see no need for this. Your build server can generate a deployable package. From what it generates this package really makes no difference, source or dist.

**Comment by alcohol** [comment]
And if your private repository offers dists for all dependencies, then `--prefer-dist` does exactly what you need.

**Comment by Seldaek** [comment]
I'd also be against adding more options to something that to me has no clear value, if prefer-dist fails then it means you have no dist available, and I don't see how failing the build entirely is better than installing from source.

If you want to avoid vcs mess in your deployable archive you are building you have a few options:

- `rm -rf vendor/*/*/.git` which cleans up before archiving
- `PATH= composer install --prefer-dist` which should make the git downloader fail as it won't find the git process.

**Comment by mikaelrandy** [comment]
I was thinking about arguing, but it's seems the decision is already taken ...

But, if you are interested in my opinion :
* the `--prefer-dist` option could fallback on source installation
* i dont understand why i should have to put some weird trick around installation to prevent unwanted operation from composer

**Comment by Hywan** [comment]
@Seldaek What is the exit status when `--prefer-dist` fails to install everything from the tarballs? Maybe this is something that could be useful?

**Comment by Seldaek** [comment]
I understand that prefer-dist doesn't do exactly what you want, but I don't agree that composer should have options to do anything that's imaginable. I don't really get what the problem is to begin with as having some git-installed dependencies isn't such a huge deal IMO, but there are also a set of workarounds available if you really think it is critical to your use case, so I don't see it as an important enough use case to mandate being in composer and something I'll have to maintain forever, sorry.

**Comment by Seldaek** [comment]
@Hywan the install is successful, so it's 0, prefer-dist just says to prefer dists, not to fail in case dists can't be used. If you make sure git is not accessible in the path (or add a script called `git` in the PATH that will just `exit 1` always for example) then it should fail to install and you'll get a non-zero code.

**Comment by Hywan** [comment]
@Seldaek So, interesting. Removing `git` from the `PATH` will mimic `--force-dist` in some way. Is it a solution for you @mikaelrandy?

@Seldaek I also asked on Twitter and Reddit if this is a situation Composer's users encounter often or not. No offense, no trolling, this is just to clarify. Personnally I never met this situation but this is to get a better overview. Here is the link: https://www.reddit.com/r/PHP/comments/3s9wvx/does_a_forcedist_option_might_be_useful_on/.

**Comment by omansour** [comment]
I think this should be a very useful option :+1:

**Comment by Seldaek** [comment]
@omansour no offense but having a colleague come and +1 does not really help convince me that the use case is valid. If you have more arguments feel free though.

**Comment by omansour** [comment]
(sorry this comment wasn't finished)

@mikaelrandy already explain. but at some point, preventing cloning in the build server save time and CPU - speeding up our deployments. In our business it can be a big deal. I can suppress git of the integration server, backhole github.com at the network level, but it's mutualised with others things, I cannot do that easily. 

Clearly we live happily without this option, and we will continue. The PR is only to gain comfort. If it costs too much, I can understand. But I don't think so.

**Comment by Seldaek** [comment]
I am not telling you to disable git for everything, you can just pass a different PATH environment to composer when running it to build packages. But down the line it's so unlikely to end up with a --prefer-dist that really uses git clone because 99% of packages are on github and those always have dists.

**Comment by omansour** [comment]
yes. it's a possible workaround too.

**Comment by mikaelrandy** [comment]
@Seldaek i go your point, but i think `--force-dist` is just an extension of `--prefer-dist` ;)

I became aware of this need the day where Github crashed and i have realized some of my packages (from a local satis) was not available anymore, but no warning was raise before it was too late.

I understand there is a lot of workaround : i use one of it ;)

**Comment by GBirch** [comment]
Just came upon this discussion, and obviously it's old.  But it seems worthwhile to note the real use case:
Installations of Drupal 8 are now commonly managed using Composer (thank you!).  The specialized hosting providers for Drupal: Acquia, Pantheon and Platform.sh all use Git for pushing code to their servers and moving code among different environments (and we try really hard not to run our build process in prod).  If you inadvertently include a git submodule in your vendor directory, that code is not uploaded, leading to all kinds of difficult-to-debug ugliness.  For us it would be much better to fail the build than to have everything work fine locally and then find out that it doesn't work remotely because we have a stray submodule.  Unless I miss my guess, this problem is present for a LOT of installations of Drupal.

**Comment by omansour** [comment]
a simple workaroud we did to manage this issue was parsing the output of the composer installation. For example in a naive way : 

```
#!/bin/bash

filename=$1

nbErrors=`cat $filename | grep 'Now trying to download from source' | wc -l`

if [ $nbErrors -eq 0 ]
then
    echo '[OK] All dependencies are correctly installed'
else
    echo '[ERROR] Some dependencies are downloaded from the source code'
    exit 1
fi  
```

**Comment by GBirch** [comment]
Nifty, thank you!

**Comment by frob** [comment]
Everything GBirch said. +1

**Comment by Radon8472** [comment]
> And if your private repository offers dists for all dependencies, then `--prefer-dist` does exactly what you need.

That is not true.

I had this issue exactly NOW....

When you have installed a package once from source, and you not like to switch to dist install you can add  `--prefer-dist` and it shows `Nothing to install or update`.

Even if you downgrade and upgrade the pack, it still takes the settings for the install-typ that was used before.

Only complete uninstalling and re-installing the package switches from `"installation-source": "source",` to `"installation-source": "dist",`.
Otherwise you always get the .git dir, and the files exluded by `.gitignore` rule `export-ignore`.

So I think `--force-dist` would be very usefull.

**Comment by Seldaek** [comment]
@Radon8472 You can do `composer reinstall foo/bar` to reinstall the package, which will select the default installation source again, or combine with --prefer-dist or --prefer-source if you wish to switch.

**Comment by pkly** [comment]
hey, maybe reconsider this? a while back composer would stall since GH would choke it with ratelimits, but sometimes that's no longer the case, as such we didn't realize but our libraries kept getting cloned, making the image size baloon from 400mb to over 3gb as it would clone repositories containing tools and phars, as of now I'll have to probably add some sort of limit on the size of the directory created by this command, but it's really not a great thing it silently clones everything

**Comment by Orrison** [comment]
A consideration for reopening this in a real world example our team experienced today.

I noticed dist install failures starting yesterday going late into the night. Mostly just locally so I ignored it. Without looking too deep into the cause, I assume it is some form of outage along the chain of composer install, not uncommon.

The issue this caused is that this did happen for a single one of our deployments resulting in the `laravel/framework` package being installed from source.

Because it was installed from source certain distribution scripts and excludes were not run, resulting in our final package shipped to include the files in this folder https://github.com/laravel/framework/tree/12.x/bin, which contains a `splitsh-lite` file with 8+ critical CVEs.

I wouldn't expect the maintainer to do something about that file normally. That is what the distribution scripts and ignores are for, to NOT include files that are used for development / CI that are not intended to be included in the final build.

So without a `--force-dist` or alternative we are open to a random CVE audit nightmare.

**Comment by Seldaek** [comment]
Not sure we need a --force-dist flag, but possibly a way/config option to disable fallback to source yes, especially if we do further things like signed releases then source installs become possibly even more of a liability or will break in more cases like the post above.

Reopening but no clear plans yet.
