### ISSUE TITLE
Homebrew Installation Instructions

### ISSUE THREAD

**Issue by jcampbell05** [composer/composer#4631]
We have setup a tap to allow you to easy install composer via homebrew. Would be a great new way of installing.

https://github.com/Supmenow/homebrew-tap

**Comment by stof** [comment]
Well, there are actually already ways to install it via homebrew. And this was documented in the official doc in the past, until https://github.com/composer/composer/commit/d26f817cfde9da7057e64be5d748803f26948c26
The issue is that the homebrew instruction were changing all the time, making it impossible to document them in a working way

**Comment by jcampbell05** [comment]
In theory if done right all that is need to be done is tell them to run `brew install composer` and `brew tap <Offical Homebrew Repo>`

**Comment by alcohol** [comment]
There really is no need to document a Homebrew install step. It adds absolutely nothing of value. I love Homebrew myself, and use it every day on my Macs. But I would never use it to install `composer`, and I would actually recommend anyone on a Mac to **not** use Homebrew to install Composer.

**Comment by jcampbell05** [comment]
Just out of interest what are the reasons not to install it via Homebrew ?

**Comment by alcohol** [comment]
We've had too many issues in the past because of it. It really provides no benefit whatsoever also. The existing "installer" can be ran in a single line from the command line. It is much more flexible also. Nor does it depend on a third party keeping their installation instructions up to date. Also, it does not limit you to just the latest alpha version. You can pick any of them, or just go for dev-master.
