### ISSUE TITLE
Composer don't work and need signature

### ISSUE THREAD

**Issue by mckenziearts** [composer/composer#4641]
[Composer\Repository\RepositorySecurityException]
  The contents of http://packagist.org/p/provider-2013%24f3b3f612b935dd06fc16c0482f4421a3bbf0b5814d8c54fef6e
  58b24224a4dcc.json do not match its signature. This should indicate a man-in-the-middle attack. Try runnin
  g composer again and report this if you think it is a mistake.

**Comment by stof** [comment]
Well, does it happen only once, or regularly ? If it is only once, it is OK (it happens sometimes that this fails for a given request in case of some race condition, even though this should not happen often).
If you get it everytime, it could be because of a proxy messing up the response (and so making it not match the signature checked by composer as the file has been altered by a MitM performed by the proxy)
