### ISSUE TITLE
Command to show/check required PHP version and exts

### ISSUE THREAD

**Issue by mishak87** [composer/composer#4658]
**Use-case:**
Composer is not very friendly when it comes to generating matching environments for application.

``` sh
composer show -i -t | grep -o "\-\-\(ext-\|php\).\+" | sort | uniq | cut -d- -f3-
```

That command gives me list of all required versions of all extensions and php like this:

```
ext-curl *
ext-iconv *
ext-pdo *
ext-tokenizer *
php >= 5.3.0
...
php >=5.3,<8.0-DEV
...
php >=5.6
```

It still needs bit of parsing and sorting to get all information for building matching environment.

**Suggestion:**
Make composer more machine friendly (CI, CD etc.)
1. Add command to check if all ext/php version requirements are satisfied.  
   It would help if composer could check if all extensions and php are matching (non destructive way). So far this is done only on install or update (destructive operations) and only if some dependency has changed or is missing.
2. Add command to list all ext/php version requirements.  
   Provide list of final version restrictions per ext/php.

**Comment by alcohol** [comment]
Composer already checks php/ext requirements. You simply put them in your "require" section. So, not really sure how that doesn't address your concerns already. Please do elaborate.

See also https://getcomposer.org/doc/02-libraries.md#platform-packages

**Comment by mishak87** [comment]
Thanks I noticed platform packages when researching this issue further.

AFAIK platform requirements are only checked for installs and updates of affected packages, please correct me if that's not the case.

I am trying to create CI process using [docker](https://www.docker.com/). Having image with minimal set of extensions reduces build time and size of image compared to generic image.

I would like to use just `composer.lock` to detect if image matches requirements without installing anything. (for checking if image matches requirements)
Second use-case is to collect platform requirements in aggregated form (one set of min, max constraints instead of N) for building image.

Flow looks like this:

1. Project is installed using secrets in PHP cli only image ignoring platform requirements except PHP of course.
2. Tailored image is build based on *requirements*.
3. Tailored image is checked if matches platform *requirements*.
4. Result is copied to tailored image.

By *requirements* I mean facts collected from `composer.lock` `require` packages sections.

**Comment by alcohol** [comment]
Composer was not built to manage php extensions, but there is a PR open that attempts to fill this gap. That still does not quite resolve your use-case though. If this is something you need, you will have to contribute it yourself.

**Comment by mishak87** [comment]
Tagging #3836 we share same need for machine readable set of aggregated constrains

**Comment by Seldaek** [comment]
Ping @dzuelke because he did a lot of stuff relating to this for Heroku builds.

**Comment by Wirone** [comment]
I am interested in this feature, here's use case:

- We define our platform requirements (php, ext) in `require`
- We use external vendors, each of them can define its platform requirements
- `composer.lock` is generated
- In our organization we have to list all requirements when we order new machine for our app, so at this point I would like to be able to list all platform requirements which should be met on target platform, so I can make sure everything will be installed in order to work. Since I work with many apps and have many extensions installed it is likely to miss some of the requirements from vendors because they can be satisfied by my localhost without my knowledge. But when we prepare requirements for production machine we need to make sure that we list all platform dependencies.

@mishak87's command did the trick after some tweaks:

```
composer show -t | grep -o "\-\-\(ext-.\+\|php \).\+" | sort | uniq | cut -d- -f3-
```

(`-i` is deprecated and it was listing `php*` packages like `phpunit/phpunit`), but it would be really helpful to print **resolved** platform requirements (minimum/maximum PHP version and so on) in user-friendly way.

**Comment by Wirone** [comment]
@Seldaek it is even harder on Windows with Cygwin. Command presented above does not work since `grep` does not handle `─` (U+2500 : BOX DRAWINGS LIGHT HORIZONTAL used by Composer's dependency tree) as `-`, also control codes must be removed before grepping. So I ended up with:

```
composer show -t | remove_control_codes | grep -o "──\(ext-.\+\|php \).\+" | sort | uniq | sed 's/─/-/g' | cut -d- -f3-
```

where `remove_control_codes` is an alias for:

```
sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g"
```
(found somewhere when I was having issues with `git log` output).

**Comment by Wirone** [comment]
Another update on topic. "Final" command for getting all requirements (both from your project and vendor packages) is:

```
(composer show -t --no-ansi && composer show -s -t --no-ansi) | grep -o "\-\-\(ext-.\+\|php \).\+" | sort | uniq | cut -d- -f3-
```

With Composer v1.5.5 it prints some error (#6902), but you can ignore it.

**Comment by Seldaek** [comment]
Composer 1.6 comes with a new command `check-platform-reqs` which does check the platform dependencies so I'm going to close this as done.

**Comment by mcasto** [comment]
I'm not sure this should have been closed. `check-platform-reqs` doesn't do what I want with regards to this topic. What I want is to know, based on the installed packages, what is the minimum version of PHP I need. That way, if I'm setting up on a server I don't have control over, I can verify that my code will run using the version of PHP that's available on the server.

`check-platform-reqs` checks my (dev) system to see if it can run the packages needed. So, when I run it, I get this:
`ext-curl     8.2.3   success 
ext-json     8.2.3   success 
ext-mbstring 8.2.3   success 
ext-openssl  8.2.3   success 
php          8.2.3   success `

Unless I have SSH or direct access to the command line on the target server, I can't run `check-platform-reqs`, so it's of no use to me.

The command posted by Wirone, though, tells me that, in the code I put together, the highest version of PHP required by any of the dependencies is 7.3 ... so before I upload to the target server, I can verify that it's running 7.3+ (even if I have to upload a file that displays phpinfo to see its version then delete that file, it's doable).

So `check-platform-reqs` is not at all helpful for my use case.

**Comment by fredden** [comment]
@mcasto can you set `config.platform.php` to be the version number of your target system and then use `check-platform-reqs` locally?

If you're looking at compatibility between PHP versions, you may like to look at https://github.com/PHPCompatibility/PHPCompatibility, which is a PHP_CodeSniffer ruleset capable of detecting incompatibilities between specific PHP versions and a codebase.

**Comment by mcasto** [comment]
Good call, @fredden. It doesn't seem to work (at least on my system). The check-platform-reqs still sees my PHP version as 8.2 after I set config.platform.php to 7.3 ... I may dig a bit deeper into that and see if I missed something.

I'll check out the PHPCompatibility repo too. Thanks.
