### ISSUE TITLE
Why composer update download json again and again?

### ISSUE THREAD

**Issue by netroby** [composer/composer#4678]
Why composer update download json again and again?

Every time run composer update, composer will download json from zero to end. 
It waste time and waste bandwidth.

Why not provided an api show the sha1 of the json file.

If the local cached json file matched the server side json file. 
just use local cached json. 

It not need to download json again and again from server.

**Comment by alcohol** [comment]
Composer does cache a lot already. But the frequency of updates on Packagist is incredibly high. That is not to say that there might be room for improvement, but the gains are quite marginal, while they would require significant effort and modifications to the current setup. In other words, the means do not justify the end in this case.

**Comment by stof** [comment]
we are already doing exactly what you suggest about using a hash of packagist files to avoid redownloading them when the cache already has them.

**Comment by netroby** [comment]
For bad network. we need waiting for 30 minutes every time run composer update. terrible experience.

**Comment by alcohol** [comment]
But you don't have to run `composer update` that frequently. This is why you have a composer.lock file. Running install is *much* more efficient/faster.

**Comment by hirak** [comment]
I have same problem. So, I made a mirror site of packagist.org -- https://packagist.jp (Japan mirror)
packagist.jp is served by CDN(cloudflare). Nice experience.

```bash
$ composer config -g repositories.packagist composer https://packagist.jp
```

Asia is too far from French(packagist.org). It takes over 1.3 seconds for downloading each json.
This is because network latency(RTT). `composer.lock` is not the solution.

I found mirror sites in China, like packagist.jp.
- http://toran.reimu.io/
- http://packagist.cn/
