### ISSUE TITLE
Package name transfert

### ISSUE THREAD

**Issue by Soullivaneuh** [composer/composer#4693]
This is just an idea, comments and debate are needed. :+1: 

The idea is to add a "Transfert" option to composer for package namespaces to be able users to download packages on both old names and the new one.

Concrete case: PHP-CS-Fixer.

This package as moved to FriendsOfPHP GitHub's namespace: https://github.com/FriendsOfPHP/PHP-CS-Fixer

But the Packagist name is still [fabpot/php-cs-fixer](https://packagist.org/packages/fabpot/php-cs-fixer), IMO to avoid breaking downloads.

With this option, this library could transfert the name and composer would be still able to download with the old name.

In addition, we could add a warning to tell users that the namespace has changed.

What do you think?

**Comment by Seldaek** [comment]
We already have the abandon feature which warns people of the change, so that is a decent option for renames, but overall I don't know if it's really necessary to rename this.. It's just the package name, it's known as such already and that name is probably in a few blog posts and whatnot, change doesn't bring much and only creates confusion in this case IMO.

**Comment by Soullivaneuh** [comment]
For the question about "should I rename my package or not?", it's belong to the maintainers IMHO. I think the opinions will be never the sames between each ones.

> We already have the abandon feature which warns people of the change, so that is a decent option for renames

Well, AFAIK, the problem with the abandon feature is the related GitHub repository have to still exists. A I right? Here, I'm talking about a *moved* repository.

**Comment by Seldaek** [comment]
You can very simply redirect the old package name to the new repo URL, 
if the repo didn't change and it's only about the package name change 
that is not an issue, both packages should continue to update..

**Comment by stof** [comment]
@Seldaek but it means that Composer could technically install the code twice if both the old name and the new one are used (and even ``replace`` won't help unless you go back to a very old version of composer due to the regression in the solver regarding conflict rules when applying an optimization based on the root composer.json. Thus, old releases will be registered on Packagist for the new name too, and they cannot have the replace rule).
The proper way to maintain both names IMO is to create an abandonned metapackage with the old name, making it require the corresponding release with the new name.

**Comment by Seldaek** [comment]
Yes a metapackage is probably cleaner, but it can be a bit more work to do than just marking the old one abandoned. IMO it's enough if you install both it means you updated and if you update you'll get the warning about the old one being abandoned. If you ignore that and get weird issues I don't really care anymore I have to say.. We do what we can here. 

I think there are enough tools in place to handle renames cleanly, even though I still think in most cases renames are a bad idea.

**Comment by stof** [comment]
@Seldaek if you install both packages, you might have multiple class definitions, which might do weird things if they are at different versions

**Comment by Seldaek** [comment]
Yes I understand the problem very well, but please see my comment above.

**Comment by Soullivaneuh** [comment]
Changing names could be useful for proprietary repository transfer IMO.

In this case, the old repository does not exists anymore and the abandon tricks would not work, would he?

**Comment by Seldaek** [comment]
As said in https://github.com/composer/composer/issues/4693#issuecomment-163942716 you don't need two repos, both packages can use the same. I'm not sure what you mean by proprietary repo transfer though. But anyway I feel like we're just wasting our time discussing a non-issue here. Are we trying to fix something that's broken or to create a problem that can then be fixed? Because I feel like we have enough other real problems to fix as it is, don't need to make some up :)

**Comment by Soullivaneuh** [comment]
Just trying to understand well. :-)

So if I'm right, on Packagist, I can have two package with the same repo url like this:

 - `dummy/old-name` -> github.com/dummy/project
 - `dummy/new-name` -> github.com/dummy/project

In this case it would be indeed enough even if for repo transfert (url change).

**Comment by Seldaek** [comment]
Yes that works just fine.

**Comment by Soullivaneuh** [comment]
Ok thanks!

Last question: Maybe do you have a doc for how to make that properly, step by step?

**Comment by Seldaek** [comment]
For the rename: Change name in composer.json, submit package again, 
done. Then IMO the best is to mark abandoned the old package name.

For the repos transfer: Rename/transfer repo, update URL on packagist, done.

You can combine both obviously.

**Comment by Soullivaneuh** [comment]
That's great. I'll take a look to propose a doc PR about that one time.

Thanks for your help!
