### ISSUE TITLE
Global Config?

### ISSUE THREAD

**Issue by Baachi** [composer/composer#4752]
Hey guys!

I have a quick question. We use currently toran proxy, which does a cool job! We configured toran to act as a proxy between the developer pc and packagist. 
Currently we have to set the `repositories` section in the `composer.json` for each project, but is there a way to do it globally?

Hopefully i was clear enough. :smile:

**Comment by Nek-** [comment]
Hello sorry to not have an answer to your question. Did you try inside the `~/.composer/composer.json` ?

You can have support at toran@nelm.io (https://toranproxy.com/support). 
ping @Seldaek

**Comment by Seldaek** [comment]
You *can* set it globally in your global config (that's config.json not composer.json @Nek-) use  `composer config -ge` to open that file in an editor. However I would advise against doing so because it will mean that you end up with your toran URLs and all in all composer.lock files you have on your machine, no matter if they are for a company project or an open source project you might be working on. That's kinda fine as long as you don't publish the lock files in open source projects, but if you do it's not great.

**Comment by Baachi** [comment]
Thank you very much for this explanation @Seldaek . 
Big :+1: for your work!
