### ISSUE TITLE
Same autoloader used on 2 virtual hosts doesn't work

### ISSUE THREAD

**Issue by tiaanl** [composer/composer#4822]
I'm deploying the same site with the exact composer files to a single instance of apache.  In this case the ComposerAutoloaderInit<hash> classes between the 2 virtual hosts get confused and the two sites start loading each other's classes.  Something to do with spl_autoload_register maybe?

**Comment by alcohol** [comment]
Can you provide a bit more details? Such as what paths you are deploying too, how your virtual hosts are setup, and how you are deploying your code/package/release?

**Comment by tiaanl** [comment]
I have a site using composer and I run composer install on a build machine.  Then I package up all the files, including the vendor directory and the composer files into a zip file and extract this zip file to my production server.

On the production server I have a very normal apache setup using virtual hosts:

````
<VirtualHost *:80>
        ServerName site1.com
        DocumentRoot  /var/www/sites/site1/web

        RewriteEngine On

        RewriteCond %{HTTP_HOST} ^site1.com [NC]
        RewriteRule ^(.*)$ http://www.site1.com$1 [L,R=301,NC]

        <Directory />
                AllowOverride None
        </Directory>

        <Directory /var/www/sites/site1/web>
                Options FollowSymLinks
                AllowOverride All
                Require all granted
        </Directory>
</VirtualHost>
````

I do this for both sites.  What I have found is that if the autoload_real.php file's ClassLoader class has the same name, e.g. ComposerAutoloaderInit<hash>, then the site that get's a request first works correctly and the other site starts loading classes from the wrong directory.  Meaning that it is cached and then both sites use the same cached values.

I've temporarily fixed this issue on our servers by appending a custom string to the end of the hash for the class name and this seems to work perfectly.

**Comment by alcohol** [comment]
Do you use symbolic links? Do you share the same codebase with multiple vhosts?

**Comment by tiaanl** [comment]
We have 2 separate copies of the sites.  They live in different directories and there are no symlinks between them.  They are handle as completely different sites entirely.

**Comment by alcohol** [comment]
Without having any useful details, I find it very hard to provide further support.

E.g., you say the sites are "loading each other's classes". But you provide no evidence that supports this theory. Do you have any debugging/logs to verify this claim?

**Comment by jakoch** [comment]
It seems that the whole server runs a single instance of the PHP interpreter, right?
(You are probably running PHP as Apache module (mod_php) and not with inidividual FGCIs and php.ini's per site.) If this is true, then the firstly (!)  loaded and cached autoloader and its folder structure wins.
This seems to be one of the rare cases, where the hashing of the autoloader classname doesn't work out.

**Comment by tiaanl** [comment]
@jakoch You are 100% correct.  So the solution i'm using is appending something to the hash to make them unique between each site.  I don't know how the hash is generated, so I can't do something different there.  I do believe this is more a php/apache issue, but it affects composer in a really bad way.

@alcohol I will set up a separate environment and try to replicate the error and give you all the logs you need.  Unfortunately I can't give you any logs from our production servers.

**Comment by Seldaek** [comment]
@jakoch I am not sure I get what you mean. Even if there is only one cache, there are still two files and including one or the other should yield a different result, AFAIK cache is per file and not class name?! 

@tiaanl it sounds like the only way to work around would be to generate one archive per site, you can use `composer config autoloader-suffix SomeFixedSuffix && composer dump- autoload` to rebuild the autoloader with a suffix of your choosing. You could do that twice with different suffixes to generate two archives that are unique, but still sounds weird to me that you have to do that at all.

**Comment by jakoch** [comment]
If you have Composer on the production server (you shouldn't), you could run 
`composer dump-autoload -o` in each of your sites to regenerate the Composer Autoloader.
That's similar to modifiying the hash on the classname of the autoloader. 

The alternative is to package the application per site, by running `composer dump-autoload` before zipping. This gives you an individual autoloading hash in each zip ready for deployment.

Notes: 

1. This isn't a PHP/Apache issue, its a Composer issue. The hashing was introduced to avoid cache collisions, but it doesn't work out in this situation. Unfortunately, its not possible to make the autoloading classname more dynamic (per site/folder) without relying on language features not available on lower PHP versions. (I'm thinking of dropping the AL classname altogether replacing it with an autoloading closure or anon class. Then, the at runtime injected folder name results in  individually cached autoloaders).

2. Without being able to examine the autoloading execution flow i'm not sure, if my following assumption holds: registering multiple autoloaders (one per vhost) results in a bad performance, even if cached. The more vhosts are registered, the slower it gets, because of the register position of a site in the autoloading stack. And that leads to the following suggestion: switch to individual FCGIs per site (without shared cache) for performance (and also security, because shared cached is always tricky :).

**Comment by Seldaek** [comment]
@jakoch the hashing was introduced to support loading multiple autoloaders at once, like when phpunit is installed with composer globally but then loads your local project autoloader. I still don't see what it has to do with caching that is AFAIK not class based (unless apache mod php does weird things I'm unaware of). And your workaround won't work because composer re-uses the hash from the currently built autoloader if there is one present, so you need to do it as I described above by specifying a suffix yourself.

The only cache clash I could think of is if you use something like Symfony's APCClassLoader which stores the paths to class names in APC, and there you should definitely use a unique key for the cache of every site you deploy.

**Comment by alcohol** [comment]
`ApcClassLoader` was my only guess as well. But standard practice is to provide a unique prefix there, so I ruled that out.

E.g. https://github.com/alcohol/paste.robbast.nl/blob/master/web/index.php#L20

Hence why I said, without knowing anything useful about your application or your environment, it is very hard to provide more useful support. Because by all accounts, your scenario should just work properly. The only reason it would not AFAIK, is bad configuration, which is a user aspect :-)

**Comment by tiaanl** [comment]
Just for clarity, I'm not using anything other than the autoloader.  I've changed my index.php to look like this:

````
require dirname(__DIR__) . '/vendor/autoload.php';

$r = new \ReflectClass('SomeClass');
var_dump($r->getFileName());
die();
````

Then I run this on both vhosts and get the same path to the file in stead of a different path to each file like i would expect, because each vhost has their own documentroot.

**Comment by Seldaek** [comment]
Can you also `var_dump(__DIR__);` ?

**Comment by tiaanl** [comment]
````__DIR__```` is correct as expected, e.g.:

````site1 = /var/www/sites/site1/web````

and

````site2 = /var/www/sites/site2/web````

**Comment by Seldaek** [comment]
Well that is really odd then. I still can't make sense of why this would act like that.

how about `var_dump(realpath(dirname(__DIR__) . '/vendor/autoload.php'));` are those different? If yes then I'm out of ideas I think :)

**Comment by tiaanl** [comment]
It gives the same expected result.  I'm pretty sure it's not using the wrong files, but caches something somewhere, because if I restart apache and request one of the sites, then the other site uses the classes from the first and vice versa.

**Comment by Seldaek** [comment]
spl_autoload_register works *per request* though. So that doesn't make any sense to me. Do you have APC or opcache enabled? If so could you copy *all* of the relevant settings from phpinfo()?

**Comment by staabm** [comment]
@tiaanl do you use the symfony class loader component?

**Comment by curry684** [comment]
I have seen similar issues with opcache in the past. You should try reproducing the issue with the following line in your vhost or .htaccess:

    php_flag opcache.enable Off

If this resolves the issue I'd be interested to see what `phpinfo()` lists as actual settings for opcache, specifically for `opcache.revalidate_path` which could potentially cause this:

> If disabled, existing cached files using the same include_path will be reused. Thus, if a file with the same name is elsewhere in the include_path, it won't be found.

This setting defaults to **false** and could be related potentially.

**Comment by Seldaek** [comment]
That would make sense if relative includes were in use but AFAIK the
include is done with an absolute path which shouldn't hit this issue right?

**Comment by curry684** [comment]
Correct, but it's not without reason opCache took so long to make it into PHP core - it's notably buggy at times  :)

What I suspect is that for some reason both sites have their docroots in the PHP include_path. In that case it could most certainly consider `pathA/thingy.php` and `pathB/thingy.php` to be the same file.

**Comment by jakoch** [comment]
And the same will happen, when `opcache.use_cwd = 0` is used (a possible misconfiguration). Then OPcache considers only the basename. So the relative or absoulte path isn't taken into account. Two files with the same names (e.g. `/site1/v/autoload.php` and `/site2/v/autoload.php`) might get messed up.

**Comment by Seldaek** [comment]
Don't think we can do much here..

**Comment by dfumagalli** [comment]
I have the same identical issue. I host multiple websites on my VPS. Some of them have WordPress with some Composer "managed" plugins in there. When I restart the server, the first website somehow "takes" the Composer autoload and then every plugin tries to require ClassLoader.php from the directories of that website.

This typically ends up as a PHP forbidden base dir error on `autoload_real.php` at line 12.
I even tried manually entering hardcoded paths:

`require '/var/www/clients/client4/web7/web/wp-content/plugins/italy-cookie-choices/vendor/composer/ClassLoader.php';`

But even then, Composer is still loading the file from the first (other) website directory.
