### ISSUE TITLE
Use different stabilty flags for development or deploy dependencies

### ISSUE THREAD

**Issue by Markcial** [composer/composer#4823]
The composer stability flag forbids you from using the development packages if the version is not stable enough, being the stability flag global instead of separated for development or deployment environment, forbids you from using packages that are intended for development only.

Example, the newer 3.0 symfony version with all stable packages cannot be used with behat in development because the stable flag does not match the release candidate tagged version of behat.

One solution would be a flag that allows to ignore stability for packages that are not intended for deploy `require-dev`. This way we can use testing libraries currently in unstable versions but having deployable libraries tagged as stable versions.

**Comment by Seldaek** [comment]
As far as I understand, you would want to define the minimum-stability but only for require-dev packages? That's not possible, and I don't think we will make it possible because it would add a lot of complexity in our code and doesn't sound like that big a win really.

However, your project composer.json is responsible for the entire stability management of all your dependencies, so you *can* require behat (or a behat dependency) with `@dev` for example to allow that one to be installed dev without allowing everything to be installed dev.

Alternatively, you can combine `minimum-stability: dev` with `prefer-stable: true` that will prevent *everything* from updating to dev versions but only take dev when necessary.

I hope this helps.

**Comment by Markcial** [comment]
We will check if this might work, thanks for the helpful insight.

**Comment by Markcial** [comment]
All worked fine with this setup, closing issue because of this alternate way for solving stability conflicts. Thanks for the help! :smile:
