### ISSUE TITLE
Convert spaces to tabs

### ISSUE THREAD

**Issue by paladox** [composer/composer#4857]
Hi please convert spaces to tabs and also use a php code sniffer to make the code look nice please.

**Comment by cs278** [comment]
"Nice" is subjective, the code follows [PSR-2](http://www.php-fig.org/psr/psr-2/).

**Comment by burzum** [comment]
You won't make them change the silly spaces to tabs. Sadly most of the projects these days follow the silly spaces AKA PSR-2 "standard" *recommendation*.

We're not following PSR-2 either in two aspects: We use tabs - that's what tabs are thought for - and do the curly bracket on the same line as the method declaration.

PSR-2 was mostly a political decision as I see it because most voting projects did it wrong for decades and had no interest in switching to tabs.

Here is the "fixed" version of it. https://github.com/php-fig-rectified/fig-rectified-standards

This project contains a fixer that does tabs over spaces as well, feel free to use it. :)
