### ISSUE TITLE
VCS branch caching is inadequate

### ISSUE THREAD

**Issue by chx** [composer/composer#4870]
Once I added https://github.com/amitaibu/og as a VCS , composer on every update , not involving og goes and dowloads every. single. branch. from the repo making the operation inbearable slow.

**Comment by cs278** [comment]
If you bypass the GitHub API then fetching repository information should be nice and quick because Composer does a `git clone --mirror` into the cache directory and then only does a `git fetch` going forward. If you have many VCS repositories though you'd be better off running a local [Satis](https://github.com/composer/satis) or [Toran Proxy](https://toranproxy.com).

```sh
composer config repositories.packagist false

# Using GitHub API
composer config repositories.foo vcs https://github.com/composer/composer
rm -rf cache

time COMPOSER_CACHE_DIR=cache composer show composer/composer
0m17.827s

time COMPOSER_CACHE_DIR=cache composer show composer/composer
0m3.190s

# Bypassing GitHub API
composer config repositories.foo '{"type": "vcs", "url": "https://github.com/composer/composer", "no-api": false}'
rm -rf cache

time COMPOSER_CACHE_DIR=cache composer show composer/composer
0m30.079s

time COMPOSER_CACHE_DIR=cache composer show composer/composer
0m1.041s
```

**Comment by ryanaslett** [comment]
git clone --mirror is unfortunate, as it creates a comprehensive copy of everything stored in git.  Normally this wouldn't be problematic, however, its a potential DOS vector due to the way that github has implemented pull requests.  When you mirror, you get every single ref in the git tree ever. Github stores pull requests *in your repo* on their server as refs/pull/###/head and refs/pull/###/merge.

So, if somebody wanted to be kinda rude and drag somebody down, all they would have to do is submit a pull request with a massively large file added, and then every --mirror is going to have to download that file.

**Comment by alcohol** [comment]
Please, use the issue tracker to report actual issues. If you want to vent your frustrations without actually contributing anything, I can recommend Twitter.

**Comment by stof** [comment]
@ryanaslett except that github does not send you these refs when cloning a repo. Getting them requires additional configuration to request github to give you such refs, and composer does not add this config

**Comment by hkdobrev** [comment]
What about the depth and breadth of the git cloning? Does Composer limit the Git history cloned with `--depth`? Could it download only the specified branch instead of all branches?

**Comment by cs278** [comment]
> @ryanaslett except that github does not send you these refs when cloning a repo. Getting them requires additional configuration to request github to give you such refs, and composer does not add this config

@stof `git clone --mirror` pulls all branches with a refspec of `+refs/*:refs/*` it's kind of a non issue anyway as GitHub would probably act upon somebody flooding a repository with thousands of PRs. And it's only applicable to Composer if you use a GitHub repository without the API integration.
