### ISSUE TITLE
Composer windows installer cannot complete in Windows 10

### ISSUE THREAD

**Issue by spotstat** [composer/composer#4914]
After downloading the Composer Windows installer, I attempt to use it to install Composer. After starting the installation, I get an error message to the effect that Windows Explorer is open and is preventing the installer from using one or more required directories or files. I tried it with all open windows closed; I also tried it with 'enable shell' disabled. Neither made any difference.
Any suggestions on how I could troubleshoot this?
Does it point to a problem with the installer itself being incompatible with Win 10?
I did eventually get Composer installed via the command line, but the installer should work, and it doesn't for some reason.

**Comment by curry684** [comment]
The installer works fine on Windows 10, tried multiple times yesterday in debugging another issue.

Can you run the installer from the command line and specify the `/log` parameter:

    Composer-Setup.exe /LOG="C:\composer.log"

And then provide the output of that log here in a [gist](https://gist.github.com/).

**Comment by spotstat** [comment]
It says Composer-Setup.exe is not recognized as an internal or external command.

**Comment by curry684** [comment]
Please execute the command from the folder you downloaded it to.

**Comment by spotstat** [comment]
Sorry to not have thought of that myself. Here is the essence of the log:
2016-02-12 14:42:00.362   DEBUG:: Running PrepareToInstall tasks
2016-02-12 14:42:00.362   DEBUG:: Writing Unix line-endings to C:\Users\DAVIDF~1\AppData\Local\Temp\is-GEH0T.tmp\composer
2016-02-12 14:42:00.435   DEBUG:: Processes (1) are locking required files
2016-02-12 14:42:02.277   Message box (OK):
                          Setup cannot continue because another application is using files that must be updated.

**Comment by curry684** [comment]
Is there no clarification at all around `Processes (1) are locking required files` as to which files or processes it's referencing?

Doesn't matter too much, as this is not the installer's problem. That process is most likely indeed `explorer.exe`, and it holds a non-concurrent file handle on a file or folder that the installer is intent on modifying. It may do so either because it has an explorer window open in (a subfolder of) that folder, or it is generating thumbnail previews for it, or because it's cleaning up temp files. None of those are likely to be detectable by you or the installer.

The good old Windows adagium is therefore probably relevant: have you tried turning it off and on again?

**Comment by curry684** [comment]
It could actually also be possibly throwing this error is a reboot is pending from another update or install. Windows protects installer services from accidentally interfering with eachother, so if something happened (could be from Windows Update) that has requested a reboot to finish its job most other installers won't run until you complied.

**Comment by spotstat** [comment]
I ran the installer after a fresh re-start. My setup is a W10 update from W8.1 from W8.0 from 7, and I have at one time or another had a lot of complex stuff going on. Explorer is clearly doing something back there in the netherworld. Thanks for your input. I really appreciate it. I'll go ahead and close the issue now.
