### ISSUE TITLE
Could not parse version contraint

### ISSUE THREAD

**Issue by ILHAMIDEAZ** [composer/composer#4916]
Hi. I have error sound: 

> Could not parse version contraint installer : Invalid version string "installer"

How can I fix this? I'm already composer selfupdate but the problem still remain.

My Composer file at AppData > Roaming > Composer also not has config.json too.
Why?

Thanks.

**Comment by ILHAMIDEAZ** [comment]
![12699242_118734931847613_810071668_o](https://cloud.githubusercontent.com/assets/5715163/13031279/024fbcb6-d303-11e5-930d-3dadb6b6faaa.jpg)

**Comment by curry684** [comment]
The package is called [`laravel/installer`](https://packagist.org/packages/laravel/installer), not `laravel installer` with a space. All composer packages follow the `<vendor>/<package>` naming convention.

So just type:

    composer global require laravel/installer

As a sidenote - in a Windows command prompt window you can click on the top left icon, select 'Edit' then 'Mark' and then drag a selection in the window. Hit the enter key next to copy the selection to the clipboard to copy/paste it here instead of using photos.
