### ISSUE TITLE
Allow dependencies to be installed only if needed

### ISSUE THREAD

**Issue by fruitl00p** [composer/composer#4996]
I'd like for my package to specify dependencies only based on criteria. I.e. I'd like to allow the users of my package to not have to install more than necassary. The situation is as follows:
I'm the maintainer of a package that uses the array_column function. But tor retain as much compatibility as possible i also have to include the dependency for the polyfill ([ramsey/array_column](https://packagist.org/packages/ramsey/array_column)) in order to allow users of old php versions to still install my package. (now this is just an example other polyfill type libraries do exsist) But including this polyfill in newer PHP environments would be silly and only clutter the `vendor/`-stack.

Is there any way to get composer to ready my package composer.json file and thus only require the dependencies as needed according to the users environment?

I know this might seem weird, but with the increasing pace of PHP module development i'd like to specifiy my dependencies based on the environment i'm used in. 
It would probably change the `require` flag from a string into an object with more options to specify stuff... 

An example might be:
```json
{
	"name": "my-package",
	"description": "This is my package that only requires ramsey/array_column when installed in older PHP versions",
	"require": {
		"php": "5 - 7",
		"ramsey/array_column": {[
				"php":"5",
				"version": "~1.2",
		]}
}
```
But one might go as far and specify versions per engine / environment:
```json
{
	"name": "my-package",
	"description": "This is my package that only requires ramsey/array_column when installed in older PHP versions",
	"require": {
		"php": "5 - 7",
		"somepackage/thatrequiresmbstring-sometimes": {[
				"php": "5",
				"ext-mbstring": "*",
				"version": "0.8",
		], [
				"php": "7",
				"version": "1",
		]}
}
```
In this last case the requirement for `somepackage/thatrequiresmbstring-sometime` would depend on both the PHP engine version _and_ if the PHP 5 than also the MBstring extension... 

Any thoughts?

**Comment by stof** [comment]
the issue with this is that the composer.lock would then depend on which set of requirements was chosen during the dependency resolution, making it a nightmare to lock dependencies.

**Comment by fruitl00p** [comment]
That's true indeed. But also seems 'logical' when defining such dependent dependencies .. ? Locking would have to be skipped and one might argue that the version would have to be very explicit... ?

**Comment by curry684** [comment]
The conceptual problem underneath the practical problems is that Composer does not intend to do what you want - lock into a specific environment. Quite the contrary you [are explicitly encouraged to commit `composer.lock` to VCS](https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file) as it represents a tried, tested and trusted state of the project and its dependencies. Were we to implement your request it would be a tried, tested and trusted state... assuming a specific PHP version with a specific set of extensions and possibly other stuff like plugins. Making committing the lock practically useless as a production server is never going to expose the exact same environment as your development machine. Meaning the whole point of lockfiles is gone, and you'll never have a consistent state to deploy to production.

The weirdest part about this request is actually that the dependent should define this instead of the depender. What would make far more sense is for a package like `ramsey/array_column` to indicate in its own `composer.json` that it's useless in PHP >=5.5, and we could then still mark it as installed but skip it in the autoloader generation, skipping a few CPU and IO cycles on more up to date machines. That feature would benefit [quite a few polyfills](https://packagist.org/search/?q=%22symfony%2Fpolyfill%22) without breaking the locking system.

Theoretically we already have the syntax partially in place, as for example `symfony/polyfill-mbstring` could `"provide": { "ext-mbstring": "*" }"`. Implementing that would be quite a lot of effort though just to save a single opcache hit and a single `if` per polyfill, not really worth it.

**Comment by fruitl00p** [comment]
@curry684 thats also true... I guess you both are right and this is just something thats unresolvable which leads to installing dependencies in environments that don't actually need them. Oh well... :)
