### ISSUE TITLE
Thoughts on secure-http

### ISSUE THREAD

**Issue by mmelvin0** [composer/composer#5008]
Many of my organization's Composer dependencies are hosted on a GitLab instance behind our corporate firewall. It's plain HTTP and not externally accessible.

Since the update that changed `secure-http` to true by default, obviously that can't be accessed without changing that setting back to false. The problem is that many developers will set it to false globally and forget about it.

I think it could be more secure if one could white-list URLs (e.g. per-project) that can be accessed insecurely.

Thoughts/concerns/criticism?

**Comment by curry684** [comment]
Have to say I agree. It's been ticking me off over the past few years that I've been 'forced' to secure internal applications that never leave the corporate network, like our vCenter console.

The way I see it there are 2 practical solutions:
 - We check the hostname of URLs, and if they resolve to known private IP ranges we ignore `secure-http`, or:
 - We add an 'http' flag to repositories to voluntarily override the requirement on a per-repository basis

**Comment by Seldaek** [comment]
I don't really like this because it's easy to mess up even if you think you're safe in condition X, and because thanks to letsencrypt it's really easy to get free certs now.

We could for sure turn the secure-http bool into a hashmap of domain names or IPs that can be configured, similar to what we have for preferred-install.. But that's again complexity and all for something that ultimately I feel would be better fixed at the source.

**Comment by curry684** [comment]
The problem is dat even Letsencrypt performs ownership validation as it's required for the SSL system as a whole to function. And thus do not issue certificates for `satis.company.intranet` and the like. So for smaller companies that means they have to maintain their own root CA, and distribute/install those with their employees, just to encrypt traffic that they're already privvy to and are the only ones with physical access to.

The current implementation means that the webdevelopment freelancer can't even run a local Satis as http://localhost/satis is also unacceptable. Good luck getting a certificate for `localhost`  ;)

**Comment by mmelvin0** [comment]
What if we were to keep secure-http as-is (boolean, default true) and add an insecure-http-whitelist that defaults to empty, can be set globally or per-project, and is only consulted if secure-http is true?

The issue really is that in order to use ANY "insecure" resources (e.g. intranet or localhost as mentioned by curry684) you have to allow access to ALL insecure resources.

**Comment by Seldaek** [comment]
Yes I can see the problem.. I guess I just wish it didn't exist ;)

**Comment by mmelvin0** [comment]
I agree, it would be great if HTTP just didn't exist without HTTPS. Alas...

I can work up a proof-of-concept pull request for this if you're interested. I've been itching for an excuse to dig a little deeper into Composer.

**Comment by Seldaek** [comment]
Sure thing :)

**Comment by bweston92** [comment]
I would of hoped for a warning first then maybe in a few months make it solid, caused lots of issues in my deployment pipeline. Unfortunately the composer.json option to make it insecure again did not work so had to use LetsEncrypt to get a deployment out.

**Comment by curry684** [comment]
@bweston92 the `"secure-http": false` config setting works for sure. Did you put it in the right place in the config?

**Comment by StormTide** [comment]
I'd -1 on this idea. This is how we end up with things like 'SSL added and removed here'. 

TLS on the intranet is now industry standard, and with the presence of APT attackers who find a beach-head by infecting some support laptop, using HTTP to install code, even internally, is just bad practice. 

Setup a CA if you need internal use, or use an external endpoint, letencrypt and authentication. A lil extra work, but well worth the time, and really, we need to stop taking short-cuts when it comes to security. Internally or externally.

**Comment by curry684** [comment]
> TLS on the intranet is now industry standard

I couldn't disagree more. In a perfect world I'm fully with you, but it's not. In the real world nearly no companies with less than 20 employees, which would cover most web development companies, have an internal CA, or the group policies required to distribute certificates. In the real world I would be surprised if 5% of all Composer users understood how SSL works, what a CA is, and why and how they are supposed to set one up.

The single biggest problem is that the "shove it down their throats" attitude is counter-productive. People will [just disable SSL effectively](https://github.com/composer/composer/issues/4967#issuecomment-193167131), or blindly click through the browser warnings, causing the paradox of a less secure internet because of more security.

To quote a [very well known public rant from a Google employee](https://plus.google.com/+RipRowan/posts/eVeouesvaVX):

> Like anything else big and important in life, Accessibility has an evil twin who, jilted by the unbalanced affection displayed by their parents in their youth, has grown into an equally powerful Arch-Nemesis (yes, there's more than one nemesis to accessibility) named Security. And boy howdy are the two ever at odds.

> But I'll argue that Accessibility is actually more important than Security because dialing Accessibility to zero means you have no product at all, whereas dialing Security to zero can still get you a reasonably successful product such as the Playstation Network.

Applying this to Composer: by requiring SSL for every single connection we are right now making thousands of people disable peer verification or the `secure-http` flag as a whole, nullifying the entire effort for them beyond repair. Whilst if we only enforced it for connections beyond the firewall they would understand, have a usable workaround with LetsEncrypt.

I have looked into this issue and it's actually not that complex to patch `secure-http` into applying only to the public internet, or ignoring a whitelist. Dunno if @mmelvin0 is working on it, otherwise I can draft a PR.

**Comment by StormTide** [comment]
No one should be disabling peer verification or enabling insecure http code install. We're not making this up because its some theoretic threat that /doesnt apply to you/... 

This comes up because verifypeer = false leads to this: http://www.unrest.ca/peerjacking and millions of stolen credit cards, user data at risk and identity theft. TLS packaging is a baseline requirement now -- most packaging systems actually do signed code, but Composer's not there yet. apt-secure and just about every other app-store on the market are using signed code, so why is PHP stuck in the dark ages and pushing back against even the basic requirement to use https?

PHP's security reputation is already crap for these reasons, and further catering to this ecosystem of people who just dont care about security is just plain irresponsible in my opinion. It took years to get the TLS bug fixed, and now you're asking for larger exceptions for folks who just dont want to secure their apps -- well im sorry, I see no reason to support that use case.

**Comment by curry684** [comment]
> No one should be disabling peer verification or enabling insecure http code install

Behind the firewall, or worst of all on `http://localhost`, that's not our responsibility. Please understand that I agree with you completely and fundamentally about the threats on every network, and how they should be mitigated. I'm only arguing realism that we've already seen multiple issues on the subject, resulting in *"I've just disabled `secure-http` to be done with it"*. This very issue we're discussing in boils down to that. We know only a handful of people running into this open issues, the others just click the documentation link in the error to find out how to disable the check. Globally. Making security worse than we started with.

My only argument is that we should not herd people into disabling SSL on the public internet just because they're running a Satis install on their Synology NAS at home in the hallway. I agree with you on every other point.

Your input on #5088 is highly appreciated.

**Comment by StormTide** [comment]
I'd point out I argued against the secure-http option in its entirety. It should be harder to disable TLS than to set it up correctly -- but we keep making the off switch just way too easy -- and to disastrous result. 

As for it not being our responsibility -- it totally is, because, as you point out, folks will use these options to get to 'it works' and then deploy the insecure configuration to production. They probably operate a website you shop on, and you're none-the-wiser.

You add this per-domain override and folks will be like 'oh well, its just that one package' and not realize that this is a weakest link scenario and that having even one package loadable over http means they're vulnerable to RCE /of any code of the attackers choosing/.

There is no safe way to install code from http, even internally.

**Comment by mmelvin0** [comment]
@curry684 Just wanted to let you know I haven't done any work on this yet. I've been busy but I've been paying attention to both this and your PR. Will definitely be in touch once I have a chance to look at this more in-depth.

I have concerns about DNS lookups and redirects making a simple "insecure" white list even more insecure, but I think those things have already been discussed in depth on the PR.

**Comment by prometheas** [comment]
Just wanted to throw in with a note that I work at a very big company, and convincing someone to configure our private packagist instance to run on https—while we'll all agree handily is a no-brainer worth doing—is at the very bottom of their priorities list, as their in the throes of a massive migration of assets from a self-run data center into AWS … there's nearly ZERO chance they'll get to this request before year's end.

In the interim, I'm left having to disable the secure-https flag globally, which—as pointed about above—is super easy to set and forget forever.

**Comment by Seldaek** [comment]
I wonder if a valid alternative could be that when secure-http is disabled, we print a warning for every file that's downloaded insecurely? That way it raises awareness about which URLs are actually used insecurely. If it's just a couple it shouldn't spam too much, and it might allow you to identify and fix them otherwise.

**Comment by prometheas** [comment]
I that's on the right track… I'd love to find a way to solve for it that "names 'n shames" the repositories, if possible, rather than merely the packages. The difference might seem subtle, but the conversation is one to be had with the repo maintainers, rather than the package maintainers, and any measures that can be taken to facilitate that conversation without shafting end-users is—I think—super valuable.

**Comment by curry684** [comment]
I think keeping `secure-http` after the switch was a bad idea to begin with. As I've argued before it creates a less secure situation in practice because the people that need it, and many do during the transitional period where many repositories are not SSL-enabled, are forced to turn off the entire mechanism in a way that's never deleted later on because people are used to it. It's not helping the problem that way, and even involuntarily maintaining the status quo.

The only sane path forward imho:

1. Deprecate `"secure-http": false` with a big warning of its own, but treat it as a `*` whitelist until 1.0.0.
2. Introduce a whitelist for URLs allowed to be accessed without SSL
3. Give a big fat warning on every file downloaded from a whitelisted URL referencing the repo

This way it indeed names and shames the repositories.

**Comment by StormTide** [comment]
@curry684 if you have even one site in a whitelist, the whole scheme is useless. HTTP is /unauthenticated/, right down to the DNS, headers, everything. Just one http exception and you might as well not use https at all, anywhere on the entire app. Thats the threat surface were talking about here, its a weakest-link-in-the-chain pattern.

If anyone is turning off security to 'make it work', thats on them -- they'll fail their security compliance, open up a world of liability if they data-spill personal information as a result, and just generally get themselves fired when someone inevitably roots the build chain.

So 

1. Absolutely not.
2. Introduces a new MITM RCE.
3. Someone will just start asking for a warning override, because /their use case is legit/ of course.

**Comment by StormTide** [comment]
Also, for the record, the transition period was the 3 years the MITM RCE was open, we're past the EOL date for HTTP here.

**Comment by Seldaek** [comment]
https://github.com/composer/composer/commit/2062070be953edf5d980311f32f5928fd40ddb3a adds a warning (once per hostname accessed insecurely) so if you have secure-http disabled you'll spot any unsafe access. That should give a good balance of letting people disable it globally but they can make sure the only domain that's unsafe is their internal network domain that's apparently safe.

**Comment by StormTide** [comment]
Again, a single domain, even if its your internal domain, enables the mitm. The attacker of a HTTP stream has full control over the domains, the dns, and the site your server connects to. Even if you think /your server/ is safe, you are not connecting to /your server/ you are connecting to Mallory's MITM. Theres many scenarios where even a domain that normally resolves to a lan ip address, can be dns hijacked, redirected to another server, and the code installed from there. Anyone contemplating disabling secure-http on the assumption that /its just your local domain/ needs to understand that its the same as turning it off for /every domain/.

**Comment by Seldaek** [comment]
@StormTide point taken, I guess what they mean is private domain using a private DNS inside a private network, in which case I suppose the dns poisoning stuff is less of an issue. But anyway they'll still see warnings, and it's still up to them to shoot themselves in the foot. I can't *force* people to use SSL everywhere, it's just not realistic when building software that has to be executable by everyone.

**Comment by StormTide** [comment]
Even in that most implausible of unlikely scenarios, you'd still be talking about an exploit that allows going from network access (any client on the private network) to root code installation on a webserver. In terms of an APT vector, this would still be downright negligent from a defence in depth perspective. 

We cant force people to use TLS, but we sure don't have to go out of the way to support them not using it. Stop making verifypeer=off easier than configuring a ca bundle!
