### ISSUE TITLE
[regression] composer show ignores --quiet

### ISSUE THREAD

**Issue by dzuelke** [composer/composer#5031]
```ShellSession
~ $ composer --version
Composer version 1.0.0-beta1 2016-03-03 15:15:10
~ $ composer show --quiet --installed foobar
                              
  [InvalidArgumentException]  
  Package foobar not found    
                              
show [--all] [-i|--installed] [-p|--platform] [-a|--available] [-s|--self] [-N|--name-only] [-P|--path] [-t|--tree] [--] [<package>] [<version>]
~ $ echo $?
1
```

It's a regression; worked in alpha11:

```ShellSession
~ $ composer --version
Composer version 1.0.0-alpha11 2015-11-14 16:21:07
~ $ composer show --quiet --installed foobar
~ $ echo $?
1
```

**Comment by curry684** [comment]
Reviewing the commit history I think this happened in 8ed894cf999756089f9ffa969b3756f26bf4af1d. Seems like an accidental side effect that exceptions are now rendering output again.

**Comment by Seldaek** [comment]
The quiet output change is by design, we now output exceptions and some critical messages (subject to change in the future). The only way to make sure you don't get any output is to run with `--quiet 2>/dev/null`, as all quiet output should be done on STDERR. Add `>/dev/null` too if you want extra safety but I think any STDOUT output in quiet mode can be considered a bug that we need to fix.

And BTW @curry684 that is incorrect, this commit is unrelated and only for people shipping composer with their own dependencies like Fedora. It does not affect composer.phar at all.
