### ISSUE TITLE
Multiple sources for repositories

### ISSUE THREAD

**Issue by svencan** [composer/composer#5040]
Hello,

(taken from another issue, but should be discussed separately):

Composer should have the possibility to have multiple sources for a repo such as:

```
"repositories": [
  {
    "type": "path",
    "url": "../libA.git"
  },
  {
    "type": "vcs",
    "url": "git@somevcs:...libA.git"
  },
}
```

If one repo is not available, it should fallback to a succeeding one.

**Comment by curry684** [comment]
`../libA.git` is not a valid path repo, but for a correctly configured path repository this should actually work - it just loads the packages it can find, and if it can't find packages it doesn't. Therefore the first repository being able to supply a package actually wins.

**Comment by alcohol** [comment]
Having multiple repositories for the same packages has been possible for quite a while already. The repositories are instantiated in order, and added to the pool, before any dependency resolving begins.

I suspect the problem is rather that Composer throws an error if one of the repository definitions doesn't work/is considered invalid (missing, cannot connect, etc)?

**Comment by curry684** [comment]
I suspect that is the case but we cannot do that. Imagine I have in my config:

1. A local path repo on an NFS fileserver providing `foo/bar` because I'm working on it.
2. A Satis repo on an EC2 server providing our company's custom stable fork of `foo/bar`
3. Default Packagist repo providing the standard edition of `foo/bar`

Now depending on network conditions I might get *any one of these 3 at random* every time I update, if we were to implement soft failing repositories. Not something we'd want.

**Comment by svencan** [comment]
I actually did not provide a valid path repository, like curry684 pointed out. Now it works as desired.
Related documentation: https://getcomposer.org/doc/05-repositories.md#path

Thanks.

**Comment by artisaninweb** [comment]
I was looking for the same thing for hours.
Was getting a error the directory of the path did not exist.
Figured out it had to do with the `"symlink": true` statement i had used.
