### ISSUE TITLE
RFC: Windows .exe setup improvements

### ISSUE THREAD

**Issue by Seldaek** [composer/composer#5061]
Please see https://github.com/composer/windows-setup/issues/51 if you are on windows and want to give feedback it'd be appreciated.

**Comment by johnstevenson** [comment]
I have released this now: [v4.1.0](https://github.com/composer/windows-setup/releases/tag/v4.1.0)

Hopefully it will fix, or at least help with, some of the `[ERR_XXX]` issues that have been reported here because it now recognizes common PHP config errors and displays all output, without trying to categorize stuff.

It also finds PHP on your computer (or at least looks in common locations), so this should make it more user-friendly for Xampp and Wamp users.

**Comment by Seldaek** [comment]
@johnstevenson sorry for not trying it out before, but I just noticed that it didn't find my PHP even though it's in the PATH and `where php` locates it just fine on in cmd.exe. I am not sure if you check common locations only (I have mine in a non-standard place ..), but I thought I'd let you know.

I deployed 4.1.0 to getcomposer.org btw.

**Comment by johnstevenson** [comment]
Hi,

If it is in your PATH then it should find it (as previously) and display it in
the select box. So what did it display? And where is yours located?

Currently it searches system drive and user profile directories first:

* \php*
* \php\php*
* \bin\php*
* \bin\php\php*

then it looks for specific (xampp, wamp, PhpEd) locations.

Ta for deploying.

John

**Comment by johnstevenson** [comment]
@Seldaek  If it is in your PATH then it should find it (as previously) and display it in the select box. So what did it display? And where is yours located?

Currently it searches system drive and user profile directories first: `\php*`, `\php\php*`, `\bin\php*`, `\bin\php\php*`, then it looks for specific (xampp, wamp, PhpEd) locations.

**Comment by Seldaek** [comment]
It's in `C:\Users\seld\Apps\Server\PHP\php\php.exe`, and the select box was empty :)

**Comment by johnstevenson** [comment]
Oh no! Were you doing an admin install (may be I've got some logic wrong if it only finds PHP in the user PATH)?

**Comment by Seldaek** [comment]
I didn't try an admin install, but it did an UAC prompt on startup.

**Comment by johnstevenson** [comment]
That's an admin install - ie. it elevates you to admin. Ta, I'll dupe your setup and investigate.

**Comment by Seldaek** [comment]
Yeah I see it is but I mean I didn't ask it to :)

**Comment by johnstevenson** [comment]
I'm afraid Inno Setup doesn't offer *Install for All Users* or *Just for me* type options at runtime like MSI installers do, so if you're an admin it prompts for elevation (unless you are running it elevated), and if you're a user it doesn't (and installs stuff in your user profile).

And it didn't show your user PATH php, because it has never looked for it if you are an admin, which I think it should. So here you go (stuff will still get installed to admin specific locations):

New release: [v4.2.0](https://github.com/johnstevenson/composer-setup/releases/latest)

**Comment by Seldaek** [comment]
Confirmed working now, thanks!
