### ISSUE TITLE
When using private repository, Composer silently prefers the Packagist one if the private is not installable

### ISSUE THREAD

**Issue by ondrejmirtes** [composer/composer#5076]
Let's say there's a package `foo/foo`. It's public, but there's a private version too.

I add a dependency to the dependent (root) project as `"foo/foo": "dev-master"`.

I add the private repository to composer.json's `repositories` key and that version's master branch has different requirements for dependencies than the public one.

If the root project has other requirements that are satisfied only by the public version on Packagist, Composer silently installs the public version even if there's a repositories section with the private version repository.

I think that adding the repository to `repositories` section clearly states my intent to use that package version instead of the publicly available one and that Composer should throw an error in this case.

**Comment by alcohol** [comment]
Composer does not throw an error, it simply falls back to the next available repository and checks if that contains an installable version of the requested package. I understand that this does not conform to your expectations, but this is the way it works, and that is not going to change.

**Comment by ondrejmirtes** [comment]
Is there a verbose mode that would express this behaviour on the outside? Or is it a complete non-debuggable blackbox?

**Comment by staabm** [comment]
did you try the very verbose flags aka `-vvv` ?

**Comment by curry684** [comment]
The dependency solver is internally pretty much a black box without logging, regrettably. A prime point for improvement hehe.

**Comment by Seldaek** [comment]
Actually I think this is an important question we should consider (if only for 2.0). One way to solve it would be that in Pool::whatProvides we look repo by repo in priority order and as soon as one repo yields a package fitting the requirement, we abort.

That way if the highest repo's package is not installable you'll get a conflict which might be a bit confusing if you look down to other repos or packagist, but I'd argue it's a better outcome than installing something which is (IMO) obviously not what you wanted.

Any thoughts @naderman?

**Comment by naderman** [comment]
@Seldaek Well we should do the other refactoring for 2.0, so that packages in the pool are all safe to install, so the process to fill the pool should do what you describe.

Generally, if you really don't want the public package, make a new one with a different name. Overwriting names was kind of meant for workarounds only. If we change this you can no longer specifically require an older version which only exists on the lower priority repository. For example if you add your company internal repo to require some other dependency, and the internal repo also overwrites only a newer version of the package which you want from the public repo, you can no longer get it. Not sure if that's a useful feature though?

**Comment by Seldaek** [comment]
Fixed by https://github.com/composer/composer/pull/8528
