### ISSUE TITLE
secure-http and HTTPS Redirect

### ISSUE THREAD

**Issue by tschechniker** [composer/composer#5152]
Hi,

we have about 150 Composer Projects. Every single Project has the definiton of our private Repo in the composer.json:

"repositories": [
     {
       "type": "composer",
       "url": "http://composer/repository"
     }

Unfortunatelly we can't update the dependencies any more because of the non existing https. So i added https support for our private repo and added a redirect from http to https. But Composer ignores the redirect and we still get the "Your configuration does not allow connection to http ..." message. So we would need to change the composer.json in every Project and in every branch. This would be about 300+ commits just because you changed the default value. Sorry but this is a big mess ...

Is there a easy way to make composer work again without changing the repo config in every project?

**Comment by Seldaek** [comment]
Not really no, sounds like it's something that is scriptable though. As a transitional way you could use `composer config -g secure-http false` to allow http across the board, but down the line you'll have to fix it one day or another, so might as well just do it IMO.

The reason is if you do a request to http://, an attacker performing a man-in-the-middle attack would be able to return what they want instead of the redirect. Your server doing a redirect offers no security at all.
