### ISSUE TITLE
Composer install/update are slow

### ISSUE THREAD

**Issue by nikhil-dhiman** [composer/composer#5176]
When I run Composer install, why it checks for meta data of all branches/tag in that repo, even if branch name and repo name is already mentioned in "require" and "repositories" key of composer.json

Is there a way  we can tell composer to not look for branches other than mentioned in "require"

Why I need that religiously
1. We have around 1000 of branches/tag
2. Around 12 repos.

Because of that composer takes the time to install/update.

**Comment by Seldaek** [comment]
It does that because it needs to know about all versions, we could possibly optimize but then it wouldn't be guaranteed correct anymore.

That's why https://toranproxy.com/ exists so it can scan this stuff in the background and then composer installs quickly using that pre-cached data from toran proxy.

If you really have 1000 branches/tags and most of them are missing a composer.json it would be good to clean them up if you can though, because branches without composer.json can not be cached so scanning will take long every time.
