### ISSUE TITLE
Make master the default branch of Composer repository

### ISSUE THREAD

**Issue by hkdobrev** [composer/composer#5182]
From: https://github.com/composer/composer/issues/5180#issuecomment-208478026

> Nope, breaking stuff is not to go anywhere right now :) master is targetting 1.1 and 1.0 targets 1.0.x.
> 
> I think before breaking things we should clean up the issue tracker and merge existing new features PR that are not breaking.

@Seldaek this all sounds great and https://github.com/composer/composer/commit/efa13d7c5ff4fb1bdf799901f34f23ad1eb066c4 is good, but I've noticed you've made `1.0` to be the default branch of the repository. This might create a few problems. The way I understand you, only bug fixes should go into `1.0` branch and any new development should be based on `master` and PRs for new features should target `master`. However GitHub PRs base branch would default to the repository default branch. So if people are not careful you'd have a lot of PRs targeting the wrong branch.

Of course it's up to you to decide which kind of PRs you get more - bug fixes or new things and where you want to merge them, but I'd normally expect the `master` branch to stay the default branch and only some things to go to the `1.0` branch.

**Comment by Seldaek** [comment]
In my experience, people don't follow guidelines and just send to the default branch, that's why I switched it, because most small changes/fixes that I quickly want to merge from github are gonna fall in the 1.0 case.

Features and all that should go to master I generally merge them locally to try it out, so I can do that on any branch, as master will be kept up to date with 1.0 changes.

**Comment by hkdobrev** [comment]
Fair enough :-)

Thanks for the clearing things up. We can refer to this issue if questions arise.
