### ISSUE TITLE
Composer does not fire an event before purging packages

### ISSUE THREAD

**Issue by LionsAd** [composer/composer#5232]
### Motivation

The wikimedia/composer-merge-plugin was suggested to be the alternative instead of 'include' / 'require' support within composer itself.

However the plugin has to work within the constraints of composers event system.

Obviously it being a plugin it could not be called before all sections have been parsed.

However while many things like dependency resolution and merging of extra dependencies work great, it is impossible to use the composer-merge-plugin with a custom installer.

The reason being that the installer is being called via purgePackages => getInstalledPath(), which is called before _any_ other event is called.

That means no plugin has any chance to enhance the root composer.json before this is called.

This can be work arounded by calling the composer-merge-plugin directly, which is really ugly, but works. (https://github.com/douggreen/drupal-composer-installer/pull/9)

However it means any installer and plugin that wants to rely on a merged composer.json needs to check for the existence of the plugin and call it.

### Proposed resolution

- Add an event immediately after the root JSON file has been parsed and all composer plugins have been loaded, e.g. COMPOSER_INIT. This would allow the merge plugin to react to this event and enhance the root config with the merged values in a deterministic way.

OR

- Add at least an event before purge packages, which would not help all other cases, but would at least ensure that Installers would work better with the merge plugin, e.g. PRE_PURGE_PACKAGES.

### Discussion

What do you think? I am happy to create a patch once we decided on an approach.

**Comment by Seldaek** [comment]
Fixed by https://github.com/composer/composer/commit/aeafe2fe59992efd1bc3f890b760f1a9c4874e1c which adds an INIT event. I think that'll do the job. I made sure that the purge happens *after* ;) And BTW you should make sure composer-merge-plugin requires the plugin `composer-plugin-api` `^1.1` so that composer doesn't upgrade the plugin to this new version in case it uses the `PluginEvents::INIT` constant because that'd make it go boom. Alternatively if you wanna keep BC with older composer just use `"init"` to register the event handler.

**Comment by LionsAd** [comment]
Thank you very much for the quick fix!
