### ISSUE TITLE
Is there a way to disable generating autoload_static file in composer.json or lock

### ISSUE THREAD

**Issue by paladox** [composer/composer#5354]
Hi is there a way to disable generating autoload_static file in composer with a config please.

It broke php 5.6 with https://github.com/wikimedia/mediawiki-vendor/commit/4bd8ba35627e7d70036de02eeec5e52ba64b9250 because it didn't generate the autoload_static file. But we carn't generate the file otherwise it will fail our php lint which is php 5.5.

**Comment by Seldaek** [comment]
IMO the right solution to this problem is to skip linting that file. I can't imagine this is impossible to do. I understand it might be a bit of an issue, but as far as I've seen we have WP and WikiMedia essentially refusing to bulge on their linters and they cause a bunch of issues for all their users. I am not going to add yet-another-flag for something that is essentially not broken.

**Comment by paladox** [comment]
Oh. But could we add a flag so if someone wants to disable it they can. Having autoload_static can stay on by default. But it causes problems for others.

**Comment by Seldaek** [comment]
Adding flags is nice and all but I need to maintain this code full of flags, so if I don't see a reason to add one I rather not. And no someone having an overly trigger happy linter is not a valid reason IMO. We discourage committing the vendor dir too by the way.
