### ISSUE TITLE
Default composer init settings

### ISSUE THREAD

**Issue by CupOfTea696** [composer/composer#5357]
Hi,

It'd be useful to be able to configure default settings for the `composer init` command. For example, when I run `composer init` it always uses `cupoftea696` as a vendor name, but I use `cupoftea` as a vendor name for my composer packages. It'd be useful to set a global config option so that I don't have to customise the package name for each package I create. I imagine it'd be useful for all composer init settings, so that people can set a default license, minimum stability, ...

**Comment by curry684** [comment]
If you have a full template of default settings, why not copy that to `composer.json` instead of using `composer init`? It doesn't seem like a really useful feature to me to build all of this into the init command as to be honest I don't think that many people actually use it - everyone I know just copies a stock file or creates it completely by hand.

**Comment by CupOfTea696** [comment]
I actually use `composer init` quite a lot.

**Comment by dbrumann** [comment]
I might be mistaken, but isn't this already supported?

```
mkdir my-package && cd my-package
composer init --name="acme/my-package"


  Welcome to the Composer config generator



This command will guide you through creating your composer.json config.

Package name (<vendor>/<name>) [acme/my-package]:
```

The option also has various levels of fallback if it's not used: https://github.com/composer/composer/blob/master/src/Composer/Command/InitCommand.php#L191-L204

**Comment by CupOfTea696** [comment]
@dbrumann That still requires you to type it every time you run `composer init`.

**Comment by jvasseur** [comment]
@CupOfTea696 you could create an alias that already contains the wanted default options.

**Comment by naderman** [comment]
How often do you realistically use composer init that typing those few characters justifies adding 40 lines of code and a new config file to this project that will need to be maintained for all eternity?

**Comment by curry684** [comment]
I'd be a lot more open-minded towards some optional env variables, like `COMPOSER_DEFAULT_VENDOR`. Hell we could just for the 3~4 properties involved also expose `COMPOSER_DEFAULT_AUTHOR`, `COMPOSER_DEFAULT_LICENSE` and `COMPOSER_DEFAULT_EMAIL`, and if set skip the question. Lot more practical than a separate config file for reasons given above.

**Comment by CupOfTea696** [comment]
@curry684 that's actually not a bad idea, tho I don't necessarily think we should skip the question? Just change the default suggestion.

**Comment by curry684** [comment]
Fine with me.

**Comment by zachflower** [comment]
@curry684 that's a great suggestion, and the intention of my PR wasn't necessarily to propose the _only_ solution, but to at least get the discussion started (I should have made that more clear in my description, so for that I apologize). I'd be happy to update my PR to utilize environment variables instead of a config file, if it makes more sense to the community?

As to @naderman's comment, I absolutely understand the concern around a new config file (see my comment to @curry684 above), but I feel the _need_ for a solution (not necessarily the exact one I suggested) is there. As a contract developer, I use `composer init` at least once or twice a week (if not more) for new client projects, and while bash aliases can shortcut some of this, it's not an ideal or portable solution.

**Comment by curry684** [comment]
Make a PR with the env variables in the init command only and you have my blessing :smile:

**Comment by zachflower** [comment]
@curry684 done and done 😃 https://github.com/composer/composer/pull/6743/files

Thanks again for the suggestion!

**Comment by Seldaek** [comment]
Merged COMPOSER_DEFAULT_*
