### ISSUE TITLE
--no-dev is not respected when updating a component

### ISSUE THREAD

**Issue by dmitryd** [composer/composer#5358]
Starting from version 1.2 (1.1 was ok), composer does not respect `--no-dev` option when executing the following command:

```
composer update --no-dev vendor/package
```

Version 1.1 produced:

```json
    ],
    "packages-dev": null,
    "aliases": [
```

Version 1.2 makes:
```json
    ],
    "packages-dev": [
        {
            "name": "fabpot/php-cs-fixer",
            "version": "v1.11.2",
            "source": {
                "type": "git",
```

So `--no-dev` option is ignored when updating a single component. There is nothing relevant with `-vvv` but the output is huge due to many components (not pasting here).

**Comment by stof** [comment]
This is expected. Dev dependencies are always resolved but not installed, otherwise the lock file would be produced in an inconsistent state:

- not talking the dev dependencies into account during the resolution when running with ``--no-dev`` means that non-dev dependencies might be selected at different versions depending on using ``update`` or ``update --no-dev``
- a lock file generated without locking dev deps is incomplete, and would make ``composer install`` break if you use it without the ``--no-dev`` option.

This is why dev deps are always resolved when running ``composer update`` now, and ``--no-dev`` impacts only the installation step. If you look at your vendor folder, you will see that this package is not installed.

btw, I think you are talking about 1.0 vs 1.1, not about 1.1 vs 1.2 (1.2 does not exist yet, and this change was done in 1.1)

**Comment by Seldaek** [comment]
Yup, this is listed as `Fixed --no-dev updates creating an incomplete lock file, everything is now always resolved on update` on https://github.com/composer/composer/releases/tag/1.1.0 - you didn't really explain what your problem is though. It does respect the --no-dev in the sense that it doesn't install the dev dependencies, but internally we resolve everything, and the lock file contains all info.

**Comment by dmitryd** [comment]
> btw, I think you are talking about 1.0 vs 1.1, not about 1.1 vs 1.2 (1.2 does not exist yet, and this change was done in 1.1)

`1.2-dev (74e8f4479917608d573e54e1b9b4a1e52e724110) 2016-05-13 07:15:42` is the version that creates `packages-dev` always.
`1.1-dev (de7123097e2e8a82997f41a844bee297dafcd4f0) 2016-04-12 08:12:34` is the version that does not create `packages-dev` during `update`.

So `update --no-dev` means that:

- `packages-dev` are still updated
- dev packages will not be installed when updating with this option.

If The above is correct, than the issue can be closed :) Thank you.

**Comment by Seldaek** [comment]
The 1.1-dev you have there is pre-1.1.0 so it might not contain that change, but 1.1.0 does have it. Anyway yes that is correct, so closing :)

**Comment by dmitryd** [comment]
The problem was that we have a production system that uses a different composer version than some dev hosts. Our `composer.lock` files usually do not have `packages-dev` when we prepare for production. Now we called `composer update --no-dev` to install security updates for a component in production and it suddenly made a huge diff in the `composer.lock`. That's why it looked like a bug to me.

**Comment by dmitryd** [comment]
Not really a problem anymore because it is not a bug.

Thank you again.

**Comment by stof** [comment]
> Our composer.lock files usually do not have packages-dev when we prepare for production.

Just update your composer to the latest stable on the dev hosts, and this won't be an issue anymore
