### ISSUE TITLE
How to update a sekeleton application created with create-project?

### ISSUE THREAD

**Issue by odan** [composer/composer#5361]
In order to build a application, I start with a "Skeleton Application" available on github.  I use composer to create a new project from scratch e.g.:

`php composer.phar create-project --stability="dev" acme/skeleton-application path/to/install`

Question: How can I update my project after I have done some implementation?
Is there somthing like "update-project" or how to handle this?

**Comment by alcohol** [comment]
That entirely depends on what you mean by "update". 

On the surface your question does not seem Composer related at all, but rather about PHP development in general (I am guessing you are a beginner?).

**Comment by odan** [comment]
@alcohol No I'm not a beginner! Why don't you ask me **before** making **totally wrong assumptions**?

**Comment by stof** [comment]
Once a project is started, your files will probably not match the files provided in the skeleton anymore (otherwise it means your project does not provide more value than a skeleton, which provides no business value except maybe a "Hello world").
This means that updating such things requires understanding of which changes you made in your project compared to the skeleton, and which changes the skeleton made, to see how they should be reconcilied.
In any case, this is not Composer's job to handle it.

**Comment by Seldaek** [comment]
It's really not something we can fix, as it would mean applying diffs and a bunch of things that tbh sound like more work than it's worth.

However to answer you, the best way I know of if you want to update the skeleton files easily, is to create-project with --keep-vcs, and just base your project on top of the skeleton's repository history. That way when you want to update, you can fetch from the skeleton repo and merge their changes into yours. You'll probably have a few conflicts to resolve, but it can still be easier than figuring out what changed manually.
