### ISSUE TITLE
different installation path since 2 days

### ISSUE THREAD

**Issue by beanieboi** [composer/composer#5399]
hey,

we are running the following command to preinstall phpunit on our CI platform.

```
"${HOME}/bin/composer" global require "phpunit/phpunit=4.8.*"
```
somehow the install path changed in the last release. here is the output from composer when running the command

working (2 days ago): `Changed current directory to /home/rof/.composer`
not working (today): `Changed current directory to /home/rof/.config/composer`

do you have any glue why the install path changed? is there anything i can help with debugging this?

i'm running the same code that was working 2 days ago, really nothing changed on our end.

**Comment by alcohol** [comment]
This seems related to XDG homedir setup. See #1407 for some context.

**Comment by alcohol** [comment]
It could be your build environment changed.

**Comment by Seldaek** [comment]
Yeah the installer script didn't use to respect the XDG settings, but now it does, so on new setup on XDG-compliant machines, we place it in ~/.config/composer by default.

I'd advise you to either update your config so you use `~/.config/composer/vendor/bin/phpunit`, or define a COMPOSER_HOME environment variable so that you define where it goes, or use this to define the binDir and call it no matter where it ends up (that's the most robust I guess):

```
binDir=`composer global config bin-dir --absolute 2>/dev/null`
$binDir/phpunit ...
```

**Comment by beanieboi** [comment]
hey,

thank you so much! i can update our paths, that totally works. it would be really awesome if you could update the Changelog and mention it there, i checked all the docs and couldn't find this. this could potentially break the setup of users, it would be great if the this explanation you gave can be easily found.

thanks you so much again.

**Comment by Seldaek** [comment]
NP, the thing is that it only affects *new* set ups, so it's not strictly a big change or break, except for things like CI where you set up new envs every time I guess. Hopefully it won't affect many people :)
