### ISSUE TITLE
Local repository / package cache

### ISSUE THREAD

**Issue by naderman** [composer/composer#54]
All downloaded packages should be stored in a local repository, e.g. $HOME/.composer which is also automatically loaded. This will avoid duplicate download of the same package if you use composer in multiple projects.

**Comment by mjonas87** [comment]
Not sure if this is the *best* place to comment, but it does seem to be the root of my current troubles. I'm using Composer with Docker

**Comment by mjonas87** [comment]
Not sure if this is the *best* place to comment, but it does seem to be the root of my current troubles. 

I'm using Composer with Docker, which means I'll only ever be installing packages for this one project. When I do this, Composer builds a local cache from source of every package (even when `--prefer-dist` is set). This takes a very long time and often fails due to Github throttling. 

My main question is this: *Does this caching system trigger additional downloads beyond what would be required for a minimal installation or am I misunderstanding something?*

Thanks!
