### ISSUE TITLE
Suggestion: allow fo the "secure-http" flag to be set inside "repositories"

### ISSUE THREAD

**Issue by Pixelfck** [composer/composer#5443]
Right now, when I need 1 non-http**s** repository, I need to allow non-http**s** for *all* repositories:

```json
{
    "config": {
        "secure-http": false
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "http://packages.example.com"
        }
    ]
}
```

However, I would like to propose an alternative, more restrictive, syntax:
```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "http://packages.example.com",
            "secure-http": false
        }
    ]
}
```
by which I would like to tell Composer to *only* allow non-http**s** traffic to this specific url.

**Comment by alcohol** [comment]
It definitely would be a nice addition to have more fine control over this flag. I'll add it to the feature request list :-)

**Comment by Seldaek** [comment]
We have given up on adding this already because it doesn't seem possible to do it safely. If you allow for one url over http, there is nothing guaranteeing that you are indeed accessing that URL. If you use http you are not safe anymore, period. So there is really no point in having more complex configuration if it anyway leads to the same lack of security.
