### ISSUE TITLE
PHP extension requirements are not excluded by the --no-dev switch

### ISSUE THREAD

**Issue by Bilge** [composer/composer#5444]
With the following composer.json:

``` json
{
  "require-dev": {
    "ext-soap": "*"
  }
}
```

When I run this command:

```
composer update --no-dev -vvv
```

I get this output:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-soap * is missing from your system. Install or enable PHP's soap extension.
```

And I expected this to happen:
Composer will not attempt to load any `require-dev` dependencies when `--no-dev` is specified.

**Comment by curry684** [comment]
This is the same issue as https://github.com/composer/composer/issues/5227. I fully agree this is a bug now though. As a practical use case - when developing a cache library it's perfectly fine to require `ext-predis` during development to be able to run the entire test suite, but that's shouldn't block installation on a production system only using Memcached or file system caches.

It's not hard to fix but I'm hesitant to make a PR on this as @Seldaek broke it 'on purpose' in https://github.com/composer/composer/issues/5016 and #5224.

**Comment by alcohol** [comment]
@Seldaek I have mixed feelings about this too :-(

**Comment by patrickkusebauch** [comment]
I wrote it on #5227, but I also have issues with this not working as expected. In my case its because of PHP version required by one of the packages in "require-dev" section. I "fixed" it for me by using the `--ignore-platform-reqs` flag, but that doesn't seem like the right course of action to me.

**Comment by Seldaek** [comment]
@patrickkusebauch the way to fix it in your case is to commit the composer.lock file to make sure `composer install --no-dev` on pre-prod uses the lock file instead of doing an implicit update.

**Comment by Seldaek** [comment]
As for the original issue here, one possible fix would be to ignore the platform requirements of the root package in require-dev, but it would still include the platform requirements of the require-dev requirements (nth-level platform dependencies). It doesn't fully fix the issue though, it just alleviates it a bit, so I don't know if it's not worse than the current rule which is at least simple.

@curry684 Generally speaking, the cache library example you have is not applicable because when developing the lib you need the dev dependencies, and when installing the lib you install it as a dependency and therefore the dev dependencies are properly ignored. The only issue is what to do with the dev dependencies of the root package.

**Comment by Seldaek** [comment]
Auto-closing as this hasn't been updated in over 6months and is marked as a question. If there is a real bug to consider please let us know.

**Comment by Bilge** [comment]
@Seldaek It may be *marked* as a question, but how is it _actually_ a question? I certainly didn't mark it as such. As far as I am concerned this is, and has always been, a bug.

**Comment by Seldaek** [comment]
I understand, reviewing this gain though, I really don't see what we can do. As long as we resolve all dependencies at once there isn't an easy way to prevent this issue. It's an unfortunate side effect I agree but I don't see a way out :/
