### ISSUE TITLE
Skip "http is an insecure protocol" warning for localhost

### ISSUE THREAD

**Issue by Pixelfck** [composer/composer#5448]
When I have set the non-secure flag:

``` json
{
    "config": {
        "secure-http": false
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "http://localhost"
        }
    ]
}
```

Composer throws a warning:
`Warning: Accessing localhost over http which is an insecure protocol.`

Maybe skip the warning for `localhost` (and `127.0.0.1`), because `localhost` traffic typically does not leave the machine.

**Comment by alcohol** [comment]
But it is still an insecure protocol. I do not think this really warrants an exception.

**Comment by Jacco-V** [comment]
Yes, http is an insecure protocol. However, at the same time, traffic to `localhost` *is*, by design, an exception.

<br>
Let's examine why `http` is 'insecure' by looking at why `https` is 'secure'. The difference between `http` and `https` lays in the fact that for `https`:

* the operator of the destination endpoint (let's call this 'the server') is guaranteed<sup>1</sup> to <s>be</s> have been in control of one of the 'administrative'<sup>2</sup> email addresses @ the domain name, specified in the certificate;
* the in-transit data is encrypted between two endpoints and thereby protected against tampering and eavesdropping.

Both parts are, given our threat model, equally important: one the one hand, having an encrypted, tamper proof connection to a malicious server is not going to protect your from downloading malware. On the other hand knowing that you speak to the 'owner' of domain, while the data could be manipulated before reaching the client would be equally bad.
Another property of `https` is that the traffic is protects against passive eavesdropping (a MitM can only determine the endpoints of a TLS connection, not not read the data), thereby protecting (some) aspects of privacy.

<br>
So, the whole point of `https` is to guarantee your endpoint and protect your data 'on the wire' (which nowadays typically also includes wifi).

So, lets get back to our connection to `localhost`. Localhost traffic is typically routed locally: your machines realises that traffic destined for `127.0.0.1` is destined for itself and handles it on the local hardware<sup>3</sup>. In other words, data is never *send* over the wire: the local machine knows it is talking to itself (no need to for a third-party certifying this fact) and there is nobody who can sniff it, except a the machine itself (so there is no point in protecting against tampering or sniffing *by* oneself).

So, while 'http' is an 'insecure protocol', it does not automatically mean that all `http` traffic is insecure, just as a `https` connection to `localhost` does not make it *more* 'secure'.

<br>
Given the above, and that `localhost` is an exception by design, I think it would warrant an exception from the warning message being shown. 

<br>
<sub><sup>1</sup> guaranteed, up to a certain level of confidence, which is typically expressed in maximum insured financial damages.
<sup>2</sup> the definition of 'administrative' email addresses differs from CA to CA. Some use other, comparable, methods to determine 'ownership' of a domain name. For an EV certificate, the check are (or at least should be) more thorough.
<sup>3</sup> it is, of course, possible to redirect `localhost` to some other (external) IP address. This can be done intentionally by the owner of the machine (unlikely, but possible) or by malware with sufficient privileges. In the latter case, the battle has already been lost.</sub>

**Comment by alcohol** [comment]
I appreciate your enthusiasm, but do you really **need** this change? Does it hinder your every day use of Composer in any significant manner?

**Comment by Pixelfck** [comment]
Well, I can work around this limitation by setting the `"secure-http": false` flag, but it is rather silly to open up everything to unecrypted http, if I just want to connect to localhost (without https).

**Comment by Seldaek** [comment]
ping @stormtide any thoughts on this (tl;dr whitelisting 127.0.0.1/::1/localhost for http)?

**Comment by StormTide** [comment]
@Seldaek I'm not sure I could predict the harm from this... I don't think the usual concerns that would apply to /any other ip/ even a lan ip opening the whole scheme up to mitm apply as localhost traffic never leaves the box and operates on a separate LO interface. There's some risk re ports for a local privilege escalation vector, but only insofar as you allow localhost on an unprivileged port... on port 80, shouldn't present a security issue as you need root to open that port anyway... 

That said, I would probably still add this as a separate option rather than a blanket whitelist... something like 'allow-localhost-http'=>true or similar for those who need it. 

HTTP traffic on a LO interface /should be/ safe as far as I know, but then, this stuff all runs on windows and different TCP/IP stacks too, so I can't say that with confidence on all platforms.

**Comment by Seldaek** [comment]
Auto-closing as this hasn't been updated in over 6months and is marked as a question. If there is a real bug to consider please let us know.

**Comment by LucasDemea** [comment]
When using a command like `composer show --available --format=json`, this warning is appended to the json output and can cause issues.

**Comment by cfahner** [comment]
> I appreciate your enthusiasm, but do you really **need** this change? Does it hinder your every day use of Composer in any significant manner?

I ran into this issue just now. I am using Satis on my local machine to create a repository on localhost based on a variety of private git repositories and don't want to allow insecure requests by default. If setting up an exception for localhost has been added since this issue was closed, please point me to it.
