### ISSUE TITLE
Dependency hell - seeking possible solution

### ISSUE THREAD

**Issue by dannykopping** [composer/composer#5450]
I am developing a client library - let's call it "X".

X depends on the monolog library (or any lib, really), version 2.0 (for example)

I'm including X as a dependency in project "A", which depends on the mutually incompatible 1.0 - let's say.

Refactoring A is obviously an option, but not feasible in this scenario.

When I try to include X in project A, this is not possible because X depends on monolog v1.0 and A depends on monolog v2.0. Resolving this dependency either way (to v1.0 or v2.0) will cause issues, so Composer borks, correctly so...

Composer seemingly flattens the dependencies across all libraries into the `vendor` directory, and only includes 1 version of each dependency. This is presumably because the namespace defined in each project is seen as immutable.

One possible solution of this would be the following:

`A/vendor/monolog` -> v1.0
`A/vendor/X/vendor/monolog` -> v2.0

As opposed to the flattened structure, this structure will maintain the dependency hierarchy, and dependencies on different levels which are equivalent can be symlinked, using the top-most node as the source.

This method would obviously necessitate "rewriting" the namespaces of the v2.0 version of the library, similar to how Laravel's `php artisan app:name Blah` command [implements it](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Console/AppNameCommand.php#L112)

When `use`ing monolog in project A, one might do it as follows:

`use A\Monolog\Logger;`

and in X:

`use X\Monolog\Logger;`

With this implemented, configuring the autoloader should be fairly trivial.

This seems like one possible solution to dependency hell. My little brain is not capable of seeing any major issues with this approach (other than the aesthetic, and some possible changes to the `composer.lock` file implementation), but I'm prepared to submit a PR for this if there's a general feeling of "screw it, just do it".

**Comment by majkel89** [comment]
I think you should start another project for this. Something like PhpNpm.

**Comment by prog-rajkamal** [comment]
In X library, create separate branches for monolog's version 1 and 2. and use mono v1 branch for use in A.

**Comment by dannykopping** [comment]
That might work with just one dependency, but the moment you add more,
you've now got a big branching issue... if I'm understanding you correctly

**Comment by prog-rajkamal** [comment]
So let's see if i got this right. 


You are writing a library X, which depends on library Lib1, Lib2 and Lib3. You need to use X in project Y. but project Y uses different version of Lib1, Lib2 and Lib3 and those versions of Lib[1,2, 3] are incompatible.


Well, if that's true. then your library X has a design issue and is not fit for general use case.

that being said, Its practical to assume that a project Y  will always use latest (stable) set of libraries, instead of an arbitrary combination of version. So you can provide branch for only the combination of libraries which are *most likely* to be used together instead of every possible combination. 


Another alternative is to make library X agnostic to Lib1, Lib2 and Lib3's versions. and *inform user to manually install the libraries* in Readme.md

**Comment by alcohol** [comment]
This has been proposed before. It is simply not feasible.

**Comment by dannykopping** [comment]
Can you elaborate please?

**Comment by alcohol** [comment]
See #4313 for example.

**Comment by dannykopping** [comment]
Thanks @alcohol - I understand

**Comment by EvaLok** [comment]
@dannykopping i did consider doing this a year or so ago, but given the wide variety of issues pointed out in #4313, it seems like it would - if possible at all under all scenarios - be very challenging at best.

however, i can give my take on things in case you have not considered these points..

something that you can do on your side which is relatively painless in order to get around dependency hell in most situations, is to abandon monolith app architecture and use a microservice architecture instead. if you do this, you can not only avoid dependency hell with relative ease, you can also of course write your microservices in any mix of languages. if you are working on a pre-existing app, you could opt to use a microservice for the piece of functionality which is causing dependency hell while keeping the rest of the app as-is.. in its crudest form, it might be as easy as this:

```php
// before
// $result = $someDep->someMethod($args);

// after
$result = queryMethod('someDep', $args); // eg: sends $args to microservice endpoint
```

dependency hell can be resolved by module vendors by:
- starting a new project instead of a new major branch when the update would case dependency hell, an example of this being done can be seen with `phpleague/url` to `phpleague/url`:
https://github.com/thephpleague/url
https://github.com/thephpleague/uri

- adding a version to namespaces, like `project/v1/class` and `project/v2/class` and never removing old code (similar to what you suggested, but done by the vendors instead of by composer)

**Comment by stof** [comment]
@EvaLok having the version in the class namespace means that any new major version is a huge BC break forcing to update the whole ecosystem, even when the actual need for a BC break would impact only 5% of users otherwise. So it is not good for the ecosystem.

@dannykopping your proposal of renaming classes would work only if the class never returns an object coming from one of its dependency (as renaming the class would change the signature of the return value) and never asks for any class coming from its dependencies in an argument (again to avoid changing signatures), which makes this unusable for most packages out there.

**Comment by EvaLok** [comment]
@stof well i mean a vendor could always include a non-versioned namespace as well which is the most current version, but it's not as if this practice will become standard anyhow, so it's all academic ;)

**Comment by dannykopping** [comment]
@EvaLok of course microservices or some other approach would obviously work, but in my current scenario - this is not possible

**Comment by dannykopping** [comment]
@stof agreed - changing namespaces does indeed seem like an impractical idea after reading your comments and @Seldaek's from the other issue

**Comment by stof** [comment]
@EvaLok but the versionned and non-versionned classes are 2 different classes, so you are actually making things worse if you have both (code using one of them is incompatible with code using the other, and code using the non-versionned classes still suffer from your issue)

**Comment by EvaLok** [comment]
@stof i'm not sure i follow 100%, but yes it's certainly an imperfect solution. i'm not sure there is a great (not extremely complex) solution given the namespace constraint that comes with PHP.. hopefully one day we'll see one, though

**Comment by stof** [comment]
@EvaLok class names are part of method signatures as long as your receive an object as argument or you return an object. So having 2 different class names is unmanageable.

The restriction we have is that PHP uses classes for its object model, and so class names are unique (this is true in other class-based languages btw).
Discussions about this topic keep pointing to NPM not having this issue, but this is because Javascript is not class-based but prototyped-based, and so you build object types by referring to other variables, allowing to scope things like any other variable (and btw, the setup used by npm still break if a package returns one of its dependency to a higher level, which is then used to pass it to another package expecting a different version of the same dependency).

**Comment by EvaLok** [comment]
@stof thanks for the detailed explanation! it's an issue that seems simple on the surface but is actually pretty complex (which is i suppose why we haven't seen any amazing solutions yet..)
