### ISSUE TITLE
RFC: Architecture for plugable repositories

### ISSUE THREAD

**Issue by PhilLello** [composer/composer#5453]
Over at https://github.com/dunlop-lello/composer-moodle, I've written a custom Repository plugin to massage a 3rd-party plugin feed into installable components. It works well enough, but bootstrapping a checkout is tricky. On a clean checkout I need to run composer install with just the plugin in composer.json, then add the dependencies and run again. This is because, quite naturally, the packages provided by the plugin aren't available before it is installed, so dependency resolution fails.

I've been thinking about how to address this, and I think the best approach to support plugin repositories is to assume any repository type matching "`<vendor>/<plugin>`" is a plugin in one of the other repositories, and to try to from install there at somewhere early in the composer process - perhaps around the time RepositoryManager:;factory() is first called.

Happy to write the code, but does this approach fit in with the composer architecture?

**Comment by alcohol** [comment]
@Seldaek knows more about plugins.

**Comment by Seldaek** [comment]
This is really hard to integrate well within our current model, because it would require knowing in advance which packages are provided by a plugin that is not yet installed, and then do a partial resolution, install the plugin, then do a full resolution including the packages provided by the plugin.. It's just adding a lot of mess in a piece of code that's already quite complex. All for fringe cases that can be best served by other methods.

IMO the way to go is rather to create a tool that converts the feed into a composer repository, so you can run that as a background job and then expose the composer repo straight to composer and have that work out of the box.
