### ISSUE TITLE
^self.version

### ISSUE THREAD

**Issue by JorisDebonnet** [composer/composer#5484]
This is a feature request, hoping it actually makes sense. :)

silverstripe/installer's composer.json includes the following:

``` json
{
    "require": {
        "silverstripe/cms": "self.version",
        "silverstripe/framework": "self.version",
        "silverstripe/reports": "self.version",
        "silverstripe/siteconfig": "self.version"
    }
}
```

That's great to keep everything up to date when testing synchronized dev-master packages etc. But that installer package doesn't really need to change all that often, it's just `create-project`'ed and only the dependencies (above) introduce new features and/or bugfixes. 

So what would actually be great is if something like "^self.version" would work. The benefit is mostly for users of the package, so that when they install it, and later `composer update`, that they do in fact get the newest releases. That currently doesn't happen because the installer package itself is never updated, and so those dependencies aren't either, because they are tied to a fixed self.version.

I know people can just edit composer.json of course -- but it seems nice to be able to support updates out of the box.

**Comment by Seldaek** [comment]
I don't really see why the installer uses self.version to be honest.. It should just require `^<current branch it targets>` so in master right now it could require `^4.0@dev`, once 4.0 stable is out change it to `^4.0` perhaps.

IMO the installer shouldn't change as much as the rest of the cms/framework so why keep the versions in sync at all times?

I don't really like the feature you request I have to say because it changes self.version from a "If it's exactly equal to that, use current version" to "Just blindly replace self.version in the string to the current version", and the latter might end up doing weird stuff or is at least less robust.

**Comment by JorisDebonnet** [comment]
Thanks for your comment, I have passed that along. As for this feature, it wouldn't necessarily need to be a blind replace, as - if I'm not mistaken - only `^self.version` and `~self.version` would need to be added. But I do realise it may not be as easy/consistent as it sounds, as things like `^dev-master` don't make sense.

**Comment by Seldaek** [comment]
Auto-closing as this hasn't been updated in over 6months and is marked as a question. If there is a real bug to consider please let us know.
