### ISSUE TITLE
Idea: make the Archiver a separate component

### ISSUE THREAD

**Issue by adrienrn** [composer/composer#5508]
I'm building a deployment tool that at some point needs to build archives.

I've roam the web and recon that composer seem to have the best archiver "library" out there, well designed with abstraction and powerful filters. 

That's all of those reasons and especially exclude filters and the path expansion from json for ignoring files that makes me think:

Would it be a good idea to make [the composer archiver code](https://github.com/composer/composer/tree/master/src/Composer/Package/Archiver) available as a standalone component useable by other projects ?
- Do you think that would be possible?
  Looking at the code, there's the necessary abstraction to do it with a few adherence with `Composer\Package\Package` and some `Composer\Util`
- Do you give me the go to outsource the archiver code to a separate repository?
- Do you think I should fork composer or create a whole new repository and import the archiver part only?

I'm thinking over my head but if that's useful to me, could be useful to more (https://github.com/composer/composer/issues/4040); and maybe someday composer could use it.

**Comment by alcohol** [comment]
I am not sure to be honest. I think it is in our interest to slowly but surely try to determine which parts of Composer could be more decoupled and offered as separate components, and which not. We do not really have a set of guidelines or ideas though specifically on this topic. One thing to keep in mind, is that the archiving functionality is also used in [Satis](https://github.com/composer/satis).

/cc @Seldaek any thoughts on this?

**Comment by stof** [comment]
I think it could make sense to extract it.

However, currently, the archiver depends on several things:

- the Finder component  (expected as we need to find files to add them to the archives)
- the Package system (this is the input of the archiver)
- the Downloader (to download the package source code when it is not a root package)
- the JsonFile utility class (to read the composer.json file from the downloaded source code, as non-root packages don't always hold the archive excludes, as Packagist does not store them)
- the ``Composer\Util\Filesystem`` utility for filesystem operations

Regarding this, I'm not sure an extracted library should be responsible to download the source code of a package (I have not included the list of things necessary for the Downloader here).

The dependency on Package is needed for several things:
- knowing the package source type to pass it to ``Archiver::supports``. But all archivers are ignoring it, as they don't care about the source anymore since they are not responsible for downloading the source code, so this should be cleaned.
- guessing a filename for the archive when it is not provided explicitly. This could be handled outside of the extracted library by making the archive name mandatory
- downloading the source code if it is not a root package (and deciding whether the downloaded code should be deleted at the end)
- getting archive exclude rules

A solution could be to extract a system able to generate an archive based on code available locally already rather than from a Package object. ``function archive(PackageInterface $package, $format, $targetDir, $fileName = null)`` would then be replaced by ``function archive($sourceDir, $format, $targetDir, $fileName, array $archiveExcludes = array())``.

We could then keep a class in Composer itself which would use keep the logic about guessing the filename from the package and downloading the source code for non-root packages.
This would make the archiver component decoupled from every other parts of Composer (it would only need the Finder component, and the ``Composer\Util\Filesystem`` utility, and this one may be replaced by the Filesystem component from Symfony, as the features it needs are also available in it now)

**Comment by stof** [comment]
In this case, Satis would probably keep using the class from Composer as it also needs the full logic about the Package, but this is not an issue as it already needs to depend on Composer due to using many other parts of the stack.

**Comment by adrienrn** [comment]
Thank you for your feedback on this!

Like you said, the archiver component shouldn't be responsible of downloads.

However, having some kind of 'Package' notion would make sense even in the archiver component but not as a composer package, more like a general abstracted notion for archive descriptors holding (at least):

- Filename
- Format (zip, phar, etc) + that `::supports` feature
- Archive exclude files
- Some options for the archive to be built: thinking compression or always create a directory at root maybe or Phar-related options

-

Do you think I should fork composer – or start a new repository – and give it a try ?

**Comment by Seldaek** [comment]
Maybe a good first step would be to split some of the code in this repo, 
then once we have something with a clear boundary I can extract it into 
its own repo like was done for composer/semver for example.

**Comment by alcohol** [comment]
@adrienrn as @Seldaek suggested, what you could do is create a pull request against [composer](https://github.com/composer/composer) which would contain a directory named `src/Composer/Archiver`, in which you move all the files related to this component (and namespace it as such). This way, once everything is in order, we can just extract this specific directory into its own repository.

**Comment by Seldaek** [comment]
Note that not everything should be moved in there, only stuff that needs to be extracted.

**Comment by stof** [comment]
@adrienrn the format and compression things are *not* part of the Package concept in the current code.
