### ISSUE TITLE
Disabling plugins for composer scripts

### ISSUE THREAD

**Issue by matt-usurp** [composer/composer#5509]
So plugins are initialised (at least, not delved in to composer code in a while) before running any of the custom defined scripts in `script`. Is there a reason for this? Surely its just meant to be a pass through or syntactical sugar?

## My Scenario ..
.. is pretty unique but raises this question. We have a `docker` setup for our project and I thought it would be great for people to just clone our project, run a composer script and get going. So the issue we have right now is `ocramius/package-versions` is written only in `php-7.0` and mac osx comes with `php-5.5` by default. Now we don't really need to upgrade the mac php version as the docker container contains the correct version `php-7.0`.

Getting to the point, imagine we have the following script. Take it with some salt, this is to prove a point, in the real world we have commands that execute database fixtures in a similar way.
```json
{
  "scripts": {
    "test": "docker exec php bash -c 'composer require ocramius/package-versions'"
  }
}
```

Running `composer test` will work fine, but the composer package installed above is a plugin and registers itself. Now its impossible to run any composer scripts (the same command again for example) on our local machines because of syntax errors. This would be fixed if plugins were not initialised for the script execution. For now we can work around this by `docker attach php` but this is not the solution.

**Comment by alcohol** [comment]
I do not see an actual problem described here, sorry. If you share your local working directory with the php container, then of course this will break things on your local host if that is running a different php version. This is why container content (code) should be added through COPY, not by mounting a volume. While the latter can sometimes be considered "convenient" during development, it will lead to obvious issues such as the one you are encountering now.

This has nothing to do with whether or not plugins are initialized for script execution. Also, look into the `--no-plugins` and `--no-scripts` flags for further details.

**Comment by matt-usurp** [comment]
This is not a question with docker, best practices aside the issue is with composer scripts and how it invokes plugins when executing scripts shouldn't require them.

Now I did originally forget to mention this in the main post, but the follow will also fail.
```
$ composer test --no-plugins

Parse error: parse error, expecting `';'' or `'{'' in /Users/mrose/Projects/brain/brain/vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 98
```

I thought no-plugins was meant to disable them?

**Comment by alcohol** [comment]
Did you try `composer run-script --no-plugins test` ?

**Comment by matt-usurp** [comment]
No I hadn't, but just tried and resulted in the same output.

**Comment by stof** [comment]
Plugins are initialized when running a composer command, because plugins can provide new commands

**Comment by alcohol** [comment]
Yeah I was not sure if that was the case. I was hoping it would not do that. But my second guess would have been that `--no-plugins` merely prevents dispatching the events to plugins; meaning that it does load them on init.

**Comment by alcohol** [comment]
Anyway, the result is still obvious and related to the use of docker. The plugin normally would fail installing because of your local php version. But since you ran the install command inside a docker container with the right php version, it happily installed (into your shared volume).

**Comment by matt-usurp** [comment]
Again, the install of the plugin is not an issue. The fact that it inevitably is ran on a `php-7.0` box is fine, our staging and production servers are all running this. The question is really what is the purpose of the composer scripts functionality, because at its root I would say the implementation might be wrong.

@stof Thanks for giving an answer that is not related to docker and more to the core question.

Is there a priority followed? Does `scripts` definition trump a composer plugin? Should it? If the `scripts` take priority over composer plugins then I would say there is no point in initialising the plugins and just delegate to a process. I have a funny feeling that as the code base isn't so flexible at this point in time a decision is just going to be made that "its working how it should".

**Comment by alcohol** [comment]
Well, yes, it is working as it should. :-)
Plugins are loaded on Composer init.

**Comment by stof** [comment]
@matt-usurp scripts can be run as ``composer <scriptname>`` only when it does not conflict with existing commands (including the ones provided by plugins). Scripts don't have the priority (as it would make it possible for a project to overwrite what ``composer install`` means, making it impossible to run an install). This is why we have the ``run-script`` command allowing to run any script even when they conflict with a command btw.

Regarding your issue in your docker setup, I consider that the issue is that you run composer on a PHP version which is not supported by your composer project, and so it breaks.

**Comment by matt-usurp** [comment]
@stof Again, thanks for clarifying. This is exactly the answer I needed.

Regarding the docker issue, its not really an issue as its not related to this ticket. I know how to use docker, I just thought (before creating the ticket) it would be nice (as stated) to have a composer "script" or "command" that manages the docker containers for people who don't. As I said, we don't need to focus on this.

To clarify, assuming that composer plugins _didn't_ get initialised this _would have worked_ no matter what the php version (as composer is supporting `php5.5` anyway) but wanted to make sure this was expected. @alcohol thanks for replying, I want to stress that I was not meaning to be rude at any point above (if I was), it was just getting frustrated that you were focusing on `docker`.

**Comment by alcohol** [comment]
I was just clarifying that normally it is not an issue for plugins to be loaded (not used, just loaded) because you cannot really install incompatible plugins unless you use work-arounds, either intentionally or unintentionally. Hence I was focusing on Docker, since it is one of the work-arounds, and I was not sure if you were aware of this or not. You can do things inside a container that can leave the environment on your host in a "broken" state.

The fact that plugins are loaded during init, also has to do with the way they are loaded (it is not as straightforward as you might assume, if you dig into the code you might not like what you find).

No offense taken, just glad everything is clear now :-)

**Comment by Seldaek** [comment]
I found the issue.. --no-plugins wasn't respected across the board and in some instances you could still initialize installed plugins via some commands, for example the ScriptAlias one which is used when you run `composer test`. Fixed in https://github.com/composer/composer/commit/7bcd336c9500a14e3cb356195f308a98652d6dd9
