### ISSUE TITLE
support box-project/box2

### ISSUE THREAD

**Issue by robfrawley** [composer/composer#5568]
Why doesn't this repository have a `box.json` file so one can easily create a PHAR directly from source?

**Comment by alcohol** [comment]
We are open to pull requests. For an impression of what behavior you would need to mimic, see [`Compiler::compile()`](https://github.com/composer/composer/blob/master/src/Composer/Compiler.php#L40). I am not sure if Box can handle all of it, which could be why we do not use it. But then again, it has been a long time since I looked into it and Box might have come a long way since then :-)

**Comment by robfrawley** [comment]
Fair enough; I'll take a look and see if it isn't feasible with current box releases, and if so submit a PR. I wasn't sure if there was a *technical reason* for not having it.

**Comment by Seldaek** [comment]
The main reason is that box is inspired from our compile script, so we couldn't use it when it didn't exist :) Technically speaking though, we do a few things with the phar that I believe aren't supported, in terms of normalizing how the phar looks and code compaction and so on, I'm not sure though I haven't looked at box in details in a while. The bottom line is we have something that works and running `bin/compile` is easy enough so I don't see a big need to change it.
