### ISSUE TITLE
composer exec does not support running interactive commands

### ISSUE THREAD

**Issue by davidolrik** [composer/composer#5615]
When running `composer exec` with a command that requires interaction with the user, no interaction happens.

This happens because the `exec` command uses `Symfony\Component\Process\Process` for execution and captures all output.

Capturing all output also strips escape codes which means no color is shown.

**Comment by alcohol** [comment]
The former is known. We cannot delegate input/output to another process since we always run as a subprocess.

The latter is not true. By default, a subprocess is not recognized as ansi compatible for some reason. But colors are supported, if you simply pass the --ansi flag (or similar) to whatever you are running.

**Comment by davidolrik** [comment]
In the case of `composer exec` I seen no need to wrap it in a subprocess as a simple `system()` call will let us call any kind of command, even those that require interaction. (And it will show color by default).

**Comment by alcohol** [comment]
We only use `system()` once in our entire codebase, and I think that is just a legacy artifact.

**Comment by johnstevenson** [comment]
@alcohol 

> By default, a subprocess is not recognized as ansi compatible for some reason.

I'd imagine that this happens because the output from the child process is a pipe (to the parent), so the child doesn't add the color escape-codes because it knows it is not terminal (via `posix_isatty` or some such). Of course the parent could enforce the colors by adding the appropriate flag.

Incidentally, `composer exec` [initially supported interaction](https://github.com/composer/composer/commit/43551bc537db681e4c97a216c2b0cf099a75d25f), because it used `passthru` rather than the Symfony component.

**Comment by davidolrik** [comment]
@johnstevenson You are absolutely correct, the child process detects that it is running non-interactively and disables colors.

I have created my own local `exec` plugin that uses `passthru` which in my opinion makes way more sense than running it through Symhony.

**Comment by alcohol** [comment]
Problem solved then.

**Comment by davidolrik** [comment]
Not really, I would expect a command run with `exec` that prompts me "Are you really sure?" to not continue until I confirm. And I believe others would expect this as well.

**Comment by alcohol** [comment]
Well, we could just remove the functionality all together. Saves us the headache of having to meet everyone's expectations (:

**Comment by Seldaek** [comment]
@davidolrik might work on linux but if it is like https://github.com/composer/composer/pull/4036 it won't work on windows and is therefore not quite a solution. We need to be cross-platform.

**Comment by mh-ovos** [comment]
@davidolrik  would you share your exec plugin for executing composer scripts with passthru function, please?

**Comment by Artusamak** [comment]
Yes please @davidolrik could you do that, please? :1st_place_medal: Thank you!
