### ISSUE TITLE
Charset problem after php upgrade.

### ISSUE THREAD

**Issue by nitishrajuprety** [composer/composer#5628]
Recently I upgraded from wamp 2.5 to 3 and selected php 7.0.3 as default php version for it. Since then when ever I run composer from command prompt there is charset problem with output text. I've attached a screenshot of the same. Thank you.
![composer-error](https://cloud.githubusercontent.com/assets/21262348/18006605/0cd6f3c4-6bc0-11e6-931c-b6b4600bd167.jpg)

**Comment by stof** [comment]
This is not a charset problem. It is because the shell is detected as supporting ANSI colors, while it does not.

This is because Symfony Console was updated to account for the color support in new versions of Windows 10, and the next Windows 10 update reverted the feature (not entirely, but it now requires executables to opt-in, and php.exe does not yet use this windows feature).

There is a patch for Symfony to fix this (until PHP supports the feature), but it is not yet released and so the version used by Composer is still affected.

for no, the workaround is to use the ``--no-ansi`` option when calling composer, to force it to disable ANSI colors instead of detecting the color support.

**Comment by nitishrajuprety** [comment]
@stof  Thanks for the information. I tried with `--no-ansi` and composer output was normal again.

**Comment by cirdog** [comment]
If this hasn't been mentioned before, the global workaround for Windows is:

```
C:\ProgramData\ComposerSetup\bin\composer.bat
(edit its content)
php "%~dp0composer.phar" %* --no-ansi
```

Adding the "--no-ansi" flag at the launch script of composer eliminates the need to flag it for every command.
