### ISSUE TITLE
Packages don't update to latest commit / Package repo fails to update

### ISSUE THREAD

**Issue by rdohms** [composer/composer#563]
When declaring packages inside the compose.json file, if reference points to `master` then running updates does not check out the latest commit in the master branch.

Expected behaviour:
Composer should see that branch is master and check if commit hash is the same as HEAD, if not it should checkout head.

Actual behaviour:
Composer sees that branch is master and ignores the rest.

Temporary workaround is to add the actual commit hash into the reference field, which gets the desired outcome but add overhead in updating.

Ideally reference should also accept dev-master as code for always getting the latest commit, or simply update to latest commit in everything but tags.

**Comment by sp-juan-hernandez** [comment]
Same issue.

Composer version 1.0-dev (79ac2cac82cfdc5460fa378b758d9322d5422893) 2016-02-04 12:40:23

I even tried:

- rm vendor
- cache-clear
- selfupdate, reinstall and a previous version

I run the same update with -vvv to debug and it worked! wtf!

**Comment by sp-juan-hernandez** [comment]
I copy the commit hash and paste it on the lock as a workaround. It works as further updates also don't change de commit.

**Comment by k1sul1** [comment]
Bringing this issue up, because this  truly rustles my jimmies. I accept that Composer will never work like you'd hope it work; e.g. dev-master always results in checking the actual master and then checking out the latest commit.

But when you have a package at packagist.org, which is autoupdated when a commit is pushed into the package repository, and you can see the commit hash change, it's infuriating to see Composer report with "Nothing to install or update" when running `composer update`. 

This is a massive UX problem, and causes hate against Composer because it's unintuitive when you compare it to other package managers such as npm. 5 out of 5 people that I've introduced to Composer hate it because of reasons like this. I'm not kidding. It's pretty hard to get them to adopt it after they hate it. 

The problem could be easily mitigated by extending the response of `composer update`. Simply tell users what to actually  do (add commit hash to the constraint) if they're using `dev-*`, instead of making them search for an answer. I've used Composer for quite a while and I still stumble upon this issue every now and then. 

The other issue that I'd like to mention; Getting a minimum stability error when trying to install a package is infuriating, as it doesn't even tell you what to do. Instead you're meant to read the docs and google the error message with correct keywords to get a solution. You can rinse and repeat this for just about any error :')

**Comment by AaronHolbrook** [comment]
I have to say that although I don't have the strong negative emotions that @k1sul1 is referencing, I do indeed find it surprising and annoying that there's no way to have it 'actually' perform a check against what is out there without doing a full cache clear (which is a workaround and not a resolution).

**Comment by robertoandrade** [comment]
I've bumped into this a couple of times and was scratching my head as to why it worked on some of my repos and not others. I've noticed that in the repos where it works "as expected", I have the following configuration on my `composer.json`:

```
"config": {
        "preferred-install": "dist"
},
```

I suppose when that's the case the behavior for composer to pull the sources is slightly different (ie: it doesn't `git clone` the repo, since it seems to default to `source` as the `preferred-install` config).

**Comment by Seldaek** [comment]
@k1sul1 @robertoandrade if you can describe a bit more what you mean, or possibly give a way to reproduce this, I'd be curious. As far as I know updates to a dev-master version work perfectly fine. Is the problem when you did a git checkout of some other branch inside the vendor dir? Or doing a simple update is not updating?

**Comment by k1sul1** [comment]
If I have dev-master spesified as the version on a subpackage I'm working on, I expect `composer update` to always fetch the latest commit. That has not been the case. IIRC I had to remove the entire lockfile and the vendor directory to get the latest update.

Ofc, I could've used `composer remove vendor/package && composer require vendor/package:dev-master`, but that literally took multiple times more than simply nuking them out of the orbit.

**Comment by Seldaek** [comment]
@k1sul1 ok, that sounds very odd.. How is your "subpackage" loaded, is it on packagist? path repo? vcs repo? If you can make a repro case of this somehow I'd be curious to see, because as far as I can tell it works.

**Comment by k1sul1** [comment]
It was on packagist, yeah. I tried using VCS once, stopped using it immediately because it was too slow on updates. I wanted symlink-like behaviour instead of waiting minutes. 

When you say "as far as I can tell it works", do you mean it works with 2.0, or should it work with 1.x too?

Only PHP development I do these days is WordPress, and before the set of plugins required to use WordPress with Composer is updated, I can't test & verify it myself. 

Here's one of my packages: https://github.com/libreform/libreform

If you were to require it with `composer require libreform/libreform:dev-master`, `composer update` wouldn't update the package after I push an untagged commit. Only way I was able to get precise commits, was to use the commit hash directly. If that's not a problem anymore, great!

**Comment by Seldaek** [comment]
Ok yeah I have a hard time believing this sorry :D I am 100% sure that works for me, already in v1. It might take a minute or two for the metadata update to happen (that is a bit faster for composer 2), but otherwise it should absolutely work.

**Comment by sypets** [comment]
@rdohms can you check if still reproducible?

It looks like Composer will now update package correctly if required as dev-master (via Packagist).
With composer version 2.1.9 and a package required as "dev-master" I get:

* `composer outdated` shows me the new commit hash if there is a newer one
* `composer update` vendor/package updates the package

e.g. 

----

1. in composer.json:

`"vendor/mypackage": "dev-master",`

----

2. `composer outdated`:
Result:
```
vendor/mypackage                      dev-master 350a877 ! dev-master e00b00d ...
```
(shows newer commit hash)

----

3. `composer update vendor/mypackage`:
Result:
```
 - Upgrading vendor/mypackage (dev-master 350a877 => dev-master e00b00d)
...
```

-----

4. `composer.lock`:
diff 
```
-                "reference": "350a877949d81008a09c08aa928235451bce48c6"
+                "reference": "e00b00db5f08b70ee56a8316860300bcb7b6e70f"
etc ..
```

**Comment by reinholdfuereder** [comment]
@sypets I just stumbled over (something like) this as well: trying to update a custom dev-master package dependency:
* with composer v1 (1.10.6) it sees outdated dev-master package, but does not update it
* with composer v2 (2.1-dev) it not only sees outdated, but also updates it (as expected) 👍

**Comment by crabique** [comment]
Not sure if this is still relevant, but I am able to reproduce this issue right now using latest Composer version.

It sees `84093d0` as the latest commit for some reason, while it should be `009de30` as it's the `HEAD`. It works if I pass the commit hash explicitly but this is not ideal. 

Also if I run it without the hash afterwards it actually downgrades it back to `84093d0` 🙂 

```
~/.wp-cli/packages # composer --version
Composer version 2.3.10 2022-07-13 15:48:23

~/.wp-cli/packages # composer require runcommand/precache:dev-master
./composer.json has been updated
Running composer update runcommand/precache
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking runcommand/precache (dev-master 84093d0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing runcommand/precache (dev-master 84093d0): Extracting archive
Generating autoload files

~/.wp-cli/packages # composer require runcommand/precache:dev-master#009de30
./composer.json has been updated
Running composer update runcommand/precache
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
  - Upgrading runcommand/precache (dev-master 84093d0 => dev-master 009de30)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Downloading runcommand/precache (dev-master 009de30)
  - Upgrading runcommand/precache (dev-master 84093d0 => dev-master 009de30): Extracting archive
Generating autoload files
```

**Comment by wouter-toppy** [comment]
> Not sure if this is still relevant, but I am able to reproduce this issue right now using latest Composer version.
> 
> It sees `84093d0` as the latest commit for some reason, while it should be `009de30` as it's the `HEAD`. It works if I pass the commit hash explicitly but this is not ideal.
> 
> Also if I run it without the hash afterwards it actually downgrades it back to `84093d0` slightly_smiling_face
> 
> ```
> ~/.wp-cli/packages # composer --version
> Composer version 2.3.10 2022-07-13 15:48:23
> 
> ~/.wp-cli/packages # composer require runcommand/precache:dev-master
> ./composer.json has been updated
> Running composer update runcommand/precache
> Loading composer repositories with package information
> Updating dependencies
> Lock file operations: 1 install, 0 updates, 0 removals
>   - Locking runcommand/precache (dev-master 84093d0)
> Writing lock file
> Installing dependencies from lock file (including require-dev)
> Package operations: 1 install, 0 updates, 0 removals
>   - Installing runcommand/precache (dev-master 84093d0): Extracting archive
> Generating autoload files
> 
> ~/.wp-cli/packages # composer require runcommand/precache:dev-master#009de30
> ./composer.json has been updated
> Running composer update runcommand/precache
> Loading composer repositories with package information
> Updating dependencies
> Lock file operations: 0 installs, 1 update, 0 removals
>   - Upgrading runcommand/precache (dev-master 84093d0 => dev-master 009de30)
> Writing lock file
> Installing dependencies from lock file (including require-dev)
> Package operations: 0 installs, 1 update, 0 removals
>   - Downloading runcommand/precache (dev-master 009de30)
>   - Upgrading runcommand/precache (dev-master 84093d0 => dev-master 009de30): Extracting archive
> Generating autoload files
> ```

I had the same while trying to get the [latest commit of PrintNote](https://github.com/PrintNode/PrintNode-PHP/commit/a7616cf62737873cc7c41d8652a537c4b055329b)

Same Composer version, cleared cache and all that stuff. but didnt work. 

passing the commit hash worked

**Comment by xtfer** [comment]
Same issue. `composer update` doesnt work, but adding a commit hash does.

**Comment by Seldaek** [comment]
@xtfer if you don't provide details (package name, reference you get and reference expected at least) this is really not something we can look at..

**Comment by xabbuh** [comment]
@jrrdnx Please share your `composer.json` and `composer.lock` files.

**Comment by Seldaek** [comment]
3.3.3 changed two dependencies to new major versions.. So I think probably you just need to run `composer update born05/craft-twofactorauthentication --with-dependencies`. If that doesn't work then check `composer why-not born05/craft-twofactorauthentication 3.3.3`

**Comment by jrrdnx** [comment]
Thanks @Seldaek, it is due to those major version changes. `--with-dependencies` did not work, but `why-not` confirmed it.
