### ISSUE TITLE
Require Live

### ISSUE THREAD

**Issue by Firesphere** [composer/composer#5649]
It would be nice to include a --require-live and --not-require-live method. To include certain packages only on the live environment.

A usecase for this is a caching module. On dev-environment, you don't want it usually, but on live, you do.

**Comment by hkdobrev** [comment]
@Firesphere That's why Composer offers `require` and `require-dev`.

From the [Composer documentation on `require-dev`](https://getcomposer.org/doc/04-schema.md#require-dev):

> `require-dev` (root-only)#
> 
> Lists packages required for developing this package, or running tests, etc. The dev requirements of the root package are installed by default. Both `install` or `update` support the `--no-dev` option that prevents dev dependencies from being installed.

So locally you would do `composer install` which installed dev dependencies as well.
On production (live) environments you would do `composer install --no-dev` which would not install the dependencies needed only for development or testing the project.

**Comment by Firesphere** [comment]
I am looking for the exact opposite of `require-dev`. Namely, modules _only_ installed on a live environment, but not on a dev environment.
Which is different from `require-dev`. I am aware of the `require-dev` option :)

**Comment by alcohol** [comment]
That doesn't make any sense from a development cycle perspective. Anything deployed on production should always have been tested on development. `require-dev` enables you to add additional tooling/helpers that you would not need on production. The reverse however simply does not make sense.

Regarding your caching use-case; your application would simply depend on an interface, and this interface could have several implementations. E.g. if you use `doctrine/cache`, on testing you could use the file or array cache implementation, while on production you would use memcache or redis. You would still need to actually test it with the redis or memcache implementation before actually deploying it though.
