### ISSUE TITLE
post-update-cmd called instead of post-install-cmd on `composer install`

### ISSUE THREAD

**Issue by tropotek** [composer/composer#5746]
I have noticed that when I run the `composer install` command for a freshly cloned project the `post-update-cmd` is called instead of the `post-install-cmd`. Last tested on version 1.2.1

After this I can call `composer install` and it behaves as expected.

**Comment by alcohol** [comment]
Can you be more specific about the project? Does the project come with a composer.lock? Cause if it does not, then the `composer install` is technically a `composer update` (since it has to resolve the dependencies first, which is done by update only, never install). This could explain why it calls the post-update-cmd. This is intentional behaviour.

**Comment by tropotek** [comment]
Thanks for the reply, no .lock file. intentional but unpredictable behavior...

Cheers.
