### ISSUE TITLE
The "no-plugins" option does not exist.

### ISSUE THREAD

**Issue by yjqg6666** [composer/composer#5773]
[Symfony\Component\Console\Exception\InvalidArgumentException]
  The "no-plugins" option does not exist.

Exception trace:
phar:///private/tmp/cli.phar/vendor/symfony/console/Input/Input.php:157
 Symfony\Component\Console\Input\Input->getOption() at phar:///private/tmp/cli.phar/vendor/composer/composer/src/Composer/Command/InstallCommand.php:84
 Composer\Command\InstallCommand->execute() at phar:///private/tmp/cli.phar/vendor/symfony/console/Command/Command.php:259

See: https://github.com/composer/composer/blob/master/src/Composer/Command/InstallCommand.php#L131, no InputOption in the command definition and just got 'no-custom-installers', 'DEPRECATED: Use no-plugins instead.'.

The other commands like CreateProjectCommand have the same issue.

**Comment by yjqg6666** [comment]
Adding an InputOption to the commands can fix the issue. I don't know the best comment for the InputOption so i did not submit PR for this one.

**Comment by JasonChilds** [comment]
It's OK man. I didn't expect to sell it. I do need help selling some of my
cousin's autographed photos and memorabilia tho
I'm very new here and don't know if they would sell for much but I'll send
you pics. I know one is worth alot

On Oct 9, 2016 1:38 AM, "yjqg6666" <notifications@github.com> wrote:

Adding an InputOption to the commands can fix the issue. I don't know the
best comment for the InputOption so i did not submit PR for this one.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/composer/composer/issues/5773#issuecomment-252468248>,
or mute the thread

**Comment by alcohol** [comment]
https://github.com/composer/composer/blob/master/src/Composer/Console/Application.php#L412

**Comment by yjqg6666** [comment]
Thanks.
