### ISSUE TITLE
Ability to suppress progress output via environment variable

### ISSUE THREAD

**Issue by AndreKR** [composer/composer#5796]
It seems that currently there is only a command line option (`--no-progress`) but no environment variable available to suppress composers progress output.

I tried using `COMPOSER_NO_INTERACTION` thinking it might also suppress progress output (because it's also kind of a user interaction) but it doesn't.

Environment variables are much easier to work with in CI environments, so it would be nice to be able to control this via environment variable.

**Comment by stof** [comment]
the progress output does not require any user interaction (as it does not ask for any input). This is why it is not controlled by the ``COMPOSER_NO_INTERACTION`` env var

**Comment by AndreKR** [comment]
Yeah, I guessed so, "staring at it" is barely interaction. :)

**Comment by alcohol** [comment]
Some of Composer's core configuration values can be [passed through environment variables](https://github.com/composer/composer/blob/master/src/Composer/Config.php#L212). However, since `--no-progress` is a command flag/option that only applies to a range of commands (not all), it is not one of Composer's core configuration values, and hence not configurable through environment variables.

**Comment by Nardberjean** [comment]
I try to put
alias composer="composer --no-progress"
in CI environment but it just produce an error on composer command not supporting it.
In 6 month I will have forgotten and I will try again. At some point I found a much more complicated (working) solution but I forgot it. It was a kind of shell function detecting the command given to composer.
In my point of view an environment variable would be simple, you set it once and it works (hopefully) forever.

**Comment by Seldaek** [comment]
Closing as nobody cared to do it in 4 years it doesn't seem that important.
