### ISSUE TITLE
Installation not work with php7

### ISSUE THREAD

**Issue by satanand7** [composer/composer#5799]
when i install composer with exe it shows this message.
C:\xampp\php\php.exe

The php.ini used by your command-line PHP is: C:\xampp\php\php.ini

A setting in your php.ini could be causing the problem: Either the 'extension_dir' value is incorrect or the dll does not exist.

Program Output:
Warning: PHP Startup: Unable to load dynamic library 'C:\xampp\php\ext\php_mysql.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Invalid library (maybe not a PHP library) 'libmysql.dll' in Unknown on line 0

When i try to download with command this same as before.

C:\xampp\php>php -r "copy('https://getcomposer.org/installer', 'composer-setup.p
hp');"
PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\xampp\php\ext\php_
mysql.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'C:\xampp\php\ext\php_mysql
.dll' - The specified module could not be found.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\xampp\php\ext\libm
ysql.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'C:\xampp\php\ext\libmysql.
dll' - The specified module could not be found.
 in Unknown on line 0

**Comment by alcohol** [comment]
The error explains itself. Solve your PHP error first, and then we can help you if you have any problems actually related to Composer.

**Comment by rquadling** [comment]
PHP7 doesn't have the mysql extension. Try the mysqli extension instead. Or PDO. Or anything really. Just not mysql.

http://www.php.net/manual/en/intro.mysql.php

> This extension is deprecated as of PHP 5.5.0, and has been removed as of PHP 7.0.0.

**Comment by Jany-M** [comment]
@satanand7 Make sure that in your `php.ini`, there's always the HDD letter before the xampp folder, in every relative path.

eg. `browscap = **"D:**\Dropbox\__WORK_IN_PROGRESS__\__xampp__\php\extras\browscap.ini"`

**Comment by kononov-a** [comment]
The configuration of extension_dir may be maybe wrong in your php.ini, which is affecting loading extensions.

If the extensions are actually inside the c:/wamp64/bin/php/php7.0.10/ext folder, then the path in php.ini must be

extension_dir="ext"
Or:

extension_dir="c:/wamp64/bin/php/php7.0.10/ext"
If it still fails, it's because somehow php_intl.dll does not exist inside the folder or has been moved to c:/wamp64/bin/php/php7.0.10/ or is using an incorrect version of .dll (I even had some problems with PHP7 extensions on Windows)

If your dlls are outside the ext folder you can then set the extension_dir to:

extension_dir="."
Or:

extension_dir="c:/wamp64/bin/php/php7.0.10"
Or move all files with php_ prefix to the ext folder
