### ISSUE TITLE
Make creation of .htaccess files optional

### ISSUE THREAD

**Issue by yaronius** [composer/composer#5816]
Currently Composer uses the following code (src/Composer/Factory.php):
```
        foreach ($dirs as $dir) {
            if (!file_exists($dir . '/.htaccess')) {
                if (!is_dir($dir)) {
                    Silencer::call('mkdir', $dir, 0777, true);
                }
                Silencer::call('file_put_contents', $dir . '/.htaccess', 'Deny from all');
            }
        }
```
Major part of its logic is based on the assumption that the web server is Apache. But this is not always true. And there is actually no flag to disable this behaviour. So far it is just a minor nuisance, but it would be nice to control this behaviour.

**Comment by alcohol** [comment]
Personally I am completely in favor of removing this snippet of code. It is not something composer should concern itself with. Unfortunately, it probably has saved some users from awkward situations.. so.. :-/

**Comment by JamesRezo** [comment]
It can be said also that the web server is assumed to be Apache 2.2 or Apache 2.4 with  mod_access_compat module loaded, (and mod_php ...)
A such config Apache 2.4 without  mod_access_compat module loaded would serve a 500 error status code if accessed instead of a 403 errror.
Apache 2.4 equivalent is `Require all denied`
And, by the way, the file name depends on the AccessFileName directive that defaults to `.htaccess` but may be set to another value :)
I don't know if a `.user.ini` file for CGI/FastCGI, then PHP-FPM, mode can reproduce that kind of behaviour.

As @alcohol says : nothing that composer can guess, actually.

**Comment by yaronius** [comment]
@alcohol @JamesRezo ok then, maybe this behaviour should be somehow configured via composer.json ? or do you mean that this should not be improved?

**Comment by alcohol** [comment]
@Seldaek are you ok with removing this snippet of code?

**Comment by Seldaek** [comment]
IMO either we decide it's not worth it and we drop it, or we agree that it doesn't matter a lot to have a hidden file created in the config dir, and everyone lives with it as it is.

The problem is it isn't really possible to measure the impact of this. Maybe it is protecting someone's cache and config on a production server right now, maybe not.

**Comment by JamesRezo** [comment]
It's better to remain with it until a dedicated tool appear to manage that kind of issue. `.htaccess` is partial but harmless.

**Comment by yaronius** [comment]
Ok, guys, thank you for your response!

**Comment by Seldaek** [comment]
OK closing for now then

**Comment by simonwahlstrom** [comment]
We are in the process of updating Ubuntu, Apache and PHP on our servers and this part is causing problems for us.

We are now running Ubuntu 14.04.05 with Apache/2.4.7. This version of apache will throw an error "/path/php/.htaccess: Invalid command 'Deny', perhaps misspelled or defined by a module not included in the server configuration, referer: http://example.com/" which will break the site.

It would be great if this could be optional or if we could have the choice to use the new version "Require all denied". The only viable option we have right now is to create the .htaccess file on all environments ourselves to prevent the code from executing.

**Comment by stof** [comment]
@simonwahlstrom or just keep your composer home and cache directories outside the Apache web root, so that it never looks at these files (which is the sensible way anyway, as the generated htaccess is here to prevent security issues in case you make the composer cache accessible from the web, which should not be the case)
