### ISSUE TITLE
Running WP-CLI Commands From Composer

### ISSUE THREAD

**Issue by JakeHenshall** [composer/composer#5834]
Hi,

Is there any way that I can do this.

I'm trying to run either any WP-CLI command from within the "post-install-cmd" inside composer and/or create a script.sh with the commands in and run them aswell, to allow the user to have a clean fresh version of WordPress installed.

Thanks Jake.

**Comment by alcohol** [comment]
"post-install-cmd" of what? Your project? Or your library?

In the first case, since you already figured out what "post-install-cmd" does, what is the problem / question exactly?

In the second case, since "scripts" is a **root-only** attribute, defining this for your library does absolutely nothing.

**Comment by Seldaek** [comment]
Closing issue as it has been quiet for a long time and there is no clear next step we can take.
