### ISSUE TITLE
How to simulate composer events

### ISSUE THREAD

**Issue by grasmash** [composer/composer#5867]
I'm currently developing a Composer plugin that responds to Composer events. When the Composer plugin is itself updated, I need to determine the prior version of the package and the new version of the package and then execute a method.

I have this mostly working, but I'm having trouble debugging because I cannot simulate an install or update without removing the package or releasing a new version. 

Is there a way to simulate a package update to the plugin in such way that I can use Xdebug to trace the execution?

**Comment by grasmash** [comment]
Maybe I should just ask, how can I determine the prior version of a given package during an update event?

**Comment by alcohol** [comment]
@Seldaek probably knows most about the plugin system.

**Comment by slbmeh** [comment]
I don't know of a good way to get the previous version of a package from an update, but I can explain what's happening in your class state.

Your `onPrePackageEvent` is running in the original class registered within the plugin manager. The `onPostCmdEvent` is running in a new class that has been mangled and eval'd under a class with a suffix like `_composer_tmp1` and registered with the plugin manager during the update.

Still somewhat ugly, but perhaps a bit cleaner than writing to disk is to make your prior version publicly and statically accessible.  Then you can do something like `MyClassName::getPriorVersion()`.  The qualified class name is essential to ensure it resolves to the previously loaded class rather than the updated class.

**Comment by Seldaek** [comment]
The best way IMO is to listen to the post-dependencies-solving event in https://getcomposer.org/doc/articles/scripts.md#installer-events or post-package-update + post-package-install if you want to react after the package has been updated.

In there, you should be able to get a list of operations from the event, and from there you can see the old/new versions in the UpdateOperation instance.

As for debugging, you can easily trigger updates by changing the require of a package between 1.0.1 and 1.0.2 for example and doing a composer update. No need for new tags.
