### ISSUE TITLE
Memory consumption

### ISSUE THREAD

**Issue by gui-don** [composer/composer#5879]
Hi guys!

Since composer version 1.2.2, I hit the memory limit quite often (not to say always 😃).
It happens on several projects of different sizes, on different systems so I think it’s composer-related.

I use PHP7 (7.0.13 now) or PHP 5.6 and xdebug is always disabled. `composer diagnose` is all green.

Research here and there shows me that it is a common problem, and the documentation states that I should increase the memory limit.

Increasing the amount of RAM for PHP up to 1GB or 2GB seems to work but this is a tremendous amount of RAM for a CLI dependency management software! Also it can be problematic on production environment as it forces other application (dbms…) to free RAM, even if I do it for a very short time. Moreover it makes devops/sysadmin work (and they don’t like it very much 😆).

Am I doing something wrong? If not, are you working to fix the issue?

Thank you! Keep up the good work.

**Comment by staabm** [comment]
Which particular command with which composer.json requires too much memory.

Most of the time you only need `composer install` in production which should not consume that much memory.

**Comment by alcohol** [comment]
It is known that `composer update` takes a lot of memory. On production environments, you really should be running `composer install` instead (and make sure your project includes a `composer.lock`). When installing from a composer.lock file, the process takes significant less memory because it does not have to resolve the dependency graph first, unlike update.
