### ISSUE TITLE
problem with chocolatey intallation

### ISSUE THREAD

**Issue by williamyeh** [composer/composer#5881]
I'm new to a lot of these things, composer, php, vagrant, homstead, laravel.
But I found this problem.
So I was trying to install php and then composer.
I am using windows 10, I used chocolatey package manager to install php.
Then I think I used chocolatey to install composer.
What happened is using chocolatey to install composer, it tried to find php on the root directory on C drive. 
However, chocolatey installed php on C:\tools\php.
Maybe there should be a fix in some corresponded scripts?

**Comment by alcohol** [comment]
We are not affiliated with chocolatey, nor do we support installing composer through third parties. You can find supported installation instructions for composer on https://getcomposer.org, including a windows installer at https://getcomposer.org/doc/00-intro.md#installation-windows

**Comment by johnstevenson** [comment]
chocolatey actually downloads and uses Composer-Setup.exe. But since it runs this with the `/VERYSILENT` option, the user never gets the chance to select where php.exe resides.

I'll add C:\tools\php in a future release, so it will work if php is installed in the default location.

**Comment by alcohol** [comment]
@johnstevenson shouldn't chocolatey simply add the tools directory to the path?

**Comment by stof** [comment]
@alcohol on windows, it is common for installer not to update the path. This is why Composer-Setup checks common locations to do it for you.
I'm totally fine with adding the chocolatey default path to the list of supported locations

**Comment by williamyeh** [comment]
chocolatey did add the tools\php directory to the path.
After installing php7 with chocolatey, i think i tried both Composer-Setup.exe and choco install composer.
Now I think maybe what I encountered with Compose-Setup.exe is that it can find the php directory alright.
But when it looks for openssl extension, it looked for c:/php instead of c:/tools/php.

Either the Composer-setup.exe or the choco install composer gave me this problem.
Solved it by downloading php7 and put it at c:/.

**Comment by johnstevenson** [comment]
It is chocolatey that is the problem (yes it does add `C:\tools\php` to the path - sorry, I am an idiot) but it needs some user action if the openssl extension is not loaded. Because it is being run with the `/VERYSILENT` option, the user is never asked to resolve the issue and the installation fails.

**Comment by ferventcoder** [comment]
Howdy folks - 
For working with native installers like INNOSETUP, think of Chocolatey as a framework that works on the idea of unattended deployments with PowerShell (it's a lot more than that because it is a full package manager, but that will give you a frame of reference when it comes to installer packages). Because we know that distribution rights is a thing, the public community repository requires software-embedded packages to carry the permissions or license to have that software embedded in the package, otherwise download the software from an official distribution location.

Chocolatey likes completely unattended installations. Or rather I should say, when a user is installing a Chocolatey package, they want to be able to push out software to multiple locations and don't want to be bothered by GUIs. 

So for the items that you are looking for during installation you have options:
 
* self-discovery (somewhat similar to what you are already doing by finding php install)
* Have the user tell you what those options are with Package parameters (`--params`) - see https://chocolatey.org/docs/how-to-parse-package-parameters-argument. A note about params, typically good defaults are set and then users can select to do that.
   * In your case, you may wish to fail the install if a package parameter isn't included.
 * As a last resort, Chocolatey does support some interactivity at runtime, as long as the package sets good defaults, you can explore that as it will still result in unattended installation. 
* A couple of simpler options are to simply fail the install if it runs into issues and leave it up to the user to investigate. Or allow the install to succeed and leave it up to the user to resolve those issues after the silent installation is complete as part of a first time run kind of thing.

Of those options, the easiest to implement is simply failing and letting the user determine what went wrong. You can even have it log and pull the log errors and present them to the user.

@williamyeh you can also change your ToolsLocation to c:\ and use that instead of C:\tools (the default). Then php will install to the root of C drive and perhaps some of this will fix itself.

**Comment by ferventcoder** [comment]
John and I had some discussion at https://gitter.im/chocolatey/chocolatey.org?at=58334b9116ee9e64046b3ce4

**Comment by johnstevenson** [comment]
Okay, we've now got a Composer-Setup chocolately package: https://chocolatey.org/packages/composer-setup

I have no idea why it's got a big red warning on it. May be it is still going through the automatic submission process? This is not particularly intuitive, so it is hard to tell.

**Comment by ferventcoder** [comment]
It looks like it was exempted. There are three final statuses - rejected, approved and exempted. https://chocolatey.org/docs/moderation

**Comment by johnstevenson** [comment]
@alcohol This issue can be closed now, since the composer chocolatey package has been in place for a while now: https://chocolatey.org/packages/composer

Sadly it doesn't have a nice green _this-is-ok_ symbol, due to a limitation of the chocolatey automatic verification process:

(Because our package relies on php being installed, this requires their testing server to update to a version of Windows that can support the latest VC redistributables, so it can install php. However, this process requires a reboot, which the testing process cannot handle, so our package _fails_ before it can be run). Hey ho...

**Comment by Seldaek** [comment]
Automatically closing as this has not received any updates in a while. Please re-open if it is still relevant.
