### ISSUE TITLE
.lock file in the wrong place

### ISSUE THREAD

**Issue by dcwmorley** [composer/composer#5926]
In studying how to use Composer, starting from Windows 10 with wampstack-5.6.28-1, I downloaded package checkdomain/holiday and checked it out in the local server. Then I moved it to a website that I own. Everything working. So far, so good.

The actual files moved to the servers were an index.php to call up the downloaded workings of the package, and a copy of \..\wampstack\php\vendor.

However when I look at all the files I find that the .lock file has not been passed to the servers because it is not in the folder \vendor that Composer created during the download from Packagist. The .lock file is in \..\wampstack\php

 Additionally, although the \vendor folder has the .json file there is another .json file in \..\wampstack\php.

I am a bit confused about this - surely the .lock file is a vital component that needs to be in the server ?

**Comment by stof** [comment]
This is totally expected for it to be outside the vendor folder.
The common setup is to ignore the vendor folder from the VCS repo, but to commit the composer.lock file (which contains all metadata necessary to download the same version of all dependencies again). Putting the lock file inside the vendor folder would make everything harder:
- harder to write ignore rules for the VCS (as you would have to exclude all the vendor folder *except one file*)
- harder to wipe out the vendor folder to reinstall it in a clean way in case you messed with it (due to corrupting the install, or just due to hacking the source code of a dependency to experiment and wanting to go back to a clean state)

Btw, the server itself should not need the composer.lock file itself if you never run a composer command on it.

**Comment by dcwmorley** [comment]
Ok Thank you for that      David Morley
 

    On Thursday, December 1, 2016 3:26 PM, Christophe Coevoet <notifications@github.com> wrote:
 

 This is totally expected for it to be outside the vendor folder.
The common setup is to ignore the vendor folder from the VCS repo, but to commit the composer.lock file (which contains all metadata necessary to download the same version of all dependencies again). Putting the lock file inside the vendor folder would make everything harder:   
   - harder to write ignore rules for the VCS (as you would have to exclude all the vendor folder except one file)
   - harder to wipe out the vendor folder to reinstall it in a clean way in case you messed with it (due to corrupting the install, or just due to hacking the source code of a dependency to experiment and wanting to go back to a clean state)
Btw, the server itself should not need the composer.lock file itself if you never run a composer command on it.—

**Comment by alcohol** [comment]
Can this be closed or do you have further questions?

**Comment by dcwmorley** [comment]
Please close this now. Thank you.
 

    On Friday, December 2, 2016 8:13 AM, Rob <notifications@github.com> wrote:
 

 Can this be closed or do you have further questions?—
