### ISSUE TITLE
Composer update runs out of memory, surprisingly

### ISSUE THREAD

**Issue by toby5box** [composer/composer#5934]
My `composer.json`:

```json
{
    "name": "symfony/framework-standard-edition",
    "license": "MIT",
    "type": "project",
    "description": "The \"Symfony Standard Edition\" distribution",
    "autoload": {
        "psr-0": { "WFV": "src/" }
    },
    "require": {
        "php": ">=5.3.3",
        "symfony/symfony": "~2.4",
        "doctrine/orm": "~2.2,>=2.2.3",
        "doctrine/doctrine-bundle": "~1.2",
        "twig/extensions": "~1.0",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~2.3",
        "sensio/framework-extra-bundle": "~3.0",
        "sensio/generator-bundle": "~2.3",
        "incenteev/composer-parameter-handler": "~2.0",
        "jms/security-extra-bundle": "dev-master",
        "leaseweb/memcache-bundle": "~1.2"
    },
    "scripts": {
        "post-install-cmd": [
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
        ],
        "post-update-cmd": [
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
        ]
    },
    "config": {
        "bin-dir": "bin"
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-web-dir": "web",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        },
        "branch-alias": {
            "dev-master": "2.4-dev"
        }
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
require.jms/security-extra-bundle : unbound version constraints (dev-master) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:

```
composer update
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)

Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 64 bytes) in phar:///usr/local/Cellar/composer/1.0.0-alpha9/libexec/composer.phar/src/Composer/DependencyResolver/Rule.php on line 60

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors
```

And I expected this to happen:

Packages to be updated.

**Comment by alcohol** [comment]
Allow more memory.

**Comment by toby5box** [comment]
Why does it need more than 1GB for this operation? Is that an unusually complicated `composer.json`?

**Comment by sbuzonas** [comment]
Generally the looser the constraints, the more memory it takes to evaluate the potential candidates in between.

**Comment by toby5box** [comment]
@sbuzonas Thanks, that's helpful. I might have to change a few of these to equalities, then, presumably.

My remaining concerns would be these:
* If this is a typical `composer.json` then the default 1GB memory definition is no longer appropriate (obviously a lot of users would experience problems on modest configurations);
* Related: Composer by its very nature is going to be expected to run, from time to time, on quite small VPSs, specifically 1GB or less.

**Comment by sbuzonas** [comment]
It is fairly typical, but generally update is run and the lock is generated.  The memory isn't needed for install, the solver has to analyze a lot of packages for an update.  Adding a package usually picks the latest version, over time as new versions are released, the new packages are potential candidates.  In 2013 when symfony/symfony 2.4 was a single package it would use a lot less memory than now when there is 60+ versions that satisfy that requirement.

**Comment by toby5box** [comment]
@sbuzonas Thanks again for the info. Indeed I can't get a lock file. But I'll try and tighten up the constraints.

**Comment by alcohol** [comment]
> Composer by its very nature is going to be expected to run, from time to time, on quite small VPSs, specifically 1GB or less.

@toby5box yes, but usually on those machines you will not be running `update`, but only `install`. And as @sbuzonas pointed out, running `update` is the action that requires a lot of memory (because it has to resolve the dependency graph). Running `install` however reads the previously resolved set of packages straight from the lock file, skipping the whole dependency graph resolving process. It therefor requires significantly less memory.

We recommend you run update only on your development environments (or possible build / CI). Releases should generally either be a straight install, or preferably even not involve composer at all (have your build / CI machines generate a release of your application in archive form and ship that).

**Comment by toby5box** [comment]
@alcohol That's a good point. However I should be wary of allowing that, in general, to justify runaway memory use in `update`.

Thanks everyone for the help.

**Comment by sbuzonas** [comment]
It may be helpful to indicate it.  I'm concerned it may be read as, loose constraints are a bad practice.  My personal preference is that libraries should have loose constraints to have a greater value to the community, where applications should have tight constraints to limit the amount of compatibility testing.

I think a better approach may be an entry to the FAQ pointing out `install` vs `update` best practices.  And highlight the memory intensive nature of update may need more memory for loose constraints, and is not necessarily a bad thing.  Then link to it from the memory limit troubleshooting section.

I don't feel it belongs directly in troubleshooting because it isn't necessarily a bad thing... It's just going to consume more resources in certain known circumstances.

**Comment by toby5box** [comment]
The way I see it, you are caught in a contradiction. Loose constraints _are_ apparently likely to cause runtime issues… as long as the default memory limit is 1GB. Another question is whether the search is as frugal with resources as it could be.

FWIW This (apparently simple) set of dependencies eventually used about 1.54 GB to process.

**Comment by toby5box** [comment]
However as a tip to others who stumble on this thread, there seems to be a very simple way to reduce the search space and memory consumed; just change the versions to the latest version matched by the rules—and an easy way to find those versions is to use https://semver.mwl.be

E.g. the first change I made was,

-        "symfony/symfony": "~2.4",
+        "symfony/symfony": "~2.8",

After making this change, the resolution of versions is much less work.

This implies that as projects "age" with un-updated dependencies, the greater they will cost to `update`, until eventually they'll die at 1GB.

I'm sure this is obvious to the experts in the room already but I'm leaving this here for people like me who didn't know all that. :)

**Comment by alcohol** [comment]
> The way I see it, you are caught in a contradiction. Loose constraints are apparently likely to cause runtime issues… as long as the default memory limit is 1GB. Another question is whether the search is as frugal with resources as it could be.

He was talking about applications vs. libraries. Generally, libraries are only used as dependencies, whereas applications require the use of a lot of libraries. Libraries want to specify their own requirements as wide as possible, so that plenty of users can make use of them.

Applications on the other hand, will want to narrow their requirements as much as possible. This will make it easier to resolve dependencies, and also makes it less likely that you will run into compatibility issues. Every time you run a `composer update` on your application, it is probably a good idea to also update your constraints (e.g. go from `^2.4` to `^2.6`). There is no reason to keep your application supporting older libraries (assuming you wont be running lots of outdated versions of your own application).

As for the memory use, it could perhaps be improved. If you can recommend us a good PHP developer who has extensive knowledge about [SAT solving](https://en.wikipedia.org/wiki/Boolean_satisfiability_problem) and can help us improve our implementation, please let us know :-)

**Comment by toby5box** [comment]
Logic programming and solving is an interest area of mine, although I wouldn't call myself an expert. Maybe I'll take a look.

**Comment by sbuzonas** [comment]
@toby5box You can show the versions of installed packages with `composer show`, and a very helpful flag for updating your application dependencies is to list the direct dependencies with `composer show -D`
