### ISSUE TITLE
Warn about identical names with different capitalization on zip archive extract failure (Not a directory)

### ISSUE THREAD

**Issue by naderman** [composer/composer#5938]
When unzip fails with "checkdir error: [path] exists but is not a directory" or if ZipArchive->extractTo fails with `ErrorException ZipArchive::extractTo(): Not a directory` we should display a message warning that the archive may contain a directory and a file with the same name but different capitalization which fails to extract on case insensitive filesystems.

**Comment by ajiyakin** [comment]
@naderman is there anyone work on this?
I'm going to work on this then :smiley:

**Comment by naderman** [comment]
@ajiyakin Please do! :-)

**Comment by ajiyakin** [comment]
Hi @naderman, I've been do a pull request for this issue. Please tell me if there's something that I might be miss understood or missing something :smiley:

**Comment by naderman** [comment]
This PR fixes the issue for ZipArchive, but the description actually also mentioned the same issue when using unzip. Can you make another PR for that too?

**Comment by ajiyakin** [comment]
OK, I'll take a look then :+1:

**Comment by ajiyakin** [comment]
Hi @naderman , sorry for my late pull request.
I already add warning for unzip for this issue. I also set warning message equals to the [master branch for ZipArchive](https://github.com/composer/composer/blob/master/src/Composer/Downloader/ZipDownloader.php#L160) one.

**Comment by nrayann** [comment]
I am getting the same error when I run `composer update` on my Laravel Project.

The process is killed at `symfony/console` updating/installing.

Bash output:

	- Installing symfony/console (v4.2.7): Loading from cache

	Failed to execute unzip -qq  '/mnt/c/Users/rayann.souza/Sites/execut-api/vendor/symfony/console/d5e2f7700964cd8960261b5750040990' -d '/mnt/c/Users/rayann.souza/Sites/execut-api/vendor/composer/76f787b7'

	Killed

	The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
	Unzip with unzip command failed, falling back to ZipArchive class

![image](https://user-images.githubusercontent.com/5538985/64639869-272dee00-d3df-11e9-86d6-0d9d4ae5a132.png)

### Steps To Reproduce:

- Ubuntu 18.04 with WSL on Windows 10 Pro
- intel core i7 7th Gen, 16gb RAM
- PHP 7.2.19
- Laravel 5.8

Anyone could help me?

Thank you in advance for any help :D

**Comment by kolumnin** [comment]
Dr.K.Muraleedharan

**Comment by mahdiarn** [comment]
> I am getting the same error when I run `composer update` on my Laravel Project.
> 
> The process is killed at `symfony/console` updating/installing.
> 
> Bash output:
> 
> ```
> - Installing symfony/console (v4.2.7): Loading from cache
> 
> Failed to execute unzip -qq  '/mnt/c/Users/rayann.souza/Sites/execut-api/vendor/symfony/console/d5e2f7700964cd8960261b5750040990' -d '/mnt/c/Users/rayann.souza/Sites/execut-api/vendor/composer/76f787b7'
> 
> Killed
> 
> The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
> Unzip with unzip command failed, falling back to ZipArchive class
> ```
> 
> ![image](https://user-images.githubusercontent.com/5538985/64639869-272dee00-d3df-11e9-86d6-0d9d4ae5a132.png)
> 
> ### Steps To Reproduce:
> * Ubuntu 18.04 with WSL on Windows 10 Pro
> * intel core i7 7th Gen, 16gb RAM
> * PHP 7.2.19
> * Laravel 5.8
> 
> Anyone could help me?
> 
> Thank you in advance for any help :D

Try installing zip and unzip in wsl

**Comment by nrayann** [comment]
@mahdiarn It is because your WSL is case insensitive, I tried to change it but the error keeps, so I quit WSL and moved to vagrant using Laravel Homestead.

**Comment by emancypage** [comment]
If you notice this problem again or you still have this problem try to clear composer cache first:

`composer clearcache`

**Comment by Ben-CA** [comment]
I'm getting this error in the logs on AWS Elastic Beanstalk on deployment when trying to include the AWS PHP SDK via composer. (Deployment fails) Works the first time, following times fail. 

Logs:
Found composer.json file. Attempting to install vendors.
  + composer.phar install --no-ansi --no-interaction
  Do not run Composer as root/super user! See https://getcomposer.org/root for details
  Loading composer repositories with package information
  Updating dependencies (including require-dev)
  Package operations: 8 installs, 0 updates, 0 removals
    - Installing symfony/polyfill-mbstring (v1.15.0): Loading from cache
      proc_open(): fork failed - Cannot allocate memory
      **The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)**
      Unzip with unzip command failed, falling back to ZipArchive class
  The following exception is caused by a lack of memory or swap, or not having swap configured
  Check https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors for details
  
  PHP Warning:  proc_open(): fork failed - Cannot allocate memory in phar:///opt/elasticbeanstalk/support/composer.phar/vendor/symfony/console/Application.php on line 952
  
  Warning: proc_open(): fork failed - Cannot allocate memory in phar:///opt/elasticbeanstalk/support/composer.phar/vendor/symfony/console/Application.php on line 952
                                                       
    [ErrorException]                                   
    proc_open(): fork failed - Cannot allocate memory  
                                                       
  install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...
   (Executor::NonZeroExitStatus)

**Comment by josselynsan** [comment]
Hi, i have the solution.

You only need delete in c:\program file\7-Zip,

after you need, reinstall this software. 7-zip

after execute

laravel new your_app

and ready.

**Comment by DaniilVelikolepniy** [comment]
Hi!
As far as I understand - in this case, the problem is related to the ratio of windows to the register. Those. if your OS is Windows, and you work through the Linux console, then the relationship to the register will be from Windows, since the console will work on the basis of Windows. I'm currently working on a Laravel project and I'm using docker to set up a virtual environment. When I encountered this problem, I realized that the raised environment should not be accessed through the Linux console running at the root of the project, but directly through the docker console, so to speak, from inside the raised system. It helped me, it might help you too. Good luck.

**Comment by Ash-raf10** [comment]
Well, I might be late...But thought it would be helpful to someone else who is using WSL in windows.

If you are using docker desktop and started the container from docker desktop the problem may occur. As you are starting it from docker desktop, it will start with other permission. 
For solving this you need to stop the container from docker desktop and start the container from ubuntu LTS.

**Comment by MelodyHacker** [comment]
watch ram&cpu used and try delete vendor&composer.lock

**Comment by MelodyHacker** [comment]
try composer install;composer update ; on host not grest  iam use docker is system slow to sync file
