### ISSUE TITLE
Different branches for dev-test-prod

### ISSUE THREAD

**Issue by RdeWilde** [composer/composer#5963]
I cannot find a way to require different packages for three different stages in a convinient way. I would like to see this feature in future - or if possible - learn how to use it.

I use one repository, with three different branches (dev, test, prod).

On dev I can override dependencies by adding the repositories to the require-dev section to, overriding it to `@dev-master` for example.
On prod I run --no-dev, so it will only use the main packages (`@prod`).
On test I would like to use the intermediate `@test`. But I'm not sure how (besides manually editing it every time).

Obviously we use branching over releases.

**Comment by RdeWilde** [comment]
How am I supposed to use it with staging envs?

**Comment by stof** [comment]
why should your staging environment run a different codebase than the prod ?

**Comment by alcohol** [comment]
I do not want to question your motivation for the path you have chosen to take in regards to your development flow. It simply is not a path composer is very compatible with, because it falls outside of the norm. We cannot accommodate everyone, because some flows simply are not compatible. So we go with the 99% :-)

**Comment by RdeWilde** [comment]
I am open for suggestion how to use composer in a professional env with different staging envs

**Comment by Seldaek** [comment]
You can script different environments using `composer require ...` to override some requirements in a given env, but I really don't think this is a good practice if you have a dev => staging => prod pipeline as you might end up changing the version of dependencies along the way. It can be fine to do this if it's about running say multiple staging envs with different branches of internal dependencies or something along those lines. But I don't think it's something we can support.. At best we can offer the `self.version` trick which you can use in your requires so that if you run a composer update on branch dev-foo it will require other packages in version dev-foo as well if you require them using `self.version`.

**Comment by the-wellness-way** [comment]
IT would be for phpunit and testing libraries. like i don't want my tests folders in the same branch as my prod code base. I want to do this before the build, because I want people to be able to download the prod zip from github.
