### ISSUE TITLE
Xdebug warning message links to non-existent documentation

### ISSUE THREAD

**Issue by TravisCarden** [composer/composer#5997]
When running composer with xdebug enabled, the following warning is emitted:

> You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug

But the URL redirects to a documentation resource that doesn't exist. The documentation apparently needs to be created or replaced, or the link needs to be updated or removed.

**Comment by staabm** [comment]
The docs have been removed with the lastest release as of 1.3 composer will take care of cdebug automatically

**Comment by johnstevenson** [comment]
I think the docs should probably stay (but rewritten) because the warning will be still be shown if:

1. The `COMPOSER_ALLOW_XDEBUG` environment has been set to override the default behavior
2. The default restart process has failed to prevent xdebug from being loaded

In the latter case it would be useful if this was reported as an issue, so we can work through various configurations that might cause it. Issue #5995 being an example.

I guess I better PR it!
