### ISSUE TITLE
Why composer clone my private gitlab instead only download it

### ISSUE THREAD

**Issue by emimarz** [composer/composer#6016]
My `composer.json`:
```
{
     "config":{
         "preferred-install": "dist",
         "secure-http": false
     },
     "minimum-stability": "dev",
     "repositories": [ {
         "type": "git",
         "url": "http://gitlab.local/GROUPNAME/REPOSITORY.git"
     }],
     "require": {
         "GROUPNAME/REPOSITORY": "0.1.0"
     }
}
```
When I run this command:
```
 composer install -o --prefer-dist
```
I get the following output:
```
  - Installing GROUPNAME/REPOSITORY (0.1.0)
    Cloning 80ed35991668ad0df9f2857b6021c61c4c70c74b
```
And I expected this to happen:
this add a .git folder inside vendor/GROUPNAME/REPOSITORY but I don't want create that folder, I only want download my package like the others packages

**Comment by tobias-trozowski** [comment]
This is the way composer works.

You just provided a repository url and composer got no information about any archive of your repository.
The reason why "other packages" are downloaded as zip, tar or whatever is that packagis also provides mirroring for packages' zip.

But there's not only Packagist out there. [Satis (open source)](https://github.com/composer/satis), [Packagist (commercial)](https://packagist.com) or [Toran Proxy (commercial)](https://toranproxy.com/) might be a good alternative.

## Satis
Satis is a static composer repository generator and needs to be regenerated after every commit.
But it is quite easy to automate this too. Just create a new repository with your satis config and a job/pipline on your CI Server which will build the package data.
Add a WebHook to your repositories on your GitLab server, so your CI gets notified about a change and rebuild the package data.
Documentation can be found at https://getcomposer.org/doc/articles/handling-private-packages-with-satis.md
See https://github.com/composer/satis

## Packagist (commercial)
This is just the commercial version of [Packagist](https://packagist.org).
In my opinion the best choice for companies because it's super easy to configure and it's easy as packagist.org to use.
See https://packagist.com

## Toran Proxy (commercial)
To be honest, i never tried it. Just wanted to mention it as an alternative.
See [Toran Proxy](https://toranproxy.com/)

**Comment by alcohol** [comment]
You might want to use `vcs` and not `git` type of repository.

**Comment by tobias-trozowski** [comment]
@alcohol what is the difference? i thought they do the same... :O

**Comment by alcohol** [comment]
They are not the same. `git` type is "dumb" and purely treats it as a git repository (so in order to retrieve any information such as branches and tags, it first does a local clone into cache). `vcs` is "smart" and will use the Github/Bitbucket/Gitlab API when possible to retrieve information about branches and/or tags.

**Comment by tobias-trozowski** [comment]
Ah ok thx, just removed my way more complicated - and obviously wrong - answer.

**Comment by alcohol** [comment]
That was not necessary..

**Comment by emimarz** [comment]
I tried both types
"type": "git",
"type": "vcs",

but I obtain the same result

**Comment by stof** [comment]
You need to configure your domain as being a gitlab domain if you want the gitlab API to be used (by default, only gitlab.com is registered there, as composer cannot know your private gitlab domain automatically): https://getcomposer.org/doc/06-config.md#gitlab-domains

**Comment by AndrewRadchenko** [comment]
@emimarz Same problem. Is anybody find the solution?

**Comment by pursehouse** [comment]
seems that the only fix is to set
`	"config" : {
		"preferred-install" : "source",`
which is kinda weak that there doesn't seem to be any way to set the preferred on a repository specific level

**Comment by Seldaek** [comment]
@pursehouse you mean like this? https://getcomposer.org/doc/06-config.md#preferred-install

**Comment by Seldaek** [comment]
Yes indeed it takes precedence

>
