### ISSUE TITLE
Bug in the ClassLoader?

### ISSUE THREAD

**Issue by CracyCrazz** [composer/composer#6038]
Hey guys,

since the latest update of Composer to version 1.3 we experienced some strange issues with our Symfony applications. The latest version of the ClassLoader wasn't able to find our classes prefixed with a backslash, eg:

`use \Doctrine\ORM\Mapping as ORM;`

Therefore the annotations in the doc blocks could not be found anymore as the first character found by composer was a "\" and that didn't matched any of the known namespaces:

https://github.com/composer/composer/blob/1.3/src/Composer/Autoload/ClassLoader.php#L375

This wasn't an issue with any previous composer versions due to the following lines in the ClassLoader:

https://github.com/composer/composer/blob/1.2.4/src/Composer/Autoload/ClassLoader.php#L317

We would like to know if this is intended to work like this or not.
Once we remove the "\" before "Doctrine" everything works out fine.

If you need any more information's I'll try to give you as much insight in our code as I'am allowed to.

**Comment by Seldaek** [comment]
We removed this because it was my understanding this bug only affected PHP 5.3.0-5.3.2, are you still running one of these versions?

**Comment by Seldaek** [comment]
Ah I think the problem is not in PHP in your case but in Doctrine's annotation lib, which probably takes the use statements as they appear and doesn't clean up the leading backslash. I'd report the bug there, and for now strip the leading backslashes if you can.

If you can't apply the change to your entire codebase easily, you can also do this as a workaround in your bootstrap file:

```
$loader = require 'vendor/autoload.php';
$loader->unregister();

spl_autoload_register(function ($class) use ($loader) {
    return $loader->loadClass(ltrim($class, '\\'));
});
```

This basically restores the trimming by decorating the composer ClassLoader.

**Comment by CracyCrazz** [comment]
Alright I will report that and for know use the workaround. 

Thank you :) and have a great day.
