### ISSUE TITLE
"[RuntimeException] Invalid working directory specified, does not exist" error

### ISSUE THREAD

**Issue by Arbeliam** [composer/composer#6063]
Hi,
I've just started using Composer. I installed Drush for Drupal 8 which is working fine. Then I installed Drupal console which isn't. I've been trying to figure out what's wrong, and might post again about the problems I have with it, but first of all there seems to be a rather fundamental issue since 'composer -d' yields an "Invalid working directory specified,  does not exist." error message. How/where exactly is the working directory defined (All the relevant information is pasted below)? 
Thanks!

My `composer.json`:

```json
{
    "require": {
        "drush/drush": "dev-master",
        "drupal/console": "@stable"
    }
}
```

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK

```

When I run this command:

```
composer -d
```

I get the following output:

```
  [RuntimeException]
  Invalid working directory specified,  does not exist.

```

**Comment by alcohol** [comment]
`composer -d /path/to/other/directory`

It simply lets you set the working directory to something other than the directory you are currently in (most people just run composer in their project root). This is mostly useful for scripted/automated environments, and you will rarely use it interactively on the commandline.

**Comment by Arbeliam** [comment]
First of all I should note that I'm working on Windows (8.1)

If I understand correctly, running  `composer -d` with no arguments is supposed to throw the RuntimeException error?

Also, Composer is installed in c:\Users\admin\AppData\Roaming\Composer\. I tried running the following:

`composer -d /Users/admin`

and 

`composer -d c:\Users\admin`

And i'm still getting errors

```
[Symfony\Component\Console\Exception\CommandNotFoundException]
Command "/Users/admin" is not defined.
```
and 

```
[Symfony\Component\Console\Exception\CommandNotFoundException]
There are no commands defined in the "c" namespace.
```

respectively

**Comment by alcohol** [comment]
Oh, Windows.

/cc @johnstevenson @Seldaek halp plz.

**Comment by stof** [comment]
the issue is not specific to Windows AFAICT. Passing options values (with the syntax sending them as separate args in the shell) without passing a command name is not working fine in symfony/console, as it will take ``/Users/admin`` (or ``c:\Users\admin``) as the command name (i.e. the first shell argument not starting with a ``-``).

You should test this for supported cases, i.e. when passing a command name to be run

**Comment by johnstevenson** [comment]
Actually, it doesn't matter which OS because the command should be  `composer -d=path/to/other/directory` otherwise the Console component doesn't behave as you might expect.

With `composer -d path/to/other/directory` it first uses the path as the value of the `-d` option (it will throw an error if it does not exists), then it will use it again as the command to run (unlike a normal getopt function that would remove the path from the arguments after it has been used).
