### ISSUE TITLE
Can I alias dev to versioned?

### ISSUE THREAD

**Issue by AndriySvirin** [composer/composer#6107]
My `composer.json`:

```json
{
  "type": "project",
  "minimum-stability": "stable",
  "require": {
    "php": ">=5.4.0",
    "p2made/yii2-p2y2-things": "1.15.0 as dev-master",
    "p2made/yii2-p2y2-things-demo": "1.15.0 as dev-master",
    "p2made/yii2-sb-admin-theme": "1.5.9",
  }
}

```

When I run this command:

```
composer update
```

I get the following output:

```
Dependency resolution completed in 0.002 seconds
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Removal request for p2made/yii2-p2y2-things == 9999999-dev
    - p2made/yii2-sb-admin-theme 1.5.9 requires p2made/yii2-p2y2-things dev-master -> satisfiable by p2made/yii2-p2y2-things[dev-master].
    - p2made/yii2-sb-admin-theme 1.5.9 requires p2made/yii2-p2y2-things dev-master -> satisfiable by p2made/yii2-p2y2-things[dev-master].
    - Removal request for p2made/yii2-p2y2-things == 9999999-dev
    - Installation request for p2made/yii2-sb-admin-theme 1.5.9 -> satisfiable by p2made/yii2-sb-admin-theme[1.5.9].
```

And I expected this to happen: Composer will alias *twice* dev -> 1.15.0 ?

**Comment by francislavoie** [comment]
I'm literally having issues with the same library you mention right now. Ugh. https://github.com/p2made/yii2-sb-admin-theme/issues/8

**Comment by alcohol** [comment]
Encourage the author of `p2made/yii2-sb-admin-theme` to use sane version constraints. `dev-master` is not a sane, safe nor useful constraint. It also does not improve dependency resolution, as he seems to suggest in the issue you linked. Using `dev-master` is generally a **bad idea**.

**Comment by AndriySvirin** [comment]
Author is ```genius```. And I am not happy that will manage project with this library.

**Comment by p2made** [comment]
I am the developer of `p2made/yii2-sb-admin-theme` & while I agree that `dev-master` is not a sane version constraint, I have almost been going insane trying to have sane versions constraints that work reliably. However I am working on it.

I must confess to feeling well out of my depth with the PHP work I am attempting. I am first & foremost a mobile app (iOS) developer trying to realise an exciting idea as an under-resourced team of one. I am only working with PHP & Yii2 out of necessity borne of needing a multi-faceted website & API in support of the app, & not having the means to pay someone else to do it. Rest assured I'm working on solving my problems with this, because I want it working for own use,  `p2made/yii2-sb-admin-theme` is intended to be my backend & the UI for future clients to manage their data through.

**Comment by alcohol** [comment]
@p2made you can always visit #composer on irc.freenode.net and ask questions you might have there (please keep in mind it is IRC though, so receiving an answer can take anywhere between 5 minutes or 24 hours).
