### ISSUE TITLE
Is there a way to silence a specific (or all) "abandoned" warning from a sub-dependency?

### ISSUE THREAD

**Issue by igorsantos07** [composer/composer#6133]
My project currently depends on a [quite old package](https://github.com/bangpound/tika-rest-client) (that still works quite well, though), that depends on a dinosaur called Guzzle 3. As the package is quite unknown, it seems abandoned as well, and I'm afraid [it will never get updated](https://github.com/bangpound/tika-rest-client/issues/3) - even more if you consider the changes between Guzzle 3 and the current upstream are _huge_.

I was wondering if there's any way I could make composer stop complaining about Guzzle 3 having been abandoned? That's quite annoying and, unfortunately, not something I could handle myself :/

![screenshot_002](https://cloud.githubusercontent.com/assets/532299/22630674/8c577e7a-ebe5-11e6-8cba-b34d53eb5cdb.png)

**Comment by curry684** [comment]
It's MIT licensed, so go fork the unmaintained package and start maintaining it yourself. Do the changes for Guzzle 6, slam a [replace](https://getcomposer.org/doc/04-schema.md#replace) header in the `composer.json`, and push it to Packagist.

That's how open source works  😄 

Composer is giving that warning for a reason, so you are reminded every time you hit that update button that your dependencies are a timebomb waiting to explode in your face. And that it would be a good idea to take my first paragraph to heart soon.

**Comment by alcohol** [comment]
Also, just because you feel that it is annoying, does not mean there is any real issue here. It's not a beauty contest. That one yellow line in your output is not going to ruin your day. Get over it.

**Comment by igorsantos07** [comment]
@curry684, you may have focused only on the point "a package I depend on is old", but if you re-read the entire bug report, you'll notice I've already tried doing _just that_ - but that's a herculean task that is not worth it. That's why I was looking for a way to hide the warning instead.
Also, I wouldn't call that a timebomb. It's not that Guzzle 3 depends on old platform features, they just decided to change their entire API so badly they needed even a new namespace. Old code still works and there's no reason it would stop working in the future - unless the rest of my project (and that package I depend on) stop working as well because of some PHP novelty.

-----------

I love how the internet is able to create such stupid trolls like that cute @alcohol(ic?).
Yeah, that's not a beauty contest, but it's a PITA to run a command every now and then and suddenly see a warning popping on your screen, just to notice it's something you have to ignore.

Until another warning starts popping up and I'm also ignoring it, but I actually shouldn't because it's indeed something relevant.

There's something you might not know about, mr. Kitty, and that's about UX. Get down from your altar and learn some manners.

**Comment by curry684** [comment]
I did read you already tried doing that. It doesn't change a bit about how the world works - if the package is unmaintained it's not going to be updated anymore unless someone volunteers. It doesn't change the fact that right now it's outdated and importing abandoned packages. It doesn't change the fact that Composer thankfully has mechanisms to warn developers of that. It doesn't change the fact that Composer doesn't want to have options to ignore truly dangerous situations like the one you're in now.

So, your project has an issue, and you choose to ignore it, that's fine. Composer will keep issuing warnings about, and you can ignore those, that's also fine. Doesn't make it any less relevant or correct, so it's not going to stop or get a suppression option. That's actually also fine. So, as @alcohol pointed out: what's the real problem here?

As for the second half of your post - @alcohol is providing free support for this project in his own unpaid time. His response may not have been the sweetest ever, but we're in a development issue tracker here, not kindergarten. His wording did not, in any way, warrant your extremely childish and offensive response. Grow up.

**Comment by igorsantos07** [comment]
Well, people have different views, right?
For that reason at least I'll never spit up two lines saying "this is not going to ruin your day, this is not a beauty contest, get over it". If that's not kindergarten, that's at least quite rude - calling it "not the sweetest ever" is quite an understatement. Those were not arguments on the matter, those were bare critics over my report. That's what a troll does: opens up an empty argument, full of bare critics. If you want, we can even call it a fallacy - quite common on children that don't know how to argue or discuss ideas properly.

Again, in my view, that's certainly not the type of thing I would say to someone I've never seen before - even more coming from someone without even a pic, or barely a name. Definitely, not welcoming - different from your messages, @curry684 :)

--------

As per the real "issue" here, I don't wanna argue if composer should ever have such flag or not, but understand: is this some sort of "uncommon" case where an old dependency is not the end of the world, or am I just not seeing the imminent explosion in this timebomb?

**Comment by curry684** [comment]
Yes, it's pretty rare, as in practice packages rarely get marked as abandoned, usually they just stop getting commits one day. That automatically implies that those few packages that *do* get the abandoned stamp get it for good reason, as the developer/maintainer took the effort to specifically warn people about the situation.

In the case of Guzzle, that's the Guzzle developers warning you that you're using an HTTP communication layer that will not, ever, get *any* update whatsoever for future security concerns. In my book, that's worrisome in a world where root certificates are getting compromised, SSL2 and SSL3 got compromised and MitM attacks are daily business.

It's not all that different from still using Windows XP in 2017. It may work fine, it just didn't get any patches for the past 3 years of security problems. Whether that's an issue.... I sure think so.

**Comment by igorsantos07** [comment]
Got your point.

That's indeed a specific case, as we use Guzzle in this situation to communicate with servers inside a VPN - the project we depend on is a PDF OCR scanner, that happens to have an HTTP server to provide data. We `post` files and `get` data back inside our own network, so HTTP security wouldn't be something for us... But I can certainly see your point: someone wouldn't mark as deprecated unless it had a very good reason (not only a change in namespaces / "hey, we got a new version, update now").

Thanks sir :)

**Comment by mercuriev** [comment]
Would be really nice of you to add a config var to shut up this warning.
Using packages that are not maintained anymore **is not a bug**!

**Comment by curry684** [comment]
> Using packages that are not maintained anymore is not a bug!
> There are absolutely valid situations when old packages are better.

That's why it raises a warning and continues instead of an error and halting.

**Comment by mercuriev** [comment]
> warning is that it will never be seen again
I propose to not throw it in bright color at each run, but to show these warnings with `-v` instead.
That way it will be seen when asked to be seen.

**Comment by curry684** [comment]
> This way it will be seen when asked to be seen.

Meaning "never" to 99% of the users, defeating the purpose. Using abandoned packages is an acute security and stability issue that should be fixed as soon as possible. Warnings should always be considered "non-blocking errors" and it simply needs to be fixed.

Fix the problem and the warning goes away.

**Comment by nicolajknudsen** [comment]
Could it potentially be a compromise to suppress specific named packages on a case by case basis? I agree with OP that after a while you just kind of mentally ignore the yellow lines and are not aware if/when a new problem arise.

In my case I get the warning from the package described in [this thread](https://drupal.stackexchange.com/questions/302682/what-is-the-best-practice-for-handling-abandoned-packages-required-by-the-drupal). That specific package mentioned was written for drupal core, and has been [merged into drupal core](https://www.drupal.org/project/drupal/issues/3180351). The problem is that here nearly one year after the warning is still there:
```
§ composer why doctrine/reflection
doctrine/common          2.13.3  requires  doctrine/reflection (^1.0)   
doctrine/persistence     1.3.8   requires  doctrine/reflection (^1.2)   
drupal/core              9.3.5   requires  doctrine/reflection (^1.1)   
drupal/core-recommended  9.3.5   requires  doctrine/reflection (1.2.2)
```
I'm not quite sure why it is still left there by drupal, as I understand they will finally remove the dependency with the release of drupal 10, but by then the message will have been shown for well over a year and there really is no underlying issue. I can't see how I could contribute meaningfully to the core development to expedite this matter faster, since it has already been patched by the core team.
