### ISSUE TITLE
Use-case for repositories-dev

### ISSUE THREAD

**Issue by alexbowers** [composer/composer#6158]
I know that this has been suggested, and rejected, a fair number of times, but I feel that something has been missed from the discussion that I hope will persuade you to the usecases.

For our system, we have several in-house projects that form our product.

Some of these projects require the same projects as each other, for example, 

`core-product-1` might require `dependency-1`, and `core-product-2` might require `dependency-1` too.

To make development feasible, we utilise symlink development, so our root directory contains all of the project source code, and all of our composer files use symlinks for our projects to load the latest code into them all.

This works without issue on our development environment.

However, when it comes to building for a release, we have to use the VCS versions, since our build machine is a completely separate process.

The current method for us doing this is to have a completely separate `production.composer.json` file, which as part of our build process, replaces the `composer.json` file in each project. This allows the `composer install` to work properly. Unfortunately, this can, and has, led to some issues with the `production.composer.json` file not being up to date with the `composer.json` file, which our staging environment catches. But this shouldn't require a full build and test suite to determine, if we could have `repositories-dev` we can have symlinks setup in the `--dev` environment, and have it `vcs` in the normal environment. This keeps the install in a single location, and allows for hopefully less mistakes.

**Comment by julienfalque** [comment]
Did you try adding your local repositories to `~/.composer/composer.json`?

**Comment by stof** [comment]
The issue with repositories-dev is that this would require totally separate resolution of packages for dev and no-dev (as available packages will not be the same), making the lock file tied to the mode used when running it (and breaking things if using it in the other mode), which is precisely something that Composer tries to avoid as of 1.0.
It would open the range for lots of weird cases breaking things (defeating the point of making your setup more reliable).
Btw, if you want a local build to catch this, it would require resolving dependencies twice locally, which would be twice slower. Or if would require you to opt-in to check the normal mode (which is not different than using ``COMPOSER_FILE=production.composer.json composer update --dry-run`` to check for it).

Btw, if you want to ensure that the files stay in sync, you could write a simple test ensuring that both files stay in sync, so that running tests locally fails if the prod file is outdated (or even a post-update hook updating the prod file automatically)

**Comment by alexbowers** [comment]
> Did you try adding your local repositories to ~/.composer/composer.json?

Didn't know that was a thing. I'll give that a go, see what happens.

**Comment by stof** [comment]
that won't work. ``~/.composer/composer.json`` is for ``composer global ...``.

And adding it in ``~/.composer/config.json`` will still not allow you to commit your lock file.

**Comment by julienfalque** [comment]
Woops, yes I meant `~/.composer/config.json` :)

**Comment by Seldaek** [comment]
Closing as per @stof's comment above, indeed it would cause tons of issues, and goes against the principles of having a composer.lock file for reliable deployments.

**Comment by stephan-v** [comment]
So in essence there is no clean way to reliably deal with this? I too am running into this problem.

**Comment by Seldaek** [comment]
Yes. The question is what you're trying to achieve. Most things are possible given the right workflow, but some people insist on workflows that just are not compatible with the way we do things.

**Comment by alewolf** [comment]
@Seldaek I ran into the same problem today. Like @alexbowers I started to link a local package  because I need it in two separate local app projects. But, when I want to deploy my apps to the production server, composer on the production server can't access my local packages, so I need to make the local package available on github (or similar). Given my limited knowledge about composer, there seems no way how to do this.

You mentioned most things are possible given the right workflow. But no one outlined a possible workflow in this thread that allows 1) quick development on a local package that is shared between several local app projects and 2) is available to the production server when deploying the apps to the production server.

I don't mind adjusting my workflow. What workflow would you recommend?

**Comment by alewolf** [comment]
@Seldaek I just found the following thread where you pointed to a solution: https://github.com/composer/composer/issues/8391#issuecomment-547435045 

I will try this.
