### ISSUE TITLE
 php composer.phar install

### ISSUE THREAD

**Issue by oepl** [composer/composer#6170]
I run below command via root user in ubuntu 14. I was not aware about to avoid to install using root user. There is no option to remove this lib? What type of issued I can face now? Anyone can advice me?

It just create a "vendor" directory at my project folder where I run command. Do I need to check any system setting or folder?

**Comment by alcohol** [comment]
You did not share the command you ran with us. There is no immediate risk I think. But we generally just do not recommend running commands as root user unless you have to.

**Comment by oepl** [comment]
I run below command after download composer.phar

php composer.phar install

**Comment by stof** [comment]
well, to avoid running composer as a root user, this is simple: don't sudo as root before running it.

It you ran composer as root already, you will need to remove your ``vendor`` folder (and maybe ``chown`` the composer.lock file if it was created during the install), so that your vendor folder is not owned by root.

**Comment by oepl** [comment]
Ok thanks for your help. Actually I ran that command in project root directory and created vendor folder. I just want make sure command is not changing operating or LAMP settings.

Thanks for your quick help
