### ISSUE TITLE
Local Path package in dependency package

### ISSUE THREAD

**Issue by TomasVotruba** [composer/composer#6253]
I use [path](https://getcomposer.org/doc/05-repositories.md#path) packages in open-source monorepo and I split them to standalone repositories.

In the split repository there are 2 local packages: https://github.com/Symplify/EasyCodingStandard/blob/master/composer.json

When I try to install this package:

```
composer require symplify/easy-coding-standard:@dev
```

Those path packages are not found.

## How to solve this?

I would love to keep them local as they are no use standalone on Packagist.

But now I don't see any other way than turn them to regular packages.

Is there any? 

Thank you

**Comment by alcohol** [comment]
The command you displayed will never work, because that tries to install `symplify/easy-coding-standard` which has dependencies on packages that you do not have. Path is meant for local development only. Path repositories can never be used as dependencies of projects that you are not working on locally. Please read the documentation if you are unclear about how to use path repositories.

**Comment by alcohol** [comment]
Your only solution is to put them on packagist, or to make them part of your root package.

**Comment by TomasVotruba** [comment]
I though so, thanks for confirmation.

> or make them part of your root package.

How would you do that without changing file structure nor `/packages` code location?


I has idea of just adding autoloading:

```json
"autoload": {
    "psr-4": {
        "Symplify\\EasyCodingStandard\\": "src",
        "Symplify\\EasyCodingStandard\\SniffRunner\\": "packages/SniffRunner/src",
        "Symplify\\EasyCodingStandard\\FixerRunner\\": "packages/FixerRunner/src"
    }
}
```

What do you think?

**Comment by alcohol** [comment]
@TomasVotruba adding their autoloading definitions should do the trick.
