### ISSUE TITLE
[Feature] option --autoload

### ISSUE THREAD

**Issue by meglio** [composer/composer#627]
Will only generate autoloading. This is often needed separately when developing a project with Composer autoloader used.

**Comment by cweiske** [comment]
Note: Simply changing a dependency's composer.json autoload section and calling `composer dumpautoload` does not help. You need to adjust `vendor/composer/installed.json` as well.

**Comment by Seldaek** [comment]
@cweiske yeah, or not changing anything in the vendor dir directly is also a good option ;) Because any time you update your changes might get wiped. Best is to configure things via your composer.json, either overriding packages to use forks of them, or even defining extra autoload rules that point to the vendor dir if you must.

Anyway this issue is probably not the best place to discuss that.
