### ISSUE TITLE
Make --prefer-lowest only affect "require"

### ISSUE THREAD

**Issue by kelunik** [composer/composer#6273]
When using `--prefer-lowest` that should only affect libraries required by `"require"`, no `"require-dev"` dependencies. It doesn't make sense to use e.g. PHPUnit and its dependencies in the lowest version. For `"require"` dependencies this makes sense to detect not strict enough dependency constraints which might get installed when the package is combined with other packages which require stricter package versions.

On the other hand, if everyone just uses semantic versioning, `--prefer-lowest` doesn't make any sense at all.

**Comment by jvasseur** [comment]
`--prefer-lowest` still make sense for `"require-dev"` when using it to testing optional dependencies.

**Comment by Seldaek** [comment]
prefer-lowest's only use case really is to check that your test suite passes with the lowest deps. phpunit being part of those deps means you should still check if the minimum version you require passes IMO.

And yes even with semantic versioning it is quite useful to check as you don't know if you require ^1.0 for example but your code actually uses stuff from v1.1 of a lib..

**Comment by kelunik** [comment]
> prefer-lowest's only use case really is to check that your test suite passes with the lowest deps. phpunit being part of those deps means you should still check if the minimum version you require passes IMO.

Testing for lowest deps only makes sense in case a lower than the most recent version could be installed. And that's only the case when other packages have additional constraints.

Regarding PHPUnit the problem is mainly that lowest would require additional constraints in `"require-dev"`, because updating to the newest version doesn't upgrade PHPUnits dependencies to the newest. That means I'd have to list PHPUnit's dependencies as my `"require-dev"` dependencies just to install the newest version.

> And yes even with semantic versioning it is quite useful to check as you don't know if you require ^1.0 for example but your code actually uses stuff from v1.1 of a lib..

My argument was rather that with semantic versioning everywhere it doesn't matter whether you specify `^1` or `1.1` as only the newest version is going to be installed.

**Comment by Seldaek** [comment]
> Testing for lowest deps only makes sense in case a lower than the most recent version could be installed. And that's only the case when other packages have additional constraints.

Nope, I could also run a partial update on my deps, and have the latest version of your lib but some older one of another lib your depends on for example.

I see the problem with phpunit's deps, but IMO it's not really a reason to change this behavior, which would possibly have much bigger unexpected impacts..

**Comment by kelunik** [comment]
Why would you do a partial update if every library follows semver? 

It doesn't have to be a change to the existing flag, could of course be an additional flag.

**Comment by Seldaek** [comment]
I do partial updates all the time because I've been bitten in the ass more than once by regressions, and sometimes I just want to quickly update one thing without having to double check nothing broke when updating the whole framework let's say.

As for the new flag, actually that's probably pretty hard to do because this only changes the way we sort packages, but doing that depending on which package is in require and which is in require-dev is probably almost impossible because stuff could be required by packages being both require and require-dev for example, so we don't have a clear list, and the policy for picking packages is applied globally without distinction. The entire solver has no knowledge of require/require-dev concepts really, it just knows requirements.

**Comment by curry684** [comment]
If `--prefer-lowest` exposes issues in your dev dependencies you should raise the minimum required version for those dev dependencies. Exactly as with regular dependencies, since that is exactly what the flag is for - testing lowest supported versions. And that should most definitely include your unit testing and mocking libraries as those are being installed all the time in CI.

**Comment by anlutro** [comment]
Hate to bump an old closed issue, but I have a problem that makes me want this feature. I want my package to support PHP versions 5.x and 7.x, but some of the 5.x versions only work with PHPUnit 4.x. However, PHPUnit 4 has a problem with PHP 7.2 specifically. So my options are:

- Ignore all failures from PHP 7.2 when --prefer-lowest is specified
- Drop support for PHP versions that don't work with more recent versions of PHPUnit 5.x
- Run `composer update` twice, once with no arguments, then again with `--no-dev --prefer-lowest`?

**Comment by iluuu1994** [comment]
Testing with the lowest versions of *some* dev dependencies indeed make sense. Maybe specifying which dependencies explicitly are exempt from `--prefer-lowest` would be useful?

```json
{
    "ignore-prefer-lowest": [
        "friendsofphp/php-cs-fixer",
        "phpstan/*",
        "psalm/*",
    ],
}
```
