### ISSUE TITLE
Programmatically register plugin

### ISSUE THREAD

**Issue by tlovett1** [composer/composer#6302]
Hello, I am using Composer programmatically like so:

```php
putenv( 'COMPOSER_HOME=vendor/bin/composer' );

$input = new ArrayInput( [ 'command' =>'init' ] );
$application = new Application();
$application->setAutoExit( false );
$application->run( $input );
```

Now this works fine.  However, what I'm trying to do is setup a plugin to be used within the code above. Is there a way to do that?

**Comment by Seldaek** [comment]
With the init command definitely not as composer plugins are not executed ever in the init command AFAIK. In other commands.. it's difficult, because at the point the Application is initialized there is no composer object to work with. It's not going to work with all commands, but for some you can do this:

```
$application = new Application();
$application->setAutoExit( false );
$application->getComposer()->getPluginManager()->addPlugin(new MyPlugin());
$application->run( $input );
```

This requires that a composer.json file be available in your working directory though..
