### ISSUE TITLE
Stable `suffix` endings

### ISSUE THREAD

**Issue by jeffminard-ck** [composer/composer#6306]
Every time I run `composer install` all of the composer files get changed similar to this:

```diff
- class ComposerAutoloaderInitb9993fa09fca665060d52df2499637d3
+ class ComposerAutoloaderInit47366cd886aa67cbbb76858fa90bc616
```

I believe [this function here](https://github.com/composer/composer/blob/122e422682d961233cc5db8b2102cd98b049d4f9/src/Composer/Autoload/AutoloadGenerator.php#L284) controls this output and produces a new random suffix hash for all the included functions.

Would it be reasonable to change that from an md5() on a random value to an md5() of the composer.json file instead? This way, as I am re-running the composer commands, these files stay consistent.

---

"But ", you ask, "what does it matter if these files change the md5 suffix every time?" I, my friend, am one of those poor souls who (for all the various reasons) has a repository where the `vendor` folder is committed to VCS. I would like to be able to re-run composer commands with as little change as possible; so this would help avoid a boatload of ineffectual hash changes.

I'm aware of the config option for [autoloader-suffix](https://getcomposer.org/doc/06-config.md#autoloader-suffix), but I do like the self-altering suffix for opcache reasons.

**Comment by curry684** [comment]
If anything it should be the hash of the lockfile, not the json file, as that is the one unique to the state.

But dare I ask: why not just remove vendor folder from VCS? What good reasons could there be for Composer to change behavior for the sake of simply lessening the administrative burden of a flawed workflow?

**Comment by Seldaek** [comment]
@jeffminard-ck I don't see what the altering suffix does for opcache to be honest. And I also don't know why it keeps changing for you, because normally [we detect the one currently used](https://github.com/composer/composer/blob/122e422682d961233cc5db8b2102cd98b049d4f9/src/Composer/Autoload/AutoloadGenerator.php#L277) and re-use it if the vendor dir exists. Are you rebuilding vendor from scratch every time? If so then yes I would say use the autoloader-suffix..
