### ISSUE TITLE
Support: Question about .phar archives and composer

### ISSUE THREAD

**Issue by roman-shuhov** [composer/composer#6332]
Is it possible to fetch vendor dependencies as phar files in composer?

**Comment by curry684** [comment]
Nope.

**Comment by roman-shuhov** [comment]
@curry684 was it considered as an option? Does it have any drawbacks or concerns?

**Comment by curry684** [comment]
To my knowledge never considered. What use case and advantages do you see?

**Comment by roman-shuhov** [comment]
I think it's good to represent a particular package version as a one file artifact. Also it may reduce installation time for packages, in terms of moving/packing/unpacking one big file, against N(may be a pretty big number) small files.

**Comment by GromNaN** [comment]
Phar can be used as dist packages, but they are extracted: https://github.com/composer/composer/blob/master/src/Composer/Downloader/PharDownloader.php

Since phar files can be included like any other PHP file, it might be possible to declare a package like this (not tested at all):
```json
{
            "type": "package",
            "package": {
                "name": "vendor/name",
                "version": "3.1.7",
                "dist": {
                    "url": "library.phar",
                    "type": "file"
                },
                "autoload": {
                    "files": ["library.phar"]
                }
            }
        }
```

**Comment by roman-shuhov** [comment]
yeah, but it's a very specific use case. I'm thinking about more generalized way of working with phar packages. So, if package provides phar option and user specifies something like --prefer-disr/phar composer can automatically handle this. 

Do you see any drawbacks with this idea?

**Comment by curry684** [comment]
Tons  :)   Many packages do things like `file_get_contents(__DIR__ . '/../res/magicfile.json')` or otherwise depending on local package structure. There is therefore no reliable coherent way to package *any* library as a phar unless the library was specifically written with this distribution method in mind.

Also, in the case of for example Symfony or other *huge* libraries it would severely hurt performance as you are losing all the caching benefits of opcache et al being able to optimize for class files with JIT autoloading.

In most if not all cases it would be less performant and buggy.

**Comment by antonmedv** [comment]
It will be cool to have that. 

Now getting this:
```
Extracting archive    REASON: Required by the root package: Install command rule (install deployer/deployer 5.1.3)
```
