### ISSUE TITLE
Non-root users can't need to enter password after update

### ISSUE THREAD

**Issue by WojciechWalczak** [composer/composer#6336]
I updated Composer on my server via ```composer self-update``` and everything seemed to be ok but user ```developer``` can no longer execute ```composer``` because password is needed:

```
$ composer
$ [sudo] password for developer:
```

```composer``` is located in ```/usr/local/bin/composer``` and has 755 mode. Even if I change owner of ```composer``` to ```developer:developer``` he still can't run it without providing password.

As I said, everything worked perfectly before, and after update this happened. I've tried removing and installing different versions of composer several times.

**Comment by alcohol** [comment]
Could possibly be related to composer trying to kill any active sudo sessions.

**Comment by Seldaek** [comment]
You can try to run `COMPOSER_ALLOW_SUPERUSER=1 composer` and see.. if that fixes it then yes it's probably due to our anti-sudo-leakage code. If it doesn't fix it then it gets even weirder. But either way this should not happen unless you are doing weird things, or unconventional as @alcohol put it.

**Comment by Seldaek** [comment]
Auto-closing this as it's marked as support request and has not received any update in a long time.
