### ISSUE TITLE
GitLab dist URL is wrong for GitLab API v3

### ISSUE THREAD

**Issue by sjadema** [composer/composer#6344]
I reported this issue in #6198 and provided a merge request to fix it. It seems my initial testing was wrong and the data set i used to verify the fix was wrong as well. The documentation on GitLab's side is not as clarifying as one might hope.

This basically means the 'fix' for the `dist-url` should be reverted. It was changed from `sha` to `ref` and should be reverted to `sha`. This fixes downloading of zipball archives from GitLab API `v3`.

I do apologize for any inconvenience this may have caused.

**Comment by Berdir** [comment]
This was reported as well in the referenced issue above, tracked it down to this problem with some help from Gitlab and wanted to fix it, only to notice that is already fixed.

As I see it, this is a pretty serious bug because it breaks the promise of the lock file, you'll get the latest version of a gitlab dependency every time you run composer install. Any chance there could be a new release soon to fix this?
