### ISSUE TITLE
Composer change path - stripped off 'a' in '.../app/...' folder

### ISSUE THREAD

**Issue by mikaelit** [composer/composer#6393]
Autoload section from composer:
```
"autoload": {
        "psr-4": { "": "src/" },
        "classmap": [ "app/AppKernel.php", "app/AppCache.php" ]
},
```

Composer build path to AppKernel.php and AppCache.php without 'a' in 'app' folder:

autoload_classmap.php
`    'AppCache' => $baseDir . '/pp/AppCache.php',
    'AppKernel' => $baseDir . '/pp/AppKernel.php',
`

autoload_static.php
`        'AppCache' => __DIR__ . '/../..' . '/pp/AppCache.php',
        'AppKernel' => __DIR__ . '/../..' . '/pp/AppKernel.php',
 `

**Comment by alcohol** [comment]
Please provide a way to reproduce this, because currently I cannot (everything works as expected). Literally thousands of Symfony users also have no trouble with this (https://github.com/symfony/symfony-standard/blob/master/composer.json#L8). So clearly it is something specific to your environment or your setup.

**Comment by diazemiliano** [comment]
I've simmilar error to.
@mikaelit You could solve it?

**Comment by mikaelit** [comment]
I tried, but only reinstall environment helps.
