### ISSUE TITLE
Unable to run composer update 

### ISSUE THREAD

**Issue by shakirblouch** [composer/composer#6395]
Getting error 
[Composer\Downloader\TransportException]   Your configuration does not allow connections to http://getcomposer.org/dow   nload/1.4.1/composer.phar.sig. See https://getcomposer.org/doc/06-config.md   #secure-http for details.

any Idea ?

**Comment by sneakernets** [comment]
same here, I can't even access the website now.

**Comment by forevermatt** [comment]
As of today, we can't access packagist.org or getcomposer.org from the office, and a remote colleague reported problems using composer/packagist as well. I know GitHub issues aren't the ideal place for troubleshooting server issues, but can anyone point me to where I should look for / report this kind of problem? Since I can't get to either of those websites, I don't know if there is information there about this. If not, I understand. I'll keep digging.

**Comment by forevermatt** [comment]
In response to @shakirblouch, it sounds like your system is trying to access getcomposer.org via HTTP, but it requires a specific config setting (`secure-http` set to `false`) to allow non-HTTPS traffic. Do you see anything in your `composer.json`, for instance, suggesting the use of `http:` somewhere?
