### ISSUE TITLE
Config command doesn't work with default packagist.org

### ISSUE THREAD

**Issue by cs278** [composer/composer#6424]
The change that made the default packagist repository to be named `packagist.org` (e38ebefc7e644899478c46e24657a6cccc5b8b5b) means that it can no longer be manipulated by the command line, you can still use the `packagist` alias but presumably that will be removed at some point. 

Also given the example set by the default repository people assume that using a domain name for the repository label is something that works just fine.

My `composer.json`:

```json
{
}
```

When I run this command:

```sh
# Either:
composer config repos.packagist.org false
composer config repos.packagist.org composer https://packagist.org

# Followed by
composer show
```

I get the following output:

```
  [Composer\Json\JsonValidationException]                                       
  "./composer.json" does not match the expected JSON schema:                    
   - repositories.packagist : Object value found, but a boolean is required     
   - repositories.packagist : Does not have a value in the enumeration [false]  
   - repositories.packagist.type : The property type is required                
   - repositories.packagist.package : The property package is required          
   - repositories.packagist.url : The property url is required                  
   - repositories.packagist : Failed to match exactly one schema
```

And I expected this to happen:

Packagist repository to be configured without an error

**Comment by alcohol** [comment]
This is because named repositories cannot contain a `.` currently. The `.` indicates a nesting level. I personally think the `config` command should have been designed to work more with `--flags` from the very beginning, which would make it a lot easier to account for all the various use-cases people have. In its current state however it is quite hard to predict what the user exactly wants. The same input could be interpreted in different (sometimes conflicting) ways.
