### ISSUE TITLE
Cannot install specific versions of a project without composer config minimum-stability first

### ISSUE THREAD

**Issue by uberhacker** [composer/composer#6512]
If I want to install a specific version of a project and that version does not have a stable release yet, I need to first run `composer init -n`, then `composer config minimum-stability beta` before I can install that version.  Example: `composer require drush/drush:9.*`.  See below:

When I run this command:

```
 composer require drush/drush:9.*
```

I get the following output:

```
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package drush/drush 9.* is satisfiable by drush/drush[9.0.0-alpha1, 9.0.0-beta1, 9.0.0-beta2, 9.0.x-dev] but these conflict with your requirements or minimum-stability.


Installation failed, deleting ./composer.json.
```

And I expected this to happen:
```
The latest available non-stable version of the project should be installed.
```
Maybe the `composer require` command needs a `--stability` option?  For example, `composer require drush/drush:9.* --stability beta` could perform the `composer init -n` and `composer config minimum-stability beta` steps behind the scenes.  Thoughts?

**Comment by stof** [comment]
if you want to change the stability of a single package that you require, the stability override is part of the version constraint. So you can already do it: `composer require drush/drush:9.*@beta`

**Comment by uberhacker** [comment]
@stof: Thank you for the suggestion.  I could do that, however, if there ever was a beta3 release, since I didn't run `composer config minimum-stability beta`, it would not update since the assumed minimum stability is still stable.  Am I right?

**Comment by stof** [comment]
nope. The `@beta` is part of the version constraint added in your composer.json. this is a per-package min-stability, which overwrites the general setting.

**Comment by uberhacker** [comment]
Ah, I didn't know that.  What happens when there is a stable release?  Will `composer update` work?  See the point I am getting at here?  My expectation is that composer will always update to the latest release without any additional configuration goofiness.  Is this possible?

**Comment by stof** [comment]
yep. Min-stability is a minimum. It does not mean that only beta versions are allowed (but unless you remove the `@beta`, composer will use 9.1-beta1 as soon as it is released instead of using 9.0.* stable releases, as 9.1 is a higher version than 9.0)

**Comment by uberhacker** [comment]
That is what I want to avoid.  Removing the `@beta` would mean more config goofiness to update.  Is there a setting that will always update to beta, rc, stable (aka whatever is the latest version) from a simple `composer require org/project:???`?

**Comment by greg-1-anderson** [comment]
One thing of note is that `@beta` et. al. is not the same as setting `minimum-stability`; in fact, in its current form, it often fails to loosen constraints sufficiently to allow the request to be satisfied.

For example, imagine that I have a PR in a library, and I want to test that PR in an application that uses the library. I add the following to my composer.json:
```
    "consolidation/robo": "dev-extract-config",
```
This results in the following error from `composer update`:
```
  Problem 1
    - Installation request for consolidation/robo dev-extract-config -> satisfiable by consolidation/robo[dev-extract-config].
    - consolidation/robo dev-extract-config requires consolidation/config dev-master -> satisfiable by consolidation/config[dev-master] but these conflict with your requirements or minimum-stability.
```
This is because my development version itself requires a development component. This could be made to work if I made a stable release of the leaf project (`consolidation/config`); however, I don't want to do that until I have demonstrated that it works in the library it is being used in, and in order to do that I need to require both of these libraries in an application that uses them, so that I can functionally demonstrate that the proposed change is compatible. Doing this necessitates that I set the minimum stability of the application via `composer config minimum-stability dev`.

Changing the constraint of my library to `dev-extract-config@dev` does not change the behavior of `composer update`. I am uncertain whether this form is intended to be semantically different; it appears to be equivalent.

I am going to remain neutral about the original ask here, to set the minimum stability via a flag in `composer require`; if this were provided, it would cause some of the "config (update) goofiness" the OP would like to avoid, as setting the minimum stability will allow other components unrelated to the requested one to be pulled in at a beta level. `prefer-stable` helps tons here -- does that mean that we also want `prefer-stable` to be a flag on `composer require`?

`composer require drush/drush:9.*@beta` is much closer in behavior to what the OP desires; however, as I mention above, it is not always sufficient, because beta Drush releases sometimes have beta dependencies. Ideally, the `@beta` modifier in `drush/drush:9.*@beta` would automatically extend to the dependencies of Drush, but not to other dependencies in the project. This, I imagine, would not be simple to implement.

**Comment by alcohol** [comment]
The preferred approach when you want one dependency at a different stability level, and it itself has dependencies that do not match your project stability level, is to also add those sub-dependencies to your root composer.json with the required `@stability` override.

Most of what has been said in this thread is spot on. Yes, it is inconvenient. But then again, this is not a use-case most users run into. But even as a library developer, you would probably be off easier if you just use path repositories locally on your development machine, and depend on `dev-master` for each package you are working on during your development cycle.

Suggested changes such as propagating the `@stability` flag are not desirable for numerous reasons, complexity definitely being one of them, but also things like predictability and awareness.
