### ISSUE TITLE
Imrove message when package was not found

### ISSUE THREAD

**Issue by robsch** [composer/composer#6513]
In combination with satis I tried to create a project. I've got the message `Could not find package myCompany/myPackage with stability stable. `. Since I've also just created a stable version 1.0.0 I was wondering why composer did not find the stable version. Took me some time to find out that it did not find the package at all. (I think my mistake was that I thought composer would evaluate an existing composer.json in the directory which has a repository declaration for the the satis server - specifying it as a command parameter is the correct approch - not sure). 

So you might improve the message to something like: 
* Package not found at all: `Could not find package myCompany/myPackage in any version.` or `Could not find package myCompany/myPackage  in any version at repository http://some.satis.url .`
* Package found without needed stability: `Found package myCompany/myPackage, but not with stability stable.` 

Or something like that.

**Comment by alcohol** [comment]
> Or something like that.

Like what we have right now? :see_no_evil:

**Comment by robsch** [comment]
@alcohol Yes, a tiny improvement. Feel free to ignore it.

**Comment by alcohol** [comment]
@naderman does the solver already make a distinction here?

**Comment by stof** [comment]
@alcohol not always (due to optimizations being applied).

The error reporting UI should then make a separate check to figure out the different case (similar to what `composer show -a`does:

- get the list of all available versions for this package (without stability filtering)
- if none, report package as not found
- if found but none matching the minimum-stability, report the stability issue (there is no release yet)
- check versions matching the constraint. If none found, report that the package version is not found
- check versions matching the constraint with the stability filter applied. If none found (while the previous case let us reach this step), report that the package version is not released yet, and suggest either changing minimum-stability or allowing lower releases
- finally report generic issue (probably a version conflict when reaching this)

**Comment by alcohol** [comment]
If the above is feasible, than implementing this would be a big plus imho indeed.

**Comment by Seldaek** [comment]
Fixed by https://github.com/composer/composer/pull/8558
