### ISSUE TITLE
composer not respecting 'requires' php version

### ISSUE THREAD

**Issue by dagnew** [composer/composer#6566]
The doctrine/instantiator 1.1.0 package has a requires php ^7.1. Composer is loading this package when my composer.json file specifies  "php": "^5.5". Expecting it to fail rather than install the package.

{
    "require": {
        "php": "^5.5"
        , "monolog/monolog": "1.*"
        , "mandrill/mandrill": "~1.0.32"
        , "nesbot/Carbon": "*"
        , "dg/twitter-php": "3.*"
        , "phpoffice/phpexcel": "1.8.*"
        , "rmccue/requests": ">=1.0"
        , "sunra/php-simple-html-dom-parser": "1.5.2"
        , "verbalexpressions/php-verbal-expressions": "dev-master"
        , "jsonrpc/jsonrpc": "v1.0.3"
        , "mobiledetect/mobiledetectlib": "2.*"
        , "fabpot/goutte": "v1.0.5"
        , "predis/predis": "0.8.*"
        , "tecnick.com/tcpdf": "6.0.*"
        , "aws/aws-sdk-php": "2.*"
        , "hashids/hashids": "1.0.*"
        , "twig/twig" : "1.*"
        , "league/climate": "2.4.0"
        , "league/csv": "^7.0.1"
        , "yiisoft/yii": "1.1.16"
        , "league/flysystem": "1.*"
        , "league/flysystem-aws-s3-v2": "1.*"
        , "danielstjules/stringy": "^1.9.0"
        , "intervention/image": "2.0.*"
        , "inlinestyle/inlinestyle": "1.*"
        , "phpmailer/phpmailer": "~5.2"
        , "knplabs/knp-snappy": "0.3.*"
        , "phpunit/phpunit": "^4.7.6"
        , "phpunit/phpunit-selenium": "^1.4.2"
        , "phpunit/phpunit-story": "1.0.*"
        , "phpunit/dbunit": "^1.4.0"
        , "phpunit/php-invoker": "^1.1.4"
        , "phpunit/phpunit-skeleton-generator": "*"
        , "johnkary/phpunit-speedtrap": "1.0.2"
        , "stripe/stripe-php": "1.*"
        , "donatj/phpuseragentparser": "*"
        , "devster/ubench": "1.*"
        , "piwik/piwik-php-tracker": "1.0.0"
        , "guzzlehttp/guzzle" : "^5.3.0"
        , "spomky-labs/base64url" : "^0.0.3"
        , "solarium/solarium" : "^3.4.1"
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}

**Comment by alcaeus** [comment]
Are you sure? Here's a minimal `composer.json`:
```
{
    "require": {
        "php": "^5.5",
        "doctrine/inflector": "^1.0"
    }
}
```

Here's what I get running under PHP 5.6.30:
```
$ php --version && composer install
PHP 5.6.30 (cli) (built: Mar 11 2017 09:56:27) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.5.4, Copyright (c) 2002-2017, by Derick Rethans
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing doctrine/inflector (v1.1.0): Loading from cache
Writing lock file
Generating autoload files
```

The same output with PHP 7.1.5:
```
$ php --version && composer install
PHP 7.1.5 (cli) (built: May 13 2017 13:30:32) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.4, Copyright (c) 2002-2017, by Derick Rethans
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php ^5.5 but your PHP version (7.1.5) does not satisfy that requirement.
```

**Comment by stof** [comment]
@alcaeus the issue here is not doctrine/inflector. It is your own test composer.json saying that your test project is not compatible with PHP 7 (`^5.5` means `>=5.5, <6.0`, and PHP 7.1.5 is outside this range). So of course trying to use your test project on PHP 7 breaks. But not because of the dependency.

`"php": "^5.5",` in your requirements means that your projects requires PHP 5.5, not that you want Composer to resolve deps compatible with PHP 5.5

**Comment by alcaeus** [comment]
@stof I know how composer works, thank you. I tried reproducing the original `composer.json` to highlight the issue, but got confused on package names (used doctrine/inflector instead of doctrine/instantiator).

My point is: on PHP 5.6, composer will simply install a version of doctrine/instantiator that runs on PHP 5.6, while running on PHP 7.1 will not run at all. Either way, @dagnew will never get an incompatible version. Could've made that clearer.

**Comment by stof** [comment]
@alcaeus what does not run on PHP 7 is not your doctrine/instantiator requirement. It is your **PHP** requirement. Remove the `"doctrine/inflector": "^1.0"` line and you will see.

what would highlight that Composer downloads the right version in both cases is a root package supporting both versions (and so able to do the selection on each of them)

**Comment by alcaeus** [comment]
@stof again, I know very well how composer works and why composer refused to install anything on PHP 7.1, thank you very much. If you check the OP you'll see the very same PHP version constraint in their `composer.json`, which is why I added it to show that composer will not simply install an incompatible version of anything. I also know full well that dropping said PHP requirement will install doctrine/inflector 1.1.0 on PHP 7.1 and 1.0.0 on older PHP versions. The reason why I didn't make that example is simple: that's not what OP claimed their problem was.

**Comment by curry684** [comment]
@alcaeus:

> I also know full well that dropping said PHP requirement will install doctrine/inflector 1.1.0 on PHP 7.1 and 1.0.0 on older PHP versions.

No it won't, that's what stof is trying to explain, that behavior is only based on the installed version of PHP, not an arbitrary root package requirement. It doesn't enforce anything on the solver other than an additional restriction.

And to answer the original question:

> The doctrine/instantiator 1.1.0 package has a requires php ^7.1. Composer is loading this package when my composer.json file specifies "php": "^5.5". Expecting it to fail rather than install the package.

Your expectation is half wrong. Your `composer.json` only states that the *root package* (your program) requires PHP `^5.5`. To actually override the PHP version used to solve you would need to [have a `platform` section](https://getcomposer.org/doc/06-config.md#platform).

So the curious thing about your case is not that `doctrine/instantiator:1.1.0` is being installed, that makes perfect sense if your PHP CLI version is 7.1+. It's weird that it's doing anything **at all** in that case, since that should make Composer halt right away as it's not satisfying the platform requirement in the root package.

To further investigate this issue we need a lot of extra information:
 - The behavior you describe should only ever happen if you pass the `--ignore-platform-reqs` flag to Composer update, in that case it's fully expected behavior on PHP 7.1+. Are you?
 - Barring that it'll be really interesting to know what PHP CLI version you are running. Please copy the full output of `php -v`
 - And of course, to debug what is happening, please use `-vvv` flags on the misbehaving command and supply the full command and its output, in a [Gist](https://gist.github.com/) or Pastebin preferably. You can edit out identifying information and private packages, neither are relevant.

**Comment by alcaeus** [comment]
> No it won't, that's what stof is trying to explain

Apart from me confusing `inflector` and `instantiator` (which have slightly different version numbers), yes, it does. On Systems with PHP 7.1 it will install doctrine/instantiator 1.1.0 (which requires PHP 7.1), while on systems with older versions it installs 1.1.0:
```
{
    "require": {
         "doctrine/instantiator": "^1.0"
    }
}
```

```
$ php --version && composer install
PHP 5.6.30 (cli) (built: Mar 11 2017 09:56:27) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing doctrine/instantiator (1.0.5): Loading from cache
Writing lock file
Generating autoload files
```

```
$ php --version && composer install
PHP 7.1.6 (cli) (built: Jun 23 2017 08:42:14) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing doctrine/instantiator (1.1.0): Downloading (100%)         
Writing lock file
Generating autoload files
```

For everything else, I wrote a blog post last night: http://doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html. Feedback is appreciated.

Also, OP is not the first person to run into an issue like this in the past few days, and in every case so far it was "run `composer update` on 7.1 and deploy to 5.6 or 7.0". At least now I can just link to the blog post instead of having to continuously re-explain that it's neither a bug with composer nor a BC break.

**Comment by bkinnari** [comment]
I am getting the error while running composer for phpSpreadhseet.

Error:
[InvalidArgumentException]
  Package phpoffice/phpspreadsheet at version  has a PHP requirement incompatible with your PHP version (5.5.12)

Please help.

**Comment by curry684** [comment]
How is that highly verbose error message not helpful enough?
