### ISSUE TITLE
Powershell - No Color Output

### ISSUE THREAD

**Issue by jagDanJu** [composer/composer#6587]
When I execute a composer command in the Powershell, I do not get any colored output...

Can anyone help me, please?

Thank You!

**Comment by alcohol** [comment]
Did you try passing `--ansi`?

**Comment by jagDanJu** [comment]
Yeah. But it does not work..

![image](https://user-images.githubusercontent.com/3613218/29019850-3c648038-7b60-11e7-996c-cb9b6e6991f7.png)

**Comment by alcohol** [comment]
Looks like an issue with powershell not properly interpreting color symbols. Do you have the same problem with other PHP CLI binaries using `symfony/console`, such as the `bin/console` from a default symfony framework application, or `phpunit` if you pass `--colors always`?

**Comment by Seldaek** [comment]
I'd recommend using ConEmu as terminal on windows, or loading ANSICON inside powershell if that's possible, not sure.

**Comment by jagDanJu** [comment]
It works with ANSICON.

`ansicon.exe "%SystemRoot%\system32\WindowsPowerShell\v1.0\powershell.exe"`

Thank you Guys!

**Comment by stof** [comment]
Yeah. Native support for POSIX colors on windows require changes which are part of PHP 7.2 (and not yet supported by symfony/console). So for now, color support on Windows requires using Ansicon or ConEmu.

Note that even when PHP 7.2 is out, support for native windows colors may not work for composer yet, as it uses an old version of symfony/console (due to PHP 5.3 support), and I'm not sure we backport it to symfony/console 2.x.

**Comment by Seldaek** [comment]
Automatically closing as this has not received any updates in a while. Please re-open if it is still relevant.
