### ISSUE TITLE
Composer is not reading Repositories of dependencies

### ISSUE THREAD

**Issue by silentwarrior** [composer/composer#6623]
In my main App, I am consuming a lib 'Lib-DB'.

In composer.json I state that App depends on Lib-DB. 
Lib-DB has its custom git repo and as such, its repo url is setup in the Repositories.

Lib-DB on itself depends on MigrationsRunner, and it also has a custom git repo and as such it is also setup in Lib-DBs Repositories section of its own composer.json.

On App, when I do `composer update` it will fail to find the migrations runner with message :

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for company/lib-db dev-migrations -> satisfiable by company/lib-db[dev-migrations].
    - company/lib-db dev-migrations requires company/migrations-runner dev-master -> no matching package found.
``` 

Running `composer update` on lib-db works perfectly. Also, running `composer update` on App if I am using a version also works perfectly, so I know the urls work perfectly.

**Is this a limitation of composer? How can I circumvent this problem?**

**Comment by jvasseur** [comment]
This is a know limitation of composer : https://getcomposer.org/doc/faqs/why-can%27t-composer-load-repositories-recursively.md

**Comment by silentwarrior** [comment]
The workaround is to add the git urls of this dependencys dependencies to the repositories of all projects where this dependency is used?

**Comment by janmyszkier** [comment]
this is not a bug:
accordinbg to 
https://getcomposer.org/doc/04-schema.md#repositories
this is root-only node, so it only reads those from the projects you're in (not from its dependencies)

the only solution for this is to add the custom repositories definitions to the project, which is the only correct behaviour imho, otherwise think about how easy would it be to:
- release nice package
- hijack other popular package by overriding in your repositories in now-dependent projects
this is security ;)
