### ISSUE TITLE
COMPOSER_ROOT_VERSION has no effect on nested dependencies

### ISSUE THREAD

**Issue by rybakit** [composer/composer#6625]
Seems like `COMPOSER_ROOT_VERSION` is only applied to direct root package dependencies, but not to nested ones.

I've created a demo repo to show the issue: https://github.com/rybakit/composer_self_version
The repository consist of 3 composer.json files:

[app/composer.json](https://github.com/rybakit/composer_self_version/blob/4ee4e6114ec52873b860132df6bb7cfb2a5c0f38/app/composer.json):

```json
{
    "name": "vendor/app",
    "type": "project",
    "require": {
        "vendor/common": "self.version",
        "vendor/foobar": "self.version"
    },
    "minimum-stability": "dev",
    "repositories": {
        "local-libs": {
            "type": "path",
            "url": "../lib/*"
        }
    }
}
```

[lib/common/composer.json](https://github.com/rybakit/composer_self_version/blob/4ee4e6114ec52873b860132df6bb7cfb2a5c0f38/lib/common/composer.json):

```json
{
    "name": "vendor/common",
    "type": "library",
    "minimum-stability": "dev"
}
```
[lib/foobar/composer.json](https://github.com/rybakit/composer_self_version/blob/4ee4e6114ec52873b860132df6bb7cfb2a5c0f38/lib/foobar/composer.json):

```json
{
    "name": "vendor/foobar",
    "type": "library",
    "require": {
        "vendor/common": "self.version"
    },
    "minimum-stability": "dev",
    "repositories": {
        "local-libs": {
            "type": "path",
            "url": "../*"
        }
    }
}
```

When I run 
```bash
COMPOSER_ROOT_VERSION=dev-master composer update --no-suggest --prefer-dist --no-scripts
``` 
everything is OK, but if I set `COMPOSER_ROOT_VERSION` to `dev-feature_branch` it starts to fail with:

```bash
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package vendor/foobar dev-feature_branch exists as vendor/foobar[dev-master] but these are rejected by your constraint.
```
Hovever, if I update `lib/foobar/composer.json`'s recuirement to
```json
    ....
    "require": {
        "vendor/common": "dev-feature_branch"
    }
```

it installs packages without any errors.

Composer version:

```bash
Composer version 1.6-dev (d9885d5b3bd1b28a6d8c679df848540e565ee818) 2017-08-21 07:16:59
```

**Comment by stof** [comment]
hmm, the path repository should indeed support `COMPOSER_ROOT_VERSION` if the detection ends up looking at the git repo containing the root package IMO. This makes sense.

**Comment by rybakit** [comment]
@stof Do you know if there is a workaround, by any chance?

**Comment by Seldaek** [comment]
I agree if the path repo is in the same git repo as `cwd` then it probably makes sense to apply COMPOSER_ROOT_VERSION to it too. 

There is no workaround for now except for not giving a version in this case, because then all your packages will have the same version defined and things should go well as long as you don't have cyclic dependencies further down the dependency graph.

**Comment by vesper8** [comment]
thank you for taking the time to explain @Seldaek 

I'm still confused though. I get that I can run 
``` COMPOSER_ROOT_VERSION=dev-master composer install ```

I just did this and it did indeed work. What is it doing exactly though? Is it just saying "for those packages without a version, use this" ?

But regarding you other option, how can I hardcode the version of my custom packages such as laravel_55?

These packages you see are nothing more than composer.json files with dependency sets of their own.. a means of organizing dependencies

**Comment by Seldaek** [comment]
It's saying for the root package (and also `path` repos in the same git repository as the root package), if no version is defined use the value of COMPOSER_ROOT_VERSION instead of guessing from git the branch/tag.

As for hardcoding it, I meant just put `"version":"1.0.0"` for example in all your composer.jsons of those "dependency sets" packages you created. Then they will always be at the same version.. Maybe that's a problem, I don't know, depends on what you do with them, this isn't really the typical composer usage so I am not sure.
