### ISSUE TITLE
Use variable in package URL?

### ISSUE THREAD

**Issue by tyrann0us** [composer/composer#6631]
Is it possible to include variables in package URL? If not, is this something you might consider in the future?
I couldn't find any information on this topic in the [documentation](https://getcomposer.org/doc/).

Thanks!

My `composer.json`:

```
[…]
{
  "type": "package",
  "package": {
    "name": "example/package",
    "version": "4.3.0",
    "dist": {
      "type": "zip",
      "url": "https://example.com/zip/{$version}/package.zip"
    }
  }
}
[…]
```

When I run this command:

```
composer update
```

I get the following output:

```
[…]
 - Installing example/package (4.3.0): Downloading (failed)

  [Composer\Downloader\TransportException]
  The "https://example.com/zip/{$version}/package.zip" file could not be downloaded (HTTP/1.1 404 Not Found)
[…]
```

And I expected this to happen:

Download package from `https://example.com/zip/4.3.0/package.zip`.

**Comment by alcohol** [comment]
No, and I do not really see a good use-case for this either, so it is very unlikely to be included.

**Comment by tyrann0us** [comment]
@alcohol, thanks for the clarification.

**Comment by robrecord** [comment]
Looks like this has been included with `{%variable}` but still I cannot find documentation - does someone have a link?

**Comment by gassan** [comment]
> No, and I do not really see a good use-case for this either, so it is very unlikely to be included.

Package distribution files are cached, so simply changing the version number is not enough to install a new version. You should always update both the `["version"]` and `["dist"]["url"]` fields.

**Comment by drzraf** [comment]
There are perfectly valid use case for this.

One is https://gitlab.com/gitlab-org/gitlab/-/issues/416071
GitLab `composer` package repository are built out of the sourcecode without any possibility to add custom (frontend) bundles into the final zip file.
It's possible to use "generic" package and follow user-defined versioning pattern. Eg: `https://gitlab.com/api/v4/projects/foo%2fbar%2fbaz/packages/generic/baz/my-1.2.3-tag/build.zip` for example.

But we **do want** to set the version inside the project's `composer.json` `require` section only without having to duplicate it in the  `repositories[X].package.version` section. And that's why `repository[FOO].package.dist.url` should definitely accept placeholder/substitution/variable out of the box.

BTW cache could (and should happen) based on the final GET URL. So having a placeholder in the URL shouldnt affect caching is handled.
