### ISSUE TITLE
The "-e" option does not exist.

### ISSUE THREAD

**Issue by yildavilla** [composer/composer#6645]
When the following command is ran: ```composer -version```, the following error is displayed:
```
  [Symfony\Component\Console\Exception\RuntimeException]
  The "-e" option does not exist.
```

**Comment by stof** [comment]
This is expected. When using a single dash, this uses option shortcuts, which can be combined together. So `composer -version` is the same than `composer -v -e -r -s -i -o -n` (and most of these options don't exist).

What you want is probably `composer --version`. Note that 2 dashes used for long option names rather than shortcuts.

**Comment by yildavilla** [comment]
oh perfect, thank you so much

**Comment by ouamba** [comment]
merci beaucoup pour votre reponse j'avais le même problème

**Comment by mofly76** [comment]
Nice.

**Comment by Nannim** [comment]
Oh okay
