### ISSUE TITLE
Failed to install dependencies on composer

### ISSUE THREAD

**Issue by vinibudd** [composer/composer#6689]
I'm trying to install the Slim Framework and it's failing composer, I'm running on bash for Windows 10

![image](https://user-images.githubusercontent.com/24849260/30546455-09261834-9c63-11e7-9b34-781ee2d1107d.png)

**Comment by stof** [comment]
Well, the message is clear IMO: it tells you that your PHP setup does not have the `zip` extension, and your system does not have the `unzip` tool, and so Composer cannot download the zip archive from github, and has to fallback to a source install (cloning the whole repo) which is generally slower (which is why it displays a warning).

Btw, the screenshot you showed us does not display any failure (well, the output tells me that the update is not yet complete at this point). There is no error message here. Only warnings (each warning is followed by a message saying that the package was cloned, and so its installation worked)

**Comment by vinibudd** [comment]
Thanks, I installed zip and unzip and it worked

![image](https://user-images.githubusercontent.com/24849260/30549492-46ef2a86-9c6b-11e7-9802-83867dea000b.png)

**Comment by stof** [comment]
note that installing one of them is enough for Composer (it supports both ways of extracting zip archives, to get more chances to have a supported way)

**Comment by vinibudd** [comment]
@stof Thanks friend
