### ISSUE TITLE
Installing Drupal via composer against local repository

### ISSUE THREAD

**Issue by achinayoungwaubonsee** [composer/composer#6694]
Hi. We are installing the latest Drupal 8.x via composer and would like to do things a little differently. Hoping you can provide some guidance. We will have a cluster of servers running Drupal. If we download Drupal with the following command-line:
  `composer create-project drupal-composer/drupal-project:8.x-dev drupal --stability dev --no-interaction`
then composer will download any dependencies from the Internet. However, is it possible for us to provide a local mirror that composer would download dependencies from? The advantage to us is that we would then be able to manage this local repository and update it when needed. If we use the command-line above today, and then a week from today, there is no guarantee that the same versions of dependencies will be available on both days. One server might have an updated version of a module than another Drupal server. We would like to prevent against this by using a local mirror.

**Comment by Jean85** [comment]
You are misunderstanding how composer works. The `create-project` is to be used just locally and to start the project; from then, you will have a composer.json file with the constraints for your packages, and a composer.lock file that will have all the informations you need: all needed packages with exact version.

Since you have the .lock file, a simple `composer install` will install all the dependencies, with fixed versions.

The mirror is still possible to save bandwidth, see Packagist.com (hosted) or [Satis](https://getcomposer.org/doc/articles/handling-private-packages-with-satis.md#satis) (self-hosted)

**Comment by alcohol** [comment]
@Jean85 summed it up nicely. Read up about what the .lock file does. For mirror options you have packagist.com or satis available.

**Comment by Jean85** [comment]
Since you are setting up a new infrastructure, I will also advise you to read this article: https://martinfowler.com/bliki/BlueGreenDeployment.html

With PHP, a simple simlink switch between two folders containing the code is enough to apply that strategy.

**Comment by achinayoungwaubonsee** [comment]
Ok, thanks.
