### ISSUE TITLE
Can requirements be added from composer hooks at runtime?

### ISSUE THREAD

**Issue by onnimonni** [composer/composer#6695]
Hey!

Is it possible to inject additional packages from composer hooks and persist them in composer.lock?

In my use case I would want to run `composer update` and end up having some extra dependencies in the lock file which were not in composer.json originally and they we're only deduced from the other packages or the environment automatically.

My example case is this one:
 
I would want to create composer-plugin `wp-language/fi` which checks that if the current composer environment has any packages with type `wordpress-plugin` it would automatically check WordPress api through: http://api.wordpress.org/translations/plugins/1.0/?slug=$PACKAGE_NAME 
and add custom Finnish translation zip file as a dependency if url responds with any available translation. And ofc similiar packages for other languages.

I know this is a hack but that would be really nice to have for people wanting a modern way to manage their WordPress translations.

Thanks in advance :blush:!

**Comment by Seldaek** [comment]
I think you could listen to the PRE_DEPENDENCIES_SOLVING event and modify the solver request there, but it's not gonna be trivial and wlil also result in issues down the line because if you inject new packages then on the next update the solver will attempt to remove them, so you could then re-add them again but it's just kinda messy. 

I don't see a way to do this very cleanly to be honest. It might be better to just listen to POST_UPDATE_CMD and POST_INSTALL_CMD, then look at which packages are currently installed then download the translation zip files and install them manually. It's still a bit dirty perhaps but should work.

**Comment by onnimonni** [comment]
Thanks for the input. I'll search for another option or settle for POST_UPDATE_CMD and POST_INSTALL_CMD.
