### ISSUE TITLE
[Feature Request] Download .git history for any Library

### ISSUE THREAD

**Issue by vzool** [composer/composer#6754]
Hi,

I'm looking for an option to download a part or all **.git** history for any installed library, because all libraries are working with others in the main project and at some point it does have an issue which needs to be fixed, tested and make PR.

Is there any option exists to do that and I'm not aware of?

Thanks

**Comment by stof** [comment]
remove your vendor folder (to uninstall all packages) and then run `composer install --prefer-source`.

The removal part is needed because `--prefer-source` has an impact on installation being performed. But if a package is already in your vendor folder, it won't be reinstalled from source.

If you always want to install from source, you can also use the config for that: https://getcomposer.org/doc/06-config.md#preferred-install
But I advice you to put such config in your system-level config, not in a project-level config, in case you use composer to perform installation on CI too. You definitely don't need VCS history on CI, and downloading a dist is fatser than cloning the repo (and the bigger the history is, the bigger the difference is).
