### ISSUE TITLE
Default virtual package provider choices

### ISSUE THREAD

**Issue by naderman** [composer/composer#6758]
There should be a way to specify a default package to satisfy a requirement on a virtual package.

For example https://packagist.org/packages/knplabs/github-api requires php-http/client-implementation . So to install it you need to require at least the implementation and the package itself. Instead it should be possible for knplabs/github-api to state that by default php-http/guzzle6-adapter can be used to satisfy the requirement.

This solution would allow easier installation while keeping the promise of not installing a package that doesn't have a direct name-based require route from the root composer.json.

I think the implementation would be quite simply, we'd introduce a new key in composer.json for this purpose and just need to make sure the package is loaded in the pool, as the solver will already work out that the package provides the required name.

```
    "require": {
        "php": "^5.5 || ^7.0",
        "psr/http-message": "^1.0",
        "psr/cache": "^1.0",
        "php-http/httplug": "^1.1",
        "php-http/discovery": "^1.0",
        "php-http/client-implementation": "^1.0",
        "php-http/client-common": "^1.3",
        "php-http/cache-plugin": "^1.4"
    },
    "default-providers": {
        "php-http/client-implementation": {
            "php-http/guzzle6-adapter": "^1.0"
        }
    }
```

**Comment by fbourigault** [comment]
That would be a great improvement. However, I would not specify any version constraint in the `default-providers` section as the solver can choose the right `php-http/guzzle6-adapter` version that satisfies the `php-http/client-implementation` `^1.0` constraint.

**Comment by joelwurtz** [comment]
For the reference this was already discussed here https://github.com/composer/composer/issues/4039, and @Seldaek point that it was more complex than it look likes.

There are some questions that comes to this that need to be discusses before having that, like:

 * What is the rule use when 2 or more libraries state differents choices for the same implementation ?
 * What happens if the default implementation is in conflict with other packages ?

**Comment by dbu** [comment]
sounds like a great idea. and yes, i would only handle the trivial case, and in all other situations fail but with a clear error message that explains that there was no explicit choice and package x and y both provided a different default implementation. the default would help in simple cases, and the better error message would at least give a hint in complex cases.

currently, the error does not even give hints that the missing dependency is a virtual package, i got many error reports because people did (of course) not read install instructions and then are confused...

**Comment by Nyholm** [comment]
Could I put out a reward for this issue to be fixed? 
Like: You do this PR and I'll do two of yours?

**Comment by Nyholm** [comment]
I increase the reward. 

If this issue get resolved I'll do 4 PRs of your choosing!

**Comment by GromNaN** [comment]
Perhaps the implementation package still needs to be explicitly required in order to avoid the following story:

In a project lifetime, when first installing knplabs/github-api would carry php-http/guzzle6-adapter, then if php-http/curl-client is installed (explixitely reauired or as a dependency) then php-http/guzzle6-adapter would be removed.

The implementation could be : when a required package has a dependency to a virtual package that is not satisfied, composer find all packages implementing it and interactively ask to choose one of them. Bonus: if one of the packages is suggested by other installed packages, it comes as "default" option on top of the choices list.

**Comment by nicolas-grekas** [comment]
See https://github.com/FriendsOfPHP/well-known-implementations for a Composer plugin that achieves the goal described here.

I'll claim the reward later :stuck_out_tongue_closed_eyes:
