### ISSUE TITLE
"git not found" error removing requried-dev packages.

### ISSUE THREAD

**Issue by vrubiella** [composer/composer#6765]
My `composer.json`:
Erro
```json
    "require": {
        "php": ">=7.0",
        "laravel/lumen-framework": "~5.5",
        "vlucas/phpdotenv": "~2.4",
        "appzcoder/lumen-routes-list": "~1.0",
        "laravel/envoy": "~1.3",
        "tymon/jwt-auth" : "~1.0.0-rc.1",
        "league/csv" : "~8.2"
    },
    "require-dev": {
        "vluzrmos/tinker": "dev-master",
        "darkaonline/swagger-lume": "~5.5",
        "fzaninotto/faker": "~1.7",
        "phpunit/phpunit": "~6.4",
        "mockery/mockery": "^1.0"
    },
```

When I run this command:

```
composer install --prefer-dist --no-dev
```

I get the following output:

```
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 0 installs, 0 updates, 43 removals
  - Removing psy/psysh (v0.8.13)
  - Removing myclabs/deep-copy (1.7.0)
  - Removing swagger-api/swagger-ui (v3.4.0)
  - Removing vluzrmos/tinker (dev-master)

                                            
  [RuntimeException]                        
  Failed to execute git show-ref --head -d  
  sh: git: not found   
```

And I expected this to happen:

Just remove dev packages.

I fix-it, moving "vluzrmos/tinker" to require packages...

**Comment by stof** [comment]
Well, I think this is related to the fact that Composer performs a check for uncommitted changes before removing a package installed from source.

But then, the question is how can you have a package installed from source if you don't have git installed in the first place ? Have you copied the vendor folder from elsewhere ?

**Comment by stof** [comment]
Composer does not behave well if it had access to git in the past (and so was able to install from source) and then you remove access to git (because Composer knows that the package was installed from source and will treat it like that)

**Comment by vrubiella** [comment]
Composer install is executed in container building process (docker build).

Maybe is a "special case", but other packages are removed without problems. I think the problem is related with "dev-master" tag.

**Comment by stof** [comment]
@vrubiella other package were not installed from source when creating the content of your `vendor` folder.
How have you run the **previous** composer command which installed these packages ? It looks like it was not the same, as this previous run had access to `git` (otherwise the package would not have been installed from source)

**Comment by vrubiella** [comment]
yes @stof I run composer update on local (git binary), but when I build the container, I just copy vendor inside container and runs composer install --prefer-dist --no-dev for cleanup all dev packages.


```
FROM xxx/alpine-fpm-composer
WORKDIR /www
COPY . /www

ENV APP_ENV=production

RUN chown -R cmsadm:cmsadm /www && \
    composer install --prefer-dist --no-dev
```

**Comment by stof** [comment]
well, then you have several solutions:

- force composer to always install from dist even on local (using ``--prefer-dist` in the CLI or the dedicated config setting)
- install git in the container so that it can use source installs
- skip the vendor folder when copying data in the container, so that `composer install --no-dev` downloads packages on its own instead of having to handle the package downloaded previously by the host with more capabilities.

**Comment by vrubiella** [comment]
thks @stof !
