### ISSUE TITLE
require_once __DIR__ . 'sendgrid-php/vendor/autoload.php' not seeing the autoload.php file

### ISSUE THREAD

**Issue by indomtrading** [composer/composer#6771]
I'm getting extremely angry with Composer. I'm getting sick to death of seeing these messag[https://imgur.com/a/aiF8w](url) when clearly the fucking directory exists. Its clear there is an issue with composer because when I run the poxy command `<require_once __DIR__ . 'sendgrid-php/vendor/autoload.php';>` it decides it's doing to be a retarded 5-year-old child.

Anny suggestions as to why this keeps happening?

Thanks
![2017-10-28 5 _li](https://user-images.githubusercontent.com/32191704/32134714-090afad4-bbeb-11e7-9355-ae62b830bc01.jpg)

**Comment by digitalkreativ** [comment]
It seems you are missing a / or \ even in your path where you include the autoload.php . 
The `__DIR__` value does not contain a trailing slash per [PHP docs](http://php.net/manual/en/language.constants.predefined.php)

Try changing `__DIR__` with `__DIR__ . DIRECTORY_SEPARATOR `

This should takes the \ into consideration.

**Comment by alcohol** [comment]
@digitalkreativ is correct. You are missing a path separator.

If you read the error that PHP provides you, you can see that it is trying to access a directory named `TastefullyObscenesendgrid-php`. This directory does not exist.

Also I have to correct you here, the first commit to this repo dates back to Tue Apr 5 17:36:01 2011 +0200, so that actually makes Composer 6 years old, not 5.

**Comment by DASPRiD** [comment]
@alcohol I would assume that with software it works the same way as with dog-years, which would make Composer a 6 years old adult, not child.
