### ISSUE TITLE
VCS repository sets different fetch/push URLs

### ISSUE THREAD

**Issue by curry684** [composer/composer#6772]
Assume in `composer.json` a VCS repository:
```
        {
            "type": "vcs",
            "url":  "https://github.com/my/package.git"
        }
```
I install `dev-master` of the package. Now `git remote -vv` in the install folder yields:
```
composer	https://github.com/my/package.git (fetch)
composer	https://github.com/my/package.git (push)
origin	https://github.com/my/package.git (fetch)
origin	git@github.com:my/package.git (push)
```
While nearly nobody will actually notice the discrepancy between the fetch and push URLs on the default origin, it does break development if you never bothered to install a pubkey on Github - in that case fetch and Composer's own actions work fine, but you cannot push.

I see no valid reason at all for overriding the push URL to an SSH URL when an HTTPS URL was explicitly defined.

**Comment by alcohol** [comment]
Have you determined **why** this is happening? Cause I don't really know.

**Comment by curry684** [comment]
Nope, haven't had a chance to debug, and was hoping someone with more intimate knowledge of the Git driver would pop up and say why he built it like this hehe.

**Comment by Seldaek** [comment]
This is done by design as if you can push you usually have an ssh key auth, and otherwise by default you get a public https URL that you can fetch without any auth. Indeed you can not push by default if you have no ssh key configured. In that case you can update the push URL, composer won't touch it after the initial clone.
