### ISSUE TITLE
Dependencies not calculated correctly when packages are pinned to a commit ref

### ISSUE THREAD

**Issue by danepowell** [composer/composer#6789]
If you pin a dependency in your composer.json to a specific commit ref on a dev branch, composer will correctly download the package files for that commit ref but it will _incorrectly_ calculate the dependencies. It appears to calculate dependencies based on the version of the package's composer.json at the tip of the dev branch, rather than the version at that commit ref.

As a test case, my `composer.json`:

```json
{
    "name": "test",
    "license": "proprietary",
    "type": "project",
    "description": "test",
    "require": {
        "acquia/lightning": "dev-8.x-2.x#b2203d3dfd978e8ce794ddadfb89b1ced28e0327"
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
The package "acquia/lightning" is pointing to a commit-ref, this is bad practice and can cause unforeseen issues.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:

```
composer update
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for acquia/lightning dev-8.x-2.x#b2203d3dfd978e8ce794ddadfb89b1ced28e0327 -> satisfiable by acquia/lightning[dev-8.x-2.x].
    - acquia/lightning dev-8.x-2.x requires bower-asset/cropper ^2.3 -> no matching package found.

```

And I expected this to happen:
The Lightning package to be installed without error, because that particular commit hash does not depend on bower-assets.

You can see that Lightning's version of composer.json at the commit ref b2203d does _not_ include any references to bower assets:
https://github.com/acquia/lightning/blob/b2203d3dfd978e8ce794ddadfb89b1ced28e0327/composer.json

But the version at the tip of 8.x-2.x _does_:
https://github.com/acquia/lightning/blob/8.x-2.x/composer.json

**Comment by stof** [comment]
This is a documented behavior: https://getcomposer.org/doc/04-schema.md#package-links (scroll a bit to reach the note on a blue background near the doc about this feature. It does not have a direct anchor).
The commit pinning is an installer-level hack changing the reference between installing. It has *no* effect on the dependency solver (it cannot, as Packagist does not keep metadata for each commit of the repo, which would be insane unless you want to run composer only on servers with 1TB RAM available for Composer to load the metadata).

My own advice is to never use this old feature of composer (this feature was added at the time where `composer update` was not able to perform partial updates only, and it is hurting Composer since then).

If you need to be able to install other things that the head of a branch, the right way is to create a release (Packagist keeps metadata for tags).

**Comment by stof** [comment]
another reason to avoid this feature: this is the end of this note in the documentation:

> The Composer team does not actively support this feature and will not accept bug reports related to it.
