### ISSUE TITLE
Is there a way to load a private repo locally if it exists, otherwise use the remote repo?

### ISSUE THREAD

**Issue by Sarke** [composer/composer#6790]
I tried a [stackoverflow question](https://stackoverflow.com/q/46965594/1448147) but I didn't get any answers.

Basically, what is the best way to develop several related packages locally, without having to push and pull on changes to the remote repository?

I know I can use local symlinked repos, but those will not work for testing/staging/production; these have to use the regular remote repo.

Having two separate `composer.json` files (one for development and one for deployed) seems like one option, but is that the best way?  Can I somehow use a condition in `composer.json`?

**Comment by alcohol** [comment]
Specify the path repositories locally in your global composer configuration. Default to regular source on all your other environments.

**Comment by alcohol** [comment]
The only downside is that you will have version constraint issues. You could get around this by doing something like (but it is kind of iffy):

```
"require": {
  "foo/bar": "^1.0"
},
"require-dev": {
  "foo/bar": "dev-master"
}
```

Locally, install with dev requirements, other environments install with `--no-dev`. Although I am not sure if this approach still works since we now always take both "require" and "require-dev" into consideration. @Seldaek thoughts?

**Comment by Seldaek** [comment]
There is no super clean way to do this I think.. At least not if the package is meant to be installed in production. If the package is a library and only will be deployed to prod as a dependency, then repositories don't matter as they are ignored when the package is a dependency.
