### ISSUE TITLE
Handle open_basedir

### ISSUE THREAD

**Issue by Seldaek** [composer/composer#680]
@LazyTown (anyway that was the IRC name, if it's not the same person on github apologies for the spam) reported this issue:

    [  file_exists(): open_basedir restriction in effect. File(/root/.composer/.htaccess) is not within the allowed path(s):
    (/var/www/vhosts/myhost.com/symfony_projects:/var/www/vhosts/myhost.com/backoffice:/var/www/vhosts/myhost.com/staging:/usr/bin/php:/tmp)

Either we catch it and advertise the use of COMPOSER_HOME, or we just skip writing silently or with a soft warning.

**Comment by HLFH** [comment]
@Seldaek Any news?

**Comment by Seldaek** [comment]
Nope, nobody cared enough to fix it so far it seems.

**Comment by cclose** [comment]
If this helps anyone... I use the following shell-script as a wrapper around my composer.phar to deal with this:

```.sh
#!/bin/bash
#!/bin/bash

#install composer if it's missing
if [ ! -f 'composer.phar' ] ; then
  echo "Composer Not Found... installing"
  curl -sS https://getcomposer.org/composer.phar > composer.phar
  if [ $? -eq 0 ] ; then 
    echo "Installed!"
  else
    echo "Composer failed to install!";
    exit 1;
  fi
fi

#double check
if [ ! -f 'composer.phar' ] ; then
  echo "Composer failed to install!";
  exit 1;
else
  COMPOSER_HOME='/var/www/composer/home' COMPOSER_CACHE_DIR='/var/www/composer/cache' bash -c "php -d allow_url_fopen=1 -d suhosin.executor.include.whitelist=phar composer.phar $@";
fi
```

In addition to redirecting the `COMPOSER_HOME` and `COMPOSER_CACHE_DIR` to open_basedir acceptable dirs, this makes distributing composer via SourceControl easier as I can now `.gitignore`  the `composer.phar` without needing an extra setup step of downloading composer.

**Comment by tamas-marton** [comment]
Hi, I've had the same issue, and think I've found the cause. I'm using a wrapper `bash` script for security reasons, which applies an `open_basedir` restriction, allowing only all the necessary paths. One of them is: `$HOME/.cache/composer/`, but an error always occured, telling me that `$HOME/.cache/composer/.htaccess` is unreachable due to the `open_basedir` restriction.

I've found out that it happens also, when the `$HOME/.cache/composer` dir doesn't exist (for example after running `composer clear-cache` in my case). Manually creating the dir resolved the issue for me.

I don't know if it's already resolved in later Composer versions, sorry if it's a duplicate. By the way, my `composer --version` outputs the following:

    Composer version 1.7.3 2018-11-01 10:05:06

**Comment by tamas-marton** [comment]
Hi, I've had the same issue, and think I've found the cause. I'm using a wrapper `bash` script for security reasons, which applies an `open_basedir` restriction, allowing only all the necessary paths. One of them is: `$HOME/.cache/composer/`, but an error always occured, telling me that `$HOME/.cache/composer/.htaccess` is unreachable due to the `open_basedir` restriction.

I've found out that it happens also, when the `$HOME/.cache/composer` dir doesn't exist (for example after running `composer clear-cache` in my case). Manually creating the dir resolved the issue for me.

I don't know if it's already resolved in later Composer versions, sorry if it's a duplicate. By the way, my `composer --version` outputs the following:

    Composer version 1.7.3 2018-11-01 10:05:06

**Comment by tamas-marton** [comment]
Hi, I've had the same issue, and think I've found the cause. I'm using a wrapper `bash` script for security reasons, which applies an `open_basedir` restriction, allowing only all the necessary paths. One of them is: `$HOME/.cache/composer/`, but an error always occured, telling me that `$HOME/.cache/composer/.htaccess` is unreachable due to the `open_basedir` restriction.

I've found out that it happens also, when the `$HOME/.cache/composer` dir doesn't exist (for example after running `composer clear-cache` in my case). Manually creating the dir resolved the issue for me.

I don't know if it's already resolved in later Composer versions, sorry if it's a duplicate. By the way, my `composer --version` outputs the following:

    Composer version 1.7.3 2018-11-01 10:05:06

**Comment by tamas-marton** [comment]
Hi, I've had the same issue, and think I've found the cause. I'm using a wrapper `bash` script for security reasons, which applies an `open_basedir` restriction, allowing only all the necessary paths. One of them is: `$HOME/.cache/composer/`, but an error always occured, telling me that `$HOME/.cache/composer/.htaccess` is unreachable due to the `open_basedir` restriction.

I've found out that it happens also, when the `$HOME/.cache/composer` dir doesn't exist (for example after running `composer clear-cache` in my case). Manually creating the dir resolved the issue for me.

I don't know if it's already resolved in later Composer versions, sorry if it's a duplicate. By the way, my `composer --version` outputs the following:

    Composer version 1.7.3 2018-11-01 10:05:06
