### ISSUE TITLE
Composer update loads all releases tree from repo

### ISSUE THREAD

**Issue by bartiii** [composer/composer#6819]
In composer.json in section require I have set that composer should use package with releases tree:
`"package":` "1.1.*"`

Composer loads full tree from 1.1.* and also other trees from the repository to the cache. 
It takes more time than required if the package has lots of releases.

**Comment by curry684** [comment]
Which driver are you using for that package?

**Comment by bartiii** [comment]
@curry684 Not sure what do You mean by **driver**, but the repository is on GitHub.

**Comment by janmyszkier** [comment]
@bartiii I think he referred to 
https://getcomposer.org/doc/05-repositories.md
so this is probably git?

Hovewer I can also confirm this happens on github repositories:
- composer.json has a version (taking from above example "1.1.*")
- I run composer update
- I can see ALL version being checked, 0.1.1, 0.1.2, 0.2.3, 0.2.4

It definitely shouldn't be checking THOSE because they don't match semver provided

**Comment by curry684** [comment]
I was asking about the driver because indeed the VCS/Git drivers work differently here than the Packagist driver. In the case of Packagist all metadata is already extracted and provided, with the other drivers the metadata has to be extracted from the repositories. Which indeed means that all tags and branches have to be inspected for the contents of their `composer.json` file, as it may contain required information on top of the tag/branch name, like [explicit version numbers](https://getcomposer.org/doc/04-schema.md#version) and [aliases](https://getcomposer.org/doc/articles/aliases.md).

So yes, when using a VCS repo directly it's by design that all potentially valid references are inspected so the solver can properly do its work.

**Comment by janmyszkier** [comment]
:thinking: so composer cannot just ignore the branches /tags that doesn't match the semver provided because it looksup some other data? Is that documented somewhere we can look this up?
@curry684 
It's either way wrong or wrong IMHO. Doesn't sound like anything intuitive nor like anything that should happen.
What you said means I can hijack someones stable version by adding my branch with a composer.json (or whatever made master qualify as valid for ^4.0) and break someones build? I don't think this works (or that it should work) like that.

**Comment by curry684** [comment]
"Adding a branch" implies the exact same access rights to a repository as "pushing to master". From a security perspective there is no difference. If you see any realistic disadvantage to the existing mechanisms by all means describe it in more detail. Just "counterintuitive" is not an argument against a mechanism that would have far more counterintuitive consequences if removed.

**Comment by alcohol** [comment]
@janmyszkier you are wrong.

In a VCS repository, the `composer.json` is leading. And in order to figure out what the `composer.json` contains, we have to check each branch and tag in a repository. Period.
