### ISSUE TITLE
Allow to specify versions for suggested packages and warn on mismatch

### ISSUE THREAD

**Issue by Xerkus** [composer/composer#6848]
Suggest section is good to specify optional dependencies that enable additional functional. It would be nice to also allow to specify versions of suggested packages and to warn on update if installed versions do not match suggested constraints.

For example zend-mvc defines following in its composer.json:
```
"suggest": {
        "zendframework/zend-psr7bridge": "(^0.2) To consume PSR-7 middleware within the MVC workflow",
        "zendframework/zend-stratigility": "zend-stratigility is required to use middleware pipes in the MiddlewareListener",
        "http-interop/http-middleware": "^0.4.1 to be used together with zend-stratigility"
},
```

Say, zend-stratigility ^2.1 introduced new functionality that we want to use, but some users might be using 2.0 or even 1.3 and they would have no way of knowing that `composer update` just broke their install.
We can't add zend-stratigility < 2.1 conflict as optional dependency might not be used with mvc, so we got a bit of an issue here.
Warning would notify users and would give them an option to fix or to ignore the issue.

**Comment by Seldaek** [comment]
Actually you can use a conflict rule to prevent these, although I wouldn't really advise adding tons of conflicts rule for all your suggests.. I don't think this is really worth the complexity here sorry.

**Comment by Xerkus** [comment]
@Seldaek please note that i do not ask sugested versions to be used in version resolution.
Only after the fact check to notify the user there is something that needs his attention.

Zend Framework consists of over 60 independently versioned packages, many of which could work together. 
Say `zendframework/zend-feed` could work with service manager to provide container based plugin manager or it can be used standalone. Framework users would also use zend-servicemanager itself.
They might update to zend-servicemanager 4.0.0 when it is released and all will go well if they didn't use it with zend-feed(or another of a dozen packages with optional deps on SM). If they used it in zend-feed then they will have dependency conflict that they will discover only at runtime. We can only pray their code is well covered by integration tests and that will be caught in advance.
Now, another scenario is user depends on service-manager v2 and then updates zend-feed to next major that dropped support for older SM version. Silent breakage again.
Declaring conflict is *not* an option since those optional dependencies might not be used together but conflict will impede the users ability to migrate their code at their own pace and to select dependencies they need for no good reason.

Each of those problems are small in isolation but they get hard to track when they start to pile up, especially when there are in excess of two hundred packages installed by the application. 

Is it really that complex to allow code that is already inspecting suggests to also compare them against installed versions?
```
$ composer require zendframework/zend-feed
Using version ^2.8 for zendframework/zend-feed
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing zendframework/zend-feed (2.8.0): Downloading (100%)
zendframework/zend-feed suggests installing zendframework/zend-servicemanager "^2.1|^3.0",
  4.0.0 installed (Zend\\ServiceManager component, for easily extending ExtensionManager
  implementations)
zendframework/zend-feed suggests installing zendframework/zend-cache (Zend\Cache component,
  for optionally caching feeds between requests)
zendframework/zend-feed suggests installing zendframework/zend-db (Zend\Db component, for use
  with PubSubHubbub)
Writing lock file
Generating autoload files
```

So as a user, what do i see here?
```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 updates, 0 removals
  - Updating zendframework/zend-servicemanager (3.3.1 => 4.0.0): Loading from cache
zendframework/zend-feed suggests installing zendframework/zend-servicemanager "^2.1|^3.0",
  4.0.0 installed
zendframework/zend-inputfilter suggests installing zendframework/zend-servicemanager "^3.1",
  4.0.0 installed
Writing lock file
Generating autoload files
```
I do not care about service manager in feed, but i use it in inputfilters. There is a new major release of input filter that works with new release of service manager, so lets migrate:
```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 2 updates, 0 removals
  - Updating zendframework/zend-inputfilter (2.7.5 => 3.0.0): Downloading (100%)
  - Updating zendframework/zend-servicemanager (3.3.1 => 4.0.0): Loading from cache
zendframework/zend-feed suggests installing zendframework/zend-servicemanager "^2.1|^3.0",
  4.0.0 installed
Writing lock file
Generating autoload files
```

**Comment by weierophinney** [comment]
I've read the above, and then clarified a bit with @Xerkus separately, and agree that `conflicts` will not always work in this situation. Let me see if I can provide a more succinct explanation.

Let's say we have a component named `acme/foo` that has two major versions, 1.0 and 2.0.

Now let's say we have another component, `emca/zoo`, which depends on `acme/foo` version 2.0.

Finally, let's say we have a component `acem/abba`, which has an _optional_ dependency on `acme/foo`, and has only been tested against version 1.0.

In your project, you depend on `emca/zoo` and `acem/abba`. In the case of `acem/abba`, you _are not using_ the integration with `acme/foo`, so there is no conflict _for your project's use cases_.

If `acem/abba` had a `conflicts` rule for `acme/foo:^2.0`, the project _would not be able to install `ecma/zoo`_, even though the project is not using `acme/foo` with `acem_abba`.

So, the feature request is for a way to warn users on installation that installation of a _suggested_ dependency _may_ cause problems due to version differences.

Does that makes sense, @Seldaek ?

**Comment by naderman** [comment]
What if you use mcae/foo which replaced acme/foo * but is compatible with acem/abba? "Optional dependencies" don't exist from composer's perspective because they are not defined in a way composer can see or work with, so I don't think this is something for Composer to deal with at all. You can maybe find some bandaid for one use case but it'll break down with the next, and may even result in incorrect output in some cases, so I'd much rather stick with the suggests we have now and leave it at that.

If you do want to use composer for these use cases the only way is to add additional metapackages in between, e.g. one that depends on acem/abba and acme/foo 1.0 and conflicts with acme/foo 2.0 and needs to be installed for acem/abba to use acme/foo - the typical bridge package.
