### ISSUE TITLE
"compose require foo/bar" ignores the existing constraints when selecting the default version

### ISSUE THREAD

**Issue by nicolas-grekas** [composer/composer#6869]
~~Variant 1: run `composer create-project symfony/skeleton` on PHP 7.0 => fails because it tells the skeleton "^4" needs 7.1 (but "^3" would be fine)~~

Variant 2: run:
- composer create-project symfony/skeleton demo ^3
- cd demo
- composer require symfony/var-dumper

Fails because composer select "^4" for the component, which conflicts with symfony/lts ^3 (but ^3 would be fine)

Saw this more that 10 times today (training session.)

**Comment by nicolas-grekas** [comment]
Se e.g. https://github.com/symfony/symfony/issues/25314 for a user report.

**Comment by curry684** [comment]
We've discussed this issue before, problem is that it's incredibly hard to solve. Only rock solid solution is to have an actual solver run with * as the package constraint, and then extract what it came up with. That would make it annoyingly slow, yet all other solutions would just be hacks with their own issues and edge cases.

**Comment by nicolas-grekas** [comment]
@curry684 sure. Yet I think we should try harder, this is hurting DX significantly.

A possible path for a fix could be to start with "*", then resolve the deps as done already, and patch the resulting composer.json to turn the "*" into a more tailored version constraint.

**Comment by curry684** [comment]
That's sort of what I was trying to type on my mobile yeah  :)

The problem is with reciprocality mainly. It's not that hard, when adding a new package, to check all currently installed packages for their dependencies, and simply walk down the possible versions of the new package to find one that doesn't violate constraints. This is *more or less* how the `why-not` command works. Except that that command inherently has the exact shortcoming that makes this issue so hard to solve as well - it cannot predict the other way around whether it's own (indirect) dependencies would cause a change in the existing installed packages, therefore invalidating the prime choice.

Like I said, there are some half-assed solutions that would make the current situation *slightly* better, but the only real solution is a full solver run based on `"new/package:*"`.

**Comment by nicolas-grekas** [comment]
FYI, Flex-based workaround here: https://github.com/symfony/flex/pull/231 (only fits `symfony/*` packages, not a generic solution.)

**Comment by nicolas-grekas** [comment]
Closing as we don't this need anymore and this is kinda edge-case.
