### ISSUE TITLE
Add version settings to `composer install` same as `composer require`

### ISSUE THREAD

**Issue by mindplay-dk** [composer/composer#6887]
With the `require` command you can install a specific version, e.g.:

    composer require phpunit/php-code-coverage:5.2.0

It would be nice if the `install` command supported the same, e.g. permitting you to override the current version in `composer.lock`, and update it, *without* affecting `composer.json` as `require` does.

My use-case: `phpunit/php-code-coverage` version 5.3 was released with a breaking change, and it's already listed in my `composer.lock` - I need to explicitly revert to version 5.2 and deploy a new `composer.lock` so I can get my build to complete.

My work-around: I use `require`, and then revert the change to `composer.json` afterwards.

Alternative work-around: add a `!5.3` constraint to my `composer.json` - but we have 20+ projects for which I'd have to do that - and there's no guarantee it'll be fixed in `5.3.1` or `5.4` etc.... We generally rely on `composer.lock` to ensure this sort of thing doesn't happen.

**Comment by Seldaek** [comment]
We don't really support "install" like npm does to install only a single package, you can only install all dependencies. Maybe `composer update foo/bar:1.2.3` could be a thing but it sounds like a slightly fringe use case really. You can as well update the composer.lock directly and programmatically on your 20 projects so that php-code-coverage 5.2 is in there and then on a composer install it'll get sorted.
