### ISSUE TITLE
'composer install' doesn't work, but only on first run

### ISSUE THREAD

**Issue by KamilKopaczyk** [composer/composer#6923]
Important note: it's only happening when GitHub token is not present in ~/.composer/config.json. It happened on our build machine, in docker container. After that i replicated it with native composer 1.5.5 on MacOS HighSierra.

My `composer.json`:

```json
[...]
"require": {
    "my/my-private-package": "^1.4"
},
"repositories": [
    {
      "type": "vcs",
      "url": "git@github.com:myorg/myrepo.git"
    }
]
[...]
```

When I run this command:

```
composer -vvv install -n
```

I get the following output:

```
Package operations: 0 installs, 2 updates, 0 removals
Updates: my/my-private-package:1.5.0, some/other:10.30.0
  - Updating my/my-private-package (1.4.0 => 1.5.0): Downloading https://api.github.com/repos/myorg/myrepo/zipball/<hash>
Downloading (failed)
Failed: [Composer\Downloader\TransportException] 404: The "https://api.github.com/repos/myorg/myrepo/zipball/<hash>" file could not be downloaded (HTTP/1.1 404 Not Found)


  [Composer\Downloader\TransportException]
  The "https://api.github.com/repos/myorg/myrepo/zipball/<hash>" file could not be downloaded (HTTP/1.1 404 Not Found)
```

And I expected this to happen:
Successful install

What's weird is that when i run `composer install` for the second time, it successfully installs this package from cache.
Here's the log fragment from second run:

```
  - Installing my/mypackage (1.5.0): Downloading https://api.github.com/repos/myorg/myrepo/zipball/<hash>
Downloading (failed)
Failed: [Composer\Downloader\TransportException] 404: The "https://api.github.com/repos/myorg/myrepo/zipball/<hash>" file could not be downloaded (HTTP/1.1 404 Not Found)
    Failed to download my/my-private-package from dist: The "https://api.github.com/repos/myorg/myrepo/zipball/<hash>" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing my/my-private-package (1.5.0): Executing command (CWD): git --version
```

I have logs from both command runs with -vvv switch. Let me know if you want me to send it.

**Comment by KamilKopaczyk** [comment]
I jumped to another repository that uses exactly same version of this lib and did `composer install -n` there too. I got the same result as before on first run. Library did install successfully on the second run though. I guess this eliminates potential cause of "losing authentication configuration between two installs".

The most annoying part of this "issue" is that i need to run `composer install -n` * (private libs to install) + 1 times.
Example first run:
Package operations: 7 installs, 2 updates, 0 removals
will result in following result from the second run:
Package operations: 8 installs, 1 updates, 0 removals

**Comment by Seldaek** [comment]
But do you have authentication configured now? It sounds like you don't.. but you had it when you initially installed these private packages. That's  what I mean by losing authentication between two installs.

**Comment by KamilKopaczyk** [comment]
I removed every occurrence of '*my-private-package*' in `~/.composer/cache` and run `composer install -n` again. Results are still the same.
Might be obvious, but just in case: after first run there are no cache entries for 'my-private-package' in `~/.composer/cache`.

I might be missing something, but shouldn't cache be independent of authentication data?

Let's say i don't want to use GitHub token anymore and only stick to SSH keys, but i did use it in the past. What would you suggest to do, to get rid of this problem entirely?

**Comment by Seldaek** [comment]
The cache has nothing to do with this. The thing is the first install as I wrote above removes the package from vendor directory and then it installs fine from clone. The solution is to remove the vendor directory and run `composer install -n` which will install everything again from dist OR source which will work. If you want to speed it up you could only delete `vendor/your-private-vendor/*` and also add `"config": {"preferred-install": { "yourvendor/*": "source" }}` in composer.json (see https://getcomposer.org/doc/06-config.md#preferred-install) so it will directly install those packages from source instead of attempting the zip download first every time. This will go faster and also won't require the `-n` to skip the auth prompt.

**Comment by msztolcman** [comment]
@Seldaek After removing `vendor` directory and run `composer install -n`, some other action is required? I am asking because it doesn't help, some time later (few install's later) there is same problem again.

**Comment by Seldaek** [comment]
@msztolcman what same problem? Have you defined preferred-install in composer.json as described in my post above?

**Comment by msztolcman** [comment]
@Seldaek Same = 404 when upgrading package. And no, I didn't, you described it as 'If you want to speed it up' - I understand this as an alternative to removing whole `vendor` directory. I'm incorrect? It should be both: removing whole `vendor` dir *and* adding these entries to `composer.json`? I am asking because it's sometimes hard to reproduce, so I cannot test this easily.

**Comment by Seldaek** [comment]
No if you remove whole vendor it should be fine.. Anyway the best way to fix this is to add a github oauth token so that you can download repositories without 404s really.

**Comment by msztolcman** [comment]
@Seldaek I don't want to use github token, I need to access github using ssh keys.

I've also added `"no-api": true` to all repositories definitions, but this doesn't help too (some hint from deep internet ;) ). Have you any other idea how to fix this? Currently it's really annoying to repeat every install/update (sometimes few times, if there is a service with many external packages).

**Comment by msztolcman** [comment]
BTW, I'm curious: is this problem related only to github? Will it work better with other git repository?

**Comment by Seldaek** [comment]
The problem is the githubdriver assumes you want github URLs.. zip files install way faster than clones so for 99% of people it's the right thing to do. If you don't want this at all, then specify `git` as repository type instead of `vcs`, so that will use the raw git driver which won't add any dist info to the package.

**Comment by msztolcman** [comment]
Hi @Seldaek, thanks for the tip, I'll try this :)
