### ISSUE TITLE
Memory requirements becomes way too demanding

### ISSUE THREAD

**Issue by taleteller** [composer/composer#6962]
I am at updating an composer installation (version 1.5.6) embedded in a Contao CMS and this process requires now **2GB of RAM**. This is for just 50 dependencies. About last year the suggestion was to set memory_limit to 512MB, some before 256MB was suggested, now its -1. 

Its an alarming rate, the memory demand keeps growing and at the given rate it will surpass most hosted webspaces pretty soon. I like to remind that composer is included in CMS systems like Drupal and Contao. Those are often installed to shared webspace hosts, without access to shell and hard limited memory availability. 

This is an issue that needs to be resolved before it run entirely out of hand.

**Comment by curry684** [comment]
On shared webspace hosts you should run install instead of update, which barely uses RAM.

Only update uses a lot of RAM for the SAT graph, but that should only ever be run on a developer machine. If you use a dev machine with less than 8GB of RAM you need a new one.

**Comment by taleteller** [comment]
This is not a solution, its a workaround. Composer is increasingly used in CMS, those systems are meant to work out of the box. Plenty of small sites use them, and they don't have development copies, since nobody would pay the costs to sync them up. Besides it contradicts the advantages of CMS and packaging a little, by preventing updates from bricking your site by allowing easy rollbacks.

For example nobody would expect an ``apt-get update`` to fail on a Raspberry Pi due to low memory and suggest to copy the package database from similar hardware.

**Comment by curry684** [comment]
It's a solution because doing it otherwise [is plain wrong](https://getcomposer.org/doc/01-basic-usage.md#installing-with-composer-lock).

`apt-get update` gets the dependencies you require on your specific system. `composer update` gets the dependencies for your specific project you're developing. `composer install` retrieves the *exact set of dependencies* you developed and tested on. Running `composer update` on prod or staging breaks [dev/prod parity](https://12factor.net/dev-prod-parity).

**Comment by Seldaek** [comment]
It's a known issue and something we will work on when time allows but for now closing this as this adds no value to the issue tracker.
