### ISSUE TITLE
Unable to install library because dev dependencies are conflicting

### ISSUE THREAD

**Issue by mxr576** [composer/composer#7022]
Am I the only one who is starting to see automatic installation of dev dependencies a huge problem? I am working with Drupal 8 (8.4 and 8.5-dev) which still requires PHPUnit 4.8 a dev dependency *only*. My module has an external library dependency that requires PHPUnit >= 6.2 *only* as a dev dependency.
Even if I run `composer create-project --no-interaction --prefer-dist --no-dev drupal/drupal /var/www/html` to get rid of Drupal's PHPUnit, I am still unable to install my module with `composer require my/awesome-module`, because its dependency conflicts with Drupal's has not been installed dev *only* dependency.
This seems illogical to me, because I do not need that library's PHPUnit in my project. What I need is to be able to install my module and run PHPunit tests on that by using Drupal's minimum requirements.

Of course this is not all about PHPUnit, this type of conflict could happen between any dev requirements of two libraries.

Composer version 1.5.5

**Comment by curry684** [comment]
I don't understand your issue, because the example simply violates how Composer works.

Dev dependencies are *only ever evaluated for the root package*. Never, in any situation whatsoever, will the dev dependencies of included projects be considered or expanded. It is true that there is the 'loophole' of dev dependencies **always** being considered for the root project. This is simply because they may introduce limiting constraints that would, if not done like this, cause a different solution to be installed for dev and no-dev installations, [violating the principle requirement of dev/prod parity](https://12factor.net/dev-prod-parity).

From what you describe however that's not even what is happening - if your `composer update` hits a conflict in `phpunit/phpunit` it can only mean that one of your dependencies is listing it *as a non-dev dependency*. Otherwise it is never loaded, and thus cannot conflict. Meaning your issue cannot exist unless an included library is explicitly misbehaving.

Please post some output and relevant `composer.json` snippets of your use case so we can look into the case, but I'm very sure the issue you describe is not the root cause.

**Comment by mxr576** [comment]
Sorry, you are right. I was to tired last night after hours of debugging to see that I have took a wrong direction to solving this problem. This morning I have started from scratch to see where this process fails.

So it seems Drupal 8.4 installs `phpdocumentor/reflection-docblock 2.0.4` out of the box as a dependency of PHPUnit 4.8. The library requires `"symfony/property-info": "^3.2 || ^4.0"` which is in conflict with the installed phpdocumentor/reflection-docblock version so it has to be updated to `phpdocumentor/reflection-docblock:^3.0.2` to be able install the library, the dependency of my module.

So the only conclusion is that my module is not compatible with a Drupal 8.4 `--prefer-lowest` installation.

Also, this is still something that would have been solved more easily with better conflict messages, #6691.

```json
{
    "name": "drupal/awesome-module",
    "type": "drupal-module",
    "description": "My awesome moule.",
    "require": {
        "php": ">=7.1",
        "drupal/core": "^8.4",
        "my/awesome-library": "*"
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

```json
{
    "name": "my/awesome-library",
    "type": "library",
    "description": "This is my awesome library.",
    "require": {
        "php": "^7.1",
        "symfony/property-info": "^3.2 || ^4.0"
  	},
    "require-dev": {
         "phpunit/phpunit": "^6.1"
     }
}
```
```Dockerfile
FROM wodby/drupal-php:7.1

RUN composer global require "hirak/prestissimo:^0.3"

RUN composer create-project --no-interaction --prefer-dist drupal/drupal /var/www/html

RUN composer why -r -t phpdocumentor/reflection-docblock

# Or composer require phpdocumentor/reflection-docblock:^3.0.2
RUN composer update -o --with-dependencies

RUN composer show

COPY --chown=www-data:www-data . "${WODBY_DIR_FILES}/composer"

RUN composer config repositories.library path "${WODBY_DIR_FILES}/composer/library" \
	&& composer config repositories.module path "${WODBY_DIR_FILES}/composer/module" \
    && composer require --update-no-dev drupal/awesome-module
```

**Comment by curry684** [comment]
That complaint is understandable and even "known", the problem is that the underlying SAT solver implicitly does not provide really user-friendly output. Good thing is it usually doesn't matter since it usually succeeds   ;)
