### ISSUE TITLE
Replace remote file_get_contents() calls with cURL

### ISSUE THREAD

**Issue by gergoerdosi** [composer/composer#704]
I found two places in the code where file_get_contents() is used with remote URLs. These are:
- Composer\Repository\ComposerRepository:: notifyInstall()
- Composer\Util\RemoteFilesystem::get()

On many servers allow_url_fopen is disabled for security reasons. A solution could be to replace these file_get_contents() calls with cURL. This would make cURL as a requirement, but most of the servers have it installed.

**Comment by karser** [comment]
I encountered the same issue.
The problem was in my CLI php.ini, option default_socket_timeout = -1.
I changed it to default value (60) and it works now.

**Comment by digitalkaoz** [comment]
i would vote for `egeloen/http-adapter` which handles all that and can guess the most suitable driver

**Comment by khaefeli** [comment]
+1

**Comment by passioncoder** [comment]
3 years (and 2 PRs) later, allow_url_fopen is still a bad practise. 

+1 for a cURL option.

**Comment by snetty** [comment]
yup, still can't use it on my live environment, no choice but to commit everything to repo just because composer devs cba to merge in a PR.

**Comment by pmlt** [comment]
+1 for this fix. We are using a CI tool to package our dependencies and we are not willing to enable allow_url_fopen on that server. It is indeed bad practice. Is there an ETA for this fix? It seems to be a rather trivial change no?

**Comment by Seldaek** [comment]
It's not quite trivial no as we do support quite a lot of things on the download level, and file_get_contents works everywhere (unless you disable it) while curl is hardly enabled everywhere. We'll get there eventually I am sure but in the meantime I'd suggest you run composer with allow_url_fopen enabled, you don't have to enable it for the whole server mind you you can just invoke `php -d allow_url_fopen=1 composer install` or such.

**Comment by vBZachery** [comment]
cURL is considerably more ubiquitous than allow_url_fopen being enabled in webhosting environments, especially when it comes to shared hosting. This is based on nearly 11 years of supporting a major PHP software package (vBulletin).

There isn't a good reason not to have cURL as an option, and still fall back to file_get_contents as a backup.

**Comment by maxiwheat** [comment]
+1 on this one, `allow_url_fopen`is disabled here for security reasons. Would be great for composer to support `curl` and `file_get_contents`

**Comment by DIOHz0r** [comment]
is this still on a pr?. I'm in a hosting server with allow_url_fopen disabled and I can't edit it 
:(

**Comment by siteleas** [comment]
@Seldaek Hey Jordi, I presume the reason that there has been no movement on this oft requested issue is that you think that it is silly to offer a curl alternative for people who have no ability to alter their server's php.ini settings? Just wondering as this problem is a game stopper for shared server users all over the place who are in a situation where their hosting company made a security call and disabled allow_url_fopen. Please let everyone know your thoughts on whether they can expect forward motion on this issue or whether you think it's a no go. At least then people will not be waiting with baited breath for an answer to this problem for four more years.

**Comment by avindra** [comment]
Besides shared hosting, my company decided to enforce this policy for 'security reasons.' I disagree that it causes any security holes, but from an coding perspective, it does seem messy to be that you can do an fopen on a url. It seems like one of those things that PHP banged together to make things easier, but ends up causing more of a mess.

Regardless of opinions about `allow_url_fopen`, the fact remains that a lot of people are encountering this issue... would nice to bump this out of the "Nice to Have" category.

**Comment by siteleas** [comment]
@avindra Agreed. It's definitely far more than nice to have.

**Comment by siteleas** [comment]
I found this:

$ php -d allow_url_fopen=on /usr/local/bin/composer install

It's a way of launching composer if the php.ini file isn't set right, but it will not work for everyone (hope it helps some).

**Comment by Seldaek** [comment]
There are possible workarounds for this as highlighted in the post just above mine, but the bottom line is that yes we will probably support it at some point, but it requires quite heavy changes to very sensitive bits of the code that are unfortunately not fully tested as testing network interactions is quite a pain. So while we already have a couple pull request that implement this, reviewing them is practically impossible and I'd rather do the changes myself or at least play with the patches for a bit to be familiar with them and make sure there are no more regressions than needed. So yeah, I know it's annoying for a few people out there, but the bottom line is it's rarely if ever a show-stopped as you can also deploy without running composer on the server itself. Thus I hope we can all have some more patience here :)

**Comment by siteleas** [comment]
@Seldaek Thanks for all your efforts and hard work!

**Comment by luceos** [comment]
@Seldaek allow_url_fopen has been disabled globally by default on every cpanel based server. Now that in PHP 7+ that directive has become `PHP_INI_SYSTEM`, one cannot use ini_set anymore to override the directive. Meaning that separate websites on shared environments will no longer be able to use composer.

I'm aware this is not entirely your/our problem, but it does block out a terrifying number of people from using composer.

---

references:

- https://forums.cpanel.net/threads/php-ini-directives-not-working-properly.614379/#post-2494067
- http://php.net/manual/en/filesystem.configuration.php

**Comment by jduartedj** [comment]
My company policy alone blocks the use of allow_url_fopen, but Curl is allowed. To explain without getting in too much detail fopen is a fucntion used in a wide variety of scenarios some of which could be hacked into using a url instead of a file name if the context isn't expecting it to whilst curl is always expecting a url so whener anyone uses curl he/she is completely aware of the consequences that might have.

**Comment by geniuswebtools** [comment]
The problem is that composer expects to be run from the CLI version of PHP.  The CLI runs off of the root level php.ini, which those of us with shared hosting can't modify.

After a chat w/ my hosting support and 5 hours of frustration, I found a working solution.

Using the MultiPHP INI Editor installed on cPanel instance, I can enable allow_url_fopen for my hosting account, but composer ignores it because it's not reading the php.ini from my hosting account, but the path where PHP was installed at the root level on the server.

Making sure my composer binary is in the public_html/ folder I can execute composer from the command line using the PHP cgi-fcgi SAPI interpreter, and it works as expected, but it does complain.

> Warning: Composer should be invoked via the CLI version of PHP, not the cgi-fcgi SAPI

My opinion is that if the PHP libs being required don't require root permissions, then composer shouldn't either.  

The only thing I've found more frustrating that PHP libs requiring the use of composer to be installed, is actually trying to install composer so I can get to work.

**Comment by glensc** [comment]
the original security implications noted by include of urls was mitigated in php 5.2.0, by splitting the functionality to two options, having url include off by default:

- allow_url_fopen=1, 
- allow_url_include=0

see:
- https://www.php.net/manual/en/filesystem.configuration.php

[5.2.0](https://www.php.net/releases/5_2_0.php) was released on [02 Nov 2006](https://www.php.net/releases/index.php#5.2.0)

**Comment by Seldaek** [comment]
Fixed by #7904 for 2.0
