### ISSUE TITLE
Package Not Found Even Though It Is In Suggest

### ISSUE THREAD

**Issue by Jafo232** [composer/composer#7044]
When you try to install this package using composer  version 1.6.2:

https://packagist.org/packages/jafo232/ambientapi

As described by packagist:

`composer require jafo232/ambientapi`

It always returns:

> [InvalidArgumentException]
>   Could not find package jafo232/ambientapi.
> 
>   Did you mean this?
>       jafo232/ambientapi

This has been going on for about 12 hours now.

**Comment by xabbuh** [comment]
The issue is that there is not stable release for the package. You can work around this passing the desired stability for this package when requiring it like this:

```
composer require jafo232/ambientapi:@dev
```

**Comment by socialknowledge** [comment]
Hmm, I added tags:

> git tag -a 1.00

And pushed the tags, but still get this message, even after a manual update at packagist?

**Comment by Jafo232** [comment]
Hmm, I added tags:

    git tag -a 1.00

And pushed the tags, but still get this message, even after a manual update at packagist?

**Comment by Jafo232** [comment]
Must be a cache issue.  It is working now.  Thanks so much for your help!

**Comment by stof** [comment]
Packagist has a small delay between the time I learns about the update (and makes it visible in the web interface) and the time Composer can knows about it. This is because the data that Composer is loading comes from static files generated by a cron running every few minutes, not from a request hitting a Symfony controller to generate them on the fly (which would be impossible from a performance PoV due to the size of the Packagist data).

**Comment by Seldaek** [comment]
Glad you got it sorted but still sounds like we should improve the message in this case if possible as it's kinda weird the way it's output right now.
