### ISSUE TITLE
Need more details about exclude-from-classmap usage

### ISSUE THREAD

**Issue by webmake** [composer/composer#7076]
Hello,
I would like to know more about `exclude-from-classmap` use cases.

Recently I have noticed, that my file had wrong namespace, but still was correctly loaded, that was weird.

`namespace Modules\Http\Handlers` but the file was under `Modules/X/Http/Handlers` folder. So I made some debugging stuff, and found out that composer itself trying to remap those files https://github.com/composer/composer/blob/master/src/Composer/Autoload/ClassMapGenerator.php#L127 into classmap.

So in my case to avoid such situation, by adding `exclude-from-classmap` attribute shown me the error, that class not found (as I was expected at very begining).
```json
    "autoload": {
        "exclude-from-classmap": [
            "/Modules/"
        ],
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/",
            "Modules\\": "Modules/"
        }
    },
```

Question is, is this good practise knowing that `Modules` directory files keep `psr-4` standard, so to prevent from any typos, to do exclusion of that directory from been taken over by classmap? Or is this not a purpose of that feature?

**Comment by tomzx** [comment]
For PSR-4 autoloaded classes, no class map is built. Thus, when you attempt to resolve a class, it will try to map the namespace to the directory layout.

Thus, as long as your file was in `Modules/X/Http/Handlers`, it will be loaded, but it may not be loaded in the appropriate namespace since composer doesn't care about that. You could have declared the namespace to be `namespace MyBanana;`, composer would not test the class was loaded in the expected namespace, it will just take care of including the file.

**Comment by webmake** [comment]
Actually class map is built. Here is the part of `autoload_classmap.php` file:
`'Modules\\Http\\Handlers\\Request.php' => $baseDir . '/Modules/X/Http/Handlers/Request.php',`

I perform `composer dump` command, maybe this is the problem why classmap gerenerated, but I don't believe in this, because as from code is seen, only [blacklist](https://github.com/composer/composer/blob/master/src/Composer/Autoload/ClassMapGenerator.php#L94) prevents from further code execution which is responsible for classmap.

**Comment by tomzx** [comment]
First, `'Modules\\Http\\Handlers\\Request.php'` should not be in your class map as it is an array of `fully qualified class name => file` mapping, and you have a `.php` in the name of your class in your example, which is not valid PHP.

Second, if this file ends up in your `autoload_classmap.php`, then it has to be listed in your `classmap` property, as classes part of the PSR-4 property will not generate entries in that file. I would suggest you delete the `vendor/composer` directory and rerun composer dump.

If you still get the same result, I'd be interested to see the files in the directory. If you can create a zip file of your current case, we will be able to better look into this issue.

**Comment by jvasseur** [comment]
This is due to the `optimize-autoloader` option (https://github.com/webmake/composer-sample/blob/master/composer.json#L56) that tels composer to optimize the autoloader by including any ps0 and psr4 autoload config into the classmap for faster autoloading.

**Comment by webmake** [comment]
Thanks @jvasseur , now it makes sense, didn't even noticed, that other configuration can cause this.

So basically `optimize-autoloader` collides with `psr-4` rule then, because optimize command doesn't respect `psr-4`?

**Comment by jvasseur** [comment]
`optimize-autoloader` basically adds all `psr-0` and `psr-4` paths as `classmap` paths.

It's true it doesn't respect folder structure when searching classes. It's a setting mostly destined for production environment (where autoloading speed matters) so not respecting folder structure is less important since such errors would have been catched in development environments.
