### ISSUE TITLE
Return latest package version ignoring semantic versioning constraints

### ISSUE THREAD

**Issue by tomzx** [composer/composer#7094]
Given a `composer.json` file, I would like to be able to tell what is the latest version available for the packages I depend upon, ignoring semantic versioning constraints.

Currently the `composer outdated` command will respect the constraints specified within the file.

In this case, we are interested to know which packages may have new major releases available in order to plan for code maintenance.

This feature could be done by taking all the current `require` dependencies and replacing the constraints with `*`.

**Comment by curry684** [comment]
The `outdated` command actually works like you describe. It lists all packages that can be upgraded, including major releases, with color coded version strings: red will be applied with a `composer update`, yellow is being blocked by SemVer constraints. You'd have to pass the `-m` flag to get the behavior you're describing.

The only constraints that it always respects are platform requirements. For example if you are running PHP 7.0 or have a `config/platform/php` key that states a 7.0.x version it will never suggest an upgrade to Symfony 4.0 because it is impossible to execute in the current environment.

**Comment by tomzx** [comment]
@curry684 I see, the `config/platform/key` constraint was indeed the reason why it seemed to limit to how high it would suggest the upgrades.

Thanks!
