### ISSUE TITLE
I would like to know more about composer remove?

### ISSUE THREAD

**Issue by zomorod** [composer/composer#7177]
Here is my scenario,
I manually created a composer.json.
This is the first time and I should run ```composer install``` but I ran ```composer remove project```.
When I ran ```composer remove``` to remove a project from my .json file I noticed composer started to install projects and then remove that project.

In this case should I ran composer install again? Why ```composer remove``` installing other projects? Can you please explain what is going on when we ran ```composer remove``` ?

I am trying to write an automation for running several command. I have memory issue on my server and I am trying to avoid running composer on my server that is why I need to know more what is going on.

**Comment by stof** [comment]
Well, `composer remove` performs 2 things by default:

- it removes the package from the composer.json
- it performs a partial update whitelisting the removed package (and its dependencies), to generate the new list of dependencies and have the right content in the vendor folder

If your vendor folder is not populated yet, the partial update will also install any package of your lock file which is missing (so that your vendor folder is in a consistent state at the end of the command).

Note that you can use `composer remove --no-update` if you want to perform only the first step (editing the composer.json)

**Comment by zomorod** [comment]
Great @stof Thank you!
