### ISSUE TITLE
Generate both unix and windows version of binaries on all systems

### ISSUE THREAD

**Issue by tomasfejfar** [composer/composer#7370]
This would ideally be default, but having at least an option would be nice. 

**Why?**
Docker. 

* You have your local (windows) directory mounted. 
* You run `composer update` inside docker (because it must run against docker's php and ext versions)  -> thus only unix binaries are created in `vendor/bin`
* For local tools (PhpStorm for example) you need to set up phpcs.bat (as it's running in Windows context)

**Current workaround:**
* set up platform in composer.json and run from windows
* generate/copy bat files from other projects

**BC breaks**
I don't think this will cause any BC breaks. It's practically a new feature. Only BC would be if someone depended on the fact that there are only linux executables in the `vendor/bin` directory in linux.

**Comment by Seldaek** [comment]
See https://getcomposer.org/doc/06-config.md#bin-compat

I'd recommend running `composer config -g bin-compat full` in your docker container, or setting `COMPOSER_BIN_COMPAT=full` in the env. You'll then get .bat files created.

**Comment by tomasfejfar** [comment]
Thanks, I'll make sure to read the whole "config" page.

**Comment by b-hayes** [comment]
Yeah this is really frustrating especially since doing a composer install on both the docker container and in windows power-shell does not generate the bat files either.

I have to delete the vendor folder and then run the install again in a windows command prompt.

This really should be at least a global setting "always give me all bin files" and this should be the default option when installed on windows since most lamp stack devs use php composer and in turn if they're on windows will need to use both because they will more than likely use composer from a posix emulator or wsl or msys and then have an IDE running natively looking for bat files.


Making it a global default would probably be better than detecting wsl or msys either (witch is also rpety easy to do) or some posix emulation.
