### ISSUE TITLE
composer archive crashes on bad line in .gitignore file

### ISSUE THREAD

**Issue by mborne** [composer/composer#7440]
Hello,

I have a full `satis build` generation that is interrupted with a `preg_match(): Compilation failed: missing ) at offset 24` when `composer archive` is invoked on a specific project tag.

It seams that `composer archive` crashes in archive generation when `.gitignore` contains strange lines.

For example, `/${ctx` will lead to the following invocation in https://github.com/composer/composer/blob/1.6.5/src/Composer/Package/Archiver/BaseExcludeFilter.php#L62 : 

```php
preg_match('{^/(?=[^\.])\$(ctx(?=$|/)}','/CHANGELOG.md')
// => preg_match(): Compilation failed: missing ) at offset 24
```

Would it be possible to validate `$pattern` and ignore invalid ones? 

PS : 
- I don't know if I have to make a pull request on composer or on satis to have this included in `--skip-errors`
- Sorry for not respecting the issue template, you'll find a minimal repository to reproduce here : https://github.com/mborne/crash-composer-archive#crash-composer-archive

**Comment by Seldaek** [comment]
Not sure if this is a bug in Composer or `Finder\Glob::toRegex` or just a borked .gitignore rule that should have no place being there in the first place, but if someone can fix it I guess why not. Doesn't seem very high prio though.

**Comment by jrfnl** [comment]
I've had a look at this issue and my conclusion would be that it is a borked `.gitignore` rule that should have no place being there in the first place.

The test case graciously provided by @mborne shows that the issue is still reproducible on the current `master`.

The only adjustment to `Finder\Glob::toRegex` which could be made IMO, would be a check that any opening brace also has a close brace and if not, escape the brace instead of changing it.
Aside from the fact that that check would be quite complicated as it would need to account for already escaped braces, I'm not sure that the method _should_ account for invalid glob patterns.

As for Composer, a simple solution could be to prefix the filter `preg_match()` with the error silencing operator.
`preg_match()` would return `false` anyway, so the value of `$exclude` would not be changed and the `tar` file would be created as expected.

https://github.com/composer/composer/blob/af677553cce0967bf7c364d64a9a169152c33fcd/src/Composer/Package/Archiver/BaseExcludeFilter.php#L62
