### ISSUE TITLE
Adding a new argument to ignore an non-empty directory when creating a new project

### ISSUE THREAD

**Issue by khalyomede** [composer/composer#7455]
This could be useful for example when we have a minimal directory with some files (like UML diagrams, firebase configurations, ...).

I see something like `composer create-project laravel/laravel:5.6.* --ignore-non-empty-directory .`, assuming we run this command in the `/home/me/php/my-project` folder.

**Comment by alcohol** [comment]
`create-project` is basically a shortcut for:

```
git clone <project-repo> <target-dir>
cd <target-dir>
composer install
```

And git does not really like cloning into a non-empty directory as that can present conflicts with files you are going to be checking out and files that already exist on disk.

**Comment by khalyomede** [comment]
@Paulmicha I think systematically checkout to master branch will not work, for example in the case you are requiring a prior version of the project you want to install (like laravel 5.6, which has of today is on version 6.0).

I guess, as it is a git issue, this has nothing to do with composer. 

Maybe an optional way could be:

1. Move existing files into the temporary folder of the OS (/tmp for Linux), into a known folder, let us say "temp-1"
2. Use the regular `composer create-project`
3. Move back the copied files from "/tmp/temp-1" to the folder where composer installed the project, let it collapse as normal
4. Remove the temporary folder "/tmp/temp-1"

(maybe you will want to first check if "/tmp/temp-1" does not exists before, voluntarily simplified here).

**Comment by stof** [comment]
@alcohol to be exact, it is more something like this:

```
git clone <project-repo> <target-dir>
cd <target-dir>
git checkout <selected-version>
composer install
rm -rf .git # skipped if using --keep-vcs
```

Except that internally, it may change the way things are actually installed (it might download an archive rather than cloning from source, and it also supports any source install supported by Composer, not only git). And so any merging implementation becomes a lot more complex because it needs to work for all these cases.

IMO, trying to do this would add unnecessary complexity to composer. the strategy suggested in https://github.com/composer/composer/issues/7455#issuecomment-536898586 can be implemented as a wrapper script.
