### ISSUE TITLE
Gitlab API v4

### ISSUE THREAD

**Issue by Stijn98s** [composer/composer#7520]
i have added a gitlab repository but the api is outdated. he is downloading file from url '/api/v4/projects/{namepace}/{projectname}' but the gitlab api cant get a response because the api changed for '/api/v4/projects/{projectid}' 

relevant parts of my composer.json

"repositories": [{     
        "type": "gitlab",
        "url": "https://gitlab.local/group/repository.git"
 }],

"config": {
        "gitlab-domains": [ "gitlab.local" ]
}

**Comment by alcohol** [comment]
I don't think we support their new API yet, and it seems their old API is no longer supported.

It looks like we need to use a project ID now (integer), and we will probably need to look that up in their API first based on the user name and repository name we have. This is no small task unfortunately (though not extremely large either). But very few of us actually use Gitlab.

**Comment by Wirone** [comment]
@Stijn98s maybe it's not an API client problem but your server configuration? We had some problems with decoding `/` in URLs (branches like `feature/something`), maybe your `{namepace}/{projectname}` should be in fact `{namepace}%2F{projectname}` with soft `/`? Take a look [here](https://gitlab.com/gitlab-org/gitlab-recipes/blob/master/web-server/apache/gitlab-ssl-apache24.conf#L46).

Because I've used API v4 yesterday in order to store dist URLs in Satis and it worked with `gitlab` type in `satis.json`.

**Comment by Wirone** [comment]
@Stijn98s I don't think it has changed because API documentation states that `:id` part is "The ID **or URL-encoded path of the project**" (which is `path_with_namespace` from the response) and this is what I said before - it must be URL-encoded, so `%2F` is used instead of `/`. Also it has to be supported by your proxy, so Gitlab gets non-decoded `:id`, otherwise it fails.

We use Gitlab 11.0.1 and I really doubt they change this resource in BC-manner between this version and 11.1.4 you're using :)

**Comment by Stijn98s** [comment]
@Wirone You where right. didnt read further than the first line. I have got it working. I got a reverse proxy to my gitlab instance. i have added the nocanon option to ProxyPass.

**Comment by Seldaek** [comment]
Ok then this can be closed I believe

**Comment by curry684** [comment]
> it seems their old API is no longer supported.

Its deprecation was announced in [February 2017](https://about.gitlab.com/2017/02/22/gitlab-8-17-released/#api-v3-deprecation) and the v3 API was definitively removed in 11.0, released June 22nd this year.

> very few of us actually use Gitlab.

My company actually runs entirely on a private GitLab instance, but we don't use the GitLab driver as we deploy the few private libraries we have with Satis through the standard Git driver. I've never seen any reason or added value to using the GitLab drivers.

I *can* however of course test/debug stuff if we have reproducible issues   :)

**Comment by alcohol** [comment]
It seems the limited functionality we used from the API is still supported. Too much documentation to read and too little familiarity with our own code, I drew the wrong conclusion. I think there is no issue in the end :-)
