### ISSUE TITLE
Refresh lock file instead of updating?

### ISSUE THREAD

**Issue by EvanK** [composer/composer#754]
My peers & I are constantly getting the following warnings from Composer:

```
BC warning: your lock file appears to be of an older format than this composer version, it is recommended to run composer update
Installing dependencies from lock file
Your lock file is out of sync with your composer.json, run "composer.phar update" to update dependencies
```

Our issue is, `composer update` will not just rewrite the lock file format, it will update _all_ versions of our dependencies. This is a problem for us because, for reasons I'd rather not go into (long story), we _must_ keep using specific versions of certain dependencies...which is why we're using a lock file to begin with.

It would be useful to have a way to update just the lock file to a newer format, while maintaining the same dependency versions. Perhaps a `composer refresh` command or something similar?

**Comment by njt1982** [comment]
There is also now this:

```
      --lock                     Only updates the lock file hash to suppress warning about the lock file being out of date.
```

(for those who end up here from Google)

**Comment by chrisyue** [comment]
I tried `--lock` option, but still get vendor libs updated

**Comment by HaykoKoryun** [comment]
same as @chrisyue here, `nothing` or `--lock` ends up trying to resolve dependencies instead of just updating the hash.

Running version: `98b0af1386f7ff730c3330e2525c1d66998c7f90`

**Comment by lifehome** [comment]
Can someone reopen this issue? I'm running into the same situation... D:

**Comment by meglio** [comment]
I would also like a solution to updating lock file only without resolving dependencies.

**Comment by stof** [comment]
Checking that the locked dependencies are compatible with the updated composer.json is important. Updating only the hash without checking what is in the lock file would be bad, as Composer would think that the lock file is uptodate while it is actually in a broken state.

A ``composer update --lock`` will make changes in your vendor dir only if what is installed currently does not match what is requested by the lock file (i.e. your local install is not uptodate)

**Comment by rmblstrp** [comment]
I find the issue arises when you have a team working on the same project and one or more people add packages. The the lock file gets merged the hash no longer is no longer valid. It would be helpful to at least have the ability to regenerate the hash for the lock file.

**Comment by HaykoKoryun** [comment]
@stof I get that, however in one of our projects we have 65 dependencies, a mixture of composer and bower packages, some of which are _external_ libraries like yii2 and others which are _internal_.

As some of the internal libraries change frequently we have to update `composer.json` and `composer.lock` every time we need the latest version.  Since the changes are known, for example the only diff is in the code in the library itself and not in any of its own dependencies, all that is required is to change the version number and reference hash in `composer.lock` and run `composer install`. This works really fast compared to updating, as the latter would require composer to look at all the dependencies of the 65 dependencies unnecessarily. A manual override is what is needed here. For example,  the install takes a few seconds, whereas the update takes longer than making coffee and getting a snack from the vending machine and we don't need those kind of excuses :stuck_out_tongue:

**Comment by slbmeh** [comment]
@HaykoKoryun you can use the `--root-reqs` flag to only consider the packages in the root composer.json.  I generally recommend that you use whitelists whenever possible... `composer update my/package` or `composer update 'mycompany/*'`, this also allows for the dependencies of the whitelist to be considered when needed with the `--with-dependencies` flag.

**Comment by alakhdeveloper** [comment]
Hello,

with composer the php and phtml file have to put in local directory to auto-overwrite. that fine, but how to unlock or add symlinks for js file? Please help.

Js didnt have any local directory to overwrite, so where i have to put js file which is locked by composer?

**Comment by dustyghost** [comment]
A workflow I was hoping for:
Branch A = working branch happy days, composer.json and .lock are working and in sync.
Branch B = very old branch, but has packages needed to make it work, not in branch A.
The goal, bring branch B up to date with the latest branch A changes. 

I update to a branch A. I composer install. This get's all the packages I need from branch A in the vendor folder. 

I then update to branch B, attempted to merge A into B, get a merge conflict on .json and .lock.
Manually fix merge conflict on .json, make sure that the composer.json is up to date with the versions from branch A, and include the new packages from branch B.

What I was then hoping for was a way to run either install or update, that could rebuild the .lock and would keep the versions of the packages in the vendor folder already (remember this was installed from branch a), and then update or install the new packages from branch B.

**Comment by curry684** [comment]
First of all you should *never use* commit pinning. You're kicking a 5 year old issue here, from the first early days of Composer, and commit pinning is currently explicitly considered bad practice, and even explicitly not supported by the Composer team.

Secondly I'd venture to say your expectations are flawed. You're more or less expecting to upgrade Windows 7 to act like Windows 10 by copying half the `system32` folder from a Windows 10 machine. Project dependencies are an atomic part of the code base, and therefore branch, they reside in, and should never be merged. This is even one of the core reasons why Composer checks lockfile validity and integrity by hashing the definition file that it originated from.

In the end the approach you're trying to follow will causes more issues than it solves, because you're merging incompatible codebases with incompatible dependencies. The end result will crash at best, or behave erratically at worst. Upgrading code has to be done right - pick the code you're trying to backmerge, carefully reconstruct your dependencies, do a full `composer update`, and test test test. All other approaches will be highly volatile and prone to failure. And therefore not supported by Composer.

**Comment by dustyghost** [comment]
Yep, your points are valid. We resorted to composer update, and testing is always our priority. thank you for your reply.

**Comment by realmocaccino** [comment]
Not valid imo. It should be a way to solve this problem.

**Comment by realmocaccino** [comment]
Not valid imo. There should be a way to solve this problem.
