### ISSUE TITLE
Leading slash == class not found

### ISSUE THREAD

**Issue by VijitCoder** [composer/composer#7540]
Composer ver. 1.6.5 (2018-05-04)

Public method `\Composer\Autoload\ClassLoader::findFile()` can't find the class with leading slash. That's it, just a slash. The previous version could handle it.

I don't know, is it a bug or a feature. In my engine I fixed this children's mistake with:

```php
...
$className = ltrim($className, '\\');
$composer->findFile($className);
...
```

**Comment by Seldaek** [comment]
We used to handle it due to some early PHP5.3 bug but this was abandoned quite a while ago in 2853e82400a113620e05504c52729c61b5a53f77 - If you must handle leading slashes then trimming yourself is the better solution. This is not something we will handle as it degrades autoloading performance for everyone.

**Comment by VijitCoder** [comment]
It reproduced in PHP 7.2 and in the newest Composer only. I believe, this is a new problem. But if don't think so - ok.

**Comment by Seldaek** [comment]
Php never calls the autoloader with a leading backslash so it's not a
problem. if you call it by hand then you have to ensure you also don't have
a leading slash to avoid issues.

>

**Comment by VijitCoder** [comment]
Ok, I got it. Thanks.
