### ISSUE TITLE
Reconsider recommendation to not commit vendor

### ISSUE THREAD

**Issue by devsnacks** [composer/composer#7559]
The [general recommendation](https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md) is to not commit the dependencies in the vendor directory. 

**My proposal is to withdraw this general recommendation and instead, give a more comprehensive explanation about the different use cases and pros and cons of each approach.**

The reasons given are very valid in a **distribution** context. 
Use case: I want to share a library others can use.

In a **deployment** context there may be several disadvantages in not committing the vendor directory:

**Lack of traceability**:
Changes in dependencies are not easily traceable anymore.
Failure analysis is made more difficult.

**Lack of reproducibility**
The additional build step to pull the dependencies increases the fragility of the build pipeline.
 
**Decreasing build performance**
Installing all dependencies on every build can have high impact on build performance.

Especially in enterprise context, the mentioned problems are critical.

Do you basically agree to
a) provide more information about the deployment use case and the mentioned downsides?
b) remove the general recommendation to not commit vendor?

**Comment by localheinz** [comment]
@devsnacks 

How about opening a PR with your proposal instead of an issue requesting someone else do the work?

Personally, I would never recommend to commit the `vendor` directory, though. All of the issues you mentioned can be solved differently:

- committing `composer.lock`
- id not committing `composer.lock`, proper dependency management (hint: semantic versioning)
- caching composer’s cache in build and deploy systems

**Comment by Seldaek** [comment]
a) Maybe some reasonable amount of additional docs
b) Definitely not. The general recommendation is to use the composer.lock and gitignore the vendor. That's applicable to most people and use cases. There ways to mitigate all the problems you mention that don't cause the huge mess of having all dependencies' code tracked in your git repo.

**Comment by devsnacks** [comment]
@localheinz 

thank you for your comment. 

It´s not about requesting someone else to just change the documentation.
My intent was so start a discussion on the topic, as this is about a general advice/best practice
which i guess needs more conversation in the first place to find an agreement on it.
Of course i can provide a PR, if there is basically consensus on it.

> commiting `composer.lock`

We already do this. Nonetheless, this does not solve the mentioned problems:
It has no impact on _traceability_, as you are still not able to have a single diff showing
all changes of the commits in a specific release.

Also it has just minimal impact on _reproducibility_, as it just ensures that the pulled versions are consistent, which i would consider as an absolute minimum level of reproducibility.

> dependency management (hint: semantic versioning)

I don´t see how semantic versioning affects the mentioned problems.

> caching

Regarding build performance caching of course could make things a little better. 
As we are using docker for building the application, we already make use of the image layer
caching possibilities. Nonetheless, this isn´t always possible, as we offer multiple build agents for our teams, which are cleaned up regularly. Also when we go to stateless agents which are dynamically created this would make caching impossible again. So caching is just an option in very small environments i guess.

**Comment by acoulton** [comment]
@devsnacks I can see the issue but I still think committing vendor is a really bad idea.

> you are still not able to have a single diff showing all changes of the commits in a specific release.

Whilst that could be useful / important in certain circumstances, including it in the primary git diff of your project could equally be a nightmare. It will become very difficult to review the actual changes developers have made to a project if the same diff shows for example that every single file in a vendor package has adopted a new code style, or a library has been pulled in for a couple of small helpers and it becomes impossible to see what of the thousands of lines of new code is actually in use (though I appreciate that might also cause the dev to consider whether they really need the new package...!). Lots of git tools, including github, start to misbehave once diffs get too big.

In environments where you do need to be 100% certain that you're reviewing every single line of vendor code, maybe it's better to create a build step that produces and publishes the diff of the vendors to a separate artifact storage so that you can link to it without it being mixed into the primary git history?

Likewise in that scenario your build could create a single .tgz of the vendors for a given commit / composer.lock hash that you could then use rather than installing them directly which would also solve the reproducibility issue again without overwhelming your main git repo?

> Regarding build performance caching of course could make things a little better.
As we are using docker for building the application, we already make use of the image layer
caching possibilities.

Depending on workflow and frequency of vendor updates, by default I think if you commit the vendors you'd then have a much larger image to build and deploy on every build even the vendors are unchanged? Where if you do a composer install as a single layer fairly early in the build that'll often be able to be reused so the containers you're distributing are much smaller?

**Comment by sbuzonas** [comment]
> Depending on workflow and frequency of vendor updates, by default I think if you commit the vendors you'd then have a much larger image to build and deploy on every build even the vendors are unchanged? Where if you do a composer install as a single layer fairly early in the build that'll often be able to be reused so the containers you're distributing are much smaller?

We add `composer.json`, `composer.lock`, then `composer install` before adding the remainder of the application code to reduce the install step when the lock is not updated.

**Comment by devsnacks** [comment]
@acoulton @sbuzonas 
Same approach here, we add manifest and lock file in a separate RUN statement, so wen can make use of the image layer cache and skip the install if nothing changed.

The primary reason not to commit seems to be the additional diff, which is considered _distracting_. 

In terms of QA and traceability i don´t see a difference between application code and library code.
Being able to quickly analyze the complete changeset of a release can be more important than a neat - but incomplete - diff. In case of incident, often the most time is spent on failure analyses and figuring out the root cause of the problem. Not even being able to get a diff including all source code changes seems to me like a step backwards. When people discover exploding and distracting diffs, than maybe it´s a sign of thoughtless dependency handling. 

Of course this all can be solved on a different layer. But this increases complexity and comes with a cost. It introduces additional dependencies.

Typical suggestions:
Availability:
_Why not install and maintain a proxy infrastructure?_

Performance:
_Why not use caching?_

Reproducibility:
_Why on vcs level? Why not use artifactory and get a reproducible history of the
generated artifacts?_

Distinct features of the version control system are omitted and have to be found elsewhere, which necessarily means an increase in complexity. 

I see that most of you are fine with the common practice, but it still sounds odd to me that the main advantage is considered in the absence of distracting diffs.

**Comment by acoulton** [comment]
@devsnacks it's not so much that the additional diff is *distracting* as that in some cases it may be large to the point of making it impossible to actually review the overall diff of the project in many tools. If the PR diff is too big to show on github, that in itself means switching to other tools and an increase in complexity.

But yes, also it's distracting. At the initial stage of an investigation I'd consider it more useful to see for example that a project bumped up a couple of minor point versions of dependencies I broadly trust - symfony components for example - and to focus in on changes my own team had made to the main codebase. With all the vendor diffs inlined with everything else, it would be easy to get sidelined by potentially huge internal refactoring or reformatting of a well-tested well-trusted package and not spot a few-line change as part of a major version bump on something else.

Even if I started to suspect vendors, I'd probably start by reviewing their changelog and reported issues for the versions that had been bumped rather than trying to line-by-line review changes in a third-party codebase in the first instance which is very likely to be slow.

Also if it's a well-managed package then the version in my `vendors` won't contain things like unit tests, docs, etc : if I actually want to understand at low-level how a package has changed between versions these would often be my first go-to as they provide important context / signposting.

> Not even being able to get a diff including all source code changes

Point is there are plenty of ways to do that if necessary. Pre-emptively that can be done at the build stage (and indeed if you're using docker layers as above then you could even use docker's inbuilt layer diff commands). Or if you need it later you can just grab the two versions of the composer.lock files, run composer install on each, and then diff locally.

**Comment by devsnacks** [comment]
@acoulton I get your point and maybe the key issue is the differentiation between well-trusted open source dependencies and in-house developed libraries. In the latter case, the level of trust should be the same for app and library changes.

So maybe the use case is more common in corporate environments but i still think this should be considered as a valid use case. It mainly depends on your level of trust or experience with the respective dependencies, but from a conservative standpoint, i would rather prefer to opt-out the diff if needed and not being dependent on third-party tooling in the first place.

**Comment by acoulton** [comment]
@devsnacks that's fair I guess. I suppose there's nothing stopping you committing specific packages you want to keep an eye on on a case-by-case basis depending on trust level. I still think in practice it's very hard to "opt-out the diff if needed" if it's part of the same set of commits / pull request as things you actually want to see. E.g. github doesn't have any mechanism to hide whole directories on a PR diff and will refuse to show anything at all if the changeset is too big. This is based on experience of committing javascript dependencies (as that's the common practice for most JS dependency managers). So I'd still say it's an approach that needs careful consideration of pros, cons and alternatives, and really not a good idea to recommend as general practice.

**Comment by sbuzonas** [comment]
@devsnacks It isn't so much that it makes the diff distracting, large scale changes have a significant impact on repository size. High bandwidth updates slow down a continuous delivery pipeline and make it difficult for overseas third party contractors to collaborate in regions where internet connectivity isn't top notch. I've seen repositories that tracked vendors grow to gigabytes in size just checking out the history.

I agree with the concept of big picture overview of software quality that the vendors should also be reviewed. At the project level, there is some level of trust assumed of the vendors. In my experience in large corporate projects, that level of trust is determined out of band with other teams that are specialized for vendor review. Usually a security or DevEx team. In-house vendors are granted trust by following the same processes and standards of the application being deployed.

**Comment by naderman** [comment]
I think one issue you've overlooked so far: If the vendor directory is commited to the repository, it becomes much more feasible to edit files inside this directory. Especially an inexperienced developer or someone not yet familiar with the management of dependencies may get the impression that this code may simply be edited in the repository.

As a result you may silently lose these changes on updates or need to resolve merge conflicts in your third party dependencies which may not be trivial or even possible. Simply commiting the lock file ensures that build systems get clean dependencies which will typically result in test failures if anyone edited files in their local vendor directory.

**Comment by devsnacks** [comment]
I see that most of you have a clear opinion on this and i agree that there are many advantages in the recommended way of doing it as well. My main point was to open up a discussion on it and there was great contribution and maybe this discussion could help other people in finding the right way in their context. Thank you all for your contributions!
