### ISSUE TITLE
Bad Composer.phar snapshot https://getcomposer.org/composer.phar

### ISSUE THREAD

**Issue by hectorprats** [composer/composer#7594]
The snapshot now gets Composer version 1.8-dev

It has several fails with symfony/dotenv, for example.

**Comment by stof** [comment]
Please give more details about the errors. `several fails` does not describe the issue.

**Comment by hectorprats** [comment]
Problem 1
    - Conclusion: remove symfony/dotenv v4.1.4
    - Conclusion: don't install symfony/dotenv v4.1.4
    - Conclusion: don't install symfony/dotenv v4.1.3
    - Conclusion: don't install symfony/dotenv v4.1.2
    - Conclusion: don't install symfony/dotenv v4.1.1
    - Conclusion: don't install symfony/dotenv v4.1.0
    - Conclusion: don't install symfony/dotenv v4.0.14
    - Conclusion: don't install symfony/dotenv v4.0.13
    - Conclusion: don't install symfony/dotenv v4.0.12
    - Conclusion: don't install symfony/dotenv v4.0.11
    - Conclusion: don't install symfony/dotenv v4.0.10
    - Conclusion: don't install symfony/dotenv v4.0.9
    - Conclusion: don't install symfony/dotenv v4.0.8
    - Conclusion: don't install symfony/dotenv v4.0.7
    - Conclusion: don't install symfony/dotenv v4.0.6
    - Conclusion: don't install symfony/dotenv v4.0.5
    - Conclusion: don't install symfony/dotenv v4.0.4
    - Conclusion: don't install symfony/dotenv v4.0.3
    - Conclusion: don't install symfony/dotenv v4.0.2
    - Conclusion: don't install symfony/dotenv v4.0.1
    - don't install symfony/dotenv v4.0.0|don't install symfony/symfony v3.4.0
    - don't install symfony/dotenv v4.0.0|don't install symfony/symfony v3.4.1
    - don't install symfony/dotenv v4.0.0|don't install symfony/symfony v3.4.10
    - don't install symfony/dotenv v4.0.0|don't install symfony/symfony v3.4.11
    - don't install symfony/dotenv v4.0.0|don't install symfony/symfony v3.4.12
    - don't install symfony/dotenv v4.0.0|don't install symfony/symfony v3.4.13
    - don't install symfony/dotenv v4.0.0|don't install symfony/symfony v3.4.14
    - don't install symfony/dotenv v4.0.0|don't install symfony/symfony v3.4.15
    - don't install symfony/dotenv v4.0.0|don't install symfony/symfony v3.4.2
    - don't install symfony/dotenv v4.0.0|don't install symfony/symfony v3.4.3
    - don't install symfony/dotenv v4.0.0|don't install symfony/symfony v3.4.4
    - don't install symfony/dotenv v4.0.0|don't install symfony/symfony v3.4.5
    - don't install symfony/dotenv v4.0.0|don't install symfony/symfony v3.4.6
    - don't install symfony/dotenv v4.0.0|don't install symfony/symfony v3.4.7
    - don't install symfony/dotenv v4.0.0|don't install symfony/symfony v3.4.8
    - don't install symfony/dotenv v4.0.0|don't install symfony/symfony v3.4.9
    - don't install symfony/dotenv v4.0.0|remove symfony/symfony v3.4.15
    - Installation request for symfony/dotenv ^4.0 -> satisfiable by symfony/dotenv[v4.0.0, v4.0.1, v4.0.10, v4.0.11, v4.0.12, v4.0.13, v4.0.14, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1, v4.1.2, v4.1.3, v4.1.4].
    - Installation request for symfony/symfony 3.4.* -> satisfiable by symfony/symfony[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].

**Comment by curry684** [comment]
Please either use the [recommended installation methods](https://getcomposer.org/download/) to use a stable version of Composer, or, if you insist on using the usually unstable developent snapshots provide proper debugging information to the developers. We cannot work with "several fails", nor with a dump of a lot of output without even the command and `composer.json` file triggering that output. [Give us a short, self contained, correct example](http://sscce.org/) so we actually understand your problem. Following the [issue template](https://github.com/composer/composer/issues/new) helps a lot.

**Comment by hectorprats** [comment]
really??

ok:

 "require": {
        "symfony/dotenv": "^4.0",
        "symfony/symfony": "3.4.*"
    },

please, you just need to pay attention to the mistake I've made. Stof was right to ask about the exact errors. But I've already put it. It indicates the version that gives you the problem and the error.

You do not need a json for this.

**Comment by curry684** [comment]
Yes we do, it's not possible to install those components at the same time, as `dotenv` is replaced by `symfony/symfony`, see https://packagist.org/packages/symfony/symfony. The error is literally right what it should be.

**Comment by stof** [comment]
Installing both `symfony/symfony` 3.4 and `symfony/dotenv` 4.0 together is not meant to work, because `symfony/symfony` contains the code of `symfony/dotenv` (and so this would lead to duplicate class definitions in your project, with no guarantee about which version of the dotenv component would actually get loaded when using it; it might even be a mix of both).
The stable version has a bug allowing this case (since a long time). The snapshot version has this bug fixed (note that until 1.0.0-alpha8, composer was behaving fine for such `replace` rules, as that's when the bug was introduced).

Note that if you have 1 package requiring `symfony/dotenv: ^4.0` and another package requiring `symfony/symfony: 3.4.*`, the stable version already refuses to install them together due to this conflict. The bug in the stable version happens when the root package is the one containing at least one of these requirements (due to some optimizations which were added based on the root package requirements).

**Comment by hectorprats** [comment]
Thanks Stof. It is very interesting what you are saying. I did not know that the error was in the stable version. I thank you for the information you provide and I have learned something new.

However, this makes me think. Is not it better to solve such a critical problem in a major version? Because I'm sure we're not going to be the only ones with this problem.

**Comment by stof** [comment]
@hectorprats any project with 2 different version of the same package installed is potentially buggy, due to being able to load classes from a mix of 2 versions of the package, and the loading code potentially not matching the expectation of the caller (if a package requires version 4 of a component, but the code for version 3 gets used at runtime, things might break). And projects might not even realize that they are affected by this bug, because most of the time, things will work fine (as the composer autoloader is deterministic about which file it will use, things won't fail randomly, but only for certain usage patterns). Thus, in the case of Symfony, the 3.4 release and the 4.0 release are mostly the same (and in the case of dotenv, they are exactly the same as this is a new component which had no deprecated APIs), so the risk of breaking things due to multiple versions is even lower.

Any bug fix could break things for people relying on the buggy behavior. This does not mean that bug fixes are forbidden out of major version

**Comment by hectorprats** [comment]
Yes, I understood the risk. But in this case, as you say, we had it controlled and studied. And we saw the notices.

That's why it seems to me a radical court to pass from warnings a fatal error in a minor one.

Anyway. I am very pleased to see that it is going to be cut and your good explanation.
