### ISSUE TITLE
Add support for calling Composer commands from child directories

### ISSUE THREAD

**Issue by filips123** [composer/composer#7602]
Add support for calling composer commands from child directories.

Currently, users have to run Composer commands (like `composer install`) from same directory as `composer.json`. It's like in Git.

Composer should look for `composer.json` in current directory and all parent directories until it find it.
For example, if `composer.json` is located in `/projects/myproject/` and user call composer from `/projects/myproject/src/Examples/`, Composer should look for `composer.json` in `/projects/myproject/src/Examples/`, `/projects/myproject/src/` and `/projects/myproject/` (it that order).

**Comment by alcohol** [comment]
You could use `composer -d` ?

I believe the functionality you requested has already been rejected in the past. But I can't recall exactly in what issue it was, nor for what reason. @Seldaek do you have any thoughts on this?

**Comment by Seldaek** [comment]
We added support for this in 1.5.0 https://github.com/composer/composer/releases/tag/1.5.0 - Please make sure you use the latest version using `composer self-update`

**Comment by filips123** [comment]
@Seldaek Thank you! I didn't have latest version.

But there is one more problem. Normal compuser commands (`install`, `update`...) works in sub-directory, but commands defined in `composer.json` don't.

I have command `test` in `composer.json`. From project's home directory, I can run it with `composer test`. From sub-directory, I can only run it with `composer run-script test`.

If I run it with `composer test`, I get error:
```
  [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "test" is not defined.
```

**Comment by Seldaek** [comment]
Ok that sounds like a bug..

**Comment by dmanners** [comment]
The bug seems to happen during the if check around asking the user to change directory. It seems that the command name, as it only checks the standard commands first because it does not have the composer.json file, is not found. Then on the check around the if we have

```
// prompt user for dir change if no composer.json is present in current dir
if ($io->isInteractive() && !$newWorkDir && !in_array($commandName, array('', 'list', 'init', 'about', 'help', 'diagnose', 'self-update', 'global', 'create-project'), true) && !file_exists(Factory::getComposerFile())) {
```

In this case we have:

`$io->isInteractive()` = true
`!$newWorkDir` = true
`!in_array($commandName, array('', 'list', 'init', 'about', 'help', 'diagnose', 'self-update', 'global', 'create-project'), true)` = false
`!file_exists(Factory::getComposerFile())` = true

In the case that we are running an install or another command we have:

`$io->isInteractive()` = true
`!$newWorkDir` = true
`!in_array($commandName, array('', 'list', 'init', 'about', 'help', 'diagnose', 'self-update', 'global', 'create-project'), true)` = true
`!file_exists(Factory::getComposerFile())` = true

I am not sure what the best option should be here. Is the default setting of command name to '' a fallback for the list command or something else? Would there be any harm in prompting the user each time they run composer outside of a project root directory to switch for everything other than global and self-update?

**Comment by Seldaek** [comment]
Fixed by #7648

**Comment by filips123** [comment]
@Seldaek When will 1.8 be released?

**Comment by Seldaek** [comment]
@filips123 most likely when it's ready.. You can use snapshots in the meantime using `composer self-update --snapshot`.
