### ISSUE TITLE
Failing intermittently for satis using bitbucket

### ISSUE THREAD

**Issue by ghost** [composer/composer#7683]
When I have my satis server set up on a cron job (which I have validated uses the correct oauth tokens and ssh keys for these private packages), I intermittently get the following response:

```
  - Installing thoughtriver/product (dev-master 473f2ee): Cloning 473f2eec3c from cache
    473f2eec3cd83eba27f0d82c19010f37425d4919 is gone (history was rewritten?)
    Failed to download thoughtriver/product from source: Failed to execute git checkout '473f2eec3cd83eba27f0d82c19010f37425d4919' -- && git reset --hard '473f2eec3cd83eba27f0d82c19010f37425d4919' --

fatal: reference is not a tree: 473f2eec3cd83eba27f0d82c19010f37425d4919

    Now trying to download from dist
  - Installing thoughtriver/product (dev-master 473f2ee): Downloading (connecting...)
                                                
  [Composer\Downloader\TransportException]      
  Could not authenticate against bitbucket.org  
                                                

build [--repository-url [REPOSITORY-URL]] [--no-html-output] [--skip-errors] [--stats] [--] [<file>] [<output-dir>] [<packages>]...
```

If I delete the entire downloaded contents of satis and let the cron run again, _sometimes_ it works and others it doesn't for a few days.

I can probably guess that the bitbucket auth issue is related somewhat to bitbucket, although the creds are valid, and doing the process manually *always* works. If I also manually run `git checkout '473f2eec3cd83eba27f0d82c19010f37425d4919' -- && git reset --hard '473f2eec3cd83eba27f0d82c19010f37425d4919'` it *always* works.

My issue is that it tells me that history has been rewritten when it clearly hasn't. *The commit exists in the repository locally and on bitbucket*

Whether this is an issue with bitbucket, composer or satis, I'm logging it here as that is where the error message I receive is coming from.

**Comment by alcohol** [comment]
Can you give us more details about your environment? Docker, Host OS, PHP version, etc?

**Comment by alcohol** [comment]
Also, Satis has its own repository: https://github.com/composer/satis

**Comment by johnrobertporter** [comment]
I know, but as I've verified just now, and referenced, when I clear _composer's_ cache, everything generally works for a while, so I figured it's composer, not satis.

Env:

- Ubuntu 16.04
- Composer 1.6.3 2018-01-31 16:28:17
- PHP 7.2.10-0ubuntu0.18.04.1 (cli) (built: Sep 13 2018 13:45:02) ( NTS )

**Comment by AndreKR** [comment]
This sounds awfully similar to the issue I am having right now.

In my case the underlying problem is that Composer uses the credentials **from the cache** instead of the ones from `auth.json`. So **whenever the credentials in `auth.json` change, existing cached repositories stop being updated**. (See also [here](https://github.com/composer/composer/issues/3644#issuecomment-461135352)).

And there is another twist when the repository exists in Composer's cache, but not in the `vendor`directory: The error message during the update is silently discarded.

Here are the relevant code locations...

`fetchRefOrSyncMirror()` calls `syncMirror()`. Note that it discards its return value.
https://github.com/composer/composer/blob/568081f9b68b9f7191a90d8ff9289913ee6e0be8/src/Composer/Util/Git.php#L253-L266

`syncMirror()` calls `runCommand()` to run `git remote update --prune origin`, catches any Exception and converts it to a return value `false`, which is then discarded.
https://github.com/composer/composer/blob/568081f9b68b9f7191a90d8ff9289913ee6e0be8/src/Composer/Util/Git.php#L229-L236

`runCommand()` uses any credentials found in the _current_ remote URL, overwriting any credentials set in `auth.json`:
https://github.com/composer/composer/blob/568081f9b68b9f7191a90d8ff9289913ee6e0be8/src/Composer/Util/Git.php#L58-L61

The `git remote update --prune origin` will fail because of the outdated credentials and `runCommand()` will throw an exception:
https://github.com/composer/composer/blob/568081f9b68b9f7191a90d8ff9289913ee6e0be8/src/Composer/Util/Git.php#L221

But we will never see it because it is discarded, as shown above.

**Comment by AndreKR** [comment]
Indeed any exceptions now seem to be properly propagated and printed in https://github.com/composer/composer/blob/2ca2ec3d0ae77bbadc8a4c60180c7770bddc4b32/src/Composer/Util/Git.php#L268

Also, the underlying logic error was fixed in https://github.com/composer/composer/commit/149250ab92feadd9fe045b54d6e42f33d185a595.
