### ISSUE TITLE
All settings correct for using Composer The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly 

### ISSUE THREAD

**Issue by sgpeter** [composer/composer#7707]
i tried running the installer in my new clean linux sharehosting,

php 7.1
how do i go about it.
please advice. thanks
All settings correct for using Composer The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly

**Comment by alcohol** [comment]
It seems you do not have `$HOME` available in your environment variables. Sounds to me like your "new clean linux sharehosting" is a bit broken, because that environment variable is incredibly common and I can't think of a reason why a system would not have it. You can set either mentioned environment variable yourself though to "fix" the problem. If you do not know what environment variables, I suggest you read up on them [here](https://en.wikipedia.org/wiki/Environment_variable) and [here](https://www.digitalocean.com/community/tutorials/how-to-read-and-set-environmental-and-shell-variables-on-a-linux-vps).
