### ISSUE TITLE
are unc paths supported for the working directory?

### ISSUE THREAD

**Issue by tonyguadagno** [composer/composer#7732]
I am asking because i am using current composer (Composer version 1.7.2 2018-08-16 16:57:12) and when i try this:

`composer --working-dir=//server/share/folder`
or
`composer --working-dir=\\server\share\folder`
i get this error:

>   [ErrorException]
>   proc_open(NUL): failed to open stream: Permission denied
> 

but if i map a drive to the same location and do this
`composer --working-dir=f:\folder`
it works....

I am quite sure this is not a perms issue, am I doing something wrong?

thanks

**Comment by Seldaek** [comment]
We might not have support for this no.. or it might be a quoting issue. Anyway not really likely that we will add support for it to be honest as it's a sort of edge case scenario.

**Comment by tonyguadagno** [comment]
hi, i don't think it is an edge case.  could it be listed as a feature request?

**Comment by Seldaek** [comment]
I understand it's a feature request but I am saying it's not something we are going to add support for. If you figure it out and send a reasonable pull request why not but I won't spend time on this. I'd make sure it's not a quoting problem first though because with backslashes funky things easily happen
