### ISSUE TITLE
[Question] how to write a plugin which tells composer to not install a dependency

### ISSUE THREAD

**Issue by DeepDiver1975** [composer/composer#7740]
Scenario:
- I want to use composer to develop a plugin (ownCloud in this case - but maybe applies to others as well)
- The plugin uses e.g. aws-sdk-php which requires guzzle
- The core system already requires guzzle
- The overall system is taking care of loading the two autoloader
- How can I tell the composer in the plugin to install aws but not guzzle?

Solution:
- define replace for guzzle - see https://github.com/owncloud/files_primary_s3/blob/e695fc78c7909bdd5da6144aae24b9d15ed8f223/composer.json#L9

Next step:
- grab these replaces dynamically from the core composer file.

I tried to use this code snippet in the plugin on various events or activate - but it is no respected:

```php
        $replaces = [
            new Link($composer->getPackage()->getName(), 'guzzlehttp/guzzle')
        ];
        $composer->getPackage()->setReplaces($replaces);
```

Any idea? THX

**Comment by DeepDiver1975** [comment]
Is it a :chicken: :egg: issue? On the first run the plugin is installed but the replaces are already loaded?

**Comment by sbuzonas** [comment]
To answer the question... IIRC, if you need to do modifications to solver logic in a plugin, it has to be global. It also required a whole lot of messy reflection to replace parts that probably shouldn't be replaced.

I'm curious as to why you need this. What is wrong with having multiple packages with common dependencies?

Replaces implies that the replacer conflicts with what is being replaced, and should prevent it from being installed entirely for any dependency. Special care should be made when choosing to use replaces, because other packages could get your package when their constraint cannot be satisfied.

**Comment by DeepDiver1975** [comment]
> I'm curious as to why you need this. What is wrong with having multiple packages with common dependencies?

Maybe I miss what you mean with 'common dependencies' - but this is what I want to build.

The is our core component which has it's own composer.json which has a dependency to guzzle 5.3 https://github.com/owncloud/core/blob/e0871ca1939b945128df89a7b8530701368dbe88/composer.json#L61 . The generated autoloader is required during bootstrapping of the application.

Next there can be many apps/plugins which we load into our core - this is all down without composer. No composer action in here. But these apps can use composer themselves to bring their own dependencies (like the aws-sdk as explained above). 
To make sure we have no conflict with different versions of guzzle we add the requirement to guzzle 5.3 as well on the app.

Still where is code duplication - but more important: we now want to move on to guzzle 6. The hard requirement to guzzle 5.3 will cause issues. It would be cool to not install any guzzle into the app but rely on the version as available by core (the aws-sdk can handle both guzzle lib versions ...)

^ this is basically the playground I'm in at the moment. Adding guzzle as replace seems to do the job. Having this in a more dynamic way where all libs which need to be ignored are just take from the core composer.json would be cool.

Or I miss one important point about composer ;-) THX

**Comment by DeepDiver1975** [comment]
Another solution would be a package which defines all replaces - https://github.com/owncloud/core/pull/33264/files#diff-05266d50ebdbb7cf698d60bcdbfcfd25 ....not sure is this is reasonable.

Usage in the app: https://github.com/owncloud/files_primary_s3/pull/146/files#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

**Comment by sbuzonas** [comment]
What I meant by common dependencies, were dependencies shared between multiple libraries.

Replaces isn't quite what you want for that scenario. That implies that the package replaces, and can be used instead of the package being replaced... For ANY other package.

I believe provides is the option you are looking for.  You could create a metapackage called something like owncloud/core-libs that has provide statements for everything brought in by your owncloud/core package. Then, when the plugins require owncloud/core-libs... It will not install any dependencies that are listed in the provides statement because you are telling composer that they already exist.

This gets tricky without telling composer about all of the dependencies, because you will run into conflicts that would be rejected by composer. For example, plugin-a requires dependency-a:1.0.0 and plugin-b requires dependency-a:2.0.0. If there are name collisions, you can't load both versions of the PHP code simultaneously, and will end up with unexpected behavior.

**Comment by DeepDiver1975** [comment]
> This gets tricky without telling composer about all of the dependencies, because you will run into conflicts that would be rejected by composer. For example, plugin-a requires dependency-a:1.0.0 and plugin-b requires dependency-a:2.0.0. If there are name collisions, you can't load both versions of the PHP code simultaneously, and will end up with unexpected behavior.

WordPress was fighting with this if I understood correctly and came up with imposter. But this one does not *yet* fully work as well - https://github.com/TypistTech/imposter/issues/75

**Comment by DeepDiver1975** [comment]
> I believe provides is the option you are looking for. You could create a metapackage called something like owncloud/core-libs that has provide statements for everything brought in by your owncloud/core package. Then, when the plugins require owncloud/core-libs... It will not install any dependencies that are listed in the provides statement because you are telling composer that they already exist.

this is basically what I did in https://github.com/composer/composer/issues/7740#issuecomment-432228289 - I'll switch to provide and give it a try

THX a lot!

**Comment by DeepDiver1975** [comment]
With provide I don't get this working ... I  must be missing something ...

**Comment by sbuzonas** [comment]
I don't understand what you are trying to do. `replace` means the package is an alternative to the package being replaced and will generate corresponding conflicts, `provides` means the functionality is included.
