### ISSUE TITLE
1.7.3. breaks composer.lock

### ISSUE THREAD

**Issue by linde002** [composer/composer#7764]
Yesterday composer install works fine. Without any changes to composer.json & composer.lock today it fails with:
```
Roberts-iMac:zagis robert$ php composer.phar install    
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove symfony/symfony v2.8.45
    - don't install symfony/symfony v2.8.45|remove symfony/var-dumper v3.4.15
    - don't install symfony/var-dumper v3.4.15|don't install symfony/symfony v2.8.45
    - Installation request for symfony/symfony v2.8.45 -> satisfiable by symfony/symfony[v2.8.45].
    - Installation request for symfony/var-dumper v3.4.15 -> satisfiable by symfony/var-dumper[v3.4.15].
```

Rolling back to 1.7.2 allows installing the old .lock file, however our CI/CD pipeline uses the latest composer which fails.

What changed? Why would you break working .lock files?

**Comment by ThomasLabstep** [comment]
Same with:
```
don’t install symfony/symfony v3.4.17|don’t install symfony/cache v4.1.6
```

**Comment by Seldaek** [comment]
These are all due to https://github.com/composer/composer/pull/7454 most likely.. Edge cases that should have broken before but were allowed accidentally.

In most of these cases you have both symfony/symfony AND some of the individual components installed, in different versions. This doesn't make any sense and might end up with unexpected results as one or the other package gets autoloaded.

To resolve this make sure you remove symfony/symfony or the other components depending on your app's requirements.

**Comment by Seldaek** [comment]
Yes that's unfortunate but it's not really something we can selectively fix as the solver is needed as well when running `install`. And technically it was a bug, albeit you surely can argue there, but fixing it in 1.8.0 would also lead to the same problem, and maybe more people affected by then, so IMO the sooner the better.

**Comment by dextervip** [comment]
I am having the same issue also with 1.7.3

```
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Dependency resolution completed in 0.003 seconds
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove symfony/polyfill v1.7.0
    - Installation request for symfony/polyfill v1.7.0 -> satisfiable by symfony/polyfill[v1.7.0].
    - Conclusion: remove symfony/stopwatch v4.1.1
    - symfony/polyfill v1.7.0 requires symfony/intl ~2.3|~3.0|~4.0 -> satisfiable by symfony/symfony[v3.4.12].
    - don't install symfony/stopwatch v4.1.1|remove symfony/symfony v3.4.12
    - don't install symfony/symfony v3.4.12|don't install symfony/stopwatch v4.1.1
    - Installation request for symfony/stopwatch v4.1.1 -> satisfiable by symfony/stopwatch[v4.1.1].
```

**Comment by Piskvor** [comment]
@Seldaek : A compatibility break between minor versions is "better"? Surely you jest!

**Comment by Seldaek** [comment]
Please do not post "me too" comments if you aren't going to provide any additional information. It spams everyone ands makes it harder to find help in this thread.

**To resolve this make sure you remove symfony/symfony or the other symfony components depending on your app's requirements.** e.g. `don't install symfony/symfony v3.4.12|don't install symfony/stopwatch v4.1.1` states that those two are incompatible, you have to find a way to remove either of them, which might involve upgrading/downgrading the other.

**Comment by dpagini** [comment]
I ran into this library with the following command:
```sh
$ composer require acquia/lift-sdk-php typhonius/acquia-php-sdk-v2
```
This appears to be because the `typhonius/acquia-php-sdk-v2` requires `acquia/http-hmac-php` and `acquia/lift-sdk-php` library requires a FORK of that library. Both libraries use different namespaces, so I'm not sure why I can't have both present in my project. My standing guess is that both libraries indicate they are `replace: acquia/hmac-request`, and that is the source of the problem? But I am not requesting that library at all, so that doesn't completely make sense either... I'm not sure I understand what is causing this issue...?

Just to piggyback on some of the comments above, this does seem like a poor choice of a change to include in a patch release. It's clear this is affecting a lot of people based on the activity here 6 hours after the release. I think some kind of composer hints that this will break in the future minor release would have been a better DX, and give users time to update their libraries before it fubars people's builds.
