### ISSUE TITLE
1.7.3 "edge case" support request.

### ISSUE THREAD

**Issue by dpagini** [composer/composer#7767]
With #7764 locked, I was hoping to get specific support for an edge case. I detailed this more in acquia/lift-sdk-php#30 where @Seldaek seemed to indicate this was unexpected.

I am unable to run the below command, but I believe I should be able to have these 2 libraries in my project at the same time.

When I run this command:

```
$ composer require acquia/lift-sdk-php typhonius/acquia-php-sdk-v2 nickveenhof/http-hmac-php
```

**Comment by naderman** [comment]
Looking at this it actually looks like correct behaviour. Replacement is meant for situations in which two packages provide classnames with the same names, so they cannot be installed at the same time. The same applies for installing two packages which both replace the same original package.

In this example typhonius/acquia-php-sdk-v2 requires acquia/http-hmac-php which replaces acquia/hmac-request. You are then trying to also install nickveenhof/http-hmac-php which also replaces acquia/hmac-request. So the assumption is that acquia/http-hmac-php and nickveenhof/http-hmac-php must conflict with each other because they both replace the same package (acquia/hmac-request).

So I'm not familiar with the code in these but possible solutions are for "nickveenhof/http-hmac-php" to replace "acquia/http-hmac-php" instead of just "acquia/hmac-request") if it implements all of that functionality. Or if it does not, you could use "provide" instead of "replace" in "nickveenhof/http-hmac-php" to indicate that the package can provide the functionality of "acquia/hmac-request" without conflicting with it. This is not recommended if you ship the same namespaces & classnames.

In general this is not a bug in Composer, but rather incorrect use of replace/provide in the packages you are trying to use.
