### ISSUE TITLE
Suggestion, ask confirmation when is run as admin

### ISSUE THREAD

**Issue by PeopleInside** [composer/composer#7795]
Hi, sometimes i forget composer should be run as user and not admin.
Instead also to advise to run as user can you add a confirmation message that ask to the user if are sure to run as admin?

Actually seems if is lunched as admin just alert and lunch without give the possibility to stop.
I will imagine this:

- run as admin -> composer show the alert that should be run as user and ask if you want continue ( y / n ).

This can be a security feature that allow you to say n (no) than switch to user and run as user.

**Comment by peter279k** [comment]
@PeopleInside, do you want to have the `prompt` to confirm that user run [composer](url) as super user?

According to the original approach, this will only output the warning message to notify the user run `composer` as super user.

I also agree this feature because this will let users do the confirmation again.

**Comment by PeopleInside** [comment]
@peter279k exact. I run as root for error and was not able to stop... alert is not enough.
If the system was asking if continue as root i would choose not and choose the normal user :)

**Comment by Seldaek** [comment]
Fixed by #7819
