### ISSUE TITLE
Composer install fails with conflict [v1.7.3] 

### ISSUE THREAD

**Issue by MarioBlazek** [composer/composer#7813]
I have composer version 1.7.3.

Same `composer.json` was working fine on 1.7.2.

My `composer.json`:

```json
{
    "require": {
        "php": "~5.6|~7.1",
        "symfony/symfony": "2.8.48",
        "symfony/cache": "^3.4",
        "symfony/var-dumper": "^3.4"
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
License "GPL-2.0" is a deprecated SPDX license identifier, use "GPL-2.0-only" or "GPL-2.0-or-later" instead
Defining autoload.psr-0 with an empty namespace prefix is a bad idea for performance
require.symfony/symfony : exact version constraints (2.8.48) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.7.3
PHP version: 7.1.23 - Package overridden via config.platform (actual: 7.2.11)
PHP binary path: /opt/local/bin/php72
```

When I run this command:

```bash
composer install
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - symfony/cache v3.4.0 conflicts with symfony/symfony[v2.8.48].
    - symfony/cache v3.4.1 conflicts with symfony/symfony[v2.8.48].
    - symfony/cache v3.4.10 conflicts with symfony/symfony[v2.8.48].
    - symfony/cache v3.4.11 conflicts with symfony/symfony[v2.8.48].
    - symfony/cache v3.4.12 conflicts with symfony/symfony[v2.8.48].
    - symfony/cache v3.4.13 conflicts with symfony/symfony[v2.8.48].
    - symfony/cache v3.4.14 conflicts with symfony/symfony[v2.8.48].
    - symfony/cache v3.4.15 conflicts with symfony/symfony[v2.8.48].
    - symfony/cache v3.4.16 conflicts with symfony/symfony[v2.8.48].
    - symfony/cache v3.4.17 conflicts with symfony/symfony[v2.8.48].
    - symfony/cache v3.4.18 conflicts with symfony/symfony[v2.8.48].
    - symfony/cache v3.4.19 conflicts with symfony/symfony[v2.8.48].
    - symfony/cache v3.4.2 conflicts with symfony/symfony[v2.8.48].
    - symfony/cache v3.4.3 conflicts with symfony/symfony[v2.8.48].
    - symfony/cache v3.4.4 conflicts with symfony/symfony[v2.8.48].
    - symfony/cache v3.4.5 conflicts with symfony/symfony[v2.8.48].
    - symfony/cache v3.4.6 conflicts with symfony/symfony[v2.8.48].
    - symfony/cache v3.4.7 conflicts with symfony/symfony[v2.8.48].
    - symfony/cache v3.4.8 conflicts with symfony/symfony[v2.8.48].
    - symfony/cache v3.4.9 conflicts with symfony/symfony[v2.8.48].
    - Installation request for symfony/symfony 2.8.48 -> satisfiable by symfony/symfony[v2.8.48].
    - Installation request for symfony/cache ^3.4 -> satisfiable by symfony/cache[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
```

And I expected this to happen:

Successful install as it was on previous version 1.7.2

**Comment by julienfalque** [comment]
Seems related to https://github.com/composer/composer/issues/7764#issuecomment-435035188.

You shouldn't require `symfony/symfony` (the Symfony monolith) *and* some of its components at the same time. The proper solution is to replace `symfony/symfony` with the components you actually need.

**Comment by emodric** [comment]
@julienfalque Easier said than done. This is on a legacy Symfony 2.8 app that in its core also depends on `symfony/symfony`, so not much can be done on that front.

Even if the fact is that now the behaviour is "correct", it left a number of projects in a non-working state in a patch release of Composer since not every project can migrate away from `symfony/symfony` yet.

**Comment by Seldaek** [comment]
This is kinda weird though because symfony/symfony 2.8.48 does not itself replace symfony/cache, so both should be installable together really. It appears that it conflicts due to the fact newer symfony releases replace it, but your specific case should work IMO. @naderman do you understand this differently?

**Comment by naderman** [comment]
@Seldaek symfony/cache 3.4 has a conflict with symfony/var-dumper <3.3. At the same time symfony/symfony 2.8.48 replaces symfony/var-dumper v2.8.48. So the conflict from cache to var-dumper also applies to symfony/symfony. This is correct behaviour and should never have worked before.

**Comment by naderman** [comment]
@MarioBlazek @emodric symfony/cache 3.4 explicitly conflicts with part of symfony/symfony 2.8.48 so I can only assume that your application was already broken in the previous state since composer's bug allowed you to install something that was intentionally flagged as incompatible by the symfony team.

**Comment by emodric** [comment]
Still, the fact is that the project worked for the past couple of years and now the patch release of Composer left it in non-working state. And this is not exclusive to our project, as obviously other projects have issues too.

Anyway, I don't see this set of dependencies as problematic and incompatible. `symfony/symfony` 2.8.48 replaces `symfony/var-dumper` only 2.8.48, and `symfony/cache` conflicts with `symfony/var-dumper` < 3.3, so `symfony/var-dumper` 3.4 should be allowed to install, since it neither conflicts, nor it is replaced by any dependency (if we disregard the autoload priority issue, which is not the topic here)

**Comment by emodric** [comment]
> symfony/cache 3.4 explicitly states that it cannot work when symfony/var-dumper < 3.3 is present. 

var-dumper < 3.3 is not present, 3.4 is, so no problem there, right?

> symfony/symfony 2.8.48 replaces symfony/var-dumper

Yes, but only version 2.8.48, not 3.4, so, again, no problem.

By all acounts, these three dependencies should be compatible, and, yes, the project worked  fine, since standalone var-dumper had priority in autoloader.

**Comment by naderman** [comment]
@emodric Please read again what I wrote multiple times now. symfony/var-dumper 2.8.48 is present if symfony/symfony 2.8.48 is installed, that's what replacing means. You cannot install symfony/var-dumper 3.4 when symfony/var-dumper 2.8.48 is already installed (through the symfony/symfony replacement of symfony/var-dumper 2.8.48). Composer does not allow you to install 2 packages of the same name in different versions because PHP does not allow you to load multiple classes with the same names.

The three dependencies quite clearly should not be compatible. Symfony explicitly states that this should not be possible, as I have repeated 3 times now. This combination of packages should not be and is not installable.
