### ISSUE TITLE
Again lack of memory

### ISSUE THREAD

**Issue by StasToken** [composer/composer#7829]
Composer version 1.8.0 2018-12-03 10:31:16
OS: Ubuntu server 18
PHP 7.2.10 

>composer install 

Error:

>Loading composer repositories with package information
Updating dependencies (including require-dev)

>mmap() failed: [12] Cannot allocate memory

>mmap() failed: [12] Cannot allocate memory
>PHP Fatal error:  Out of memory (allocated 904929280) (tried to allocate 20480 bytes) in phar:///home/ubuntu/print-press/composer.phar/src/Composer/DependencyResolver/Pool.php on line 205

>Fatal error: Out of memory (allocated 904929280) (tried to allocate 20480 bytes) in phar:///home/ubuntu/print-press/composer.phar/src/Composer/DependencyResolver/Pool.php on line 205

I tried to fix it:

export COMPOSER_MEMORY_LIMIT=-1
в php.ini set memory_limit=512M
php -d memory_limit=512M /usr/local/bin/composer install 
Created swap files 200M 

And another 1001 "Изёб" - found on the Internet, not what does not help

What kind of bug? how to treat?

**Comment by curry684** [comment]
Sorry but 512MB RAM nor 200MB swap files will cut it for more complex Composer configurations. You should simply not run the solver on such extremely limited machines. And you never need to due to how locking works.

Run `composer update` on a proper development machine with a proper amount of RAM (8GB or more), with `memory_limit=-1` for CLI processes, and the solver will produce a `composer.lock` file allowing you to **deploy** fast and without issues to machines with only 512MB of RAM and no or limited swap space (200MB is useless anyway, swap should always be 100% to 200% of physical RAM).

**Comment by StasToken** [comment]
I managed to solve the problem by increasing the swap to 4GB - I don’t name it for what this amount of memory is spent on, as a person developing on php, this is not clear .... could you tell me why he has so much RAM - it’s just interesting from curiosity

**Comment by curry684** [comment]
https://en.wikipedia.org/wiki/Boolean_satisfiability_problem explains the SAT problem that products like Composer internally need to handle. Specifically how to handle an unknown number of recursive constraints (every package you include includes other packages with specific constraints) is eventually a brute force problem that boils down to evaluating hundreds of thousands or even millions of possible solutions to the original set of constraints.
