### ISSUE TITLE
Install to virtual file system

### ISSUE THREAD

**Issue by felixfbecker** [composer/composer#7838]
Hi 👋 
I digged around the code, but wasn't able to answer this question. Is it possible to invoke Composer so that it does all file system operations to a virtual file system interface (backed in memory) instead of on disk? The use case for this is fast static code analysis in a service that needs dependencies to correctly analyse a project (and, from Composer's point of view, easy and fast unit testing).

**Comment by Seldaek** [comment]
We don't support this no, but you could create/mount a ramdisk and run composer in there which would have the same result without us having to modify anything. Or you can possibly only set the vendor-dir to be in a ramdisk path.

**Comment by Seldaek** [comment]
There are tons of FS interactions all over the place tbh.. it really does not seem worth the effort and added complexity/abstractions. We have our own filesystem class, the symfony one, some chdir stuff, just off the top of my head. It really seems way easier to do this at the OS level because then the program doesn't need to know anything.

**Comment by Seldaek** [comment]
Yeah everything can *simply* be done.. except it adds complexity for something that interests only you, and then we have to maintain this. So I am sorry but no I don't see this as an option.

Regarding mapping URIs to system paths I have no idea what you mean, but for temp dir etc this can all be configured with env vars to make sure Composer writes things only within the realm of your ramdisk. (TEMP + https://getcomposer.org/doc/03-cli.md#environment-variables )
