### ISSUE TITLE
`composer update` installs new unrelated packages when specific package for update is given

### ISSUE THREAD

**Issue by JacekDziurdzikowski** [composer/composer#7841]
The issue is about unexpected behaviour of `composer update vendor/package` and/or non consistent with the docs.

Scenario: I got installed one package, e.g. `psr/log` in v1.0 which is present in my `composer.lock` and present in `vendor` directory. In my `composer.json` I have got listed packages which are not installed or no present in `composer.lock`. 

My `composer.json`:
```
    "require": {
        "psr/log": "^1.0",
        "monolog/monolog": "^1.0"
    },
```

Because in my lock file I got listed only `psr/log` in v1.0 and have got it installed, `composer outdated` prints:
```
psr/log 1.0 1.1.0 Common interface for logging libraries
```

So, when I execute command `composer update psr/log` I expect that one particular package to be updated.

Instead I get:
```
Package operations: 1 install, 1 update, 0 removals
  - Updating psr/log (1.0 => 1.1.0): Loading from cache
  - Installing monolog/monolog (1.24.0): Loading from cache
```

It looks like this behaviour is overdoing and might give unexpected effects.

The scenario in which I came into troubles with it was when someone else did an oversight and let the production code to have the `composer.json` and `composer.lock` out of sync. I wanted to install a new package and couldn't do it either by using `require` command or by manually adding new package name to require section in `composer.json` because there was an additional package in `composer.json` not installed in fact and which was causing the whole operation failure by not meeting version constraints. 

It obviously would be perfectly correct behaviour for `composer update` command but `composer update vendor/package` should rather consider only whitelisted packages. Why would this command do more if I ask just for a specific package?

I am using composer version 1.8.0 but this issue appears in previous versions as well.

**Comment by Seldaek** [comment]
This is not something we can easily fix, a partial update (which is done by `require` internally or via `update xxx`) is simply pinning existing dependencies to their version from the lock file, but it can't prevent new packages being installed if they are needed by the composer.json, otherwise we wouldn't be able to resolve dependencies.

The only safe way to do this is running `composer install` first to make sure your local state matches the lock file, and that will also warn you if you have an outdated composer.lock vs composer.json - then partial update should only do what you tell it to, except if you got that warning then you first need to make sure the warning is dealt with.
