### ISSUE TITLE
composer install fails due to hard coded hash in official install instructions

### ISSUE THREAD

**Issue by mnhassan** [composer/composer#7846]
Recently, I had noticed a Dockerfile failing with composer install.  I checked and found that they were using the older hash value, and this hash value was hard coded in the Dockerfile.

That didn't seem the right approach, and I referred to the official install instructions.  I was surprised to see that the instructions at link [Get Composer Download Site](https://getcomposer.org/download/) also had the hash value hard coded.

Interestingly, there was a "programmatically install" instruction right above, where it suggested a bash script where the hash value was downloaded from the website.  I think this should be the right approach, and I modified the install instructions with a simple ````trim(file_get_contents('https://composer.github.io/installer.sig'))```` instead of the hash value and it worked like a charm!

But this is so trivial, it seems the download instructions are kept that way deliberately.  Can someone please explain?  Or if this method is better, can we update the instructions to reflect this?

**Comment by Seldaek** [comment]
The download instructions if you copy them from the browser are safer with the hash inline because we can most likely trust your browser's HTTPS to be functioning properly. On the other hand file_get_contents might be doing insecure stuff on older PHP versions especially, so we rather not have the programmatic version be the default.
