### ISSUE TITLE
[RFC] Allow ignoring local platform

### ISSUE THREAD

**Issue by alcaeus** [composer/composer#7884]
Source of this RFC was discussion in https://github.com/dependabot/dependabot-core/pull/890. With dependabot, you can't really control the environment that `composer update` is run on. To ensure that packages can be installed, dependabot runs composer with `--ignore-platform-reqs`, unless there is a `config.platform` set in composer.json.

Setting a platform config is the recommended way to ensuring that the resulting lock file is compatible with the target system, except for one flaw: If a platform package is installed on the system that dependabot runs on, there's no useful way to disable it. I've tried the following solution locally:
```json
{
    "config": {
        "platform": {
            "ext-mongodb": "0"
        }
    }
}
```

This does what we want if we ignore the slightly confusing error message:
> mongodb/mongodb 1.4.2 requires ext-mongodb ^1.5.0 -> the requested PHP extension mongodb has the wrong version (1.5.2) installed.

The problem with this is that it needs to be repeated for every package present on dependabot systems but not on the target deployment system. It would be much easier if there was a `ignore-platform` (or other wording) option that ignores all currently installed platform packages and relies only on what `config.platform` provides.

**Comment by stof** [comment]
`"ext-mongodb": "0"` is already a valid config, saying it provides this package at version 0 (which is a valid version, even though it is weird).

And it does not do what you want in case the requirement is `*`.

**Comment by alcaeus** [comment]
> And it does not do what you want in case the requirement is `*`.

Excellent point, thank you! So the workaround doesn't do what we want either.

**Comment by DvdGiessen** [comment]
I was just bitten by this. We use the `platform` config setting to help ensure we have correct dependencies for our application to work our production server, even when we never directly run Composer on that server but only in development and CI.

Today, a new deployment was done for the first time using the new Composer 2.0, which has the platform-check feature enabled by default. This broke our application, showing a "Composer detected issues in your platform" message because the `mbstring` extension was not installed on this particular production server.

(Actually, we had previously considered that might not always be the case and depended on the popular Symfony polyfill, but that didn't help us here as one of our dependencies required `ext-mbstring: *` directly and the relevant `provide` directive is [not yet implemented in the polyfill](https://github.com/symfony/polyfill/pull/54).)

Now, while of course we shouldn't be running Composer 2.0 without checking for breaking changes, and we should have noticed a long time ago that that server was missing an extension, et cetera, et cetera, a core issue here was our assumption that dependencies had been properly checked using the  `platform` config option, which, turns out, was not the case. The `composer install` in our development and CI environments didn't throw any warning despite `ext-mbstring` not being set in the `platform` config option, because it turns out that the platform option doesn't *set* the platform, it merely *merges* over the existing one.

(To be clear, while the platform-check option exposed this problem for us, I don't have any issue with that. It did what it was supposed to do, and it was due to other circumstances (namely, this issue) that we had such an unmet dependency in the first place.)

The [documentation of the `platform` config option](https://getcomposer.org/doc/06-config.md#platform) doesn't clearly state that the specified platform is merged over the current one; I can see how I made the wrong assumption back when I started using the option.

Implementing some kind `platform-exact` option would be very useful for this use case where we want to, to quote the documentation, "emulate a production env" precisely.

Aside from the opt-in config option and tests, the actual change itself seems doable without adding significant complexity: from what I can tell, an conditional early return / splitting up the function at [`PlatformRepository.php` line 83](https://github.com/composer/composer/blob/5df1797d20c6ab1eb606dc0f0d76a16ba57ddb7f/src/Composer/Repository/PlatformRepository.php#L83) would do the trick. (Might also make a good "Good First Issue".)

**Comment by Seldaek** [comment]
@DvdGiessen the platform config does not ensure dependencies are properly checked, see more at https://github.com/composer/composer/issues/9377#issuecomment-719019204

IMO making the platform config an exact one would be a massive pain.. In a random project here if I run `composer check-platform-reqs` it lists 27 platform requirements.. so that means I'd have to list all 27 in the platform config, including lots of built-in PHP extensions to make it work. It's much easier to make `composer check-platform-reqs` part of your deploy/build process, and to use platform config to fake the presence of exts in dev if needed, which is what it was built for.

**Comment by DvdGiessen** [comment]
Quoting from https://github.com/composer/composer/issues/9377#issuecomment-719019204:

> The platform config (...) allows you to make sure that no dependencies get installed that work on your machine but won't work in production.

This does not function as described in all cases; it only works when overriding existing platform items or adding new ones. In my example I was able to install a dependency that depended on `ext-mbstring` on my machine, but which won't work in production since there that extension is not installed. It would be nice if Composer could have warned me about that.

Thus, the kind of option proposed by @alcaeus, to have an *opt-in* way of specifying an exact platform instead of only overriding part of it, would enable us to cover the case where we want to ensure the dependencies composer installs / updates during development are compatible with the *exact* platform on the production environment. :)

This would be new functionality, dealing with a different use case than the use case the currently existing platform config option deals with.

> IMO making the platform config an exact one would be a massive pain (...) I'd have to list all 27 in the platform config, including lots of built-in PHP extensions to make it work.

Correct, for this to have the desired benefit, listing the entire platform would be required, because only then Composer can reliably check whether all the platform requirements of all dependencies are met. This new option would of course have to be opt-in, so one only has to deal with this if explicitly choosing to use this functionality.

The list of platform items, although long, can be readily generated using the existing `show -p` subcommand.

> It's much easier to make `composer check-platform-reqs` part of your deploy/build process

Yes, but this has two disadvantages:

- You only find out some of your dependencies are incompatible once deploying, not while installing/updating dependencies during development.
- It requires us to push the new version to the production server and run then Composer on the server to perform the check, adding complexity to the deployment which could be handled elsewhere.

Note it can not necessarily be done as part of the build process, since the goal is to check the dependencies against the production environment, not the build environment, which in many cases will not be on the same server.

**Comment by Seldaek** [comment]
Closing this as I don't think we'll do it.. And https://github.com/composer/composer/issues/9664 partially added a way to do it by excluding everything that's installed or that you know you don't have on prod that might be problematic.
