### ISSUE TITLE
Deprecation warning for package names of form vendor/directory/package

### ISSUE THREAD

**Issue by adam-maus** [composer/composer#7938]
Summary: 
I receive deprecation warnings for package names of the form `vendor/directory/package name`.

My `composer.json`:

```json
{
	"name": "foo/bar",
        "require": {
		"foo/themes/bar-1": "1.*.*"
        }
}
```

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.8.3
PHP version: 7.2.14
PHP binary path: /usr/bin/php7.2
```

When I run this command:

```
composer update
```

I get the following output:

```
Deprecation warning: require.foo/themes/bar-1 is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9]([_.-]?[a-z0-9]+)*". Make sure you fix this as Composer 2.0 will error.
```

And I expected this to happen: No Warning

Description:
One of our vendors organizes their packages into a directory like structure i.e. "foo/plugins/bar-1" and "foo/themes/bar-1" which is throwing deprecation warnings like the one above. The original reason for this warning appears to be here: composer/issues/7874

Could the regular expression used to validate the package name be updated to include multiple forward slashes? Unless I mistaken, I think the updated regular expression would look something like this: `(([a-z0-9]([_.-]?[a-z0-9]+)*/)+[a-z0-9]([_.-]?[a-z0-9]+)*`

This would help for vendors that organize their packages into a directory structure or if the vendor utilizes groups (and subgroups) within Gitlab.

Thank you for your time and help, I appreciate it.

**Comment by stof** [comment]
I think the validation added for #7874 was meant to reject any package name that is not valid on package.

> if the vendor utilizes groups (and subgroups) within Gitlab

I don't see what the Gitlab groups have to do here. We are talking about the composer package name, not about the package URL.

**Comment by adam-maus** [comment]
Thank you for the response and you are right. In my case, this vendor decided to set their package names to mimic their urls so `foo/plugins/bar-1` is used in both the URL and the package names on their instance of Gitlab. That was where I had made that assumption about Gitlab (oops). 

In preparation for Composer 2.0, I can imagine that the vendor could simply update their package names to something like `foo/plugins-bar-1` and `foo/themes-bar-1` then, is that correct? If so, both client and vendor would have to update their composer files because of an update to Composer. This is not unmanageable but could be surprising even with the warnings.

But, I am curious (and not very smart...), what benefits are there for `vendor/package` over letting there be multiple forward slashes like `vendor/directory/package` within the package name?

**Comment by stof** [comment]
@adam-maus Packagist does not allow multiple slashes, because it would impact the way Packagist URLs look like (many pages have a package name in the URL). That's also the reason why a package name ending in `.json` is not allowed on Packagist (we had bugs in the past due to ambiguous routing where `/packages/foo/bar.json` could either be the JSON version of `foo/bar` details, or the HTML details of `foo/bar.json`).
Allowing multiple slashes on Packagist would require a lot of investigation first to be sure we never end up with ambiguous routing (and the result of this investigation might still be a NO). At the composer level, there is no issue with multiple slashes (or with no slashes)

> This is not unmanageable but could be surprising even with the warnings.

Well, composer 2.0 is not yet out there. So this warning coming out now is precisely meant to give time to prepare for it.
And note that such package name is already forbidden on Packagist (so not a good naming convention for open-source packages) since years. And `composer validate` also warns about it since years (since Packagist forbids it).

**Comment by Seldaek** [comment]
These non-standard package names have caused issues in different tools around Composer even tho Composer supported them, that's the main reason we decided to deprecate them, to avoid bugs when encountering rarely-seen package names. Please reach out to your package vendor.

**Comment by adam-maus** [comment]
That all makes sense, thank you for taking the time to explain that. I will talk to our vendor about changing their package names.

And I definitely get it, Composer 2.0 is a major version change so you shouldn't expect things to work exactly like before.

Thanks for the help!
