### ISSUE TITLE
Don't use abandoned phpunit/phpunit-mock-objects package

### ISSUE THREAD

**Issue by alecpl** [composer/composer#8099]
The same as in https://github.com/composer/semver/issues/66 composer should not use abandoned packages. Now throws a warning `Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested`.

It's not nice to display a warning that user can do nothing about.

**Comment by alcohol** [comment]
I am not sure where this requirement stems from. It has been there for a long time, but in theory it is not necessary since phpunit/phpunit pulls in the same dependency in older version. I very recently dropped this requirement in our semver library: https://github.com/composer/semver/commit/74ef3203909c3306d8078365d3cdf90bf223d3b5

I think we can drop it in composer too. But honestly this should not bother a lot of people. It is merely a warning, and only people who directly require `composer/composer` will be hit by this (which is almost nobody). So, no harm for now. We'll look at this some time in the future.

**Comment by stof** [comment]
Thus, composer only has a *dev* requirement on it, so it should not even affect you if you require composer in your project, as dev requirements are root-only.

**Comment by alcohol** [comment]
Yeah that too. :thinking:

**Comment by Seldaek** [comment]
$ c why phpunit/phpunit-mock-objects
phpunit/phpunit  4.8.36  requires  phpunit/phpunit-mock-objects (~2.3)

So we can't fix this until we drop phpunit 4.8, which means dropping php 5.3 and co.

**Comment by alcohol** [comment]
@Seldaek but do *we* need to specify it as our own dependency?

**Comment by Seldaek** [comment]
Need nope, but I tried removing it and it does not change anything, so will deal with this later when upgrading phpunit

**Comment by stof** [comment]
the explicit requirement was added in the past to workaround bugs in some versions with HHVM: https://github.com/composer/composer/commit/e2b183136c0ca3606acf0c211ef80407d42a0a9e

this is likely not relevant anymore.
