### ISSUE TITLE
How to hide reading of repositories

### ISSUE THREAD

**Issue by szepeviktor** [composer/composer#8112]
This is the output on GitHub CI
![kép](https://user-images.githubusercontent.com/952007/56787152-eb153a80-67fb-11e9-9541-189b17a7f1c6.png)

Is there a way to hide these messages?

**Comment by szepeviktor** [comment]
`--noprogress` didn't help

**Comment by alcohol** [comment]
Does it matter? Also can you not use screenshots? Just copy the exact command you are running and the actual log output. Thanks.

**Comment by alcohol** [comment]
You can disable those messages (but also pretty much everything else) by passing `--quiet`.

**Comment by szepeviktor** [comment]
Thank you.
That is sad news.

**Comment by alcohol** [comment]
Yeah.. I have mixed feelings about this myself. They should probably be moved behind at least 1 level of verbosity to be honest (`-v`).

But on the other hand, because they are some of the slowest steps in the whole process, I think there is also merit to always showing them. It gives the user a sense of progress.
