### ISSUE TITLE
askAndHideAnswer() shows typed Password

### ISSUE THREAD

**Issue by hannsen** [composer/composer#8119]
It asked my for my Gitlab password, and as I typed the password appeared on screen. It should have either been **** or just not show any characters at all, in my opinion.

**Comment by alcohol** [comment]
Can you share more about your environment?

**Comment by hannsen** [comment]
Windows 10 Pro

mingw64 git-bash (when you install git for windows you get this)

PHP 7.2.10 (cli) 


Not sure what more I can say

**Comment by alcohol** [comment]
@Seldaek any idea if the windows binary would not work in such an environment?

**Comment by Seldaek** [comment]
Normally this works everywhere but eh maybe not, there are so many ways to have a shell on windows it's kinda hard to cover all ground.

**Comment by hannsen** [comment]
It works on the windows command line, yeah. But not in git-bash

**Comment by hannsen** [comment]
I just tried this with a barebones symfony application and set a question so setHidden(true), and it did not show me the typed in data. But when I use composer it will show the typed data. Maybe composer is using an old symfony version?

**Comment by hannsen** [comment]
it still happens.. 
![grafik](https://user-images.githubusercontent.com/3775136/96164481-91d32680-0f1b-11eb-98dd-4eecb1ce8341.png)

**Comment by Seldaek** [comment]
And I still have no idea what to even do about it. mingw used to work last time I used it, but it might depend on the terminal emulator you use on top of it, or god knows what. In any case we should soon upgrade symfony components to latest in composer 2.1 or 2.2, so that'll hopefully help you. It's just not something we will actively fix in composer as it's handled upstream.
