### ISSUE TITLE
How do I solve conflicts when two parts of my system in the same run-time require the same dependency?

### ISSUE THREAD

**Issue by sproutwp** [composer/composer#8176]
Sorry this isn't an issue about Composer, but I just started using and struggling heavily. I've made big contributions to projects I had issues with in the past so, hopefully, in the future I can pay it back.

I have created my framework with modules, as I developed more, it occured to me that these modules could be composer packages themselves. So I started going at it.

My framework's base includes a `ServicesProvider`, `Cache`, `CacheGraph`, `Events`, `Identity` and other things that help me glue WordPress in what it should've been from the beginning. I want to make use of `ServicesProvider` outside too.

**The problem is, my framework is a plugin and I want to make use of `ServicesProvider` inside of my theme, before the plugin is enabled.**

Here is how my `ServicesProvider`'s `composer.json` looks like:

```
{
    "name" : "sprout/services",
    "description" : "A service provider used by Sprout",
    "version" : "1.0.0",
    "keywords" : [
        "service",
        "service provider",
        "wordpress service provider"
    ],
    "require": {
        "sprout/sprout_privileges": "1.0.*"
    },
    "autoload": {
        "psr-4": {
            "SproutServices\\": ""
        }
    }
}
```

A package that will simply autoload everything in the namespace of `SproutServices` in that directory. As such, when it's autoloaded by the `autoload.php`, I'll have access to `use SproutServices` whenenver my first **package that uses it as requirements autoloads it, but what about the next?**

What do I do if both my theme and the framework require it and they also happen to run in the same space? I will hit `Class is defined somewhere else` conflicts. How do I tell Composer to "oi, matey, if this requirement is already loaded, use that, don't try to load it again".

Thank you and sorry. I promise to make good use of this information and help more if I can. I have read the full Composer documentation, the generated files and don't understand how I can solve it.

**Comment by greg-1-anderson** [comment]
Composer does not solve this problem directly. You should avoid including an `autoload.php` file as a basis for a plugin mechanism, as such a design is fragile and fraught with peril. See [the trouble with two autoloaders](https://pantheon.io/blog/trouble-two-autoloaders).

There are various strategies. In general, Composer presumes that all of your plugins should be `composer require`-d into a single vendor directory. From there, you can discover your plugins by whatever means you wish. This is the technique that [Robo](https://github.com/consolidation/robo) uses. I believe that Symfony Flex uses a similar strategy.

You could consider including a `autoload.php` file if you first validate it to ensure that there will be no problems (conflicting dependencies) if it is included. This is what [Terminus](https://github.com/pantheon-systems/terminus) does. This method is not very flexible, though, and it essentially boils down to saying that your plugins cannot have dependencies of their own, and must rely on whatever the main application provides.

At one time, the Sculpin project used something called [embedded composer](https://github.com/dflydev/dflydev-embedded-composer) to attempt to resolve Composer dependencies for plugins on the fly. This technique was abandoned by Scuplin because it was difficult to maintain.
