### ISSUE TITLE
Fail validation when platform constraints are missing

### ISSUE THREAD

**Issue by localheinz** [composer/composer#8218]
As suggested on Twitter (https://twitter.com/localheinz/status/1148868388917272576), perhaps it makes sense to expand the validation of `composer.json` to the specification of platform requirements?

That is, fail the validation when a requirement for `php` (is `hhvm` still relevant?) has not been configured. 

I’ve come across (closed-source) projects where these have been missing. 

I’d be normally happy to open a pull request, but I’m on vacation and only have my phone with me.

**Comment by alcohol** [comment]
Are you talking about `composer validate --strict` ?

**Comment by localheinz** [comment]
@alcohol 

Does that fail when the `require` section is missing an entry for `php`?

**Comment by alcohol** [comment]
No I was merely asking if you could elaborate on what "fail validation" meant.

**Comment by Seldaek** [comment]
IMO being overly strict doesn't bring a lot, the people who don't have a php requirement most likely also don't run validate. We could emit warnings non-stop like npm does but then I also don't see a lot of them being fixed in npm packages so I doubt this is a successful strategy either. People not caring are the problem here I'd say..
