### ISSUE TITLE
FFI and package type considerations

### ISSUE THREAD

**Issue by rask** [composer/composer#8230]
With FFI around the corner, we can expect PHP packages that make use of it.

I'm wondering if packages that utilize FFI and C-ABI libraries should be differentiated from "regular" PHP packages (e.g. `library` and `ffi-library` or something)? This is hard to enforce, obviously.

Also how portable are FFI-packages going to be? Can I install the same FFI-package on Linux and Windows all the same assuming dependencies work?

Should Composer do some prerequisite checks for FFI-library dependencies akin to `configure` when building software ('lib-zlib not found`, etc.)? Can/should Composer invoke build tools to build a C-ABI library from source upon FFI-package installation?

How often will people bundle compiled C-ABI binaries into their PHP packages? How can interoperability be ensured across systems?

I know some of these are not problems for Composer to solve, just brainstorming here. I just would hate to see FFI-powered packages devolve into a mess when used with Composer.

**Comment by stof** [comment]
I think that this is too early to discuss in composer itself, as we don't know yet how a FFI package would look like.
If some special installation is needed for them, this should first be experimented using a dedicated installer developed out of composer (it is much easier to experiment in a third-party installer plugin than in core). And what kind of special installation is needed might even depend on the packages.

**Comment by rask** [comment]
Right you are, did not even think about custom installers. Those would probably be the sanest choice first.

**Comment by Seldaek** [comment]
Yup I think we're still a long way to having this be common enough, but definitely worth keeping an eye on..

**Comment by Seldaek** [comment]
Closing as I don't think we will ever do anything here. But if you disagree please do say we can reopen, I just haven't seen much FFI used in the wild which tells me it's still a fringe use case.

**Comment by dhernandez** [comment]
Hello @Seldaek.
I've built a FFI library for DuckDB and not sure which is the best option to release with composer/packagist. As you can see in this thread https://github.com/satur-io/duckdb-php/issues/12, our main issue is to provide the native C libraries to users since they are OS dependent. Maybe you could reopen this issue to discuss it. Thank you.

**Comment by spinitron** [comment]
As a user of @dhernandez wonderful duckdb package it seems to me the options are as follows

1. don't include duckdb lib in the PHP package
2. include bins for all os ⨯ arch
3. composer does something to help

As sysop of my own servers I'm used to having to manually and separately install and configure things that depend on each other. So I'm OK with Option 1. But I do understand that this may be a problem for pure coders.

As sysop of my own servers used to having to manually install and configure things, Option 2 is offensive. I can do better than that with a few lines of Salt or Ansible.

```
debian in 🌐 ark4 in vendor/satur.io/duckdb on  main via 🐘 v8.4.10
❯ du -sh *
4.0K    LICENSE
4.0K    aliases.php
4.0K    composer.json
368K    docs
56K     examples
4.0K    info.php
272M    lib
4.0K    phpbench-local.json
16K     scripts
312K    src
228K    test

debian in 🌐 ark4 in vendor/satur.io/duckdb on  main via 🐘 v8.4.10
❯ du -sh lib/*
58M     lib/linux-amd64
54M     lib/linux-arm64
101M    lib/osx-universal
30M     lib/windows-amd64
32M     lib/windows-arm64
```

**Comment by dhernandez** [comment]
Thanks for contributing to the discussion @spinitron 😄.

For the versions released until now, I included all bins in the package mainly because of two reasons: 

- It's the best option I found to encourage developers to start playing with DuckDB in PHP. Anyone can use the package just running a simple and standardized `composer require`.

- 270MB shouldn't be a real blocker nowadays.

It's an early development package so getting new users, getting feedback, finding and fixing bugs, etc. is more important at this stage than an storage-optimized installation IMHO.

But of course including all bins is not ideal, hence the requirement for a native composer solution that combines the simplicity of getting started with the package with no additional steps and some production-optimized options, such as installing the library by yourself and setting the path e.g.

**Comment by fredden** [comment]
Perhaps this is a good use-case for [the "provide" feature](https://getcomposer.org/doc/04-schema.md#provide) that Composer already supports.

So, splitting up the parts into a PHP-only package (eg, `your-vendor/duckdb`) which has a `require` entry for a virtual package (eg, `your-vendor/duckdb-library-implementation`), and a set of packages (eg, `your-vendor/duckdb-library-ubuntu-i386`, `your-vendor/duckdb-library-rhel-amd64`) which all `provide` the virtual package.

**Comment by Seldaek** [comment]
Yeah what @fredden said is the best IMO, that way consumers would have to require your library AND one of the duckdb-library-* packages to satisfy that dependency.

**Comment by dhernandez** [comment]
Thanks a lot @fredden and @Seldaek.

The provide feature looks as a good option. I need to check how to split the repo, since I would like to avoid making manual releases for each lib package. I think this should be doable by adding some workflows, but it will take some time. I'll keep you posted as I progress.
