### ISSUE TITLE
Remove package that's both directly require'd and indirectly require-dev'd

### ISSUE THREAD

**Issue by sserbin** [composer/composer#8263]
My `composer.json`:

```json
{
    "name": "sserbin/composer-test",
    "description": "composer test removal",
    "type": "project",
    "license": "MIT",
    "require": {
        "php-http/guzzle6-adapter": "1.1.*",
        "knplabs/github-api": "^2.3"
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.9.0
PHP version: 7.1.30
PHP binary path: /usr/bin/php7.1
```

When I run this command:

```
composer install
composer remove php-http/guzzle6-adapter
```

I get the following: the package is removed from `composer.json` but is still present in `composer.lock` (under `packages` section). Presumably this happens because `knplabs/github-api` `require-dev`s the same package (`php-http/guzzle6-adapter`)

And I expected this to happen:
Either the package is removed from `packages` of `composer.lock` (and is added as `packages-dev`?) or composer notifies me that it can't satisfy the removal request. 

Also, just for reference, 1.8.0 also didn't include such "removed" package in `autoload_psr4` (`1.8.6+` does include it)

**Comment by xabbuh** [comment]
The fact that the package isn't removed looks reasonable to me as `knplabs/github-api` requires a package providing `php-http/client-implementation`.

**Comment by alcohol** [comment]
I think @xabbuh is correct.

**Comment by sserbin** [comment]
> The fact that the package isn't removed looks reasonable to me as knplabs/github-api requires a package providing php-http/client-implementation.

technically, they only require specific implementation as dev dependencies though. I agree the fact that it's not removed is reasonable (to an extent), but I was more asking if moving it into packages-dev or showing a note would be a better behavior.

**Comment by xabbuh** [comment]
The important part is not the dependency on `php-http/guzzle6-adapter` in their `require-dev` section, but the fact that it requires `php-http/client-implementation`:

```json
"require": {
    "php-http/client-implementation": "^1.0"
}
```

You would see the same behaviour if, for example, you had `php-http/buzz-adapter` instead.

**Comment by alcohol** [comment]
> technically, they only require specific implementation as dev dependencies though

But dev requirements of dependencies are completely ignored by Composer, so that is not relevant. They only have that for their own development and testing purpose.

They do require a package that provides `php-http/client-implementation` however. And since you have one installed currently, Composer will not remove it.

The following illustrates this as well:

```
rob@thinkpad ~ $ cd $(mktemp -d)
rob@thinkpad /tmp/tmp.exHdYfppz1 $ echo {} > composer.json
rob@thinkpad /tmp/tmp.exHdYfppz1 $ composer require knplabs/github-api
Using version ^2.11 for knplabs/github-api
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for knplabs/github-api ^2.11 -> satisfiable by knplabs/github-api[2.11.0].
    - knplabs/github-api 2.11.0 requires php-http/client-implementation ^1.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
```

**Comment by sserbin** [comment]
Ok, yeah, that makes sense. Just did exactly that ^ @alcohol to verify it :)
Thanks!

**Comment by sserbin** [comment]
I still suppose it'd be useful to warn about that when you try to remove such package, but not a deal breaker.

**Comment by alcohol** [comment]
I think that is because removing it from `composer.json` and then running the solver again are two steps that are not directly linked together. And since both succeed, it is a bit confusing from a user perspective. The solver merely runs an 'update' with the new `composer.json`, and determines that the current set of installed packages still fulfills all requirements. So hence it does not actually remove the package. I think that is probably because of how `provides` sprinkles some extra magic into the mix. @naderman do you think we could detect this scenario and return some feedback to the user here?

**Comment by naderman** [comment]
I think this is something that will really only be fixable in Composer v2 where the vendor dir's installed.json is no longer used as solver input. We'd probably still need to somehow remove the package from the composer.lock package list which is used as input to the solver still, so that it doesn't just pick it cause it's still there. So @alcohol can you make a separate new ticket for 2.0 that more clearly explains the issue?

**Comment by alcohol** [comment]
I would if I understand what exactly is going wrong..

Starting from scratch and just a requirement for `knplabs/github-api`, Composer would determine that it requires a meta package for which currently no actual implementation is chosen, and thus it cannot proceed installing.

Given a requirement on `knplabs/github-api` and a requirement on a concrete implementation that `provide`s `php-http/client-implementation`, the solver runs its usual course and installs everything.

But then, when you run `remove`, it will drop this requirement from the `composer.json` and trigger the solver, which at this point looks at our project requirements but also at `installed.json` (or only the latter?), and then concludes that all requirements are met, and there is no valid reason to uninstall the concrete implementation because it is still needed? Is that roughly what is happening, or?

**Comment by naderman** [comment]
Yes exactly. The solver currently takes remote repos like packagist.org into account but also local repos like composer.lock and installed.json. And while for remote repos it doesn't install anything that's not directly required, there is no such filter for anything that is already installed.

**Comment by alcohol** [comment]
I did my best, feel free to edit it :d
