### ISSUE TITLE
Allow us to create our environments

### ISSUE THREAD

**Issue by steevanb** [composer/composer#8288]
Hi !

Today, we have 2 envs in composer : `prod` (`require`) and `dev` (`require-dev`).
For example, if i don't want phpunit in `dev` but only when i'm building my application, i can't, because composer is limited to this 2 environments.

Could you allow us to create our environments?
Travis could have it's `build` env, developers their `dev` env etc.

Another question, not linked to the one above: i've seen some commits related to Composer 2.0, do you have any informations about that? When it will be released and the changelog?

Thanks!

**Comment by alcohol** [comment]
The `require` and `require-dev` are not directly related to the concept of "environments".

`require` declares libraries you need for your application to run (be that in a development environment, staging/acceptance or production).

`require-dev` declares libraries you need for your development *process*. E.g. phpunit to run your test suite.

> Could you allow us to create our environments?

No, as there is no such concept as environments for Composer.

> do you have any informations about that? When it will be released and the changelog?

There is no timeline or roadmap set in stone. It is a work in progress, and it is quite extensive.

**Comment by alcohol** [comment]
For your scenario, you could create a `composer.ci.json`, and assign that to the environment variable `COMPOSER` in your build pipeline. Composer will then use that file to resolve dependencies instead of `composer.json`. Just be mindful that this might result in a different set of dependencies which could result in false positives or negatives of your build process.
