### ISSUE TITLE
VCS repositories with the format git@github.com:/my/repo behave differently to git@github.com:my/repo

### ISSUE THREAD

**Issue by greysteil** [composer/composer#8309]
Specifically, the former will fall back to using HTTPS to fetch the repository if git authentication fails, while the latter won't. 

We're seeing this on Dependabot, where we have git configured to use credentials when using HTTPs, but don't have any SSH tokens. URLs of the format `git@github.com:my/repo` work fine with this setup, but those using `git@github.com:/my/repo` (note the `:/`) don't.

**Comment by stof** [comment]
this is because the case with `:/` does not match the regex at https://github.com/composer/composer/blob/f0d565bb6d354331cadf12712b4f6e8ebbaf51a6/src/Composer/Repository/Vcs/GitHubDriver.php#L50 (or rather at https://github.com/composer/composer/blob/f0d565bb6d354331cadf12712b4f6e8ebbaf51a6/src/Composer/Repository/Vcs/GitHubDriver.php#L270 but this is the same regex) and so won't be detected as a github repository (with the support for github-specific features like this fallback) but will use the raw git support instead.
