### ISSUE TITLE
[Feature Request] Composer.php class + Di Container + Event Injector

### ISSUE THREAD

**Issue by 6562680** [composer/composer#8319]
1) Hello, often coders complains in supported channels that there is the problem to replace outdated/bad dependency of some library in their personal project.

Would be great if you think about convert composer.json into wrappable Php class that we can extend or merge dynamically. We still using require_once 'vendor/autoload.php' - why not to use Composer->mergeConfig() ? Why not to extend ComposerConfig class where can i replace dependencies for specific vendors? Yes, its breaks out the library tests, but, hey, it breaks when i fork/copy it and replace with my own libraries. I just spending 3 hours to mirror the library. If you know what you doing, why not?

2) So, we have class autoloader. In simple, we have event that handles "new" of each class but only first time. Why not to update composer to make it globally dependency injector of the project? How about THIS next step?

3) And really crazy idea. Regarding (2) we should write injection config for the classes. So, if we write DYNAMIC DECORATOR that has __call() + __callStatic() methods - we (possible, am not sure finally) can use our config to wrap required classes into anonymous decorator that can use own method implementation - for example - adding EVENT to separated functions - begin/end. Even certain functions. Of course there should be code generator that copies other non-modified methods to avoid __callStatic() delay (on 100k calls _callStatic works 10 times slower than directly call). It should not be solution to create events, but it could be solution to fast change certain working projects without rewriting it - you just listen/pipe arguments and then listen/pipe return to do something. Prefer listen because of solid, but for really... legacy... projects you can just fix some errors (you'll get some pain later), but today your project is fixed.

**Comment by stof** [comment]
Your second point seems like a crazy idea (a bit in the spirit of what https://github.com/nicolas-grekas/Patchwork did in the past), which does not belong to Composer itself (it has nothing to do with resolving dependencies here, as your suggestion would be something happening at runtime). You can already do things like that by using your own autoloader instead of the one generated by composer.

> So, we have class autoloader. In simple, we have event that handles "new" of each class but only first time. Why not to update composer to make it globally dependency injector of the project? How about THIS next step?

This is not what a class autoloader gives you. The autoloader will be triggered by the first usage of a class. It may be because of `new` (but you still cannot hook into the instantiation itself), but it may be something else (extending the class, or even just calling `class_exists`). An autoloader is not an AOP system (even though an AOP system for PHP will often *use* a custom autoloader to be implemented, the main feature is not triggered by the autoloading).

> Would be great if you think about convert composer.json into wrappable Php class that we can extend or merge dynamically.

So you would like to download arbitrary code from any version of any package registered on packagist and execute it to know what the composer metadata of the package are ? Hopefully you don't care about the security of what happens on your machine. There are very good reasons why the metadata are a static file, and security is one of them (being able to aggregate metadata in Packagist is another one).

**Comment by 6562680** [comment]
Thanks for the answer. Then i closing. Np.
