### ISSUE TITLE
error win10

### ISSUE THREAD

**Issue by xuhaihui** [composer/composer#8426]
use composer

 [ErrorException]
  proc_open(NUL): failed to open stream: No such file or directory

I don't know how to solve this problem

**Comment by S-Tian86** [comment]
> This is probably one of the 3 issues if your using windows 10.
> 1- Php version below 7.2
> 2- Window null issue mentioned by [above](https://github.com/composer/composer/issues/7186#issuecomment-373134916)
> 3- Ur Project is in One Drive and the File System is not supported.
> 
> I solved it by moving the project out of the One Drive Directory.


> Thank you so much @isheraz. The OneDrive issue solved it. My students will be very happy....

El proyecto siempre lo he tenido en la carpeta de One Drive, pero ahora después de que actualicé Windows a la version 1909 me falló. Moví el proyecto a otra carpeta y volvió a funcionar. Muchas gracias.

**Comment by yangjiafei** [comment]
This problem i have solved. find the system file 'C:/windows/system32/drivers/null.sys'.  use other right file replace it. My system is win10，After I installed the wamp3 （but it no run）.    Compoer can't  be used. It say 'proc_open(NUL): failed to open stream: No such file or directory'.   At the same time,  git bash  automatically close when i open it.  never can open for more than three seconds,      and the file mintty.exe.stackdump be created in the folder where i open the git bash.   after i replace the null.sys use a new one,  'sc query null ' display STATE is RUNNING.

This is  reference material :  https://www.jianshu.com/p/1642eedab81b

**Comment by carouselcarousel** [comment]
> This problem i have solved. find the system file 'C:/windows/system32/drivers/null.sys'. use other right file replace it. My system is win10，After I installed the wamp3 （but it no run）. Compoer can't be used. It say 'proc_open(NUL): failed to open stream: No such file or directory'. At the same time, git bash automatically close when i open it. never can open for more than three seconds, and the file mintty.exe.stackdump be created in the folder where i open the git bash. after i replace the null.sys use a new one, 'sc query null ' display STATE is RUNNING.
> 
> This is reference material : https://www.jianshu.com/p/1642eedab81b


Is there anyone who have the null.sys which needs to be changed? File has been removed.

Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\DOS Devices\
NUL = \Device\Null

When I try to run "sc start null"
[SC] StartService FAILED 1058:
The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.

Also tried creating the folders but diddn't worked.
C:\dev\null
C:\Program Files\git\dev\null

I have the same problem (After windows update). It's worked before. Now can't even isntall the latest version  Git-2.41.0.3-64-bit.exe .
