### ISSUE TITLE
feature: add calendar versioning support

### ISSUE THREAD

**Issue by ghost** [composer/composer#8436]
And I expected this to happen:

composer to not be tightly coupled to only one versioning scheme. least of all semantic versioning, makes me and (I deduce) others nauseous.

----

its really annoying that versioning is decided by composer or whatever is the thorn here. I think package dependency management should be more flexible.

----

asd-collab

**Comment by asd-collab** [comment]
if this a permanent limitation, let me know. I'll find another open-source language to use.

I wanted to try exploring php more as its a scripting language like python, but was built to be used for web development. And its easier to read than python.

---

asd-collab

**Comment by alcohol** [comment]
We support date versioning ( see https://github.com/composer/semver/blob/master/src/VersionParser.php#L135-L139 ) but it is discouraged because semantically it means nothing.

Semver is the defacto standard for anyone developing libraries that are meant to be used by others for good reason.

If you're versioning your own project for personal use however, you can version it any way you want. Nobody will care.
