### ISSUE TITLE
`composer global exec` does not seem to run commands in the current directory

### ISSUE THREAD

**Issue by cdayjr** [composer/composer#8481]
When I run this command:

```
composer global exec -v -- phpcs test.php
```

I get the following output:

```
Changed current directory to /Users/cdayjr/.composer
> __exec_command: phpcs 'test.php'
ERROR: The file "test.php" does not exist.

Run "phpcs --help" for usage information

Script phpcs handling the __exec_command event returned with error code 3
```

And I expected this to happen:
(output of calling `phpcs` directly)
```
FILE: test.php
------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------------------------------------------
 11 | ERROR | Assignment in if condition is not allowed.
    |       | (SlevomatCodingStandard.ControlStructures.AssignmentInCondition.AssignmentInCondition)
------------------------------------------------------------------------------------------------------------------------------------------------

Time: 114ms; Memory: 10MB
```

**Comment by Seldaek** [comment]
This is a tricky one, because `composer global` indeed does change the working directory (as the first line of output indicates). So if you are trying to run exec in the global dir, you wouldn't want this "problem" fixed. But in your case it's indeed a problem. 

I'd say the better approach though for you, if you want to set up global utils, is to make sure you add the global bin-dir to your PATH, so you can directly execute `phpcs` anywhere. That's much more useful..

**Comment by cdayjr** [comment]
Is there any use case to running the binaries from `exec` in the global directory regardless of the user's current working directory? I understand that's the behavior of `composer global` for other commands but it seems strange for `exec`.

Adding the global bin directory to the `PATH` is a fine solution if I'm only concerned with my environment, but I want to make sure some scripts I'm writing can run in anyone's environment once composer and the required packages are installed.

Currently I can work around it like this, but it seems weird when there's a nice `exec` command I could be using.

```sh
COMPOSER_GLOBAL_ROOT=$(composer global config -q home)
PHPCBF="$COMPOSER_GLOBAL_ROOT/vendor/bin/phpcbf"
PHPCS="$COMPOSER_GLOBAL_ROOT/vendor/bin/phpcs"
```

**Comment by Seldaek** [comment]
I'd get bin-dir instead of home, that's more portable, but anyway yes.. I really can't tell what the possible use cases would be. I tend to agree with you it's most likely more useful to run things in the local dir. I am not sure how to implement this though, as the global command runs a chdir then calls the command you pass it, but it does this in a very oblivious way.

**Comment by Seldaek** [comment]
Perhaps there is a way to store on the Application that we had a previous workdir which has been changed, so exec command can read that if it's there.. kinda nasty hack but would work. Anyway if you feel like experimenting and sending a PR, I'd say why not if it's a reasonable solution.

**Comment by cdayjr** [comment]
Thanks, I'll look into it. 👍
