### ISSUE TITLE
what the hell is this composer made php very hard

### ISSUE THREAD

**Issue by atta1234** [composer/composer#8491]
when you run every time you will get some sort of errors

**Comment by ENM1989** [comment]
#lol

**Comment by remotelyliving** [comment]
![giphy](https://user-images.githubusercontent.com/2728347/71315588-2f121b00-242f-11ea-8841-814aa7ae92d0.gif)

**Comment by theofidry** [comment]
@atta1234 if you have some constructive feedback you are free to give some, but just trolling an OSS project because you had trouble with it (be it legitimate or not) is both extremely disrespectful and of poor taste. You are only contributing to making OSS more toxic and causing unnecessary strain on people spending their free time on it. Please delete your issue and think again before posting any of those
