### ISSUE TITLE
Windows installer blocked Anti virus

### ISSUE THREAD

**Issue by JBlond** [composer/composer#8532]
When I try to install the Composer-setup .exe it gets blocked by the anti virus program. I made an upload to Virustotal https://www.virustotal.com/gui/file/80422fef0ea310c0f565d6028f34010eeebc96a4edec3175156d85f4f0eeef10/detection

**Comment by johnstevenson** [comment]
This is getting tedious. The latest versions of Composer-setup.exe (5.0.0 and 5.1.0) use a new version of the Inno Setup installer program, which is possibly why these false positives are showing.

Version 5.0.0 showed similar results, but after reporting the errors to the vendors, it now looks good on VirusTotal: https://www.virustotal.com/gui/file/6a0b75feaf3823a1054274a362bdd92b9687b265c0f0ff782741853c7995cdd8/detection

When I first released 5.1.0 (on January 1st), VirusTotal gave it a clean bill of health, but this seems to have changed so I have once again reported the errors to the vendors.

These false positives do make one question the proficiency of some engines, because all four mentioned (Avira, F-Secure, Ikarus, Sangfor Engine Zero) give a clean bill of health to the `composer.nupkg` Chocolatey package, which is essentially a zip-archive that includes Composer-Setup.exe

https://www.virustotal.com/gui/file/827b6bc31ab6499f8db3b38d8ade1192dc927bff98819febff79a9ee4d843347/detection
