### ISSUE TITLE
Change breaks support for older git-versions

### ISSUE THREAD

**Issue by tomasnorre** [composer/composer#8598]
This commit: 
https://github.com/composer/composer/commit/0bd3f27693530e41b98d7b835adf37302bc6e968

Breaks compatibility with older git versions. 

I don't know in which version from `git` the `-c` parameter got introduced, Would expect in 2.0.0, it isn't in 1.7.1 which lead me to the breaking change. 

Getting following error on `composer install --dry-run`, 
verbose says that no valid `composer.json` is found, but `composer validate` doesn't report anything

```
Skipped branch master, DateTime::__construct(): Failed to parse time string (@) at position 0 (@): Unexpected character
```

Summery:
https://twitter.com/tomasnorre/status/1227538070154686469

**Comment by alcohol** [comment]
So update your install of git. You're several years behind already.

**Comment by tomasnorre** [comment]
I sort of agree, but it's still breaking ;) and not all systems are easy to update. 
Cannot risk destroying my build server.

But have reverted my composer version for now, and then I'll check if updating git is possible.

**Comment by alcohol** [comment]
I understand that some legacy systems are hard to maintain and are barely kept up to date.

When it comes to external tooling, we kind of just go with what seems reasonable. Perhaps we can document somewhere what the minimum required versions are. But it's hard to keep track and even harder to get users to actually pay attention to it, so I'm not sure if that effort is even worth it.

You pretty much only need git if you have dependencies that are unversioned or sources which don't offer dist files (e.g. private non-github git repositories). Because for everything else, we can just use zipfiles.

**Comment by tomasnorre** [comment]
I know, I also don't what to argue with you, I'm totally on you side. 

Was just surprised that my setup al the sudden broke.
But the problem is for sure more mine than yours. 

Just hoped there was an easy fix, to get this supported. 

And to be honest, didn't know my git was that old.

**Comment by alcohol** [comment]
Yeah no worries at all, I did not perceive your response as arguing.

If you can manage to get a Docker daemon running on your build server, you could solve a whole lot of your tooling issues as it is much easier to support different versions using different containers.

**Comment by tomasnorre** [comment]
I'm trying to get rid of the Build server, so will try to lowest effort to get it running and atm. it's switching to an older composer version.
