### ISSUE TITLE
Writing an Envato (Theme Forest) installer/plugin

### ISSUE THREAD

**Issue by szepeviktor** [composer/composer#8623]
Hello!

I'd like to write a plugin/installer that

1. Catches `envato/anything` **virtual** package names when installing, generates repository data (partly from values in `$COMPOSER_HOME/config.json`)
1. And provides a download URL from Envato API (that is btw, signed and expires in 10 minutes)

https://github.com/szepeviktor/composer-envato

Could you point me to the right direction.
https://getcomposer.org/doc/articles/scripts.md#event-names seem to be not enough for me
Thank you!

**Comment by stof** [comment]
Custom installers are not able to provide repository data, as they are called *after* resolving dependencies.

What you would need to provide is probably a custom type of repository, registered by a plugin. You can look at https://github.com/fxpio/composer-asset-plugin to see how this was done by this plugin.
You might still need a custom installer if you want to wait until download time to generate the URL due to expiration.

Note that a plugin wanting to provide repository data **must** be installed globally. Requiring it locally will not work when you run a composer install or update without already having a populated vendor folder, as you would not have the repository data when running the solver.

**Comment by szepeviktor** [comment]
Thank you @stof !

I'm trying to add a new `ArrayRepository` at `InstallerEvents::PRE_DEPENDENCIES_SOLVING`
and I think that is all :)

**Comment by szepeviktor** [comment]
Could you help me in what event should the virtual repository be added?
