### ISSUE TITLE
Temporary URL-s got saved into the lock file

### ISSUE THREAD

**Issue by szepeviktor** [composer/composer#8637]
While testing my [very 1st plugin](https://github.com/szepeviktor/composer-envato)
I've noticed that signed and expiring package URL-s (generated by the plugin) get into `composer.lock`.

Could you help me how to exclude these from the lock file
or make Composer never use them again?
Thank you.

**Comment by alcohol** [comment]
@Seldaek you're more of a plugin wizard than me. From what I understand, I think his plugin is designed to install licensed packages that require a signed (expiring) URL to download and he doesn't want to store the source location in the lock file.

**Comment by szepeviktor** [comment]
Yess!!

**Comment by Seldaek** [comment]
Sounds to me like you should encourage Envato to make use of https://packagist.com/vendors which is exactly for this, shipping private Composer packages to people buying them. With ACLs etc. Because I really don't see how what you want to achieve will work here.. This goes against many assumptions Composer makes about package URLs.

**Comment by szepeviktor** [comment]
Thank you for your advise.
I think there are ~1 Composer user among Envato customers :)

I'm thinking of setting distUrl to a basic parameterless URL and a custom Installer that would add authentication to it.
