### ISSUE TITLE
COMPOSE_VENDOR_DIR & generated autoloaders

### ISSUE THREAD

**Issue by tkleinhakisa** [composer/composer#8658]
Hello, 

I am facing an issue when trying to run composer with the COMPOSE_VENDOR_DIR environment variable set.

At first let me describe my use-case:
I am working on a build script which goal is to create a zip file of my application, including the vendors.
The project is also making use of [local "Path" repositories](https://getcomposer.org/doc/05-repositories.md#path)

When working on dev, the local repositories are symlinked in the vendor folder, which is quit convenient.
When building the zip file, i need to copy/mirror the local packages to the vendor folder.

1 - I've been able to achieve this goal with a "not so pretty" solution:
```
# clear the vendor folder which contains symlinks
rm -Rf vendor/*

# tell composer to copy local packages instead of symlinking
export COMPOSER_MIRROR_PATH_REPOS=1

# install the dependencies
composer install --no-dev --optimize-autoloader

# at this point the vendor folder is correct and i can add it to my zip file

# clear the vendor folder which contains copies of the local packages (not dev friendly)
rm -Rf vendor/*

# tell composer to symlink local packages
export COMPOSER_MIRROR_PATH_REPOS=0

# install the dependencies again for local development
composer install
```

2 - I've been trying a cleaner solution by using a temporary build directory (which is managed by my task runner framework, quit convenient also):
```
# tell composer to copy local packages
export COMPOSER_MIRROR_PATH_REPOS=1

# tell composer to install dependencies in my temporary build directory
export COMPOSER_VENDOR_DIR=/tmp/tmp_ab12c3/vendor

# install the dependencies
composer install --no-dev --optimize-autoloader

# at this point the vendor folder should be correct and i should be able to add it to my zip
# also everything gets removed automatically as the temporary folder is managed by the task runner framework
```
 
Unfortunately, doing so result in an issue with the autoloader that cannot find any of my classes when the project is deployed.
The issue is that the autoloaders generated by composer are containing an absolute path to my project folder on the machine where the script has been run.

```
// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = '/home/user/my-project';  // NOT GOOD IN MY USE CASE
```

When i'm not using the COMPOSER_VENDOR_DIR variable, the result is exactly what i need 
```
// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir); // GOOD IN MY USE CASE
```

3 - I've also noticed that if the COMPOSER_VENDOR_DIR variable is set to a relative path, eg `export COMPOSER_VENDOR_DIR=vendor2`, then there is no absolute path in the autoloader
```
# tell composer to copy local packages
export COMPOSER_MIRROR_PATH_REPOS=1

# tell composer to install dependencies in a directory inside the project
export COMPOSER_VENDOR_DIR=vendor2

# install the dependencies
composer install --no-dev --optimize-autoloader

# at this point the vendor folder is correct and i can add it to my zip file

# remove the fake vendor folder, not managed by my task runner framework :( but an acceptable solution :)
rm -Rf vendor2 
```

So the question is: is there a way to configure composer to work as i describe in exemple 2, with COMPOSER_VENDOR_DIR outside of the project and generated autoloaders without hard-coded absolute paths ?

Thanks for you help and feedbacks
Best regards

**Comment by stof** [comment]
Well, the generated autoloader files need to have a path from themselves to the app folder. It will try to generate a relative path if possible. But in the first case, there is no common prefix between `/tmp/tmp_ab12c3/vendor` and `/home/user/my-project`. So there would be no benefit over an absolute path as the absolute path would still be part of the relative path (as the relative path would be `../../../home/user/my-project)`. And doing that with `dirname()` (because $baseDir is actually expected to contain an absolute path not using `..`) until the root would create issues on Windows (due to the drive at the beginning of absolute paths).

Your case 3 works because the relative path from `/home/user/my-project/vendor2` to `/home/user/my-project` is the same than the relative path from `/home/user/my-project/vendor` to `/home/user/my-project` (getting the parent folder in both cases).
`COMPOSER_VENDOR_DIR` is not meant to generate the vendor dir somewhere and then copy it back to `vendor` with a working autoloader. The generated autoloader is meant to work when the vendors are in the `COMPOSER_VENDOR_DIR` location.

**Comment by tkleinhakisa** [comment]
Thanks @stof for this detailed explanation. 
When building this kind of package/zip I always find it cleaner to do everything in a temporary build directory. But maybe it is not so common to package the vendors with the application (the goal is to speed deployment of new instances and avoid issue in case of github downtime). Also I have this issue because the build is done on dev machine, but it wouldn't exist with a dedicated build system :'(
Do you think it would be doable/acceptable to add an option for this ? eg: COMPOSER_AUTOLOADER_BASE_DIR

**Comment by stof** [comment]
Well, that would add complexity in composer for a very specific case.

Btw, if you were actually doing *everything* in the temporary directory, you would not need that feature, because you app code would be there too (and you wouldn't even be using `COMPOSER_VENDOR_DIR`, as the vendor dir would have the default name in the temporary build folder in such case). The issue in your case is that you actually do only half in the temporary folder (you put the vendor folder there, but not the whole project).

**Comment by tkleinhakisa** [comment]
You're correct ! In reality it's more like "at least don't touch the current dev files so i can keep working after my deployment" ^^ Anyway this gives me some ideas on how to improve things so thanks for this little exchange.
