### ISSUE TITLE
Composer Install Exception with local repository

### ISSUE THREAD

**Issue by shyim** [composer/composer#8679]
My `composer.json`:

```
{
  "name": "shopware/development",
  "type": "project",
  "license": "MIT",
  "repositories": [
    {
      "type": "path",
      "url": "custom/plugins/*",
      "options": {
        "symlink": true
      }
    },
    {
      "type": "path",
      "url": "platform",
      "options": {
        "symlink": true
      }
    }
  ],
  "config": {
    "optimize-autoloader": true
  },
  "prefer-stable": true,
  "minimum-stability": "dev",
  "autoload": {
    "psr-4": {
      "Shopware\\Development\\": "src/"
    }
  },
  "require": {
    "php": "~7.2",
    "ocramius/package-versions": "1.4.0",
    "shopware/platform": "6.1.x@dev"
  },
  "scripts": {
    "post-update-cmd": [
      "[ ! -d platform ] || [ -L vendor/shopware/platform ] || (echo 'vendor/shopware/platform should be a symlink to platform'; exit 1)",
      "[ ! -d vendor/shopware/platform/.git ] || ln -sf $PWD/dev-ops/pre-commit vendor/shopware/platform/.git/hooks/pre-commit"
    ]
  },
  "require-dev": {
    "ext-tokenizer": "*",
    "ext-xmlwriter": "*",
    "bheller/images-generator": "1.0.1",
    "fzaninotto/faker": "1.8.0",
    "johnkary/phpunit-speedtrap": "3.1.0",
    "league/flysystem-memory": "1.0.2",
    "mbezhanov/faker-provider-collection": "1.2.1",
    "phpunit/phpunit": "8.4.3",
    "smalot/pdfparser": "0.14.0",
    "symfony/browser-kit": "4.4.1",
    "symfony/dependency-injection": "4.4.1",
    "symfony/phpunit-bridge": "4.4.1",
    "symfony/stopwatch": "4.4.1",
    "symfony/var-dumper": "4.4.1",
    "symfony/web-profiler-bundle": "4.4.1",
    "symfony/dom-crawler": "4.4.1"
  }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
require.ocramius/package-versions : exact version constraints (1.4.0) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: OK
Composer version: 1.10.0
PHP version: 7.4.2
PHP binary path: /nix/store/k6gx6n6dajskpmwysi8d2mlgb5k2mp3f-php-7.4.2/bin/php
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

When I run this command:

```
composer install
```

I get the following output:

```
Loading composer repositories with package information

                                                                                
  [RuntimeException]                                                            
  The `url` supplied for the path (custom/plugins/*) repository does not exist  
                                                                                
```

And I expected this to happen:
It works.

Reproduce:
Clone this repo: https://github.com/shopware/development
composer install

1.9.3 => works
1.10.0 => exception

**Comment by alcohol** [comment]
I mean, it's correct technically, because you're providing a path to an empty directory, so there is nothing to be found there. Why do you expect this to work?

This change introduced the additional check which guards against a bad configuration (which you have): https://github.com/composer/composer/commit/18895064ad12bbe165221029f166eff368e4e833#diff-620a11fbfc7f8f33cc6bc0b1ebc253b4

**Comment by shyim** [comment]
Hey,
I understand your point but, there was no warning or such other things. It's also not mentioned in the Changelog. Normally when a software breaks things, it adds warnings and removes it in later versions. And this didn't happen here.

**Comment by alcohol** [comment]
It's not really breaking things though, it is merely providing you with details about a configuration error, giving you the chance to fix it?

**Comment by shyim** [comment]
The ```composer install`` isn't running anymore. It's for me a breaking change. So all Travis builds are failing and maybe also in the customers deployments.

**Comment by Ocramius** [comment]
Yeah, calling it a BC break seems to be a bit of a stretch: this is going way above what's documented/typed, heh...

Latest validation change (loosening) was on on https://github.com/composer/composer/commit/40e6d19d7352ad096b15985f09cc53152ee689be, but only to allow local (fixed) paths, not patterns.

**Comment by shyim** [comment]
But there was still no validation or warning.  The users are not looking in the schema 😉

**Comment by Crusse** [comment]
1.10.0 broke our project builds as well. Our composer.jsons contain local paths (e.g. `"url": "/custom/plugins/*"`) that only exist in local development. In Jenkins (where we build the projects) those local paths don't exist.

We fixed this by removing all `"path"` repositories from composer.json in our Jenkins build script:

```
cat composer.json | jq 'del(.repositories[] | select(.type == "path"))' > composer-fixed.json
mv composer-fixed.json composer.json
```

If Composer will require that the local paths exist from now on, it would be nice to have a setting to be able to return to the previous, more lenient behavior, where local paths did not need to exist.

Or maybe the path existence check could be special-cased for any paths that contain wildcards, although that gets complicated/hacky real quick.

**Comment by alcohol** [comment]
> If Composer will require that the local paths exist from now on, it would be nice to have a setting to be able to return to the previous, more lenient behavior, where local paths did not need to exist.

Like say, running a previous version until you fix your configuration?

Just thinking in terms of solutions here. 🤷‍♂ 


FYI: if you use path repositories in your development workflow only, I would suggest adding those to your global configuration instead of your project. Whether or not that suits your use-case depends on several factors though (e.g. do you want to share the same path repos across multiple projects, etc).

**Comment by naderman** [comment]
I don't think we should be recommending adding path repositories or really anything else to global configuration @alcohol - just causes issues if you have multiple projects.

**Comment by alcohol** [comment]
@naderman I've had use-cases where it was helpful, but in general I would agree, it causes more problems than it solves.

**Comment by mitelg** [comment]
the error remains, even if I put a plugin into our plugins directory and it looks like that: `custom/plugins/SwagPayPal/composer.json`. 
Is this still misconfigured? 
It would really be too bad, if we would have to change our complete plugin system approach.

**Comment by mitelg** [comment]
FYI: this is a quote from the current docs. https://getcomposer.org/doc/05-repositories.md#path

> Note: Repository paths can also contain wildcards like * and ?. For details, see the PHP glob function.

**Comment by windaishi** [comment]
We have the same problem here. We currently solved it by creating an empty directory inside the respective path. 
Would be nice to see a fix for that in the next composer version.

**Comment by Seldaek** [comment]
I'd be happy to move forward with a fix, but I am not sure how to fix this. IMO the warning makes sense, if there is no directory, the path repo is misconfigured and not loading any packages.

I am not sure why you all have these definitions with optional dirs in there, because if the dir is there and you run update, then run an install on some other machine where the dir is missing it will fail or end up in different results. It sounds overall like fairly bad practice which is bound to lead to surprises.

So I don't know what are the options here.

**Comment by JoshuaBehrens** [comment]
I see the asterisk like in RegEx. It describes a case collection of zero to unlimited results. So I don't see a problem having an empty set of repositories as result.

So I'd either revert https://github.com/composer/composer/commit/18895064ad12bbe165221029f166eff368e4e833#diff-620a11fbfc7f8f33cc6bc0b1ebc253b4 or make it less fixed. E.g. an option at the repository definition could contain a flag stating: empty is allowed. This is opt-in as default though is: there has to be at least something. Otherwise an asterisk can already be that opt-in.

**Comment by Seldaek** [comment]
The asterisk is as in glob matching "any string there", it doesn't really mean it's optional, and the intent was never to support optional paths, just to avoid having to specify 30 times the same path when you have 30 folders/packages in there. But yeah, regardless of what the intent was, the reality is that some of you are doing this optional package stuff, so probably adding an option to shut down the warnings or perhaps silencing the warning if the path up to the `*` exists would be simpler.

**Comment by mitelg** [comment]
interesting notice: the error appears only, if the `composer.lock` file is missing. 
our production template works without any change https://github.com/shopware/production

**Comment by oemmes** [comment]
We also use a path with asterisk ("packages/*") where we put pacakges we need to change during development. That is quite handy as you don't have to change code under vendor or possibly some other package install path.

The new behaviour is breaking this and actuall not really checking what it tries to do. Because if i just create an _empty_ folder "packages/dummy/" composer does not complain although there is still no composer package in the path.
So this is as well a workaround for the new check...

I would like to get the old behaviour back, though.

**Comment by stucki** [comment]
> The asterisk is as in glob matching "any string there", it doesn't really mean it's optional, and the intent was never to support optional paths, just to avoid having to specify 30 times the same path when you have 30 folders/packages in there. But yeah, regardless of what the intent was, the reality is that some of you are doing this optional package stuff, so probably adding an option to shut down the warnings or perhaps silencing the warning if the path up to the `*` exists would be simpler.

@Seldaek Yes please!

**Comment by Seldaek** [comment]
Please confirm it works for you after `composer self-update --snapshot`

**Comment by mitelg** [comment]
works :+1:

**Comment by stucki** [comment]
@Seldaek Works, thank you!

**Comment by JoshuaBehrens** [comment]
Nice comment in the implementation 😁

**Comment by Crusse** [comment]
> FYI: if you use path repositories in your development workflow only, I would suggest adding those to your global configuration instead of your project.

Thanks, this works in our case, since we're running Composer inside a project-specific Docker container. Any global Composer config is therefore only global to that project's Docker container, and not to the developer's whole machine.

> I am not sure why you all have these definitions with optional dirs in there

Our use case is mainly with WordPress, where each WordPress site has its own `composer.json` file. `composer.json` lists all of the site's WordPress plugin and theme dependencies.

By default all plugin and theme dependencies are fetched from our Composer repository, but for easy local development we've used Composer's `"path"` repositories to optionally fetch some plugins and themes from the developer's own machine. This requires that the developer downloads (e.g. git-clones) plugins or themes to a specific directory (e.g. `/custom/plugins/`) on their filesystem. For example:

```
"repositories": [
    {
        "type": "path",
        "url": "/custom/plugins/*"
    },
    {
        "type": "path",
        "url": "/custom/plugins/*/*"
    },
    {
        "type": "composer",
        "url": "https://our-internal-composer-repo.example.com"
    }
]
```

> if the dir is there and you run update, then run an install on some other machine where the dir is missing it will fail or end up in different results. It sounds overall like fairly bad practice which is bound to lead to surprises.

This is a good point, and this did always feel a bit awkward for us.

- Whenever the developer adds or removes a plugin on their local filesystem, the developer also needs to remember to re-run `composer update` to update the symlinks created by the `"path"` repositories
- We never distribute (e.g. in Git) the `composer.lock` file due to the problem you mention: the `composer.lock` file refers to paths of plugins that were found on a _specific developer's_ filesystem at the time of running `composer update`. If another developer takes that lock file and runs `composer install`, it'll probably result in an error, since the other developer doesn't have the same `/custom/plugins/*` files on their machine.

(For what it's worth, the behavior in `1.10.0` was not a showstopper in our case, since we can work around it with many of the workarounds mentioned above, or with some other solution outside of `composer.json`.)

**Comment by oemmes** [comment]
> Please confirm it works for you after `composer self-update --snapshot`

yes, it does :) Thanks!

**Comment by Seldaek** [comment]
Released now as 1.10.1

**Comment by pamuche** [comment]
> We also use a path with asterisk ("packages/*") where we put pacakges we need to change during development. That is quite handy as you don't have to change code under vendor or possibly some other package install path.

Sorry to complain again. We use the same workflow to develop bundles locally. As we are forced to deploy on Win-Machines it is hard for us (nearly impossible :grin:) to create an empty "linux-style"-folder (say '/home/userA/dev/bundle-abc'). 

Is the check really necessary? In production mode composer can just skip the "path-type" repository and ask our satis or packagist.org.

P.S.:
I'd really like to know how you develop bundles locally (always in vendor-dir, maybe with symlinks)

**Comment by Seldaek** [comment]
@pamuche you can just append a * to your path and it should remove the warning as far as I can tell?

**Comment by pamuche** [comment]
> you can just append a * to your path and it should remove

But `if (is_dir($url)) {..` will fail because we are developing in linux and have to deploy on Windows. So we can't e.g. create the empty folder: '/home/userA/dev/bundle-abc'. 

"path-type"-repositories are the only way for us to develop a bundle (without pushing it to an package-repo) and still use `composer update/install`. Maybe we missed something and there is a better way. (I can imagine to have these kind of local-"dev"-configuration in an extra file let's say composer-override.json)

**Comment by stucki** [comment]
@pamuche has a point here. Before the check, the folder that is referred to as path-type repository did not have to exist, but now it does. For this reason, we had to add an empty folder to the repository now, which did not have to exist in versions up to 1.9.x.

I agree with his point, the check doesn't help anything but causes new problems.

**Comment by Seldaek** [comment]
Ah ok now I get your point.. how about defining it with a relative path instead of absolute? Or using `~/foo` at least to make it relative to HOME/user dir, that should work on windows too.

Anyway, IMO this is still a misuse of this feature.. the point as I already said is not to have optional repos and run update on different machines obtaining different results. For developing dependencies locally either you can work in the vendor dir using a --prefer-source install (so you have the git data in vendor), or you can use https://github.com/franzliedke/studio which does something more advanced with symlinks etc, might be more what you are looking for.

**Comment by pamuche** [comment]
Ah thanks for the link to https://github.com/franzliedke/studio  

But as they say

> Under the hood, it uses Composer's path repositories to do so. As a result, you won't have to develop in the vendor directory.

I'm not sure if this will still working with the new limitation. I'll try.... 

And I agree with you in 
> run update on different machines obtaining different results
should be avoided. But I'm really amazed that I can't find more hints on dev-scenarios with composer. (getting instant bundle changes but keep ```composer update/install``` still working..) (Maybe [studio](https://github.com/franzliedke/studio ) is a way)
