### ISSUE TITLE
Custom Repository implementation issues

### ISSUE THREAD

**Issue by aurimasniekis** [composer/composer#8695]
I am trying to create a custom repository adapter, but I ran into a couple of issues.

The first issue is the `composer-schema.json` is hardcoded repository types that disallow using custom repository type value as it's validated according to ENUM values.

The second issue I found is that in your custom Plugin in the `activate` method when trying to set custom repository class, it does not affect RepositoryManager used in everywhere else which prevents adding a custom repository.

Any suggestion for trying to implement a custom repository type?

**Comment by Seldaek** [comment]
There really isn't good support for custom repositories, and it's difficult to achieve because it needs the plugin to be installed before the repository is enabled, so typically it forces use of global plugins, and is overall just not a great way to do this. IMO the better approach is to build the repository as an adapter repo, which exposes a composer repository format to composer, and consumes whichever data you want to expose.

**Comment by brandung-sjorek** [comment]
@Seldaek Do you have any hit, what you mean by _“adapter repo”_ … i.e. some lines of code?

**Comment by stof** [comment]
@brandung-sjorek some server-side tool that exposes a composer repository format, generating that data from any source it wants.

For instance, https://github.com/composer/packagist reads the metadata from VCS repositories (as supported by Composer natively) and aggregates them in a composer repository (powering packagist.org).
https://github.com/composer/satis does something similar but as a static site generator (you need to re-run Satis each time you want to include new versions of packages)
And https://github.com/hiqdev/asset-packagist exposes a composer repository generated based on the packages of the npm registry.

**Comment by brandung-sjorek** [comment]
@stof Got it, thanks a lot!
