### ISSUE TITLE
Process Signaled with Signal 6 for every command. New Install.

### ISSUE THREAD

**Issue by andrewvillano** [composer/composer#8721]
My `composer.json`:

{
}

Output of `composer diagnose`:

                                                          
  [Symfony\Component\Process\Exception\RuntimeException]  
  The process has been signaled with signal "6".          
                                                          

When I run this command:

When I run **any** command...

I get the following output:

                                                          
  [Symfony\Component\Process\Exception\RuntimeException]  
  The process has been signaled with signal "6".          
                                                          
composer -vvv shows it is trying to issue a git branch, but I can issue that command fine in bash.

And I expected this to happen:

Something else.

Running RHEL8, PHP 7.2.11

**Comment by adampmoss** [comment]
I'm also finding this issue. If I run composer install on an old project it works ok, but all new projects seem to have this same issue.

> [Symfony\Component\Process\Exception\RuntimeException]
> The process has been signaled with signal "6".


Exception trace:
 ```
() at phar:///usr/local/bin/composer.phar/vendor/symfony/process/Process.php:366
 Symfony\Component\Process\Process->wait() at phar:///usr/local/bin/composer.phar/vendor/symfony/process/Process.php:198
 Symfony\Component\Process\Process->run() at phar:///usr/local/bin/composer.phar/src/Composer/Util/ProcessExecutor.php:75
 Composer\Util\ProcessExecutor->execute() at phar:///usr/local/bin/composer.phar/src/Composer/Package/Version/VersionGuesser.php:299
 Composer\Package\Version\VersionGuesser->guessSvnVersion() at phar:///usr/local/bin/composer.phar/src/Composer/Package/Version/VersionGuesser.php:82
 Composer\Package\Version\VersionGuesser->guessVersion() at phar:///usr/local/bin/composer.phar/src/Composer/Package/Loader/RootPackageLoader.php:88
 Composer\Package\Loader\RootPackageLoader->load() at phar:///usr/local/bin/composer.phar/src/Composer/Factory.php:351
 Composer\Factory->createComposer() at phar:///usr/local/bin/composer.phar/src/Composer/Factory.php:576
 Composer\Factory::create() at phar:///usr/local/bin/composer.phar/src/Composer/Console/Application.php:368
 Composer\Console\Application->getComposer() at phar:///usr/local/bin/composer.phar/src/Composer/Console/Application.php:486
 Composer\Console\Application->getPluginCommands() at phar:///usr/local/bin/composer.phar/src/Composer/Console/Application.php:178
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer.phar/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer.phar/src/Composer/Console/Application.php:113
 Composer\Console\Application->run() at phar:///usr/local/bin/composer.phar/bin/composer:61
 require() at /usr/local/bin/composer.phar:24
```

**Comment by Seldaek** [comment]
Do you use php from homebrew? https://github.com/laravel/valet/issues/876 suggests that maybe `brew upgrade` would fix it.

**Comment by andrewvillano** [comment]
I'm using the php package that comes with RHEL 8. php 7.2.11 

Oddly enough, this is working on an almost identical RHEL 8 machine. I can get so far as to get composer to run after a fresh install. It will also accept a selfupgrade or other status commands. But after doing a require and having it create a composer.json file, I must delete that file before composer will accept any more commands.

**Comment by Seldaek** [comment]
From https://stackoverflow.com/a/3413215:

> abort() is usually called by library functions which detect an internal error or some seriously broken constraint. For example malloc() will call abort() if its internal structures are damaged by a heap overflow.

Seems like some sort of assertion deep down fails and makes PHP kill itself.. But I really can't imagine what given what you described, sorry.

**Comment by tripbnb66** [comment]
$ composer -vvv


Reading ./composer.json
Loading config file ./composer.json
Checked CA file /usr/local/etc/openssl@1.1/cert.pem: valid
Executing command (): git branch --no-color --no-abbrev -v
Executing command (): git describe --exact-match --tags
Executing command (): git log --pretty="%H" -n1 HEAD
Executing command (): hg branch
Executing command (): fossil branch list
Executing command (): fossil tag list
**Executing command (): svn info --xml**


  **[Symfony\Component\Process\Exception\RuntimeException]
  The process has been signaled with signal "6".**


Exception trace:
 () at phar:///usr/local/bin/composer/vendor/symfony/process/Process.php:366
 Symfony\Component\Process\Process->wait() at phar:///usr/local/bin/composer/vendor/symfony/process/Process.php:198

above is the error that I execute "composer -vvv"
the problem is caused by "svn info --xml"
therefore, I tried to fix the svn issue.

I execute the "svn" and got error message
$ svn
**dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/Cellar/subversion/1.12.2/libexec/serf/lib/libserf-1.dylib
  Reason: image not found
Abort trap: 6**

so, I just did below steps:
**brew reinstall svn**

then, the problem is fixed.

**Comment by TishoTM** [comment]
for MacPorts users

`port uninstall php-svn` 
`port install php-svn` 

fixes the problem
