### ISSUE TITLE
Allow multiple sets of credentials per repository

### ISSUE THREAD

**Issue by djacques4gorilla** [composer/composer#8724]
This is a feature request. First a bit of context:

When dealing with larger applications containing multiple paid dependencies, it's often the case that those extensions are purchased by different people or agencies, each using their own account with the package vendor. When comes the time to add all of those dependencies, we can run into the issue where multiple packages come from the same vendor, but will be accessible with different sets of credentials. Some vendors are pro-active and offer sub-domain aliases to work around this (e.g. Amasty), which allows us to assign one set of credentials per alias, but others do not. In those cases, it means we either need to install the package directly in the project code and forgo the use of Composer (the worst!) or copy the package into our own Satis repository (making us responsible to manually fetch and upload new versions from the vendor). There's also a workaround of having one set of credentials set in the project's auth.json, and another in the user's home directory (this only works if you have no more than 2 sets per repository though).

Given that last workaround, it would seem that Composer already has a built-in fallback mechanism for credentials. With that in mind, I would make the suggestion to add the ability to add sets of credentials in an array for a given repository host, leveraging the existing fallback logic. For example:
```javascript
{
    "http-basic": {
        "repo.example1.org": [
            {
                "username": "my-username1",
                "password": "my-secret-password1"
            },
            {
                "username": "my-username2",
                "password": "my-secret-password2"
            }
        ],
        "repo.example2.org": {
            "username": "my-username3",
            "password": "my-secret-password3"
        }
    }
}
```
where the first repository has 2 sets of credentials, and the second has one as usual. Composer would then retrieve the list of packages from the repositories with each set of credentials to build a complete list that can be accessed, and when pulling packages from that repository, it could either cycle through the credentials until it finds a set that works, or possibly store the index of the set that works for that domain in the lock file to avoid having to look for the right ones.

**Comment by Seldaek** [comment]
TBH that's a special use case due to poor repository construction which I am not so keen on supporting in composer. [Private Packagist](https://packagist.com) does support this though, as you can add the same repo as a third party mirror multiple times, configuring each with a different set of credentials, and mirroring a different set of packages from each. So I'd suggest you maybe have a look at using that, or try and get your vendors to use it as a paid package repository, which is also something we offer and we then handle credentials correctly for customers.

**Comment by ProxiBlue** [comment]
Hello,

I am aware this is closed, but I will pipe in and say this IS a real world practical issue.
Poor design, or not, the issue exists.

Example:

Adobe has repo,magento.com

I have a client that has TWO accounts with Adobe, due to multiple businesses with separate financials, but some modules are shared across the entities, so, I have to contend with 2 credentials for repo.magento.com

I'd like to tell them to change their entire business model, to accommodate a 'poor repository design', but, I don't think that will go down to well ;), or I can scream at adobe to have a separate HOST for each repo (I am sure they will change it all for little old me).....

AND THAT IS THE KEY: HOSTNAMES

Simply CNAME the SOURCE repo repo using DNS

So, now your duplicate credentials are seen as a new repo, and packages can install

I have no clue what side effects this will have. but thusfar seems to just work peachy

@djacques4gorilla 

Unfortunately, I had found in my life travels that the real world seldom follow our ideals of 'best practice'

**Comment by johnorourke** [comment]
I arrived here with the same issue as @ProxiBlue - multiple accounts on the Magento marketplace each containing different paid-for modules.  I don't understand the comment about "poor repository construction".

One example of a neat solution would be including the full URI or at least username in the auth.json lookup - eg. so you could do:

```
"repositories": {
   "repo1": { "type":"composer", "url":"https://username1@example.org" },
   "repo2": { "type":"composer", "url":"https://username2@example.org" }
}
``` 

Even if you could find a hostname alias (eg. 'connect20.magentocommerce.com' is the same as 'repo.magento.com') it won't work because the downloaded package.json files contain repo.magento.com URLs, so composer will use the credentials for that.

**Comment by naderman** [comment]
I would very much prefer to avoid using "usernamen@" as part of the URL as this already has http basic auth implications and we try and tell people not to do that to avoid unintentionally exposing passwords in their composer.json or when sharing repo URLs and to use auth.json instead. So advocating it now for a different use will be very confusing.

So if we want to add support for this it would really need to be through a new field in the repository object which picks the auth to use for the particular repository.

Making a change as proposed to auth.json is going to have pretty wide implications, as there is various tooling, e.g. IDEs which read auth.json without using our composer code, and these will all have to update to now support arrays of authentication. 

Making this change will make auth.json incompatible with older versions of Composer, but I suppose that's acceptable?

**Comment by ProxiBlue** [comment]
> auth.json incompatible with older versions of Composer, but I suppose that's acceptable?

I would say, yes, is acceptable. It will not take much for all to make needed updates by users.
IDE's etc will also need to update, but of course proper period of notification woudl be appreciated by those else they can be in a massive user outcry for broken systems/processes.

I gather this will be a composer 2 change? or is v1 still actively supported?

**Comment by ProxiBlue** [comment]
@johnorourke 

> it won't work because the downloaded package.json files contain repo.magento.com URLs, so composer will use the credentials for that.

Likely what I ran into. I initially got excited that the CNAME idea worked, but next day it failed. I did not consider that limitation

**Comment by naderman** [comment]
Sorry to get your hopes up here. I was really just commenting on the theoretical possibility of that particular implementation proposal.

Considering the complexities of having to add this to lock files, anywhere dist URLs are used, the backward compatibility implications, changes that would be required to interactive auth dialogs to allow for a choice of multiple credentials per domain, the issues I already brought up etc. and seeing how this has worked for Composer users for years, I don't think adding support for this will be worth it.

So you should really consider either consolidating your repo.magento.com accounts, or telling Magento to change this if they actually want users to use multiple credentials for a single project (I don't think they do).

**Comment by johnorourke** [comment]
Just adding this for info- We've got three solutions to evaluate:

* A simple nginx reverse proxy including rewrite of any URLs returned in the JSON
* running a private packagist repo and pulling in all of the remote repo
* Magento.com has an "account sharing" feature

@naderman the issue with account consolidation is extensions have to be repurchased, so it could cost a huge amount of money. That's a shortcoming on their side though so I agree composer shouldn't have to work around it.

Interestingly, Amasty (a major supplier of paid extensions) have worked around this by providing ten aliases for their repository hostname.

**Comment by ProxiBlue** [comment]
I understood that. Was just thinking of tgis issue may not already be
resolved in composer 2. Since v1 is now EOL the fix would really never
happen

**Comment by johnorourke** [comment]
We're using a simple nginx reverse proxy setup to handle this, hope this helps someone:

```
server {
    server_name mirror1.repo.magento.com.example.com;
    server_name mirror2.repo.magento.com.example.com;
    server_name mirror3.repo.magento.com.example.com;
    server_name mirror4.repo.magento.com.example.com;
    server_name mirror5.repo.magento.com.example.com;

    location / {
        proxy_pass $scheme://repo.magento.com;
        # ensure not just any client can use this mirror - add your composer keys to the file:
        auth_basic "GetJohn mirror";
        auth_basic_user_file /var/www/vhosts/example.com/htdocs/.nginx-basic.passwd;
        # resolve the upstream name - point it to your local resolver:
        resolver 127.0.0.53;
        # tell it not to compress:
        proxy_set_header Accept-Encoding "";
        # filter the response:
        sub_filter_once off;
        sub_filter_types application/json;
        sub_filter '//repo.magento.com' '//$host';
        sub_filter '\/\/repo.magento.com' '\/\/$host';
    }
}
```

**Comment by riconeitzel** [comment]
Came here as well … same issue … also no solution! what a *sigh* …

**Comment by johnorourke** [comment]
Prompted by @riconeitzel to come back and provide our current solution!  Suppose you have one repo, "marketplace.magento.com", and two sets of credentials, A and B.   We ended up using satis as a cache/proxy for the Magento marketplace, so that our clients could have two sets of credentials - one for our satis repo, and one for the Magento marketplace, with a `satis.json` like the below.

In your client you'll need "canonical" = "false", like this:

```
    "repositories": {
        "my-satis-repo": { "type": "composer", "url": "https://my-satis-repo", "canonical": false },
        "the-real-repo": { "type": "composer", "url": "https://marketplace.magento.com/......" }
    }
```

and your client's `auth.json` could then include two sets of credentials:

```
{
    "my-satis-repo":  { ... credentials for my-satis-repo .... }
    "the-real-repo": { .... the 'A' credentials .... }
}
```

Your client can then include your satis repo, plus your regular repo, and your satis repo will include all the 

```
{
  "name": "getjohn/satis",
  "homepage": "http://xxxxxxxxxxxxxxxxxx/",
  "repositories": {
        // SPECIFY YOUR REGULAR MODULE SOURCE REPOSITORIES:
        "getjohn-onelogin-module-saml2-extend": { "type": "vcs", "url": "git@bitbucket.org:getjohn/onelogin-module-saml2-extend.git" },
        "punchouthub": { "type": "vcs", "url": "git@bitbucket.org:getjohn/punchouthub-m2-module" },
        "getjohn-saml2": { "type": "vcs", "url": "git@github.com:getjohn/saml2" },
         // AND THEN THE REPO YOU WANT TO PROXY:
        "the-real-repo-again": { "type": "composer", "url": "https://repo.magento.com/" } 
  },
  "require-all": true,
  "output-dir": "pub",
  "config": {
    "preferred-install": "dist"
  },
  "archive": {
    "directory": "dist",
    "format": "zip",  // IMPORTANT! It defaults to 'tar', which has a directory depth limit, not suitable for Magento
    "prefix-url": "https://xxxxxxxxxxxxxxxxx",
    "skip-dev": false,
    "rearchive": true
  }
}
```

and then the `auth.json` in your satis repo will include the other set of credentials:

```
    "the-real-repo-again": { .... the 'B' credentials .... },
```

It works nicely for us, but of course it downloads the entire upstream repo which could be huge.

Be certain to include "format":"zip" in satis.json, because the default is 'tar' which can't handle really long filenames or really deep directory structures.

**Comment by aholovan** [comment]
> I arrived here with the same issue as @ProxiBlue - multiple accounts on the Magento marketplace each containing different paid-for modules. I don't understand the comment about "poor repository construction".
> 
> One example of a neat solution would be including the full URI or at least username in the auth.json lookup - eg. so you could do:
> 
> ```
> "repositories": {
>    "repo1": { "type":"composer", "url":"https://username1@example.org" },
>    "repo2": { "type":"composer", "url":"https://username2@example.org" }
> }
> ```
> 
> Even if you could find a hostname alias (eg. 'connect20.magentocommerce.com' is the same as 'repo.magento.com') it won't work because the downloaded package.json files contain repo.magento.com URLs, so composer will use the credentials for that.

It's require a password also. It will work (at least for repo.magento.com) if looks like:
 
"repositories": {
   "repo1": { "type":"composer", "url":"https://username1:passwd1@example.org" },
   "repo2": { "type":"composer", "url":"https://username2:passwd1@example.org" }
}

**Comment by djacques4gorilla** [comment]
@aholovan ,

As it was mentioned before, this is problematic as it then exposes your credentials in your project repository, which may be shared or otherwise exposed to other parties, so that's undesirable.

@johnorourke ,

The Satis solution only works if you have a single project, but we deal with dozens of clients, each with their own Magento/Adobe credentials, so we can't mirror the Marketplace repository in our Satis Composer repository as we don't have a single set of credentials that would give access to all extensions purchased by all clients (or that wouldn't give access to extensions purchased by some and not others).

@naderman,

It doesn't seem like all that much would need to change. If, for example, I have one set of credentials for repo.magento.com in the project root directory, and then another set in my ~/.composer/auth.json, the project does build correctly if, for example, I'm pulling the Magento core packages with one set of credentials and some extensions from the Marketplace with the other. The issue is that versioning the auth.json file in the project repository is bad security practice for the same reason you don't want to add your username and password to the repo URLs in composer.json, so this trick can't be used on a production environment, especially on something like Magento Cloud where we can't just drop an unversioned auth.json into the project code as part of a custom deployment script.

**Comment by stof** [comment]
@djacques4gorilla this is quite hard to implement. Once your lock file contains a link to `https://example.org/archives/package1.zip` as dist URL, how would composer know which credentials if should use for that URL ?

The composer authentication system is not built around repositories, because the composer downloader system is not aware of repositories either.

**Comment by djacques4gorilla** [comment]
@stof ,

I can't say I have reviewed the Composer code for how it does that, but my anecdotal experience is that if you have credentials for the same repository URL set in multiple valid locations (e.g. in auth.json in the same directory as composer.json and in ~/.composer/auth.json), when it tries to fetch the package, if the credentials in one file fail to access the file, it will fallback to the ones in the other file. So the lock file doesn't need to know which set of credentials were used, it will fallback through the available credentials on each attempt. All I'm requesting is that we extend that fallback logic so a single file can have multiple sets of credentials to fallback through, you try them all on each download until you find a set that works (or fail if none worked).

**Comment by p24-max** [comment]
I'm facing same issue.

@Seldaek please consider reopening the ticket.

**Comment by rbouma** [comment]
We are having the same issues with Adobe with modules that are spread to multiple accounts and does have multiple credentials.

**Comment by naderman** [comment]
Why are you spreading the purchase to multiple accounts? Use the same account to purchase all the modules you need for a project, or ask Adobe to provide separate subdomains?

**Comment by rbouma** [comment]
@naderman We have modules we purchased on our Adobe account. Some clients of us are purchasing modules in their own account. Some of our clients came from other company that we taken over but they have also purchased the modules in theirs account. 

So this can have multiple reasons.
* Company take over with lot of modules in their account.
* Client has split accounts because they have multiple separate companies with separate finances and accounts.
* Client has their own account with purchased modules and our company has an account.

Now we need to switch authentication constantly to get all modules loaded.

**Comment by HeRovaZy** [comment]
@naderman It can be a solution to have multiple subdomains available for `repo.magento.com` so that we can add multiple access keys to the repo. 

At our company we take over webshops from other companies regularly, where they already have some plugins purchased from Magento already by the previous company. It's a big issue for these customers, because if they want additional modules purchased, we need to purchase them via the old partner (who aren't always very coöperative), or let the customer purchase all the modules again.

**Comment by naderman** [comment]
I'm not sure but it increasingly looks to me like this is exclusively an Adobe/Magento problem, so that's probably where your efforts should be directed. Sounds like they should figure out how to properly allow their customers to manage package access.

**Comment by ProxiBlue** [comment]
> this is exclusively an Adobe/Magento problem

Yep. Adobe will not likely change their way.

Alternative solution: Stop purchasing modules via their marketplace. Each vendor on there usually have their own sales site and properly managed unique url repos.

Also, adobe can pull a module from their ecosystem whenever they want (and have), and it has been unreliable being down for periods in the past.

I pulled all paid modules from there (not had many at that time) and ported them into a self hosted repo, and then migrated future updates to the specific vendors sites.

**Comment by johnorourke** [comment]
Hi everyone - I'm in the process of writing up our satis setup, which solves this and has allowed us to create a single composer repo per client.  It's also worth noting that Private Packagist looks like it'll also solve this since you can create sub-repositories and mirror other repositories, and of course that supports the community.  I'll post my write-up in the next few days!

**Comment by johnorourke** [comment]
> > this is exclusively an Adobe/Magento problem
> Alternative solution: Stop purchasing modules via their marketplace. Each vendor on there usually have their own sales site and properly managed unique url repos.

@ProxiBlue unfortunately only a few vendors have multiple URL aliases, so you get the same problem as soon as you're dealing with multiple client accounts.  Amasty, Mageworx and Xtento do provide this, but even some of the big players do not - Aheadworks, Mageplaza and the rest.  And a few still don't have their own composer repositories (eg. Webkul), so the Marketplace is necessary there.

**Comment by ndthanhnet** [comment]
i got the same request days ago, so i created a bash script to solve this specific problem, i made the repo public so you can visit it here https://github.com/ndthanhnet/multiple-composer-sources

**Comment by nitsan-technologies** [comment]
Maybe try the `only` property to define multiple `customer's access` + individual sources `product's access`.

```
"repositories": {
	"product1": {
		"type": "composer",
		"url": "https://USER:PASS@domain.com",
		"only": ["name/product"]
	},
	"product2": {
		"type": "composer",
		"url": "https://USER:PASS@domain.com",
		"only": ["name/product"]
	}
}
```

**Comment by djacques4gorilla** [comment]
@nitsan-technologies Our security best practices forbid adding credentials to the project Git repository. They have to be in the auth.json file, which only exists on the environment where the application is built.

**Comment by Minirock** [comment]
The issue is real, in our cases I'm with a company who got merged into an other one, as a result we end up having keys in our auth.json that are not matching anymore the module and keys of our new company. So what can we do ? Pray that the merchant has a solution to merge the modules of both the account into one.....and that's such a war path to start....it's been like 4 month and i can't still deploy properly my projects....being able to specify multiply auth keys for the same composer repositories would be more than great and save us a lot of trouble.

Although I can understand the safety issue, I don't feel there is much more risk to do it. Currently this is only letting me with the alternative to play with my auth.json to switch between keys depending on what module i want to update....such a messy process....

**Comment by pisarkov** [comment]
Hello Composer team and @naderman 

We also support this idea.
Currently, we are working on a project where the module was purchased from a personal account of the member who left.
We can still use keys but can't move a module to another account or use one more account together.

**Comment by stof** [comment]
Allowing multiple auth keys is not easy because this is not only about the authentication to load the repository metadata but also about the downloading of archives. And when installing from lock, composer ends up with the URL of the downloaded archive, with no information from which repository that archive was discovered when running `composer update` previously.
Composer needs to be able to retrieve the authentication credentials based only on the URL, which is why it currently allows only 1 set of credentials per domain (as it then uses the domain of the URL to select the credentials).
Changing this architecture is unlikely to happen (and even if it happens, it will probably involve BC breaks, which won't make it happen soon). And Private Packagist solved that using the capabilities of the current composer architecture.

**Comment by nitsan-technologies** [comment]
@stof 💯 

Mentioned the same thing at https://github.com/composer/satis/issues/482#issuecomment-2809316583

**Comment by nitsan-technologies** [comment]
**Good news!**

We’ve finally resolved the `Multi-Credential Issue` using a reverse proxy with cool PHP script, .htaccess techniques, and smart caching for better performance.

Check out the full solution here:
👉 https://t3planet.de/en/blog/composer-multi-credential-satis-domains/

**Comment by rbouma** [comment]
Just to contribute constructively: we've been running into this same multi-auth Composer issue quite a lot. Especially in Magento 2 projects where packages are tied to different client or vendor accounts 🔑

Managing multiple keys for repo.magento.com and other private sources becomes a real headache. Particularly in CI/CD pipelines ⚙️💥

That’s why we’ve been working on a tool to simplify this syncing packages from multiple authenticated sources and offering one unified Composer repo 📦🔁

If others are facing similar challenges, happy to share what we’ve learned or built. Feel free to reach out or check [https://www.rexsync.com](https://www.rexsync.com/) if it’s relevant 🙌

@naderman Totally understand! and thanks for the heads-up 👍

**Comment by naderman** [comment]
@rbouma I removed the content of your comment because I don't appreciate the level of advertising in it. Feel free to restate what you were saying that is relevant to the specific issue here and link to your paid product, but keep it on topic and relevant.
