### ISSUE TITLE
Feature request: force upgrade

### ISSUE THREAD

**Issue by GKFX** [composer/composer#8745]
It can be very difficult to upgrade a framework package such as Symfony as there are many dependencies on it and these all conflict with its upgrade. E.g. with [my composer.json](https://github.com/camdram/camdram/blob/60ac38a3c9830e0a7515c7622cd38445d1817427/composer.json), it is taking some time to persuade Composer to let me upgrade to 4.4.

Starting from [Symfony's instructions](https://symfony.com/doc/4.3/setup/upgrade_major.html#dependency-errors), I increased the version number of Symfony from `3.4.*` to `^4.1` and ran
```sh
composer update "symfony/*" --with-all-dependencies
```

This gave `Your requirements could not be resolved to an installable set of packages.` and a verbose explanation of the problem. So I am now slowly removing those other dependencies that seem to cause a problem, and I'll re-add them one-by-one once Symfony is at version 4.4. However, this is all very manual and each time I run Symfony there is a long wait for it to run.

Could I suggest a force-upgrade command of some sort to automate this process? I would imagine running something like

```
composer upgrade --force symfony=^4
```
and Composer would then remove or change the version numbers of any of my other dependencies as needed to make the upgrade happen, without further help from me. I.e. this would be a command that always succeeds, regardless of the consequences.

(Composer version 1.10.1)

**Comment by Seldaek** [comment]
Sorry but that sounds like an insane workflow to me. If you have dependencies then they should be needed, and removing them randomly is surely going to end up in a mess.

I would say try first to run `composer update --dry-run` to see if there is a solution by updating other dependencies which depend on symfony. `--with-all-dependencies` will only update symfony and things that it depends on, but not other packages that depend on symfony. If not then make sure you update those packages' requires to versions which support symfony 4.1+, until it resolves, then if you don't want to update everything at once you can still do a partial update with `composer update --with-all-dependencies symfony/* other/package and/some-more as/needed`.

That way you get to a state where you have working dependencies and you can then focus on getting the app to run again, update config etc, instead of having to disable half your bundles then having to add them again later.
