### ISSUE TITLE
[Question] self-update and locking of version

### ISSUE THREAD

**Issue by boesing** [composer/composer#8753]
Hey there,

is there a way to depend on composer 1.0 and still using `self-update`?
As 2.0 is on its way, I believe that using `self-update` will automatically bump to 2.0 if stable (and `--stable` as provided).
Actually, there are many servers we are using, which executes `self-update` regularly to be up2date.
As there are not all packages already "ready" for 2.0, we would prefer locking composer to `<2.0` until we actively want to upgrade.

Ofc, we could disable the `self-update` mechanism at all to avoid to get any version bump. That would be fine, if composer will never have fixes for the 1.X versions. But if you plan to release fixes vor v1, that wont be a good choice to disable the update process at all.

So, do you have any suggestions on how to achieve a smooth upgrade progress without disabling `self-update` at all on our servers?

Thanks and with best regards,
Max

**Comment by Seldaek** [comment]
I'm not sure how to best handle this tbh.. I see the problem, but anything we add now would need people to first self-update to that new 1.x version before they even get the feature to prevent the self-update to v2.. Or we can maybe build a new mechanism so that self-update in older versions only ever updates to the latest v1 and that one should have support for the new mechanism to prompt users if they want v2 once it's out.. 

I guess the latter is preferable. Will need to give it some more thought, but I'd say don't disable your self-updates just yet :)

**Comment by Seldaek** [comment]
Once https://github.com/composer/composer/commit/ccc8829ed963c8add98a60d88ad3ae6d8e7f11de is released in 1.10.2 you can then change your scripts to `composer self-update --1` to avoid surprises.

**Comment by boesing** [comment]
That was fast. Thanks!

**Comment by Seldaek** [comment]
1.10.2 is out now
