### ISSUE TITLE
Composer Autoload Class Name Conflict 

### ISSUE THREAD

**Issue by hwsiew** [composer/composer#8826]
Hi,

We are working on multiple plug-able modules for a project. Each module requires same basic library dependency which is handle by composer now. When we enable only one module at a time in the project, everything works fine. However, we are facing a problem where multiple modules are enabled in the project, since composer.json is the same in each module, composer autoload class will have the exact same name and hash. This resulted the conflict of composer autoload class name conflict. For now, we are checking the autoload class name before include it. But this might have another problem where we need to update the checking each time the composer.json is updated. Wondering is there any better method to resolve this elegantly ?

Thanks for your advice.

**Comment by Seldaek** [comment]
Not sure what you mean by the autoloader hash being the same. By default, `autoloader-suffix` is generated randomly in every vendor directory and then re-used to be stable over time.

If you do specify it in your composer.json via `config.autoloader-suffix`, you must then ensure you make it unique in every project.

May I misunderstood something though, I am not quite sure what the problem is.

**Comment by hwsiew** [comment]
Thanks @Seldaek. 

autoloader-suffix is exactly what i need.

Thanks again for your advice.
