### ISSUE TITLE
Option to disable deprecation notice about psr4

### ISSUE THREAD

**Issue by Yivan** [composer/composer#8834]
Hello,

Last composer version send a lot of `Deprecation Notice` saying `does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0`.
Actually it reports vendor ones and we cannot change them.

It mess the cli output, even more in verbose mode where we can see only this and all other message are lost in a yellow fog of deprecated notice ; )

Purpose of this issue is having the ability to disable this message.
Setting php to error_reporting 0 don't work. It should respect it (or at least E_USER_DEPRECATED).

Thanks!

**Comment by Seldaek** [comment]
These are only warnings.. Just make sure you update your dependencies to latest version which might have a fix already, or if not then report it to them so it gets fixed. Things need to get fixed to avoid problems in the future, ignoring warnings is not a solution.

That said if it's that disturbing in development, you can also avoid dumping an optimized autoloader, because that's the only point where the warning is emitted, and optimized autoloader on dev machines does not bring all that much.

**Comment by Yivan** [comment]
@Seldaek Thanks for your fast return on this.
Yes I understand totally that you prefer to not provide this option to ensure better ugrading to composer 2.0 (which i wait too because faster! : ) ).

But sadly we cannot upgrade dependency like you suggest as many projects are enterprise production project. So this way of upgrading dependencies is not applicable.
The way to disable optimize is tricky for us because we use Pimcore as development plateform and post-script composer are running optimizing automatically. So it needs some refactoring, changing our CI, etc. And telling all devs of the company to no more use optimize, etc... you anderstand just for a warning message is not a good solution either.

I imagine every people have different use case, so I was really thinking such an option to disable warning would be helpful. For now we have to live with it as no solution can work easily in our case.

The more easy solution is to downgrade composer, i imagine.

I hope if some more people ask for this feature it will be reopened!

Thanks again,
Best regards.
