### ISSUE TITLE
Composer require from specific repository

### ISSUE THREAD

**Issue by Yannik** [composer/composer#8857]
I got two repositories configured in my composer.json which provide both provide a package I need.

How can I require the package from a specific repository? Currently, it's unfortunately using the wrong repository when I'm simply doing `composer require my/package`.

I'm looking for something like
`
composer require --repository <repo-name> my/package`

**Comment by Seldaek** [comment]
In composer 1 this is not possible, you gotta pick the right version and it should then take it from the correct repo. In composer 2 it will always take it from the top repo priority unless specified otherwise via https://github.com/composer/composer/blob/master/doc/articles/repository-priorities.md
