### ISSUE TITLE
How do you load a package from a specific repository that exists in multiple sources?

### ISSUE THREAD

**Issue by klausi** [composer/composer#8893]
drupal/coder is a PHP library, not a Drupal module. It is on packagist but for commit credit purposes also on drupal.org. Drupal developers use drupal.org as additional composer repository:

My `composer.json`:

```json
{
    "repositories": [
        {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        }
    ], 
    "require-dev": {
        "drupal/coder": "^8.3"
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.10.6
PHP version: 7.2.24
PHP binary path: /usr/bin/php7.2
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
```

When I run this command:

```
composer update drupal/coder
```

I get the following result: coder is installed as Drupal module, but it should be installed as PHP library.

The first problem is that the drupal.org composer facade is broken and delivers Coder as drupal module, issue for that is https://www.drupal.org/project/project/issues/3135034

As a temporary fix it would be cool to tell Composer to fetch drupal/coder from packagist, not from drupal.org. How can I configure composer to do that?

Tracking issue for Coder to get any hack working is https://www.drupal.org/project/coder/issues/3134853

**Comment by greg-1-anderson** [comment]
From the [Composer Repositories documentation](https://getcomposer.org/doc/05-repositories.md):

> Composer will correctly pick your package over the original one since the custom repository has priority over packagist.

Packagist always has lower priority than any custom repository. This is how packages are overridden. If we gave packages.drupal.org a lower priority than Packagist, that might produce surprising behavior for other projects.

The real issue here is that packages.drupal.org does not support custom types for projects, so Coder is forced to be type "drupal-module" when it is published. This used to work because Coder used non-overlapping version numbers on packagist.org and packages.drupal.org. Now that the version numbers are overlapping, Composer is selecting the releases from the custom project, as it is designed to.

Making the priority of Packagist configurable does not feel right to me. Have you tried leaving Packagist out of the equation, and specifying drupal/coder as a custom vcs repository pointing at GitHub in the top-level composer.json file?

The best solution, I think, would be to not publish any Coder releases in packages.drupal.org. Perhaps you could achieve this by removing all of the tags and releases on drupal.org? If that is not effective, then perhaps you could try requesting that drupal infra special-case Coder, and not export it to packages.drupal.org. If we did this, then folks wouldn't have to add a repositories entry (or any sort of custom configuration, as requested in this issue) in their top-level composer.json file just to use Coder.

**Comment by apfelbox** [comment]
As a temporary fix you could probably add the specific repository as a VCS repository with the Github URL as the very first repository? Because they are matched in order, so just add the Github repo for only that specific package/repository as the first entry.

**Comment by Ayesh** [comment]
Composer 2 already has support for repository priorities and filters. See ["Filtered Repositories" here](https://php.watch/articles/composer-2).

If you use Composer 2, you could easily mark `drupa/coder` as one of the `exclude` directives for `packages.drupal.org`, so Composer would not use it and pick another repo (with `packagist.org` implied unless otherwise configured)

**Comment by Seldaek** [comment]
What @Ayesh said for v2. Generally speaking though this is not a problem we can fix. Requiring all users of your package to add it in the packages.drupal.org exclude directive if they want to install your package correctly sounds like a major PITA for them. If all this is for "commit credit purposes" (I'm not entirely sure what that means given I'm not that familiar with the drupal infra) it sounds to me like the trade-off is not worth it and it'd be best to save the users some trouble and lose the commit credit. Or publish the package on github or something. Anyway that's all up to whoever is responsible for drupal/coder.

**Comment by klausi** [comment]
Sorry, forgot to report back here: drupal.org now excludes Coder and we solved it as a special case in https://www.drupal.org/project/project/issues/3135034
