### ISSUE TITLE
Suggestion: Case-insensitive autoloader

### ISSUE THREAD

**Issue by ondrejmirtes** [composer/composer#8906]
Classes in PHP are case-insensitive. That means that even if I reference a class name with wrong case, it should work (`new datetime()`). And not just on Windows (case-insensitive filesystem).

Composer's autoloader doesn't behave like this. `ClassLoader::findFile` doesn't attempt to do so.

It might be challenging to do that with PSR-0/PSR-4 in `ClassLoader::findFileWithExtension`) but if Composer generated `autoload_classmap.php` with lower-case keys it'd be easy at least for that case.

Why I'm asking for this: Users might sometimes be unlucky if they reference classes with wrong case and that code is executed first - the class is not found. But in other circumstances it might work - if the class is loaded based on the name with the correct case, then the occurences with wrong case work too, because `class_exists(WrOnGcAsE::class)` will return true.

So without case-insensitive autoloader, people can experience weird and non-deterministic behaviour in production.

Related: https://github.com/phpstan/phpstan/issues/3047#issuecomment-624251312

**Comment by Seldaek** [comment]
The minor gains here are not worth the performance hit of having to strtolower every class name entering the autoloader IMO. This is something which static analysis can help fix IMO, by highlighting both class name -> file name mismatch, and wrong class name in usages.

**Comment by ondrejmirtes** [comment]
I guess that double the size of the class map by having both lowercase and actual case names in there, and check the actual name first, is a no go?

The problem is that PHPStan sometimes will report "unknown class name" and sometimes "wrong class name case" because of the autoloader behaviour which is why I opened this issue :) I wanted to make this behaviour deterministic. Which will be possible once we turn on the static reflection engine (and strtolower the class map index ourselves), but PHPStan will still sometimes fallback to the runtime autoloader.

**Comment by Seldaek** [comment]
IMO fixing this for the use case of static analysis is the wrong approach.. In practice it is very rarely a problem, so it's something that should rather be fixed by the static analyzers. 

Note that you could detect composer class loaders in `spl_autoload_functions()`, decorate them and de/re-register them decorated, with modified classmaps as you described for example.. This should be possible without too much hackery to even support runtime autoloading IMO.

**Comment by ondrejmirtes** [comment]
I found out about this behaviour thanks to static analyser, but my point was that this can happen to people whe normally running the application too. Anyway, I understand your point of view, it will be fixed by the static reflection engine :) 👍

**Comment by stof** [comment]
Also, for PSR-4 autoloading (rather than classmap autoloading), things become really hard for case-sensitive filesystems (i.e. the default on Linux), as you have to find the canonical case to find the file, which might involve trying all case variants (as the lowercase one might not be the right one)

**Comment by stof** [comment]
btw, the `symfony/error-handler` component already implements a decorator doing case checks to report a meaningful error on failed class loading.
