### ISSUE TITLE
Command to remove redundant dependencies (those already required by other requirements) from top-level composer.json

### ISSUE THREAD

**Issue by mlncn** [composer/composer#8925]
OK, so this request is weird and seems even weirder when i wrote it out, but the idea is when developing an application composed of multiple projects it can be faster to add dependencies at the root level composer.json, but for contributing we want to be sure everything is captured by one of the component projects.

Hence it would be very handy to have a 'simplify' or other command that removes any requirements in composer.json which aren't needed because *other* requirements in composer.json already account for them in *their* requirements.

**Comment by stof** [comment]
Well, the best practice is that any package that you use directly in your own code should appear in your own requirement rather than relying on transitive dependencies (because these transitive dependencies might change, either being removed or bumping to a new major version, which could then break your own code).
Given that the suggested command goes explicitly against this recommendation, I don't think it belongs to the core.

**Comment by mlncn** [comment]
To clarify, *all code would be in a dependency*.  My request is not going against recommendation that any package used in my code should appear in my requirements.  Our use case is a Drupal distribution which may be why it seems a little odd to other uses.  Root project brings in Project A.  Root project brings in Project B during development.  Project A is updated to require Project B.  There is no dependency in the root project on project B directly, and automated help to clean up the root project composer file to reflect this (only listing a requirement on Project A) would be useful.

**Comment by Seldaek** [comment]
That's something you could do as a plugin IMO, or an external tool running Composer commands to figure out what is needed still by the root package. I don't really see the use case for having this in Composer itself.

For example by calling `composer show -N` then `composer why $name` on every name returned, you could quickly determine this. Looking at this sample output using Composer dependencies:

```
$ composer why psr/log
composer/composer        2.0.x-dev  requires  psr/log (^1.0)
composer/xdebug-handler  1.4.1      requires  psr/log (^1.0)
symfony/debug            v2.8.52    requires  psr/log (~1.0)

$ composer why symfony/debug
symfony/console  v2.8.52  requires  symfony/debug (^2.7.2|~3.0.0)

$ composer why composer/ca-bundle
composer/composer  2.0.x-dev  requires  composer/ca-bundle (^1.0)
```

We can see that psr/log is required by composer/composer but also by something else, so I could drop the requirement from our composer.json and it would remain installed.

symfony/debug on the other hand is not required by composer/composer at all, so nothing to do.

And composer/ca-bundle is only required by composer/composer, so you wouldn't want to remove it either, as it would be gone otherwise.

I hope this helps you automate this.

**Comment by alexandre-le-borgne** [comment]
I made this:

```php
<?php

namespace App\Command;

use Composer\InstalledVersions;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

#[AsCommand('list-redundant-dependencies')]
class ListRedundantDependencies extends Command
{
    #[\Override]
    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $rootPackageName = InstalledVersions::getAllRawData()[0]['root']['name'];
        $rootDependencies = $this->getDependencies($output, $rootPackageName);
        $rootDependenciesIncludedInNestedDependencies = [];

        $packages = InstalledVersions::getAllRawData()[0]['versions'];
        foreach ($packages as $name => $data) {
            if($name === $rootPackageName) {
                continue;
            }

            $nestedDependencies = $this->getDependencies($output, $name);
            $commonDependencies = array_intersect($rootDependencies, $nestedDependencies);
            foreach ($commonDependencies as $dependency) {
                if ($dependency === 'php' || str_starts_with($dependency, 'ext-')) {
                    continue;
                }

                $rootDependenciesIncludedInNestedDependencies[$dependency][] = $name;
            }
        }

        $output->writeln(
            PHP_EOL . 'Got ' . count(
                $rootDependenciesIncludedInNestedDependencies
            ) . ' root dependencies included in nested dependencies'
        );

        foreach ($rootDependenciesIncludedInNestedDependencies as $rootDependency => $dependants) {
            $output->writeln('- ' . $rootDependency . ' required by : ' . implode(', ', $dependants));
        }

        return self::SUCCESS;
    }

    private function getDependencies(OutputInterface $output, string $package): array
    {
        $installPath = InstalledVersions::getInstallPath($package);
        $composerJson = $installPath . '/composer.json';
        if (!file_exists($composerJson)) {
            $output->writeln('Skipping ' . $package . ' : No composer.json found in ' . $installPath);
            return [];
        }
        return array_keys(
            json_decode(file_get_contents($composerJson), true, 512, JSON_THROW_ON_ERROR)['require']
        );
    }
}
```

Result: 
![image](https://github.com/composer/composer/assets/10196942/561e018d-16fd-4642-8535-dff6de579454)
