### ISSUE TITLE
Where to place the composer.json file for Artifact? 

### ISSUE THREAD

**Issue by wissem** [composer/composer#8931]
Looking at the Artifact docs, it mention that the composer.json file need to be at the root directory. But while looking at the `Composer\Util\Zip::getComposerJson($pathToZip)` it's working differently: it searches in the root directory for a composer.json but if it doesn't find it there it keeps searching until it finds the file with the shortest path.

Is that the expected behaviour? Or how should that work?

**Comment by naderman** [comment]
More specifically: If there are multiple composer.json files in a zip file it currently picks the one with the shortest path, which seems pretty random/arbitrary. I'd be in favor of only supporting the json on the top two levels of directory and erroring if there is more than 1 composer.json on that level. However that would be a BC break, I'm just not sure if this actually matters to anyone right now, since you wouldn't currently even be able to control which composer.json of multiple would get used?

@wissem Could you look into what exactly the behavior implemented for other archive types is? We should probably aim to have the same behavior for all types.

**Comment by stof** [comment]
For other archives, the composer.json is not read from the archive at all.

**Comment by naderman** [comment]
Oh I didn't realize the artifact repository doesn't support .tar.gz/bz2 at all?

**Comment by stof** [comment]
However, for the archive downloaders, they support having either the package content at the root, or having a single folder in the archive containing the content

**Comment by Seldaek** [comment]
## For metadata stage

artifact repo reads from zip OR phar files, and indeed finds either root composer.json or shortest path. The point of the shortest path thing isn't to support files with multiple composer.json, it's just because github archives for example come nested within a folder like `reponame-shortCommitSha`, so we need to find the composer.json in there.

No other repos look at archives of any kind IIRC.

## Download stage

Then when installing dist packages, a few downloaders support archives:

- ZipDownloader `zip`
- TarDownloader `tar`, `tar.gz` or `tar.bz2` (uses PharData only, some of these need the right extensions loaded IIRC)
- RarDownloader `rar`
- GzipDownloader `gz` but it does not support extracting further so single files only
- XzDownloader `xz` (requires system tar)
- PharDownloader `phar` 

All of these inherit from ArchiveDownloader which will do the same as the above, i.e. extract and if only one directory is present after extraction, move the contents of that directory one level above to eliminate the top folder wrapping.

Only zip is really used widely, the rest can be defined using package repos, so it has seen some use I'm sure but is definitely not as polished.

----

I don't really think the behavior of Zip util needs changing as it works well as is.. I don't necessarily think it'd need to be replicated to other formats if we add support for other formats in ArtifactRepo, because it was a workaround for the github zip format mostly.

**Comment by naderman** [comment]
I think what would work for all archive types, not cause issues with the current state of things would be:

- If there is a composer.json on the root level use it.
- If there is a single directory containing a composer.json use it.

All other cases would be invalid, so

- no composer.json on root and multiple directories on top level: invalid
- no composer.json on root and one directory containing exactly one other directory containing a composer.json: invalid

**Comment by Seldaek** [comment]
Yeah that sounds ok to me as a strictness cleanup for 2.0
