### ISSUE TITLE
Git::checkRefIsInMirror prevents https/git public usage

### ISSUE THREAD

**Issue by pierrejoye** [composer/composer#8932]
Using GitDowloader with the following config:
```
	$config->merge(['config' => [
        'secure-http' => true,
]);
```

I now get (just updated to latest stable composer release):

```
Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+MyStation+2020-05-28+1637
```
This is something that was not before. The git error happens in the Git::checkRefIsInMirror. Basically it seems it is not allowed for public repo anymore or something is wrong elsewhere.

Any thoughts?

You can see the usage here: https://github.com/FriendsOfPHP/pickle/blob/master/src/Package/Convey/Command/Git.php#L59

Or do you suggest an alternative way to use the download for any Git repo (public or not)?

**Comment by pierrejoye** [comment]
btw, doing  git clone https://github.com/beberlei/env.git ../testext in the console work just fine. So it could be some operations called in this method that requires now auth

**Comment by pierrejoye** [comment]
Found the culprit. HOME env is not defined.

`  - Installing env (master): PHP Notice:  Undefined index: home in /home/pierre/projects/php/pickle/pickle/vendor/composer/composer/src/Composer/Config.php on line 279

Notice: Undefined index: home in /home/pierre/projects/php/pickle/pickle/vendor/composer/composer/src/Composer/Config.php on line 279
Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos`

So another issue, minor, but the notice should not happen.

@Seldaek What behavior do you expect if HOME is missing? I can provide a PR

**Comment by pierrejoye** [comment]
2nd issue is why HOME is missing or does not make it at this stage inside composer. As it is defined and available before the call to GitDownloader.

**Comment by pierrejoye** [comment]
Any change regarding COMPOSER_HOME behavior when not set? It seems it was defaulting to ~/.config/composer before but latest do not, leading to the unset config HOME.

**Comment by Seldaek** [comment]
Not sure what this is all about, but `Undefined index: home` comes from a mis-initialized Config instance. It should be instantiated via Factory::createConfig https://github.com/composer/composer/blob/662d6d8351840ac25dc9d9b10deddc7df242b6cb/src/Composer/Factory.php#L164

As for HOME env var, which is something else, it needs to be defined or COMPOSER_HOME needs to be defined, as per https://github.com/composer/composer/blob/662d6d8351840ac25dc9d9b10deddc7df242b6cb/src/Composer/Factory.php#L56

I guess you figured it out somehow tho, but I'd suggest perhaps switching to Composer\Factory still.

Can this be closed otherwise?

**Comment by pierrejoye** [comment]
I use the later to fix it, including the COMPOSER_HOME check.

It looks, if I understand you correctly, like it should rely on Factory::createConfig only to be clean. I will update the code accordingly.

Thanks!
