### ISSUE TITLE
Feature Request: More robustness when encountering parse errors in version constraints

### ISSUE THREAD

**Issue by flack** [composer/composer#9195]
This is a bit of a followup to #9191 and related tickets: It appears that a parse error for version constraints in packages that are not even used in the current installation can prevent composer from working at all. It would be nice if composer would handle this situation more gracefully: A package that has nothing to do with your current installation shouldn't be able to block your installation from working. Wouldn't it be possible to simply skip packages with unparseable constraints (provided that they are not used ofc)?

**Comment by naderman** [comment]
Just to point out an issue with the logic here: you need to parse the constraints to work out whether the package should be installed. So you don't know whether the package should be used in the current installation unless you can parse the constraints.

**Comment by Seldaek** [comment]
Also, overall I am rather in favor of failing hard on such strictness issues, otherwise the whole ecosystem ends up in a mess. If we are not strict, repositories are free to do a poor job implementing things, and then the quality of everything slowly degrades.

Failing hard does cause occasional issues, but at least it gives a good incentive for things to get fixed.

**Comment by podarok** [comment]
> Failing hard does cause occasional issues

Occasional issues like an impossibility to install large distributions like Open Y/Drupal where we have tons of dependencies from modules where maintainers are slow?
C'mon. It's fine with having default as Failing, but should be at least option to proceed while dependencies are trying to fix new rule.
@Seldaek seems like some wrong decisions being maid which could lead to "composer is unreliable" perception.
Can we have better solution for strict rules?
Let's put strict rules in version 2 of composer to give people time to upgrade, but braking version 1 just because there is a need - bad

**Comment by Seldaek** [comment]
There is one package that I know of causing issues, if you don't require it you don't have a problem. You can also very easily use Composer 1.10.10 until this is resolved. I think we have a fairly ok track record of reliability, especially when compared to other package managers out there.

**Comment by flack** [comment]
Well, if you insist on failing hard, there really needs to be better testing before pushing out releases. If a minor point release immediately breaks a ton of unrelated projects and entails 24 hours of back and forth with fixes and new emergency releases, that just creates unnecessary stress for everyone involved. Somebody mentioned in the other ticket running the new release against all packages on packagist, maybe that is something that can be done as a standard part of the release progress?

And yes, composer had a good track record for reliability these last few years. I still remember the early, pre-1.0 days where `composer self-update` had like a 50% of breaking my stuff, and I really don't want to go back to that.

**Comment by ryanaslett** [comment]
> Failing hard does cause occasional issues, but at least it gives a good incentive for things to get fixed.

While I agree with failing hard on strictness issues, I dont think we have to do that in a move fast and break things kinda way, forcing us to drop what we're working on, and switch into emergency stress mode knowing that a large portion of the drupal ecosystem is unable to move forward with their builds until I'm able to rush to get a fix.

We'll do what we can, but Im unavailable to work on this until tomorrow at the earliest.
