### ISSUE TITLE
Legacy classmap notation supported or deprecated?

### ISSUE THREAD

**Issue by ondrejmirtes** [composer/composer#9229]
I stumbled amphp/process v0.1.3 which has this weird thing in its composer.json:

```
    "autoload": {
        "classmap": [
            {"Amp\\Process": "Process.php"}
        ]
    }
```

Composer's documentation only talks about an array of strings (directories). How this entry should be interpreted? Is it still supported? Shouldn't Composer mark it as error?

I'm asking about this because PHPStan reads autoload information from composer.json and installed.json and it doesn't expect this notation...

Thank you!

**Comment by Seldaek** [comment]
Right, our validation only checks that classmap is an array, not deeper, as we technically support arrays of arrays because you can do `psr-4 => array<namespace string, string[] | string>`, and we just parse this with the same code for classmap, so it really supports `classmap => array<useless key, string[] | string>`, so in this case the object is turned into an array anyway in php, and just behaves the same as `classmap: ["Process.php"]` which is technically valid. It just looks wrong..

**Comment by Seldaek** [comment]
The way it's done here is https://github.com/composer/composer/blob/cc1e91ba8c606fea66c3ec9697e9fdb17726ce78/src/Composer/Autoload/AutoloadGenerator.php#L1049-L1050 - which I guess you could replicate to be sure you support everything that's out there.
