### ISSUE TITLE
It is recommended to store development dependencies and production dependencies in separate directories.

### ISSUE THREAD

**Issue by allowing** [composer/composer#9238]
It is recommended to store development dependencies and production dependencies in separate directories.

Sometimes developers may not want to ignore the `vendor` directory and submit it to the version control system, but they don't want to submit development dependencies.

**Comment by stof** [comment]
> It is recommended

where does this recommendation come from ?

**Comment by allowing** [comment]
For example, `phpmyadmin` does not ignore `vendor`

**Comment by dereuromark** [comment]
I also wonder.
This is the first time I ever hear about this, and it sure doesn't seem to be the case for the PHP (and composer) ecosystem.
Especially since the tool properly handles the separation on the low level and does not include dev dep on prod systems by design
Separating them in different folders is not helping here either.
And committing vendor seems also like a huge smell and counter productive to me given the whole picture of how composer works and was designed to work.

**Comment by Seldaek** [comment]
See https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md - and sorry but no we are not going to change this.
