### ISSUE TITLE
Feature request: event on load class (ClassLoader)

### ISSUE THREAD

**Issue by WinterSilence** [composer/composer#9248]
_I use new syntax to be code more readable_

### Vendor package
`composer.json`:
~~~json
{
    "scripts": {
        "autoload": "MyVendor\\AutoloadHandler::handle",
}
~~~
`AutoloadHandler.php`:
~~~php
namespace MyVendor;
use Composer\Autoload\Event;
class AutoloadHandler
{
    public static function handle(Event $event) {
         // for example, initialize static class:
         if (! $event->isMissingClass() & is_subclass_of($event->getClassname(), '\MyVendor\InitStaticInterface')) {
             [$event->getClassname(), 'init']();
         }
    }
}
~~~
### Composer
New event class:
~~~php
namespace Composer\Autoload;
class Event
{
     public function __construct(ClassLoader $loader, string $classname, ?string $filename = null)
     public function getClassLoader(): ClassLoader;
     public function getClassname(): string;
     public function getFilename(): ?string;
     // "short-hands"
     public function isMissingClass(): bool
     {
          return $this->getFilename() === null;
     }
}
~~~
Updated `ClassLoader`:
~~~php
class ClassLoader
{
    private $eventDispatcher;

    // optional: passed if event have handlers/listeners
    public function setEventDispatcher(EventDispatcher $dispatcher)
    {
        $this->eventDispatcher = $dispatcher;
    }

    public function getEventDispatcher(): ?EventDispatcher 
    {
        return $this->eventDispatcher;
    }

    public function loadClass(string $class): ?bool
    {
        $file = $this->findFile($class);
        if ($file  !== false) {
            includeFile($file); // why not static function/closure? 
        }
        if ($this->getEventDispatcher() !== null) {
           $this->getEventDispatcher()->dispatch(new Event($this, $class, $file ?: null));
       }
        // fix bug: void !== null
        return $file === false ? null : true;
    }
}
~~~

**Comment by stof** [comment]
IMO, this is a bad idea:

- this will add overhead to the autoloader for all classes, which is a very performance-sensitive code
- this is by design incompatible with PHP 7.4 preloading (which is bad news for performance)
- it can become very hard to debug: the dispatched event would be coming from the PHP autoloading stack, where PHP has some special behavior. Running complex logic in this place can be tricky
- for legacy codebases which rely on doing some special static initialization (which is a bad idea for modern codebases IMO), a solution could be to use a dedicated autoloader instead of the composer one. See https://github.com/swiftmailer/swiftmailer/blob/ff832c46efb93bd8c7ec86273fc292fc170b76a1/composer.json#L31-L33 for an example (be careful that this will still be incompatible with preloading, but at least classes from other ). But by making this part of a specific autoloader, it solves previous points:
    - this specific autoloader can be registered after the composer one, so that the optimized autoloader first handles all classes not needing static initialization without ever reaching the other one
    - the specific autoloader can easily filter out any unrelated class so that it does not perform logic for classes of other packages
    - by calling the static initialization logic directly rather than using the EventDispatcher abstraction, the amount of logic running in the autoloading stack is reduced

**Comment by WinterSilence** [comment]
> this will add overhead to the autoloader for all classes, which is a very performance-sensitive code

yes, it's true for my example, but it can be cached same as class map

> this is by design incompatible with PHP 7.4 preloading (which is bad news for performance)

please, explain with code sample

> it can become very hard to debug

any solution has a certain cost - package developers have the right to decide for themselves whether to use this event

> for legacy codebases which rely on doing some special static initialization

your package can require some legacy packages too. also, my example it's only example... for example (:  event handler can set aliases or load polifills optional

> be careful that this will still be incompatible with preloading, but at least classes from other

this is other thing, I'm can inject autoloader in my decorator and replace autoloader to decorator. It's not "i dont know how do it, add crutch to me".

**Comment by stof** [comment]
> yes, it's true for my example, but it can be cached same as class map

you still need to dispatch an event for each autoloaded class, without knowing whether a listener will care about it. That's the performance cost.

> please, explain with code sample

with preloading, classes are already loaded by the preloaded code. So the autoloader is not called, and your event is never triggered => your static initialization is not done...

> your package can require some legacy packages too

The legacy codebase could be one of the vendor packages. And btw, the example I gave with swiftmailer is exactly such a case

> this is other thing, I'm can inject autoloader in my decorator and replace autoloader to decorator. It's not "i dont know how do it, add crutch to me".

I'm not talking about adding a decorator. I'm talking about registering a *separate* autoloader dealing with classes form the package requiring such static initialization **instead of** using the composer autoloader (if you decorate the composer autoloader, you will still run your custom code for all classes and might break performance easily too if not careful, while the separate autoloader will be called only when the composer autoloader cannot find the class, if the order is the correct one).

**Comment by WinterSilence** [comment]
> with preloading, classes are already loaded by the preloaded code. So the autoloader is not called, and your event is never triggered => your static initialization is not done...

you talk about opcache optional features? preloaded classes not use autoloader in any case

**Comment by stof** [comment]
yes, I'm talking about the PHP 7.4 preloading feature, which is indeed a part of OPCache.

**Comment by WinterSilence** [comment]
@stof 
> And no, the effect of the listener cannot be cached by Composer.

i don't talk about it, but otherwise you're right - need register my autoloader after Composer's loader.
