### ISSUE TITLE
Drop support for older PHP releases

### ISSUE THREAD

**Issue by Seldaek** [composer/composer#9303]
As per #8785 - for 2.1 or 2.2, bump php requirement to 7.1.3, and bump all dependencies.

Grep for PHP_VERSION_ID to find stuff needing fixing.

Edit May 2021: Probably targetting PHP 7.2.5 now for Composer 2.3 as the timelines have slipped.

**Comment by GrahamCampbell** [comment]
Going to PHP 5.5.9 with Symfony 3.4 in Composer 2.1 might be a good idea, in particular, because PHP 8 support was never implemented on Symfony 2.8. Then maybe go all the way in a later release to PHP 7.1.3 with Symfony 4.4. Then again, I guess you don't want to end up with more than one LTS series of Composer 2.x...

**Comment by stof** [comment]
Given that Symfony 3.4 reaches end of bugfix support at the end of November, I doubt making it a target for the version used in Composer 2.1 is a good idea: it would probably already be in security-only support by the time composer 2.1 gets released.

**Comment by GrahamCampbell** [comment]
Certainly better than Symfony 2.8 though, which is what we currently have.

**Comment by simonberger** [comment]
Raising support to PHP 7.1.3 is a nice step. It gives much room to improve the code with new PHP language and dependency features and isn't that new leave too many behind.

In my opinion sticking to any PHP 5.X version and with it using Symfony 3 instead of 4 just slows down improvements. The long planned support for Composer 2.0 should fill the gap enough.

**Comment by morrisonlevi** [comment]
How long do you plan to support 2.0.x for bug and security fixes? As already noted, PHP 7.1 isn't an LTS version on any known OS that do LTS's: https://github.com/composer/composer/issues/8785#issuecomment-635240404. Using Symfony 5 means using a supported Symfony release longer than Symfony 4.4.

Circling back to my opening question:
  1. There are LTS users on PHP 5.5 and 7.0 and you already plan to support them through Composer 2.0 (for some unknown amount of time)
  2. PHP 7.2 is the next version with widespread LTS support
  3. I don't see any reason PHP 7.1 can't use the same security updates on composer 2.0 meant for the other outdated PHP versions.

IMO, the other option to support PHP 7.0 as it also has LTS support, but since it seems you've already ruled that out it makes sense to solidify on the next major LTS, which isn't PHP 7.1.

**Comment by Seldaek** [comment]
First just for reference, most likely Composer 2.1 will be the LTS one and then 2.2 will drop old PHP. This is only the current plan though, we'll see how it ends up.

1. According to that comment on LTS distros you linked, we'd need to support Composer 2.1 until 2024 then.. I think to be honest it sounds reasonable if we only talk about bug/security fixes. The more minor bugfixes might see less backports with time because 2024 is pretty far away, but overall Composer is fairly stable.
2. That's a good point, we probably will have to drop 7.1 at some point to be able to upgrade to Symfony 5 dependencies. Depending on when 2.2 comes out it might be reasonable then, or if not it might be ok a few minor releases down the line. At that point we can still tell people insisting  on using 7.1 that they can use the LTS Composer 2.1. Until/unless we really need Symfony 5 though, I don't really see the benefit in bumping to 7.2 as language-wise it doesn't bring us much.
3. I think that's the same thing I just said, but I am not sure I understand your sentence.

As for "why 7.1", the thing is I am looking at our current user base, and not just at the LTS distros. LTS distros for sure have an effect on adoption, but tons of people also use other PHP versions one way or another. This is what I am seeing right now:

![image](https://user-images.githubusercontent.com/183678/97917191-69895b80-1d54-11eb-8e3f-0ab360caad39.png)

So yeah as per point 2 + the graph, I think 7.1+ is a good choice right now.

**Comment by morrisonlevi** [comment]
Sounds like our viewpoints are pretty similar and I guess it really hinges on how far out Composer 2.2 will actually be.

**Comment by paveldvorak5** [comment]
Please drop the old dependencies soon, I run into Symfony 5 problem again today.

**Comment by GrahamCampbell** [comment]
@paveldvorak5 I don't follow how this is constructive feedback? Are you offering your services to free to speed up this transition?

**Comment by imme-emosol** [comment]
Is it an option to skip the 2.2 and directly go to php ^7.4 ? Because: property data typing.

Developers and CI-scripts can run composer with recent enough php-versions (through docker or /usr/local/ ), right?

The BackwardCompatibility of the generated autoloader-scripts might be another issue.
As such, it might be an idea to move the autoloader generator into a separate package, so the composer.json in it can inform users about its compatibility with legacy php-versions?

**Comment by imme-emosol** [comment]
Yes, definitively. :+1: 

Just tell all users that native data typing is more aesthetically pleasing than docblocks, I am sure they'll understand and be very sensible about it :grin:

**Comment by Seldaek** [comment]
Fixed by https://github.com/composer/composer/pull/10428 and a few others over the last few days.
