### ISSUE TITLE
Bug?: Package is moving when adding an unrelated *installed* package to `composer.json`

### ISSUE THREAD

**Issue by ThomasLandauer** [composer/composer#9365]
In short:
I have package A and package B actually installed, but not contained in `composer.json`. When I add package A to `composer.json` and run `composer update`, package B changes (up/downgrade).
When I add package B too, those changes get reverted, and everything's fine again.

In long:
**1:**
In the beggining, I have this in my `composer.json` (only showing `doctrine/*` and `symfony/security-*`):
```json
"doctrine/annotations": "^1.8",
"doctrine/dbal": "^2.12",
"doctrine/orm": "^2.7",
"symfony/security-bundle": "4.4.*",
```
...and this is contained in the output of `composer show`:
```
doctrine/persistence  1.3.8
symfony/security-core v4.4.15
```
**2:**
Now, if I add `"symfony/security-core": "4.4.*",` (=package "A") to `composer.json` and run `composer update`, this happens:

```bash
Lock file operations: 0 installs, 3 updates, 1 removal
  - Removing doctrine/reflection (1.2.1)
  - Upgrading doctrine/common (2.13.3 => 3.0.2)
  - Upgrading doctrine/persistence (1.3.8 => 2.1.0)
  - Downgrading symfony/orm-pack (v1.2.0 => v1.1.0)
```
Expected result would be: No change at all; since I already have `symfony/security-core`, and just adding it to `composer.json` shouldn't change anything.

**3:**
But then, if I also add `"doctrine/persistence": "^1.3",` (=package "B") to `composer.json` and run `composer update`, the downgrade is undone:
```bash
Lock file operations: 1 install, 3 updates, 0 removals
  - Downgrading doctrine/common (3.0.2 => 2.13.3)
  - Downgrading doctrine/persistence (2.1.0 => 1.3.8)
  - Locking doctrine/reflection (1.2.1)
  - Upgrading symfony/orm-pack (v1.1.0 => v1.2.0)
```

Composer version 2.0.2

I already opened an issue at `doctrine/persistence`, but it was closed: https://github.com/doctrine/persistence/issues/140

**Comment by Seldaek** [comment]
Note that symfony/orm-pack 1.2 requires doctrine/common 2.*, while symfony/orm-pack 1.1 does not have a require on that at all. I think that explains why as it downgrades or upgrades the orm pack, the rest changes.

Now the question is why is the orm pack changing. I can't answer that from the info I have. I actually can not reproduce the problem given the info you gave.

Installing just the 4 first deps, I get these installed:

```
doctrine/persistence                 2.1.0
symfony/security-core                v4.4.16
```

Then adding the security-core require does not update anything.

I think what happens is that adding the require changes the path the solver takes to determine which dependencies should be selected. And in this case due to the symfony/orm-pack having either version 1.2 (higher) which requires doctrine/common 2 (lower), or symfony/orm-pack version 1.1 (lower) which allows doctrine/common 3 (higher), both are valid but also it's not clear which is superior, so it depends which one it stumbles upon first, and then when it finds a valid solution it ends there.

If you add a require for symfony/orm-pack 1.2 as well, hopefully you can force it to select the packages you want. Or maybe you should not care if those are not your dependencies anyway and your dependencies say they work with all versions, then it should not matter.
