### ISSUE TITLE
composer 2.0.x doesn't find version tags in vcs repositories

### ISSUE THREAD

**Issue by mkalkbrenner** [composer/composer#9371]
I test the installability of my libraries  using composer using github actions.
All of them are currently broken since composer 2.0 has been released.
It seems like tags in a git repository aren't identified as version string anymore.
Here's a snippet of https://github.com/mkalkbrenner/search_api_solr/blob/4.x/.github/workflows/jump-start-config-sets.yml

```
            - name: Checkout search_api_solr
              uses: actions/checkout@v2
              with:
                path: search_api_solr
                fetch-depth: 0

            - name: Tag search_api_solr
              run: |
                cd search_api_solr
                git tag 4.99.0

            - name: Install dependencies
              run: |
                cd drupal
                composer config repositories.search_api_solr '{"type": "vcs", "url": "../search_api_solr"}'
                composer require drupal/search_api_solr:4.99.0
 ```

Even with composer 2.0.3 I get the following output:

```
Error: Could not find package drupal/search_api_solr in a version matching 4.99.0
```

This approach worked perfectly well with composer 1.x

**Comment by Seldaek** [comment]
I think I see the issue, will try to work on a fix a bit later.

**Comment by mkalkbrenner** [comment]
Thanks!

**Comment by Seldaek** [comment]
Ok I fixed the config command to now prepend repos instead of appending them, which should fix your problem if you use the composer snapshot (I'll try to do a release later anyway).

@greg-1-anderson @mixologic @xjm Related to this issue, sorry not sure where else to report this, I noticed drupal/drupal ships with the drupal.org repository on top https://github.com/drupal/drupal/blob/9.2.x/composer.json#L107 - probably for composer 2 given https://getcomposer.org/repoprio it makes more sense to have it at the bottom to make sure the path repos are above, and to hint at users that their custom repos should go above too.

**Comment by greg-1-anderson** [comment]
Thanks @Seldaek this should help a lot. Created https://www.drupal.org/project/drupal/issues/3179875
