### ISSUE TITLE
Gitlab private repository auth.json not working

### ISSUE THREAD

**Issue by iamrekas** [composer/composer#9373]
My `composer.json`:

```json
{
...
  "config": {
  ...
    "gitlab-domains": [
      "gitlab.vendor.com"
    ]
  ...
  },
  "repositories": {
    "vendor": {
      "type": "composer",
      "url": "https://gitlab.vendor.com/api/v4/group/vendor/-/packages/composer/"
    }
  }
...
}
```

My `auth.json`:

```json
{
    "gitlab-token": {
        "gitlab.vendor.com": "SOME_TOKEN"
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0.3
PHP version: 7.4 - Package overridden via config.platform, actual: 7.4.11
PHP binary path: /usr/local/bin/php
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
cURL version: 7.64.0 libz 1.2.11 ssl OpenSSL/1.1.1d
zip extension: OK
```

When I run this command:

```
composer require vendor/package
```

I get the following output:

```
[Composer\Downloader\TransportException]                                                                                                    
  The "https://gitlab.vendor.com/api/v4/group/vendor/-/packages/composer/packages.json" file could not be downloaded (HTTP/1.1 404 Not Found)
```

And I expected this to happen:
it must work or i can make debug to check is it my fail or not...

I am using private gitlab server and try use token. it's failing... i try put token inline - works. try put "http-basic" in auth.json (using same token and same inline way) - not works.. 

Thanks for your help.

**Comment by Seldaek** [comment]
I don't have a private gitlab install so can't really check that, but using gitlab.com it all seems fine to me using `vcs` repo type and loading the package like that. I didn't test their composer repo functionality but I don't see why the authentication would not apply to it as it's an url like any other.

Anyway as workaround I'd suggest using `type: vcs` repository and the git repo url, or use [Private Packagist](https://packagist.com) which syncs from GitLab and has a much nicer integration with a unified composer repository.

**Comment by strausmann** [comment]
Good Day,

Is the gitlab private instance Domain defined in the composer.json? 

composer config gitlab-domains gitlab01.example.com gitlab02.example.com

Reading the docs please. 

https://docs.gitlab.com/ee/user/packages/composer_repository/ 

Best regards 

Björn

**Comment by strausmann** [comment]
@Seldaek,

I just took a look at the problem myself. It seems that the error is in the new Composer v2. With Composer v1 everything works as expected.
I followed the instructions of GitLab (see above).

If you use the http-basic instead of the gitlab-token in auth.json, it will also work with Composer v2.

Do you have an idea what this might be?

Best Regards,

Bjoern

**Comment by strausmann** [comment]
Feel free to contact me for access to a Gitlab Self-Hosted Instance.
You can get the contact information through my packagist.com subscription.

Thanks

**Comment by strausmann** [comment]
I can see that in the 2.0.0-alpha1 release for GitLab the Deploy Tokens have been integrated. 

I just tried the Deploytoken and it seems to work without problems.

```json
{
    "gitlab-token": {
        "gitlab.privateinstance.de": {
            "username": "testcomposerbug",
            "token": "MyDeployToken"
        }
    }
}
```

**Comment by Seldaek** [comment]
FYI `gitlab-token: { domain: $TOKEN }` (what @iamrekas is using) gets loaded as if you put http-basic auth with username `$token` password `private-token` https://github.com/composer/composer/blob/3daa174bc171dd332d73212b1acfa98e89b06cc9/src/Composer/IO/BaseIO.php#L137

See https://getcomposer.org/doc/06-config.md#gitlab-token for details

I don't know why they have so many different auth methods private tokens and deploy tokens and they are used differently, it's such a mess to document for users :/

**Comment by strausmann** [comment]
@Seldaek 

So at Gitlab there is the user token, which is used with the private-token in the header or as the username.
With this token Composer has access to all projects the user has access to.

The Deploy token is intended to allow limited access to the projects within the namespace in the case of the associated GitLab group.

This is simply a security idea, that one token does not always allow access to too many projects.

**Comment by Seldaek** [comment]
That's fine to have different tokens with different levels of access, but why do we have to configure them differently, and use them differently when accessing gitlab? Is it just a misunderstanding on our end and this could be simplified? Or is it really so messy on gitlab's end?

**Comment by strausmann** [comment]
The user token really has no username, so in this situation only the token is specified.

But the Deploy Token has a username. When creating the Deploy Token, a dummy user is created, which has access to all projects of the GitLab Group.

So yes, it's a bit complicated with GitLab, and you have to distinguish between a user and a deploy token when using them.

**Comment by Seldaek** [comment]
Ok thanks for explaining, sorry but I'm really not so familiar with GitLab, I spend most of my time here ;) 

If you see ways to help clarify our docs on this and feel like sending a PR that'd be great.

Back to this issue though, you say deploy tokens work, but private tokens maybe don't in Composer 2? Or am I mistaken?

**Comment by strausmann** [comment]
Apparently my test token for my Composer (2.0.4) test was not correct. Sorry for this mishap.
The appropriate return of an error message is not yet ideal for GitLab with Composer.

I have now successfully used the GitLab Composer Registry with v2.0.4 and the following configuration.

However, I did find a mistake. But more about that at the end...

In order to be able to understand the procedure again, here are all my steps again.

1. Creating a composer.json with the following content:

```json
{}
```

2. Adding the Composer repository:

```shell
composer config repositories.gitlab.privateinstance.de/127 '{"type": "composer", "url": "https://gitlab.privateinstance.de/api/v4/group/127/-/packages/composer/packages.json"}'
```

3. Adding the Gitlab domains:

```shell
composer config gitlab-domains gitlab.privateinstance.de
```

4. Adding the GitLab token:

```shell
composer config gitlab-token.gitlab.privateinstance.de MyToken
```

5. Adding the Composer Package:

```shell
composer req testcomposerbug/php-package:1.1.1
```

This results in the following structure for the Composer.json:

```json
{
    "repositories": {
        "gitlab.privateinstance.de/127": {
            "type": "composer",
            "url": "https://gitlab.privateinstance.de/api/v4/group/127/-/packages/composer/packages.json"
        }
    },
    "require": {
        "testcomposerbug/php-package": "1.1.1"
    },
    "config": {
        "gitlab-domains": ["gitlab.privateinstance.de"]
    }
}
```

This results in the following structure for the Auth.json:

```json
{
    "gitlab-token": {
        "gitlab.privateinstance.de": "MyToken"
    }
}
```

A few weeks ago, we had an issue in the GitLab project, where the definition of the Self-Hosted GitLab Instance Domain in composer.json was missing, so here's my first comment on the topic, I had already revised the GitLab documentation accordingly with the gitlab-domains hint.

Now to the mentioned bug I found.

If you want to use a GitLab private token for Gitlab.com, no extra gitlab-domains entry is required.
However, once you have added a GitLab Self-Hosted Instance entry, you need to add gitlab.com to the entry. 

Otherwise, gitlab.com will use the token as the username.

One more question, what is the shell command for Composer to give GitLab not only the token but also a username?

**Comment by Seldaek** [comment]
- shell command I guess it would be `composer conifg gitlab-token.example.org username token` but it won't work it expects only a single value right now. We'd need to add support for that.
- the bug, that's a good point, github-domains also has the problem it seems, if you override it it gets overwritten instead of merged.. Should be easy to fix too though.

So it sounds like mostly it works though, given it's correctly configured. @iamrekas does this help you or do you still have issues?

**Comment by iamrekas** [comment]
Thanks all for responding in my issue.

@Seldaek I make switch to http-basic with token authentication and to my is working. so i doesn't going more, cuz for now doesn't have enough time to play with configuration. for now working, then i will have more time, i will try others methods that is posted by other persons in this issue.

**Comment by Seldaek** [comment]
@strausmann I fixed the two issues you mentioned in the two commits linked above. Going to close this issue as I am not sure what else can be done here.
