### ISSUE TITLE
Changes to default platform check behavior

### ISSUE THREAD

**Issue by Seldaek** [composer/composer#9412]
It's quite clear the more people move to Composer 2 that this is causing problems in many places. We've had many issues reported, and tweets and whatnot, plus as https://github.com/composer/composer/issues/9411 shows a few sites are actually down still due to this.

I see a few ways to improve this while still retaining some value to the feature:

- [x] **Skip extension checks by default** by changing the platform-check option to be `false` (off), `php-only` (new default), or `true` (full check of exts+php, current default). The reason here is it seems like in most cases it's failing due to some ext which is optionally required, and everything would work fine still without it. Not exactly warranting a white page.
- [x] **Skip dev dependencies** by persisting to installed repo which packages are dev requires and which are not. The reason here is I suspect in some cases people deploy with dev dependencies included and that can change the required platform packages quite substantially in some cases.
- [x] **Improve output** explaining a bit more what is going on, how this can be fixed, etc.
- [x] **Improve http responses** by making sure if we're in a web sapi we set the response status code to 500 before exiting. Also adding  a link to the platform-check docs. In progress in https://github.com/composer/composer/pull/9410
- [ ] **Improve docs** to include details from https://github.com/composer/composer/issues/9377#issuecomment-719019204
- [x] **Follow error reporting standards more closely** On CLI throw a regular error and let PHP decide how to log/output it, on other sapis try to display some hint as to what caused the error without exposing specific info like php version (ranges), throw a PHP error to make sure logging/error reporting settings are respected. In progress in https://github.com/composer/composer/pull/9414

Frameworks who wish to force this on their users could still include the platform-check option set to `true` in their project templates.

**Comment by JohnMaguire** [comment]
>  Skip dev dependencies by persisting to installed repo which packages are dev requires and which are not. The reason here is I suspect in some cases people deploy with dev dependencies included and that can change the required platform packages quite substantially in some cases.

Just wanted to chime in and say thanks for this change! Our development workflow involves creating a "production" build container (without dev dependencies), and then overlaying our development repository over it. The development repository contains dev dependencies since we need to run tests, but the production image does not contain the required PHP extensions for these, since they're not used inside the Docker container itself.

This caused an issue where we suddenly started seeing errors in our development environment which broke the application, but not our production environment. The behavior was present in 2.0.4, but not 2.0.7 and was a bit tricky to track down the reason. I believe this is it, and the new behavior is much welcomed!
