### ISSUE TITLE
Parsing exception when use private satis

### ISSUE THREAD

**Issue by matthieumota** [composer/composer#9417]
My `composer.json`:

```json
"repositories": [{
    "type": "composer",
    "url": "https://foo-satis.com"
}]
```

When I run this command:

```
composer require vendor/package
```

I get the following output:

```
[Seld\JsonLint\ParsingException]
"https://foo-satis.com/p2/vendor/package.json" does not contain valid JSON
```

And I expected this to happen:

Nothing special but fallback to packagist if package is not present on Satis. I know that Satis app can handle a 404 if file does not exists but composer can handle that more easily. I'm going to open a PR.

**Comment by stof** [comment]
Are you sure that your server returned a proper 404 response ? Composer knows how to deal with 404.

**Comment by matthieumota** [comment]
Nope, server return a 200 response (badly I know) but I think we can easily handle that ?

**Comment by stof** [comment]
Disable support for the Composer v2 metadata in your Satis build then. The v2 metadata format relies on getting proper 404 for non-existent metadata. That's part of the format.

**Comment by matthieumota** [comment]
I agree with you. I was just thinking about this option but I couldn't find it anymore. I thought I dreamed of it. Or I'll configure Nginx to return a clean 404. Thank you, we can close issue I think.

**Comment by stof** [comment]
Well, there is an option to specify `available-packages` in the packages.json file (not sure whether Satis supports configuring it).
But in any case, configuring nginx properly is a must-have. It should return proper 404 status code on missing metadata, and proper `Last-Modified` headers on existing files (the second point is optional if you don't care about having no cache, but make sure it does not return inaccurate values at least, because a wrong cache will cause you a lot more issues than no cache)

**Comment by stof** [comment]
> I was just thinking about this option but I couldn't find it anymore.

Looks like there is no option. And that actually make sense. As the composer team wants to push for the new repository format (which is much more efficient), there is no point allowing Satis to disable it. So that would require using an older version of Satis (before the support of the v2 metadata), which is only a workaround.

**Comment by matthieumota** [comment]
Of course, we can downgrade to Satis v1 but not interesting. I'm going to handle 404 correctly on server.
