### ISSUE TITLE
Command "self-update" is not defined.

### ISSUE THREAD

**Issue by KarelWintersky** [composer/composer#9419]
When I run this command:

```
composer self-update --2
```

I get the following output:

```
  Command "self-update" is not defined.
```

So, `self-update` command not available for most default composer packages at debian/buster. 
I have debian buster and latest composer version are: `Composer 1.8.4 2019-02-11 10:52:10`

So, add hint to https://blog.packagist.com/composer-2-0-is-now-available/

**Comment by Seldaek** [comment]
This is a packaging issue and is entirely debian's fault IMO, because they choose not to install the phar we ship. That's why we do not support nor recommend installing via OS package managers. They leave you with a much outdated Composer.

You can run the installer from https://getcomposer.org/download/ with the rigth params to the installer to overwrite your local install:

Something like:

```
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === 'c31c1e292ad7be5f49291169c0ac8f683499edddcfd4e42232982d0fd193004208a58ff6f353fde0012d35fdd72bc394') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php --install-dir /usr/bin --filename composer
php -r "unlink('composer-setup.php');"
```

With `--install-dir /usr/bin --filename composer` matching the output of `which composer`.

**Comment by KarelWintersky** [comment]
Is it possible publish deb-packages of composer (in releases)? 

I can make them ;)

**Comment by Seldaek** [comment]
Nope sorry but I don't really feel like maintaining this. Our php-only installer is enough IMO. See also https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md

**Comment by KarelWintersky** [comment]
As you wish.

**Comment by int-ua** [comment]
> because they choose not to install the phar we ship

Do I understand correctly that this phar would have a way to affect system files with root privileges that's harder to verify for being non-malicious?

**Comment by Seldaek** [comment]
@int-ua the phar does not require root privileges, if you run it with root privileges sure it's like any other piece of code, it can do things. We do advise against that though and explicitly warn when running as root.

Also, we went to great lengths to make sure that the phar can be built reproducibly, so that you can verify integrity.

**Comment by TechNov** [comment]
> When I run this command:
> 
> ```
> composer self-update --2
> ```
> 
> I get the following output:
> 
> ```
>   Command "self-update" is not defined.
> ```
> 
> So, `self-update` command not available for most default composer packages at debian/buster. I have debian buster and latest composer version are: `Composer 1.8.4 2019-02-11 10:52:10`
> 
> So, add hint to https://blog.packagist.com/composer-2-0-is-now-available/

Think @KarelWintersky , you save and solve me

**Comment by stof** [comment]
Well, then install composer through an officially supported channel. Installing it from the Debian apt package is not officially supported by the Composer team, so you should then contact the Debian maintainers instead.
