### ISSUE TITLE
latest version doesn't work.

### ISSUE THREAD

**Issue by yelojedi** [composer/composer#9435]
the latest release doesn't work at all, please roll back instead of making waste everybody time.

**Comment by techthatmatters** [comment]
> the latest release doesn't work at all, please roll back instead of making waste everybody time.

Same problem with me

**Comment by yelojedi** [comment]
can't apply patches, and with no patches at all composer install. rollback this crap release please. we can't deploy.

**Comment by Seldaek** [comment]
@yelojedi screw you and your entitlement.

First of all the latest release did work, it failed to handle some custom installers, under some conditions. 

Second, if you want some help first of all you could say what is happening and how to reproduce it, like the issue template asked you to. You can thank the good people of https://github.com/composer/composer/issues/9431 for reporting it correctly, and you can thank me for taking some time of my Saturday to do an emergency fix and release. 

Thirdly, learn to use your tools before whining. You can run `composer self-update 2.0.4` to downgrade to 2.0.4 and move on with your day after reporting the issue, instead of coming back here to whine about the "crap release".

2.0.6 is now out. Good day to you.

**Comment by GrahamCampbell** [comment]
@yelojedi It is **your** job to test the software you are using works after an upgrade before using it in production. **Nobody else's**.

**Comment by nealio82** [comment]
@yelojedi do yourself a favour and [watch this video](https://www.youtube.com/watch?v=cOjS7iof6SU), then re-assess how you interact with people who are working for free to bring you tools. Absolutely nobody is forcing you to use Composer. Write your own package manager if you need to.

Your stress and panic because you haven't test-deployed to staging / test-installed / etc after updating Composer, or because you're tight on a deadline, isn't @Seldaek's problem or responsibility.

**Comment by yelojedi** [comment]
@nealio82 fact is since yesterday release composer install on deploy are broken because it was not tested right. It breaks on applying patches.
PATCHES.txt: failed to open stream: No such file or directory. this error appear since yesterday version.
It is the maintainer job to assure that it is at least working on previous composer.json versions.
We don't all have the permissions on the servers to use a previous version.

**Comment by ahinkle** [comment]
> It is the maintainer job to assure that it is at least working on previous composer.json versions.

That is not how open source works. Maintainers don’t owe you **anything**. They are doing this for **free**  out of the goodness of their hearts.

**Comment by liam-wiltshire** [comment]
Sorry @yelojedi , but if this is how you treat fellow developers you need to leave and get a job where being a dick is rewarded, like politics. It is no-one's job but yours to make sure it works in _your_ environment. Maintainers are volunteers (although I'd also never speak to an employee like that either!), they literally owe you nothing. If its that urgent, fix it yourself and submit a PR.

**Comment by nealio82** [comment]
> We don't all have the permissions on the servers to use a previous version.

So what I'm seeing here is that *you* didn't test *your* own software _before_ upgrading Composer on *your* prod server, and *your* server permissions don't allow *you* to rollback. Neither of those are anyone's responsibility except *your own*.

**Comment by yelojedi** [comment]
Looks more that the patches using the previous composer version applies fine but not with the composer version from yesterday. and that it has not been even tried from maintainers...
This error appears on patching now:
PATCHES.txt: failed to open stream: No such file or directory.

**Comment by naderman** [comment]
@GrahamCampbell @nealio82 @ahinkle @liam-wiltshire There's really no need for people to pile on here now and keep this issue including notifications going. Jordi said what needed to be said, the issue was resolved in the other ticket. Let's leave it at that.

@yelojedi hopefully you understood at this point that your way of communicating here was unhelpful and inappropriate.
