### ISSUE TITLE
How to prefer Composer Plugin versions that work both with Composer 1 and 2

### ISSUE THREAD

**Issue by mxr576** [composer/composer#9474]
We are in a transition between Composer 1 and 2. Some hosting providers do not support Composer 2 yet. It could also happen that team members are using different Composer versions locally (unfortunately it is still a thing in EOY of 2020).

Today I did a project update with Composer 2 and it upgraded https://packagist.org/packages/ergebnis/composer-normalize to 2.11.0 which _dropped_ Composer 1 support. I did not notice it until the build failed on the server which is still using Composer 1. 
2.9.0 from that package supports both soI rolled back to that version.

Is there a way, like a platform requirement or sth, which can be used to tell Composer 2 to prefer Composer plugin versions that support both plugin API?

**Comment by mxr576** [comment]
Related https://github.com/composer/composer/issues/9329

**Comment by Seldaek** [comment]
Not really, you can require v2 or v1 by putting a require on `composer-plugin-api` in your package which would force anyone installing it to use the version you want.. But it's not possible to say you want only packages supporting both.

That said, if hosting providers do not upgrade (if they are still on 1.9.0 I assume they're using some OS packages which will "never" get a more recent composer versions), you can also ship your own composer.phar in the git repo or install it somehow on the server, and install via that instead of relying on the OS one.

**Comment by mxr576** [comment]
>  But it's not possible to say you want only packages supporting both.

Yeah, I knew that :( 

> That said, if hosting providers do not upgrade (if they are still on 1.9.0 I assume they're using some OS packages which will "never" get a more recent composer versions), you can also ship your own composer.phar in the git repo or install it somehow on the server, and install via that instead of relying on the OS one.

That does not sound good. I mean it is not something that can work as a generic workaround, especially with on-prem customers who have their own build pipelines and their infra team is usually very careful with running external binaries or updating to newer versions. Of course, we are trying to push and use Composer 2 everywhere, but if we could figure out a solution that could solve it, I think it would be useful for everyone.

I also understand if maintainers would like to push everyone to upgrade Composer 2 so they can stop supporting Composer 1 completely.

**Comment by stof** [comment]
> I also understand if maintainers would like to push everyone to upgrade Composer 2 so they can stop supporting Composer 1 completely.

that's precisely the state of the project. And that's also why the LTS release supporting old PHP versions will be Composer 2.1, not Composer 1.10

**Comment by Seldaek** [comment]
@mxr576 Sorry but I don't see what we can do to help here. For on-prem IMO shipping docker containers with vendors already installed is the only sane way to deal with things, otherwise you're completely at their mercy and it adds tons of maintenance burden on both sides.

In the meantime, all you can do is pin plugins to versions compatible with both composer 1 and 2.

**Comment by mxr576** [comment]
No problem, thanks for sharing your insights so quickly.
