### ISSUE TITLE
Regression or overprotection

### ISSUE THREAD

**Issue by dereuromark** [composer/composer#9486]
I now get always

> [RuntimeException]                                                                                                                                                              
  Source directory /.../vendor/admad/cakephp-social-auth has unpushed changes on the current branch:   
  Branch docs could not be found on the origin remote and appears to be unpushed      

Same for a lot of other repos that I just pushed a test branch into a forked github repo.
Those are pushed however, so no stash or uncommited files. Completely clean.

In v1 this was fine then and it switched automatically back to the main branch here as defined in composer.
With v2 it seems now to also or only check the upstream (instead of the forked and linked own remote), and thus not finding this branch and aborting.
This is quite cumbersome if you are switching branches frequently for testing - and the current way does not offer any additional protection IMO, only makes it quite annoying having to switch back those repo branches on my own now.

Are we able to remove this overprotective here?
I get it if there are still changes open and so far I think this is already also covered by aborting.
So the above shouldn't be necessary and probably a regression as "and appears to be unpushed" is definitely not true.

**Comment by Seldaek** [comment]
Could you give me an example of what commands to run exactly in a package's dir to get it into this state?

**Comment by dereuromark** [comment]
OK, so created a branch on a required repo

cd vendor/org/repo-name && git create -b bugfix/foo-bar

Then you work on that and commit and push it to your own remote (adding new remote).
So the branch contains now no diff anymore, it just still points to the own remote instead of the upstream one.

Therefore now with composer v2 you need to manually reset every single branch back to the upsteam master, before v2 will allow you to continue.
The error "could not be found on the origin remote" indicates that it only checks this upstream remote.
It either needs to ignore a branch with a fully committed and pushed repo or also needs to check the remote on that own one.

**Comment by Seldaek** [comment]
Hmm yeah the assumption there I think is that people can change the url of the origin remote if they want, and leave the composer remote for composer. Adding your own remote means we now need to check all remotes present I guess, which is slower, but I'll have a look if it's fixable somehow.

**Comment by dereuromark** [comment]
It will only be slower in the rare case you have some extra. So most people will not even notice.

**Comment by Abdull** [comment]
I think I have the same problem with `Composer version 2.0.6 2020-11-07 11:21:17`:

In my TYPO3 composer-based setup, we have a TYPO3 composer "distribution" within which we also use our own TYPO3 composer extension. We are switching between development, test and master branches in both of these composer projects, and in my IDE I have imported the "nested but separate" extension git repository to edit around.

```
$ composer update
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 0 updates, 0 removals
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 25 updates, 0 removals
  - Syncing foo/bar (dev-test c0e3780) into cache

  [RuntimeException]
  Source directory C:\Users\Gerrit\git\gesis-web-dist\public\typo3conf\ext\gesis_web_ext has unpushed changes on the current branch:

[ ... list of files]
```

This never happened with composer 1.x, but happens since I switched to composer 2.

The error message `Source directory ... has unpushed changes on the current branch` is incorrect, all changes of the "nested" TYPO3 extention git repository are pushed.

The described workflow has previously worked well and was pragmatic and productive.

I'm happy to help out with testing fixes.

In the meantime, is there a workaround to ignore the error and force a syncing?

**Comment by dereuromark** [comment]
I found a working workaround to be: 
navigate to that vendor library, and `git checkout master` (or whatever is linked from your composer.json)
then to the update, then gith checkout back to the branch you were working on.

**Comment by Abdull** [comment]
> I found a working workaround to be:
> navigate to that vendor library, and `git checkout master` (or whatever is linked from your composer.json)
> then do the composer update, then gith checkout back to the branch you were working on.

@dereuromark, awesome - this workaround brought me on the right path and now `composer update` works again! Thanks.

Though in my case, I had to do it slightly different - doing it first like you suggested still caused aforementioned `RuntimeException`.

For the protocol, here is what I did and what happened:

```
# my environment:
# TYPO3_DISTRIBUTION_DIR = /var/www/typo3
# TYPO3_OUR_EXTENSION_DIR = /var/www/typo3/public/typo3conf/ext/bar
# <-- notice TYPO3 is a little special when it comes to vendor directory.

cd $TYPO3_OUR_EXTENSION_DIR
git checkout master
# extension git repository now on master

cd $TYPO3_DISTRIBUTION_DIR
composer update

# Loading composer repositories with package information
# Updating dependencies
# Lock file operations: 0 installs, 0 updates, 0 removals
# Installing dependencies from lock file (including require-dev)
# Package operations: 0 installs, 25 updates, 0 removals
#   - Syncing foo/bar (dev-test c0e3780) into cache
#
#
#  [RuntimeException]
#  Source directory $TYPO3_OUR_EXTENSION_DIR has unpushed changes on the current branch:
#
# ... ugh, still the same error ... let's not give up though ...

cd $TYPO3_OUR_EXTENSION_DIR
# push all the remotes!
git push --all origin
# Everything up-to-date

git push --all composer
# Everything up-to-date

# so, nothing seems to have changed... oh well, let's just run composer update one more time

cd $TYPO3_DISTRIBUTION_DIR
composer update
# Loading composer repositories with package information
# Updating dependencies
# Lock file operations: 0 installs, 0 updates, 0 removals
# Installing dependencies from lock file (including require-dev)
# Package operations: 0 installs, 25 updates, 0 removals
#   - Syncing foo/bar (dev-test c0e3780) into cache
#   - Upgrading foo/bar (dev-master 0e68034 => dev-test c0e3780): Checking out c0e3780ab9 from cache
#   - Upgrading typo3/cms-scheduler (v9.5.22 => v9.5.23): Extracting archive
# ... more upgradings
#
# oh wow, no RuntimeException anymore.
# oh wow, everything now works
```

So if I'm not delusional, `git push --all origin` and `git push --all composer`, i.e. pushing all remotes of my extension / dependency repaired something so that `composer update` worked again.

A possibly relevant extra information: A long time ago, just after the all-beginning `composer install`, I updated my extension's remote `origin` URL from https to ssh. Maybe such git changes within a composer project's dependency cause problems with composer 2.
