### ISSUE TITLE
Platform check error handling inappropriate

### ISSUE THREAD

**Issue by GregOriol** [composer/composer#9509]
The platform check script is very useful in its intent, but its handling of errors is kind of inappropriate currently.

Following a discussion that happened in https://github.com/composer/composer/pull/9418, I'd like to re-open the subject.

I do think that @jakubboucek in that discussion is right about fixing the display of errors: when developers specify `display_errors = Off` in their php configuration, they expect no display of technical errors at all, not even fatal ones.
However, currently composer's dumps its errors from the platform check (as argued for by @Seldaek).

For a very strong argument to change this, I'd like to say that when the display_errors value is Off, even PHP parse errors are not displayed, and they actually break everything even more than the platform checks.

The error is still logged in the current implementation by the trigger_error, so on the developer's side there is a way to find out what is happening from the logs, without dumping it to the user.

So I'd like to suggest that platform check only displays it's errors with echo if display_errors is On

**Comment by Seldaek** [comment]
What I have seen though is cases like a WP plugin being updated by an end user, leading to a blank page because the plugin had the platform check enabled and required a newer PHP version. If we don't output there, most end users administering WP blogs will likely be completely at a loss. I doubt they know how to check their php error log. Giving them some output to google for at least seems to be working, and they are helping each other and getting their php version upgraded.

What's your argument for hiding it?

**Comment by GregOriol** [comment]
@Seldaek As I said: when the setting is Off, even parse errors and fatal errors are not displayed; I do believe they are even more important than those from the platform check. So I believe platform check should follow the same behavior.

**Comment by Seldaek** [comment]
But an end user getting a parse error or fatal error affecting their entire WP install is very unlikely in normal operations. I don't know how you feel about leaving these users to fend for themselves without any clue what broke their site but I don't feel great about it.

**Comment by GregOriol** [comment]
Maybe make a composer config option to not display those errors? that way power users can change the behavior for their more advanced services/setups?

**Comment by Seldaek** [comment]
Power users should know better than to deploy stuff on the wrong platform, and can use `composer check-platform-reqs` as part of their deployment process to make sure nothing bad happens and there is never a need for a blank page, which really is an amateurish outcome.. If you do that correctly you can then completely disable the platform-check feature (with the config option of the same name), and skip the runtime check entirely.

**Comment by Seldaek** [comment]
The whole point of the feature is to avoid people ending up with a wrong version of dependencies on the wrong PHP, then reporting confusing issues to maintainers because stuff is breaking in subtle ways. So it should save maintainers and users time if the root cause is identifier quickly.

Power users are not the target audience.

**Comment by GregOriol** [comment]
Well, I do disagree strongly: power users need options to make their own choices; here you are forcing a behavior on them that is the default for composer and that is against their php settings!

Also `composer check-platform-reqs` tests the command line and not the web interface, which could be an entirely different setup.
