### ISSUE TITLE
Wrong dependencies resolution when using dev-branch + commit 

### ISSUE THREAD

**Issue by oleg-andreyev** [composer/composer#9547]
Installing proprietary package (sorry for a lot of images)

```
"<vendor>/<package>": "dev-branch#<revision> as 2.0"
``` 

Output of `composer diagnose`:

```
$ composer diagnose
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Composer version: 1.10.17
PHP version: 7.3.4
PHP binary path: /usr/bin/php
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017
```

**Problem:**
Composer is resolving dependencies against latest commit in dev-branch which caused a downgrade of another package (doctrine/dbal)
![image](https://user-images.githubusercontent.com/1244112/101192823-4e1bb400-3664-11eb-8430-7ec7cae42449.png)

![image](https://user-images.githubusercontent.com/1244112/101191756-c2555800-3662-11eb-95e2-b5bfa6012715.png)
![image](https://user-images.githubusercontent.com/1244112/101192062-2ed05700-3663-11eb-8c3b-5c8bc0f15b36.png)

Latest commit
![image](https://user-images.githubusercontent.com/1244112/101192254-7a830080-3663-11eb-9e54-7d67b0feebf8.png)

Specific commit version
![image](https://user-images.githubusercontent.com/1244112/101192185-60e1b900-3663-11eb-8bad-039ce20c08dc.png)

composer.lock in target project
![image](https://user-images.githubusercontent.com/1244112/101192394-ab633580-3663-11eb-810d-216b85edb5f3.png)

And I expected this to happen:
To resolve dependencies again specific commit.

**Comment by stof** [comment]
> To resolve dependencies again specific commit.

That's not possible (and the documentation of the feature documents that fact btw). Resolving against a particular commit would require that the solver can get the metadata about that particular commit. and that would imply that the metadata repository (packagist.org generally) exposes metadata for all commits rather than only for branches and tags. That would be an insane amount of data to store and transmit (and you would need a huge amount of memory to run the solver...)

**Comment by oleg-andreyev** [comment]
Found it.
https://getcomposer.org/doc/04-schema.md#package-links 

Thanks.
