### ISSUE TITLE
Feature request: Include upper bound PHP version check in runtime platform check

### ISSUE THREAD

**Issue by helhum** [composer/composer#9596]
The new runtime platform check in Composer is super useful.
However currently the upper bound PHP version isn't considered.

Is this on purpose, or would you accept a PR introducing it?

Thanks.

Could e.g. be useful to comminicate that some package isn't ready for PHP 8 yet.

**Comment by mbrodala** [comment]
Seems like this was intentional: https://github.com/composer/composer/commit/21e708f2c47a5c11b38d8b9d74fa7abe48419857

The change itself does unfortunately not have enough details about the potential issues.

**Comment by gilbertsoft** [comment]
I also can't see a current risk as long as the PHP constraint are defined correctly. Using the constraints defined (and tested) by the package maintainer should be more safe than assuming a higher version will work correctly. So IMHO it's more risky to not have the upper bound check here.

**Comment by gilbertsoft** [comment]
FYI the reason for this request was an issue we had last week with a TYPO3 v10 installation which currently only supports PHP < 8. Because this version isn't ready for PHP 8 there is currently an exception thrown about incompatible signatures which is not very helpful for the users. So we thought introducing a check here will be better for the users instead of having a not really meaningful excpetion.

**Comment by stof** [comment]
@gilbertsoft the runtime platform check feature of composer 2 is meant to catch mistakes happening when the requirements were resolved against a different runtime (the solver won't ignore these requirements).
The value added is to have a meaningful error rather than a parse error when a package uses a syntax supported only in a newer version (because your runtime is older than the lower bound of the resolved dependency). The opposite is happening a lot less (and the runtime check causes lots of heated discussion already).

If you want to be safe about the dependencies, the right solution is to resolve dependencies against the correct PHP version anyway (where all constraints are respected) rather than using a different version and relying on runtime checks (which are checking only a subset of the constraints for performance reason too)

**Comment by gilbertsoft** [comment]
@stof Thanks for your comment!

> the right solution is to resolve dependencies against the correct PHP version anyway

Yeah, we are aware of it and always tell the users to use the correct platform.php config of the server for the deployment.

The main problem here is we always recommend to use a proper deployment so if the platform.php isn't defined correctly the application will finally fail on the server. But the issue also exists on the dev platforms if the developer uses a wrong PHP version which was currently the case.

**Maybe it's possible to make this upper check optional / configurable?**

Here are the related patches for the TYPO3 Core where we're currently working on this issue, currently we do a lower bound check already in our entry scripts and we are discussing to introduce an upper bound check here too. For the v11 we would like to rely on the Composer functionallity:
- https://review.typo3.org/c/Packages/TYPO3.CMS/+/67365
- https://review.typo3.org/c/Packages/TYPO3.CMS/+/67371

**Comment by Seldaek** [comment]
IMO upper bound check is a bad idea, because it may mean that at some point some old software might be bricked due to a PHP upgrade because of this check, despite the fact that it may well work fine on that newer PHP version.

It's kinda like planned obsolescence. I understand it can reduce confusion in some cases, but it can also introduce roadblocks.

One alternative way IMO could be to wrap the whole app in a `try { ...  } catch(\Throwable $e) { if (PHP_VERSION_ID > 80100) { echo 'The following exception may be due to your PHP version being newer than what this software was tested with.'; } throw $e; }`. This offers a hint to people *if* something goes bad, but does not prevent execution because odds are things will work fine.

**Comment by gilbertsoft** [comment]
> ```
> try { ...  } 
> catch(\Throwable $e) {
>     if (PHP_VERSION_ID > 80100) {
>         echo 'The following exception may be due to your PHP version being newer than what this software was tested with.'; 
>     }
>     throw $e; 
> }
> ```
> 
> This offers a hint to people _if_ something goes bad, but does not prevent execution because odds are things will work fine.

Great suggestion, thanks!
