### ISSUE TITLE
Security - allow to specify hash with specific version and validate it during install

### ISSUE THREAD

**Issue by mvorisek** [composer/composer#9647]
When some package needs a small change and the maintainers do not want to merge it, a fork can be created. Like https://github.com/ProtonMail/sdk-core-php which provides support for PHP 7.4.

This fork can be easily used by:
```
"protonlabs/paypal-sdk-core-php": "3.4.1"
```

But as fork is provided by some random company, the company can modify the source and retag it with the `3.4.1` tag.

This is a feature request to implemente security feature in composer to be able to enforce specific hash with the following format:

```
"protonlabs/paypal-sdk-core-php": "3.4.1#73d7c19"
```

**Comment by Seldaek** [comment]
You can [require hashes](https://getcomposer.org/doc/04-schema.md#package-links) if you require dev versions, so `dev-php7.4#73d7c19 as 3.4.1` should work.

**Comment by mvorisek** [comment]
But this can not be used for a production due the minimum stability required.

**Comment by Seldaek** [comment]
It's pinned to a single commit, so it's about the same as using the tag. "can not be used for production" is a company policy issue, not a Composer issue.

Note that this feature is also root-package only, so the minimum-stability does not need to be changed as the dev-foo require will already mark that package as safe to use in stability dev (which, since it's pinned to a single exact version, is completely fine).
