### ISSUE TITLE
curl_multi_remove_handle isn't always called for all handles if an exception is thrown

### ISSUE THREAD

**Issue by naderman** [composer/composer#9655]
If the reject function of one of the curl downloader promises throws, the curl handles do not get cleaned up properly, this isn't much of an issue in composer CLI since php then exits and cleanup happens automatically, but it's problematic when using composer as part of a library or even inside a web request.

This can throw: https://github.com/composer/composer/blob/c800db04d31accad2ed219f5de3aff13f11c14dd/src/Composer/Util/HttpDownloader.php#L273

This probably needs an additional try catch which cleans up in catch and then rethrows: https://github.com/composer/composer/blob/c800db04d31accad2ed219f5de3aff13f11c14dd/src/Composer/Util/Http/CurlDownloader.php#L389

**Comment by Seldaek** [comment]
In short: Yes.

I think if the consumer of the promise calls `->then(x, y)` with a `y` (reject) present, then that will be called with the exception and if not rethrown then https://github.com/composer/composer/blob/c800db04d31accad2ed219f5de3aff13f11c14dd/src/Composer/Util/Http/CurlDownloader.php#L389 will not throw. Just to say it does not always throw AFAIK.

I guess looping over $this->jobs in CurlDownloader and calling `->abortRequest((int) $job['curlHandle'])` would be enough? Or do you see more?

**Comment by naderman** [comment]
> Just to say it does not always throw AFAIK.

Yes my point was rather that it is by design that this place may throw once in a while.

In general looping over the jobs and aborting the requests should do it as far as cleanup goes. But I'm actually unsure if that's always desired? Is there a situation where the function throws, and it is handled elsewhere and then the rest of the urls continue downloading? But if that isn't the case, your solution sounds good to me.

**Comment by Seldaek** [comment]
>  Is there a situation where the function throws, and it is handled elsewhere and then the rest of the urls continue downloading?

I don't *think* so.

**Comment by Seldaek** [comment]
Ok I had a look and I can not find a way to get a try/catch around https://github.com/composer/composer/blob/c800db04d31accad2ed219f5de3aff13f11c14dd/src/Composer/Util/Http/CurlDownloader.php#L389 to catch anything. I think it happens somehow later/out of band due to the promise mess, I am not sure tbh. 

The way I see it, either the throw isn't handled and it ends up crashing process/request and it doesn't matter, or the throw is handled upstream (like in some cases in Composer with a retry) and then it should not abort all other requests internally because the process is actually continuing just fine like that.

So I am not sure that there needs to be any change applied.
