### ISSUE TITLE
Cheap/fast alternative to "composer update --lock", to recalculate "content-hash" and more?

### ISSUE THREAD

**Issue by donquixote** [composer/composer#9677]
## Background / use case
I am working on a project where the composer.lock is tracked in git.
(typical for a website project)
To make it more interesting, 

I am doing `git rebase -ir) on a branch with multiple changes to composer.json and composer.lock.
Some of these commits are only adding new patches to existing packages.
When changing the order of commits that change composer.lock, conflicts naturally occur. Most often in the "content-hash" value, but also in other places ("patches_applied").

To resolve these conflicts, I usually run `composer update --lock`.
The goal is to recalculate the "content-hash", and update the "patches_applied" for different packages, while leaving the rest of composer.lock mostly unchanged.

_In this project I am stuck with composer 1 due to some older packages. But I already played with composer2, the same problem seems to still exist._

## Problem
`composer update --lock` can be quite slow.
`composer update --lock -vvv --profile` shows that it does a lot more than one would expect given the goal above:

- It reads the composer.json of every branch and tag in the private repository.
- It reads various provider-*.json files.
- It does the "Resolving dependencies through SAT", which can take quite long.
- It installs all the packages (see #8669, this seems already fixed)

This way, a rebase that should take a few seconds may now take 5 minutes, and "disrupt the flow".

It seems to me that a lot of this could be skipped, if all we want to do is update the hash or the patches.
But I could be wrong.

## Question / feature request
Is there a way to skip dependency resolution, if the current versions of everything in composer.lock already satisfy all requirements?
(This could be an option in `composer update`, or it could be a separate command.)

**Comment by stof** [comment]
Skipping dependency resolution is a no-go. It is necessary to run it to know that the requirements are satisfied.

Note that composer 2 should already be loading a lot less data than composer 1 as it will load metadata from composer repositories only for packages which are whitelisted for an update (which is none of them in `composer update --lock`).
For private repositories registered as VCS repositories, they will still be loaded by composer, because it cannot know what packages are inside them without doing the loading. The solution for that is to use a private composer repository to host the metadata of your private packages (which can then be loaded using the composer repository protocol when needed), with tools like [Private Packagist](https://packagist.com/) or [Satis](https://github.com/composer/satis). They will handle the processing of metadata from the private VCS repository instead of doing that in the project itself when running composer (similar to what packagist.org does for public packages).

And due to the optimization which load less data for partial updates, the "Resolving dependencies through SAT" step should also be faster in composer 2.

And regarding installing the packages, this is already solved in composer 2 as you linked.

So this gives you 2 ways to optimize things:
- to reduce the time loading metadata for your private VCS repository, use a composer repository exposing the metadata in the composer format (this helps also on composer 1)
- migrate to composer 2

Note that even if a new feature was implemented to solve more of this (which I find unlikely for now as creating a lock file without actually checking that it is a valid one would be quite fragile), it would only be available in Composer 2.x anyway. Composer 1.x is now closed for new features (only important bug fixes are done there until it is retired). So you should really migrate to composer 2.

**Comment by donquixote** [comment]
Thanks! Some useful tips here.
But I still have questions.

> Skipping dependency resolution is a no-go. It is necessary to run it to know that the requirements are satisfied.

Shouldn't an existing lock file already contain all the info needed to validate the requirements?
Every package entry in composer.lock has a "version" and a "require" section, and possibly more. So we would only need to combine all the "require" sections with the main "require" from composer.json, and check whether each package version satisfies the combined requirements.

If all requirements are satisfied, we are done. Calculate the hash and update the "patches_applied" section for each package, and finished. Or not?
If the requirements are not satisfied, then we can do the full dependency resolution.

If the info in composer.lock is not enough, perhaps the "source" and "dist" part could help to load only a specific part of the source repo, instead of checking every branch and tag.

(I don't find in composer.lock whether the "source" or "dist" was used for a specific package)

---------

I could imagine one scenario where this might not work: If the current composer.lock is already faulty, as the result of an unlocky merge resolution. E.g. the entry for a specific package could contain a mix of settings from different versions.

But this seems acceptable to me, if the skipping of dependency resolution is opt-in.

It might even be possible to verify the integrity of each package entry, if this is cached somewhere (per package name, version and source repo).

**Comment by stof** [comment]
Well, composer 2 will skip loading metadata from composer repositories for any package which is forced to stay in the locked version. As `composer update --lock` is locking all packages which are already in the lock file, this effectively disable all loading of metadata when relying on composer repositories.
For other types of repositories (VCS repositories, artifact repositories, etc...), composer cannot lazy-load the metadata, as it cannot communicate with these repositories by asking them for metadata for a given package name. That's why composer will load such repositories eagerly (the case where composer will not need to load any package at all was not specifically optimized, as that's a very special case).
That's where the usage of Private Packagist or Satis helps a lot: these tools are reading the metadata from the VCS repositories and exposing them as a composer repository (which can then be loaded in an optimized way in composer 2).

Note that composer 1 is implementing only the v1 format for composer repositories, not the v2 format, and so it will always load more data from these repositories than composer 2 (packagist.org, Private Packagist and latest Satis are all supporting both v1 and v2 formats). And it does not have the optimizations of partial updates either to skip loading metadata for locked packages.

> If all requirements are satisfied, we are done.

Running the solver is precisely what tells us that the requirements are satisfied (without inventing a new way of deciding what "satisfied" means, as your proposal of combining requirements is not simple at all if you want to guarantee that the result is equivalent).

**Comment by donquixote** [comment]
> For other types of repositories (VCS repositories, artifact repositories, etc...), composer cannot lazy-load the metadata

Is the per-package metadata that is already in the lock file not enough?
Is there additional metadata that we can only get from the repo?

> the case where composer will not need to load any package at all was not specifically optimized, as that's a very special case

For me, `composer update --lock` is the most frequently used and repeated command..
Do others not do this?

> That's where the usage of Private Packagist or Satis helps a lot
Right. I will look into this.

> your proposal of combining requirements is not simple at all if you want to guarantee that the result is equivalent
Perhaps there is some detail that I am missing.

But the basic idea seems simple:
We compare the existing package version to every version requirement string from dependees. E.g. if packages A, B and C each require package Z, but with different version requirement strings, then we check the existing version of Z to each of the requirements specified in A, B and C separately, and return false if any one of them does not match.
The idea with "combined requirement" was to optimize and reduce redundancy, but actually this is not needed at all.

Isn't this what already happens in a single iteration of the "full" resolver?

**Comment by stof** [comment]
> Is the per-package metadata that is already in the lock file not enough?
> Is there additional metadata that we can only get from the repo?

As I said, we *could* implement an optimization of the loading of the metadata for the case where all packages are locked to their existing version and all of them are in the lock file already (i.e. the `composer update --lock` case where no packages are missing in the lock file). But I don't know how easy such implementation would be in the current architecture of Composer 2 (for Composer 1, this is a no-go anyway as this part of the architecture was a mess, even without taking into account the fact that any refactoring is now a no-go).
And as soon as 1 package is missing in the lock file, we would still have to initialize all the VCS repositories, cancelling that optimization.

> For me, `composer update --lock` is the most frequently used and repeated command..
> Do others not do this?

I actually use this command quite rarely. But most of my rebases don't need to deal with any changes in the composer.json file as it changes much less often than my own code.

> But the basic idea seems simple:

Add into the mix all the rules about `provide`, `conflict` and `replace`, and you'll see that this is not that simple. You would end up doing again what the solver does.
And when passing it an optimized set of packages containing only one version for each locked package (which is what happens in Composer 2), the solver will be quite fast anyway (as it does not need to examine alternative combinations to find a solution or to fail).

**Comment by donquixote** [comment]
@stof 

> we could implement an optimization of the loading of the metadata for the case where all packages are locked to their existing version

> Add into the mix all the rules about provide, conflict and replace, and you'll see that this is not that simple. You would end up doing again what the solver does.

Ok, good to know. Who knows perhaps some day I find time to look deeper into this.

> And as soon as 1 package is missing in the lock file, we would still have to initialize all the VCS repositories, cancelling that optimization.

This is fine. In the most common case, git conflict resolution already leaves the composer.lock in an almost-perfect state, it only needs an updated hash and patches_applied.
Of course I do have to manually edit the composer.lock to become _readable_ (e.g. by accepting one of the conflicting hashes), before running `composer update --lock` - but that is fine.

> most of my rebases don't need to deal with any changes in the composer.json file as it changes much less often than my own code.

I think it depends on the type of project.
I typically work on Drupal 8 website projects with lots of modules and packages. It is quite common in a single pull request for a bug or feature to update, add or patch one or more modules.

**Comment by Seldaek** [comment]
I don't really think there is anything to fix here.. It's a workflow thing, which Composer 2 already improves a lot, so make sure you upgrade when possible.

**Comment by Berdir** [comment]
>  Some of these commits are only adding new patches to existing packages.

The composer-patches package supports providing a separate composer.patches.json file, that then no longer affects the content-hash and you can update that without having to run composer update/composer.lock changes.
