### ISSUE TITLE
got problem when install this library is to rely on Composer

### ISSUE THREAD

**Issue by keason** [composer/composer#9738]
got problem when install this library is to rely on Composer
	- composer require spomky-labs/jose
![image](https://user-images.githubusercontent.com/8910112/109474607-a7528280-7aaf-11eb-8071-b56b7a13c643.png)
, :

**Comment by stof** [comment]
Composer is selecting the 0.1.0 release (probably because newer releases are saying they don't support PHP 8), which depends on spomky-labs/jose-interface for which the github repository has been removed. this release is from 2015 and should probably not be used anymore.
Anyway, this is not a bug in composer.

**Comment by Seldaek** [comment]
FWIW, the readme from spomky-labs/jose advises using [web-token/jwt-framework](https://packagist.org/packages/web-token/jwt-framework) instead as the jose package is abandoned.
