### ISSUE TITLE
Dev dependency should not be installed to satisfy virtual package when --no-dev is used

### ISSUE THREAD

**Issue by samdark** [composer/composer#9799]
## To reproduce the issue

1. Clone https://github.com/peesoft/package-user
2. `composer update --no-dev`.
3. `testsoft/package-test-support` while I expect error to be issued.

## Details

```json
{
    "name": "testsoft/package-user",
    "description": "User application",
    "type": "project",
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "php": "^7.4|^8.0",
        "testsoft/package-interface": "dev-master@dev",
        "testsoft/package-vitual-interface": "1.0.0"
    },
    "require-dev": {
        "testsoft/package-test-support": "dev-master@dev"
    },
    "autoload": {
        "psr-4": {
            "Testsofr\\PackageUser\\": "src"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "TestSoft\\PackageUser\\Tests": "tests"
        }
    }
}
```

`testsoft/package-test-support` provides  `testsoft/package-interface` but it is a dev dependency that should be ignored when `--no-dev` is used.

**Comment by Seldaek** [comment]
All dependencies are resolved as one exactly to prevent this kind of issue, where a dev requirement would provide something, and thus --no-dev output would be inconsistent with complete output. The update process then splits packages in dev/non-dev ones by running an update without the require-dev present, to see which become uninstalled. As your require-dev package provides something from require, it does not get uninstalled and thus is considered to be a non-dev requirement in the lock file.

If we did fix this, you could not resolve such a package's dependencies at all, which IMO is not great as it would prevent developing packages which depend on an abstract implementation like this.

It is a good thing that you can use require-dev to pull in a valid implementation for `testsoft/package-vitual-interface` - and that lets you run the test suite etc for testsoft/package-user. Now if testsoft/package-user gets installed as a dependency however, the person requiring it will also have to require an implementation like testsoft/package-test-support to satisfy the dependencies fully.

The alternative would mean you'd have to move the `testsoft/package-test-support` requirement to `require`, and that would then make your package depend on a concrete implementation instead of just depending on the interface.

I hope this clarifies things. I realize this is kinda abstract stuff.

**Comment by samdark** [comment]
That clarifies about why it does work this way but that's not what I'd logically expect from virtual packages.

The case we have is the following:

1. There is a vitual package such as https://packagist.org/providers/psr/simple-cache-implementation.
2. We also have two implementations: one is for real production use (https://github.com/yiisoft/cache-file) and another provides a mock for testing PSR interfaces (https://github.com/yiisoft/test-support).
3. In the `test-support` package we can either provide virtual package like in thie PR: https://github.com/yiisoft/test-support/pull/30 or not provide virtual package at all. Both ways aren't perfect:
  - If we provide a vitual package in `test-support` and `test-support` in `require-dev` to run tests in a project (root package), then the it won't tell warn us anymore if real cache implementation should be installed (and that's the goal of virtual packages, right?).
  - If we don't provide virtual package in `test-support` then the root package will warn us well but we'll have to install real package just to satisfy requirements and then use just stubs from `test-support` if we are testing a non-root package.

**Comment by samdark** [comment]
> If we did fix this, you could not resolve such a package's dependencies at all, which IMO is not great as it would prevent developing packages which depend on an abstract implementation like this.

Why? If I develop a package and it has a dev dependency in require-dev then it will be satisfied during development and won't be satisfied with `--no-dev`.

**Comment by Seldaek** [comment]
Too late and tired, can't explain, maybe @naderman feels like doing it, but the point is we can not do this without screwing up other stuff/use cases.

**Comment by samdark** [comment]
OK :(
