### ISSUE TITLE
Linux-unsuited file name "why-can't-composer-load-repositories-recursively.md"

### ISSUE THREAD

**Issue by jschleus** [composer/composer#9802]
Only a very "small" issue: A file name like `doc/faqs/why-can't-composer-load-repositories-recursively.md` (containing an apostrophe) can be problematic e.g. on Linux systems. Although it may principally "allowed" it seems to be poor  practice  on any Linux/UNIX box. So why not just omit the apostrophe?

**Comment by stof** [comment]
Renaming this file would first require implementing a solution for doc redirections in https://github.com/composer/getcomposer.org (maybe hardcoding it in https://github.com/composer/getcomposer.org/blob/95d11ed947f602b5a5f83f80c062e134d62c9f4b/src/Controller/DocsController.php#L74-L84 like previous moves would be enough). Otherwise, this will break existing links as the doc URL depends on the file name.

**Comment by Seldaek** [comment]
Yeah this is frankly not worth the trouble IMO. The apostrophe is only problematic if you are trying to refer to the file and quote it incorrectly or such.. As it's a doc file which is just sitting there, I doubt it causes much real harm?

**Comment by jschleus** [comment]
Okay, I didn't expect side effects. The filename is on the Linux command line e.g. for commands like "less" or "pandoc" not directly usable but quoting it or use filename completion (that escaped the apostrophe) would help. I found according problems on my own FOSS server but you are right, it's behavior must be improved.
