### ISSUE TITLE
Circular call to script handler 'post-file-download' detected

### ISSUE THREAD

**Issue by phenaproxima** [composer/composer#9846]
I have an under-development plugin to marry Composer to [PHP-TUF](https://github.com/php-tuf/php-tuf): https://github.com/php-tuf/composer-integration.

Right now, it works nicely in a little local sandbox project I've got set up. However, there's an error that gets raised when requiring a project and downloading dependencies: 

```
Failed to download vendor/package from dist: Circular call to script handler 'post-file-download' detected
    Now trying to download from source
```

What does this mean? Why is Composer producing this error? My plugin is not, as far as I know, calling anything in a circular fashion -- it's all very straightforward. The event handlers are located in https://github.com/php-tuf/composer-integration/blob/main/src/Plugin.php.

As far as I can tell, the exception is raised by EventDispatcher::pushEvent() if it is already handling an event with the same name. But how does this square with the idea of downloading multiple files at once, which might trigger post-file-download events? Composer does plenty of async file downloading. Is there anything I can do to prevent or mitigate these scary-looking exceptions?

**Comment by staabm** [comment]
Some steps to reproduce the issue would be helfpul

**Comment by Seldaek** [comment]
So I guess the problem is the "native" downloads done by Composer are each triggering post-file-download events but they are doing so on top of the stack. While you may be doing downloads and thus triggering post-file-download events from within a post-file-download event handler? Is that the case?

I tend to agree post-file-download may need to be excluded from this circular call detection anyway, I doubt this is a real problem in practice. This was added to detect other cases where people did silly things resulting in endless loops.

**Comment by phenaproxima** [comment]
> While you may be doing downloads and thus triggering post-file-download events from within a post-file-download event handler? Is that the case?

Well, that's exactly what's weird: we are NOT triggering any downloads within our post-file-download event handler. In fact, we are not triggering downloads through Composer _at all_ -- our plugin is only ever reacting to existing pre- and post-download events. The PHP-TUF library does download some metadata of its own, but that happens in its own subsystem that doesn't fire any events at all and is totally divorced from Composer's download mechanisms.

Another data point here is that I don't see these "circular call" errors consistently. Sometimes I do, other times I don't. I'm wondering if it is not a preexisting problem, caused by the fact that the HttpDownloader _will_ try to download things asynchronously if it can, but AFAICT the event dispatcher doesn't really seem to understand that several of the same event could be handled simultaneously. Maybe this is something that would be exposed by _any_ plugin which reacts to post-download events, but since it doesn't halt the entire application (just triggers a warning), it has never been reported or dealt with?

**Comment by phenaproxima** [comment]
If it turns out to be the case that the event dispatcher is simply naïve about stacked events, then maybe one solution that might make sense is for it to maintain some internal configuration about which events are allowed to be stacked, and what the stacking limitations are. For example, we could add something which says that the event dispatcher can allow up to 10 simultaneous post-download events before it raises an error.

**Comment by Seldaek** [comment]
@phenaproxima Could you maybe make a composer.json that lets me reproduce this? Because looking at the code now I really do not see how this can happen if you're not triggering downloads from a listener.. I'd need to look at the stack trace.

Alternatively you can try to add a `throw $e;` on top of this function https://github.com/composer/composer/blob/a04202aa7d43e6701a68e759bc491b56007e50d8/src/Composer/Downloader/DownloadManager.php#L205

To make sure you get to see the exception trace (need to run with `-v` too), and paste that here maybe it'll be enough.

**Comment by phenaproxima** [comment]
> Could you maybe make a composer.json that lets me reproduce this?

That might be a bit tricky. Let me see if I can reproduce this locally and get you a stack trace.

**Comment by phenaproxima** [comment]
@Seldaek, I actually just encountered this with the pre-file-download event, and I traced through it and found a major clue.

ComposerRepository has logic which will try to download metadata files a few times (i.e., if the first attempt fails, we retry several times). So here's what happens:

* On the first attempt, everything is fine -- we fire a pre-file download event, and it goes into the event stack as per usual.
* For whatever reason, during the course of the operation, an exception is thrown...but it's NOT a transport exception. Instead, the exception is some non-Composer exception thrown by a pre-file-download event handler.
* ComposerRepository will catch the exception and, seeing that it doesn't match any known exception type, will just decrement the retry counter and try again.
* Upon retry, the pre-file download event is dispatched again. The event stack now has two pre-file download events in it, and throws a RuntimeException.

So! I think a solution to this problem is for us to ensure that the pre- and post-file download events are dispatched OUTSIDE of any retry loops.

**Comment by phenaproxima** [comment]
A workaround I can implement in php-tuf/composer-plugin for now is to ensure that exceptions thrown by my event handlers are `\LogicException`, which will immediately get re-thrown by Composer.

**Comment by Seldaek** [comment]
Ok that is interesting, pre-file-download tho not post-file-download. IMO they should be dispatched every single time as the event listener might be doing some modifications which are essential to the download. 

See https://github.com/composer/composer/commit/37f4f531d0c99cb224076d2ae22490a2bba978b8 which I believe fixes the root cause.. it'd be good if you can try with latest snapshot.
