### ISSUE TITLE
composer `update` w/ `--no-dev` checks dev packages platform requirements

### ISSUE THREAD

**Issue by ktomk** [composer/composer#9869]
As noted in https://github.com/composer/composer/issues/7314#issuecomment-416132989 `composer install --no-dev` takes the requirements of the development packages into consideration and

> This could lead to somewhat confusing scenarios

which I just had in a CI situation, thankfully there is a message hinting this potential culprit:

```
$ composer update --no-dev --no-plugins --no-scripts --no-progress \
    --prefer-dist
[...]
Running update with --no-dev does not mean require-dev is ignored, it just
means the packages will not be installed. If dev requirements are blocking
the update you have to resolve those problems.
```

As this is easy to work-around (run `update --no-dev` with `--ignore-platform-reqs` and then `install --no-dev`), this issue is not biting me too much but I'm curious if this would be considered a thing a) worth to address for composer e.g. open for accepting a PR on this and b) feasible to address (like a good first issue or similar, e.g. complexity factor).

It would be the `update` counter-part to the #7314 changes in `check-platform-reqs` command.

(report/workaround is against composer 1.10.22 and 2.0.13)

**Comment by Seldaek** [comment]
It's not going to be addressed. We have to resolve all dependencies at once otherwise the lock file can not be guaranteed to be correct and that's just not something we want to do.

Not sure what your suggested fix would be, but I don't think doing an update with --ignore-platform-reqs is a great solution generally speaking. It might get you out of a pickle and it's a great option to have, but I wouldn't make this a generalized solution as it can also lead to installing invalid dependencies. The solution is fixing the requirements/platform so that it updates correctly.
