### ISSUE TITLE
Question: has anything changed in the way composer generates binaries?

### ISSUE THREAD

**Issue by DocFX** [composer/composer#9871]
Hello,

Recently a non-backwards compatible change seems to be made from composer + php-cs-fixer repo: composer generates upon install command Unix + Windows binaries in the bin directory of current composer installation (global or local). Default is `vendor/bin`.

There used to be a PHP script generated by composer install for php-cs-fixer in that directory, now there's none anymore. There are a Unix shell and a Windows shell batch files now only.

I'm calling php-cs-fixer through a path-specific PHP executable (on Windows, by the way) on a machine that has several PHP binaries.

So I was doing something like:

`"path/to/php.exe" "path/to/vendor/bin/php-cs-fixer" fix [options]`

This script used to be PHP, now it's plain Unix script. So I updated the scripts with:

`"path/to/php.exe" "path/to/vendor/bin/friendsofphp/php-cs-fixer" fix [options]`

Question: is this sustainable, and the best way to do so? (I can also call it from containers, which is another story ^^)

(originally posted [here](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5700))

**Comment by Seldaek** [comment]
What composer version are you running? You seem to be describing the old behavior, which we fixed in 2.0.10 to generate a php script exactly to support the use case you are referring to (custom php executable running vendor/bin/x).

You can find the latest code here https://github.com/composer/composer/blob/649087d6de158dc4da73a06c7759dec5932be5a5/src/Composer/Installer/BinaryInstaller.php#L187-L255 if it helps..

**Comment by DocFX** [comment]
Oh yeah! That's what I encountered! We're running the latest version now, I was just curious! 

As usual, many thanks, @Seldaek! You rock, as you always do! \o/
