### ISSUE TITLE
Increase PHPStan level

### ISSUE THREAD

**Issue by Seldaek** [composer/composer#9964]
Need to see what level is reasonable given 5.3 support, but would be good to do before forking the codebase long term for higher php version support.

Also add https://github.com/phpstan/phpstan-deprecation-rules

**Comment by stof** [comment]
In other projects, I successfully use the max level (with a baseline for some legacy parts of the code that are totally crappy) with PHP 5.6+. phpstan cares about getting the right type information. But as it supports providing it in phpdoc rather than in native types, there is generally no big issues related to older PHP versions (the issues appear when the PHP API changes between major versions)

**Comment by villfa** [comment]
Also consider https://github.com/phpstan/phpstan-strict-rules

As seen recently, some type of bugs can only be detected by them: https://github.com/composer/composer/commit/128a2648fb47a34a52f1ba9d7c31453794c56e19
